### ISSUE TITLE
Please run Atom command 'Atom-Beautify: Migrate Settings'. You have unsupported options: _analyticsUserId

### ISSUE THREAD

**Issue by funk77** [Glavin001/atom-beautify#1001]
Please run Atom command 'Atom-Beautify: Migrate Settings'.
You have unsupported options: _analyticsUserId
how 2 cure?

**Comment by Glavin001** [comment]
Did you successfully run the `Atom-Beautify: Migrate Settings` command?
If no, then duplicate of https://github.com/Glavin001/atom-beautify/issues/936

**Comment by funk77** [comment]
ty, ctrl+alt+p - cure ;)

2016-06-01 22:37 GMT+03:00 Glavin Wiechert <notifications@github.com>:
