### ISSUE TITLE
Beautify add quotes to value of url() stops less variable being parsed

### ISSUE THREAD

**Issue by Ariex** [Glavin001/atom-beautify#1002]
### Description

When formatting the less code, beautify add a double-quote for the value in url(), even its value is a variable. Which the double-quote just disabled the variable from parsing by less compiler (client side less.js).
`Source`:

```
@var1: "/images/image1.jpg";
.a{
    background: url(@var1) no-repeat 0 0 scroll transparent;
}
```

formatted to

```
@var1: "/images/image1.jpg";
.a{
    background: url("@var1") no-repeat 0 0 scroll transparent;
}
```
### Expected Results

Only add quotes to non-less variable, simply not starts with a `@`
like below

```
@var1: "/images/image1.jpg";
.a{
    background: url(@var1) no-repeat 0 0 scroll transparent;
}
```
### Steps to Reproduce
1. Create a less file using the `Source`
2. Open in Atom.io
3. Run command `Atom Beautify: Beautify Editor`
4. Then you get the variable around with `"`;

**Comment by prettydiff** [comment]
I can confirm this is a Pretty Diff defect.  I suspect this will be fairly quick and simple to resolve.  I am wrapping up attendance at a military school right now and will work on it when I return home this weekend.
