### ISSUE TITLE
for xml, if element value is end with white space, white space is replaced with a new_line character

### ISSUE THREAD

**Issue by feitian124** [Glavin001/atom-beautify#1003]
### Description

for xml, if element value is end with white space, white space is replaced with a new_line character, which lead to the element closed in the next line.

The beautified code should have looked like:

``` xml
<EndWithBlank>abc  </EndWithBlank>
```

but the result is:

``` xml
<EndWithBlank>abc
</EndWithBlank>
```

**Comment by prettydiff** [comment]
This is the intended behavior.  Is it causing any problems?

**Comment by feitian124** [comment]
yes. 

usually we should keep the element value exactly same, including the blanks. the above behavior lead to the value changed. 

it is better to start a new line after where xml element pairs closed.

**Comment by prettydiff** [comment]
I don't remember if Atom Beautify is supporting the Pretty Diff option `textpreserve`.  I don't have Atom installed on this military computer and am away from home right now, but that option is exactly what you need.

You can play around with it at http://prettydiff.com

**Comment by feitian124** [comment]
i will have a look, thanks
