### ISSUE TITLE
Please update js-beautify to 1.6.3

### ISSUE THREAD

**Issue by NerdPad** [Glavin001/atom-beautify#1005]
Please update js-beautify to 1.6.3.

A new option for [operator position](https://github.com/beautify-web/js-beautify/pull/735) has been added, I have been waiting for this to be merged for so long :)

Also, is there a way to tell atom-beautify to use the globally installed js-beautify instance rather than the local one?

**Comment by prettydiff** [comment]
@NerdPad Does JS Beautify not automatically update to the latest version if your reinstall Atom Beautify?

**Comment by Glavin001** [comment]
Uninstalling and reinstalling Atom-Beautify should trigger a fresh install of the latest versions of the dependencies, such as js-beautify. If not, let us know!

**Comment by NerdPad** [comment]
Yup, I did that. But adding an option for operator position in the settings would be helpful.

**Comment by Glavin001** [comment]
> adding an option for operator position in the settings

That'd be great! Take a look at https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md and many other Pull Requests and submit your own implementing this feature. Thanks!
