### ISSUE TITLE
PHP Beautify Indent Issue

### ISSUE THREAD

**Issue by captainrugged** [Glavin001/atom-beautify#1013]
### Description

The results of beautification of indents are always 4 spaces and whatever I set in .jsbeautifyrc does not have any effect. The same happens also with my xml files that I try to beautify.
### Expected Results

The beautified code should have looked like:
1 tab equals 6 spaces

```
if ($portalId != 0) {
      require_once APP_ROOT.'inc/init/config_portal.php';
      foreach ($portal_schulen as $school) {
            if ($school['id'] == $portalId) {
                  $config_file = $school['config'];
            }
      }
}
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
### Debug

https://gist.github.com/captainrugged/c5deff50a8d06c9beaa765c2b3d5e4ab

Thanks for your help guys

**Comment by captainrugged** [comment]
Hej Guys,

is there anything that I can do to to fix the issue for me?

Thanks in advance

**Comment by Glavin001** [comment]
Looking at https://gist.github.com/captainrugged/c5deff50a8d06c9beaa765c2b3d5e4ab#final-options I see `indent_size: 6`.
Then above, in `Project Options` section I again see:

```javascript
{
        "php": {
            "indent_size": 6,
            ...
        }
    }
```

This shows the options stored in `.jsbeautifyrc` within `/htdocs/webfalter/sws/api` directory and up to the root directory.
I recommend you look again and confirm that your `.jsbeautifyrc` is correct with `indent_size: 4` (desired?).

**Comment by captainrugged** [comment]
thanks so much for your response.

I just checked again and my jsbeautifyrc says   "indent_size": 6 & "indent_with_tabs": true.

The beautified result should be one tab represented by 6 spaces but I always (whatever I configure in jsbeautifyrc) get 4 spaces as an indent (not with tabs).

**Comment by Glavin001** [comment]
Could you re-generate the `debug.md`. The final options should show `indent_size: 4`, as you described. And then we can diagnose where that is coming from.
