### ISSUE TITLE
can not find path

### ISSUE THREAD

**Issue by aicochow** [Glavin001/atom-beautify#1019]
when I run `where sqlformat`,can not find path.
when I run `where sqlparse` ,I can find the path.

**Comment by prettydiff** [comment]
Would you mind pasting a gist of the debug.md file?  This way we can see if there is a faulty configuration or missing dependency.

**Comment by aicochow** [comment]
@prettydiff sorry,I can not

**Comment by vmuriart** [comment]
@prettydiff I think this may be related to https://github.com/Glavin001/atom-beautify/issues/456 .
`sqlparse`/`sqlformat` currently doesn't have Windows support from `cli`. The next release will include a windows entry point. 

Even after that change though, `sqlformat` is still erroring out on `atom-beautify`. #456 has some of the early troubleshooting and `HACK` we did to get it to work back then.

**Comment by vmuriart** [comment]
@aicochow, out of curiosity what fixed the issue? 
Did you just update to the development version of `sqlparse` and it worked right after that?
