### ISSUE TITLE
Executable not found on windows

### ISSUE THREAD

**Issue by go2sh** [Glavin001/atom-beautify#1022]
### Description

Beautifier reports that the executable is not found though the PATH is set up correctly.

### Expected Results

Beautifier is executed properly

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. atom-beatify reports exe not found

### Debug

I checked the process.env variable. It contains too PATH entries. One is named "Path" as windows expects it and one is named "PATH". This second one is actually used by spawn. The second one looks like:
`"C:\Python35;;/usr/local/bin;/usr/bin;/bin;/usr/sbin;/sbin"`

The issue can be soleved by adding:
```
if process.env.PATH?
  delete process.env.PATH
```
I do not know, where this is comming from. My environment in Windows is clean. It has to be added by atom somewhere.... Pretty annoying. You might add the fix to the `getShellEnvironment` function to add a work around.

**Comment by prettydiff** [comment]
Which language are you trying to beautify?  It could be a problem in a beautifier.

**Comment by go2sh** [comment]
Sorry, not a problem of atom-beautify. Traced it done to python-tools. See MichaelAquilina/python-tools#48. Closing it.
