### ISSUE TITLE
Installing “atom-beautify@0.29.8” on Ubuntu 16.04 failed

### ISSUE THREAD

**Issue by valorloff** [Glavin001/atom-beautify#1028]
### Description
Installing “atom-beautify@0.29.8” failed. 
(
Ubuntu 16.04
npm -v  // 3.9.6
node -v // v4.4.3
)

> atom-beautify@0.29.8 postinstall /tmp/apm-install-dir-116522-12883-1318sbu/node_modules/atom-beautify
> node script/build-options.js

npm WARN engine analytics-node@2.1.0: wanted: {"node":">= 0.12.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine typescript-formatter@2.2.0: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-116522-12883-1318sbu/node_modules/atom-beautify/script/build-options.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "/tmp/d-116522-12883-yqk3cg/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.8 postinstall: `node script/build-options.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.8 postinstall script 'node script/build-options.js'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/build-options.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116522-12883-1318sbu/npm-debug.log

**Comment by hoseong613** [comment]
I have the same problem. Installed node and atom from the deb files and all are updated. I even checked the /tmp dir and was 777. ubuntu 16.04 node 4.4.5 npm 2.15.5 atom 1.8.0 .

**Comment by prettydiff** [comment]
If the problem is missing dependencies try `apm install atom-beautify` from the console and see if that helps.

**Comment by hoseong613** [comment]
Tried it already. Exactly the same error page.

**Comment by valorloff** [comment]
apm install atom-beautify also tried,
throw just same error output, but in Ubuntu console

2016-06-23 14:39 GMT+03:00 James <notifications@github.com>:

> Tried it already. Exactly the same error page.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Glavin001/atom-beautify/issues/1028#issuecomment-228024077>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASmbZ0slRHQGId1DnG6Ct7n3kgZRvZqCks5qOnBZgaJpZM4I7wO5>
> .
>



-- 
-- 
С уважением, Dostavka.net.ua
ваш надежный партнер
--------------------------------------
+3 (8-050) 323-76-64 MTC
ICQ 290462045, Hangouts
--------------------------------------

**Comment by Glavin001** [comment]
> /tmp/apm-install-dir-116522-12883-1318sbu/node_modules/atom-beautify
node script/build-options.js
> Error: Cannot find module '/tmp/apm-install-dir-116522-12883-1318sbu/node_modules/atom-beautify/script/build-options.js'

Has someone checked the contents of that directory? `'/tmp/apm-install-dir-116522-12883-1318sbu/node_modules/atom-beautify/`
There should be a script `build-options.js` in `atom-beautify/scripts`: https://github.com/Glavin001/atom-beautify/blob/master/script/build-options.js

Also, your versions do not match:
```
(
Ubuntu 16.04
npm -v // 3.9.6
node -v // v4.4.3
)
```
and from the logs
```
npm ERR! node v0.10.40
npm ERR! npm v2.13.3
```

Travis CI is passing: https://travis-ci.org/Glavin001/atom-beautify
So there must be something about your individual installations that are causing these issues.
However, I want to resolve this. So please provide more information so I can try to help you debug this issue.

I also highly recommend that you post an issue over at https://github.com/atom/apm and see if they can make sense of your installation, why your Node/npm versions are different, and why running `node SOME_SCRIPT.js` would fail given that they do the same: https://github.com/atom/apm/blob/master/package.json#L20
Please post here when you make the issue over at `atom/apm` so there is not duplicate issues and others can go to that Issue and comment.
Thank you.

**Comment by Glavin001** [comment]
I found https://github.com/atom/apm/issues/548#issuecomment-214510076
which mentions that:
> `apm` uses Node 0.10.40 internally - we haven't managed to update it yet.

So that explains the versions being different.

And also https://github.com/Glavin001/atom-beautify/issues/947#issuecomment-214963510 which may be helpful as it relates to cleaning up a dirty temporary directory that was causing problems.
Hope that helps!

**Comment by hoseong613** [comment]
I have been doing some research and found out that it wasn't the plugin problem. I think it has got to do with apm or versions of node and npm. I get the same errors with other plugins.

**Comment by suulnnka** [comment]
wait https://github.com/atom/atom/pull/11897/
