### ISSUE TITLE
Unable to set 0 to Wrap line length in XML formatter options

### ISSUE THREAD

**Issue by ziacik** [Glavin001/atom-beautify#1029]
### Description

Unable to set zero value to Wrap line length in XML formatter options

### Expected Results

Wrap line length option set to 0. (Is instead reverted to default value which is 250.)

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I believe Pretty Diff is the default beautifier for XML, so I can probably help.  Would you mind producing the debug.md and pasting it into a gist?  This really helps us to see if there is a conflict in the options and reproduce the problem.

A setting of 0 means to ignore the option. http://prettydiff.com/documentation.xhtml#wrap

**Comment by ziacik** [comment]
I'm sorry for not being clear enough. The issue doesn't involve the beautifier, it is a problem with the Settings of the package in Atom editor. Might be related to the Atom editor itself, I'm not sure. I'm including an image to demonstrate.


![atom-beautifier](https://cloud.githubusercontent.com/assets/4528506/16341765/162e29c8-3a2f-11e6-9c4c-fabb84ec4810.gif)

**Comment by Glavin001** [comment]
It is a bug with atom/settings-view: https://github.com/atom/settings-view/issues/783
