### ISSUE TITLE
阿里巴巴开源了we跨三端动态化方案

### ISSUE THREAD

**Issue by walid1992** [Glavin001/atom-beautify#1032]
希望支持.we文件，谢谢

**Comment by prettydiff** [comment]
I am having trouble understanding. Are you requesting support for certain languages or file types?

**Comment by Glavin001** [comment]
Google Translate results:

> Alibaba we open a three-terminal cross- dynamic scheme
> .we Want to support document , thank you

Not great...

@walid1992 please translate to English so we can help support your request. Thank you.
