### ISSUE TITLE
希望可以添加weex项目的we文件代码格式化支持

### ISSUE THREAD

**Issue by zct1989** [Glavin001/atom-beautify#1033]

**Comment by Glavin001** [comment]
Please translate to English before creating Issues, since that is the language of our current contributors. Thank you.

Google Translate result:
> I hope we can add weex project file code formatting support

Please also provide a sample code and a link to documentation on the language.

**Comment by prettydiff** [comment]
https://alibaba.github.io/weex/

Looks like it is probably already supported.  The code looks like XML with HTML style and script tags.  We would just need to add the `.weex` extension and grammar name to the xml.coffee file.
