### ISSUE TITLE
Beautifier Option Comparison Documentation

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#1039]
Automatically generate additional documentation from language and beautifier options.

In this case, compare supported options for each beautifier of a given language.

Example:

> # Beautifier Options Comparison
> 
> ## JavaScript
>
| Option | PrettyDiff | JS-Beautify |
| --- | --- | --- |
| `brace_style` | ? | ? |
| `break_chained_methods` | ? | ? |
| `end_with_comma` | ? | ? |
| `end_with_newline` | ? | ? |
| `eval_code` | ? | ? |
| `indent_size` | :white_check_mark: | :white_check_mark: |
| `indent_char` | :white_check_mark: | :white_check_mark: |
| `indent_level` | ? | ? |
| `indent_with_tabs` | :white_check_mark: | :white_check_mark: |
| `jslint_happy` | ? | ? |
| `keep_array_indentation` | ? | ? |
| `keep_function_indentation` | ? | ? |
| `max_preserve_newlines` | ? | ? |
| `preserve_newlines` | ? | ? |
| `space_after_anon_function` | ? | ? |
| `space_before_conditional` | ? | ? |
| `space_in_paren` | ? | ? |
| `unescape_strings` | ? | ? |
| `wrap_line_length` | ? | ? |
>
> ## Markup (HTML, XML, template languages)
| Option | PrettyDiff | JS-Beautify |
| --- | --- | --- |
| `brace_style` | ? | ? |
| `end_with_newline` | ? | ? |
| `extra_liners` | ? | ? |
| `indent_char` | ? | ? |
| `indent_inner_html` | ? | ? |
| `indent_size` | ? | ? |
| `indent_scripts` | ? | ? |
| `preserve_newlines` | ? | ? |
| `max_preserve_newlines` | ? | ? |
| `unformatted` | ? | ? |
| `wrap_attributes` | ? | ? |
| `wrap_attributes_indent_size` | ? | ? |
| `wrap_line_length` | ? | ? |

Edit: Just writing out options.  I will being populating for Pretty Diff shortly.
Edit: Added a table for markup languages

**Comment by Glavin001** [comment]
@prettydiff take a look at https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#javascript 

What do you think?

> 
| Option | JS Beautify | JSCS Fixer | Pretty Diff |
| --- | --- | --- | --- |
| `disabled` | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `default_beautifier` | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `beautify_on_save` | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `brace_style` | :white_check_mark: | :x: | :x: |
| `break_chained_methods` | :white_check_mark: | :x: | :white_check_mark: |
| `end_with_comma` | :white_check_mark: | :x: | :white_check_mark: |
| `end_with_newline` | :white_check_mark: | :x: | :x: |
| `eval_code` | :white_check_mark: | :x: | :x: |
| `indent_char` | :white_check_mark: | :x: | :white_check_mark: |
| `indent_level` | :white_check_mark: | :x: | :x: |
| `indent_size` | :white_check_mark: | :x: | :white_check_mark: |
| `indent_with_tabs` | :white_check_mark: | :x: | :white_check_mark: |
| `jslint_happy` | :white_check_mark: | :x: | :x: |
| `keep_array_indentation` | :white_check_mark: | :x: | :x: |
| `keep_function_indentation` | :white_check_mark: | :x: | :x: |
| `max_preserve_newlines` | :white_check_mark: | :x: | :x: |
| `preserve_newlines` | :white_check_mark: | :x: | :white_check_mark: |
| `space_after_anon_function` | :white_check_mark: | :x: | :white_check_mark: |
| `space_before_conditional` | :white_check_mark: | :x: | :x: |
| `space_in_paren` | :white_check_mark: | :x: | :x: |
| `unescape_strings` | :white_check_mark: | :x: | :x: |
| `wrap_line_length` | :white_check_mark: | :x: | :white_check_mark: |

**Comment by prettydiff** [comment]
Status of missing or unsupported options in Pretty Diff:

* `brace_style` - Pretty Diff supports this feature in a different way with the Pretty Diff options [braceline](http://prettydiff.com/documentation.xhtml#braceline), [bracepadding](http://prettydiff.com/documentation.xhtml#bracepadding), [braces](http://prettydiff.com/documentation.xhtml#braces), [formatObject](http://prettydiff.com/documentation.xhtml#formatObject)
* `end_with_newline` - Not supported
* `eval_code` - I don't know what this option does, so Pretty Diff probably doesn't have it.
* `indent_level` - **Supported** with [inlevel](http://prettydiff.com/documentation.xhtml#inlevel)
* `jslint_happy` - **Supported** with [styleguide](http://prettydiff.com/documentation.xhtml#styleguide) with a value of `jslint`
* `keep_array_indentation` - Not supported
* `keep_function_indentation` - Not supported
* `max_preserve_newlines` - **Supported** with [preserve](http://prettydiff.com/documentation.xhtml#preserve)
* `space_before_conditional` - Not supported.
* `space_in_paren` - **Supported** with [bracepadding](http://prettydiff.com/documentation.xhtml#bracepadding)
* `unescape_strings` - Not supported

**Comment by Glavin001** [comment]
If you submit a Pull request to add those options to the internal Pretty Diff beautifier then run `npm run docs` and it will re-generate the documentation and beautifier option comparison tables.

**Comment by prettydiff** [comment]
Awesome!
