### ISSUE TITLE
Add beautify for elixir/phoenix

### ISSUE THREAD

**Issue by RomarioLopezC** [Glavin001/atom-beautify#1040]

**Comment by Glavin001** [comment]
Please provide a link to the language's documentation, including example code. Thank you.

**Comment by ssijak** [comment]
@Glavin001 [http://elixir-lang.org/](http://elixir-lang.org/)  [http://elixir-lang.org/docs/stable/elixir/Kernel.html](http://elixir-lang.org/docs/stable/elixir/Kernel.html)

**Comment by RomarioLopezC** [comment]
@Glavin001 Phoenix is a web framework written in Elixir

http://www.phoenixframework.org/
https://hexdocs.pm/phoenix/Phoenix.html

**Comment by rubencaro** [comment]
This could be a duplicate of #545
