### ISSUE TITLE
Dynamic beautifier per project

### ISSUE THREAD

**Issue by mjanser** [Glavin001/atom-beautify#1041]
Some projects define which beautifier should be used. This happens usually with a config file specific to a beautifier stored in project's root directory. For example in PHP there is [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) which use `.php_cs` and `phpcs.xml.dist` respectively.

It would be great if the plugin could check for such config files and then run the appropriate beautifier dynamically.

**Comment by Glavin001** [comment]
This will be supported by Unibeautify: https://github.com/Unibeautify/unibeautify/issues/4
Atom-Beautify will be migrating to Unibeautify in the near future ( #1174 ) and therefore support this feature.

**Comment by Glavin001** [comment]
Multiple beautifiers per language has been implemented in Unibeautify: https://github.com/Unibeautify/unibeautify/issues/4

Atom-Beautify is being rewritten to be powered by Unibeautify. (cc @szeck87 )

Please keep the feature ideas and support coming! I appreciate your patience. I hope to develop Unibeautify to meet all of your needs.
