### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by cdrandin** [Glavin001/atom-beautify#1043]
Installing “atom-beautify@0.29.9” failed.Hide output…

npm WARN engine typescript-formatter@2.2.1: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine glob-expand@0.2.0: wanted: {"node":">0.10 <=5"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing uglify-js@2.6.4
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Chris\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\Chris\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Chris\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Chris\.atom\.apmrc" "install" "C:\Users\Chris\AppData\Local\Temp\d-11662-2960-tjqhhw\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\Chris.atom.apm\sigmund\1.0.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\Chris.atom.apm\sigmund\1.0.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by prettydiff** [comment]
Looks like not all the dependencies were downloaded.  Could you try this from the command line and let me know if it works:

    apm install atom-beautify

**Comment by cdrandin** [comment]
I still get the same issue.
It wants a node version and claims I have `0.10.40`, but when I do `node --version` it prints `v6.2.1`. My npm is on version `3.9.3`.

**Comment by prettydiff** [comment]
You probably have v6.2.1 manually downloaded to your computer.  Atom has a separate internal version of node running.

**Comment by cdrandin** [comment]
How would I go about updating it or set my own path?

**Comment by DavidGDD** [comment]
I've similar problems:

> atom-beautify@0.29.9 postinstall /tmp/apm-install-dir-11664-23287-5ft8jf/node_modules/atom-beautify
> node script/build-options.js


npm WARN engine typescript-formatter@2.2.1: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine glob-expand@0.2.0: wanted: {"node":">0.10 <=5"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-11664-23287-5ft8jf/node_modules/atom-beautify/script/build-options.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "?.atom/.apm/.apmrc" "--userconfig" "?/.atom/.apmrc" "install" "/tmp/d-11664-23287-1jezmwe/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.9 postinstall: `node script/build-options.js`
npm ERR! Exit status 8

I try to uninstall and install again and it doesnt work.

**Comment by Glavin001** [comment]
It might be a good idea to ask for `apm` help over at https://github.com/atom/apm

**Comment by ngo6012** [comment]
I'm having the same issue as DavidGDD. Has anyone found a solution?

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
