### ISSUE TITLE
Javascript comment in last line doesn't beautify well

### ISSUE THREAD

**Issue by giovannibenussi** [Glavin001/atom-beautify#1046]
I have found that in javascript with this code the beautification doesn't work well:

```js
res.json({  
        success: true,  
        message: []  
    })  
    // console.timeEnd("Response time")
```

However, if I delete the last line the beautification works well:

```js
res.json({
    success: true,
    message: []
})
```

If I remove the comment, it also works:

```js
res.json({
    success: true,
    message: []
})
console.timeEnd("Response time")
```

Regards!

**Comment by prettydiff** [comment]
Which beautifier are you using to beautify JavaScript?  The default is JS Beautify.

**Comment by giovannibenussi** [comment]
It is JS Beautify

**Comment by prettydiff** [comment]
I recommend opening an issue at https://github.com/beautify-web/js-beautify/issues

**Comment by giovannibenussi** [comment]
Ok, thankyou !
