### ISSUE TITLE
Trouble installing atom beautify on mac

### ISSUE THREAD

**Issue by wmcolodette** [Glavin001/atom-beautify#1050]
### Description

I'm getting the following issue when I try to install beautify. Can anyone help?
> fsevents@1.0.12 install /private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.36.8

npm WARN engine typescript-formatter@2.2.1: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine glob-expand@0.2.0: wanted: {"node":">0.10 <=5"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.36.8
node-pre-gyp ERR! stack     at get_runtime_abi (/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "node" "/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@1.0.12
npm ERR! fetch failed https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/untildify/-/untildify-2.1.0.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/wagnercolodette/.atom/.apm/.apmrc" "--userconfig" "/Users/wagnercolodette/.atom/.apmrc" "install" "/private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/d-11666-897-xjj2sy/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! fetch failed with status code 502
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/vj/r0zdmg_n1_v5wjy5vv9q105c0000gn/T/apm-install-dir-11666-897-js3ruj/npm-debug.log

# Checklist

- [x] I have tried uninstalling and reinstalling Atom to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
Usually this issue is due to missing dependencies.  Try running this from the command line and let us know if it helps:

    apm install atom-beautify

**Comment by wmcolodette** [comment]
I tried doing that, and it reports the same error after about 4 minutes.

**Comment by wmcolodette** [comment]
Fixed it. Removed all node and node_module directories and uninstalled node, then reinstalled it.
