### ISSUE TITLE
Update takes ages to complete

### ISSUE THREAD

**Issue by duytrung** [Glavin001/atom-beautify#1053]
Hi,

I just don't know whether the update of this plugin is by download from the website file-by-file or whole zipped package to the install. It took almost an hour to complete.

Was Atom download alot of files from repo to update the plugin?

Kind regards

TN

**Comment by Glavin001** [comment]
> It took almost an hour to complete.

An hour is crazy. Maybe a couple minutes, tops. Is your Internet very slow?

Regardless, we are working on improving the installation time. Thanks for your feedback.

**Comment by jemminger** [comment]
This happens to me too on every update.  OSX 10.11.5, happened on Yosemite too.  If I just use the update functionality, it will sit there "updating" forever, with apm process taking 200% or more.  If I just kill Atom after a few minutes and relaunch, the update appears to have applied correctly.

**Comment by Glavin001** [comment]
> If I just use the update functionality, it will sit there "updating" forever, with apm process taking 200% or more. If I just kill Atom after a few minutes and relaunch, the update appears to have applied correctly.

This is **not** an Atom-Beautify issue. This is a bug with `settings-view`.
See Issue https://github.com/atom/settings-view/issues/532 and Pull Request https://github.com/atom/settings-view/pull/771

**Comment by Glavin001** [comment]
This bug with `settings-view` has since been updated so a future Atom release should resolve this issue.
