### ISSUE TITLE
Could not find 'X'. The program may not be installed. on Windows 10

### ISSUE THREAD

**Issue by UziTech** [Glavin001/atom-beautify#1054]
I was having an issue where every command that I did not explicitly set the path to was throwing an error.

`Could not find 'X'. The program may not be installed.`

I tracked the bug down to [/src/beautifiers/beautifier.coffee#L171](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L171)

```javascript
        options.path ?= env.PATH
```

Turns out my `PATH` variable was set to `Path` so `env.PATH` was undefined

I have no idea how the variable name got changed but when I changed it back and restarted Atom everything worked fine.

Just throwing this out there for anyone else who may have this issue.

**Comment by Glavin001** [comment]
That's very strange. Thanks for sharing so other users can find this in the search!

**Comment by UziTech** [comment]
Same thing happened again after updating windows 10. I have submitted feedback to windows about the issue but I'm wondering if Atom-Beautify should check for this in the `which` function?

**Comment by Glavin001** [comment]
I suppose you could look into adding support for `Path` (along with the existing `PATH`)? See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L171 and purhaps other lines.

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
