### ISSUE TITLE
add support for mjml language

### ISSUE THREAD

**Issue by MatasSim** [Glavin001/atom-beautify#1058]
https://mjml.io/documentation/

**Comment by prettydiff** [comment]
@MatasSim This looks like XML syntax.  Is there anything uniquely different about the syntax?  If this is just XML syntax then it is already supported provided a slight modification to this file:

https://github.com/Glavin001/atom-beautify/blob/master/src/languages/xml.coffee

**Comment by Glavin001** [comment]
@MatasSim : If the answer to @prettydiff 's question is `Yes, mjml is just the XML syntax` then please let us know! We can add official support for mjml language to Atom-Beautify so you do not have to change the Atom grammar to `XML` whenever you want to beautify it.

**Comment by prettydiff** [comment]
I reopened the issue as the request is valid.  We just need a minor technical confirmation to complete and verify support.

**Comment by MatasSim** [comment]
Hi, I think mjml is more like HTML than XML syntax because MJML supports inline css for e-mail templating. I have changed Atom syntax from XML to HTML and beautified code, results were pretty the same. actually there is nothing unique about this syntax so I think we can close this issue.

**Comment by Glavin001** [comment]
>I have changed Atom syntax from XML to HTML ...  actually there is nothing unique about this syntax so I think we can close this issue.

We would want to add support for MJML such that you **do not** have to change the selected grammar for Atom.
