### ISSUE TITLE
In C++ unnecessary break statements required for beautify to work with switch statements

### ISSUE THREAD

**Issue by matthewfeickert** [Glavin001/atom-beautify#1060]
### Description

In the attached C++ code ([Chapter_4-Quiz.zip](https://github.com/Glavin001/atom-beautify/files/357951/Chapter_4-Quiz.zip)) Beautify fails on main.cpp where the switch statement does not have break statements as return statements are used. However, if unnecessary break statements are included (as they are in beautify_works.cpp) Beautify proceeds just fine.
### Expected Results

The beautified code should have looked like it is presented (after aligning by hand) in the attached file main.cpp:

```
std::string getMonsterType (const Monster &monster) {
  switch (monster.type) {
  case MonsterType::OGRE:
    return "Ogre";

  case MonsterType::DRAGON:
    return "Dragon";

  case MonsterType::ORC:
    return "Orc";

  case MonsterType::GIANT_SPIDER:
    return "Giant spider";

  case MonsterType::SLIME:
    return "Slime";

  default:
    return "Type unknown";
  } // switch
}   // getMonsterType
```
### Steps to Reproduce
1. Open main.cpp in Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Beautify fails.
### Debug

The contents of `Atom Beautify: Help Debug Editor` are not being copied into my clipboard (Atom v1.8.0 for Linux) so I am unable to create a `debug.md` Gist. Sorry.
# Checklist
- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
  - Used filter: is:issue is:open "switch" "c++" 
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue
  - The contents of `Atom Beautify: Help Debug Editor` are not being copied into my clipboard (Atom v1.8.0 for Linux) so I am unable to create a `debug.md` Gist. Sorry.

**Comment by prettydiff** [comment]
Which beautifier are you using?  This is most likely a parse/beautification failure on behalf of a language specific beautifier.

**Comment by matthewfeickert** [comment]
uncrustify.
I apologize if this is the case. I had no memory of manually installing uncrustify, so I had (most likely falsely) assumed that Atom-Beautify had pulled it along upon install.

**Comment by prettydiff** [comment]
Uncrustify is a dependency of Atom Beautify, so the defect is valid.  I also recommend opening an issue with the uncrustify project: https://github.com/uncrustify/uncrustify

Please include a link to this issue in the Uncrustify issue, so that the status can be tracked from here.

**Comment by matthewfeickert** [comment]
Now that I've automatically created a Gist using the update from #1061 is there a way to find the Gist to view or share it? Or it is just sent to the dev team only?

**Comment by Glavin001** [comment]
The Gist has a link and a prompt will appear providing that link for you to copy and paste, as well as automatically open the address in your web browser.

**Comment by matthewfeickert** [comment]
The Gist didn't automatically open in Chrome, so I just assumed that it was created somewhere that the devs could find. Does that mean that if the Gist doesn't open that it wasn't created properly?

**Comment by Glavin001** [comment]
It should both open (in Chrome, possibly, using [`node-open`](https://github.com/pwnall/node-open) ) and provide you with a link to share via a `confirm` prompt. Did the prompt not appear? If an error occurred, it should show another prompt with the error message.
