### ISSUE TITLE
`Help Debug Editor` should open a new editor instead of copying to clipboard

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#1061]
For some reason, using the clipboard does not always work with Atom. /cc #1060 et al.

**Comment by Glavin001** [comment]
In fact, let's create the entire Gist automatically: https://developer.github.com/v3/gists/#create-a-gist

**Comment by Glavin001** [comment]
Published to v0.29.10

**Comment by emileber** [comment]
It should be made clear in the doc that this changed. The [troubleshooting](https://github.com/Glavin001/atom-beautify/blob/0212f49c83a9eec9fd777bd0d8f3f98af9d5d5e9/docs/troubleshooting.md) page wasn't updated with this.
