### ISSUE TITLE
Indentation issues: Has this error being fixed ? 

### ISSUE THREAD

**Issue by PolGuixe** [Glavin001/atom-beautify#1066]
I am experiencing this issue: https://github.com/beautify-web/js-beautify/issues/889

Apparently it has been fixed in JSBeautify. Which version are we using?

**Comment by PolGuixe** [comment]
Sorry, it hasn't been fixed in JSBeautify.

**Comment by prettydiff** [comment]
It is also showing as defective in Pretty Diff, so I will need to issue a fix on my end.
