### ISSUE TITLE
Custom config location

### ISSUE THREAD

**Issue by mdmoreau** [Glavin001/atom-beautify#1069]
It would be great if we could specify a custom config location so a fallback/default .jsbeautifyrc file could be synced when using https://github.com/atom-community/sync-settings.  Sync settings allows you to sync files located in ~/.atom, so if we could store the .jsbeautifyrc there it could be synced with other settings.

Ideally then you could specify the atom-beautify config location as ~/.atom/.jsbeautifyrc to get your default/fallback synced - emmet works using something similar.  Does that sound like something that's possible?  Thanks for the great plugin - appreciate all of the work that's gone into it.

**Comment by Glavin001** [comment]
:+1:!
Atom-Beautify currently supports a `.jsbeautifyrc` within the user's home directory. 
The `~/.atom/.jsbeautifyrc` path could also be included by changing https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L435-L444 and/or related parts.
