### ISSUE TITLE
Beautification does not work in PHP-files when atom is opend via windows explorer context menu

### ISSUE THREAD

**Issue by joergmoldenhauer** [Glavin001/atom-beautify#1071]
### Description

When I open a folder by right clicking it in Windows Explorer and selecting "Open with atom" the beautification simply does not happen in PHP-files. There is no error message and the "beautification in progress" window appears, but the code stays as ugly as it is. The problem seems to be only in PHP-files. JS-Files are beautified as they should. Also the problem only happens when Atom is opened via the Windows context menu. When I open Atom via the shortcut on my desktop (which opens the last project) beautification works just fine.
### Steps to Reproduce
1. Open a project with PHP-files by right clicking it in Windows Explorer and select "Open with Atom"
2. Run command `Atom Beautify: Beautify Editor`
3. Beautification does not happen
### Debug

Here is a link to the `debug.md`
https://gist.github.com/joergmold/77dc831503da4a2687ae05bc95822810
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
The error is:
```
2016-07-17T09:53:52.713Z - debug: [beautifiers\beautifier.coffee] spawn done 1  Could not open input file: /Users/Joerg/.atom/php-cs-fixer.phar
```

And I confirmed the `php.cs_fixer_path` is set to:
```
    "cs_fixer_path": "/Users/Joerg/.atom/php-cs-fixer.phar",
```

Please confirm this path `/Users/Joerg/.atom/php-cs-fixer.phar` is correct.

**Comment by joergmold** [comment]
Thanks for pointing out the error. In fact the path was not quite right. The "C:" at the beginning was missing. I have Atom and php-cs-fixe.phar under "C:" and my projects under "D:" It seems that Atom is started with a different context when I open projects under "D:" via the explorer menu. Adding the "C:" at the beginning solved this problem.

Thank you very much for your help. Also thank you very much for your fantastic Atom package. It is definitely a must-have for all coders.

**Comment by Glavin001** [comment]
Glad to hear it is working for you! Thank you for the kind words 😃 !

**Comment by sgehrman** [comment]
This was working, but stopped weeks ago.  I have the correct path with the C: but php doesn't beautify.
