### ISSUE TITLE
end-with-newline with css

### ISSUE THREAD

**Issue by raky291** [Glavin001/atom-beautify#1077]
This option is not available on the interface.
Can you add this feature please?

The default library already contains this option (jsbeautifier).

**Comment by Glavin001** [comment]
A simple change to https://github.com/Glavin001/atom-beautify/blob/master/src/languages/css.coffee#L30 and  https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/js-beautify.coffee#L15 would do it. I would be happy to merge a Pull Request for this. Thanks.

**Comment by Glavin001** [comment]
Published to v0.29.11
