### ISSUE TITLE
Beautify PHP not work...

### ISSUE THREAD

**Issue by edDimensi** [Glavin001/atom-beautify#1078]
# Description

The results of beautification are not what I expect.
I use ctrl + alt + b, see animation progress and nothing change.

# Expected Results

The beautified code should have looked like:

```
<?php
require_once ('phpQuery/phpQuery.php');

$catalogLink = 'http://tiesshop.ru/catalog/102';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $catalogLink);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$catalog = curl_exec($ch);
curl_close($ch);
$document = phpQuery::newDocumentHTML($catalog);
$links = $document->find('a.good_title');

foreach($links as $value) {
	$pq = pq($value);
	$link = 'http://tiesshop.ru' . $pq->attr('href');
	$linksFromCatalog[] = $link;
}

print_r($linksFromCatalog);

foreach($linksFromCatalog as $itemLink) {
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $itemLink);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	$newItem = curl_exec($ch);
	curl_close($ch);
	$itemDocument = phpQuery::newDocument($newItem);
	$title = $itemDocument->find('.pad > h1');
	$title = pq($title)->text();
	foreach($itemDocument->find('table#properties > tr') as $value) {
		$trPq = pq($value);
		$tdKey = $trPq->children('td')->eq(0)->text();
		$tdContent = $trPq->children('td')->eq(1)->text();
		$table[$tdKey] = $tdContent;
	}

	$pageContent['title'] = $title;
	$pageContent['content'] = $table;
	$pages[] = $pageContent;
}

$printTableTitles = array_keys($pages[0]['content']);
echo mb_convert_encoding("РќР°Р·РІР°РЅРёРµ;", "windows-1251");
echo mb_convert_encoding(implode(";", $printTableTitles) . PHP_EOL, "windows-1251");

foreach($pages as $key => $page) {
	$titlePage = $pages[$key]['title'];
	echo mb_convert_encoding($titlePage . ';', "windows-1251");
	echo mb_convert_encoding(implode(";", $page['content']) , "windows-1251");
	echo PHP_EOL;
}

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/216a567ed0d905193da3a2de5b59fc6f

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Looking at your debugging information I see:

```
2016-07-21T16:42:39.947Z - debug: [beautifiers\beautifier.coffee] spawn C:\tools\php\php.EXE 0=C:\Users\Dimen\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=C:\Users\Dimen\AppData\Local\Temp\temp116621-10296-bxlxyt
2016-07-21T16:42:39.991Z - debug: [beautifiers\beautifier.coffee] spawn done 0  @ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../fabpot/php-cs-fixer/php-cs-fixer
php "%BIN_TARGET%" %*
```

Pay close attention to the `spawn` command:

```
spawn C:\tools\php\php.EXE 0=C:\Users\Dimen\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT ....
```

Notice that it ends in `.BAT` which is not a PHP script, and so it fails.
PHP-CS-Fixer beautifer implemented within Atom-Beautify calls `php php-cs-fixer {..args}`: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L37-L38

I recommend changing your `cs_fixer_path` to the appropriate `php-cs-fixer` path that is a PHP file.

```
    "cs_fixer_path": "C:/Users/Dimen/AppData/Roaming/Composer/vendor/bin/php-cs-fixer",
```

Hope that helps!

**Comment by edDimensi** [comment]
Nope, it's anyway not work. And from the beginning I have such a path. I even removed the .bat file, but it still does not work.

**Comment by Glavin001** [comment]
I'd recommend taking a look at the many of PHP-CS-Fixer related Issues that already exist: https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=php-cs-fixer+bat&type=Issues
When you find the solution that works for you, please post back here.

**Comment by edDimensi** [comment]
https://github.com/Glavin001/atom-beautify/issues/903#issuecomment-207074273
