### ISSUE TITLE
Configuration to keep LI contents on one line?

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#1081]
Is there a configuration setting to keep LI tags and their contents together?

In other words, currently I get this:

``` html
<li>
  <a href="#">Action</a>
</li>
```

But I'd rather get this:

``` html
<li><a href="#">Action</a></li>
```

I realize many people prefer the first way, which is why I was wondering if there was a config I can edit to get it my way?

**Comment by Glavin001** [comment]
I think what you want is the `unformatted` option: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#unformatted

**Comment by smlombardi** [comment]
This does not work, adding the tag to my .jsbeautifyrc, the `li` tags are still being broken onto separate lines.
```json
  "html": {
    "unformatted": ["li", "th", "td"]
  }
```

**Comment by Glavin001** [comment]
Create a `debug.md` Gist and add a link here. It includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by smlombardi** [comment]
https://gist.github.com/6979d1ff77d2cc08b2bc7ba7f8a90bc5
