### ISSUE TITLE
Sass format don't work properly

### ISSUE THREAD

**Issue by raky291** [Glavin001/atom-beautify#1088]
My code:
![err1](https://cloud.githubusercontent.com/assets/12045722/17082593/dfa7afe4-5141-11e6-8e63-ba4b527049d0.jpg)

After pressing Ctrl+Alt+B
![err2](https://cloud.githubusercontent.com/assets/12045722/17082594/dfdb377e-5141-11e6-8724-ccb8d727aee5.jpg)

Any idea what's going on?

**Update:**

> Pretty Diff will not support this. The original file does not contain curly braces to separate the selector from its properties and there are no semicolons to separate the properties from each other. https://github.com/Glavin001/atom-beautify/issues/981#issuecomment-223856949

Pretty Diff don't support Sass, it cannot be the default beautifier.

And when I use CSScomb I get the following error:
![err3](https://cloud.githubusercontent.com/assets/12045722/17082761/6286b168-5146-11e6-9b3a-d6ace5053d23.jpg)

**Comment by prettydiff** [comment]
Pretty Diff supports the SCSS variant of SASS.

**Comment by aidistan** [comment]
There are lots of differences between SCSS and SASS. The former could be handled well with `csspretty.js` (used by prettydiff) while the latter could not.  Surely we should change the default beautifier of SASS.

@raky291 I have tried your example codes with CSScomb and everything works fine.

**Comment by aidistan** [comment]
@raky291 The same error was raised by CIs. I will have a look into it.

https://travis-ci.org/Glavin001/atom-beautify/jobs/153043688
https://ci.appveyor.com/project/Glavin001/atom-beautify/build/641

**Comment by raky291** [comment]
Hi @aidistan the sass syntax don't use `{}` and `;` review the following lines of code:

https://travis-ci.org/Glavin001/atom-beautify/jobs/153043688#L898
https://ci.appveyor.com/project/Glavin001/atom-beautify/build/641#L501

**Comment by aidistan** [comment]
@raky291

Thanks for point out. I have updated test examples for SASS: https://github.com/Glavin001/atom-beautify/pull/1141/commits/e6bdb8a0f3aa9f3d676605bfbf7b5857e527f4bd

It turns out that `CSScomb` could not format SASS codes well either. I will try to use the official cli `sass-convert` instead.

**Comment by aidistan** [comment]
My PR #1141 is ready for merge now. Hope it would help : )

**Comment by raky291** [comment]
Thank you so much! :smiley:
