### ISSUE TITLE
Do not remove last line-feed from file.

### ISSUE THREAD

**Issue by starquake** [Glavin001/atom-beautify#109]
I use atom-beautify with linter jscs (google preset but I think it also complains with jquery preset) but it keeps complaining: Missing line feed at file end.

Enabling "js preserve new lines" does not fix this. And there is no way to let these two plugins come to peace with each other. Could you keep the last line-feed intact or make it an option to keep it intact?

**Comment by nelson6e65** [comment]
`end_with_newline` option, or similar, is available for SCSS?
