### ISSUE TITLE
Beautifying HTML results in collapsed tags being expanded

### ISSUE THREAD

**Issue by destinationunknown** [Glavin001/atom-beautify#1091]
# Description

Beautifying HTML (Have not tested with other languages) results in all collapsed tags being opened/expanded.

EDIT: Can confirm, this happens with other languages as well.
# Expected Results

The collapsed tags stay collapsed.
# Steps to Reproduce
1. Add any syntactically correct HTML code to the Atom editor.
2. Collapse any element, for example a `div`, by clicking on the down arrow next to the line       number of the opening tag.
3. Run command `Atom Beautify: Beautify Editor`
4. The collapsed HTML tag would have now opened/expanded.
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Please reopen this issue with the necessary debug.md file so that we can have details to investigate.
