### ISSUE TITLE
Beautification for PHP not working on OS X El Capitan

### ISSUE THREAD

**Issue by mawkee** [Glavin001/atom-beautify#1093]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/cddf67980db613fc53a3387ac7065786

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by mawkee** [comment]
This is invalid, please remove

**Comment by Glavin001** [comment]
> This is invalid, please remove

You should be able to close this issue yourself.
