### ISSUE TITLE
Please support unicode characters

### ISSUE THREAD

**Issue by robinguo** [Glavin001/atom-beautify#1094]
# Description

I'm using atom-beautify to beautify SQL files. I have Chinese characters in the file. After beautified, Chinese characters are garbled.
# Expected Results

```
select name as 姓名 from user
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
What computer language or beautifier are you using?

**Comment by robinguo** [comment]
Computer language is English.
Beautifier is sqlformat.

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by twang2218** [comment]
I run into the same error, I think this error is duplicate to #1142

**Comment by benlaan** [comment]
Hi, I'm not sure why you linked my project to this issue. I actually do support unicode, however my formatter is not used in atom-beautify.

**Comment by twang2218** [comment]
@prettydiff Atom-Beautify is using https://github.com/andialbrecht/sqlparse, which contains `sqlformat` command, for SQL formatting, it's quite confusing and caught me at the first time.

And yes, `sqlparse` has problem supportting unicode.

I have raised the issue https://github.com/andialbrecht/sqlparse/issues/315 and created a PR https://github.com/andialbrecht/sqlparse/pull/316 for it.

**Comment by prettydiff** [comment]
I am closing this issue as it is a third party defect in sqlformat application and @twang2218 is reporting the problem there.
