### ISSUE TITLE
python code, autopep8 0.9.1 does not support --indent-size option

### ISSUE THREAD

**Issue by Alienfeel** [Glavin001/atom-beautify#1095]
# Description

autopep8 does not support --indent-size option
autopep8 version 0.9.1
# Expected Results
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. ERROR occurs
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Odyseus** [comment]
Hello, @Alienfeel.

I just had this exact problem too. I also had installed autopep8 0.9.1 from Linux Mint repositories. Then I found [this StackOverflow](http://stackoverflow.com/questions/38441697/autopep8-error-indent-size) question with the same error report. It simply suggests to remove the autopep8 package (in my case was **python-autopep8**) and install autopep8 with **pip**.

```shell
pip install autopep8
```

This installed autopep8 1.2.4 and it works flawlessly with atom-beautify.
