### ISSUE TITLE
CSS statement broken by beautification

### ISSUE THREAD

**Issue by MichaelHancock** [Glavin001/atom-beautify#1100]
# Description

Calc css function is manipulated incorrectly by atom-beautify

```
  width: calc(100% + 45px); // Pre beautification
  width: calc(100%+ 45px); // Post beautification 
```
# Expected Results

This line should have been unchanged, removing the space broke the css statement.

```
  width: calc(100% + 45px);
```
# Steps to Reproduce
1. Add code to Atom editor (the line above)
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/MichaelHancock/61d06636a40244fedd7ecf61617f3e72
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
JS Beautifier defect.  Including @bitwiseman

**Comment by MichaelHancock** [comment]
I don't know if this is any help, but the issue seems directly linked to the use of + inside a calc statement. For example this breaks:
`width: calc(100% + 10px);` and turns into this `width: calc(100%+ 10px);`

But this does not break:
`width: calc(100% - 10px);` 

Hope this is of some help.

**Comment by prettydiff** [comment]
Thank you @MichaelHancock
