### ISSUE TITLE
Handlebars preserve newlines not working as expected

### ISSUE THREAD

**Issue by rwwagner90** [Glavin001/atom-beautify#1102]
# Description

Handlebars newlines are not preserved, and all the properties are squashed to one line.

# Expected Results

The beautified code should have looked like:

```hbs
{{ember-flatpickr
    altInput=true
    altFormat="m/d/Y"
    appendDataInput=false
    dateFormat="Y-m-d"
    enableTime=false
    onCloseAction=(action 'enableValidation' 'hireDateValidationEnabled')
    placeholder="Choose a date"
    value=(mut user.hireDate)}}
```

It squashes everything into:
```hbs
{{ember-flatpickr altInput=true altFormat="m/d/Y" appendDataInput=false dateFormat="Y-m-d" enableTime=false onCloseAction=(action 'enableValidation' 'hireDateValidationEnabled') placeholder="Choose a date" value=(mut user.hireDate)}}
```
# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/b5d81523821902ed7645b6fca82a95e8

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
This appears to be a JS Beautify defect.  I recommend opening a defect at https://github.com/beautify-web/js-beautify/issues

Including @bitwiseman

**Comment by rwwagner90** [comment]
@prettydiff I did open an issue there, but I assumed, since preserve newlines was a checkbox, maybe it just wasn't actually passing it through to JS Beautify or something. The issue I opened is here https://github.com/beautify-web/js-beautify/issues/978

**Comment by rwwagner90** [comment]
Confirmed to be lack of support for handlebars in JS Beautify
