### ISSUE TITLE
No error notification from invalid JSON inside .jsbeautifyrc

### ISSUE THREAD

**Issue by emileber** [Glavin001/atom-beautify#1106]
# Description

If the JSON inside the `.jsbeautifyrc` file is invalid, there's no error notification so you can't know why your `.jsbeautifyrc` is ignored.

I had a comma at the end of an object definition, which is valid js, but invalid json. I tried the _Help Debug Editor_ option (see below) and then I saw that my `.jsbeautifyrc` file inside a project sub-folder wasn't interpreted correctly.

# Expected behavior

Would be cool if there was an error (or at least a warning) notification when an invalid `.jsbeautifyrc` file is encountered.

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/50c9cc5cb71e99a32bb8141365a6e732

**Comment by Glavin001** [comment]
I agree. 

I am away on vacation for the next two weeks so it is unlikely I will be able to make the appropriate changes and publish. Pull requests welcome back. Thanks.

**Comment by emileber** [comment]
This was merged and published to v0.29.11

**Comment by Glavin001** [comment]
Thanks, @emileber !
