### ISSUE TITLE
Pretty Dif HTML

### ISSUE THREAD

**Issue by djchou** [Glavin001/atom-beautify#1109]
# Description

When I beautify HTML using prettydif, a javascript comment using /\*   comment */ will cause beautify to delete all of the javascript code.

The results of beautification are not what I expect.
# Expected Results

no code deleted

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Would you mind generating Atom Beautify's debug.md file and pasting that into a gist?  That way I can see all the option settings and a sample of the code causing the problem.

**Comment by Glavin001** [comment]
This can be reopened once we have more information.
