### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by ronnyfly2** [Glavin001/atom-beautify#1110]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/70c1d67533b4bab824f9d6a8acb1b350
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Thank you for the debug.md file.  Could you be more specific on the nature of the defect?  What part do you believe is incorrect?  When I pass the sample code, from the debug.md file, into http://jsbeautifier.org/ it appears to beautify correctly.

**Comment by Glavin001** [comment]
Please reopen with more information.
