### ISSUE TITLE
Random line break in middle of text inside <p></p> tags

### ISSUE THREAD

**Issue by masteryprep** [Glavin001/atom-beautify#1112]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:
![What I'd like for it to look like](https://cloud.githubusercontent.com/assets/20819775/17376085/89fde064-5979-11e6-9eda-096a3177cd33.PNG)

What it actually looks like:
![What it actually looks like](https://cloud.githubusercontent.com/assets/20819775/17376089/8be60352-5979-11e6-9506-89cb8f305844.png)
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/b381c33e49b46b32c1d8ac4ee2f0d568

**Comment by prettydiff** [comment]
Issue opened with JSBeautify

**Comment by Glavin001** [comment]
Closing this as a JS-Beautify bug.

**Comment by gsteffins** [comment]
This was breaking <p>tags for me as well with default settings.  Change your settings: Packages / Atom Beautify / Settings / HTML / Wrap line length to 0 to disable.
