### ISSUE TITLE
Could not get Shell Environment. Exit code: 1, Signal: null

### ISSUE THREAD

**Issue by k4rtik** [Glavin001/atom-beautify#1113]
# Description

On invocation using Ctrl-Alt-b, I see a spinner for a while and then this error bubble pops up to the top-right of Atom:

```
Could not get Shell Environment. Exit code: 1, Signal: null
Hide Stack Trace
Error: Could not get Shell Environment. Exit code: 1, Signal: null
    at ChildProcess.<anonymous> (/home/kartik/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:147:31)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

No beautification happens.
# Expected Results

NA
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
# Debug

Attempt to create debug.md also fails as I do not see any change in my clipboard. (On a different note, I believe instead of hanging on to user's clipboard, a better idea would be to create a `debug.md` in `/tmp` or some other suitable directory.)
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Cablethief** [comment]
Do you use byobu or some sort of screen? 
I make use of byobu which uses tmux I believe, so to drop me into a session immediately I added 
```
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec byobu
```
to my .zshrc 
This caused the exact error you described. 
```
Could not get Shell Environment. Exit code: 1, Signal: null
Hide Stack Trace
Error: Could not get Shell Environment. Exit code: 1, Signal: null
    at ChildProcess.<anonymous> (/home/michael/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:147:31)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by k4rtik** [comment]
I was probably using Terminator back when I filed this bug. I do not recall if I was also running tmux inside it.

**Comment by Cablethief** [comment]
After some testing I believe it to be caused by the use of `exec` in the .rc file to move into tmux or byobu.

**Comment by Glavin001** [comment]
Recent Atom-Beautify has a new `Help Debug Editor` command. Please give it a try if you would like some assistance!

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by k4rtik** [comment]
@Glavin001 thank you for your help, but I cannot reproduce this bug anymore. If no one else has encountered this issue, please feel free to close it.

**Comment by maksimf** [comment]
I'm having the exact issue described here. I have tmux installed and I'm using terminator

**Comment by Glavin001** [comment]
The applicable section of code is https://github.com/Glavin001/atom-beautify/blob/0f691d5116e21dac38fb75636197c24e4b173968/src/beautifiers/beautifier.coffee#L163-L174

It executes a command along the lines of`bash -ilc env` to read the latest environment variables. However, the `bash` part is really `process.env.SHELL` and looks to be causing problems.

I am not very familiar with Tmux and Terminator so I encourage anyone who is experiencing this issue to share your insight and contribute with a Pull Request once you figure something out. Please let me know if there's anything I can help you with.

**Comment by imdaadz** [comment]
I remember I'm not installing `tmux` or `terminator`.

I'm using MacOS, and when I executing my `.zshrc` file  error message show up it says: 
 `exec: byobu: not found`

**Comment by ryanpcmcquen** [comment]
Here's my [debug.md](https://gist.github.com/ryanpcmcquen/831273eaffb9186a6811b9cd6034cea2).

I'm on Mac OS 10.11.x with `tmux` and using `bash`.

**Comment by ryanpcmcquen** [comment]
I cannot remember the last time this happened, but it may still be an issue for some.

**Comment by k4rtik** [comment]
Haven't seen this in ages, closing.
