### ISSUE TITLE
indentation settings ignored for angular HTML files

### ISSUE THREAD

**Issue by fthebaud** [Glavin001/atom-beautify#1116]
# Version

Atom 1.9.2, atom-beautify 0.29.10 
# Description

Trying to beautify a HTML file that contains angular directives.

Settings in the html section:
![20160805-17 25 13](https://cloud.githubusercontent.com/assets/5389778/17453505/ade7e83a-5b31-11e6-87c4-fb8a96b5f076.png)

**Expected:** the indentation to be equal to 2 spaces.
**Results:**  the indentation is still equal to 4 spaces.

The _angularjs_ package is installed, and type of the file is _**HTML (angular)**_. 
![20160805-17 28 45](https://cloud.githubusercontent.com/assets/5389778/17453539/3e1b4744-5b32-11e6-8fc2-c7c97fc423b9.png)

If I force the grammar to be just **_HTML_** instead of **_HTML (angular)_**, the indentation setting is taken into account and the indentation is correct (i.e. equal to 2 spaces0.

**Comment by prettydiff** [comment]
Would you mind generating a debug.md file and pasting it into a gist?  It could be a broken Atom Beautify setting related to a specific grammar, a setting not being passed to a beautifier used for a specific grammar, or a grammar that isn't completely recognized.

**Comment by fthebaud** [comment]
https://gist.github.com/anonymous/7e0e672eddc67e841295aae381491ce9

**Comment by NodeJoSe** [comment]
You need to configure the EJS setting on atom-beautify, those are the settings for HTML (Angular)..

**Comment by Glavin001** [comment]
@NodeJoSe is correct. Based on the `debug.md` provided above you need to change the `EJS` settings, such as `EJS - Indentation Size`.
