### ISSUE TITLE
php_beautifier: command not found

### ISSUE THREAD

**Issue by maxxcrawford** [Glavin001/atom-beautify#112]
Using [Laravel Blade Template Structure](http://laravel.com/docs/4.2/templates) on project. The plug-in fails when ran on foo.blade.php files. It may be that the page starts with Laravel specific syntax, `@layout` or `@section('bar')` before the standard HTML beings. 

**Atom Error Code:**

```
Command failed: /bin/sh -c [ -f ~/.bash_profile ] && source ~/.bash_profile;[ -f ~/.bashrc ] && source ~/.bashrc;php_beautifier "/var/folders/vp/_9mdqt253m5bjm29_mbj7_rr0000gn/T/input11491-14187-1sd36l1" "/var/folders/vp/_9mdqt253m5bjm29_mbj7_rr0000gn/T/11491-14187-1r4cq45" /bin/sh: php_beautifier: command not found
```

**Comment by batmandakh** [comment]
I get this error:
Command failed: /bin/sh -c [ -f ~/.bash_profile ] && source ~/.bash_profile;[ -f ~/.bashrc ] && source ~/.bashrc;php "/usr/bin/php_beautifier " --input "/tmp/input115013-9069-1fnheun" --output "/tmp/115013-9069-1druszz" /bin/sh: 1: source: not found

I've check temp folder and didn't find temporary files... Other things working properly.
