### ISSUE TITLE
Beautify of .html and .twig files with twig tags (for craft cms) seem to ignore twig tags

### ISSUE THREAD

**Issue by tortilaman** [Glavin001/atom-beautify#1122]
# Description

With craft cms your twig files are all saved as HTML, so when trying to solve this I saved as .twig just in case to see if that would fix the problem, but no luck. It seems that twig elements such as {{ }}, {# #}, {% %} are all placed inline and indentation is ignored. If it helps, I have it set to beautify on save.
# Expected Results

The beautified code should have looked like:

```
{#
# Design Index template
# _________________________
#
# This template gets loaded whenever the Design index is requested, because
# the Design Index single_entry section's Template setting is set to
# "design/_index".
#
# An `entry` variable will be automatically passed to this template, which will
# be set to the Design Index entry.
#}

{# Rearrange entries #}
{% if filmEntries|length and designerEntries|length %}
    {% for i in 0..(filmEntries|length - 1) %}
        {# Film Entry #}
        {% set entries = entries|merge([filmEntries.nth(i)]) %}
        {# Designer Entries #}
        {% set entries = entries|merge(
            designerEntries[i * filmOffset : filmOffset]
        ) %}
    {% endfor %}
    {% set entries = entries|merge(
        designerEntries[filmOffset * filmEntries|length : filmOffset]
    ) %}
{% elseif designerEntries|length and filmEntries|length == 0 %}
    {# No short films in this year #}
    {% set entries = designerEntries %}
{% elseif filmEntries|length  and designerEntries|length == 0 %}
    {% set entries = filmEntries %}
{% endif %}
```

**Comment by prettydiff** [comment]
Would you mind generating the debug.md file and pasting it to a gist?  It will help me to reproduce the problem.

**Comment by tortilaman** [comment]
Gist is [here](https://gist.github.com/anonymous/409f1b99bd5ab73fd35e1e92aff47df2). The original might not be exactly right because I can't undo to where it was, but this is pretty close.

**Comment by prettydiff** [comment]
This also exposed a defect in Pretty Diff and I just pushed a resolution to branch 2.1.3.

**Comment by tortilaman** [comment]
Just for my own understanding, that's not the live branch, so as of now the issue is unresolved?

**Comment by prettydiff** [comment]
@tortilaman That is correct.  I have not merged to master yet.  When I do Github should automatically close this issue.  Even when I merge to master the fix may not automatically appear in Atom Beautify.  I bailed out of NPM a few months ago and am currently writing an alternative automation deployment solution.

**Comment by Glavin001** [comment]
Closing this as a Pretty Diff bug.
