### ISSUE TITLE
issues in Django Templates

### ISSUE THREAD

**Issue by orangercat** [Glavin001/atom-beautify#1123]
# Description

when i use atom-beautify for Django Templates code

``` html
    <link rel="stylesheet" href="{% static "css/lightbox.css" %}">
```

add space between `static ""`

``` html
    <link rel="stylesheet" href="{% static " css/lightbox.css " %}">
```
# Expected Results

The beautified code should have looked like:

```
    <link rel="stylesheet" href="{% static "css/lightbox.css" %}">
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist
- [Y] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [Y] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I need you to generate Atom Beautify's debug.md file and paste it to a gist.  The defect is most likely in Pretty Diff and most likely related to the nested quotes... but I want to be certain.

**Comment by prettydiff** [comment]
In the mean time you can immediately solve this problem by converting those two middle double quotes to single quotes.

**Comment by prettydiff** [comment]
I just enhanced Pretty Diff's markup parser to support this.  I would still like the debug.md file in case you are not using Pretty Diff as your beautifier.

**Comment by orangercat** [comment]
https://gist.github.com/anonymous/b093db8dd10a6b8d4cfa01801b3eea6f

HI  this  is debug.md thanks

**Comment by prettydiff** [comment]
Awesome.  Opening an issue with JSBeautify.

**Comment by Glavin001** [comment]
Closing this as a third-party bug.

**Comment by spaceneenja** [comment]
Updated today and still seeing this issue. Using better syntax fixed the parsing issue as recommended above.

**Comment by Glavin001** [comment]
@spaceneenja which grammars worked and which did not work for you? We could change Atom-Beautify's default beautifiers for Django.

**Comment by spaceneenja** [comment]
Sure, I changed:
```
<a href="{% url "order" %}">
<link type='text/less' rel="stylesheet" href="{% static "less/header.less" %}">
```

To:
```
<a href="{% url 'order' %}">
<link type='text/less' rel="stylesheet" href="{% static 'less/header.less' %}">
```

Now it works just fine!

**Comment by Glavin001** [comment]
Oh, so this isn't a bug? Just need to not use double-quotes (e.g. `"`) within double-quotes? Awesome! 👍

**Comment by spaceneenja** [comment]
Exactly. It is valid Django syntax however, so I suppose beautify shouldn't mess with it. 

Beautify adds a space before and after each item in the second quotes.
```<a href="{% url " order " %}">```

Updating someone's dirty old code however was a quick and easy fix though, and seems so obvious now that it's painful.
