### ISSUE TITLE
Formated XML CDATA Contains extra space

### ISSUE THREAD

**Issue by jdgomeza** [Glavin001/atom-beautify#1132]
# Description

The results of beautification are not what I expect. There is a undesired space that is breaking my well-formed XML file.
# Expected Results

The beautified code should have looked like:

```
...
    <state id="assignDestination">
        <onentry>
            <script>
                <![CDATA[sessionData.tmp = getDestination(sessionData, sessionData.group);]]>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code adds an undesired space between `<` and `![CDATA`
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/adcf9119fd624724cb949d99b53f47a8
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue
- [x] Upgraded Atom and all the packages to the latest version

**Comment by jdgomeza** [comment]
Forgot to mention it works fine with `Pretty Diff`. It only fails with `JS Beautify`

**Comment by jdgomeza** [comment]
Is this the right library? The issue here appears to be resolved.
https://github.com/beautify-web/js-beautify/issues/117

Thanks

**Comment by prettydiff** [comment]
@jdgomeza That is the correct library.  I recommend opening an issue with JSBeautify for their awareness.  They are wanting to support XML, but that support isn't there yet.  In the mean time I recommend changing your beautifier for XML to Pretty Diff.

**Comment by Glavin001** [comment]
Closing this as a third-party bug with the current work around being to use Pretty Diff as default beautifier.
