### ISSUE TITLE
JSX formating not work properly with .js extension

### ISSUE THREAD

**Issue by seajean** [Glavin001/atom-beautify#1143]
# Description
if file extension is .js, and contains jsx,
after select the Beautify menu, the file will become something like this:
```
  <
            Text style = {
                [styles.white, styles.title]
            } > {
                this.state.orderData.statusInfo.text
            } < /Text> <
            Text style = {
                [styles.white]
            } > order ID: {
                this.state.orderData.mainOrderId
            } < /Text> <
            Text style = {
                [styles.white]
```
# Expected Results

The beautified code should have looked like:

```
  <Text style={[styles.white, styles.title]}>{this.state.orderData.statusInfo.text}</Text>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

- [* ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ *] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ *] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [* ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by seajean** [comment]
I change the setting and it works fine now.

**Comment by phaibin** [comment]
@seajean I meet the same issue. What change has you made?

**Comment by seajean** [comment]
@phaibin  go to the package setting and find the javascript column,  change the default beautifier to  Pretty Diff

**Comment by phaibin** [comment]
@seajean I works! Thanks!
