### ISSUE TITLE
Not able to install package

### ISSUE THREAD

**Issue by amolbagde** [Glavin001/atom-beautify#1144]
I am getting below error while trying to install the package.

> atom-beautify@0.29.10 postinstall C:\Users\c0bagdea\AppData\Local\Temp\apm-install-dir-116719-15508-1jhrmdv\node_modules\atom-beautify
> node script/build-options.js

npm WARN engine typescript-formatter@2.3.0: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine glob-expand@0.2.0: wanted: {"node":">0.10 <=5"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine attach-ware@2.0.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\c0bagdea\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\c0bagdea\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\c0bagdea\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\c0bagdea\\.atom\\.apmrc" "install" "C:\\Users\\c0bagdea\\AppData\\Local\\Temp\\d-116719-15508-dgknwf\\package.tgz" "--target=0.37.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.10 postinstall: `node script/build-options.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.10 postinstall script 'node script/build-options.js'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/build-options.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

**Comment by prettydiff** [comment]
The error says Atom ships with an internal Node.js run time of version *0.10.40* but the typescript-formatter package now supports a minimum Node version of *4.2.0*.

I could implement TypeScript, Java, and maybe C# in Pretty Diff's JavaScript parser.  The only feature not currently supported are the angle brace type annotations.  I just wish I had more hours in the day.  Right now I am getting crushed by the archaic Java-centered technology of my employer.  It really hurts my soul that a web business believes everything can created and tested by Java after being rendered into web technologies by Java.

**Comment by Glavin001** [comment]
> > npm WARN engine typescript-formatter@2.3.0: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})

> The error says Atom ships with an internal Node.js run time of version 0.10.40 but the typescript-formatter package now supports a minimum Node version of 4.2.0.

@prettydiff : I believe that is just a warning.

The true error is `npm ERR! atom-beautify@0.29.10 postinstall: node script/build-options.js`

@amolbagde please see duplicateissues: https://github.com/Glavin001/atom-beautify/search?q=postinstall+build-options&type=Issues&utf8=%E2%9C%93
