### ISSUE TITLE
Beatify removes one bracket from Handlebars

### ISSUE THREAD

**Issue by sangdth** [Glavin001/atom-beautify#1149]
# Description

The results of beautification are not what I expect. After beautify, everything go fine, Atom Beautify just removes one bracket from Handlebars triple-stash, look at line `isAdminEditorCSS user`, it starts with 3 `{{{` but closes with only 2 `}}`:

```
<link href="/styles/site.min.css" rel="stylesheet">{{!-- This file provides the default styling for the KeystoneJS Content Editor
            - only renders when user is logged in and admin --}}

    {{{isAdminEditorCSS user}}{{!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
        //- Safely remove this block if you are not targeting IE8 --}}
        <!--[if lt IE 9]>
            <script src="//cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.js"></script>
            <script src="//cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
```
# Expected Results

The beautified code should have looked like:

```
  <link href="/styles/site.min.css" rel="stylesheet">
  {{!-- This file provides the default styling for the KeystoneJS Content Editor - only renders when user is logged in and admin --}}

  {{{isAdminEditorCSS user}}}

  {{!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
        //- Safely remove this block if you are not targeting IE8 --}}
  <!--[if lt IE 9]>
    <script src="//cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.js"></script>
    <script src="//cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/1d70ed88828c9fd4ce9ebd3b7bf3d86c
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I am having trouble reproducing the defect using either Pretty Diff or JS Beautify.  Both appear to be handling this correctly.  Although I am getting this unrelated defect that could be blocking beautification in Atom: https://github.com/Glavin001/atom-beautify/issues/1130
