### ISSUE TITLE
apm install error

### ISSUE THREAD

**Issue by qianghaohao** [Glavin001/atom-beautify#1156]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.37.8/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node.lib
gyp http GET https://atom.io/download/atom-shell/v0.37.8/x64/node.lib
gyp WARN install got an error, rolling back install
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/x64/node.lib
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at TCP.onread (net.js:552:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Users\\qianghaohao\\AppData\\Local\\atom\\app-1.10.0-beta7\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\qianghaohao\\AppData\\Local\\atom\\app-1.10.0-beta7\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=0.37.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=ia32" "--ensure"
gyp ERR! cwd C:\Users\qianghaohao\.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

---------->How to solve this problem？

**Comment by prettydiff** [comment]
This appears to be a distribution problem either with APM or your connection.  It does not appear to be related to Atom Beautify.

**Comment by Glavin001** [comment]
> How to solve this problem？

I recommend contacting https://github.com/atom/apm
