### ISSUE TITLE
Issue when beautifying CSS

### ISSUE THREAD

**Issue by JamesCoyle** [Glavin001/atom-beautify#1158]
Probably not the place to report this issue but it seems to happen with all three CSS Beautifiers.

This CSS

    .toolbar :first-child {
        display: none;
    }

should not be changed to this

    .toolbar:first-child {
        display: none;
    }

as those selectors are not equivalent. The first selects the first child element within `.toolbar` elements whereas the second selects any `.toolbar` element that is the first child of its parent. It seems to happen with all three CSS beautifiers so I'm not sure where to report the issue really.

**Comment by prettydiff** [comment]
This is fine.  I will patch this into the next release of Pretty Diff and report this issue for the other two beautifiers.

**Comment by JamesCoyle** [comment]
Should be noted that is the case for all of the `:[first/last/nth]-child` and `:[first/last/nth]-of-type` selectors.

**Comment by bitwiseman** [comment]
@JamesCoyle @prettydiff - Please upgrade  to js-beautify@1.6.4.  This is fixed there.

**Comment by prettydiff** [comment]
@JamesCoyle You can get the latest dependencies by reinstalling Atom Beautify.  `apm install atom-beautify`
