### ISSUE TITLE
can not beautify .rb file 

### ISSUE THREAD

**Issue by kevin-jj** [Glavin001/atom-beautify#1159]
# Description

can not beautify .rb file using rubocop but manually can do it in command line using rubocop xxx.rb --auto-correct.

# Expected Results
To beautify the ruby code.

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/6e2f00f49842f135b20abc3fc86706e4

# Checklist

- [✔️ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [✔️  ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [✔️  ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Looks like an error occurred:
```
2016-08-28T02:39:11.616Z - debug: [beautifiers/beautifier.coffee] spawn done 1 /Users/liujun/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'rubocop' (>= 0.a) among 19 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/liujun/.rvm/gems/ruby-2.3.1:/Users/liujun/.rvm/gems/ruby-2.3.1@global', execute `gem env` for more information
    from /Users/liujun/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
    from /Users/liujun/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
    from /Users/liujun/.rvm/gems/ruby-2.3.1@mall/bin/rubocop:22:in `<main>'
    from /Users/liujun/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/liujun/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `<main>'

2016-08-28T02:39:11.617Z - verbose: [beautifiers/beautifier.coffee] spawn result 1  /Users/liujun/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'rubocop' (>= 0.a) among 19 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/liujun/.rvm/gems/ruby-2.3.1:/Users/liujun/.rvm/gems/ruby-2.3.1@global', execute `gem env` for more information
    from /Users/liujun/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
    from /Users/liujun/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
    from /Users/liujun/.rvm/gems/ruby-2.3.1@mall/bin/rubocop:22:in `<main>'
    from /Users/liujun/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/liujun/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

More specifically: `Could not find 'rubocop'`
Take a look at https://github.com/Glavin001/atom-beautify/issues/689 and https://github.com/Glavin001/atom-beautify/issues/548

**Comment by kevin-jj** [comment]
migrating RVM to Rbenv fixs this issue.

Your have to get rubocop gem installed in the rvm global path to solve this issue if using RVM.
