### ISSUE TITLE
Beautify RiotJS Tags

### ISSUE THREAD

**Issue by 20zinnm** [Glavin001/atom-beautify#1160]
RiotJS's .tag worked well until this update. It looks like this (both on prettydiff and in Atom):

```
<card-list>

  <ul class="pagination center-align"><li <a class{disabled: page<2}> href="#!"> <i class="material-icons">chevron_left</i>
</a>
</li>
<li class={active: page==1, waves-effect: page !=1}>
<a href="#!">1</a>
</li>
<li class="waves-effect">
<a href="#!">2</a>
</li>
<li class="waves-effect">
<a href="#!">3</a>
</li>
<li class="waves-effect">
<a href="#!">4</a>
</li>
<li class="waves-effect">
<a href="#!">5</a>
</li>
<li class="waves-effect">
<a href="#!">
  <i class="material-icons">chevron_right</i>
</a>
</li>
</ul>

<script>
var self = this;
</script>

</card-list>
```

**Comment by 20zinnm** [comment]
This might be a prettydiff issue. Will post there.

**Comment by 20zinnm** [comment]
https://gist.github.com/anonymous/f6c56177ee3e2775453a35d2304d0b46 is the debug log, I fixed some HTML issues to.

**Comment by prettydiff** [comment]
The problem is the `<` in the `page<2` portion.  I need to add this to my unit tests.  This is likely a regression defect from enhanced support to JSP tags.

**Comment by prettydiff** [comment]
I am looking at the code sample provided in the debug.md.  I added `{` and `}` as attribute delimiters, but the result still doesn't look right.  I see a closing `</i>` tag, but I don't see its start tag.  Would you mind taking a look?  I put up the latest change at the following address

http://prettydiff.com/ignore/testlocation/?m=beautify

**Comment by 20zinnm** [comment]
@prettydiff I had the opening tag, but when I "beautified" it the tags got messed up. I must've forgotten to put it back.

**Comment by 20zinnm** [comment]
That site, @prettydiff, didn't have an option for Riot tags and presumed it to be XML.

**Comment by prettydiff** [comment]
Yeah, don't worry about that.  Pretty Diff only has three parsers and only differentiates just enough to pick the right parser.  All other language options are just there in the case of syntax conflicts (if any).  In this case RiotJS only appears to conflict with JSX format, but I can distinguish between these two languages without additional configuration.

**Comment by prettydiff** [comment]
I can see this issue is still open.  @20zinnm could you provide a code sample that isn't corrupted by Pretty Diff so that I can see what Pretty Diff is doing to the original code?
