### ISSUE TITLE
addon apparently works, but does not write the php file

### ISSUE THREAD

**Issue by Sinejov** [Glavin001/atom-beautify#1162]
# Description

addon apparently works, but does not write the file
# Expected Results

The beautified code should have looked like:
whitout spaces and with {} fixed (?)
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist
- [yes ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [yes] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [yes ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [yes] Generated debugging information and added link for `debug.md` Gist to this issue

Attached debug file 
[debug.zip.zip](https://github.com/Glavin001/atom-beautify/files/443819/debug.zip.zip)

**Comment by Glavin001** [comment]
From your logs there is an error:

```
2016-08-30T01:12:34.294Z - debug: [beautifiers\beautifier.coffee] spawn D:\xampp\php\php.EXE 0=D:\xampp\php\php-cs-fixer.phar, 1=fix, 2=--level=PSR-2, 3=C:\Users\SWEETM~1\AppData\Local\Temp\temp116729-6992-1gp06bi.nngklqh0k9
2016-08-30T01:12:34.644Z - debug: [beautifiers\beautifier.coffee] spawn done 16 


  [Symfony\CS\ConfigurationException\InvalidConfigurationException]  
  The level "PSR-2" is not defined.                                  



fix [--config="..."] [--config-file[="..."]] [--dry-run] [--level="..."] [--fixers="..."] [--diff] [--format="..."] [path]



2016-08-30T01:12:34.644Z - verbose: [beautifiers\beautifier.coffee] spawn result 16  


  [Symfony\CS\ConfigurationException\InvalidConfigurationException]  
  The level "PSR-2" is not defined.                                  



fix [--config="..."] [--config-file[="..."]] [--dry-run] [--level="..."] [--fixers="..."] [--diff] [--format="..."] [path]

```

Your current configuration is:

```
{
    "indent_size": 2,
    "indent_char": " ",
    "indent_with_tabs": false,
    "cs_fixer_path": "D:\\xampp\\php\\php-cs-fixer.phar",
    "level": "PSR-2",
    "phpcbf_path": "D:\\xampp\\php\\php.exe",
    "standard": "D:\\xampp\\php\\php.exe",
    "fixers": "",
    "disabled": false,
    "default_beautifier": "PHP-CS-Fixer",
    "beautify_on_save": false
}
```

I recommend you change your value for `level` from `PSR-2` and look at https://github.com/FriendsOfPHP/PHP-CS-Fixer for more options.

There is an issue that errors are currently being ignored for PHP-CS-Fixer: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L45
I think this was done because PHP-CS-Fixer would throw strange return codes while not being an error. Will have to look into this more later.

**Comment by Sinejov** [comment]
I try levels PSR-0, PSR-1, PSR2 And synfony but nothing work...

PSR-0 : https://gist.github.com/anonymous/5b69d13f69076ae7724ceee349f5e4d4
PSR-1: https://gist.github.com/anonymous/7a0da4f55abef3bf9cc19a46d86744cb
symfony: https://gist.github.com/anonymous/c50f4f510107149575c9a949f36745fd

All PSR levels not defined to me :(. 

symfony is working on code, but dont write on my file, there is the result: 
spawn result 0 Fixed all files in 0.107 seconds, 4.500 MB memory used

On the console the following code: 
php "d:/xampp/php/php-cs-fixer.phar" fix "D:/xampp/htdocs/lavozinformatica/hola.php"

give me this: Fixed all files in 0.105 seconds, 4.500 MB memory used

My code look like the last debugs with a wrong }, spaces and ;

**Comment by Glavin001** [comment]
Unfortunately, I am not a PHP nor Synfony user. I recommend you ask for help over at https://github.com/FriendsOfPHP/PHP-CS-Fixer as they would be able to help you much better than I would. Best of luck! 😃

**Comment by Sinejov** [comment]
Thanks.

**Comment by Glavin001** [comment]
Closing this as a PHP-CS-Fixer issue.
