### ISSUE TITLE
Beautifying a file doesn't update atom's tab setting

### ISSUE THREAD

**Issue by garygreen** [Glavin001/atom-beautify#1163]
For example if you beautify a PHP file that was originally detected to use tabs and beautified it to PSR-2, Atom would still show as using tabs. Even once the file is saved, it's still using tabs. If you re-open the file, it will correctly detect it as using spaces.

The atom-beautify package should somehow tell atom that the file should now be formatted in 4 spaces, but it's not....

PS - I'm using the [tab control](https://atom.io/packages/tab-control) package to show what Atom has detected the indentation should be for the document.

**Comment by Glavin001** [comment]
Atom-Beautify intends to beautify/format the code based on the styles configured, such as via `.jsbeautifyrc` file, etc. This is useful for projects with multiple files that should all have clean code that looks the same. It does not detect any style settings from the current file and instead enforces the configuration set for the entire project.

**Comment by garygreen** [comment]
I think you possibly misinterpret the problem. Try to install the tab control package and then beautify an existing project from tabs to spaces, or vice versa - it will still show as using tabs/spaces until you close / open the file again.

**Comment by Glavin001** [comment]
The problem is that [Tab Control](https://atom.io/packages/tab-control) does not update the status indicator to tabs/spaces after Atom-Beautify correctly beautifiers the code to tabs/spaces?

![image](https://cloud.githubusercontent.com/assets/1885333/18108094/1bbfa786-6ee1-11e6-99cf-c1b0f4dcc017.png)

**Comment by garygreen** [comment]
@Glavin001 that's correct. Maybe it's a problem with the tab control package itself? Is beautify updating atom's tab setting when it beautify s the document?

**Comment by Glavin001** [comment]
That is a [Tab Control](https://atom.io/packages/tab-control) issue. 😉
