### ISSUE TITLE
Support for ES6 destructuring

### ISSUE THREAD

**Issue by mkermani144** [Glavin001/atom-beautify#1164]
It seems `atom-beautify` doesn't support ES6 destructuring:
Before applying `atom-beautify`:
```js
var {anAttribute} = anObject
```
After applying `atom-beautify`:
```js
var {
    anAttribute
} = anObject
```
Any idea?

**Comment by prettydiff** [comment]
What beautifier are you using?  It appears to work correctly with Pretty Diff but not JSBeautify.

@bitwiseman alerted for his awareness.

**Comment by bitwiseman** [comment]
@mkermani144 
If you try `brace-style=collapse-preserve-inline` you should get better behavior.  
Just to make sure I understand, the beautified output you show still works, right? It just isn't what you expect.

**Comment by mkermani144** [comment]
@bitwiseman Yeah, it works but it isn't what I want.

**Comment by mkermani144** [comment]
@prettydiff Yes, Pretty Diff works for me. 
@bitwiseman Using `brace-style=collapse-preserve-inline` works too.
So the issue is resolved.
