### ISSUE TITLE
Why Beatify JSX crashed?

### ISSUE THREAD

**Issue by nsklyarov** [Glavin001/atom-beautify#1165]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
  class DateField extends React.Component {
            render() {
                return ( <
                    div className = "App-searchForm-dateField" >
                    <
                    p > Дата отправления < /p> <
                    input type = "date"
                    name = "date" / >
                    <
                    /div>
                )
            }
        }
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/09cbf5ad714732e0ebd9c6f0bc8cc074
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
In the code sample from the gist class CitySelect appears to be missing a closing curly brace.  I entered the code sample into the web tools for Pretty Diff and JSBeautify and neither crashed.  I would have to attempt to reproduce later in Atom using the inspector.

Adding @bitwiseman in case he is aware of anything.

**Comment by bitwiseman** [comment]
I'm not aware of anything, but it looks like the "expected output" above looks like e4x is not turned on.

**Comment by unamoralez** [comment]
I got what it was. This happens when i try beatify * .js file containing syntax *.jsx

**Comment by Glavin001** [comment]
I would be happy to review and merge someone's Pull Request for Atom-Beautify's JS-Beautify beautifier changing `JSX` case to set `e4x` option at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/js-beautify.coffee#L36

**Comment by derwaldgeist** [comment]
I may not get this issue correctly, but I also have the problem that AtomBeautify completely "destroys" JSX files if they have the extension .js instead of .jsx. Unfortunately, this is the case in many React tutorials and also in the scaffolds Create React App is producing. I would love to see this supported in Atom, but unfortunately I am not deep enough into Atom to provide a PR for that.

**Comment by prettydiff** [comment]
@derwaldgeist The problem in that case is that jsbeautify requires an option setting to make JSX work correctly, which is not triggered if it doesn't have to be.

**Comment by derwaldgeist** [comment]
Ok, thanks for the info.

**Comment by prettydiff** [comment]
I just looked at this and the problem appears unchanged.
