### ISSUE TITLE
ERB - do/end should have inner code indented

### ISSUE THREAD

**Issue by jasonivers** [Glavin001/atom-beautify#1167]
# Description

code inside do/end (<% do %> <% end %>) should be indented.
# Expected Results

The beautified code should have looked like:

```
<ul>
  <% 3.times do |x| %>
    <li>This is item <%= x %></li>
  <% end %>
</ul>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/d0a31ccd2bc9bd02b5a1230e49fd01b0
# Checklist
- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [X] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Closing as Pretty Diff bug.

**Comment by NaldoColella** [comment]
This still doesnt work :(

**Comment by benjam1n** [comment]
Still happening :(

**Comment by Glavin001** [comment]
Please follow https://github.com/Glavin001/atom-beautify/issues/881 for any Pretty Diff updates. Pretty Diff is blocking this feature, not Atom-Beautify. Hopefully bugs like this will be resolved soon.
