### ISSUE TITLE
ERB Beautify does not indent inside <% if %> and <% end %>

### ISSUE THREAD

**Issue by jasonivers** [Glavin001/atom-beautify#1168]
# Description

When beautifying ERB files, indents inside <% if %> and <% end %> are removed.

This code should have the middle line indented:

```
<% if true %>
Show this
<% end %>
```
# Expected Results

The beautified code should have looked like:

```
<% if true %>
  Show this
<% end %>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

https://gist.github.com/anonymous/aab2b30a67e5535e9d4139aab8390d51
# Checklist
- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [X] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Closing as Pretty Diff bug.
