### ISSUE TITLE
Content inside <template> element no longer formatted in release : 0.29.11

### ISSUE THREAD

**Issue by jfletcher-nuxeo** [Glavin001/atom-beautify#1170]
# Description

The results of beautification are not what I expect.  Source:

```
<i
/>
  <template>
    <i
    />
</template>
```

# Expected Results

The beautified code should have looked like:

```
<i />
<template>
    <i />
</template>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/94f9ebc281dd0ab6945b56e413d8212f

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by valdrinkoshi** [comment]
A workaround to this is use Pretty Diff as Default Beautifier (Atom Settings -> Packages -> Atom Beautify -> HTML -> Default Beautifier)

**Comment by Glavin001** [comment]
Pretty Diff for the win! Thanks for letting us know @valdrinkoshi.
