### ISSUE TITLE
beautify on save .vue file not work

### ISSUE THREAD

**Issue by MAYDAY1993** [Glavin001/atom-beautify#1175]
I just set preferences in atom-beautify about beautify on save ,and it worked fine with single html and js files,but when I run into Vue to check the beautify on save and change a .vue file and save it ,it didn't work !I'm wondering why,what's wrong with my settings?
the following is my setting 
![image](https://cloud.githubusercontent.com/assets/14831051/18244199/5f43b592-7391-11e6-9fd4-8c1065e69fae.png)
this is the .vue file ,it turns out that the on save beautify didn't work
![image](https://cloud.githubusercontent.com/assets/14831051/18244104/e77e70ec-7390-11e6-9092-b6475c1e3833.png)

**Comment by iapYang** [comment]
Same issue occured on mine yesterday, have you solved it yet?

**Comment by MAYDAY1993** [comment]
@iapYang  not yet ,I checked out the docs,atom-beautify doesn't support .vue file to beautify .

**Comment by prettydiff** [comment]
Support appears to be provided:

* https://github.com/Glavin001/atom-beautify/blob/master/src/languages/vue.coffee - language
* https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/vue-beautifier.coffee - beautifier

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

---

Can you confirm this only occurs with `Beautify on save`? What if you manually trigger beautification, does it then work?
