### ISSUE TITLE
JSX inline style error

### ISSUE THREAD

**Issue by manhhailua** [Glavin001/atom-beautify#1176]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<h3>53<sup style={{
    fontSize: 20
  }}>%</sup>
</h3>
```
# Real result

```
       <h3>53<sup style={{
          fontSize: 20
  }}>%</sup>
        </h3>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Would you mind creating Atom Beautify's debug.md file and pasting it into a gist?  I am not sure which beautifier you are using.

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by manhhailua** [comment]
My bad! Here it is!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/6b06def8f46cf3c504b7070a5b21c0c1

**Comment by Glavin001** [comment]
Closing as Pretty Diff bug.
