### ISSUE TITLE
Respect the new `core.telemetryConsent` configuration option

### ISSUE THREAD

**Issue by lee-dohm** [Glavin001/atom-beautify#1179]
# Description

In Atom v1.11.0-beta0 a new Telemetry Consent system was introduced. The user's decision is stored at `core.telemetryConsent`. The three possible values are `undecided`, `no` and `limited`. The intent is that consent is given **if and only if** `limited` is chosen. The atom-beautify package should respect this decision also.
# Expected Results

When `core.telemetryConsent` is set to `undecided` or `no`, atom-beautify does not collect any data on the user's behavior or use of the package.
# Checklist
- **N/A** - I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- **N/A** - I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- **N/A** - Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Glad to see this built-in to Atom! If someone does not submit a Pull Request by this upcoming weekend, I'll implement it and publish a release. Thanks for letting me know!

**Comment by Glavin001** [comment]
Published to v0.29.23

**Comment by Glavin001** [comment]
![image](https://cloud.githubusercontent.com/assets/1885333/25234140/947b1b50-25b7-11e7-8ebc-0ae37420f13e.png)

![image](https://cloud.githubusercontent.com/assets/1885333/25234184/b41b4192-25b7-11e7-8185-a83829b48078.png)
