### ISSUE TITLE
[Vue Beautifier] Add preserve inline in braces option

### ISSUE THREAD

**Issue by Akryum** [Glavin001/atom-beautify#1180]
# Description

This new `brace_style` option should not add new lines in inlined attributes in objects, juste like it does for JavaScript (especially in imports).

Currently, we get:

```
<script type="module">
import {
  Publications
} from '../../names';
</script>
```
# Expected Results

The beautified code should have looked like:

```
<script type="module">
import { Publications } from '../../names';
</script>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by prettydiff** [comment]
Could you please generate Atom Beautify's debug.md file?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by Akryum** [comment]
https://gist.github.com/anonymous/f532f7ed37cfc10ec58a9b1b4e115328

**Comment by beebase** [comment]
@prettydiff Do you need more user information?

Is there a way to disable the wrapping? Code is becoming unreadable.
![image](https://cloud.githubusercontent.com/assets/446089/19591150/d18e8048-9775-11e6-8f08-16014511d5ce.png)

**Comment by prettydiff** [comment]
Thanks for the update.  I need to look more into this.  At this time though all my attention is directed to: https://github.com/prettydiff/biddle/

**Comment by prettydiff** [comment]
I would recommend opening a Pretty Diff issue at https://github.com/prettydiff/prettydiff

**Comment by daggerjames** [comment]
+1, 
as discuss above, looking forward to be solved.

**Comment by Cedric-song** [comment]
mark

**Comment by Minasokoni** [comment]
+1

**Comment by prettydiff** [comment]
Fixed in the latest version of Pretty Diff which is now in Atom Beautify.

**Comment by Minasokoni** [comment]
@prettydiff Sorry, im confused here, Vue Beautifier is still the only and default Beautifier for Beautifying .vue files. Is there a way to add Pretty Diff?

**Comment by prettydiff** [comment]
@Minasokoni Good catch.  Perhaps I am being too aggressive in cleaning up old issues.
