### ISSUE TITLE
Debug issue #1

### ISSUE THREAD

**Issue by Ancisuce** [Glavin001/atom-beautify#1183]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/5263b517e20d42642ab3832df4aa89e8

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Would you mind describing the problem in more detail?

**Comment by Ancisuce** [comment]
Sorry, my English level is low. So I don't remember how did & why did I send this issue to here. Can you close it?

**Comment by prettydiff** [comment]
Yes, thank you.
