### ISSUE TITLE
Does nothing to incomplete HTML

### ISSUE THREAD

**Issue by JamesCoyle** [Glavin001/atom-beautify#1185]
It seems that any HTML files without the html or body tags do not get beautified. It would be nice if they were appropriately indented regardless of whether they are fully formed HTML documents or not.

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by JamesCoyle** [comment]
Ah I just realized I'm using a `.php` file (out of habit) which is why the indentation isn't working.

**Comment by JamesCoyle** [comment]
Why doesn't the html in PHP files get beautified?

**Comment by Glavin001** [comment]
The PHP beautifiers don't appear to support HTML and then the HTML beautifiers don't support PHP. 
Related issues: 
- https://github.com/Glavin001/atom-beautify/issues/484
- https://github.com/Glavin001/atom-beautify/issues/457#issuecomment-162086934
- https://github.com/Unibeautify/unibeautify/issues/4

I am working on rewriting Atom-Beautify using a new core library, [Unibeautify](https://github.com/Unibeautify/unibeautify/), which I plan to have a way to beautify HTML and PHP both separately, with their respective beautifiers, and merge the result back together.

**Comment by JamesCoyle** [comment]
Could you not just run the HTML beautifier after the PHP one? I doubt I've exhaustively tried every eventuality but from my testing it seems to work well enough. The php tags should just be treated as a normal HTML tag from what I can see. An option in the PHP settings to also trigger a HTML beautification would be awesome. 

Glad to hear it's being worked on though.

**Comment by Glavin001** [comment]
> Could you not just run the HTML beautifier after the PHP one?

Yeah I described the wrong feature 😜. There is one new feature for running a list of beautifiers (such as PHP then HTML or two different JavaScript beautifiers, etc) and another more complex feature for languages like Vue ( #722 ) that will detect different pieces as different languages and apply the appropriate beautifier. Regardless, languages such as PHP should be seeing an improvement in future releases, once I am done with developing Unibeautify v1.

**Comment by prettydiff** [comment]
@JamesCoyle I recently extended the js parser in Pretty Diff to support C#, Java, and TypeScript.  It is not currently on my agenda, but I could also extended it to support PHP.
