### ISSUE TITLE
why did not to beautify PHP?

### ISSUE THREAD

**Issue by gychg** [Glavin001/atom-beautify#1188]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/8b034214bf18ab50ad05e400755465c1
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
It looks like the beautifier did run:

```
2016-09-12T03:30:20.727Z - debug: [beautifiers\beautifier.coffee] spawn D:\nmp\php\php.EXE 0=D:\atom\php-cs-fixer.phar, 1=fix, 2=C:\Users\jommy\AppData\Local\Temp\temp116812-7612-s2rv7b.4arcm78pvi
2016-09-12T03:30:20.884Z - debug: [beautifiers\beautifier.coffee] spawn done 0  Fixed all files in 0.073 seconds, 6.000 MB memory used
```

If you expected a change then maybe there is a bug in [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). I recommend asking over there and trying `php-cs-fixer` manually from command line to confirm.
