### ISSUE TITLE
LESS output includes extra newline at the end of every style

### ISSUE THREAD

**Issue by ghost** [Glavin001/atom-beautify#119]
I have code as:

```
.gray-lighter {
  color: @gray-lighter;
}

.label-gray-lighter {
  color: @gray-lighter;
}

.label-md {
  font-size: @font-size-base;
  font-weight: normal;
}
```

Just pressing Ctrl+Alt+B and i have:

```
.gray-lighter {
  color: @gray-lighter;

}
.label-gray-lighter {
  color: @gray-lighter;

}
.label-md {
  font-size: @font-size-base;
  font-weight: normal;

}
```

I've read about prettydiff. How can i use it in Atom?

**Comment by yaroshevych** [comment]
This issue is resolved in prettydiff@1.7.2. To upgrade, you may drop your ```.atom/packages/atom-beautify/node_modules``` folder, navigate to ```.atom/packages/atom-beautify``` and reinstall packages with ```npm install```.
