### ISSUE TITLE
PHP code not beautifying on Windows

### ISSUE THREAD

**Issue by ShreyanshLodha** [Glavin001/atom-beautify#1194]
# Description

I am a windows user using your Beautify, works beautifully on all the languages but I recently started development in PHP and I downloaded PHP-CS-FIXER and also I have set the location in the settings.
It run and give no error, but it does not beautify the code
I tried using PHPCBF but nothing works.

Please help me out.

```
"atom-beautify":
    php:
      beautify_on_save: true
      cs_fixer_path: "C:\\PHP-CS-Fixer-1.12\\PHP-CS-Fixer-1.12\\php-cs-fixer"
      phpcbf_path: "C:\\PHPCBF\\PHP_CodeSniffer-master\\scripts\\phpcbf"
      fixers: "",
      level: ""
```

**Comment by guzuomuse** [comment]
+1

**Comment by mintjustin** [comment]
I think a fix was provided but it is broken again. Was it something about "php" command before "php-cs-fixer"?

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
