### ISSUE TITLE
PrettyDiff's space in paren (bracepadding) unexpected behavior

### ISSUE THREAD

**Issue by qwemaze** [Glavin001/atom-beautify#1197]
# Description

Unexpected in _space_in_paren (bracepadding)_ is:
- a space in empty parentheses
- square brackets not being processed
- if contents contain line break it's not processed, which is supposed to be a thing according to Pretty Diff docs, but still seems kind of lame to me, correct me if there's something to it
  
  > Inserts a space after the start of a container and before the end of the container in JavaScript if the contents of that container are not indented; such as: conditions, function arguments, and escaped sequences of template strings.
# Expected Results

``` js
"use strict";

const express = require( 'express' );
const ext = require( '../dbmodel' );
const requireDir = require( '../requireDir' );
const rest = require( '../lib/rest' );
const CRUDAPI = require( '../lib/API' );
const config = require( "../config" );
const Log = config.LOG( 'app:router' );

const router = express.Router();

const models = {};
Object.keys( ext ).map( ( modelname ) => {
    models[ modelname ] = ext[ modelname ].model.source();
} );

router.get( "/init", ( req, res ) => {
    return res.json( {
        result: {
            user: req.user,
            models: models,
            API: CRUDAPI
        }
    } );
} );

Object.keys( ext ).map( modelname => {
    let mRouter = express.Router();
    ext[ modelname ].useRouter && ext[ modelname ].useRouter( mRouter, modelname );
    rest( modelname, mRouter );
    router.use( `/${ modelname }`, mRouter );
} );

const routes = requireDir( './router/routes' );

Object.keys( routes ).map( ( route ) => {
    router.use( `/${ route }`, routes[ route ] );
} );

module.exports = router;

```
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/42718cec93bf6ae3edf47badea134e20

**Comment by prettydiff** [comment]
Could you provide me a code example for the third bullet point?  This will ensure I am following you.  I also found an additional defect.  For some reason the final router.use was not getting the padding in the latest version of Pretty Diff.

**Comment by qwemaze** [comment]
Thanks for quick response!

Sample for third bullet point:
before
```js
router.get( "/init", ( req, res ) => {
    // things
} );
```
after
```js
router.get("/init", ( req, res ) => {
    // things
});
```

**Comment by prettydiff** [comment]
Thanks, I will work on this today.

**Comment by prettydiff** [comment]
This appears to be fixed in the latest version of Pretty Diff and Pretty Diff 2.x is now in Atom Beautify.
