### ISSUE TITLE
Don't work with composer global instalation of php-cs-fixer

### ISSUE THREAD

**Issue by odahcam** [Glavin001/atom-beautify#1199]
# Description

Nothing happens.
# Expected Results

The code obviously should be beautified.

``` php
<?php

if(true){
die();
          }
```
# Steps to Reproduce
1. Install `php-cs-fixer` on Windows with Composer: `composer global install friendsofphp/php-cs-fixer`
2. Add code to Atom editor
3. Run command `Atom Beautify: Beautify Editor`
4. This  code was not beautified.
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/0849b1590ac7a38cd7d604941ac36135
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by guzuomuse** [comment]
+1

**Comment by Larandar** [comment]
The same for me, here is my debug.md : https://gist.github.com/anonymous/5c6919e11d2290bd87fa605c4e23a2be#results

It's quite problematic since it don't allow to beautifier at all for PHP, I still use the command line and it work well.

**Comment by Glavin001** [comment]
Looking at the debug logs provided:

```
2016-09-16T17:37:31.328Z - debug: [beautifiers\beautifier.coffee] spawn C:\xampp\php\php.EXE 0=C:\Users\H2K\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=C:\Users\H2K\AppData\Local\Temp\temp116816-6468-j1efk4.znz40u23xr
2016-09-16T17:37:31.386Z - debug: [beautifiers\beautifier.coffee] spawn done 0  @ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../friendsofphp/php-cs-fixer/php-cs-fixer
php "%BIN_TARGET%" %*
```

It is executing the command:

```bash
C:\xampp\php\php.EXE C:\Users\H2K\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT fix FILE
```

The `C:\Users\H2K\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT` part is incorrect. It should be a `.php` file not a `.BAT` file. 

You can see that PHP-CS-Fixer Path (key `cs_fixer_path`) is not set: https://gist.github.com/anonymous/0849b1590ac7a38cd7d604941ac36135#final-options
I recommend finding the `.php` executable for PHP-CS-Fixer and setting the `cs_fixer_path` config setting.

**Comment by odahcam** [comment]
So why running the global path `php-cs-fixer` works?

The only way I could make this work in Atom was adding a path to `C:\php\php-cs-fixer.phar`.

**Comment by Glavin001** [comment]
> So why running the global path php-cs-fixer in CLI works?

I would suppose it is the `php` being the executable with `php-cs-fixer`'s path as the second argument: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L37-L38
Thus resulting in:

> C:\xampp\php\php.EXE 0=C:\Users\H2K\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=C:\Users\H2K\AppData\Local\Temp\temp116816-6468-j1efk4.znz40u23xr

I think there was a reason why the contributor(s) chose to implement it in this way. However, I do not use Windows or PHP so I am not familiar with these issues.

I recommend submitting a Pull Request changing the implementation of PHP-CS-Fixer beautifier for Windows case: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L37-L38

My suggestion would be something like this:

```coffeescript
isBatFile = phpCSFixerPath.toLowerCase().endsWith(".bat")
if isBatFile
  @run(phpCSFixerPath, ...
else
  @run("php", [
            phpCSFixerPath,
            ...
```

In this way if it is the `.php` or `phar` file it will work as before and with the `.bat` extension it will now work.

**Comment by odahcam** [comment]
I could not get it to work. :(
I'm shity with coffee, so I can't understand what is happening.

**Comment by Glavin001** [comment]
I think https://github.com/Glavin001/atom-beautify/pull/1510 may resolve this issue 😃 .
