### ISSUE TITLE
s

### ISSUE THREAD

**Issue by VladymyrVr** [Glavin001/atom-beautify#1203]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/017b12d87a73728b77587e914c67e7bf

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Thanks for the debug.md file.  Would you mind quickly describing the problem?  It will help us know what to look for.

**Comment by Glavin001** [comment]
Once we have more information this issue can be reopened. Thank you.
