### ISSUE TITLE
Beautify HTML within PHP

### ISSUE THREAD

**Issue by streamworksaudio** [Glavin001/atom-beautify#1204]
Hi,

Thanks for this great package!  

I was wondering, is it possible (or is planned) to select some HTML within a PHP file and beautify it using the HTML beautifiers? 

Cheers

**Comment by vnt** [comment]
I need html + php, how do you activate it?

**Comment by Glavin001** [comment]
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/457 feature request.
