### ISSUE TITLE
.

### ISSUE THREAD

**Issue by aruhirin** [Glavin001/atom-beautify#1206]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/d3574aa6fefe89db35dca69dc8917bb7
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by alexlur** [comment]
Would you mind describing the problem in more detail?

**Comment by aruhirin** [comment]
Installing “emmet@2.4.3” failed.
help me plz.
[http://imgdb.kr/akdM](url)

**Comment by prettydiff** [comment]
It seems there are defects in the code sample that will interfere with beautification.  Consider this part from the code sample:

    2008년 9월 18일에 <미아>라는 하이브리드 팝이라는

The `<` and `>` should be encoded because `<미아>` looks like a tag.  Instead try: `&lt;미아&gt;`

**Comment by prettydiff** [comment]
Here is the code sample corrected: https://gist.github.com/prettydiff/9e640ad19cab23d8d4f4e801a2c010cf
