### ISSUE TITLE
Lost Ability to use CSSComb for .sass files

### ISSUE THREAD

**Issue by ChrisSargent** [Glavin001/atom-beautify#1208]
It seems since the last update I can no longer select CSSComb for .sass files? But I can select it for .scss / .less / .css files.

If I change the config file manually with `default_beautifier: "CSScomb"` it gets deleted as soon as I start Atom.

**Comment by ChrisSargent** [comment]
Looks like this was maybe removed because of it not working correctly. Apparently the Sassconvert is much more reliable for sass files. And I've installed a separate CSSComb package for sorting. It's true I use to have some issues when running this on Sass files and it would corrupt some of the indents etc, which is hard to debug, and it didn't work for longer selectors.

**Comment by prettydiff** [comment]
Is there a change to the current settings you would recommend?

**Comment by ChrisSargent** [comment]
By the looks of it, I think the issues are in csscomb rather than the beautifier. As far as a change goes, I guess it would be nice to still select csscomb for sass files because it's very handy, but with the caveat that it's not 100% reliable (and then I guess I'll open an issue with them and see if we can get to the bottom of it :-)).

**Comment by prettydiff** [comment]
Awesome!  Thanks for contributing.

**Comment by Glavin001** [comment]
For those interested, CSSComd support could be added again by submitting a Pull Request reverting some of the changes made by https://github.com/Glavin001/atom-beautify/pull/1141
