### ISSUE TITLE
Issue with Debug

### ISSUE THREAD

**Issue by physcocode** [Glavin001/atom-beautify#1224]
# Description
Atom Beautifier: Help Debug Editor does not output anything

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Help Debug Editor`
3. Nothing is displayed after clicking ok.

![screen shot 2016-09-25 at 9 41 04 pm](https://cloud.githubusercontent.com/assets/7591484/18816490/cf7e592a-8368-11e6-8507-eddc473d0d9d.png)

**Comment by Glavin001** [comment]
Published to v0.29.13.

**Comment by physcocode** [comment]
Thank you so much 😁

**Comment by physcocode** [comment]
@Glavin001 debug is now working perfect
