### ISSUE TITLE
php-cs-fixer not working

### ISSUE THREAD

**Issue by physcocode** [Glavin001/atom-beautify#1225]
# Description

shows php-cs-fixer error even though its installed properly
![screen shot 2016-09-25 at 9 20 48 pm](https://cloud.githubusercontent.com/assets/7591484/18816373/0cfd7a9a-8366-11e6-93bc-e5bea5bb2780.png)

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Php-cs-fixer not found!
# Debug

Nothing is output/gist is form  on Atom Beautify:Help Debug Editor #1224 

# Checklist

- [x] Running which php outputs : 

![screen shot 2016-09-25 at 9 24 42 pm](https://cloud.githubusercontent.com/assets/7591484/18816388/839d4626-8366-11e6-9238-0ff895ba0344.png)
- [x] Running which php-cs-fixer outputs: 

![screen shot 2016-09-25 at 9 25 31 pm](https://cloud.githubusercontent.com/assets/7591484/18816399/b2d39dfa-8366-11e6-9c9f-0de43a1314b9.png)
- [x] Running Atom Beautify:Help Debug Editor outputs nothing #1224 

- [x] Added php-cs-fixer path still error persists : 

![screen shot 2016-09-25 at 9 27 56 pm](https://cloud.githubusercontent.com/assets/7591484/18816413/fade42bc-8366-11e6-875c-5222604e435f.png)

#Additional info
- Tried steps from #394 #584 with no success.
- If debug information was printed i could have self helped myself

**Comment by physcocode** [comment]
@Glavin001 Debug File: https://gist.github.com/anonymous/2ebcad7854e30b8640d7a032262a45e4
The path seems correct ! whats the issue?

**Comment by Glavin001** [comment]
It looks like `cs_fixer_path` is not used for Mac/Linux only Windows: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L66

```
  cs_fixer_path: '/Users/pranjalp/.composer/vendor/bin/php-cs-fixer',
```

For Mac/Linux it uses the `PATH` environment variable:

```
PATH=/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Applications/XAMPP/xamppfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pranjalp/Desktop/caddy/:/opt/X11/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Applications/XAMPP/xamppfiles/bin
```

I recommend adding `/Users/pranjalp/.composer/vendor/bin/` to your `PATH` and it should work. If not, re-run Help Debug Editor again and we can see what the next issue is.

**Comment by physcocode** [comment]
Manually adding PATH to the paths file fixed the issue . Hats off to your support @Glavin001
10/10 to this package ! Thank you :)

**Comment by Glavin001** [comment]
Awesome to hear, @physcocode! Let me know if you need anything else. Hopefully the next version of Atom-Beautify will be less prone to these kinds of errors 😃 .
