### ISSUE TITLE
loop “for” have a problem for PHP

### ISSUE THREAD

**Issue by gychg** [Glavin001/atom-beautify#1229]
original::

> for ($i = 0; $i <= $maxNum; **$i++**) { }

transform::

> for ($i = 0; $i <= $maxNum; **++$i**) { }

**Comment by prettydiff** [comment]
This is likely a problem with the beautifier.  Could you please generate the debug.md file so that we can direct this problem to the correct people?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by Glavin001** [comment]
Closing this as it will be a third-party bug, likely PHP-CS-Fixer or another beautifier. Without the debugging information there is nothing more we can help with.
