### ISSUE TITLE
的

### ISSUE THREAD

**Issue by hzcfy** [Glavin001/atom-beautify#1231]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/a2ccdaf3668005fc5252278ba1fd9408

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I can see your provided debug.md file.  There is not a description of the problem, so I am guessing the problem is the excess indentation inside the class.  Alerting @bitwiseman

**Comment by Glavin001** [comment]
The issue is the results are `null` (was not beautified).
This is because `JavaScript` language has `disabled` set to `true`.

Snippet from logs:
```
 js: 
     { beautify_on_save: true,
       break_chained_methods: true,
       disabled: true,
```

See Final Options: https://gist.github.com/anonymous/a2ccdaf3668005fc5252278ba1fd9408#final-options

```
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false,
    "beautify_on_save": true,
    "break_chained_methods": true,
    "disabled": true,
    "end_with_comma": true,
    "end_with_newline": true,
    "eval_code": true,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "space_in_paren": false,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "unescape_strings": false,
    "wrap_line_length": 0,
    "default_beautifier": "JS Beautify"
}
```

See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#javascript for more options.
