### ISSUE TITLE
Spaces added after <code> block

### ISSUE THREAD

**Issue by nahumj** [Glavin001/atom-beautify#1237]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
                    <p>An if-statement may optionally be followed by an <code>else</code> command and a second statement. The second statement is executed if and only if the condition expression evaluated to zero and the first statement was skipped. The <code> else </code> 
                    must bind to the most recent paired if statement. </p>
```
# Actual results

The beautified code looks like:

```
                    <p>An if-statement may optionally be followed by an <code>else</code> command and a second statement. The second statement is executed if and only if the condition expression evaluated to zero and the first statement was skipped. The <code> else </code>                    must bind to the most recent paired if statement.
```

There's a strange series of spaces introducted after the closing code block. It seems to not add the appropiate newline character.
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/6a4a0f778544cbe834a1a03c6e62cdee
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I can reproduce this issue on http://jsbeautifier.org/ when using the using the "wrap lines near 80 characters" option.  Alerting @bitwiseman

**Comment by Glavin001** [comment]
Closing as a JS-Beautify bug.
