### ISSUE TITLE
Format *.php file with html inserts

### ISSUE THREAD

**Issue by Rad1calDreamer** [Glavin001/atom-beautify#125]
Hi,
Does it can format templates.php like java ide (netbeans)? 
example: 
format from 
![1](https://cloud.githubusercontent.com/assets/7055577/4715514/13190b08-58ff-11e4-851e-c426057741f3.png)

to 
![2](https://cloud.githubusercontent.com/assets/7055577/4715517/1e51c8b6-58ff-11e4-922b-4975ced15a4c.png)

**Comment by ffsantos92** [comment]
Why not use [PHP Coding Standards Fixer](http://cs.sensiolabs.org) instead of PHP_Beautifier?

**Comment by Glavin001** [comment]
That looks great! Might be a very good idea to switch to using that instead. Thanks for sharing. 

—

**Comment by Glavin001** [comment]
Will be switching to PHP Coding Standards Fixer with #175
