### ISSUE TITLE
Atom-Beatify not respons

### ISSUE THREAD

**Issue by opikhidayat** [Glavin001/atom-beautify#1259]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/e9b1ea1349ffa8d0fbf2035fb49fe1fc
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
```
2016-10-10T12:31:44.158Z - debug: [beautifiers/beautifier.coffee] spawn /usr/local/bin/php-cs-fixer 0=fix, 1=/tmp/temp116910-1931-cm1hra
2016-10-10T12:31:44.189Z - debug: [beautifiers/beautifier.coffee] error Error: spawn EACCES
```

The error is `Error: spawn EACCES` and you may need to change the file permissions so it is executable: http://stackoverflow.com/a/19026627/2578205

```bash
sudo chmod -R a+rwx /usr/local/bin/php-cs-fixer
```

**Comment by trevorhreed** [comment]
Changing file permissions did not resolve this for me. I'm still getting the same error message.

**Comment by szeck87** [comment]
@trevorhreed What OS are you on?

**Comment by trevorhreed** [comment]
MacOS (High Sierra)
