### ISSUE TITLE
error

### ISSUE THREAD

**Issue by opikhidayat** [Glavin001/atom-beautify#1264]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/05ad64f7cefdacbbbb7139898ddadef9
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Would you mind describing the error in more detail?  I looked at the debug.md file and noticed that this is JavaScript code beautified with JSBeautifier.  I ran the code through their online tool and everything looked good there.

I notice this problematic code in your original code sample:

    Promise.prototype._onCancel = function() {};
    Promise.prototype._setOnCancel = function(handler) {;
    };
    Promise.prototype._attachCancellationCallback = function(onCancel) {;
    };
    Promise.prototype._captureStackTrace = function() {};
    Promise.prototype._attachExtraTrace = function() {};
    Promise.prototype._clearCancellationData = function() {};
    Promise.prototype._propagateFrom = function(parent, flags) {;;
    };

The second and final promise contain extraneous semicolons that would cause an error.  Is this what you mean?
