### ISSUE TITLE
convert unicode python dictionary to formated json.

### ISSUE THREAD

**Issue by aidanmelen** [Glavin001/atom-beautify#1265]
# Description

I would this package to convert python unicode dictionaries into json. the solution is to:
find occurrences pf **u ', u', '** and replace with **"**.
# Input Before Beautification

This is what the code looked like before:

``` json
{
    u 'firstName': 'John',
        u 'lastName': 'Smith',
        u 'isAlive': true,
        u 'age': 25,
        u 'address': {
            u 'streetAddress': '21 2nd Street',
            u 'city': 'New York',
            'state': 'NY',
            u 'postalCode': '10021-3100'
        },
        'phoneNumbers': [
            {
                u 'type': 'home',
                u 'number': '212 555-1234'
    },
            {
                u 'type': 'office',
                u 'number': '646 555-4567'
  },
            {
                u 'type': 'mobile',
                u 'number': '123 456-7890'
    }
  ],
        u 'children': [],
        u 'spouse': null
}
```
# Expected Output

The beautified code should have looked like this:

``` json
{
    "firstName": "John",
        "lastName": "Smith",
        "isAlive": true,
        "age": 25,
        "address": {
            "streetAddress": "21 2nd Street",
            "city": "New York",
            "state": "NY",
            "postalCode": "10021-3100"
        },
        "phoneNumbers": [
            {
                "type": "home",
                "number": "212 555-1234"
    },
            {
                "type": "office",
                "number": "646 555-4567"
  },
            {
                "type": "mobile",
                "number": "123 456-7890"
    }
  ],
        "children": [],
        "spouse": null
}
```
# Actual Output

The beautified code actually looked like this:

it currently does not do this, but it would be nice.
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
This functionality would need to be integrated into a new or existing beautifier.  I believe the current Python beautifier is autopep8.

At first it sounds as easy as performing a trivial string replacement, but this will require a formal parser.

**Comment by aidanmelen** [comment]
i think it would be a very slick feature. please post if there is any new developments on this. thanks.
