### ISSUE TITLE
PHP beautification,how to change scene

### ISSUE THREAD

**Issue by ysling** [Glavin001/atom-beautify#1274]
it working like this:

```php
class IndexController extends Controller
{
    public function index()
    {
        $arr['num'] = 15;
    }

public function zz()
{
    for ($k = 0; $k < $h; ++$k) {
        $jj += $k."\r\n";
    }
}

}
```

However, I want to make it look like this:

```php
class IndexController extends Controller {
    public function index() {
        $arr['num'] = 15;
    }

public function zz() {
    for ($k = 0; $k < $h; ++$k) {
        $jj += $k . "\r\n";
    }
}

}
```

How should I do?

**Comment by prettydiff** [comment]
First determine which beautifier you are using for PHP.  Atom Beautify contains two or three PHP beautifiers each likely having their own options.

**Comment by ysling** [comment]
@prettydiff https://packagecontrol.io/packages/phpfmt

<?php
for($i = 0; $i < 10; $i++)
{
if($i%2==0)
echo "Flipflop";
}

#I want this effect
<?php
for ($i = 0; $i < 10; $i++) {
  if ($i%2 == 0) {
    echo "Flipflop";
  }
}

**Comment by prettydiff** [comment]
@ysling To preserve the literal formatting and white space around the code wrap the code in back ticks like this:  &#096;example&#096; or precede each line with 4 spaces.

**Comment by ysling** [comment]
@prettydiff 
I mean how to apply ② mode
https://atom-china.org/uploads/default/original/1X/e6b15c1241f3e26f3ad6ddb6bfdba42c686aba94.jpg

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
