### ISSUE TITLE
php-cs-fixer not run

### ISSUE THREAD

**Issue by opikhidayat** [Glavin001/atom-beautify#1276]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/3f42094a6f6e3caaf76f2864c8b1ae1c
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
> Original File Path: /home/ujank/.atom/packages/atom-beautify/package.json

Looking at your `debug.md`, this is not a PHP file and is instead a `JSON` file being correctly processed.

Please generate a correct `debug.md` if you still need help.
