### ISSUE TITLE
atom-beautify on the php array does not work

### ISSUE THREAD

**Issue by ysling** [Glavin001/atom-beautify#1281]
![9](https://cloud.githubusercontent.com/assets/22723099/19465465/0f6254e4-9537-11e6-83b2-4e741902203a.jpg)

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
