### ISSUE TITLE
Unexpected spaces added to quoted strings

### ISSUE THREAD

**Issue by AsciiSmoke** [Glavin001/atom-beautify#1282]
# Description

For some reason beautifying is inserting random spaces in quoted strings 
# Input Before Beautification

This is what the code looked like before:

```
<script type="text/javascript" src="/js/mailcheck.js?u=<%=ConfigurationManager.AppSettings("UpdateNumber")%>">
            </script>
```
# Expected Output

The beautified code should have looked like this:

```
<script type="text/javascript" src="/js/mailcheck.js?u=<%=ConfigurationManager.AppSettings("UpdateNumber")%>"></script>
```
# Actual Output

The beautified code actually looked like this (note the spaces around the string argument in the ASP.Net tag):

```
<script type="text/javascript" src="/js/mailcheck.js?u=<%=ConfigurationManager.AppSettings(" UpdateNumber ")%>"></script>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/f49d6bb2602eeb4a3f236066609d01ee

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Closing this as a JS-Beautify issue. See https://github.com/beautify-web/js-beautify/issues/943#issuecomment-254681926 for explanation.

**Comment by prettydiff** [comment]
I just looked at this again and it seems the code samples are defective.  The extra spaces appear because you are nesting double quotes inside a double quoted attribute value, which really means you are ending the attribute value and creating a new attribute value.  Instead use single quotes for the nested values.

**Comment by AsciiSmoke** [comment]
@prettydiff; yes you are correct and I can see why beautify see's it that way. Unfortunately this is perfectly valid .net markup and the contents of the '<%' and '%>' are rendered on the server before the markup is sent to the page.

In this instance I can get around the problem by using single quotes on the html src attribute but there will likely be cases where this is not possible for one reason or another.

Happy to close the ticket for now but it would be great if beautify could recognise strings within server-side tags as separate from regular markup (long-shot, I know).

Thanks
