### ISSUE TITLE
Whenever I tried to indent of HTML(Angular), It indent by default setting.

### ISSUE THREAD

**Issue by rahulgupta20nov** [Glavin001/atom-beautify#1283]
Hi, I am using indentation of 2 space in my project. For all file indentation working fine, but For HTML(Angular) this indentation takes default setting (indent space = 4).

If I change it HTML(Angular) => HTML, Then it takes 2 indent space. 

I try to find the solution, But any solution not working for me.

Please gi
ve me solution for that, Because I am a big fan of Atom and Atom beautify.
Thanks.

**Comment by NodeJoSe** [comment]
You need to configure the EJS setting on atom-beautify, thise are the settings for HTML (Angular)

**Comment by NodeJoSe** [comment]
Also, i would like to be able to use js beautify on my HTML (Angular) files, but EJS config only supports Pretty Diff

**Comment by prettydiff** [comment]
@NodeJoSe submit a pull request with your desired change.

**Comment by rahulgupta20nov** [comment]
please tell me, where I will get EJS setting, what need to change in EJS setting.

**Comment by Glavin001** [comment]
@rahulgupta20nov : Here is the documentation for options you can configure: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#ejs
