### ISSUE TITLE
Apple .plist support

### ISSUE THREAD

**Issue by pnerum** [Glavin001/atom-beautify#1284]
Description

I would like to see support for Apple .plist xml files.
If I beautify a plist file I get an error:

> Atom Beautify could not determine a supported beautifier to handle this file with grammar "Property List (XML)" and extension "plist". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by bochoven** [comment]
I would like to up vote this!

**Comment by prettydiff** [comment]
Just submit a pull request to extend XML beautification to support the .plist file extension:

https://github.com/Glavin001/atom-beautify/blob/master/src/languages/xml.coffee

**Comment by Glavin001** [comment]
Closed by https://github.com/Glavin001/atom-beautify/pull/1335

**Comment by Glavin001** [comment]
Published to v0.29.15
