### ISSUE TITLE
Allow elm-format path to be configured

### ISSUE THREAD

**Issue by zakaluka** [Glavin001/atom-beautify#1286]
# Description

Cannot specify the path to elm-format.  This is especially a concern when elm-format is not on the execute search path.
# Expected Output

Code should be beautified
# Actual Output

Atom display error message stating that elm-format is not found.
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Error message is displayed.
# Checklist

I have:
- [N/A] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [N/A] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [Yes] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [N/A] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [N/A] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
You are correct, there is not configuration option for `elm-format` executable: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/elm-format.coffee#L18

However, it should not be necessarily if your `PATH` environment variable is configured properly.

Regardless, I will leave this issue open as adding a configurable path is a good idea for those who do not know how to change their environment variables, thus making it easier to setup. I'd be happy to review and merge a Pull Request from someone else implementing this. Thanks in advance!

**Comment by Neppord** [comment]
I like to be able to use the elm-format installed in the projects node_modules. This relative path would hopefully be easy to add in the drop down with the static one.

But also being able to configure it per project would work.
