### ISSUE TITLE
Preserve braces in same line for php code

### ISSUE THREAD

**Issue by 50l3r** [Glavin001/atom-beautify#1292]
I want to preserve brackets in the same line after beautify

The results of beautification are not what I expect.

```
<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Inicio extends Ubiety_Controller
{
    public function index()
    {
        echo $this->mustache->render('Hello, {{planet}}!', array('planet' => 'Damn')); // "Hello, World!"
    }
}
```

The beautified code should have looked like this:

```
<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Inicio extends Ubiety_Controller{
    public function index(){
        echo $this->mustache->render('Hello, {{planet}}!', array('planet' => 'Damn')); // "Hello, World!"
    }
}
```

I have:
- Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- Reloaded (or restarted) Atom to ensure it is not a caching issue
- Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- Use PHPCBF instead PHP-CS-FIXER

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
