### ISSUE TITLE
Windows - php beautifier not working

### ISSUE THREAD

**Issue by craigfanman** [Glavin001/atom-beautify#1297]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/6cb9c451ba5ea1dbdf3d3906b5980a7a
# Checklist
- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [X] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
What is your expected results?

This issue can be reopened once we have completed information.
