### ISSUE TITLE
Auto remove number and multiplication sign

### ISSUE THREAD

**Issue by LiangHanLyu** [Glavin001/atom-beautify#1302]
# Description

12*60*60*1000 
become 
12 *1000
# Input Before Beautification

Cookie.set('token', 111, {expires: 12*60*60*1000});
# Expected Output

Cookie.set('token', 111, { expires:  12 \* 60 \* 60 \* 1000 });
# Actual Output

Cookie.set('token', 111, {expires: 12 *1000});

**Comment by prettydiff** [comment]
Would you mind producing the debug.md file and pasting it into a gist?  I am not sure which language or beautifier you used, so I cannot help debug this yet.

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

---

This Issue can be reopened with more information.
