### ISSUE TITLE
Add Puppet beautification via puppet-lint.

### ISSUE THREAD

**Issue by dougborg** [Glavin001/atom-beautify#131]
It should be fairly easy to add beautification of puppet (*.pp) files using puppet-lint (http://puppet-lint.com).

**Comment by richardraseley** [comment]
@dougborg or @Glavin001 - have any of you taken a crack at this yet?

**Comment by Glavin001** [comment]
I have not. 

I am hoping after my exams (next few weeks) that I will be able to find time to greatly improve Atom Beautify.

**Comment by dougborg** [comment]
I had looked at it a bit ages ago, but then got caught up in other things.

**Comment by richardraseley** [comment]
@Glavin001 @dougborg - Thanks for the updates!

**Comment by Glavin001** [comment]
The new internal API ( #282 ) for adding beautifiers and languages make it much quicker and easier to add support. If anyone is feeling up for submitting a pull request, they are always welcome. And feel free to ask any questions. I am still working on documentation, so if there are questions then I'll make sure to keep track of them for documenting later.

**Comment by Glavin001** [comment]
See https://github.com/Glavin001/atom-beautify/issues/300#issuecomment-107590998 for how to add a new language and/or beautifier.

**Comment by rmaika** [comment]
Thanks for creating those docs, @Glavin001. I would love to have a beautifier for developing Puppet code. I think I'll give writing a beautifier a shot when I have a bit of free time to knock it out.

**Comment by Glavin001** [comment]
Great! Let me know if you have any questions :smiley:.
