### ISSUE TITLE
JS - Wrap Line Length

### ISSUE THREAD

**Issue by PolGuixe** [Glavin001/atom-beautify#1312]
# Description
I think the wrap line length option is not working as I would expect.

.jsbeautifyrc 
```json
{
	"js": {
		"indent_size": 2,
		"indent_with_tabs": false,
		"jslint_happy": true,
		"end_with_newline": true,
		"brace_style": "expand",
                "function_name": true,
                "space_after_anon_function": true,
                "bracepadding": true,
                "wrap_line_length": 80,
	}
}
```

# Input Before Beautification

This is what the code looked like before:

```js
throw new Error('invite-requested', 'They have already requested an invite, search it in the list');
```

# Expected Output

The beautified code should have looked like this:

```js
throw new Error(
   'invite-requested', 
   'They have already requested an invite, search it in the list'
);
```
or at least something below 80 char.

# Actual Output

The beautified code actually looked like this:

```js
throw new Error('invite-requested', 'They have already requested an invite, search it in the list');
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/78d3ce649f315d9138080ac1d309a7a2

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by hielfx** [comment]
I can confirm this on Windows 10 with Atom v1.12.6 and package version v0.29.13

**Comment by prettydiff** [comment]
Yeah, Pretty Diff is currently doing a poor job of wrapping long lines composed of comma separated lists.

**Comment by Glavin001** [comment]
@PolGuixe and @hielfx , have you tried switching to using `JS Beautify` beautifier instead? It appears Pretty Diff's Issue https://github.com/prettydiff/prettydiff/issues/397 has not been completed.

I am closing this as a third-party (Pretty Diff) bug. Hopefully JS Beautify does work at least.

**Comment by PolGuixe** [comment]
@Glavin001 I've tried JSBeautify, it lacks support for other features that Pretty Diff have.

**Comment by prettydiff** [comment]
I will return focus to this.  Sorry, I have been distracted recently by a seemingly simple problem that I cannot solve in another project.

**Comment by Glavin001** [comment]
https://github.com/prettydiff/prettydiff/issues/397 looks to be completed. @prettydiff is there a new option we need to add to support this with Atom-Beautify?

**Comment by menocomp** [comment]
@Glavin001  I have the same issue but it is fixed by use PrettyDiff instead of JS Beautify.
