### ISSUE TITLE
php-cs-fixer not found after successfully installing it

### ISSUE THREAD

**Issue by mmrs151** [Glavin001/atom-beautify#1313]
# Description
I have installed php-cs-fixer and it is working fine by itself, but atom-beautify keep on saying it can't find it. I have use the absolute path in the settings too.

# Debug

https://gist.github.com/anonymous/31649b3564793d840f24d01e7ac3b370

**Comment by janssenb** [comment]
Same here !

**Comment by Wockito** [comment]
Same here

**Comment by sxdubin** [comment]
Same here. Running Mac.
