### ISSUE TITLE
Haskell on Windows

### ISSUE THREAD

**Issue by blackjack4494** [Glavin001/atom-beautify#1314]
I am experiencing issues using beautify with haskell. I cannot use it. It tells me that haskell-stylish (or other way around) is not installed. So I tried it and it gave me an error. I need Cygwin/MinGw to install a dependency called old-times which needs that. Is someone else having the exact same problem. Or is there maybe another way without installing Cygwin? :/

**Comment by Glavin001** [comment]
I am not a Windows or Haskell user, so I will not be much help. You should ask your questions regarding stylish-haskell installation over at https://github.com/jaspervdj/stylish-haskell#installation 
Maybe @bobjflong  has some suggestions, too.
