### ISSUE TITLE
install atom-beautiful throw Error

### ISSUE THREAD

**Issue by budapeisidajiudian** [Glavin001/atom-beautify#1318]
the Error message ：
Unable to download https://www.atom.io/api/packages/atom-beautify/versions/0.29.13/tarball: getaddrinfo ENOTFOUND www.atom.io www.atom.io:443
why？

**Comment by prettydiff** [comment]
Could you describe the steps you took so that we can reproduce the problem?

**Comment by SagarRanglani-xo** [comment]
Facing the same problem, it comes whenever you try to update a package.

**Comment by Glavin001** [comment]
I recommend talking to the Atom team over at https://github.com/atom/atom or https://github.com/atom/apm or https://discuss.atom.io/
