### ISSUE TITLE
language-babel conflict with atom-beautify on save

### ISSUE THREAD

**Issue by PapyElGringo** [Glavin001/atom-beautify#1321]
# Description

When language-babel is installed the beautify on save don't work anymore. I don't have idea why.

# Steps to Reproduce

1. install atom
2. install atom-beautify
3. active beautify on save for javascript files
4. check that is working properly
5. install language-babel
6. try to save your file
7. see that beautify is not happening

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

---

We can reopen this Issue once the `debug.md` is provided. Until then there is nothing we can do.

**Comment by vyarmak** [comment]
In `atom-beautify` config you must configure default beautifier for `JSX` to `JS Beautify`. Your JS files would be formatted correctly.
