### ISSUE TITLE
JavaScript exponential numbers like 1.e-7 become 1. e - 7

### ISSUE THREAD

**Issue by thierryc** [Glavin001/atom-beautify#1322]
# Description

JavaScript wrong Beautification for exponential numbers like 1.e-7

# Input Before Beautification

This is what the code looked like before:

```
if ( toto > 1.e-7 ) { 

}
```

# Expected Output

The beautified code should have looked like this:

```
if ( toto > 1.e-7 ) { 

}
```

# Actual Output

The beautified code actually looked like this:

```
if ( toto > 1. e - 7 ) {

}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Create JavaScript file
3. Copy Past the code.
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
Which beautifier are you using?  Would you mind producing the debug.md file and pasting it to a gist?

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by thierryc** [comment]
Here is a link to the `debug.md` Gist: https://gist.github.com/bb6dd0eb0ea9d9a50fb4fe9d631a73f4

**Comment by prettydiff** [comment]
Looks like a solution was quickly written.

**Comment by thierryc** [comment]
Great !
