### ISSUE TITLE
Atom Beautify could not determine a supported beautifier to handle this file

### ISSUE THREAD

**Issue by dbenton414** [Glavin001/atom-beautify#1332]
this is what i got when i tried to run on some code i had written 
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Null Grammar" and extension "". If you would like to request support for this file and its language# Description

**Comment by prettydiff** [comment]
What was the code language and file extension?

**Comment by jnewth** [comment]
I have the same problem. The error message reports grammer "ejs" and extension "ejs". I am using ejs (javascript templates).

**Comment by prettydiff** [comment]
I am marking this as a bug for EJS language.

**Comment by Glavin001** [comment]
Closing this as solved by https://github.com/Glavin001/atom-beautify/pull/1326

**Comment by Glavin001** [comment]
Published to v0.29.15
