### ISSUE TITLE
Exponential notation with a plus sign gets formatted to cause a syntax error.

### ISSUE THREAD

**Issue by jlubean** [Glavin001/atom-beautify#1342]
# Description

The exponential notation of a number with a plus sign between the "e" and the power of 10 (i.e. "2e+3") will get formatted to cause a javascript SyntaxError (i.e. "2e + 3").  You can write the code without a plus sign (i.e. "2e3"), but it is valid JavaScript to have the plus sign.  The Number.prototype.toExponential() method returns a formatted string that has the plus sign in it.

# Input Before Beautification

This is what the code looked like before:

```
var x = 2e+3 + 2; 
var z = 2e3 + 2;
var y = 2e-3 + 2;
```

# Expected Output

The beautified code should have looked like this:

```
var x = 2e+3 + 2;
var z = 2e3 + 2;
var y = 2e-3 + 2;
```

# Actual Output

The beautified code actually looked like this (notice the first line has a syntax error):

```
var x = 2e + 3 + 2;
var z = 2e3 + 2;
var y = 2e-3 + 2;
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code has a syntax error

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I can reproduce the defect in Pretty Diff but not in JS Beautify.  I will open an issue for this.

**Comment by Glavin001** [comment]
Closing as a Pretty Diff bug, fixed with https://github.com/prettydiff/prettydiff/issues/385
