### ISSUE TITLE
Add Fortran beautifier indent_size option

### ISSUE THREAD

**Issue by MrYann** [Glavin001/atom-beautify#1348]
Indentation is strange (sometimes 2 spaces, sometimes 3).

Could there be an option in the beautify settings to set indentation size, and that it would be reliable ?
Additionally, it would be nice that this option would take its default value in the Editor settings.
And even nicer would be to allow for tabs as indentation.

**Comment by MrYann** [comment]
As an example, here is a poorly indented source file : 
```
module example_module
contains


subroutine example_routine(ecart,ptmes,nbpmes,nbtmes)
ecart=0.
do l=1,nbtmes
 do i=1,nbpmes
	 nbpmes = nbtmes + i + j
 end do
end do
ecart=sqrt(ecart)
return
end subroutine example_routine

end module example_module
```

And the result I obtain is this:

```
MODULE example_module
CONTAINS


  SUBROUTINE example_routine(ecart,ptmes,nbpmes,nbtmes)
    ecart=0.
    DO l=1,nbtmes
       DO i=1,nbpmes
          nbpmes = nbtmes + i + j
       END DO
    END DO
    ecart=SQRT(ecart)
    RETURN
  END SUBROUTINE example_routine

END MODULE example_module
```

Still poorly indented:  2 spaces most of the time, 3 spaces inside the DO loops, and never tabs -- which is the global setting I chose in the global editor preferences.

**Comment by MrYann** [comment]
I guess I'm not allowed to set labels, but I'd rather set "bug" and "feature request", rather than question.

**Comment by prettydiff** [comment]
Done.  Since Atom Beautify relies upon a third-party beautifier for Fortran here is the course of action to see this through:

1. Ensure the beautifier supports this feature.  If so skip to point 3.
2. Go to the beautifier's repo and submit an issue asking for the feature.
3. Once supported submit a pull request enhancing Atom Beautify with new options for this beautifier's feature.  I can provide some additional guidance when you get here.

**Comment by Glavin001** [comment]
It appears Fortran beautifier for Atom-Beautify does not yet support `indent_size` option, or any other options for that matter: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/fortran-beautifier/index.coffee#L28-L35

See Pull Request: https://github.com/Glavin001/atom-beautify/pull/383
Maybe @janbernloehr would be able to assist you, @MrYann, in adding `indent_size` support and submitting a Pull Request.

**Comment by MrYann** [comment]
Ok, thanks.
Anyway, I also do not like that all keywords are in CAPS, and moreover, the built-in Edit / lines / auto-indent menu already does exactly what I want : consistent indentation, and using the parameters defined in the general settings.
Si I will just use the built-in menu command, instead of beautifier.

**Comment by paspro** [comment]
What is the situation with this issue?

**Comment by bcaddy** [comment]
I'm having this same issue.  Fortran beautification doesn't use the same indentation everywhere.  Help.
