### ISSUE TITLE
The results of SQL beautification for CREATE TABLE are not what I expect

### ISSUE THREAD

**Issue by lundybernard** [Glavin001/atom-beautify#1354]
# Description

The results of beautification are not what I expect.
The comma delimited parameters inside the parenthesis are wildly over-indented.
note: this is output from a liquibase migration

# Expected Results

The beautified code should have looked like:

```
CREATE TABLE REPORTING.BUSINESS_HOURS_CONFIG (
    ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(127) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    SHIFT_BY TIME NOT NULL,
    SHIFT_START_TIME TIME NOT NULL,
    SHIFT_END_TIME TIME NOT NULL,
    CONSTRAINT PK_BUSINESS_HOURS_CONFIG PRIMARY KEY (ID)
    );
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/8d747242c51eaa28d571f1219ad53b24

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by vmuriart** [comment]
This is probably an issue with `sqlparse` rather than `atom-beautify`. Do you get your expected results if you run it directly on `sqlparse` ?

**Comment by Glavin001** [comment]
I think this is an issue with `sqlparse` instead. Looking at the `debug.md` Atom-Beautify ran as expected. I recommend creating an issue over at https://github.com/andialbrecht/sqlparse
