### ISSUE TITLE
beautify .vue file

### ISSUE THREAD

**Issue by zhifuliu** [Glavin001/atom-beautify#1357]
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Vue Component" and extension "vue". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by prettydiff** [comment]
Strange.  The config is defined at https://github.com/Glavin001/atom-beautify/blob/master/src/languages/vue.coffee

**Comment by zhifuliu** [comment]
Sorry,Just now,I update this plugin, you are right
