### ISSUE TITLE
Question: working with eslint in Javascript

### ISSUE THREAD

**Issue by kuzyn** [Glavin001/atom-beautify#1360]
Is there a way to play nice with eslint configurations when beautifying JS?

My use case is that I `atom-beautify` to fix indentations, trailing spaces and such, but it also take other liberties (remove trailing commas, remove explicit newline). Some (most?) of this stuff is already defined in my eslint file, which obviously causes conflicts.

Am I doing it wrong?

**Comment by prettydiff** [comment]
Atom Beautify makes use of a .jsbeautifyrc file instead of the .eslintrc file.

**Comment by Glavin001** [comment]
There is a feature request already: #897. Definitely something I want to investigate and support in the future! Closing as a duplicate.

**Comment by miguel-orange** [comment]
Hello all,
Beautifying based working based on my config in .eslintrc file.
install linter, linter-eslint.
`⌘+⇧+P`, then type `fix` and press enter on `Linter Eslint: Fix File`
As a test I changed my indent rule, say the lint errors, ran the command above, and it worked!

**Comment by miguel-orange** [comment]
https://github.com/Glavin001/atom-beautify/issues/897#issuecomment-274241350

**Comment by miguel-orange** [comment]
https://github.com/Glavin001/atom-beautify/issues/897#issuecomment-274241350
