### ISSUE TITLE
TypeScript - Space in parens/Break chained methods do not work

### ISSUE THREAD

**Issue by struct78** [Glavin001/atom-beautify#1362]
# Description

Checking "Space in parens" and "Break chained methods" options under TypeScript appear to have no affect on TypeScript files.

# Input Before Beautification

This is what the code looked like before:

```
	ngOnInit() {
		this.productService.getProducts().subscribe(products => this.products = products);
	}
```

# Expected Output

The beautified code should have looked like this:

```
	ngOnInit() {
		this.productService.getProducts()
			.subscribe( products => this.products = products );
	}
```

# Actual Output

The beautified code actually looked like this:

```
	ngOnInit() {
		this.productService.getProducts().subscribe(products => this.products = products);
	}
```

If I import this code into a new .js file, and set the same options for the .js formatter, it works as expected.

**Comment by prettydiff** [comment]
Thank you for the specific details about the issue.  Would you also mind generating a debug.md file from Atom Beautify so that we can know a couple more technical details?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by struct78** [comment]
https://gist.github.com/anonymous/4d5e96af5001ad3a6c1f6015bc3e61ab

**Comment by prettydiff** [comment]
Looks like this issue will not be addressed by typescript-formatter.
