### ISSUE TITLE
Problem when I was trying use beautify

### ISSUE THREAD

**Issue by jesusmr25** [Glavin001/atom-beautify#1379]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/fa9f777cafa2d98fa70b32745de3c21b

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Could describe the problem in more detail?

**Comment by jesusmr25** [comment]
I forgot change the title, sorry

**Comment by prettydiff** [comment]
What kind of problem did you encounter?  Was something out of place, poorly indented, or missing?

**Comment by jesusmr25** [comment]
The problem was that beautify didn't do anything.
But now, beautify it's working. I solved this problem to use the option debug in beautify's pakage.

**Comment by prettydiff** [comment]
Awesome, glad to hear it is working now.
