### ISSUE TITLE
Beautifying PHP

### ISSUE THREAD

**Issue by dpureco** [Glavin001/atom-beautify#1381]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
It's on debug.md, not sure what it should look like.
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/857c8a2facbaf0cc4a783182eff24c80

# Checklist

- [X ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ X] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by robinparisi** [comment]
Same here, PHP beautification doesn't work anymore (nothing happens) but it works well when I use php-cs-fixer directly from the command line.

**Comment by odahcam** [comment]
Here, when I use php-cs-fixer from Windows CLI, it works fine, but this package seems to not work with it. atom-beautify only works when I give it the path of php-cs-fixer.phar file.

**Comment by robinparisi** [comment]
Finally got it!

It seems that my PHP version was involved. I'm on OSX and installed PHP in the past by using this script https://php-osx.liip.ch/. I also have a php version available with brew but I think the wrong version was used. 

So, I completely removed php5 folders in /usr/local/ then try the command ```which php```, which should return  ```/usr/local/bin/php```.

We must ensure that the good version is used (it should be a symlink to brew php binaries) :

```php
-> ls -l /usr/local/bin/php
lrwxr-xr-x  1 robin  admin  32 30 nov 22:40 /usr/local/bin/php -> ../Cellar/php70/7.0.13_6/bin/php
```

After that, everything was back to normal with atom-beautify :simple_smile:

**Comment by prettydiff** [comment]
The frequent level of frustration and numerous issues related to PHP here really make me want to extend Pretty Diff to support PHP formally.  If only there were more time in the day.

**Comment by petrchutny** [comment]
I have similar issue, nothing happens to my code at all.

Debug gist from Beautify is [here](https://gist.github.com/petrchutny/aa71acc936966d33b81a1c3967891e6a).

**Comment by madrussa** [comment]
I found my PHP wasn't beautifying and checking the debug I found using PHP-CS-Fixer with xdebug enabled would cause it to write to stderr and prevent any beautification of the code.

If you are having issues with PHP Beautify then I would suggest checking if you have xdebug installed and disabling it. Unless the Beautify devs can capture the response and still allow it to work. :)

**Comment by petrchutny** [comment]
Thanks for the suggestion @madrussa, but I have no idea how to disable xdebug. I've tried to update php-cs-fixer by its selfupdate command but that failed due to some permission problem. It still doesn't work…
