### ISSUE TITLE
"HTML (EEx)" Support

### ISSUE THREAD

**Issue by arteepa** [Glavin001/atom-beautify#1383]
It's HTML with embedded elixir.

**Comment by prettydiff** [comment]
Before this can move foward we will need an elixir beautifier.  Please see https://github.com/Glavin001/atom-beautify/issues/545

**Comment by arteepa** [comment]
Yes, it's the same.

It makes sense to first need the Elixir beautifier. This thread is no longer needed. Thanks for the response.
