### ISSUE TITLE
Beautifying CSS rules will have a newline added to the beginning of each rule, and I can't turn it off.

### ISSUE THREAD

**Issue by tommai78101** [Glavin001/atom-beautify#1387]
# Description

The results of beautification are not what I expect.

There is a newline added before the beginning of the style rules. It should be added at the end of the style rules.

newline_between_rules flag has already been set to false, yet it still inserts newlines before the beginning of each style rules.

Duplicate issue: 

https://github.com/Glavin001/atom-beautify/issues/709

It's opened, but it was a question, and not a bug report.

# Input Before Beautification

This is what the code looked like before:

```
    
    <style>
      /*This is a body.*/
      body {
        -webkit-text-size-adjust: 100%;
      }

      /*This is a table.*/
      table[align="center"] {
        margin: 0 auto;
      }

      /*Test*/
      .THIS_IS_A_CLASS {
        blah: yes;
      }
    </style>
    
```

# Expected Output

The beautified code should have looked like this:

```
    
    <style>
      /*This is a body.*/
      body {
        -webkit-text-size-adjust: 100%;
      }

      /*This is a table.*/
      table[align="center"] {
        margin: 0 auto;
      }

      /*Test*/
      .THIS_IS_A_CLASS {
        blah: yes;
      }
    </style>
    
```

# Actual Output

The beautified code actually looked like this:

```

    <style>
      /*This is a body.*/
      
      body {
        -webkit-text-size-adjust: 100%;
      }
      /*This is a table.*/
      
      table[align="center"] {
        margin: 0 auto;
      }
      /*Test*/
      
      .THIS_IS_A_CLASS {
        blah: yes;
      }
    </style>
    
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: 

~~[debug.md](https://gist.github.com/anonymous/0ea0f9db48d5c036ca6aae76fd83eb14)~~ [debug.md](https://gist.github.com/anonymous/3871b468c90999689c269220e6652b1e)

# Checklist

I have:
- [v] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [v] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [v] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know there is a duplicate issue, but no results were determined. 
- [v] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [v] Generated debugging information and added link for `debug.md` Gist to this issue.

**Comment by tommai78101** [comment]
Full code:

```
<html>

  <body>
    <style>
      /*This is a body.*/
      body {
        -webkit-text-size-adjust: 100%;
      }

      /*This is a table.*/
      table[align="center"] {
        margin: 0 auto;
      }

      /*Test*/
      .THIS_IS_A_CLASS {
        blah: yes;
      }
    </style>
  </body>

</html>

```

**Comment by Glavin001** [comment]
> > debug.md: https://gist.github.com/anonymous/0ea0f9db48d5c036ca6aae76fd83eb14
> Original File Language: CoffeeScript

It appears your `debug.md` is actually for a CoffeeScript file and this issue is about CSS. Please replace your `debug.md` with the correct one demonstrating your issue.

**Comment by tommai78101** [comment]
Sorry, this is the actual debug.md

[debug.md](https://gist.github.com/anonymous/af9049f7ff7e9319e943c9ac624789a0)

**Comment by tommai78101** [comment]
Hello, after numerous testing, disabling "Preserve New Lines" option doesn't seem to be helping.

**Comment by prettydiff** [comment]
I attempted to beautify the code sample in the debug.md file on http://jsbeautifier.org/ with *Remove all extra newlines* toggled but no luck.

Including @bitwiseman

**Comment by bitwiseman** [comment]
@prettydiff - That setting on the website is not sufficient to test this.  The website does not expose the setting they are talking about.  Please try from the command-line with the desired settings.

**Comment by prettydiff** [comment]
Thanks Liam!

**Comment by prettydiff** [comment]
@tommai78101 Guidance to further test or resolve this problem was provided by bitwiseman with no further updates.  I am closing this issue as resolved.  If I am in error please reopen the issue.
