### ISSUE TITLE
Could not find 'X'. The program may not be installed. on Windows 10

### ISSUE THREAD

**Issue by seanmars** [Glavin001/atom-beautify#1392]
# Description

When open atom with right click menu, it's always get "Could not find 'X'. The program may not be installed. ", But when open atom with shortcut it's work find.

# Debug

Here is a link to the debug.md Gist: 
https://gist.github.com/anonymous/27d26ff481383bae07f7971a1bcc2f97

**Comment by prettydiff** [comment]
This appears to be a duplicate of #1052

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
