### ISSUE TITLE
not working for fortran code

### ISSUE THREAD

**Issue by Foadsf** [Glavin001/atom-beautify#1393]
# Description

The results of beautification are not what I expect. It used to work, but now it doesn't. I tried the command `Atom Beautify: Beautify Editor` but I it gives the error below:

<img width="461" alt="screen shot 2016-12-04 at 01 18 52" src="https://cloud.githubusercontent.com/assets/12762442/20863081/e350502e-b9bf-11e6-97d1-c649d0e877d1.png">

text:

Atom beautify could not determine a supported beautifier for this file
Atom beautify could not determine a supported beautifier could not handle this file with grammar "Fortran - Free Form " and extension "f95". if you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by Glavin001** [comment]
Closed by https://github.com/Glavin001/atom-beautify/pull/1380

**Comment by Glavin001** [comment]
Published to v0.29.15
