### ISSUE TITLE
OSX Bad Argument for PHP Editor

### ISSUE THREAD

**Issue by slaughter550** [Glavin001/atom-beautify#1395]
# Description
Since last update, all php files fail to beautify with "Bad Argument" being thrown.
# Expected Results

The beautified code should have looked like:

Code is already beautified and still fails. Code also fails if it needs beautification. 
# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Error is thrown and nothing changes.

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/3510d32e424b03c4df53c7b09da0194c

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by slaughter550** [comment]
@Glavin001 do you need anything else?

**Comment by slaughter550** [comment]
@Glavin001 just an FYI, when I removed shell integration for iTerm everything started working again.

https://www.alexkras.com/remove-shell-integration-from-iterm2/

**Comment by pnutster** [comment]
Thanks! Been having this problem for months and just couldn't figure it out. Removing shell integration did the trick, never would have thought of that!

**Comment by jbnv** [comment]
What does iTerm2 integration have to do with this? I'm getting this error on one of my PH projects--but not others, and I use iTerm2 but don't have integration installed.
