### ISSUE TITLE
Extra "}" when beautifying a commented JSX code

### ISSUE THREAD

**Issue by reznord** [Glavin001/atom-beautify#1396]
# Description
An extra "}" includes every time I try to beautify the code which has jsx commented.

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:
```
<div>
  <Field component={ScrollHeader} name="name"  isPopup={true} team={true} placeholder="Enter Destination Name" />
  <div className="content-width">
    <Field component={TextArea} name="description" label="Description" heading={true} className="row-main-2" orientation="vertical" placeholder="Enter the description for the IVR"/>
    <Launcher label="Add Destination" description="This includes default destinations that can be used by anyone to alter the system behaviour of your outbound routing" className="row-main">
      { destinationAdd }
    </Launcher>
    <Launcher label="Custom Dial Codes" className="row-main">
      { customDialCodes }
    </Launcher>
    <FormFooter>
      <Button label="Done"
         // onButtonClick={ handleSubmit(values => addDestination(values, startFormSubmit.bind(null, this.formName), stopFormSubmit.bind(null, this.formName))) }
       />
    </FormFooter>
  </div>
</div>
```

# Expected Output

The beautified code should have looked like this:

```
<div>
  <Field component={ScrollHeader} name="name"  isPopup={true} team={true} placeholder="Enter Destination Name" />
  <div className="content-width">
    <Field component={TextArea} name="description" label="Description" heading={true} className="row-main-2" orientation="vertical" placeholder="Enter the description for the IVR"/>
    <Launcher label="Add Destination" description="This includes default destinations that can be used by anyone to alter the system behaviour of your outbound routing" className="row-main">
      { destinationAdd }
    </Launcher>
    <Launcher label="Custom Dial Codes" className="row-main">
      { customDialCodes }
    </Launcher>
    <FormFooter>
      <Button label="Done"
       // onButtonClick={ handleSubmit(values => addDestination(values, startFormSubmit.bind(null, this.formName), stopFormSubmit.bind(null, this.formName))) }
       />
    </FormFooter>
  </div>
</div>
```

# Actual Output

The beautified code actually looked like this:

```
<div>
  <Field component={ScrollHeader} name="name"  isPopup={true} team={true} placeholder="Enter Destination Name" />
  <div className="content-width">
    <Field component={TextArea} name="description" label="Description" heading={true} className="row-main-2" orientation="vertical" placeholder="Enter the description for the IVR"/>
    <Launcher label="Add Destination" description="This includes default destinations that can be used by anyone to alter the system behaviour of your outbound routing" className="row-main">
      { destinationAdd }
    </Launcher>
    <Launcher label="Custom Dial Codes" className="row-main">
      { customDialCodes }
    </Launcher>
    <FormFooter>
      <Button label="Done" // onButtonClick={handleSubmit(values => submitAddIvr(values, startFormSubmit.bind(null, this.formName), stopFormSubmit.bind(null, this.formName)))
          }}/>
    </FormFooter>
  </div>
</div>
```

# Steps to Reproduce

1. Add code to Atom editor and comment out a function inside a div and then beautify the code.
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right and it gives an error because it adds an extra bracket to the end of the commented code!

Attaching the screenshots of the problem.

Before beautifying:
<img width="913" alt="code before beautifying" src="https://cloud.githubusercontent.com/assets/3415488/20878816/ec7f0266-baf6-11e6-87c9-260125bf43ba.png">

After beautifying: 
<img width="929" alt="code after beautifying" src="https://cloud.githubusercontent.com/assets/3415488/20878874/2b5bf034-baf7-11e6-9bb4-2cee97e9cbf9.png">

**Comment by prettydiff** [comment]
I am not sure what beautifier you are using, but I will assume it is a Pretty Diff defect.

**Comment by reznord** [comment]
@prettydiff I am using atom-beautify itself. That doesn't mean it is a 3rd party application bug. All I am doing is right-click in the editor when the file is open and then click on the "Beautify editor contents". This is a functionality of the atom-beautify.

**Comment by prettydiff** [comment]
@reznord Atom Beautify is using a beautifier of some sort to beautify the code.  You can tell which beautifier it is using for JSX by looking at the Atom Beautify settings in Atom.

**Comment by reznord** [comment]
@prettydiff it is Pretty Diff package, sorry for earlier. I guess this is an issue already there in Pretty Diff as well.

**Comment by Glavin001** [comment]
> I am not sure what beautifier you are using, but I will assume it is a Pretty Diff defect.

and

> I am using atom-beautify itself. That doesn't mean it is a 3rd party application bug.

This is the kind of confusion I do not want to see. I must *insist* the `debug.md` be included within new Issues before we ( @prettydiff, myself, et al.) invest any time in analyzing and debugging the issue. @prettydiff please use `waiting-for-user-information` label in all applicable cases where `debug.md` is missing, such as this one. Instead of asking "what beautifier are you using?" we should *always* say "Please include the `debug.md` Gist and follow the Issue template structure". We must enforce this so we can focus our very limited time on providing quality support, instead of playing a guessing game which should be a non-issue given we already have spent time developing the `Help Debug Editor` feature!

![image](https://cloud.githubusercontent.com/assets/1885333/21598987/01af9f96-d13c-11e6-8cf9-5cdcb79e7853.png)

My saved reply, which applies to Issues like this, is:

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by prettydiff** [comment]
Something I noticed is that the sample block of code begins and ends as markup.  It is my understanding that JSX is a JavaScript format containing XML bodies, that is that it would start and end as JavaScript.  **Is this an incorrect understanding?**

In the latest version of Pretty Diff beautification appears correct if I put this `var a = ` at the front of the code sample.
