### ISSUE TITLE
Doesn't recognize .ejs file extensions

### ISSUE THREAD

**Issue by jer244** [Glavin001/atom-beautify#1403]
There are no file extensions listed for EJS files.

![ejs beautify](https://cloud.githubusercontent.com/assets/17435276/20978886/9b068e6c-bc78-11e6-94e1-92fa0b2dd215.png)

Get the following error when trying to beautify .ejs files:

Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "EJS" and extension "ejs". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
Odd, I see a file dedicated to EJS: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/ejs.coffee

I will mark this as a bug.

**Comment by prettydiff** [comment]
@jer244 You can probably fix this by including `ejs` in the extensions array of that file I linked to.

**Comment by jnewth** [comment]
@prettydiff Your fix (that is, adding "ejs" to "extensions" in .atom\packages\atom-beautify\src\languages\ejs.coffee) works. The formatting doesn't look as good as what atom-beautify usually creates, so maybe there is a follow-on improvement to ejs formatting? (Im an EJS n00b but maybe someone has something).

**Comment by prettydiff** [comment]
@jnewth It seems that Pretty Diff is the default beautifier for that format.  Some solutions to improve beautification are:

* You can add JSBeautifier as a second beautifier for that code format.
* Open issues at https://github.com/prettydiff/prettydiff/issues with defects you discover and I will work out resolutions.

**Comment by Glavin001** [comment]
- @jnewth in the future please feel free to submit a Pull Request for simple changes like this.
- @prettydiff looks like this is a `third-party bug` for Pretty Diff.

**Comment by Glavin001** [comment]
Published to v0.29.15
