### ISSUE TITLE
Installed, but not working for HTML

### ISSUE THREAD

**Issue by bramvana** [Glavin001/atom-beautify#1404]
Hello,

Tried installing Beautify without success.

Opened command line prompt (ctrl + alt + p) and
* entered 'beautify' - No matches found
* entered apm install atom-beautify' - no reaction.

Fresh Atom install (1.12.6) running on Win10.

What am I doing wrong?

Regards

**Comment by prettydiff** [comment]
Try this and let me know what the results are:

    apm install atom-beautify

**Comment by bramvana** [comment]
`apm install atom-beautify`
yields no reaction at all.
Installed it through File > Settings > +Install >
entering Beautify in query box and pressing Packages. Search results showed up and clicked Install.

It doesn't work for some simple HTML tags/containers, so something must be off:

> Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Null Grammar" and extension "". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by prettydiff** [comment]
It sounds like Atom isn't properly installed.  Are you able to open the Atom editor?

**Comment by bramvana** [comment]
Problem persists.

Uninstalled Beautify.
Uninstalled Atom.
Re-downloaded the standard Atom installer, ran installer.
Opened Atom > Packages > installed Beautify

Copy-pasted some html content, clicked Packages > Atom Beautify > Beautify

Still the same result:
`Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Null Grammar" and extension "". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues`

https://dl.dropboxusercontent.com/u/27774206/Atom-Beautify-scrn.png or attached png.
![atom-beautify-scrn](https://cloud.githubusercontent.com/assets/24454138/21016566/50331b32-bd66-11e6-9d7e-e260428d5095.png)

**Comment by prettydiff** [comment]
Ah, could you prepare a debug.md file?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

It seems Atom Beautify is installed correctly, but cannot detect that HTML is the proper language grammar.  With the debug.md file I can see the file extension and see if there something else that is causing the error.

**Comment by bramvana** [comment]
Atom Beautify Help Debug Editor created another error:

![screenshot 2016-12-08 17 03 19](https://cloud.githubusercontent.com/assets/24454138/21017053/4c194eac-bd68-11e6-86fc-e7f40d9fe345.png)

**Comment by prettydiff** [comment]
Could you do me a big favor and copy that stack trace, from attempting to generate the debug.md, and put that into a comment here?

**Comment by bramvana** [comment]
Sorry for the delay. The way I see it, it's you doing the favors here ;-)

`Cannot read property 'name' of null
Cannot read property 'name' of null
Hide Stack Trace
TypeError: Cannot read property 'name' of null
    at atom-workspace.debug (file:///C:/Users/Bram/.atom/packages/atom-beautify/src/beautify.coffee:364:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-li.<anonymous> (C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
    at HTMLOListElement.dispatch (C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (C:\Users\Bram\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)`

**Comment by bramvana** [comment]
Was it helpful?
Is my machine or is this a reproducible error?

**Comment by prettydiff** [comment]
I haven't looked into it yet.

**Comment by Glavin001** [comment]
> Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Null Grammar" and extension "". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

I may have missed something, however it looks like Atom is not detecting the grammar as HTML and instead using "Plain Text". You can either select the grammar for your file with https://atom.io/packages/grammar-selector or you can save the file with the appropriate file extension and Atom should correct detect the grammar. This screenshot above is expected behaviour. Atom does not know what type of file this is, and therefore either does Atom-Beautify.
