### ISSUE TITLE
How to set .jsbeautifyrc to fit airbnb js style guide？

### ISSUE THREAD

**Issue by jasonwwl** [Glavin001/atom-beautify#1406]
# Description

my .jsbeautifyrc:
```
    "brace_style": "collapse-preserve-inline",
    "break_chained_methods": false,
    "e4x": true,
    "end_with_newline": true,
    "end_with_comma": false,
    "indent_char": " ",
    "indent_level": 0,
    "indent_size": 2,
    "indent_with_tabs": false,
    "jslint_happy": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 4,
    "preserve_ternary_lines": true,
    "space_after_anon_function": true,
    "space_after_named_function": true,
    "space_before_conditional": true,
    "space_in_empty_paren": false,
    "space_in_paren": false,
    "unescape_strings": false,
    "wrap_attributes": "auto",
    "wrap_attributes_indent_size": 2,
    "wrap_line_length": 0
```

# Input Before Beautification

This is what the code looked like before:

```
import React, { Component, PropTypes } from 'react';

export default class Abc extends Component {
  static propTypes = {
    test: PropTypes.string,
  };

  constructor(props) {
    super(props);
    this.state = {
      test: '',
    };
  }

  render() {
    return (
      <div>
        <h1>test{this.props.test} {this.state.test}</h1>
      </div>
    );
  }
}

```

# Expected Output

The beautified code should have looked like this:

```
import React, { Component, PropTypes } from 'react';

export default class Abc extends Component {
  static propTypes = {
    test: PropTypes.string,
  };

  constructor(props) {
    super(props);
    this.state = {
      test: '',
    };
  }

  render() {
    return (
      <div>
        <h1>test{this.props.test} {this.state.test}</h1>
      </div>
    );
  }
}

```

# Actual Output

The beautified code actually looked like this:

```
import React, {Component, PropTypes} from 'react';  // <-- { Component.... } need space

export default class Abc extends Component {
  static propTypes = {
    test: PropTypes.string // <-- need comma
  };

  constructor(props) {
    super(props);
    this.state = {
      test: '' // <-- need comma
    };
  }

  render() {
    return (
      <div>
        <h1>test{this.props.test} {this.state.test}</h1>
      </div>
    );
  }
}

```

**Comment by Glavin001** [comment]
Documentation for available JavaScript options can be found at https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#javascript

You could ask at https://github.com/beautify-web/js-beautify/issues or https://github.com/prettydiff/prettydiff/issues for assistance (depending on your selected beautifier). Since I do not see your `debug.md` Gist link -- which would have told me your selected beautifier -- I will say the standard message and leave it to you:

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

It may also be better for you to ask on Stackoverflow: http://stackoverflow.com/questions/ask
