### ISSUE TITLE
LUA - inline block comments are not beautiful

### ISSUE THREAD

**Issue by Nexela** [Glavin001/atom-beautify#1411]
# Description

The results of beautification are not what I expect.
My assumption is it stops looking at the rest of the line when it encounters a comment start.

# Expected Results

The beautified code should have looked like:

```
local function test()
  if true then
    print("true")
    if true --[[and true]] then
     print("both true")
    end
  end
end
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/e468c30d49370065c0f13c32242fc31b

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Lua beautifier was merged from https://github.com/Glavin001/atom-beautify/pull/973 and developed  by @JoostvDoorn. Maybe @JoostvDoorn would be able to provide some assistance?
