### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by Vextraaa** [Glavin001/atom-beautify#1418]
Hello, I have recently been trying to get atom-beautify to work on windows 8 but it keeps saying that I need to install "php-cs-fixer" I have no idea how to do this as I have just installed Atom, If anyone can provide me when a easy tutorial for windows it would be highly appreciated!

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
