### ISSUE TITLE
Autopep8 beautifier for Python does not support "eol" option

### ISSUE THREAD

**Issue by seanmars** [Glavin001/atom-beautify#1419]
# Atom Beautify - Debugging information

[Debugging information on Gist](https://gist.github.com/seanmars/71ad1f47800eb4da7a52aa1a79d1230c)

**Comment by Glavin001** [comment]
Please put the debugging information into a Gist and replace the body above with the link.

Also, it looks like `eol` option is not supported: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#python
Feel free to submit a Pull Request to add support for it by changing https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/autopep8.coffee and letting me know if you have any questions,
