### ISSUE TITLE
Ruby beautification improvements

### ISSUE THREAD

**Issue by erniebrodeur** [Glavin001/atom-beautify#142]
rbeautify supports a few options now

- [x] --tabs
- [x] --spaces
- [x] --indent_count i

If you add these to the settings/support in atom, that would be greatly appreciated.

**Comment by Glavin001** [comment]
Rubocop beautifier support has been recommended ( #226 ) and implemented in Atom Beautify ( #275 ). Atom Beautify will currently have support for both. What are your thoughts on Rubocop? Do you feel rbeautify has advantages/disadvantages over it?

**Comment by flujan** [comment]
How can I choose between them?

**Comment by Glavin001** [comment]
@flujan: Go to Atom Beautify's package settings and find `Language Config - <your language> - Default Beautifier` and select from the options.

**Comment by flujan** [comment]
@Glavin001 thanks for the tip. It is working now. :)

**Comment by Glavin001** [comment]
Published to v0.28.3
