### ISSUE TITLE
Beautify html not following the rules

### ISSUE THREAD

**Issue by tonylin0826** [Glavin001/atom-beautify#1422]
# Description

The results of beautification are not what I expect.
I set the indent size to 2, but it still indent 4.

If i disable the angulars package and restart, it work normally.

# Input Before Beautification

This is what the code looked like before:

```html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html>
```

# Actual Output

The beautified code actually looked like this:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>

        <h1>This is a Heading</h1>
        <p>This is a paragraph.</p>

    </body>
</html>

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/tonylin0826/84c5a9da63908a5a4a403eb4b8686aee

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Your file is being recognized as:

```
Original File Grammar: HTML (Angular)

Original File Language: EJS
```

and therefore is using the EJS settings:

```
"ejs": {
        "indent_size": 4,
```

Instead of your HTML settings:

```
"html": {
        "indent_size": 4,
```

You can either configure EJS language settings or change the Atom grammar for your file.
See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#ejs for available EJS options.
