### ISSUE TITLE
unable indent properly

### ISSUE THREAD

**Issue by ChandraKantPaliwal** [Glavin001/atom-beautify#1433]
https://gist.github.com/ChandraKantPaliwal/0732b005485be45696eb988c68e0344a

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

This issue can be reopened once we have the appropriate information to help you.

**Comment by ChandraKantPaliwal** [comment]
i have create new issue with full detail.
https://github.com/Glavin001/atom-beautify/issues/1436
