### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by Schepp98** [Glavin001/atom-beautify#1435]
atom-beautify will not install for me. I am receiving the following error message:

Installing “atom-beautify@0.29.16” failed.Hide output…
INFO: Could not find files for the given pattern(s).

The system cannot find the file specified.

npm ERR! addLocal Could not install C:\Users\Student\AppData\Local\Temp\d-11702-18496-icxu2x\package.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Student\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Student\\AppData\\Local\\atom\\app-1.12.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Student\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Student\\.atom\\.apmrc" "install" "C:\\Users\\Student\\AppData\\Local\\Temp\\d-11702-18496-icxu2x\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\Student\.atom\.apm\atom-beautify\0.29.16\package.tgz.1192071348
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Student\.atom\.apm\atom-beautify\0.29.16\package.tgz.1192071348' -> 'C:\Users\Student\.atom\.apm\atom-beautify\0.29.16\package.tgz'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Student\.atom\.apm\atom-beautify\0.29.16\package.tgz.1192071348' -> 'C:\Users\Student\.atom\.apm\atom-beautify\0.29.16\package.tgz']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\Student\\.atom\\.apm\\atom-beautify\\0.29.16\\package.tgz.1192071348',
npm ERR!   dest: 'C:\\Users\\Student\\.atom\\.apm\\atom-beautify\\0.29.16\\package.tgz' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Student\AppData\Local\Temp\apm-install-dir-11702-18496-ms1vjk\npm-debug.log

**Comment by jolsenmultiad** [comment]
I'm only a fellow user and I'm just guessing here, but it seems like you're a student and perhaps trying to install it on a school computer where you do not have the proper permissions.  This guess is based on the following two lines in your output:

> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Student.atom.apm\atom-beautify\0.29.16\package.tgz.1192071348' -> 'C:\Users\Student.atom.apm\atom-beautify\0.29.16\package.tgz'
> npm ERR! Please try running this command again as root/Administrator.

If you have administrative access, try running atom as an administrator and let it do the updates. If you don't have administrative access, you might try downloading the ZIP of Atom and extracting it to the desktop or removable media and running Atom in  "portable" mode (see https://github.com/atom/atom/pull/8442).

Good luck.

**Comment by prettydiff** [comment]
@Schepp98 could you respond in a comment validating or invalidating the assumption provided by @jolsenmultiad ?

If this assumption is not valid then try `apm install atom-beautify` to gather any missing components.

**Comment by lloydstubber** [comment]
I've got the same problem. I've re-installed node.js and npm, tried running as admin, tried apm install and still no luck. Any ideas?

Error below:

`> atom-beautify@0.29.16 postinstall C:\Users\LLCOOL~1\AppData\Local\Temp\apm-install-dir-117014-9912-1dm3k1g\node_modules\atom-beautify
> npm run build-options

C:\Users\LLCOOL~1\AppData\Local\Temp\apm-install-dir-117014-9912-1dm3k1g
`-- (empty)


npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
'C:\Users\LL' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\LLCOOL~1\AppData\Local\Temp\apm-install-dir-117014-9912-1dm3k1g\package.json'
npm WARN apm-install-dir-117014-9912-1dm3k1g No description
npm WARN apm-install-dir-117014-9912-1dm3k1g No repository field.
npm WARN apm-install-dir-117014-9912-1dm3k1g No README data
npm WARN apm-install-dir-117014-9912-1dm3k1g No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\LL COOL J\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\LL COOL J\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\LL COOL J\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\LL COOL J\\.atom\\.apmrc" "install" "C:\\Users\\LLCOOL~1\\AppData\\Local\\Temp\\d-117014-9912-17d7e5m\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\LLCOOL~1\AppData\Local\Temp\apm-install-dir-117014-9912-1dm3k1g\npm-debug.log
npm ERR! code 1`

**Comment by Glavin001** [comment]
> 'C:\Users\LL' is not recognized as an internal or external command,
operable program or batch file.

@lloydstubber, this is a duplicate issue: https://github.com/Glavin001/atom-beautify/issues/1434
Which is actually an `apm` bug: https://github.com/atom/apm/issues/666
Which has been fixed with https://github.com/atom/apm/commit/e8b28ce31dc55890ca978ebe889a3de945d7cd99

**Comment by Glavin001** [comment]
@Schepp98, I agree with @jolsenmultiad comment. I would also add you should contact the `apm` team at https://github.com/atom/apm for additional help as these types of installation issues are outside of the control of Atom-Beautify.

**Comment by ememumoh** [comment]
the real problem is here: 
'C:\Users\LL' is not recognized as an internal or external command, operable program or batch file. see this:
npm ERR! argv "C:\\Users\\LL COOL J\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\LL COOL J\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\LL COOL J\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\LL COOL J\\.atom\\.apmrc" "install" "C:\\Users\\LLCOOL~1\\AppData\\Local\\Temp\\d-117014-9912-17d7e5m\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"

Do not seem to recognize LL COOL J as a string!! I had this problem when I was trying to clone a repository from github, it could not because my username is Admin Pc. The space is the problem. How can this be solve? the system always defaults to a directory under your username! So if you have space in your username, then the problem comes.

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
