### ISSUE TITLE
Incorrect brace style behavior for JSON and JavaScript

### ISSUE THREAD

**Issue by joshuaavalon** [Glavin001/atom-beautify#1439]
# Description

Latest update changes the brace style behavior for JSON and JavaScript. I was use the default config for both JSON and JavaScript. After the update, the formatted file looks different than the one before update.

# Input Before Beautification

This is what the code looked like before:

```
[
    {
        "id": 1,
        "Merge": true,
        "Crane": 650,
        "Crane": 963,
        "LD": 326,
        "Non": 781
    },
    {
        "id": 2,
        "Merge": true,
        "Crane": 444,
        "Crane": 240,
        "LD": 705,
        "Non": 691
    }
]
```

# Expected Output

The beautified code should have looked like this:

```
[{
    "id": 1,
    "Merge": true,
    "Crane": 650,
    "Crane": 963,
    "LD": 326,
    "Non": 781
}, {
    "id": 2,
    "Merge": true,
    "Crane": 444,
    "Crane": 240,
    "LD": 705,
    "Non": 691
}]
```

# Actual Output

The beautified code actually looked like this:

```
[{
        "id": 1,
        "Merge": true,
        "Crane": 650,
        "Crane": 963,
        "LD": 326,
        "Non": 781
    },
    {
        "id": 2,
        "Merge": true,
        "Crane": 444,
        "Crane": 240,
        "LD": 705,
        "Non": 691
    }
]
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/joshuaavalon/842487de88885f84c10c6d62361fa404

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
The final options passed to `JS Beautify` are

```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false,
    "space_before_conditional": true,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "space_in_paren": false,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse",
    "break_chained_methods": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0,
    "end_with_newline": false,
    "end_with_comma": false,
    "disabled": false,
    "default_beautifier": "JS Beautify",
    "beautify_on_save": false
}
```

It looks like a `JS Beautify` issue you could forward to https://github.com/beautify-web/js-beautify/issues
Also, you could try changing the beautifier to `Pretty Diff` and seeing if it helps at all.
