### ISSUE TITLE
Can't install 0.29.16 on portable Atom

### ISSUE THREAD

**Issue by mosesontheweb** [Glavin001/atom-beautify#1442]
I tried to update my existing 0.29.14 package to the most actual version 0.29.16, suggested by Atom, which did not succeed. I then did the mistake to uninstall the running version 0.29.14 and tried to install 0.29.16 - no success again. I also tried to copy the package 0.29.14 again into the .atom/packages directory, no luck so far. The module even did not show up in the packages list.

Information on trying to copy the package manually into packages and then run "apm install" from the command line within the directory, is, that I should tell the author that `npm run docs` failed.

 Installing and updating modules wasn't a problem yet, even though I'm behind a firewall and using the portable version of Atom on a Windows 7 client (configured proxy settings in .apmrc). This is actually the first time I have some troubles.

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by elartix** [comment]
I have the same issue

[https://gist.github.com/elartix/776715bcac6897bf6bfa61b5c2f75f73](https://gist.github.com/elartix/776715bcac6897bf6bfa61b5c2f75f73)

**Comment by Glavin001** [comment]
https://github.com/Glavin001/atom-beautify/pull/1598 should fix this 😃 !
