### ISSUE TITLE
cannot be installed on osx

### ISSUE THREAD

**Issue by jipp** [Glavin001/atom-beautify#1443]
# Description

the latest version cannot be installed under osx 

> atom-beautify@0.29.16 postinstall /private/var/folders/c2/s65fq1t930sdnv60jfqqg3kw0000gp/T/apm-install-dir-11704-8311-t3bkdg/node_modules/atom-beautify
> npm run build-options

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine remark@6.2.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine typescript-formatter@2.3.0: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine remark-parse@2.2.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine remark-stringify@2.3.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine unified@5.1.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine trough@1.0.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine markdown-table@1.0.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine glob-expand@0.2.1: wanted: {"node":">0.10"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine array-iterate@1.1.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
sh: npm: command not found
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/wolfgang.keller/.atom/.apm/.apmrc" "--userconfig" "/Users/wolfgang.keller/.atom/.apmrc" "install" "/private/var/folders/c2/s65fq1t930sdnv60jfqqg3kw0000gp/T/d-11704-8311-b3ahp/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-options'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/c2/s65fq1t930sdnv60jfqqg3kw0000gp/T/apm-install-dir-11704-8311-t3bkdg/npm-debug.log

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
