### ISSUE TITLE
"loading nunjucks" appears in Atom console

### ISSUE THREAD

**Issue by damieng** [Glavin001/atom-beautify#1449]
# Description

```loading nunjucts``` appears in the Atom console;

![image](https://cloud.githubusercontent.com/assets/118951/21696594/a30de61e-d343-11e6-8c77-3fb35c882167.png)

# Expected Output

No console output.

# Fix

Remove this line - no other languages in Atom beautify do this - 
https://github.com/Glavin001/atom-beautify/blob/70dbad5819ffc0bc95eb9de55cf6b44910498b0e/src/languages/nunjucks.coffee#L1

**Comment by prettydiff** [comment]
https://github.com/Glavin001/atom-beautify/pull/1450

**Comment by Glavin001** [comment]
Wow, I'm surprised this was not caught earlier. Thanks!

**Comment by Glavin001** [comment]
Published to v0.29.19
