### ISSUE TITLE
Add compressedcss option for CSS to Pretty Diff beautifier

### ISSUE THREAD

**Issue by naymaeu** [Glavin001/atom-beautify#1451]
Hi
I try to use Compressed CSS style beautification what is avalible in PrettyDiff 2.1.15. I add option to setting files:

`compressedcss: true`

but is not working. Do you have any idea how to use it ?? Thanks for any advice.

**Comment by prettydiff** [comment]
I recommend playing around with http://prettydiff.com/.  This way you can get a feel for the available options and determine which features you want or don't want.  Then come back to Atom Beautify and adjust the settings as necessary.  If there is an option in Pretty Diff that is not currently in Atom Beautify please let us know or submit a pull request adding the missing option.

Please let me know what other questions you have.

**Comment by naymaeu** [comment]
Hi.
Thanks for reply.
Like I wrote upper i looking for **compressedcss** option for CSS for prettydiff. I chceck this option on prettydiff and its look like this:

![zrzut ekranu 2017-01-07 13 42 24](https://cloud.githubusercontent.com/assets/24625283/21741718/3319eefa-d4df-11e6-86c6-6eb7b3f4af54.jpg)

Compressed CSS style beautification option. I try to use it in atom-beautify this option but is not in options so i try to use config file and there use option

`compressedcss: true`

but is not working. So how to pull request to add this options in feature ?

Thanks a lot for any help.

**Comment by prettydiff** [comment]
That option probably isn't in Atom Beautify.  You would need to submit a pull request adding it to Atom Beautify.  I recommend reading this guide to help get you started: 

https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md

You would need to modify these files:

* https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee
* https://github.com/Glavin001/atom-beautify/blob/master/src/languages/css.coffee

**Comment by prettydiff** [comment]
The latest version of Pretty Diff is in Atom Beautify.  The code is there in Atom Beautify, but this option is not exposed.  I would recommend writing a pull request adding this option to Atom Beautify.
