### ISSUE TITLE
unexpected JS formatting

### ISSUE THREAD

**Issue by ali-hellani** [Glavin001/atom-beautify#1454]
could atom-beautify achieve this Expected Output ? (using React JSX)

# Input Before Beautification

This is what the code looked like before:

```
this.props.navigator.push({name: 'eventDetail', title: rowData.name.text, description: rowData.description.text, url: rowData.url, img: rowData.logo.url});
```

# Expected Output

The beautified code should have looked like this:

```
this.props.navigator.push({
    name: 'eventDetail', 
    title: rowData.name.text, 
    description: rowData.description.text, 
    url: rowData.url, 
    img: rowData.logo.url
});
```

# Actual Output

The beautified code actually looked like this:

```
this.props.navigator.push({name: 'eventDetail', title: rowData.name.text, description: rowData.description.text, url: rowData.url, img: rowData.logo.url});
```

**Comment by prettydiff** [comment]
Are you using Pretty Diff or JS Beautify.  I am sure JS Beautify has an option to do this, but I cannot remember what it is.  Possibly, `brace-style`.  Pretty Diff has an option to do this as well: http://prettydiff.com/documentation.xhtml#neverflatten

Please let me know if this helps.

**Comment by mksuper1** [comment]
How to configure that settings  in pretty diff in atom editor?

**Comment by prettydiff** [comment]
It looks like somebody is actually working on this - https://github.com/Glavin001/atom-beautify/pull/1289

I bet they could use some help.  See if you can modify the changes in their pull request so that the unit tests pass or additional test units are added.

**Comment by deforder** [comment]
@mksuper1 

put  ```neverflatten: true```

under args in src/beautifiers/prettydiff.coffee (# Prettydiff Arguments)
```
      # Prettydiff Arguments
      args =
        source: text
        lang: lang
        mode: "beautify"
        neverflatten: true
```

Note: this block is the one used to setup the argument(Options) before passing to PrettyDiff via API.

**Comment by ali-hellani** [comment]
i have switched to **JS-beautify** to try the **brace-style** option you mentioned above because currently pretty-diff doesn't support this yet but when i hit reformatting it hangs with a popup window (**beautification on progress**) and nothing happens.

<img width="494" alt="screen shot 2017-01-13 at 9 18 33 pm" src="https://cloud.githubusercontent.com/assets/10726596/21942521/1beb4b9c-d9d6-11e6-8702-497ac019df7f.png">

**Comment by deforder** [comment]
@ali-hellani 
With current atom-beautify version(0.29.16), JS-beautify isn't supported JSX yet. it seems the supported version will come with the next release. [(reference)](https://github.com/Glavin001/atom-beautify/pull/1432)

You have to wait until then or try to modify an argument for Pretty Diff by yourself as I mentioned above.
