### ISSUE TITLE
Default settings should be Atom's 

### ISSUE THREAD

**Issue by TouPye** [Glavin001/atom-beautify#146]
I've seen #50 and I understood that Atom Beautify settings have to override Atom settings in order to work properly.

Nevertheless, I think that default settings should be Atom settings. 
For instance, I use an indent length of 4 on every language. By default, Atom Beautify uses 2. 
Here I have to manually edit every indent setting and put them on 4.
System should be abble to find that I already set it to 4 in Atom general settings.

If no Atom Beautify setting is set, can't you check Atom settings ?

**Comment by Glavin001** [comment]
I re-read your original comment:

> I think that default settings should be Atom settings. 
> For instance, I use an indent length of 4 on every language. By default, Atom Beautify uses 2. 
> Here I have to manually edit every indent setting and put them on 4.
> System should be abble to find that I already set it to 4 in Atom general settings.

Instead of providing a flag that could be toggled that would change the precedence of the options, I think what would be ideal is actually setting the Atom Beautify default settings to the current values of the Atom Editor (at first launch). Thoughts?

**Comment by Glavin001** [comment]
This will be resolved by #172. I am updating from using `configDefaults` to Atom's latest `Config API`. I am going to make it such that the defaults check `atom.config.get('editor.tabLength')` and other settings and use those as the default values, as you requested.

**Comment by TouPye** [comment]
Great job :+1:
