### ISSUE TITLE
SCSS styles automatically go to new line, even with Newline between rules disabled

### ISSUE THREAD

**Issue by nickmak** [Glavin001/atom-beautify#1463]
Within the SCSS, SASS and CSS, I have disabled Newline between rules option, to keep all my CSS style properties inline with their class.

However, upon beautifying, the program newlines every property and selector. 

The following are my settings for SCSS/SASS/CSS (where applicable) within the plugin's config:

Enabled: 
Indent Commends
Indent Size: 2
Wrap line length: 200

Disabled:
Align Assignments
Fore Indentation
Newline between rules
No lead Zero
Preserver newlines

Am I missing something?

**Comment by prettydiff** [comment]
Could you please look to the issue template and provide the required information including the debug.md file?  Please reopen this issue once the required information is present.
