### ISSUE TITLE
Newer PHP-CS-Fixer version does not support older command-line arguments

### ISSUE THREAD

**Issue by Skysplit** [Glavin001/atom-beautify#1465]
[debug.md](https://gist.github.com/Skysplit/26a2a0ed86922f11986dabd5ee7039b5)

There's an error with beautification, It seems that there's newer version of php-cs-fixer that does not support older parameters/rules

**Comment by Glavin001** [comment]
Feel free to submit a Pull Request updating the beautifier. Applicable file is https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee
