### ISSUE TITLE
Shows Beautification in progress everytime

### ISSUE THREAD

**Issue by niranjan-mitrai** [Glavin001/atom-beautify#1471]
# Description

When I tried to beautify my code it shows Beautification in progress on atom. This issue has occurred after I update my atom. Now my version is 1.13.0

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by Glavin001** [comment]
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/1458

Please provide your `debug.md` Gist link as a comment over at #1458.

**Comment by Glavin001** [comment]
Published fix of #1432 to v0.29.17! Thank you for your patience!
