### ISSUE TITLE
Support for .ex files

### ISSUE THREAD

**Issue by cedrico2016** [Glavin001/atom-beautify#1474]
The support for .ex files is not found? is there any way to solve that? 
Best regards.

**Comment by prettydiff** [comment]
What is an ex file?

**Comment by cedrico2016** [comment]
I mean elixir files. 
http://elixir-lang.org/

**Comment by cedrico2016** [comment]
![screenshot from 2017-01-17 02-00-35](https://cloud.githubusercontent.com/assets/20278476/22004073/e5092704-dc58-11e6-819b-5f3c0604eeec.png)

This is what was displayed.

**Comment by prettydiff** [comment]
I am marking this as a duplicate of https://github.com/Glavin001/atom-beautify/issues/545
