### ISSUE TITLE
Incorrect beautifying of markdown literal asterisks

### ISSUE THREAD

**Issue by SV-AlphaDelta** [Glavin001/atom-beautify#1476]
# Description

The results of beautification are not what I expect.

Different variations of the bug was discovered in both Remark and Tidy. As per the markdown spec, asterisks and underscores surrounded with spaces should not be interpreted as emphasizing text. 

In Remark, the Asterisks are replaced with underscores, though still with a space between the underscores and `B`. In TIdy Markdown, the asterisks are directly converted to underscores surrounding `B`.

# Input Before Beautification

This is what the code looked like before:

```
A * B * C
```

# Expected Output

The beautified code should have looked like this:

```
A * B * C
```

# Actual Output

The beautified code actually looked like this:

```
A _B_ C
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/to-boldly-go/dfd1b8673be8d698921a57fc35580e0a

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Looks like a defect from the beautifier, which appears to be something named Tiny Markdown.
