### ISSUE TITLE
HTML Invisible Line Breaks?

### ISSUE THREAD

**Issue by thejamespower** [Glavin001/atom-beautify#1478]
# Description

We often get copy supplied to us from clients in Word documents. When we copy the content from word to Atom and beautify, strange line breaks appears in the copy. I'm assuming they are some kind of weird carriage return that is used in Word? Removing the line breaks and any extra spaces generated and re-beautifying produces the same results. Any help debugging this would be extremely helpful. We are using @prettydiff :)

# Input Before Beautification

This is what the code looked like before:

```
<p class="article__paragraph">The course of MM is punctuated by repeated treatment responses followed by inevitable disease relapses. \[(24327) 4,] \[(2784) 5,] With each relapse, the disease becomes more resistant to existing treatments. \[(6045) 6,] \[(6046) 7,] Although treatment advances have prolonged OS and PFS, MM inevitably progresses to a treatment-refractory state where the outlook remains poor. \[(283) 8,] MM patients refractory to both PIs and IMiDs have a median OS of only 9 months, underlining a continued urgent need for novel treatment options. \[(5678) 1,] \[(604) 2,]</p>
```

# Expected Output

The beautified code should have looked like this:

```
<p class="article__paragraph">The course of MM is punctuated by repeated treatment responses followed by inevitable disease relapses. \[(24327) 4,] \[(2784) 5,] With each relapse, the disease becomes more resistant to existing treatments. \[(6045) 6,] \[(6046) 7,] Although treatment advances have prolonged OS and PFS, MM inevitably progresses to a treatment-refractory state where the outlook remains poor. \[(283) 8,] MM patients refractory to both PIs and IMiDs have a median OS of only 9 months, underlining a continued urgent need for novel treatment options. \[(5678) 1,] \[(604) 2,]</p>
```

# Actual Output

The beautified code actually looked like this:

```
        <p class="article__paragraph">The course of MM is punctuated by repeated treatment responses followed by inevitable disease relapses. \[(24327) 4,] \[(2784) 5,] With each relapse, the disease becomes more resistant to existing treatments. \[(6045)
          6,] \[(6046) 7,] Although treatment advances have prolonged OS and PFS, MM inevitably progresses to a treatment-refractory state where the outlook remains poor. \[(283) 8,] MM patients refractory to both PIs and IMiDs have a median OS of only 9
          months, underlining a continued urgent need for novel treatment options. \[(5678) 1,] \[(604) 2,]</p>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Not relevant.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
It just looks like word wrap is wrapping the selected content.  The default wrap length in Atom Beautify is 250 characters.  Try changing that value in the Atom Beautify settings to 0, which will eliminate word wrap.

If I have failed to resolve this issue please reopen it.

**Comment by thejamespower** [comment]
Doh! Can't believe it was that simple. Thanks @prettydiff
