### ISSUE TITLE
conflict with linter-cpplint plugin

### ISSUE THREAD

**Issue by Foadsf** [Glavin001/atom-beautify#1481]
unfortunately there is a styling conflict between linter-cpplin and atom-beautify. when I use them together cpplint warns me:
`At least two spaces is best between code and comments [whitspace/comments]`
also a screenshot

<img width="642" alt="screen shot 2017-01-23 at 21 19 01" src="https://cloud.githubusercontent.com/assets/12762442/22221230/52c09c60-e1b2-11e6-99dd-ce969c8ca92c.png">

it would be great if two teams could resolve this issue!
[link to the same issue reported for linter-cpplint plugin](https://github.com/AtomLinter/linter-cpplint/issues/63)

**Comment by prettydiff** [comment]
Please provide the generated debug.md file in a gist.  We cannot move forward without that file.  Please reopen the issue once updated and we will triage this.
