### ISSUE TITLE
Always 8 characters with uncrustify

### ISSUE THREAD

**Issue by DXXL** [Glavin001/atom-beautify#1484]
Atom-Beautify is always typing 8 spaces as indent although the editor settings of atom are set to 4 (while using uncrustify for c++). If I set my editor to hard indention Atom-Beautify will use 8 tabs (!) as indention. I have tried changing the config file of uncrustify (in the Atom-Beautify package). Changing the config.coffee also makes no difference.

**Comment by prettydiff** [comment]
I will reopen this defect once we have access to your debug.md file.  Until that time we do not have the necessary information to debug the problem.

**Comment by nyaapass** [comment]
if you want to change the tab width from 8(Unix default) to 4:
```
$ atom ~/.atom/packages/atom-beautify/src/beautifiers/uncrustify/default.cfg
output_tab_size = 4 # (edit about line 14) 
indent_columns  = 4 # (edit about line 42) 
```
then change path of the C and C++ setting of atom-beautify:
`~/.atom/packages/atom-beautify/src/beautifiers/uncrustify/default.cfg`

**Comment by Kailash23** [comment]
> if you want to change the tab width from 8(Unix default) to 4:

>$ atom ~/.atom/packages/atom-beautify/src/beautifiers/uncrustify/default.cfg
>output_tab_size = 4 # (edit about line 14) 
>indent_columns  = 4 # (edit about line 42) 
>then change path of the C and C++ setting of atom-beautify:
>~/.atom/packages/atom-beautify/src/beautifiers/uncrustify/default.cfg

### **+**

comment out the align_number_left
>(in default.cfg , otherwise it will give an error)
