### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by brainytwoo** [Glavin001/atom-beautify#1485]
Lua is listed as one of the supported languages... why do I keep getting this error when I try to use it?

"Could not find 'perl'. The program may not be installed."

**Comment by prettydiff** [comment]
That means the Lua beautifier that you are using through Atom Beautify requires Perl.

**Comment by brainytwoo** [comment]
Could you please post a link to the perl that I would need to install?

**Comment by prettydiff** [comment]
Perl can be downloaded from https://www.perl.org/get.html

The version of Perl you might need depends upon the requirements of the Lua beautifier you are using.  I recommend creating a debug.md file so that you can see the beautifier by name.

**Comment by brainytwoo** [comment]
I am very sorry for having wasted your time.
After you install perl and beautify still gets the error simply restart your computer and it will work perfectly.
Again I apologize for wasting anyones time with this issue.
I love Beautify btw

**Comment by prettydiff** [comment]
Naw, you don't know if you don't know.  I am not complaining.

**Comment by Glavin001** [comment]
The Lua beautifier has now be re-written in Node.js / JavaScript so users, like yourself, will no longer need to install perl 😃 ! https://github.com/Glavin001/atom-beautify/pull/1572

**Comment by brainytwoo** [comment]
Sweet thx dude.
Just in time too, just got a new pc.

Brian De Guire

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
