### ISSUE TITLE
atom-beautify the installation process never ends.

### ISSUE THREAD

**Issue by vpalakurthi** [Glavin001/atom-beautify#1489]
# Description

atom-beautify the installation process never ends.

# Steps to Reproduce

1. Install the atom-beautify from atom package manager. The installation will never end. Upon restarting the atom it shows as installed but the beautify does not work. Provides a red flag showing autopep8 program may not be installed.

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by trystan2k** [comment]
I am getting the same issue.

I executed via command line with verbose and see that it stopes here:

REQUEST reading response's body
REQUEST finish init function https://registry.npmjs.org/js-yaml
REQUEST response end https://registry.npmjs.org/js-yaml 304 { date: 'Mon, 30 Jan 2017 10:54:50 GMT',
  via: '1.1 varnish',
  'cache-control': 'max-age=300',
  etag: 'W/"58889305-14f14"',
  age: '95',
  connection: 'close',
  'x-served-by': 'cache-lhr6326-LHR',
  'x-cache': 'HIT',
  'x-cache-hits': '9',
  'x-timer': 'S1485773690.148964,VS0,VE0',
  vary: 'Accept-Encoding' }
REQUEST end event https://registry.npmjs.org/js-yaml
REQUEST emitting complete https://registry.npmjs.org/js-yaml

Hope this info helps

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by RiahShay** [comment]
Having this problem as well

**Comment by noahhi** [comment]
having the same problem

**Comment by gambolputty** [comment]
having the same problem

**Comment by szeck87** [comment]
Are you behind a firewall and/or proxy?

**Comment by gambolputty** [comment]
I had the same problem. Restarted Atom and tried again. It took a while, but the package got installed in the end. I'm not behind a firewall or proxy.
