### ISSUE TITLE
Beautify breaks interpolated text variables in SCSS files

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#149]
See attached animated GIF:

![scss-beautify](https://cloud.githubusercontent.com/assets/835148/5304893/d7c281cc-7bc4-11e4-8f2d-80dd7b6ede21.gif)

This block breaks the code if beautified.  The `#{$name}` must not be broken onto lines.
````
@mixin text-emphasis-variant($parent, $color) {
  #{$parent} {
    color: $color;
  }
  a#{$parent}:hover {
    color: darken($color, 10%);
  }
}
`````

**Comment by Glavin001** [comment]
Published to v0.18.0. Happy New Year! :smiley:
