### ISSUE TITLE
How to disable reformatting of ternary operators?

### ISSUE THREAD

**Issue by derwaldgeist** [Glavin001/atom-beautify#1491]
Since JSBeautify breaks my JSX files, I am using PrettyDiff now for JSX beautification. But there is a behavior that drives me nuts since it conflicts with my linter: the reformat of ternary operators.

PrettyDiff automatically converts this

```js
const a = b ? c : d;
````
into this
```js
const a =
  ? b
  : c;
```

Can I disable this?

**Comment by prettydiff** [comment]
Pretty Diff has an option named `ternaryline` that is false by default.  You need to set this to true.  If the option is not exposed to Atom Beautify then you will need to create a pull request to add the option in.

**Comment by Glavin001** [comment]
The `ternaryline` option is available: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L43
It is called `preserve_ternary_lines`.

**Comment by derwaldgeist** [comment]
Thanks for the fast reply. Worked.

Is there also an option to prevent object literals from collapsing? I guess it's the formatObject option of PrettyDiff. Could not find this in the .coffee file.

**Comment by Glavin001** [comment]
Glad to hear!

If you know the option for Pretty Diff and see it is missing support in Atom-Beautify, please feel free to submit a Pull Request adding support. Let us know if you have any questions! Take a look at https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language to get started.

**Comment by derwaldgeist** [comment]
Great, will try my best :-)
