### ISSUE TITLE
Using for react / react-native (JSX)

### ISSUE THREAD

**Issue by indivisable** [Glavin001/atom-beautify#1493]
# Description

What is the best setup for using atom-beautify with react or react-native? It seems to be tricky to get it to work well with JSX, espeicially when using the *.js file extension like react-native uses.

Related Issues:
https://github.com/Glavin001/atom-beautify/issues/742 <-- most related
https://github.com/Glavin001/atom-beautify/issues/774
https://github.com/Glavin001/atom-beautify/issues/1454

# Input Before Beautification

This is what the code looked like before:

```
import { Component } from 'react';
import { View, Text, Image } from 'react-native';

export default class extends Component {
    render() {
        return (
            <View style={styles.test}>
              <Text style={{color:'red'}}>Test</Text>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    test: {
        backgroundColor: 'red'
    }
});
```

# Expected Output

The beautified code should have looked like this: **(same as above just to test)**

```
import { Component } from 'react';
import { View, Text, Image } from 'react-native';

export default class extends Component {
    render() {
        return (
            <View style={styles.test}>
              <Text style={{color:'red'}}>Test</Text>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    test: {
        backgroundColor: 'red'
    }
});
```

# Actual Output

The beautified code actually looked like this:

```
import {
    Component
} from 'react';
import {
    View,
    Text,
    Image
} from 'react-native';

export default class extends Component {
    render() {
        return (
            <View style={styles.test}>
                <Text style={{
                    color: 'red'
                }}>Test</Text>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    test: {
        backgroundColor: 'red'
    }
});
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/indivisable/b11dd57c529e7c258d720b9fe1a654db

# Checklist

I have:
- [X ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
To solve this problem you need to submit a pull request adding support for Pretty Diff's [neverflatten](http://prettydiff.com/documentation.xhtml#neverflatten) option.  It seems there exists a pull request for this that you could pick up: https://github.com/Glavin001/atom-beautify/pull/1289

**Comment by indivisable** [comment]
@prettydiff this does not solve, I integrated this and get same results.

**Comment by prettydiff** [comment]
I tested at http://prettydiff.com/?m=beautify&neverflatten=true and it worked there.  It could be that the last version of Pretty Diff published to NPM is 1.16.37, but current version 2.1.16.  I aggressively working to close that gap, see #881.

**Comment by indivisable** [comment]
@prettydiff Thanks, prettydiff is a great tool, lucky to have found it today :)

I tried on the website too with neverflatten and got same results:

![image](https://cloud.githubusercontent.com/assets/22860891/22411725/76a0655c-e66c-11e6-9273-feab11d71feb.png)

**Comment by prettydiff** [comment]
Sorry, I provided bad instructions.  The neverflatten option needs to be set to false. and your import lists will be flattened.

**Comment by Babazon** [comment]
Using for React JSX it sometimes simply deletes parts of the code and breaks it. 

This part at the end of my every React Redux component is deleted when atom-beautify finds an error (and sometimes randomly) in the html markup part of the jsx. I tested with all beautifiers (JSDiff etc..) provided for JS and JSX. 

I will make a gif of me recreating the bug and update this comment.

```
};
export default connect()(Component); 
```

**Comment by prettydiff** [comment]
@Babazon If you could open a new issue please.  That sounds like a different issue.

**Comment by prettydiff** [comment]
Closing as this issue appears to be resolved.  If I am closing this issue incorrectly please reopen it.
