### ISSUE TITLE
[SCSS] AB Adding Additional Spaces into Quoted Text String

### ISSUE THREAD

**Issue by maxxcrawford** [Glavin001/atom-beautify#1499]
# Description

SCSS adds additional spaces in a quoted string, breaking the code. 

# Input Before Beautification

This is what the code looked like before:

```
.class-name {
    color: blue;
    @include media('>=' + $switch-to-mobile-width) {
        color: red;
    }
}
```

# Expected Output

The beautified code should have looked like this:

```
.class-name {
    color: blue;

    @include media ('>=' + $switch-to-mobile-width) {
        color: red;
    }
}
```

# Actual Output

The beautified code actually looked like this:

```
.class-name {
    color: blue;

    @include media (' > =' + $switch-to-mobile-width) {
        color: red;
    }
}

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/f8f325d694eeb03601596957ec6c6ae3

# Checklist

I have:
- [X ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
This is a defect present in Pretty Diff version 1.16.37 which is included with Atom Beautify.  I cannot reproduce the defect in the current version 2.1.16.  I am working on getting an updated version into Atom Beautify at https://github.com/Glavin001/atom-beautify/issues/881

**Comment by maxxcrawford** [comment]
@prettydiff Thanks!
