### ISSUE TITLE
Marking a block of code in a file to be not beautfied

### ISSUE THREAD

**Issue by safm** [Glavin001/atom-beautify#1501]
It would be nice if we can mark a block of code in a file to be not beautified. 

Sometimes I need to arrange my collection (objects inside an array) in a way which is easier to read rather it being beautified.

**Comment by prettydiff** [comment]
What type of file and what beautifier are you using?

**Comment by safm** [comment]
I am using atom-beautify and the it's a JavaScript file.

```javascript
var arr = [
 { "first": "Abc", "last": "Xyz", "age": 13 },
 { "first": "Xyz", "last": "Abc", "age": 31 }
]
```
This is how I want my this code to be. 

When I beautify the file it beautifies it using the set rules. I would like to some how inform the plugin to not beautify few lines.

First thing that comes to mind is some kind of starting and ending comment that indicates the plugin not beautify lines in-between these two comments. 

```javascript
//atom-beautify: start-ignore
var arr = [
 { "first": "Abc", "last": "Xyz", "age": 13 },
 { "first": "Xyz", "last": "Abc", "age": 31 }
]
//atom-beautify: end-ignore
```
Something like this.

**Comment by prettydiff** [comment]
The default beautifier for JavaScript is JS-Beautify.  You can see this if you generate a debug.md file https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

I recommend opening an issue with JS-Beautify at https://github.com/beautify-web/js-beautify/issues

I have opened an issue with Pretty Diff at https://github.com/prettydiff/prettydiff/issues/415

**Comment by safm** [comment]
Thanks @prettydiff for pointing me in the right direction.
JS-Beautify already supports ignoring based on comments.
https://github.com/beautify-web/js-beautify#user-content-directives-to-ignore-or-preserve-sections-javascript-only

**Comment by prettydiff** [comment]
In that case you have either found a defect or you aren't using JS-Beautify as your JavaScript beautifier.  Could you prepare a debug.md and paste it into a gist?

**Comment by safm** [comment]
No. What I meant was they already have support for it. Once I placed the comment in the correct format, JS-beautify ignored the code.

**Comment by prettydiff** [comment]
Awesome, then I can close this issue.
