### ISSUE TITLE
Atom-Beautify has uninstalled dependencies

### ISSUE THREAD

**Issue by c650** [Glavin001/atom-beautify#1503]
When I installed this package from within Atom, I soon realized that I could not use it out of the box because it depended on other pieces of software like `uncrustify`.

Can the package itself install these dependencies so that I as a user do not have to?

Thank you.

**Comment by Glavin001** [comment]
> Can the package itself install these dependencies so that I as a user do not have to?

Unfortunately, no. Atom-Beautify supports Atom on Mac, Windows, and Linux. These third-party beautifiers, such as `uncrustify`, require custom installation instructions for each and with a wide variety of different languages. It is significantly easier for a human to follow the applicable instructions than have Atom-Beautify handle cross-platform installation of all of the beautifiers.

A list beautifiers and whether they are pre-installed can be found at https://github.com/Glavin001/atom-beautify#beautifiers
