### ISSUE TITLE
Getting Installing Problem Again and Again

### ISSUE THREAD

**Issue by Rohiii** [Glavin001/atom-beautify#1504]
I have tried to install it lots of time after upgrading my system. Before its working like chap but after formatting my system i cant install this package any more all time getting this error. Please help me to fix it.

Installing “atom-beautify@0.29.17” failed.Hide output…

> atom-beautify@0.29.17 postinstall C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9\node_modules\atom-beautify
> npm run build-options

C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Koushik Rohi\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Koushik Rohi\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
'C:\Users\Koushik' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9\package.json'
npm WARN apm-install-dir-11717-3752-1xschm9 No description
npm WARN apm-install-dir-11717-3752-1xschm9 No repository field.
npm WARN apm-install-dir-11717-3752-1xschm9 No README data
npm WARN apm-install-dir-11717-3752-1xschm9 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Koushik Rohi\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Koushik Rohi\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Koushik Rohi\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Koushik Rohi\\.atom\\.apmrc" "install" "C:\\Users\\KOUSHI~1\\AppData\\Local\\Temp\\d-11717-3752-7fc3c5\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.17 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.17 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Koushik Rohi\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Koushik Rohi\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Koushik Rohi\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Koushik Rohi\\.atom\\.apmrc" "install" "C:\\Users\\KOUSHI~1\\AppData\\Local\\Temp\\d-11717-3752-7fc3c5\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9\npm-debug.log.3795009212
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9\npm-debug.log.3795009212' -> 'C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9\npm-debug.log'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\KOUSHI~1\AppData\Local\Temp\apm-install-dir-11717-3752-1xschm9\npm-debug.log
npm ERR! code 1

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
Tracking at #1490

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.

**Comment by redbonzai** [comment]
Run the command : `npm install -g minimatch@3.0.2`
The result should be : `+ minimatch@3.0.2
added 4 packages in 2.186s`

Then run : `npm install`
Problem fixed.  Yay!
