### ISSUE TITLE
angularjs package for templates

### ISSUE THREAD

**Issue by phstoned** [Glavin001/atom-beautify#1505]
Hello.
Trying to beautify templates, where is selected language is Html(Angular), takes forever.
This appears with the following package: 
[AngularJS-atom](https://github.com/angular-ui/AngularJS-Atom)

However switching to default Html, then pressing beautify everything works fine.

Maybe it would be good for all Html extensions to beautify exactly as default Html?
I just needed the indentations, and I think this is most reason to beautify the file, to intend the code.

**Comment by prettydiff** [comment]
Could you prepare a debug.md file and past it into a gist?  We cannot move forward without it.  Please reopen the issue at that time and we will investigate.

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md
