### ISSUE TITLE
CUDA grammar and .cu .cuh file extensions support 

### ISSUE THREAD

**Issue by CodefroesPuc** [Glavin001/atom-beautify#1506]
# Description

Could you include support for CUDA language grammar and .cu, .cuh file extensions? It could totally replicate C/C++ beautification. 

Thank you.

I have:
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.

**Comment by prettydiff** [comment]
You could add this update in a pull request.  See this getting started guide at https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md and let us know what questions you have.  You probably just need to extend the file https://github.com/Glavin001/atom-beautify/blob/master/src/languages/cpp.coffee

**Comment by CodefroesPuc** [comment]
New to contributing...
I made a Pull Request. Not really sure if I should check all the tasks as completed. I don't think they apply, anyway. What now? :)

**Comment by Glavin001** [comment]
Published to v0.29.19
