### ISSUE TITLE
Indentation Problem for Object Matching with Default Values

### ISSUE THREAD

**Issue by guiguan** [Glavin001/atom-beautify#1508]
In js,
**expect**:
```js
    const {
      shouldSave = true,
      Controller,
      updateLinks = true
    } = options;
```
**actual**:
```js
    const {
      shouldSave = true,
        Controller,
        updateLinks = true
    } = options;
```

**Comment by prettydiff** [comment]
Please paste a debug.md into a gist.  Without this we do not have enough evidence to investigate.  Once the debug.md is available please reopen this issue and we will investigate.

**Comment by guiguan** [comment]
@prettydiff hi, here is the gist: https://gist.github.com/guiguan/7ad6ac4132c18f4f1ee3c6f1138abf38. Please reopen the issue.

**Comment by prettydiff** [comment]
This is a JS Beautify only bug.  I can reproduce it at http://jsbeautifier.org/  I am currently checking to see if they have an existing issue open for this and if not I will create a new one.

**Comment by guiguan** [comment]
Oh, okay. Thanks!
