### ISSUE TITLE
GitHub Markdown links broken

### ISSUE THREAD

**Issue by dkaksl** [Glavin001/atom-beautify#1512]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
[atomtest.md](atomtest.md)
```

# Expected Output

The beautified code should have looked like this:

```
[atomtest.md](atomtest.md)
```

# Actual Output

The beautified code actually looked like this:

```
<atomtest.md>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/dkaksl/4eace81b10b201169528c0431d8f1b32#file-debug-md

# Checklist

I have:
- [✔] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [✔] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [✔] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [✔] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [✔] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Where did you see this broken link at?

**Comment by dkaksl** [comment]
@prettydiff Just a private project README.md I was working on. As you can see in the debug.md, it recreates for some reason with a very minimal document.

**Comment by prettydiff** [comment]
I opened an issue with the Tidy Markdown project.

**Comment by prettydiff** [comment]
Resolved in third-party library.

**Comment by dkaksl** [comment]
@prettydiff any idea on the timeline until this is released?

**Comment by prettydiff** [comment]
I have no idea.  You would have to ask the maintainers of the Tidy Markdown project.

**Comment by dkaksl** [comment]
@prettydiff the linked issue (or rather the [parent issue](https://github.com/slang800/tidy-markdown/issues/38)) shows that the bug was fixed with a commit to the master branch, so it looks like it is resolved in the TM project.

I'm not sure how this propagates into the beautify project, though. Hence the question.
