### ISSUE TITLE
Beautify on save for Html is not working properly

### ISSUE THREAD

**Issue by agravat202** [Glavin001/atom-beautify#1517]
hello,
  i don't know why this is happning but i want to use 

> Beautify on save

 option for html but it's not working, while for JavaScript is working cool. 
system information
i am on ubuntu 16.04 , and using theme atom Light for Ui and one light for syntax .
hop i get guidelines asap. 
thank you.

**Comment by prettydiff** [comment]
Could you generate the debug.md file and save that to a gist?

**Comment by agravat202** [comment]
Actually I am new user of atom so don't know how to get debug.md file. Else
currently I just uninstall package and will install in short future.


One more information. Me and my other team member get same problem with its
like when we save code it Beautyfy but some extra code appand to bottom of
file which generates error. So we both uninstall it.

**Comment by agravat202** [comment]
Before Save : 
`		query: {
			isArray: false
		},
		update: {
			method: 'PUT'
		}
	});
}]);`

and after save : 
`		query: {
			isArray: false
		},
		update: {
			method: 'PUT'
		}
	});
}]);
	method: 'PUT'
		}
	});
}]);
`

**Comment by prettydiff** [comment]
The debug.md file can be generated with these instructions: https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

This issue looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/1213

**Comment by agravat202** [comment]
ok it will take time to sent you debug.md file coz i am working on something and yes it's looks my problem is very similar  #1213. 

But again . i have other issue : 
i setup for html , when i save file it has to be beautify but it won't.

**Comment by prettydiff** [comment]
The beautify on save doing nothing for all with the HTML is possibly a different defect.  Again, it would be helpful to that that debug.md in both cases so that we can see what your software configuration is and what beautifiers you are using.

If you changed beautifiers are both of these problems resolved?  I suspect, from the other issue, that the defect is related to a how a particular beautifier is configured in Atom Beautify.

**Comment by agravat202** [comment]
Oky I will sent you my configuration's screenshots and .MD file asap.

**Comment by dgroh** [comment]
Any feedback on this? Beautify on save for HTML file is not working
