### ISSUE TITLE
HTML wrap-line-length config property not inheriting correctly 

### ISSUE THREAD

**Issue by jwhitmarsh** [Glavin001/atom-beautify#1518]
# Description

When beautifying HTML, the `wrap-line-length` property is being set from the `js` settings of my `.jsbeautifyrc` not the `html`.

# Input Before Beautification

This is what the code looked like before:

```
<!DOCTYPE html>
<div>
  <gvd-header start-tour-fn="startTour()" show-tour-button="true"></gvd-header>
  <div class="header-divider"></div>
  <div ng-intro-options="gvdDashVm.introOptions" ng-intro-method="startTour" ng-intro-autostart="false" ng-intro-onbeforechange="gvdDashVm.tourOnBeforeChange"
      ng-intro-onafterchange="gvdDashVm.tourOnAfterChange" ng-intro-refresh-method="gvdDashVm.tourRefresh">
</div>
</div>
```

# Expected Output

The beautified code should have looked like this:

```
<!DOCTYPE html>
<div>
    <gvd-header start-tour-fn="startTour()" show-tour-button="true"></gvd-header>
    <div class="header-divider"></div>
    <div ng-intro-options="gvdDashVm.introOptions" ng-intro-method="startTour" ng-intro-autostart="false" ng-intro-onbeforechange="gvdDashVm.tourOnBeforeChange" ng-intro-onafterchange="gvdDashVm.tourOnAfterChange" ng-intro-refresh-method="gvdDashVm.tourRefresh">
    </div>
</div>
```

# Actual Output

The beautified code actually looked like this:

```
<!DOCTYPE html>
<div>
  <gvd-header start-tour-fn="startTour()" show-tour-button="true"></gvd-header>
  <div class="header-divider"></div>
  <div ng-intro-options="gvdDashVm.introOptions" ng-intro-method="startTour" ng-intro-autostart="false" ng-intro-onbeforechange="gvdDashVm.tourOnBeforeChange"
      ng-intro-onafterchange="gvdDashVm.tourOnAfterChange" ng-intro-refresh-method="gvdDashVm.tourRefresh">
</div>
</div>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist:https://gist.github.com/jwhitmarsh/de5bf68f0173992c0a1c486e3c6ea10f

You can see the HTML wrap-line-length is set to 500, but in the Final Options it's 120

# Checklist

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by ardean** [comment]
+1
