### ISSUE TITLE
Atom Beautify could not find a supported beautifier for this file

### ISSUE THREAD

**Issue by helloworldtang** [Glavin001/atom-beautify#1521]
![atombeauty](https://cloud.githubusercontent.com/assets/13701989/23157754/65f0006c-f857-11e6-9a12-340570bcff40.png)

**Comment by prettydiff** [comment]
This isn't an Atom Beautify defect.  Atom Beautify cannot guess at the language type by looking at the file extension `.roadhogrc`.  It looks like this is JSON format so just manually select JSON using Edit -> Select Grammar from the main menu.
