### ISSUE TITLE
Error Install 

### ISSUE THREAD

**Issue by quantumlap** [Glavin001/atom-beautify#1531]
Installing “atom-beautify@0.29.17” failed.Hide output…

> atom-beautify@0.29.17 postinstall /private/var/folders/_r/cpdpg5s94913_pbdgy435xzc0000gn/T/apm-install-dir-117127-5078-vwng42/node_modules/atom-beautify
> npm run build-options

/private/var/folders/_r/cpdpg5s94913_pbdgy435xzc0000gn/T/apm-install-dir-117127-5078-vwng42
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/npm.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/npm:25:13
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/npm:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/_r/cpdpg5s94913_pbdgy435xzc0000gn/T/apm-install-dir-117127-5078-vwng42/package.json'
npm WARN apm-install-dir-117127-5078-vwng42 No description
npm WARN apm-install-dir-117127-5078-vwng42 No repository field.
npm WARN apm-install-dir-117127-5078-vwng42 No README data
npm WARN apm-install-dir-117127-5078-vwng42 No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/fabioc/.atom/.apm/.apmrc" "--userconfig" "/Users/fabioc/.atom/.apmrc" "install" "/private/var/folders/_r/cpdpg5s94913_pbdgy435xzc0000gn/T/d-117127-5078-ub4z07/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.17 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.17 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/_r/cpdpg5s94913_pbdgy435xzc0000gn/T/apm-install-dir-117127-5078-vwng42/npm-debug.log
npm ERR! code 1

**Comment by MartyBum** [comment]
Same here. Atom 1.9.9

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
