### ISSUE TITLE
Antivirus detection

### ISSUE THREAD

**Issue by steronydh** [Glavin001/atom-beautify#1532]
I've just installed 0.29.17, and Avira detected occurrences of HTML/ExpKit.Gen2 in C:\Users\Name\.atom\.apm\registry.npmjs.org\which\.cache.json

Not sure if this is an atom-beautify problem or Avira being over-sensitive.

**Comment by prettydiff** [comment]
Thanks for letting us know.  That does not appear to be associated with this repo directly, but could be included indirectly from a dependency.

**Comment by prettydiff** [comment]
What language were you attempting to beautify?

**Comment by steronydh** [comment]
I hadn't got that far - it seemed to be picked up during the installation. I had previously uninstalled it because of #1423, and was reinstalling it because d4nirod said that it was OK now.

**Comment by steronydh** [comment]
I've just tried uninstalling and reinstalling it, and it's definitely during the install process.

**Comment by steronydh** [comment]
More info - I think it's related to node-which. I've let them know.

**Comment by steronydh** [comment]
Avira confirm it's clean, so a false positive at their end. :)

**Comment by Noobincoding** [comment]
I had the same issue when i was trying to install angular cli. Am i in the safe side? Are you guys sure its only Avira acting out?

**Comment by prettydiff** [comment]
Yes, certain.
