### ISSUE TITLE
Issue sorting SCSS

### ISSUE THREAD

**Issue by line47** [Glavin001/atom-beautify#1535]
I'm trying to sort my SCSS properties and not having any luck.
I've got ATOM v 1.14.3 and atom-beautify 0.29.17
SCSS Settings

Screenshot GIF below
![no-sorting](https://cloud.githubusercontent.com/assets/1449852/23444906/eed4e114-fe05-11e6-9213-e55d4ada6107.gif)

# Expected Output

The SCSS properties to be sorted alphabetically.

# Actual Output

The SCSS properties are not sorted.

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by prettydiff** [comment]
Could you please prepare a debug.md file and save into a gist?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

Pretty Diff is the default beautifier for SCSS and I cannot reproduce the problem in Pretty Diff.

**Comment by prettydiff** [comment]
Please reopen this issue once the necessary debug.md file is prepared.

**Comment by line47** [comment]
Here is the debug file requested, thanks! https://gist.github.com/line47/985f3e82e593c5288251aef4528959b7#file-debug-md

**Comment by Glavin001** [comment]
Closing as a duplicate of https://github.com/Glavin001/atom-beautify/issues/1559
