### ISSUE TITLE
Uncaught TypeError: Cannot read property 'readJSON' of undefined

### ISSUE THREAD

**Issue by rbaprado** [Glavin001/atom-beautify#154]
Uncaught TypeError: Cannot read property 'readJSON' of undefined

**Atom Version**: 0.161.0
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.17.2

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At d:\buzz\Projetos\mobtag\backend\Gruntfile.js:25

TypeError: Cannot read property 'readJSON' of undefined
  at module.exports (d:\buzz\Projetos\mobtag\backend\Gruntfile.js:25:20)
  at Builder.discoverBuildSystem (c:\Users\buzz\.atom\packages\build-systems\lib\builder.coffee:83:13)
  at Builder.discoverBuildSystems (c:\Users\buzz\.atom\packages\build-systems\lib\builder.coffee:112:10)
  at c:\Users\buzz\.atom\packages\build-systems\lib\main.coffee:20:31

```

/cc @atom/core

**Comment by Glavin001** [comment]
From your log in the Issue it looked like this package was the culprit to me: https://atom.io/packages/build-systems

Good luck and let me know if there's anything I can do with Atom Beautify.
