### ISSUE TITLE
setting "indent size = 2" not work

### ISSUE THREAD

**Issue by hefei00** [Glavin001/atom-beautify#1540]
# setting "indent size = 2" not work

The results of beautification are not what I expect. I set the 'indent size: 2'. but after running command `Atom Beautify: Beautify Editor`.The indent size is 4. 

# Input Before Beautification

```
function Test(name) {
  this.name = name
}

```

# Expected Output

```
function Test(name) {
  this.name = name
}
```

# Actual Output

```
function Test(name) {
    this.name = name
}

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by smackgg** [comment]
+1

**Comment by osro** [comment]
+1

If the beautifier is set to JS Beautify the indent settings does not have any effect on the output, but with Pretty Diff it works.

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
