### ISSUE TITLE
Isse with  PHP-CS-Fixer  v2.1.1

### ISSUE THREAD

**Issue by kaushikindianic** [Glavin001/atom-beautify#1541]
# Description

I update PHP-CS-Fixer with latest version  V2.1.1
Then found that atom-beautify not work properly and not support PSR2

Then I revert to old version and look fine :)

**Comment by raphaabreu** [comment]
It seems that PHP-CS-Fixer 2.x is API incompatible with 1.x version. I also reverted and it worked again.

**Comment by Glavin001** [comment]
https://github.com/Glavin001/atom-beautify/pull/1511 should resolve this issue.

Is it reasonable to expect all PHP-CS-Fixer users to upgrade to 2.x? The PR looks like a breaking change which will not allow PHP-CS-Fixer 1.x users.

**Comment by Glavin001** [comment]
I'm going to close this as solved by #1511 and duplicate of https://github.com/Glavin001/atom-beautify/issues/1465
