### ISSUE TITLE
Can't Install Beautify. 

### ISSUE THREAD

**Issue by rvsingh011** [Glavin001/atom-beautify#1546]
OS : ubuntu 16.04

Error Message : 

/usr/lib/node_modules/npm/node_modules/update-notifier/index.js:2
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:28:17
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:83:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/hackerx/.atom/.apm/.apmrc" "--userconfig" "/home/hackerx/.atom/.apmrc" "install" "/tmp/d-11728-18049-ila95a/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.17 postinstall: `npm run build-options`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.17 postinstall script 'npm run build-options'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
