### ISSUE TITLE
Breaks .twig templates

### ISSUE THREAD

**Issue by rhazor** [Glavin001/atom-beautify#1554]
Reproduce: open .twig template > ctrl+alt+b:

![twig](https://cloud.githubusercontent.com/assets/22996586/23902496/01f105d8-08ca-11e7-8307-cabf9e446e30.gif)

Drupal is pretty huge and popular CMS and Drupal 8 comes with .twig templating.

**Comment by prettydiff** [comment]
I need you to please create the debug.md file.  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

Please reopen this issue once a gist containing the debug.md is created.

**Comment by rhazor** [comment]
https://gist.github.com/rhazor/52f73e691d8cbd1c1c0e44d3367af540

**Comment by prettydiff** [comment]
Thank you.  This clearly appears to be a Pretty Diff defect related to version 1.16.37, which is the version in Atom Beautify.  Whatever the defect is it seems I have resolved the defect and it is no longer present in the current version of Pretty Diff.

Pretty Diff is horribly out of date in Atom Beautify and I am entirely to blame.  I am working on a resolution.  Resolution is https://github.com/prettydiff/prettydiff/issues/409 but I am knocking out unrelated issue https://github.com/prettydiff/prettydiff/issues/268 first.  I am making good progress on 268, but its a challenging one.

**Comment by prettydiff** [comment]
An updated version of Pretty Diff is now in Atom Beautify.
