### ISSUE TITLE
Babel Problems After Update

### ISSUE THREAD

**Issue by thewolff** [Glavin001/atom-beautify#1555]
# Description

I updated my linter packages as well as Atom. Now Atom Beautify gives me the opposite result of what I expect on my Babel files. What's more, if I manually correct the contents Babel removes the spaces in curly braces after save.

# Input Before Beautification

This is what the code looked like before:

```
import React from 'react'
import { View} from 'react-native'
import { Provider} from 'react-redux'
import { createStore} from 'redux'
import reducers from './reducers'
import { Header} from './components/common'

const App = () => {
    return (
        <Provider store={createStore(reducers)}>
            <View/>
        </Provider>
    );
};

export default App;
```

# Expected Output

The beautified code should have looked like this:

```
import React from 'react';
import { View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common';

const App = () => {
    return (
        <Provider store={createStore(reducers)}>
            <View/>
        </Provider>
    );
};

export default App;

```

# Actual Output

The beautified code actually looked like this:

```
import React from 'react'
import {View} from 'react-native'
import {Provider} from 'react-redux'
import {createStore} from 'redux'
import reducers from './reducers'
import {Header} from './components/common'

const App = () => {
    return (
        <Provider store={createStore(reducers)}>
            <View/>
        </Provider>
    );
};

export default App;

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: [here](https://gist.github.com/thewolff/1dd7d6223d2a590b68f33a506b538124)

# Checklist

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I can see you are using Pretty Diff as your beautifier.  You will need to activate the option `bracepadding` with a value of `true`.  You can see it demonstrated at http://prettydiff.com/?m=beautify&bracepadding=true

I can the option is already available in Atom Beautify at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L44 but it looks like it is set to false in your settings according to the debug.md file (near the bottom of the file).  If this option is not exposed to the Atom Beautify preferences GUI then fix Atom Beautify and submit a pull request.  There is guidance available at https://github.com/Glavin001/atom-beautify/tree/master/docs
