### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by malyarevich** [Glavin001/atom-beautify#1558]
Add stylus 
It same grama of less or sass

**Comment by prettydiff** [comment]
Would you mind testing some stylus code out at http://prettydiff.com/?m=beautify&lang=less and let me know if that tool works?  It is already integrated into Atom Beautify, and so if this works then this could be a very simple enhancement.

**Comment by malyarevich** [comment]
It does not work. Bad idea...
[main.txt](https://github.com/Glavin001/atom-beautify/files/853369/main.txt)

**Comment by prettydiff** [comment]
Yeah, Pretty Diff will not support that.  It looks like SASS syntax opposed to LESS or SCSS.

**Comment by Glavin001** [comment]
Closing this Stylus feature request as a duplicate of https://github.com/Glavin001/atom-beautify/issues/318
