### ISSUE TITLE
Issue sorting SCSS

### ISSUE THREAD

**Issue by line47** [Glavin001/atom-beautify#1559]
# Description

I'm trying to sort my SCSS properties and not having any luck.
I've got ATOM v 1.15.0 and atom-beautify 0.29.17
SCSS Settings

# Input Before Beautification

This is what the code looked like before:

```
li {
  margin: 10px;
  border: 1px red solid;
}
```

# Expected Output

The beautified code should have looked like this: (sorted alphabetically)

```
li {
  border: 1px red solid;
  margin: 10px;
}
```

# Actual Output

The beautified code actually looked like this:

```
li {
  margin: 10px;
  border: 1px red solid;
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/line47/985f3e82e593c5288251aef4528959b7#file-debug-md

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by line47** [comment]
I could not reopen https://github.com/Glavin001/atom-beautify/issues/1535 so I created a new issue.

**Comment by Glavin001** [comment]
Looks like the selected beautifier is `Pretty Diff` and the configuration is:

```json
{
    "inchar": " ",
    "insize": 2,
    "objsort": false,
    "preserve": "none",
    "cssinsertlines": true,
    "comments": "indent",
    "force": true,
    "quoteConvert": "single",
    "vertical": "none",
    "wrap": 0,
    "noleadzero": true,
    "methodchain": true
}
```

I think the option you want is `objsort` for `Pretty Diff`: http://prettydiff.com/documentation.xhtml#objsort
/cc @prettydiff please confirm.

**Comment by prettydiff** [comment]
Yes, objsort option is exactly it!

**Comment by line47** [comment]
@Glavin001 How/where would I make that update?

**Comment by prettydiff** [comment]
Guidance is provided in the docs: https://github.com/Glavin001/atom-beautify/tree/master/docs and the code to update is https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee

**Comment by line47** [comment]
Here is the objsort codeblock. 
``` 
 objsort: (objsort) ->
        objsort or false
      preserve: ['preserve_newlines', (preserve_newlines) ->
        if (preserve_newlines is true ) then \
          "all" else "none"
      ]
```
I'm not sure what to change to get sorting to work can you assist @Glavin001 or @prettydiff

**Comment by prettydiff** [comment]
Yeah, so you just need to include the option name and its choice of values.  The values and types can be determined from the documentation: http://prettydiff.com/documentation.xhtml#objsort

Looks like that option takes several string values: `all`, `css`, `js`, `markup`, `none`

You don't have to worry about making this option conditional upon the preserve_newlines options.  They play well together.

So, the final code might look something like:

```
objsort: ['objsort_assignments', (objsort_assignments) ->
    if (objsort_assignments is true ) then \
        "all" else "none"
]
```
All this activity so far just defines a coded interface between Atom Beautify and the beautifier, Pretty Diff.  It still does not expose the option to the user in the settings.  I modeled the code above from the `vertical: [align_assignments` code in prettydiff.coffee.  To figure out the final step I searched the repo for `align_assignments` and found it used in css.coffee.  So we will need something like:

```
objsort_assignments:
    type: 'boolean'
    default: false
    description: "If properties should be sorted in CSS related code"
```

I am thinking this is all you need, but I am probably wrong.  Some things to look for:

* does this code change work if Pretty Diff is the selected beautifier for CSS when tested on your local after restarting Atom?
* Does this work automagically for SCSS files?
* does this code change break things if Pretty Diff is not the selected beautifier

This should get you pretty close.  If this still doesn't work we can call out to Glavin for additional support.

**Comment by luharinos** [comment]
@prettydiff 
I want to sort CSS properties. So, I did the above code changes as suggested by you but, this code change doesn't work if Pretty Diff is the selected beautifier for CSS when tested on my local after restarting Atom.

Using ATOM v 1.39.1 and atom-beautify 0.33.4 on Windows 10.

**Comment by prettydiff** [comment]
@raoniz Currently Atom Beautify uses a much older version of Pretty Diff.  Please try a code sample at https://prettydiff.com/ and see if the problems persist or if the problems are solved.  If the problems are solved in the browser tool then I just need to get Pretty Diff update in Atom Beautify.

**Comment by luharinos** [comment]
@prettydiff 
Yes, the browser tool works completely fine. 
@Glavin001 
Kindly get the update in Atom Beautify. 

Thank you.
