### ISSUE TITLE
Installing “atom-beautify@0.17.2” failed.

### ISSUE THREAD

**Issue by bojanbjelic** [Glavin001/atom-beautify#156]
Hi,
The installation failed.
I'm on Windows 7, Atom 0.162.0

Here's the output...

Installing “atom-beautify@0.17.2” failed.

npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/coffee-formatter
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/atom-message-panel
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/loophole
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/prettydiff
npm http GET https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/typescript-formatter
npm http 304 https://registry.npmjs.org/coffee-formatter
npm http 304 https://registry.npmjs.org/js-beautify
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/atom-message-panel
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/analytics-node
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/prettydiff
npm http 304 https://registry.npmjs.org/editorconfig
npm http 304 https://registry.npmjs.org/typescript-formatter
npm http 304 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/superagent-proxy
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/uid/0.0.2
npm http 304 https://registry.npmjs.org/lazy
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/component-type
npm http 304 https://registry.npmjs.org/join-component
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/superagent-proxy
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/uid/0.0.2
npm ERR! Error: ENOENT, lstat 'C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8\node_modules\atom-beautify\node_modules\editorconfig\node_modules\commander\Readme.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\bbjel\\AppData\\Local\\atom\\app-0.162.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\bbjel\\AppData\\Local\\atom\\app-0.162.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\bbjel\\AppData\\Local\\atom\\app-0.162.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\bbjel\\.atom\\.apmrc" "install" "C:\\Users\\bbjel\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.17.2\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8\node_modules\atom-beautify\node_modules\editorconfig\node_modules\commander\Readme.md
npm ERR! fstream_path C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8\node_modules\atom-beautify\node_modules\editorconfig\node_modules\commander\Readme.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\bbjel\AppData\Local\atom\app-0.162.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\bbjel\\AppData\\Local\\atom\\app-0.162.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\bbjel\\AppData\\Local\\atom\\app-0.162.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\bbjel\\AppData\\Local\\atom\\app-0.162.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\bbjel\\.atom\\.apmrc" "install" "C:\\Users\\bbjel\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.17.2\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/proxy-agent
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/proxy-agent
npm http GET https://registry.npmjs.org/http-proxy-agent
npm http GET https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/https-proxy-agent
npm http 304 https://registry.npmjs.org/pac-proxy-agent
npm http 304 https://registry.npmjs.org/http-proxy-agent
npm http 304 https://registry.npmjs.org/socks-proxy-agent
npm http GET https://registry.npmjs.org/agent-base
npm http GET https://registry.npmjs.org/rainbowsocks
npm http GET https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/pac-resolver
npm http GET https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/agent-base
npm http 304 https://registry.npmjs.org/rainbowsocks
npm http 304 https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/pac-resolver
npm http 304 https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/file-uri-to-path
npm http GET https://registry.npmjs.org/data-uri-to-buffer
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/netmask
npm http GET https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/thunkify
npm http GET https://registry.npmjs.org/regenerator
npm http 304 https://registry.npmjs.org/file-uri-to-path
npm http 304 https://registry.npmjs.org/netmask
npm http 304 https://registry.npmjs.org/data-uri-to-buffer
npm http 304 https://registry.npmjs.org/ftp
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/degenerator
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/ast-types
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/private
npm http GET https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/defs
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8\node_modules\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\node_modules\ftp\node_modules\readable-stream\lib'
npm ERR! error rolling back  readable-stream@1.1.13 { [Error: EPERM, unlink 'C:\Users\bbjel\AppData\Local\Temp\apm-install-dir-1141119-13192-n257e8\node_modules\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\node_modules\ftp\node_modules\readable-stream\lib']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\bbjel\\AppData\\Local\\Temp\\apm-install-dir-1141119-13192-n257e8\\node_modules\\atom-beautify\\node_modules\\analytics-node\\node_modules\\superagent-proxy\\node_modules\\proxy-agent\\node_modules\\pac-proxy-agent\\node_modules\\get-uri\\node_modules\\ftp\\node_modules\\readable-stream\\lib' }
npm http 304 https://registry.npmjs.org/private
npm http 304 https://registry.npmjs.org/ast-types
npm http 304 https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/config-chain
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/proto-list
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/commander/2.2.0
npm

**Comment by Glavin001** [comment]
Please let me know if you resolved this issue on your own (and how, for others also with same issue) or if this was an unrelated issue to Atom Beautify. If there's anything more I can do let me know and we can reopen this issue. Thanks.

**Comment by bojanbjelic** [comment]
Sure thing - I tried on a virtual machine at home and it worked. I'll try it again when back at the office.

**Comment by Akarienta** [comment]
Hi, very similar issue for me.

my conf
```
Windows 7
Atom 0.165.0
npm 2.1.18
git 1.9.4.msysgit.2
```

I'm behind corporate proxy and have it configured properly in system variables `HTTP_PROXY` and `HTTPS_PROXY ` as well as in `.apmrc` file. I've double checked it and tested it - the proxy setup seems to be right (another Atom's plugins can be installed properly and a usage of git is also fine). 

Here is an output:

```
apm install atom-beautify
Installing atom-beautify to C:\Users\pc00120\.atom\packages failed

npm http GET https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/atom-message-panel
npm http GET https://registry.npmjs.org/coffee-formatter
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/loophole
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/prettydiff
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/typescript-formatter
npm http GET https://registry.npmjs.org/yaml-front-matter
npm http GET https://registry.npmjs.org/node-dir
npm http 304 https://registry.npmjs.org/prettydiff
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/editorconfig
npm http 304 https://registry.npmjs.org/analytics-node
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/typescript-formatter
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/coffee-formatter
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/node-dir
npm http 304 https://registry.npmjs.org/atom-message-panel
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/yaml-front-matter
npm http 304 https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/superagent-proxy
npm http GET https://registry.npmjs.org/uid/0.0.2
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/commander/1.0.0
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/is-browser
npm http GET https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/component-type
npm http 304 https://registry.npmjs.org/join-component
npm http 304 https://registry.npmjs.org/uid/0.0.2
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/superagent-proxy
npm ERR! git fetch -a origin (https://github.com/Benvie/harmony-collections.git) fatal: Unable to find remote helper for 'https'
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/is-browser
npm http 304 https://registry.npmjs.org/commander/1.0.0
npm ERR! Error: Command failed: fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\pc00120\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "c:\\Users\\pc00120\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\pc00120\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\pc00120\\.atom\\.apmrc" "install" "C:\\Users\\pc00120\\AppData\\Local\\Temp\\d-11505-9532-1yq7i7m\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! cwd C:\Users\pc00120\AppData\Local\Temp\apm-install-dir-11505-9532-1999ct4
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/proxy-agent
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/http-proxy-agent
npm http GET https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/socks-proxy-agent
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/https-proxy-agent
npm http 304 https://registry.npmjs.org/pac-proxy-agent
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http 304 https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/http-proxy-agent
npm http 304 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/agent-base
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/pac-resolver
npm http GET https://registry.npmjs.org/stream-to-array
npm http GET https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/rainbowsocks
npm http 304 https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/pac-resolver
npm http 304 https://registry.npmjs.org/get-uri
npm http 304 https://registry.npmjs.org/agent-base
npm http 304 https://registry.npmjs.org/rainbowsocks
npm http 304 https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/data-uri-to-buffer
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/file-uri-to-path
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/netmask
npm http GET https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/thunkify
npm http GET https://registry.npmjs.org/regenerator
npm http 304 https://registry.npmjs.org/data-uri-to-buffer
npm http 304 https://registry.npmjs.org/file-uri-to-path
npm http 304 https://registry.npmjs.org/ftp
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/degenerator
npm http 304 https://registry.npmjs.org/netmask
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/proto-list
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/ast-types
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/ariya/esprima.git)
npm http GET https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/private
npm http GET https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/private
npm http 304 https://registry.npmjs.org/recast
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/ast-types
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/commander/2.2.0
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository 'C:\Users\pc00120\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: Unable to look up github.com (port 9418) (Unknown host.)
npm
```

**Comment by bojanbjelic** [comment]
Hi, unfortunately I still have the same problem at workplace. General internet connectivity requires no proxy settings, but can't say about specific ports.
