### ISSUE TITLE
extra blank space

### ISSUE THREAD

**Issue by antoniochacon** [Glavin001/atom-beautify#1560]
# == 'POST' should stay as == 'POST' but it goes to == ' POST'

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<div class='form-group {% if field.errors %} has-error {% else %}{% if request.method == 'POST' %} has-success {% endif %} {% endif %}'>
```

# Expected Output

The beautified code should have looked like this:

```
<div class='form-group {% if field.errors %} has-error {% else %}{% if request.method == 'POST' %} has-success {% endif %} {% endif %}'>
```

# Actual Output

The beautified code actually looked like this:

```
<div class='form-group {% if field.errors %} has-error {% else %}{% if request.method == ' POST' %} has-success {% endif %} {% endif %}'>

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
It looks like a problem in the code sample in that there is an attribute delimited by a single quote character that contains an internal template attribute also delimited by a single quote character.  I do not have any problems with this once I change either set of quotes to double quote characters.

Please reopen this issue if I got this wrong.
