### ISSUE TITLE
Flow's nullable types.

### ISSUE THREAD

**Issue by jaybowong** [Glavin001/atom-beautify#1565]
# Description

I'm an iOS developer and Swift [Optionals](https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwigrYSSvurSAhWFUrwKHd9dAT0QygQIHjAA&url=https%3A%2F%2Fdeveloper.apple.com%2Flibrary%2Fcontent%2Fdocumentation%2FSwift%2FConceptual%2FSwift_Programming_Language%2FTheBasics.html%23%2F%2Fapple_ref%2Fdoc%2Fuid%2FTP40014097-CH5-ID330&usg=AFQjCNHOuBMHtgkI642rFokkBTRMnNEFDg&sig2=O5UJyRiScW7_Lgg7nRMpKQ) is essential to me. I just started learning JavaScript and happily found that [Flow](https://flowtype.org/) supports [nullable types](https://flowtype.org/docs/nullable-types.html), but the code looks wired and it's hard to read.

# Input Before Beautification

This is what the code looked like before:

```
// @flow

class BeautifyFlowDemo {
    method1(one : ?string) {
        //
    }

    method2(one : ?string, two : ?number) {
        //
    }

    methodWithReturnedValue(one : ?string) : ?string {
        //
    }

}
```

# Expected Output

The beautified code should have looked like this:

```
// @flow

class BeautifyFlowDemo {
    method1(one : ?string) {
        //
    }

    method2(one : ?string, two : ?number) {
        //
    }

    methodWithReturnedValue(one : ?string) : ?string {
        //
    }

}
```

# Actual Output

The beautified code actually looked like this:

```
// @flow

class BeautifyFlowDemo {
    method1(one :
        ? string) {
        //
    }

    method2(one :
        ? string, two :
        ? number) {
        //
    }

    methodWithReturnedValue(one :
        ? string) :
        ? string {
            //
        }

}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/jaybowong/bd699dc802417ad5ae1284b98273a83a>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Looks like your selected beautifier is `Pretty Diff`. CCing @prettydiff for a comment.

**Comment by prettydiff** [comment]
That is an easy to fix defect from Pretty Diff.  It looks like a ternary, but a ternary would not immediately follow a colon.
