### ISSUE TITLE
windows10 auto save lf --> crlf

### ISSUE THREAD

**Issue by liupeng0518** [Glavin001/atom-beautify#1568]
when I save as beautify ,and the lf change to crlf,
i dont waht this

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
