### ISSUE TITLE
Option `default_beautifier` not respected

### ISSUE THREAD

**Issue by adi518** [Glavin001/atom-beautify#1570]
# Description

Started editing JSX files lately so the package now defaults to Pretty Diff. Strange actually, because `JS Beautify` seems more elaborate/popular. Since a lot of my legacy project was formatted using `JS Beautify` I'm bound to keep using it anyway, so I set `.jsbeautifyrc` with `default_beautifier: JS Beautify`, expecting it'd work.

# Input Before Beautification

This is what the code looked like before:

```
switch (1) {
case 1:
    break;
}
```

# Expected Output

The beautified code should have looked like this:

```
switch (1) {
case 1:
    break;
}
```

# Actual Output

The beautified code actually looked like this:

```
switch (1) {
    case 1:
        break;
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/adi518/310db275bf1270e7d2a0eb39d9b428ed

# Checklist

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
If I recall correctly, `Pretty Diff` beautifier ( @prettydiff ) has better support for JSX than `JS Beautify`, thus the `defaultBeautifier` for `JSX` is set to `Pretty Diff`: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/jsx.coffee#L25

I think you are correct, the `default_beautifier` option is not respected from the configuration files (e.g. `.jsbeautifyrc`). I see it is being extracted from Atom's settings: https://github.com/Glavin001/atom-beautify/blob/604b6340d6a34d13a1b0285cc341da6afeb447d3/src/beautifiers/index.coffee#L137

I will be addressing this bug in future releases with Unibeautify ( #1174 ) which will rely on configuration and not on Atom's settings for `default_beautifier` and more. For now, I recommend you make the change within Atom-Beautify's package settings.
