### ISSUE TITLE
Unable to indent my python code with 4 spaces

### ISSUE THREAD

**Issue by rogaha** [Glavin001/atom-beautify#1574]
# Description

My `python` is not following the indentation configured for python `default=4`. 

![screen shot 2017-03-30 at 9 06 10 am](https://cloud.githubusercontent.com/assets/4483394/24514554/8c8bf32c-1529-11e7-9d0b-d9bd0a3824db.png)

Every time I apply `atom-beautify` it indents the file with `2 spaces`. 

**Config:**
```
  "atom-beautify":
    general:
      analytics: false
    go:
      beautify_on_save: true
    python:
      beautify_on_save: true
      indent_size: 4
    """
```

# Input Before Beautification

This is what the code looked like before:

```
def run():
    """
    Temporary highland collector, it should be deprecated once
    we have kafka in place. It fetches the build requests from
    previous day saves into a CSV file that will be processed
    and pushed to Redshift
    """

    build_requests_data = get_previous_build_request_data()
```

# Expected Output

The beautified code should have looked like this:

```
def run():
    """
    Temporary highland collector, it should be deprecated once
    we have kafka in place. It fetches the build requests from
    previous day saves into a CSV file that will be processed
    and pushed to Redshift
    """

    build_requests_data = get_previous_build_request_data()
```

# Actual Output

The beautified code actually looked like this:

```
def run():
  """
  Temporary highland collector, it should be deprecated once
  we have kafka in place. It fetches the build requests from
  previous day saves into a CSV file that will be processed
  and pushed to Redshift
  """

  build_requests_data = get_previous_build_request_data()
```

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
I see you tried to add a `Config` section above, however we need more information than this 😉  to help you.

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
