### ISSUE TITLE
Having an issue creating an issue

### ISSUE THREAD

**Issue by xn** [Glavin001/atom-beautify#1575]
In trying to get the output from `Help Debug Editor`, I am getting an error.

`An error occurred when creating the Gist: Cannot read property 'path' of null`

**Comment by Glavin001** [comment]
@xn The `Help Debug Editor` feature is very important. Could you try again and see if the problem still occurs? I'd like to make sure this is working. What version of Atom are you using?

The application section of code is: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L471-L484
It looks like a call to `atom.workspace.open()` may be the culprit. Maybe Atom made a breaking change to their API?

**Comment by xn** [comment]
Updated Atom Beautify and was able to generate. Thanks.

**Comment by Glavin001** [comment]
Great!
