### ISSUE TITLE
Markdown - Beautify shouldn't remove double-spaces at the end of the line

### ISSUE THREAD

**Issue by cavo789** [Glavin001/atom-beautify#1581]
# Description

For Markdown file, we can choose to put a "line break" i.e.   `<br>` by putting a double space (or more)
 at the end of the line, see [https://daringfireball.net/projects/markdown/syntax#p](https://daringfireball.net/projects/markdown/syntax#p) for the specification.

# Input Before Beautification

```
a line ending by two spaces  
```

# Expected Output

The beautified code should have looked like this:

```
the line ending by two spaces  
```

This is needed because when we use markdown parser to convert to html, the double-space will be converted into a `<br>`

# Actual Output

Ending spaces are removed which is not correct.

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
