### ISSUE TITLE
Indent Size should respect the indentation specified at the file level

### ISSUE THREAD

**Issue by nemchik** [Glavin001/atom-beautify#1582]
# Description

Each file opened in Atom has an indentation spec down in the bottom right corner of the editor (Note: I may not be using the correct name for that, but it's down there next to your line endings, charset, and language). Beautifiers should respect the indentation type selected here rather than trying to force a predefined indentation based on the beautifier for the language.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

Here are some related issues that would probably be resolved if the requested behavior above were implemented (there may be more, this is just from the most recent two pages of issues):
https://github.com/Glavin001/atom-beautify/issues/1283
https://github.com/Glavin001/atom-beautify/issues/1488
https://github.com/Glavin001/atom-beautify/issues/1422
I do not feel that these other issues are direct duplicates because they are either asking for assistance with settings within atom-beautify or reporting that settings within atom-beautify do not work correctly. My intention with this issue is more of a feature request to have atom-beautify respect individual file's specified indentation preferences.

**Comment by Glavin001** [comment]
Prioritizing configuration is a big pain point right now. My current plan is to allow users to customize the order of configurations before they are merged, such that you could configure Atom editor's settings to override the Atom-Beautify configuration, for example. This will likely be in the Unibeautify release ( #1174 ).

**Comment by nemchik** [comment]
That sounds good! I've read over the information about #1174 and I'm looking forward to seeing it in action!

**Comment by DAGapps** [comment]
Or just use the Tab Length of Atom configuration. (Settings > Editor > Tab Lengrth ; Default = 2 Spaces)
And / Or set the ident level in the "General" region of this plugin. One value for all languages. Not for each languages. That's a bit annoying.
