### ISSUE TITLE
<template> elements not handled properly

### ISSUE THREAD

**Issue by jfletcher-nuxeo** [Glavin001/atom-beautify#1583]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<dom-module id="xxx-yyy">


  <elem-1>
    <elem-2>
      </elem-2>
  </elem-1>

  <template>
    <elem-1>
      </elem-1>
  </template>

  <template>
    <template>
      <template>
      </template>
    </template>
  </template>


</dom-module>
```

# Expected Output

The beautified code should have looked like this:

```
<dom-module id="xxx-yyy">


  <elem-1>
    <elem-2>
    </elem-2>
  </elem-1>

  <template>
    <elem-1>
    </elem-1>
  </template>

  <template>
    <template>
      <template>
      </template>
    </template>
  </template>


</dom-module>
```

# Actual Output

The beautified code actually looked like this:

```
<dom-module id="xxx-yyy">


  <elem-1>
    <elem-2>
    </elem-2>
  </elem-1>

  <template>
    <elem-1>
      </elem-1>
  </template>

  <template>
    <template>
      <template>
      </template>
  </template>
  </template>


</dom-module>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

It still works ok in 0.29.10

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/jfletcher-nuxeo/b9d61cc31f5a40ffa7b77b7b86be5015

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue (similar to #1270 )
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
JS Beautify does not officially support XML or XML-like languages.  In this case I would recommend changing the beautifier to Pretty Diff.

**Comment by Glavin001** [comment]
@jfletcher-nuxeo : In your debugging info it says `Atom Beautify Version: 0.29.17` and you noted above

> It still works ok in 0.29.10

Are you saying this worked before and is now broken? Does reverting back to previous version fix the issue?

Did switching to using Pretty Diff beautifier resolve the issue?

Let me know if there's anything we can do to help.

**Comment by jfletcher-nuxeo** [comment]
@Glavin001 I missed your reply sorry. Yes it works in 0.29.10, that's the version I've reverted too. @prettydiff this is not XML, it's HTML.  Specifically it's HTML using Web components and Google Polymer.

I will try Pretty Diff and report back.

**Comment by jfletcher-nuxeo** [comment]
So @prettydiff Pretty Diff handles the element indentation, but doesn't support attribute wrapping; even worse if I have the attributes on separate lines, it puts them back on one line :(

What I want:

```
    <elem-1 attribute="1"
            attribite-2="2"
            attribite-3="3"></elem-1>
```

What I get:

`    <elem-1 attribute="1" attribite-2="2" attribite-3="3"></elem-1>`

(this is with atom-beautify 0.29.24)

**Comment by prettydiff** [comment]
Looking back at the debug.md settings I see this under the HTML options: `"wrap_line_length": 250,`.  The example in the previous comment is shorter than 250.

I have created a new option called `force_attribute` which always forces the attributes to be indented.  This option is in Pretty Diff 2, which be coming to Atom Beautify very shortly.

**Comment by jfletcher-nuxeo** [comment]
Good to know, thank you!

**Comment by jfletcher-nuxeo** [comment]
Looks like Pretty Diff 2 still isn't in atom, however `force_attribute` *is* in Pretty Diff v1.16.37 (the current dependency). Trying to figure out how to add this option...

**Comment by prettydiff** [comment]
You can try helping out with Pretty Diff 2 integration: https://github.com/Glavin001/atom-beautify/pull/1750

Some of the unit tests are failing and I am not sure why, but it does not appear to be related to Pretty Diff.
