### ISSUE TITLE
Markdown - Getting atom-beautify to leave this untouched

### ISSUE THREAD

**Issue by JetStreamVelocity** [Glavin001/atom-beautify#1584]
# Description

**Background:** I am using the [Jekyll Documentation Theme](https://github.com/tomjohnson1492/documentation-theme-jekyll) for a project. It uses a piece of Markdown for setting up the table of contents on a page.

```
* Table of Contents
{:toc}
```

Need to get atom-beautify plugin to leave it untouched. The beautified code doesn't play well with [Jekyll](https://jekyllrb.com/). Is there a way to tell atom-beautify not to reformat this?

I have played with the settings but cannot get it to work. 

Is this a bug? If not, any workaround?

PS: I am new to Markdown

# Input Before Beautification

This is what the code looked like before:

```
* Table of Contents
{:toc}
```

# Expected Output

The beautified code should have looked like this:

```
* Table of Contents
{:toc}
```

# Actual Output

The beautified code actually looked like this:

Using Tidy-Markdown:
```
- Table of Contents {:toc}
```

Using Remark:
```
-   Table of Contents
    {:toc}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: [Gist Link](https://gist.github.com/JetStreamVelocity/eec80d1daf1d541bec39a1c785148328)

# Checklist

- [X] Atom running on Windows 7 x64

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Looking at your debugging information ( https://gist.github.com/JetStreamVelocity/eec80d1daf1d541bec39a1c785148328#original-file-to-be-beautified ) I see the beautifier used is `Remark`. You could take a look at https://github.com/wooorm/remark to see if someone can help you with your specific issue. You could also try switching to using `Tidy Markdown` beautifier.
