### ISSUE TITLE
PHP increments

### ISSUE THREAD

**Issue by mrpaulphan** [Glavin001/atom-beautify#1592]
# Description
While I working on a php file, I noticed that a line of code changed after doing a code review. When I ran beautify on this page, the plugin converted my Post-increment operator  and changed it to a Pre-increment operator. I specifically used `$i++` intentionally and beautify changed it to `++$i` and broke my logic.  

# Input Before Beautification

This is what the code looked like before:

```
$i++;
```

# Expected Output

The beautified code should have looked like this:

```
$i++;
```

# Actual Output

The beautified code actually looked like this:

```
++$i;
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Please reopen this issue once you have prepared the necessary debug.md file and pasted it into a gist.

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md
