### ISSUE TITLE
Handlebars file detected as Mustache

### ISSUE THREAD

**Issue by KeithClinard** [Glavin001/atom-beautify#1593]
# Description

All `*.hbs` files are being detected as Mustache, and using setting for Mustache instead of Handlebars.  
The root of the problem is that I want to use `Pretty Diff` for Handlebars instead of `JS Beautify`, but it's not one of the supported beautifiers for Mustache.

# Input Before Beautification

```
{{header}}
{{outlet}}
{{footer}}
```

# Expected Output

```
Original File Path: C:\temp\format\app\application\template.hbs

Original File Grammar: Handlebars

Original File Language: Handlebars

Language namespace: handlebars

Supported Beautifiers: JS Beautify, Pretty Diff
```

# Actual Output

```
Original File Path: C:\temp\format\app\application\template.hbs

Original File Grammar: HTML (Mustache)

Original File Language: Mustache

Language namespace: mustache

Supported Beautifiers: JS Beautify
```

# Steps to Reproduce

1. Go to `.hbs` file
2. Run command `Atom Beautify: Beautify Editor`
3. Code is beautified with Mustache settings

# Debug

Here is a link to the `debug.md` Gist: [debug.md](https://gist.github.com/KeithClinard/205155cf010eefd72df0e677874b749d#beautification-options)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
It looks like this can be done by simply modifying this file https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee at around line 50.  Just make the change and submit a pull request!
