### ISSUE TITLE
JS beautification breaks on "break"

### ISSUE THREAD

**Issue by veltman** [Glavin001/atom-beautify#1595]
# Description

Beautifying a JS (`.js` extension) file fails to put a space between a `break` and the preceding statement, causing a syntax error.

**Atom Version**: 1.15.0

**Atom Beautify Version**: 0.29.17

# Input Before Beautification

This is what the code looked like before:

```
var val = "yes";

switch (val) {
    case "yes":
        console.log(val)
        break;
    default:
      console.log("no")
}
```

# Expected Output

The beautified code should have looked like this (with a space before `break`). This is what `js-beautify` produces if I use it directly:

```
var val = "yes";

switch (val) {
    case "yes":
        console.log(val)
        break;
    default:
        console.log("no")
}
```

# Actual Output

The beautified code actually looked like this (note lack of space before `break`):

```
var val = "yes";

switch (val) {
    case "yes":
        console.log(val)break;
    default:
        console.log("no")
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`

# Notes

Putting a semicolon after the statement before the break:

```js
console.log(val);
break;
```

prevents the `break` statement from being moved up.

**Comment by prettydiff** [comment]
The *expected output* example is no different (to the compiler) than the *actual output* example.  That space doesn't make any difference.  A semicolon is absolutely required at that position whether there manually or dynamically inserted via ASI from a line break.

Could you please prepare the debug.md file and paste it into a gist?  That way we have all the debugging information we need before opening an issue with the JSBeautify team.

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by veltman** [comment]
Yes, true - expected output would be to leave the `break` statement below (updated)

**Comment by veltman** [comment]
debug.md: https://gist.github.com/veltman/cf2803559f7b9b992fa2051776603097

**Comment by prettydiff** [comment]
Thanks.

**Comment by prettydiff** [comment]
This is a Pretty Diff defect.  I can reproduce this defect in version 1.16.37, which is the version currently included in Atom.  Pretty Diff pulled out of NPM last year.  An alternate distribution scheme is written and the two final issues are underway right now:

* https://github.com/prettydiff/prettydiff/issues/409
* https://github.com/prettydiff/biddle/issues/34

**Comment by prettydiff** [comment]
Latest Pretty Diff is now in Atom Beautify so closing issue.
