### ISSUE TITLE
Error when beautifying through tree view

### ISSUE THREAD

**Issue by AtomicCoding** [Glavin001/atom-beautify#1597]
# Description
(Works fine when using the packages menu or the command)
When beautifying a CPP file (the only file I have tested) by right-clicking on the file and clicking "beautify file". The atom-beautify returns an error:
/var/folders/gk/vzmxs4mj3_v538q051hfw6r00000gn/T/117315-5722-8fc2i6.mdtaoiggb9.cfg:1 Expected a number for output_tab_size, got undefined /var/folders/gk/vzmxs4mj3_v538q051hfw6r00000gn/T/117315-5722-8fc2i6.mdtaoiggb9.cfg:2 Expected a number for input_tab_size, got undefined Parsing: /var/folders/gk/vzmxs4mj3_v538q051hfw6r00000gn/T/input117315-5722-1sqo2tm.enrfg06bt9 as language CPP
/var/folders/gk/vzmxs4mj3_v538q051hfw6r00000gn/T/117315-5722-8fc2i6.mdtaoiggb9.cfg:1 Expected a number for output_tab_size, got undefined
/var/folders/gk/vzmxs4mj3_v538q051hfw6r00000gn/T/117315-5722-8fc2i6.mdtaoiggb9.cfg:2 Expected a number for input_tab_size, got undefined
Parsing: /var/folders/gk/vzmxs4mj3_v538q051hfw6r00000gn/T/input117315-5722-1sqo2tm.enrfg06bt9 as language CPP

# Input Before Beautification

N/A

# Expected Output

N/A

# Actual Output

N/A

# Steps to Reproduce

1. Create a CPP file. (Only file I've tested it with)
2. Right-Click file in tree view. Click "Beautify File"
3. Atom will return an error.

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/AtomicCoding/79ca1db313d1db0640d87035eb83890a>

# Similar Issue (but issue reports problem always occurs)
Issue: #948 
# Checklist

I have:
- [✓] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [✓] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [✓] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [✓] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [✓] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by AtomicCoding** [comment]
This is still an issue

**Comment by AtomicCoding** [comment]
This is still an issue.

**Comment by AtomicCoding** [comment]
This is still an issue.

**Comment by szeck87** [comment]
@AtomicCoding sorry for taking so long.  I tried this out and I'm not getting an error, and based on the gist you have there's no error there either.  Can you take a screenshot of it if that part is still happening?

**Comment by AtomicCoding** [comment]
No longer an issue. Sorry, I switched to Sublime, so I didn't have much time to test.
