### ISSUE TITLE
Must manually run beautify before reformat on save works

### ISSUE THREAD

**Issue by sgehrman** [Glavin001/atom-beautify#1604]
I expect it to reformat on save, but you have to run beautify once first before it starts working.

**Comment by prettydiff** [comment]
Could you please generate the debug.md file so that we have extra evidence to investigate against?

**Comment by Glavin001** [comment]
We are using Atom's builtin `activationEvents`: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L191-L192

If they are not working for you, I recommend contacting Atom team over at https://github.com/atom/atom 

Also providing the debugging information as @prettydiff would be ideal when you create an issue.

**Comment by Glavin001** [comment]
@sgehrman I just tested and beautification on save works for me.
Note that I was testing `JavaScript` file. Atom initially detected the file as `JSX` so I had to manually change it over to `JavaScript` grammar: https://github.com/atom/grammar-selector
