### ISSUE TITLE
File corruption on beautify

### ISSUE THREAD

**Issue by sgehrman** [Glavin001/atom-beautify#1605]
I keep noticing random junk at the bottom of my files randomly after beautify on save.  These are .vue files if that helps.

**Comment by prettydiff** [comment]
Thanks, this error is due to some integration bug with JSBeautify into Atom-Beautify, but does not seem to be caused by JSBeautify itself.  This is a duplicate issue and we haven't been able to figure it out.

https://github.com/Glavin001/atom-beautify/issues/1213

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
