### ISSUE TITLE
Add option to specify path to clang-format binary (C/C++)

### ISSUE THREAD

**Issue by dkt1412** [Glavin001/atom-beautify#1608]
# Description
I have several different version of clang (because needs) and thus also different versions of clang-format (most notably the chromium version vs the standard clang).  I'd like to be able to specify which version to use, so having an option in settings to do so would be great.

**Comment by prettydiff** [comment]
Do the files have different file extensions?

**Comment by dkt1412** [comment]
No, the file extensions are all cpp and h (C++).  I've got different C++ projects that requires different clang-format (owned by different teams), so it'd be useful to be able to switch when I switch projects (even if it means doing so by inputting the path manually each time I switch).
