### ISSUE TITLE
Support for Lua

### ISSUE THREAD

**Issue by dtruel** [Glavin001/atom-beautify#161]
Hello, any chance you will be adding lua as a supported language?

**Comment by Stanzilla** [comment]
Want! :)

**Comment by xcgasparxc** [comment]
Want! :D

**Comment by chkuendig** [comment]
see also https://github.com/mingjunyang/atom-format-lua

**Comment by Glavin001** [comment]
Please provide your feedback on these beautifiers and post links to others to try here.
Once a third-party beautifier/formatter has been found, then we can add support to Atom Beautify.

Let me know if [atom-format-lua](https://github.com/mingjunyang/atom-format-lua) is working for you.
Also take a look at:
- https://github.com/LuaDist/luapretty
- http://notebook.kulchenko.com/programming/lua-beautifier-in-55-lines-of-perl
- http://lua-users.org/wiki/SourceCodeFormatter
and any others you can find.

**Comment by wulei** [comment]
Want! :D

**Comment by C-Bouthoorn** [comment]
Let's join everyone here: Want! :smiley: 

Sidenote: atom-format-lua just removes all my code :disappointed:

**Comment by mazrabul** [comment]
my +1 pretty please.

**Comment by prettydiff** [comment]
@mazrabul Would you mind playing around with the beautifiers at https://github.com/Glavin001/atom-beautify/issues/161#issuecomment-135607812 and letting us know the pros and cons for each.  We are not Lua developers, so we don't know what to look for.

**Comment by JoostvDoorn** [comment]
http://lua-users.org/wiki/SourceCodeFormatter does not do what's desired here.

http://notebook.kulchenko.com/programming/lua-beautifier-in-55-lines-of-perl seems to work well.
