### ISSUE TITLE
Lua Beautifier replaces CRLF with LF

### ISSUE THREAD

**Issue by Nexela** [Glavin001/atom-beautify#1613]
# Description

CRLF is replaced with LF file endings after beautifying,   
Tested with Markdown and LUA beautifiers and they are both affected.
Tested with JS and it was not affected

Tested with Line ending package settings to both system and CRLF

# Input Before Beautification

File has CRLF endings

# Expected Output

File keeps same line endings 

# Actual Output

File has LF endings

# Steps to Reproduce

Open an lua file with CRLF line endings
Beutify

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/8ce276ad58d4ede7736c292ac973b0ae

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
@Nexela in the future please make the Gist with extension `.md`. I have done so here: https://gist.github.com/Glavin001/e24eeab0afa5e661579fdd21279c3ba6
Thanks! 😜 

---

Looks like the `EOL` option is not supported by the current Lua beautifier:
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/lua-beautifier/index.coffee
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/lua-beautifier/beautifier.coffee

Pull Requests welcome!

**Comment by hxsf** [comment]
@Glavin001 I add some code in #1625 about get the eol, but just get the editor option or system default EOL.
So, how can i get the current file's EOL?
