### ISSUE TITLE
Change the color for 'css comments' or any comments, if easily done, from Black to Green

### ISSUE THREAD

**Issue by jfkirkpatrick** [Glavin001/atom-beautify#1615]
# Description

I am embarrassed to ask this as an issue but I could not find where I could change the config file.

I am using UI Theme of 'Atom Dark' and the Syntax Theme of 'Atom Material Dark'.  I love the colors being displayed but the comments are Black and are not readable against the Black background.

If you can point me in the right direction, I will make the change.

Love your Package and it makes coding so much easier.

John

**Comment by Glavin001** [comment]
Hi John,

Could you help me understand your issue a little more?

> I am using UI Theme of 'Atom Dark' and the Syntax Theme of 'Atom Material Dark'. I love the colors being displayed but the comments are Black and are not readable against the Black background.

Would these two packages be more appropriate place to ask?
- https://github.com/atom/atom-dark-ui
- https://github.com/atom-material/atom-material-ui

> If you can point me in the right direction, I will make the change.

Open the Atom command palette and search for `Application: Open Your Stylesheet`:

![image](https://cloud.githubusercontent.com/assets/1885333/25255529/8226192e-2601-11e7-8325-810ae173598a.png)

![image](https://cloud.githubusercontent.com/assets/1885333/25255557/a17fd26a-2601-11e7-85bb-ca2cd52ef655.png)

Add the following code and save:

```
atom-text-editor .syntax--comment {
    color: green;
}
```

![image](https://cloud.githubusercontent.com/assets/1885333/25255572/b7c589a2-2601-11e7-9cdb-c7792feb5261.png)

As you can see the comments at the top are now green ✅.

I hope this helps!

**Comment by jfkirkpatrick** [comment]
Thank you
