### ISSUE TITLE
.liquid (HTML) is not working (Shopify liquid)

### ISSUE THREAD

**Issue by hszili76** [Glavin001/atom-beautify#1619]
I got this Error:
Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "HTML (Liquid)" and extension "liquid". If you would like to request support for this file and its language

What should I do to be able to use it?

**Comment by Glavin001** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/393
