### ISSUE TITLE
Combination of parenthese and curly bracket breaking indentation with lua

### ISSUE THREAD

**Issue by Zod-** [Glavin001/atom-beautify#1622]
# Description

In Lua files there is a bug which breaks indentation of the whole file after a specific combination of parentheses and curly brackets since `0.29.18`:
```lua
}
)
```
With each occurrence of this combination, the indentation level is reduced by one.

# Input Before Beautification

This is what the code looked like before:

```lua
print({
    a = 1
  }
)

local foo = {
  b = {
    c = 2
  }
}

print({
    a = 1
  }
)

local bar = {
  b = {
    c = 2
  }
}
```

# Expected Output

The beautified code should have looked like this:

```lua
print({
  a = 1
}
)

local foo = {
  b = {
    c = 2
  }
}

print({
  a = 1
}
)

local bar = {
  b = {
    c = 2
  }
}
```

# Actual Output

The beautified code actually looked like this:

```lua
print({
  a = 1
}
)

local foo = {
b = {
  c = 2
}
}

print({
a = 1
}
)

local bar = {
b = {
c = 2
}
}
```

# Steps to Reproduce

1. Add code that has a parenthese and a curly bracket after each other with their own lines.
2. Run command `Atom Beautify: Beautify Editor`
3. For each combination there will be one less indentation level below it.

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/Zod-/267629834e31c605c4f9c5175d372e2b

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Zod-** [comment]
This has not been fixed yet.

**Comment by szeck87** [comment]
@hxsf do you have any insight on this?

**Comment by Zod-** [comment]
Can you just reverse the lua beautifier if nobody is going to fix it. 

Similiar issue #1790

**Comment by hxsf** [comment]
Sorry to reply you so long
But this format tool not add / remove '\n' in your code.

so, it cannot format the
```
fn({
        a = 2
    }
)
```

to 

neither

```
fn(
    {
        a = 2
    }
)
```
nor 
```
fn({
    a = 2
})
```

**Comment by Zod-** [comment]
This issue is not about line breaks. 

The indentation is completely broken for the whole file in the case shown above and also in the case shown in #1790. I do not want it to remove or add \n. I want it to not mess up the whole file when I use brackets.
