### ISSUE TITLE
JavaScript beautification issue

### ISSUE THREAD

**Issue by InfosystaMobileTeam** [Glavin001/atom-beautify#1623]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
switch (event.mode) {
    case PushClient.MODE_FOREGROUND: //Android
    case 1: //iOS
        if (OS_ANDROID) {
            PushClient.showLocalNotification(event.data);
        } else {
            openNotification(event);
        }
        break;
    case PushClient.MODE_CLICK: //Android
    case 2: //iOS
        openNotification(event);
        break;
    default:
}
```

# Expected Output

The beautified code should have looked like this:

```
switch (event.mode) {
    case PushClient.MODE_FOREGROUND: //Android
    case 1: //iOS
        if (OS_ANDROID) {
            PushClient.showLocalNotification(event.data);
        } else {
            openNotification(event);
        }
        break;
    case PushClient.MODE_CLICK: //Android
    case 2: //iOS
        openNotification(event);
        break;
    default:
}
```

# Actual Output

The beautified code actually looked like this:

```
switch (event.mode) {
case PushClient.MODE_FOREGROUND: //Android
case 1: //iOS
    if (OS_ANDROID) {
        PushClient.showLocalNotification(event.data);
    } else {
        openNotification(event);
    }
    break;
case PushClient.MODE_CLICK: //Android
case 2: //iOS
    openNotification(event);
    break;
default:
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Would you mind producing the debug.md file and pasting that into a gist?  This is likely due to an option setting, but I need to know some details before I can troubleshoot.  Once the debug.md file is ready add to this issue and reopen.

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md
