### ISSUE TITLE
LUA Beautifier formatting issues

### ISSUE THREAD

**Issue by Nexela** [Glavin001/atom-beautify#1627]
# Description
@hxsf 
Lua Beautifier formating issues
using the lua beautifier from https://github.com/hxsf/atom-beautify/tree/master/src/beautifiers/lua-beautifier for testing
Apologies for the lack of debug.md

Using your Eol fixed beautifier I still got many beautifying issues  Mainly around comments and special chars in strings.

Here is the file I used to test. It is formatted correctly (4 space indentation)
[control.lua](https://gist.github.com/5b45d5f93eccd1ffd7d4a81f0da22ab0)

This file formats correctly in 0.29.17

Most of the formatting issue seem to be related to block comments:
If I remove all of the block comments and replace them with line comments it formats slightly better

Additionally after removing block comments
line 275 (before removing comments)
`gui.caption = inventory_count .. (vehicle_count and (" ("..vehicle_count..")") or "")`
Causes everything after it to be off by 1 indentation level

Indentation also fails after Gui.on_click("picker_rename_button", function(event)
If I move the function(event) to its own line below it will keep beautifying until it hits the next snafu

Debug MD could not be created. However these are all just formatting issues on lua-beautifier #1625 

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by hxsf** [comment]
Thank you for your test. 👍 
There are still some issues about block comment.
I will check it. 😄
