### ISSUE TITLE
Support for swift

### ISSUE THREAD

**Issue by Austinthemighty** [Glavin001/atom-beautify#1629]
can you add support for swift please

**Comment by prettydiff** [comment]
Marking as duplicate of https://github.com/Glavin001/atom-beautify/issues/675

**Comment by Glavin001** [comment]
@issue-manager duplicates test

**Comment by Glavin001** [comment]
@issue-manager duplicates test

**Comment by Glavin001** [comment]
@issue-manager duplicates test

**Comment by Glavin001** [comment]
@issue-manager duplicates test

**Comment by Glavin001** [comment]
@issue-manager duplicates test

**Comment by Glavin001** [comment]
@issue-manager duplicates test
