### ISSUE TITLE
"HTML Wrap Line Length" parameter does nothing

### ISSUE THREAD

**Issue by soygul** [Glavin001/atom-beautify#163]
Seems like this value is not passed to `js-beautify` properly.

**Comment by Glavin001** [comment]
This was merged in about 18 days ago :+1:

**Comment by Glavin001** [comment]
Update `js-beautify` to `1.5.5`.

**Comment by Glavin001** [comment]
This was already done in https://github.com/Glavin001/atom-beautify/pull/228

**Comment by malkomich** [comment]
I guess the 'Wrap line length' setting should work fine if this issue is closed, but it does not seem to work.
Is this near to be fixed? Or maybe I can try it out

**Comment by prettydiff** [comment]
@malkomich Which code language are you using?

**Comment by malkomich** [comment]
I'm using HTML.
I put the line length to 120, but the wrapping is not properly working and some lines keeps longer.

**Comment by prettydiff** [comment]
@malkomich Would you mind generating a debug.md file and pasting it into a gist?  This way I can see your sample, beautifier, options, and so forth so that I can reproduce the problem.

**Comment by malkomich** [comment]
Here it is :smile:  
https://gist.github.com/malkomich/e5a6c23e21417c5a1c30905cca58c57d

**Comment by prettydiff** [comment]
Thanks for that.  It appears the language is HTML, the beautifier is JS Beautify, and that JS Beautify does support text wrapping to a specified length as tested on their web tool.
