### ISSUE TITLE
Update CSSComb to Latest Version

### ISSUE THREAD

**Issue by thejamespower** [Glavin001/atom-beautify#1630]
Do we have any update on when CSSComb will be updated to the latest version?

**Comment by kinkwilde** [comment]
It will be nice when the pull request gets accepted because it means I can sort my includes by name. Currently this isn't supported, but is supported in the latest version of csscomb, csscomb is now at 4.1.0 so is it worth updating to that instead of 4.0.1 that the pull request is trying to do?

**Comment by thejamespower** [comment]
>4.0 CSSComb also uses an updated version of Gonzales, which has numerous bug fixes. 4.0.1 was the latest version I think when I made the PR, but I will look at bumping it further if I get a sec' this week!

**Comment by Glavin001** [comment]
https://github.com/Glavin001/atom-beautify/pull/1660 has been merged.

Published to v0.29.26
