### ISSUE TITLE
not beautify

### ISSUE THREAD

**Issue by acecx** [Glavin001/atom-beautify#1637]
<button type="button" class="navbar-toggle
     collapsed" data-target="#site-navbar-collapse"
    data-toggle="collapse">
    <i class="icon wb-more-horizontal" aria-hidden="true"></i>
  </button>

**Comment by prettydiff** [comment]
Please generate the debug.md file and paste it into a gist.  At that point we will have the details necessary to troubleshoot this concern:

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

Once the debug.md file is available please reopen this issue.
