### ISSUE TITLE
Update typescript-formatter

### ISSUE THREAD

**Issue by epelc** [Glavin001/atom-beautify#1638]
# Description

The latest version of `typescript-formatter` is 5.1.3 but atom-beautify is using 2.3.0. This causes issues if you try to run `tsfmt` on a project that also uses atom-beautify(ie subtle differences).

See the changelog for differences https://github.com/vvakame/typescript-formatter/blob/master/CHANGELOG.md

**Comment by Vic-Dev** [comment]
Yes please update

**Comment by effervescentia** [comment]
Please update this, we rely heavily on typescript and atom for development

**Comment by Glavin001** [comment]
A Pull Request is how this is going to get done. I just received one 3 hours ago: https://github.com/Glavin001/atom-beautify/pull/1740
It is currently failing to pass TypeScript tests. Once it works as expected, I can merge and publish.

**Comment by Glavin001** [comment]
Published to v0.30.6
