### ISSUE TITLE
Force hardcoded paths to CLI beautifiers

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#164]
There have been many problems with the `$PATH` and using https://github.com/Glavin001/atom-beautify/blob/master/lib/langs/cli-beautify.coffee#L37-L42 to automatically fix the `$PATH`. This is not working out.

- [x] Remove https://github.com/Glavin001/atom-beautify/blob/e59d7c33a6458418915a2a4d0deef38d5ed78c83/lib/langs/cli-beautify.coffee#L45-L50 and force CLI beautifiers to have hardcoded paths in config
- [x] Use https://github.com/Glavin001/atom-beautify/blob/e59d7c33a6458418915a2a4d0deef38d5ed78c83/lib/langs/cli-beautify.coffee#L45-L50 code to *suggest* if the beautifier's path is current empty
- [x] Change `$PATH` (for auto-detecting paths of CLI beautifiers)

**Comment by Glavin001** [comment]
Use `which` command in Mac and Linux to determine executable file's path.
Use `where.exe` for Windows: http://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

**Comment by Glavin001** [comment]
Ended up using code from `script-runner` by @ioquatix: https://github.com/ioquatix/script-runner/blob/v1.5.0/lib/script-runner.coffee#L45-L63
This will auto-detect all shell environment variables, including PATH. This means we can get rid of the hardcoded CLI executable paths entirely!

**Comment by ioquatix** [comment]
Be careful with that code it's a bit unstable.. not like, in that it doesn't work.. just that it's hard to guarantee it works cross platform. Interactive login shells sometimes do weird things, like print out headers, etc. We changed it a couple of times to try and get the correct cross platform behaviour, it's working well at the moment, but if you depend on it perhaps it should be a separate npm package so it can be updated independently.

**Comment by ioquatix** [comment]
Okay, so you've motivated me to try making my first npm module.. with this code.

https://github.com/ioquatix/login-environment

@Glavin001 I've added you as a collaborator so feel free to make any changes. Then once it is good and makes sense, we can release a 1.0.0 release and that way any improvements to the code would be shared between both this project and `script-runner`.
