### ISSUE TITLE
phpcbf 3.0 returns ERROR: option "--no-patch" not known

### ISSUE THREAD

**Issue by UziTech** [Glavin001/atom-beautify#1643]
The `--no-patch` option has been removed in [phpcbf 3.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0a1)

There should be some way of determining which version of phpcbf the user is using like [linter-phpcs](https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.js#L26) or a config setting like the [PHP-CS-Fixer Version](https://github.com/Glavin001/atom-beautify/blob/master/src/languages/php.coffee#L30) setting

**Comment by Glavin001** [comment]
https://github.com/Glavin001/atom-beautify/issues/1645 merged.

**Comment by Glavin001** [comment]
Published to v0.29.24
