### ISSUE TITLE
'atom-beautify.yaml.padding' could not set the default

### ISSUE THREAD

**Issue by jeffs** [Glavin001/atom-beautify#1647]
# Description

I see odd errors related to atom-beautify in the dev console:

```
'atom-beautify.yaml.padding' could not set the default. Attempted default: undefined; Schema: {"type":"integer","default":null,"minimum":0,"description":"The amount of padding to add next to each line. (Supported by align-yaml)","title":"Padding","beautifiers":["align-yaml"],"key":"padding","language":{"name":"YAML","namespace":"yaml"}}
```

These errors are reported even when YAML is disabled in the atom-beautify package settings.  Opening a YAML file does not trigger them, but merely opening Settings/Packages does.  In fact, immediately upon installation of atom-beautify, the error is reported twice.

# Steps to Reproduce

1. Open Atom.
2. Open Settings.
3. Select Packages.
4. Look at the console.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [NA] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
  * Not applicable.  No editor is open; only Workspace and Settings.  Help Debug Editor duly reports: "Active Editor not found.  Please select a Text Editor first to beautify."

**Comment by Glavin001** [comment]
I am noticing this, too. It is a bug.

The issue is the default value is `null` for `padding`: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/yaml.coffee#L28

I suppose it should be default value of `0`.

Pull requests welcome!

**Comment by jeffs** [comment]
Thanks!  PR: https://github.com/Glavin001/atom-beautify/pull/1648
