### ISSUE TITLE
No space after anonymous async in js

### ISSUE THREAD

**Issue by TwoAbove** [Glavin001/atom-beautify#1654]
# Description
Hey! I hope you're having a good day.

The results of beautification are not what I expect.

Anonymous async function (`async () => {}`) should have a space after `async`.

Might I have missed something?

`async function () {}` works as intended

# Input Before Beautification

This is what the code looked like before:

```javascript
routes.get('/', async(req, res) => {
  res.status(200).json({ message: 'Connected!', apiVersion: 1 });
});
```

# Expected Output

The beautified code should have looked like this:

```javascript
routes.get('/', async (req, res) => {
  res.status(200).json({ message: 'Connected!', apiVersion: 1 });
});
```

# Actual Output

The beautified code actually looked like this:

```javascript
routes.get('/', async(req, res) => {
  res.status(200).json({ message: 'Connected!', apiVersion: 1 });
});
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/TwoAbove/d262f8c3e347c5beeaff7a9613779775

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by TwoAbove** [comment]
Hey! The linked issue is closed, can you update the project?
