### ISSUE TITLE
[Vue Beautifier] Add option to let it indent first child in .vue files' <template> section

### ISSUE THREAD

**Issue by lbssousa** [Glavin001/atom-beautify#1659]
I'm working on a Vue.js project with some coworkers, where some of us use Atom (with atom-beautify package) and the other ones use Visual Studio Code (with Vetur extension). I'm trying to fit my project's extensions/settings so that I can get the same formatting rules for both editors, but I simply can't make them indent `<template>` sections the same way. VSCode/Vetur treats this section as an ordinary HTML code, indenting it as usual:

```
<template>
  <div> <-- indented as usual
    (...)
  </div>
</template>
```

On the oher hand, atom-beautify seems to treat the very first `<template>` tag in .vue files specially, not indenting its first child:

```
<template>
<div> <-- NOT indented
  (...) <-- indented as usual
</div>
</template>
```

Would it be possible to add an option to Vue Beautifier allowing it to indent `<template>`'s first child as the first example above shows, so that I can format code consistently in either Atom or VSCode?

By the way, I've just opened another issue for the converse behaviour in VSCode: https://github.com/octref/vetur/issues/198

**Comment by lqzhgood** [comment]
I think `<template>` 、`<script>` 、'<style>'  should add option to indent first child.
and extra newline before them

**Comment by amandamcg** [comment]
This would also help with the issue that Atom only allows you to fold indented code. 

Atom folding will work as expected if there is a leading indent...
```
<template lang="pug" >
    .main-section
        p Lorem Ipsum
</template>
```
collapses, as expected, to
```
<template lang="pug" >
</template>
```
But atom-beautify removes that indent.

The output after code has been "beautified". Atom will not recognize the template tag as an indent point
```
<template lang="pug" >
.main-section
    p Lorem Ipsum
</template>
```

**Comment by lan3jur** [comment]
I'm still experiencing this issue ...

**Comment by Ten-Taken** [comment]
Having this problem currently. Found no setting to indent first child.

**Comment by robitn** [comment]
Still experiencing this issue as well. Would love to have this option.

**Comment by weswinder** [comment]
This is something I would also be interested in seeing.

**Comment by mOewa** [comment]
Having this problem, no settings to indent first child.

**Comment by jianmoz** [comment]
Having this problem as well, sad.
