### ISSUE TITLE
Out of no where not indenting correctly

### ISSUE THREAD

**Issue by ErraticFox** [Glavin001/atom-beautify#1662]
Hello, I've been using Atom Beautify for the last couple months and I love it. Though just now, out of no where it stopped working correctly. I was working on a project and I usually use my hotkey for it every time I save, even though there's a feature for that. Though I just made a change on my project, which I've been working on for the last two hours then all of a sudden, my beautify is still beautifying, just not how it usually does it. It usually does two tabs (not spaces) and then I came back, made a change, did it again and bam. Everything shifted to one tab. I updated beautify recently, but that was last night and this didn't start  happening till just now. Checked my general settings and it's set to "hard" two tabs. I couldn't find the Beautify config though. I'm on Windows 10.

**Comment by RenaKunisaki** [comment]
I think I'm having the same issue. Just installed the package and it's adding extra indents to my C code, eg: (with tab size set to 4):

```C
void debug_main_init() {
        //Called at boot once our code is loaded into RAM.

        //patch display list debug to show in corner of screen.
        //these addresses are part of the instructions that set the text position.
        u32 xpos[] = {0xA00016FA, 0xA00016CE, 0xA0001662, 0xA0001726, 0xA0001732};
        u32 ypos[] = {0xA0001706, 0xA00016DA, 0xA00016B2, 0xA0001752, 0xA0001736};
        for(int i=0; i<5; i++) {
                *(u16*)(xpos[i]) =   0;
                *(u16*)(ypos[i]) = 205;
        }

        //enable title screen debug menu by default
        // *(u16*)0xA00B3F76 = 2;

        screenMode = 0; //not sure why it keeps defaulting to 2p
        numPlayers = 1;
}
```

Every brace level is indented by two tabs instead of one. Uncrustify itself seems to generate the correct output though.
