### ISSUE TITLE
PHP Beautification not working for PHP-CS-Fixer

### ISSUE THREAD

**Issue by asafm7** [Glavin001/atom-beautify#1663]
# Description

I set the paths to the executables but when I click for beautification "Beautification in Progress" message shows for sec and then nothing happens. No errors are shown (using Windows).

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/asafm7/2348641507843ab1113ce19501f51e85

**Comment by asafm7** [comment]
Thanks, I think i tried everything.

I get no errors but no results. 

Actually the only thing that **does** happen is an empty line added in the end of the file...

It seems like everything is running but no roles applied...

Is there anything else I can do?

Thanks,

Asaf

**Comment by Glavin001** [comment]
@issue-manager duplicates?

**Comment by Glavin001** [comment]
Please rename your Gist to `debug.md` not `debug,md` (note the period instead of comma) 😛. This will allow us to use the Markdown links.

In the logs I see the following:

```
2017-05-14T10:51:10.299Z - debug: [beautifiers\beautifier.coffee] spawn C:\php\php.EXE 0=C:\xampp-5.6.30\php\php-cs-fixer, 1=fix, 2=--allow-risky=no, 3=--using-cache=no, 4=C:\Users\asafm\AppData\Local\Temp\temp117414-5980-32bpg0.hvzfqadcxr
2017-05-14T10:51:10.460Z - debug: [beautifiers\beautifier.coffee] spawn done 1  Could not open input file: C:\xampp-5.6.30\php\php-cs-fixer

2017-05-14T10:51:10.461Z - verbose: [beautifiers\beautifier.coffee] spawn result 1 Could not open input file: C:\xampp-5.6.30\php\php-cs-fixer
```

Can you confirm `C:\xampp-5.6.30\php\php-cs-fixer` is:
1) the correct path (i.e. exists)
2) a PHP file

**Comment by asafm7** [comment]
Hi,

Here is a new debug file:
https://gist.github.com/asafm7/c0c1a6c41c73684a108cc9d96aab16d5

The path to the `php-cs-fixer` is:
C:\Users\asafm\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.phar

Thanks again,
Asaf

**Comment by Glavin001** [comment]
I see in your new debug file you have changed the configured `php-cs-fixer` path: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php-cs-fixer-path

In the logs it shows:

```
2017-05-15T06:36:51.581Z - debug: [beautifiers\beautifier.coffee] spawn C:\php\php.EXE 0=C:\Users\asafm\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.phar, 1=fix, 2=--allow-risky=no, 3=--using-cache=no, 4=C:\Users\asafm\AppData\Local\Temp\temp117415-6564-1mvn53.50fuyds4i
2017-05-15T06:36:52.335Z - debug: [beautifiers\beautifier.coffee] spawn done 0 Loaded config default.
 
Fixed all files in 0.259 seconds, 5.250 MB memory used

2017-05-15T06:36:52.336Z - verbose: [beautifiers\beautifier.coffee] spawn result 0 
Fixed all files in 0.259 seconds, 5.250 MB memory used
 Loaded config default.
```

It appears to be working as expected now, from Atom-Beautify's perspective, as the message shown -- `Fixed all files in 0.259 seconds, 5.250 MB memory used
` -- is generated by PHP-CS-Fixer.

However, it looks like the indentation is still off. This would suggest an issue with PHP-CS-Fixer's handling of your file. Have you tried using `PHP-CS-Fixer` manually via CLI? See https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage for details.

**Comment by asafm7** [comment]
I did. It outputs:

```
$ php php-cs-fixer.phar fix test.php
Loaded config default.

Fixed all files in 0.251 seconds, 5.250 MB memory used
```

But again, no beautification is taking place...

Any ideas?

Does all beautification rules are within the `php-cs-fixer.phar`? Can you send me a `php-cs-fixer.phar` file known to work?

**Comment by Glavin001** [comment]
> But again, no beautification is taking place...

Then this must be a bug with PHP-CS-Fixer itself. I recommend you create an issue over at https://github.com/FriendsOfPHP/PHP-CS-Fixer to ask for help.

**Comment by odahcam** [comment]
When I run: `php-cs-fixer fix <filepath>.php` on any CLI in my Windows, everything works fine, but inside Atom, using atom-beautify, nothing happens.

**Comment by tommykamkcm** [comment]
Hello, I just did a test and the result was same as @odahcam 's observation. It would be good if you can check again. Thank you so much!

**Comment by Orsokuma** [comment]
Win10x64.
The fix for me was to simply rename the downloaded `php-cs-fixer` to `php-cs-fixer.phar` and update the path in Atom accordingly.
