### ISSUE TITLE
LESS Convert quotes none(default) doesn't work 

### ISSUE THREAD

**Issue by sl2782087** [Glavin001/atom-beautify#1664]
When I select Convert quotes "none" all my quotes converts to double quotes.
That's make some error like this.

![image](https://cloud.githubusercontent.com/assets/18182914/26040823/fd363b32-395a-11e7-88a4-98a6e6b474c2.png)

**Comment by prettydiff** [comment]
This is likely a Pretty Diff defect, but I would like to be sure.  Would you be able to create the debug.md file and paste it into a gist?

https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by sl2782087** [comment]
https://gist.github.com/8706cf9dfb219a5c47bba486579d6251.git

**Comment by prettydiff** [comment]
I can reproduce this defect in Pretty Diff v1.16.37, which is the version currently included with Atom Beautify.  In the current version of Pretty Diff, v2.2.0, I cannot reproduce this defect.  I am working on getting the latest version of Pretty Diff into Atom Beautify.  I have this problem solved from the Pretty Diff side, and now I need to work on extending Atom Beautify with the new distribution logic.  For updates please watch https://github.com/Glavin001/atom-beautify/issues/881
