### ISSUE TITLE
Beautify indent guides not working after atom 1.17 update

### ISSUE THREAD

**Issue by dileeparanawake** [Glavin001/atom-beautify#1665]
After installing atom 1.17 code doesn't seem to be beautified - I've lost all my indent guides
<img width="749" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/28249421/26126845/08f162a6-3a7f-11e7-8868-ed7dd207437a.png">

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by dileeparanawake** [comment]
Slight change the indent guides have come back - no idea how this happened. I received a prompt saying something along the lines of needed uncrustify so I installed via homebrew.

I'm new to coding, atom etc so I've filled in the below best I can. Worth mentioning that the initial issue seems to be solved (not sure what I did to make this happen).

I do get an error if I try to beautify code manually - error below. Can close issue if needed. 

Thanks for the support

# Description

The results of beautification are not what I expect - indent guides didn't appear, but now seem to be working.

# Input Before Beautification

This is what the code looked like before:

#include<iostream>
#include<string>
#include <vector>
#include <algorithm>
#include <cmath>
using namespace std;
inline void keep_window_open() {char ch; cin>>ch;}

int main () // c++ progams start by excuting the funciton main.
{
  cout <<"Hello, World!\nHere we go!\n";
  keep_window_open(); // wait for a charachter to be entered
  return 0;
}

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

photo attached in the comment above (no indent guides were present at the time of writing)

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

error when I click beautify:


age_input.cpp
hello_world.cpp
operators.cpp
untitled
 1
 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15

#include<iostream>
#include<string>
#include <vector>
#include <algorithm>
#include <cmath>
using namespace std;
inline void keep_window_open() {char ch; cin>>ch;}
 
int main () // c++ progams start by excuting the funciton main.
{
  cout <<"Hello, World!\nHere we go!\n";
  keep_window_open(); // wait for a charachter to be entered
  return 0;
}
 
Project
3 deprecations
/var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/117416-37503-1fayano.xyt10dx6r.cfg:1 Expected a number for output_tab_size, got undefined /var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/117416-37503-1fayano.xyt10dx6r.cfg:2 Expected a number for input_tab_size, got undefined Parsing: /var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/input117416-37503-vjz3og.wle9l4bo6r as language CPP
/var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/117416-37503-1fayano.xyt10dx6r.cfg:1 Expected a number for output_tab_size, got undefined
/var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/117416-37503-1fayano.xyt10dx6r.cfg:2 Expected a number for input_tab_size, got undefined
Parsing: /var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/input117416-37503-vjz3og.wle9l4bo6r as language CPP
Hide Stack Trace
Error: /var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/117416-37503-1fayano.xyt10dx6r.cfg:1 Expected a number for output_tab_size, got undefined
/var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/117416-37503-1fayano.xyt10dx6r.cfg:2 Expected a number for input_tab_size, got undefined
Parsing: /var/folders/vd/nm8rhrx90m30xcq9xnjbyngw0000gn/T/input117416-37503-vjz3og.wle9l4bo6r as language CPP
    at /Users/Dee/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:322:27
    at tryCatcher (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/Dee/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

# Checklist

I have:
- [ y] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [y ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ y] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [- ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [- ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by dileeparanawake** [comment]
The original issue seems to 'have fixed itself' as in the comments above however a second issue seems to have emerged (also in comments above).
