### ISSUE TITLE
Atom beautify introduces syntax error

### ISSUE THREAD

**Issue by vanng822** [Glavin001/atom-beautify#1669]
# Description

Beautification losing code which causing syntax error. I am using atom-beautify 0.29.23

# Input Before Beautification

This is what the code looked like before:

```
const wWidth = document.body.offsetWidth;
const style = {
      weekHeader: {
        width: wWidth*7+8
      }
  };
export default style;
```

# Expected Output

The beautified code should have looked like this:

```
const wWidth = document.body.offsetWidth;
const style = {
    weekHeader: {
        width: wWidth*7 + 8
    }
};
export default style;
```

# Actual Output

The beautified code actually looked like this:

```
const wWidth = document.body.offsetWidth;
const style = {
    weekHeader: {
        width: *7 + 8
    }
};
export default style;

```
We are loosing variable wWidth

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the debug.md Gist: https://gist.github.com/vanng822/90d5088ac55baab8a9aac682af584772

**Comment by prettydiff** [comment]
I opened an issue on this.

**Comment by vanng822** [comment]
Thank you @prettydiff

**Comment by prettydiff** [comment]
Yep, I am trying to get the latest version of Pretty Diff into Atom Beautify today.
