### ISSUE TITLE
vue file less format issue

### ISSUE THREAD

**Issue by weifeiyue** [Glavin001/atom-beautify#1677]
# Description

vue file less format issue

# Input Before Beautification

This is what the code looked like before:

```
<style lang="less">
.demo {
  font-size: 14px;
}
</style>
```

# Expected Output

The beautified code should have looked like this:

```
<style lang="less">
.demo {
  font-size: 14px;
}
</style>
```

# Actual Output

The beautified code actually looked like this(extra 2 space):

```
<style lang="less">
.demo {
    font-size: 14px;
}
</style>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by no1xsyzy** [comment]
I have the same problem with `lang="scss"`
