### ISSUE TITLE
Extra space before `:host` selector

### ISSUE THREAD

**Issue by jarrodek** [Glavin001/atom-beautify#1680]
# Description

When the selector is a `:host{}` selector, the `atom-beauty` adds extra space before the declaration.

# Input Before Beautification

This is what the code looked like before:

```
<style>
:host {
      outline: none;
      display: block;
    }
</style>
```

# Expected Output

The beautified code should have looked like this:

```
<style>
:host {
  outline: none;
  display: block;
}
</style>
```

# Actual Output

The beautified code actually looked like this:

```
<style>
 :host {
  outline: none;
  display: block;
}
</style>
```
Notice extra space before `:host`.

The `<style>` is a part of the `<template>` element inside HTML content. It is used to register a web component. Because of this it cannot be in separate CSS file. But I've checked that the same thing is happening in CSS file.

**Comment by prettydiff** [comment]
You are probably using Pretty Diff as your beautifier.  This has already been reported as a defect and the defect is resolved in a later version of Pretty Diff.  I am trying to get the latest version of Pretty Diff into Atom Beautify without NPM.... as I no longer update to NPM.

Here is the current activity: https://github.com/Glavin001/atom-beautify/pull/1672

I was having trouble figuring out why the tests were failing.  Once I can get the tests passing I can recommend Glavin merge the pull request and this issue is resolved.

**Comment by jarrodek** [comment]
I'm not using Pretty Diff. The only package related to beautifying is this package.

**Comment by prettydiff** [comment]
Atom Beautify is a shell of beautifiers for various languages.  Pretty Diff is the default beautifier for LESS and SCSS formats.  You can be sure by running the Atom Beautify's debug function and reading the output.

**Comment by jarrodek** [comment]
Debug output: https://gist.github.com/jarrodek/f938635e04c3d83a40231e3fd9185d34
I don't know how to read this but I think it says that it uses `JS Beautify` for CSS.

**Comment by prettydiff** [comment]
Yeah, then it is a JS Beautify defect.

**Comment by jarrodek** [comment]
But why is this JS Beautify in the first place? Shouldn't it be CSS Beautify (or whatever)?

**Comment by Glavin001** [comment]
The naming is weird. The beautifier is called `JS Beautify` although it supports JS, HTML, and CSS separately. When CSS is detected, it uses JS Beautify's CSS beautifier. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/js-beautify.coffee#L50-L53

We recommend creating an issue over at https://github.com/beautify-web/js-beautify to receive help for JS-Beautify related bugs. Please add a link back to this issue as well so other users can follow the discussion. Thanks!
