### ISSUE TITLE
Stopped reorder and regroup SCSS properties with csscomb

### ISSUE THREAD

**Issue by asafm7** [Glavin001/atom-beautify#1689]
# Description

Hi,

atom-beautify stopped reorder and regroup SCSS properties with csscomb (apparently, after update).

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/asafm7/d5594e42d262f9f5d7f25a8ec5d2ef64

**Comment by asafm7** [comment]
I've tried to add a custom cssscomb.json file and it also didn't work.

**Comment by asafm7** [comment]
It is now working,

**Comment by Glavin001** [comment]
@asafm7 I notice you are already using latest version, v0.29.26. Is there anything else you did to make it work? Such as reloading/restarting Atom.

**Comment by asafm7** [comment]
I think restarting Atom didn't works. Maybe it was a conflict with another package, since I've tried some new packages today and uninstalled most of them.
