### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by augustoccesar** [Glavin001/atom-beautify#1692]
Is it possible to add Kotlin support?

**Comment by Glavin001** [comment]
May be able to use https://github.com/shyiko/ktlint as it has a "built-in formatter".

**Comment by Glavin001** [comment]
Pull Requests welcome!

See https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md for instructions on how to add a new Language and Beautifier to Atom-Beautify. There are many Pull Requests doing this which you can look at and learn from. Let me know if you have any questions!
