### ISSUE TITLE
EJS beautification is not what I expect

### ISSUE THREAD

**Issue by fishcharlie** [Glavin001/atom-beautify#1702]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<% if (newaccount) { %>
<%- include('elements/fbnewaccountpixel.ejs') %>
<% } %>
```

# Expected Output

The beautified code should have looked like this:

```
<% if (newaccount) { %>
	<%- include('elements/fbnewaccountpixel.ejs') %>
<% } %>
```

# Actual Output

The beautified code actually looked like this:

```
<% if (newaccount) { %>
	<%- include('elements/fbnewaccountpixel.ejs') %>
		<% } %>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/fishcharlie/99cca73c63ec215dada5932423fe1dc4

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
The `debug.md` (btw, it is named incorrectly as `gistfile1.txt`) shows the Selected Beautifier as `JS Beautify`. I recommend forwarding this issue over to https://github.com/beautify-web/js-beautify for further support from this specific beautifier.

**Comment by raggesilver** [comment]
Yup, still an issue!

**Comment by alsmith808** [comment]
Happening for me too, frustrating.

**Comment by prettydiff** [comment]
There are two beautifiers available in the package for EJS: JSBeautify and Pretty Diff.  Change the beautifier to Pretty Diff and it will work.

**Comment by ZainabAl-khabori** [comment]
I have the exact opposite:
When using js-beautify, I get the following:

```
<%- include("header"); -%>

<h1>Home</h1>
<p>Lorem Ipsum</p>

<% for (let post of posts) { %>
<h1><%= post.title %></h1>
<p><%= post.body %></p>
<% } %>

<%- include("footer"); -%>
```

Of course, looking at the for loop above, that is not what I want.

But then, when I use Pretty Diff, this is what I get:

```
<%- include("header"); -%>

    <h1>Home</h1>
    <p>Lorem Ipsum</p>

    <% for (let post of posts) { %>
        <h1><%= post.title %></h1>
        <p><%= post.body %></p>
    <% } %>

    <%- include("footer"); -%>
```

This solved the for loop issue, but the result was the same issue this post is about, but with Pretty Diff.

Is there any way I can get the result I want?
