### ISSUE TITLE
Unexpected indentation for LaTeX

### ISSUE THREAD

**Issue by edwinksl** [Glavin001/atom-beautify#1706]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
\documentclass{article}

\begin{document}

\begin{equation}
a = 1.
\end{equation}

\end{document}
```

# Expected Output

I expected to see 2 spaces for indentation before `a = 1`. The beautified code should have looked like this:

```
\documentclass{article}

\begin{document}

\begin{equation}
  a = 1.
\end{equation}

\end{document}
```

# Actual Output

I saw only 1 space for indentation before `a = 1`. The beautified code actually looked like this:

```
\documentclass{article}

\begin{document}

\begin{equation}
 a = 1.
\end{equation}

\end{document}
```

# Comments

Directly running `latexindent -w test.tex` in the terminal does give 2 spaces for indentation, so I suspect this is not a bug with `latexindent.pl`.

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/edwinksl/e47e089d515f65ad77645318179cd54f

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
I think there is a bug at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/latex-beautify.coffee#L25
I see usage of `indent_char` but no `indent_size`! 😝

Pull Request welcome!
