### ISSUE TITLE
TextEditor.setScrollTop is deprecated.

### ISSUE THREAD

**Issue by Nelson112** [Glavin001/atom-beautify#1709]
This is now a view method. Call TextEditorElement::setScrollTop instead.
```
TextEditor.setScrollTop (/opt/atom/resources/app.asar/src/text-editor.js:3523:12)
<unknown> (/home/bootcamp/.atom/packages/atom-beautify/src/beautify.coffee:126:20)
```

**Comment by Glavin001** [comment]
Thanks for the notice. Pull Requests welcome!

**Comment by szeck87** [comment]
@Nelson112 I don't see this deprecation in deprecation cop or elsewhere.  Can you please reply where you're seeing this is deprecated exactly?
