### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by TyouSF** [Glavin001/atom-beautify#1712]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (<embedded>:110850:20)
MarkerLayer.markRange (<embedded>:71710:77)
DisplayMarkerLayer.markBufferRange (<embedded>:111463:58)
TextEditor.markBufferRange (<embedded>:4005:44)
constructor._showSignatureOverlay (C:\Users\TyouSyouI\.atom\packages\autocomplete-python\lib\provider.coffee:294:23)
<unknown> (C:\Users\TyouSyouI\.atom\packages\autocomplete-python\lib\provider.coffee:346:28)
```

**Comment by Glavin001** [comment]
Thanks for the notice. Pull requests welcome!

**Comment by Glavin001** [comment]
> <unknown> (C:\Users\TyouSyouI\.atom\packages\autocomplete-python\lib\provider.coffee:346:28)

Just realized this is not even a Atom-Beautify issue, it is for `autocomplete-python`.
