### ISSUE TITLE
Beautify is not working for SQL and BASH

### ISSUE THREAD

**Issue by sani554** [Glavin001/atom-beautify#1713]
# Description
Beautify  Package is not working for SQL and BASH. Kindly check the issue.

See https://github.com/andialbrecht/sqlparse for program installation instructions.
Your program is properly installed if running 'where.exe sqlformat' in your CMD prompt returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=sqlformat&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.
# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```
select * from employee where employee number = '12345' order by empno;
# Expected Output

The beautified code should have looked like this:
Beautified Code

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by sani554** [comment]
Tried even checking the option of beautify file while saving. Still it is not working.

**Comment by Glavin001** [comment]
The above error would be for SQL beautification:

> See https://github.com/andialbrecht/sqlparse for program installation instructions.

Have you followed the instructions and installed `sqlparse` which comes with `sqlformat`?

Also I see you did not add your `debug.md` file.

Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
