### ISSUE TITLE
HTML indentation wrong

### ISSUE THREAD

**Issue by LadyVanilla** [Glavin001/atom-beautify#1714]
my HTML gets 4 spaces of indentation after beautifying when it should get 2

<script src="https://gist.github.com/LadyVanilla/eaa65ac8d7ec594dcea1990278c64a25.js"></script>

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
