### ISSUE TITLE
That did not work well ... Install Atom, Beautify, tried, error ...

### ISSUE THREAD

**Issue by wloske** [Glavin001/atom-beautify#1716]
# Description

A 479kB XML did not beautify at all. 

# Input Before Beautification

A 479kB, 3776 line long XML

# Expected Output

A beautified XML ...

# Actual Output

Nothing. Error. Maximul call stack exceeded error ...

My best guess: The tool can't handle the size as small selections work. I tried NOT when it brakes because, really, 3776 lines is not large and it still breaks ...

Edit: Changed the engine from Pretty Diff to JS Beautify. result: Atom unresponsive, high CPU load.
Tried with PHPStorm. Worked flawlessly ... reformatted under a second ...

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by wloske** [comment]
I won't. Partially I did but filling in before/after sections with over 3700 lines seems a bit too much. Especially when the XML contains non public data. Actually, that 5 Minute experience was so unconvincing that the effort I put into this bug report exceeds already the effort in evaluating the editor with his plugin.

Close the ticket if you really need more ...

**Comment by Glavin001** [comment]
Feel free to report at https://github.com/beautify-web/js-beautify or https://github.com/prettydiff/prettydiff
I suspect they will want the actual long XML file so they can do testing themselves.

If you do find another beautifier which does support XML files of this size please let me know so I can add support for it in Atom-Beautify. 

> Tried with PHPStorm. Worked flawlessly ... reformatted under a second ...

I am not familiar with PHPStorm. If there is a way to call it from command line (i.e. `phpstorm format FILENAME`) or directly using Node.js then I can add support for it. Let me know. Thanks!

**Comment by wloske** [comment]
The handling of the report made the experience not more pleasant. Sorry. I am experiencing a non functional piece of software and gave an example of what to expect by a commercial tool. What I got was not an answer to the problem but a request to fill a form instead.

At least atom-beautify and it's rewrite Unibeautify claim a lot and I am sure they do a lot.  I should not be expected to deal with a subpackage of the distribution, though. You integrate it, it "stains" your package, you should take care of that.
