### ISSUE TITLE
Preserve newlines adding newlines on save.

### ISSUE THREAD

**Issue by whitneymarkov** [Glavin001/atom-beautify#1718]
# Description

With CSS 'beautify on save' and 'preserve newlines'  enabled, saving causes newlines to be added to the document.

# Input Before Beautification

This is what the code looked like before saving:

```
</* --------------------------
  Base
--------------------------- */

body {
    background: #8069a1;
    padding-top: 60px;
}

svg {
    margin: auto;
    display: block;
}

/* --------------------------
  Keyframes
--------------------------- */


/* --------------------------
  SVG Styles
--------------------------- */
>
```

# Expected Output

The beautified code should have looked like this after saving:

```
</* --------------------------
  Base
--------------------------- */

body {
    background: #8069a1;
    padding-top: 60px;
}

svg {
    margin: auto;
    display: block;
}

/* --------------------------
  Keyframes
--------------------------- */


/* --------------------------
  SVG Styles
--------------------------- */
>
```

# Actual Output

The beautified code actually looked like this (saved four times to show the newlines adding up with each save):

```
</* --------------------------
  Base
--------------------------- */

body {
    background: #8069a1;
    padding-top: 60px;
}

svg {
    margin: auto;
    display: block;
}





/* --------------------------
  Keyframes
--------------------------- */


/* --------------------------
  SVG Styles
--------------------------- */
>
```

# Steps to Reproduce

1. Open CSS file
2. In Atom-beautify, under CSS enable 'beautify on save' and 'preserve newlines'
3. Save CSS file

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/whitneymarkov/692c7fd5e7944005fd329c80dd873d96>

# Checklist

I have:
- [ y] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [y ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [y ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ y] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [y ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by AbdelrahmanHafez** [comment]
Getting similar results when I use "Beautify Editor" command. I'll try to downgrade the package.

**Comment by prettydiff** [comment]
Thank you for the issue.  Looping in @bitwiseman
