### ISSUE TITLE
[JS / JSX] JS Beautify - End with comma

### ISSUE THREAD

**Issue by hatsuo** [Glavin001/atom-beautify#1719]
# Description

Trailing commas are not being inserted into JS / JSX code when using JS Beautify.
Note: this works with Pretty Diff

This causes ESLint error `missing-dangle`.

# Input Before Beautification

This is what the code looked like before:

```
import React from 'react';
import { IntlProvider } from 'react-intl';
import { fromJS } from 'immutable';
import { shallow } from 'enzyme';

import Profile from '../index';
import messages from '../messages';

const someMap = { a: 'a', b: 'b' };
```

# Expected Output

The beautified code should have looked like this:

```
import React from 'react';
import {
  IntlProvider,
} from 'react-intl';
import {
  fromJS,
} from 'immutable';
import {
  shallow,
} from 'enzyme';

import Profile from '../index';
import messages from '../messages';

const someMap = {
  a: 'a',
  b: 'b',
};
```

# Actual Output

The beautified code actually looked like this:

```
import React from 'react';
import {
  IntlProvider
} from 'react-intl';
import {
  fromJS
} from 'immutable';
import {
  shallow
} from 'enzyme';

import Profile from '../index';
import messages from '../messages';

const someMap = {
  a: 'a',
  b: 'b'
};
```

# Steps to Reproduce

1. Add code to Atom editor
2. Set editor style to `JavaScript` or `JavaScript (JSX)`
3. Set atom-beautify settings for JavaScript / JSX:
 - Default Beautifier: JS Beautify
 - End with comma: true
4. Run command `Atom Beautify: Beautify Editor`
3. Trailing commas are missing

# Debug

Here is a link to the `debug.md` Gist: [debug.md](https://gist.github.com/AaronBurmeister/ac130e3f1cfc0472dd666e39278c0bff)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by mdskinner** [comment]
"end_with_comma": true,

**Comment by AaronBurmeister** [comment]
@mdskinner as you can see in the [debug.md](https://gist.github.com/AaronBurmeister/ac130e3f1cfc0472dd666e39278c0bff) this option is enabled for js and jsx.

**Comment by mdskinner** [comment]
Try adding the param to the root and not categorising it into the `js` property

```
cat ~/.jsbeautifyrc

{
    "indent_size": 4,
    "indent_char": " ",
    "other": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "break_chained_methods": true,
    "space_before_conditional": true,
    "space_after_anon_function": true,
    "keep_function_indentation": true,
    "keep_array_indentation": true,
    "brace_style": "none",
    "max_preserve_newlines": 3,
    "space_in_paren": true,
    "end_with_comma": true,
}

```

**Comment by AaronBurmeister** [comment]
@mdskinner I'm sorry but I could not figure this out.

I have no `.jsbeautifyrc` in my home directory and there also is no one in `~/.atom`.
The only way for me to set the option is by using `~/.atom/config.cson`.

How would I do this?

**Comment by szeck87** [comment]
I think the Preferences for atom-beautify are incorrect, I don't see anywhere in [jsbeautify's options](https://github.com/beautify-web/js-beautify#options) that state it can insert a comma at the end. Or perhaps it did at one point and has since been removed.

**Comment by mdskinner** [comment]
@AaronBurmeister you need to make one in the root of your project.

What is the path of your directory root?

vim ~/.jsbeautifyrc
or 
vim path/to/project/.jsbeautifyrc

Then copy the file contents from above in there.
If you don't know how to use vim, try vi or something else.

**Comment by szeck87** [comment]
@mdskinner I've tried it, it doesn't work with jsbeautify.  Are you sure you're not using prettydiff?

**Comment by mdskinner** [comment]
@szeck87 positive, its working as we speak. What have you tried?

**Comment by szeck87** [comment]
I put a .jsbeautifyrc file in the root of project folder with the json from your earlier comment.  I ran the Beautify command for a javascript file/language with js-beautify as the default beautifier, it didn't insert any commas.

To ensure it was reading the file, I added `comma_first: true` and ran it again, and it moved the commas from the end of the line to the beginning of the next line as I expected.  Can you post a gist of yours?

**Comment by AaronBurmeister** [comment]
@mdskinner I also tried your solution with same results as @szeck87.

Are you using the latest version (0.30.5)? It uses js-beautify v1.6.14.
