### ISSUE TITLE
PHPCBF stopped working altogether after v0.30.1. Throws 'Could not find 'PHPCBF'. The program may not be installed'

### ISSUE THREAD

**Issue by avivais** [Glavin001/atom-beautify#1730]
After last update I cannot beautify using PHPCBF anymore.
Previously, it worked "out-of-the-box", now even when setting the path explicitly it still complains about not finding the executable

![screen shot 2017-06-19 at 18 29 47](https://user-images.githubusercontent.com/1503623/27292924-937e7a9a-551d-11e7-917e-60b8c1657121.png)

![screen shot 2017-06-19 at 18 30 21](https://user-images.githubusercontent.com/1503623/27292952-a8dc4836-551d-11e7-8fd0-0d7e7ea5dd0b.png)

<img width="575" alt="screen shot 2017-06-19 at 18 31 22" src="https://user-images.githubusercontent.com/1503623/27292978-bebc0614-551d-11e7-80e3-7509051347cf.png">

Running on latest macOS Sierra (10.12.5)

[debug.md](https://gist.github.com/avivais/1d31bbc34c0f7c2b4e8e449e20b9ef49)

**Comment by Glavin001** [comment]
@prasadfutballer  please subscribe to this Issue.

**Comment by Glavin001** [comment]
@avivais Thanks for reporting. I will be fixing this ASAP (likely tonight). Please downgrade to last working version, `v0.29.26`, and I will post here once a fix has been published. Thanks!

**Comment by avivais** [comment]
@Glavin001 thank you for the (very) fast response! I just updated PHPCBF via composer to 2.9.1 (stable) by Squiz (And not 3.0.1 as you mentioned).
I now get a different error:
> Error parsing PHPCS response
> Something went wrong attempting to parse the PHPCS output

How do you suggest I downgrade? Won't it (Beautify package that is) keep being updated automatically?

**Comment by Glavin001** [comment]
> How do you suggest I downgrade? Won't it (Beautify package that is) keep being updated automatically?

I'm not familiar with any auto-updating package functionality in Atom. Maybe I missed it -- I manually choose when to update my packages.

Downgrading Atom-Beautify would be: `apm install atom-beautify@0.29.26`. Let me know if that does not work.

> I just updated PHPCBF via composer to 2.9.1 (stable) by Squiz (And not 3.0.1 as you mentioned).

The quote block above was from another user, who has the exact same issue, on another PHPCBF version. Atom-Beautify is having troubles parsing the version. It expects `phpcbf --version` to return `3.0.1` or `2.9.1` however it instead receives `PHP_CodeSniffer version 3.0.1 (stable) by Squiz (http://www.squiz.net)`. So I will need to add support for both 😄 .

**Comment by prasadfutballer** [comment]
@avivais I actually upgraded PHPcode_sniffer to 3.0.0, then it stopped working, then tried downgrading to 2.9.0 and still had this issue. So right now i am running PHPcode_sniffer 2.6.0 whicch works perfectly with atom beautify 0.29.26

**Comment by Glavin001** [comment]
Published fixes to v0.30.2

**Comment by avivais** [comment]
@Glavin001 updated to v0.30.2 and still get the "Error parsing PHPCS response". This is my updated [debug.md](https://gist.github.com/avivais/54fc0c9762666b18ddcbd35e726b7ce2)

**Comment by Glavin001** [comment]
> 2017-06-21T12:59:35.674Z - error: [beautifiers/index.coffee]  ReferenceError: path is not defined
    at /Users/avivais/.atom/packages/atom-beautify/src/beautifiers/phpcbf.coffee:63:49

Looks like I have an error: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/phpcbf.coffee#L63
Missing requiring `path`. Will have to fix this later. 

@avivais Pull requests welcome, by the way 😄 . May be quicker than me patching and retrying, since your system setup is likely differently than my own.

**Comment by avivais** [comment]
@Glavin001 point taken :)

Actually that error message was the linter, not the beautifier - Sorry on that (Though it did help discovering the *path* issue ;) )

Thanks again
