### ISSUE TITLE
Warning about "php cs fixer"

### ISSUE THREAD

**Issue by bestina75** [Glavin001/atom-beautify#1732]
# Description

An alert appears after updating to version 0.30.2.

The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option named "Executables - PHP-CS-Fixer - Path" in Atom-Beautify package settings now.

There was no problem in previous versions.
How should we solve it?

**Comment by Glavin001** [comment]
> How should we solve it?

The solution is in the error message:

> The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option named "Executables - PHP-CS-Fixer - Path" in Atom-Beautify package settings now.

I will elaborate.

Go into Atom-Beautify package settings.

## Before (currently what you have):

![image](https://user-images.githubusercontent.com/1885333/27331510-262ae394-5594-11e7-8fc4-4b751731087c.png)

^ Delete it from there.

## After (new correct way):

![image](https://user-images.githubusercontent.com/1885333/27331542-495b48d6-5594-11e7-9464-6fd4a55306a8.png)


Does this help? How would you recommend I change this error message so it would be clear what to do?

**Comment by Glavin001** [comment]
@nicholas-ooi, you had the same question from https://github.com/Glavin001/atom-beautify/issues/1725#issuecomment-309413358

How would you recommend I change this error message to be more clear?

**Comment by bestina75** [comment]
@Glavin001 Thank you. However, I do not have a PHP-CS-FIXER entry.
My environment is win10, atom1.18.0ia32, atom-beautify 0.30.2.

**Comment by Glavin001** [comment]
@LIANGWEIBIAO what do you think would make this message clearer and more self explanatory?

**Comment by ryanpcmcquen** [comment]
Perhaps we could change:
```
The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option named "Executables - PHP-CS-Fixer - Path" in Atom-Beautify package settings now.
```
To:
```
The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option under "Executables", labeled "PHP-CS-Fixer - Path" in this package's settings (scroll up).
```

**Comment by Glavin001** [comment]
Thank you for your feedback @ryanpcmcquen!

Before:
>  Please switch to using the option **named "Executables - PHP-CS-Fixer - Path" in Atom-Beautify package settings now.**

After:
> Please switch to using the option **under "Executables", labeled "PHP-CS-Fixer - Path" in this package's settings (scroll up).**

I think this is an improvement.
I'm not sure what you meant by `(scroll up)`? Is this because the `Executables` section is at the top?

Let's go even further, how about the following:

> Please switch to using the option **in section "Executables" (near the top) in subsection "PHP-CS-Fixer" labelled "Path" in Atom-Beautify package settings.**

I'm not sure about `in this package's settings` versus `Atom-Beautify's package settings`.

Please keep the feedback coming! I will make this change in the next couple days and publish.

**Comment by ryanpcmcquen** [comment]
I like _near the top_! I just found the wording confusing, although I am not sure `in this package's settings` is any less confusing ...

**Comment by Glavin001** [comment]
Awesome! Changing it to the following now:

> The "PHP-CS-Fixer" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "PHP - PHP-CS-Fixer Path (cs_fixer_path)" labelled "Path" in Atom-Beautify package settings.

Will be in the next release.

**Comment by PeterStavrou** [comment]
How do you get the menu "PHP-CS-FIXER" below PHP?
I have: 
Perl
PHP
Puppet

**Comment by keisukefunatsu** [comment]
@PeterStavrou 
You can see "PHP-CS-FIXER" in "Executables" below General.

**Comment by Glavin001** [comment]
Published to v0.30.4

The error message should now be:

> The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "PHP-CS-Fixer" labelled "Path" in Atom-Beautify package settings.

**Comment by Treasu** [comment]
it is so difficult to find the PHP-CS-Fixer under the Executables

**Comment by Glavin001** [comment]
@Treasu is it? This is what it looks like:

![image](https://user-images.githubusercontent.com/1885333/27331542-495b48d6-5594-11e7-9464-6fd4a55306a8.png)

Any recommendations for how it could be improved?

**Comment by blachawk** [comment]
what would be the windows based path?   I am placing the following into the required field based on this thread... 
```
C:\Users\me\.atom\packages\php-cs-fixer
```
but it still does not work.

**Comment by k2levin** [comment]
Just a small add on, for those who is confuse and cannot find the "PHP-CS-Fixer"
Please expand the "Executables", "PHP-CS-Fixer" is inside "Executables"

**Comment by Samnan** [comment]
This is a mess really. I have tried everything to update the php cs fixer path, in executables section, in php cs fixer path ,removed one of them to keep the other , nothing works. The warning continues. Moreover updating to the 0.30.5 version always gets stuck and never updates.

**Comment by Glavin001** [comment]
@Samnan the applicable line of code can be found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L92-L93

```coffeescript
    if options.cs_fixer_path
      @deprecateOptionForExecutable("PHP-CS-Fixer", "PHP - PHP-CS-Fixer Path (cs_fixer_path)", "Path")
```

Where `options.cs_fixer_path` is the old, deprecated `PHP - CS-Fixer Path` option.
By deleting the value for this option -- making it an empty string, falsy -- it will not show the deprecation message.

If you find there is an issue, I recommend creating a `debug.md` Gist by following instructions at https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md
Without this `debug.md` information *nothing can/will be done* to investigate your issue. Once provided, I am confident we can figure out the issue.

---

@Treasu and @k2levin if you have recommendations for how to improve the deprecation message, please let me know and preferably submit a Pull Request changing the code found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L99-L101

**Comment by xuanmos** [comment]
@Glavin001 	
I read the answer above, but I still didn't solve the problem. What's the reason? Or a warning message, can you help me?
<pre>The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "PHP-CS-Fixer" labelled "Path" in Atom-Beautify package settings.</pre>

**Comment by Berg93** [comment]
![php-cs-fixer-problem](https://user-images.githubusercontent.com/25328637/33716058-fa94918e-db54-11e7-880f-1dd9be0cf5b2.png)
