### ISSUE TITLE
VSCode (Visual Studio Code) port?

### ISSUE THREAD

**Issue by donovanhiland** [Glavin001/atom-beautify#1737]
By far the best code formatting plugin. I was spoiled and can't find anything that will give me the same results in VSCode. Any chance we might get a port sometime in the future?

**Comment by Glavin001** [comment]
I definitely plan to support VSCode when [Unibeautify](https://github.com/Unibeautify/unibeautify) is ready. In fact, the goal is Atom, VSCode, Sublime Text, Node.js API, and CLI app. Lots to do! Thank you for your interest in Atom-Beautify!

**Comment by JohaWeber** [comment]
as @donovanhiland mentioned, i also was spoiled - tried VSCode but switched back to Atom the same day just because of this plugin. Any ETA on Unibeautify? The catchphrase sounds really promising!

**Comment by Glavin001** [comment]
Here is the repository: https://github.com/Unibeautify/vscode

I have started working on it. No ETA yet. Thank you all for your patience!
