### ISSUE TITLE
Executables - PHP-CS-Fixer - Path

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [Glavin001/atom-beautify#1743]
The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option named "Executables - PHP-CS-Fixer - Path" in Atom-Beautify package settings now.

**Comment by Glavin001** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/1732#issuecomment-309727855
