### ISSUE TITLE
disable line break within curly braces

### ISSUE THREAD

**Issue by hemedani** [Glavin001/atom-beautify#1752]
# Description
Sorry for this cheap issue but i can't find the right way to do that.

whenever i use the beautify it's break everything in curly braces in new line.

for example it's convert this line :
```javascript
const { email, password, shomare, address, name, nameKhanevadegi, shahr, taxibs } = req.body;
```
to this :
```javascript
const {
	email,
	password,
	shomare,
	address,
	name,
	nameKhanevadegi,
	shahr,
	taxibs
} = req.body;
```

I want to disable this line break and keep it in one line.

**Comment by prettydiff** [comment]
Could you please complete the debug.md template from Atom Beautify so that we know which beautifier to work with?
