### ISSUE TITLE
Colorize Pug

### ISSUE THREAD

**Issue by djcaesar9114** [Glavin001/atom-beautify#1758]
# Description

The results of beautification are not what I expect: everything is the same color.

# Input Before Beautification

Everything is the same color.

# Expected Output

Everything is the same color.

# Steps to Reproduce

1. Code in Pug
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Please provide an example, screenshot, and/or anything else which may make this Issue more clear. I do not understand what the problem is or how I can help. Atom-Beautify does not even deal with colour of text in Atom.
