### ISSUE TITLE
Rename "jade" into "pug"

### ISSUE THREAD

**Issue by djcaesar9114** [Glavin001/atom-beautify#1759]
Well, the title is self-explanatory.
I spent a few minutes wondering why I couldn't find pug beautifyer, but then I noticed you kept the old name, not in use anymore.
Is it possible to put  the actual name?
Thanks :)

**Comment by Glavin001** [comment]
Absolutely, good idea!

Pull Requests welcome 😃 .

**Comment by Glavin001** [comment]
Possibly applicable code:
- https://github.com/Glavin001/atom-beautify/blob/master/src/languages/jade.coffee#L3-L3
- https://github.com/Glavin001/atom-beautify/blob/master/src/languages/index.coffee#L40
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/pug-beautify.coffee#L9

And some related documentation: https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md
