### ISSUE TITLE
Add Golang support

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#176]
Use [go fmt](http://blog.golang.org/go-fmt-your-code).

**Comment by Blaskyy** [comment]
+1

**Comment by hairyhenderson** [comment]
+1

**Comment by dgeske** [comment]
I suggest the [https://atom.io/packages/go-plus] (go-plus package), which adds `gofmt` on save amongst other handy features needed for go dev in Atom. Happy coding!

**Comment by Glavin001** [comment]
After #282 is released, this will be much easier to add support for. Thanks for your patience everyone.

**Comment by Glavin001** [comment]
Useful links:
- http://blog.golang.org/go-fmt-your-code
- https://github.com/joefitzgerald/go-plus/blob/1bf750daaf38757d9b703fdb1df908e72c48bc42/lib/gofmt.coffee#L32-L79

**Comment by Glavin001** [comment]
Published to v0.26.0
