### ISSUE TITLE
atom-beautify not working..??

### ISSUE THREAD

**Issue by kondalraodurgam** [Glavin001/atom-beautify#1762]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```
<div class="row">
<div class=" col-md-12">
<p>
<span>Hello world</span>
</p>
</div>
</div>

# Expected Output
<div class="row">
	<div class=" col-md-12">
		<p>
			<span>Hello world</span>
		</p>
	</div>
</div>

The beautified code should have looked like this:

<div class="row">
	<div class=" col-md-12">
		<p>
			<span>Hello world</span>
		</p>
	</div>
</div>

# Actual Output

The beautified code actually looked like this:
```

```
# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
2017-07- debug: [beautifiers\beautifier.coffee] Beautified HTML: <div class="row">
	<div class=" col-md-12">
		<p>
			<span>Hello world</span>
		</p>
	</div>
</div>
# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**EDITED** - I changed this comment to make the code sample easier to read. (prettydiff)

**Comment by kondalraodurgam** [comment]
I installed 2 times but atom-beautify is not working

**Comment by kondalraodurgam** [comment]
how  you gonna solve issue in my atom

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by kondalraodurgam** [comment]
Thank you for your response

**Comment by kondalraodurgam** [comment]
I thing its working now fine @Glavin001  But Tag lines is not showig
