### ISSUE TITLE
Keybind not working

### ISSUE THREAD

**Issue by filipesilva** [Glavin001/atom-beautify#177]
The default keybinding seems to not be working anymore. I'm on windows 7, using atom 0.166.0 and atom-beautify 0.21.1.

Keybind resolver shows the keybind was resolved, but nothing happens.
![image](https://cloud.githubusercontent.com/assets/4172079/5630525/88c443ec-95b6-11e4-993a-19d6981e2766.png)

Running from the command palette works though.

**Comment by Glavin001** [comment]
Sorry, there have been some unfortunate breaking changes to keep up with the Atom API.
Here are the up-to-date commands: https://github.com/Glavin001/atom-beautify/blob/master/lib/beautify.coffee#L260-L262

`beautify:beautify-editor` is what you want.

**Comment by Glavin001** [comment]
The README documentation is up-to-date: https://github.com/Glavin001/atom-beautify#custom-keyboard-shortcuts

Let me know if you have any more problems. Thanks.

**Comment by filipesilva** [comment]
Thanks for the swift reply! 

I added that keybind to my keybinds.cson but it seems to be superseded by the default one. Did I misinterpret your reply?

![image](https://cloud.githubusercontent.com/assets/4172079/5630739/4ef54d4e-95b8-11e4-81bf-cdcfef25dac6.png)

**Comment by Glavin001** [comment]
There's the bug! https://github.com/Glavin001/atom-beautify/blob/master/keymaps/atom-beautify.cson#L11

Thank you for letting me know. I'll fix it ASAP.

**Comment by Glavin001** [comment]
Published patch to v0.21.1

**Comment by filipesilva** [comment]
And it works! Awesome, thank you :D

**Comment by DioDread** [comment]
Hello, on Win 10 I have same problem but with a bit strange behavior - default package keybinding doesn't work, but if I access Atom-Beautify via main menu -> Packages -> Atom Beautify -> Beautify it's working fine. There no other packages which override ctrl + alt + b.
Thank you.
