### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by NFGamerMC** [Glavin001/atom-beautify#1771]
https://gist.github.com/NFGamerMC/6efd948ec05066c4f998c4abd6adfe8d

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
