### ISSUE TITLE
TWIG beautifier: 'or' is not recognized, whatever parentheses you add around the two sides of the expression

### ISSUE THREAD

**Issue by asitemade4u** [Glavin001/atom-beautify#1775]
# Description

TWIG beautifier: 'or' is not recognized, whatever parentheses you add around the two sides of the expression

# Input Before Beautification

This is what the code looked like before:

```
{% if (( post_pax.pax_typepax != "Student" ) and ( area == 'aca' )) or (( post_pax.pax_typepax != "Traveler" ) and ( area == 'lsr' )) %}
```

# Expected Output

The beautified code should have looked like this:

```
{% if (( post_pax.pax_typepax != "Student" ) and ( area == 'aca' )) or (( post_pax.pax_typepax != "Traveler" ) and ( area == 'lsr' )) %}
```

# Actual Output

The beautified code actually looked like this:

```
	{% if (( post_pax.pax_typepax != "Student" ) and ( area == 'aca' )) 
					or(( post_pax.pax_typepax != "Traveler" ) and ( area == 'lsr' )) %}
```
As you see the 'or' is stuck to the following parenthese.
Ialso attach a screen copy of the code.
![selection_001](https://user-images.githubusercontent.com/11460106/28480090-23a821d4-6e2d-11e7-87a2-beb130fbdc97.jpg)

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: 
<script src="https://gist.github.com/asitemade4u/67fc77567cf4008ee0e9567bed0e4097.js"></script>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
This is a Pretty Diff defect.  I can reproduce it in the latest version.  It will be a little while until I can get the fix out.  I am spending all my open source time ripping the parsers out of Pretty Diff - https://github.com/Unibeautify/parse-framework/  Once I get those parsers ripped out, stable, and more standard I will have a lot of work to do to adjust Pretty Diff to use these parsers as an external dependency with different options.
