### ISSUE TITLE
how can i format code nowrap

### ISSUE THREAD

**Issue by kog-7** [Glavin001/atom-beautify#1786]
# Description

i want to only use for indent by format code ,but create much newline in code,how can i config code as i wish？ 

# Input Before Beautification

This is what the code looked like before:

```
    var item=0;
var ob={a:1,b:2,c:3}


```

# Expected Output

The beautified code should have looked like this:

```
var item=0;
var ob={a:1,b:2,c:3}
```

# Actual Output

The beautified code actually looked like this:

```
var item=0;
var ob={
     a:1,
     b:2,
     c:3
  }
```

**Comment by prettydiff** [comment]
Which beautifier are you using?  You can find out by preparing a debug.md file from Atom Beautify.
