### ISSUE TITLE
Beautification of comment in combination with language-babel package breaks code

### ISSUE THREAD

**Issue by derwaldgeist** [Glavin001/atom-beautify#1789]
I am using `language-babel` in combination with `atom-beautify`.

In adapter.js, there is the following lines:
```
  // add promise support
  ['createOffer', 'createAnswer'].forEach(function(method) {
  ...
```

If I enable `language-babel`, this is auto-beautified on save to:

```
  // add promise support['createOffer', 'createAnswer'].forEach(function(method) {
  ...
```

effectively breaking the code.

I'm not sure which package is actually responsible for this degradation.

**Comment by prettydiff** [comment]
If you generate the debug.md you can see which package is responsible

**Comment by derwaldgeist** [comment]
Thanks for your response. How can I create this `debug.md`?

BTW: I also filed this issue for the `language-babel` plugin. The owner told me that it cannot be his package, as he is not doing any code rewrites. The only thing his plugin changes that might affect beautification is that he changes the type of my JavaScript files to JSX.

**Comment by prettydiff** [comment]
https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by derwaldgeist** [comment]
Here's the Gist:
https://gist.github.com/derwaldgeist/89c0a39b9368061265fd5d15381eaa05

To find the line affected, search for
// add promise support['createOffer', 'createAnswer'].forEach(function(method)

**Comment by prettydiff** [comment]
This must be a defect in the older version of Pretty Diff.  I cannot reproduce this in the latest version.  I have been trying to get a recent version of Pretty Diff into Atom Beautify but have had some trouble with unit tests.  Perhaps you can help: https://github.com/Glavin001/atom-beautify/pull/1750

**Comment by derwaldgeist** [comment]
Ok, thanks for the feedback!
