### ISSUE TITLE
Add Angularjs+Template support

### ISSUE THREAD

**Issue by ArtworkAD** [Glavin001/atom-beautify#179]
For angularjs template code inside html

    <% styles.forEach( function ( file ) { %>
        <link rel="stylesheet" type="text/css" href="<%= file %>" />
    <% }); %>

beautifying is not working. It comes out like this:

    <% styles.forEach( function ( file ) { %>
        <link rel="stylesheet" type="text/css" href="<%= file %>" />
        <% }); %>

            
            <% scripts.forEach( function ( file ) { %>
                <script type="text/javascript" src="<%= file %>"></script>
                <% }); %> 

Would appreciate a fix for this problem.

**Comment by Glavin001** [comment]
js-beautify handles HTML support for Atom Beautify. I'd recommend forwarding this issue over to them at https://github.com/beautify-web/js-beautify
Thanks.

**Comment by prettydiff** [comment]
This is the same syntax used with Embedded JS, ERB, Mustache, and so forth. I added support for this with: https://github.com/prettydiff/prettydiff/issues/59

**Comment by Glavin001** [comment]
Excellent, @prettydiff! Then this should be coming soon with #282 release.

**Comment by Glavin001** [comment]
When v0.25.0 is released you can beautify Angular Template code using EJS (Embedded JavaScript) language, which uses the Pretty Diff beautifier. In Atom Beautify, EJS language is detected with the `JavaScript Template` grammar. You can force Atom to treat your file as `JavaScript Template` grammar by clicking your file's current grammar in the bottom status bar and changing it to `JavaScript Template`.

File's current grammar is `HTML`:

![image](https://cloud.githubusercontent.com/assets/1885333/7443244/d917c140-f112-11e4-8528-3117685b0b2e.png)

Then select grammar `JavaScript Template`:

![image](https://cloud.githubusercontent.com/assets/1885333/7443249/297adf3c-f113-11e4-8ae4-ef2f096ec2fb.png)

Let me know if you have any problems.

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.
