### ISSUE TITLE
Is it possible to only break method chains if chain length is more than two methods

### ISSUE THREAD

**Issue by joaobarcia** [Glavin001/atom-beautify#1794]
# Description

According to https://github.com/airbnb/javascript#whitespace--chains you are only suppose to break method chains if the chain has more than 2 methods. And it does make sense to me. Small chains are more readable inline and they are frequent enough that they should have their own rule.

Is it possible to define a chain length after which they are broken?

# Input Before Beautification
```
// Long method chain
const leds1 = stage.selectAll('.led').data(data).enter().append('svg:svg').classed('led', true)
    .attr('width', (radius + margin) * 2).append('svg:g')
    .attr('transform', `translate(${radius + margin},${radius + margin})`)
    .call(tron.led);

// Short method chain
const leds2 = stage.selectAll('.led').data(data);
```

# Expected Output

```
// Long method chain - should be broken
const leds1 = stage.selectAll('.led')
    .data(data)
  .enter().append('svg:svg')
    .classed('led', true)
    .attr('width', (radius + margin) * 2)
  .append('svg:g')
    .attr('transform', `translate(${radius + margin},${radius + margin})`)
    .call(tron.led);

// Short method chain - should NOT be broken
const leds2 = stage.selectAll('.led').data(data);
```

# Actual Output

The beautified code actually looked like this:

```
// Long method chain - is correctly broken
const leds1 = stage.selectAll('.led')
    .data(data)
  .enter().append('svg:svg')
    .classed('led', true)
    .attr('width', (radius + margin) * 2)
  .append('svg:g')
    .attr('transform', `translate(${radius + margin},${radius + margin})`)
    .call(tron.led);

// Short method chain - is INCORRECTLY broken
    const leds2 = stage.selectAll('.led')
      .data(data);
```

Thanks a lot

**Comment by prettydiff** [comment]
Yes, it is possible.  Different beautifiers handle that differently.  Pretty Diff has an option called `methodchain` that will break method chains onto new lines http://prettydiff.com/documentation.xhtml#methodchain

**Comment by joaobarcia** [comment]
@prettydiff , thanks for the quick comment.

However, from what I understand from the docs you sent the options are only "always break chain methods" and "never break chain methods". There is no "only break chain methods if there are more than two methods applied"

**Comment by prettydiff** [comment]
Yeah, that is how Pretty Diff is configured.  JS Beautify likely has this configured differently if they support it.

**Comment by joaobarcia** [comment]
It seems JS Beautify also does not support this, even though there are a few issues requesting it. Thanks anyway, @prettydiff !

**Comment by prettydiff** [comment]
This appears to be working perfectly in the latest version of Pretty Diff.  I cannot remember if this was a Pretty Diff issue or a JS Beautify issue.  The latest version of Pretty Diff is now in Atom Beautify, so if you were using Pretty Diff as your beautifier would you kindly close this issue?

**Comment by joaobarcia** [comment]
Hi @prettydiff , thanks for the updates! It is true that now the chain is breaking only if there is more than one method applied. Is there anywhere we can set after how many methods the chain should break? In my case I would love to set it for "if more than two".

**Comment by prettydiff** [comment]
@joaobarcia That capability doesn't currently exist.  That would be an enhancement to change the methodbreak option from a boolean to a number.

**Comment by joaobarcia** [comment]
@prettydiff , exactly. Maybe I'm the only one who would be interested in it, but it would be good to leave an open issue in one of the repos so other people could vote for it if they are interested as well. Should I close this one and the issue is tracked in the prettydiff repo?

**Comment by prettydiff** [comment]
Yes, that would be a good idea to close this and open a new issue in prettydiff.  Thanks for the interest.
