### ISSUE TITLE
Additional ; inserted when using next.js style multi-line inline CSS

### ISSUE THREAD

**Issue by derwaldgeist** [Glavin001/atom-beautify#1795]
The next.js tutorial recommends to style your React components like this:

```jsx
<style jsx>{`
      h1, a {
        font-family: "Arial";
      }
`}</style>
```

If I enable atom-beautify, it auto-adds a semicolon after the closing ` of the multi-line string,  causing the code to break:

```jsx
<style jsx>
      {
        ` h1,
        a {
          font-family: "Arial";
        }
         `;
      }</style>
```

Here's the debugging gist:
https://gist.github.com/derwaldgeist/e7d756ad097e17be167bc8bcb23964f8

**Comment by prettydiff** [comment]
I can reproduce this defect in Pretty Diff and am working it now.

**Comment by prettydiff** [comment]
Does this really break rendering in JSX because it looks like a proper use of a semicolon to terminate a statement?

**Comment by derwaldgeist** [comment]
Not sure, but it definitely broke eslint linting.

**Comment by prettydiff** [comment]
In JavaScript the backticks are an ES6 (ES2015) new feature to allow template strings.  In this case you have a JSX block (JavaScript) from a JSX tag (XML) containing a single statement of a template string.  Without further clarification I cannot change Pretty Diff to accommodate this request.  I recommend seeking clarification from whoever maintains the ESLint config you are using.

**Comment by derwaldgeist** [comment]
Ok, thanks for the clarification. Makes sense.
