### ISSUE TITLE
Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version'

### ISSUE THREAD

**Issue by kadekutama** [Glavin001/atom-beautify#1796]
I have a problem when trying to use atom-beautify. It is always showing message "Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version'".

![Error Message](https://image.prntscr.com/image/22jSr0pCQjyaIpumYdCdfg.png)

Here is the full message:
`Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version'
Hide Stack Trace
Error: Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version'
    at file:///C:/Users/Kadek/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:27
    at tryCatcher (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

I use Anaconda Python 3.6 on my Windows 10 laptop. Everything is okay when I use CMD, but it never runs on Atom.

![CMD](https://image.prntscr.com/image/pzffu463S6uHH2dO9QEF5Q.png)

How do I resolve this problem?

**Comment by riokt** [comment]
I still got this issues. any solutions?

**Comment by aarish407** [comment]
I'm not sure if this is still an issue for some, but here is the solution either way. 

Since you're working on Windows, you need to add the location of "conda.exe" to your PATH Environment variable. 

Go to your Anaconda folder, open the "Scripts" folder, and copy the path. (It will look something like "C:\.....\Anaconda3\Scripts")

Then go to "Properties" (right-click anywhere on file explorer) -> Advanced System Settings  -> Environment Variables -> Click on the "Path" variable and hit Edit -> New -> Paste the path that you had copied earlier. 

Remember to hit OK each time while shutting the windows. 

Note: If any current CMD windows are open, you'll have to close them and open a new one in order to use your new environment variables.

**Comment by Ap1075** [comment]
Still getting the same error. Any other solution for this?

**Comment by yizhixiaorenzha** [comment]
I see,I am sorry, I didn’t use it long time,but i will try my best to recall it, I will answer you later.

**Comment by kadekutama** [comment]
If I remember correctly, it happened because I'm running Atom without administrator access. Run as administrator solved the problem.

**Comment by AlfhaOmega** [comment]
try check your python windows-based applications 32 or 64 bit. And then install anaconda according to your python windows-based applications bit.

**Comment by shshilpa65** [comment]
I have uninstalled anaconda. I am using the only the python setup but still i get the same error

**Comment by ghost** [comment]
Check your anaconda file. Search python.exe maybe not in. I solved this problem. Maybe will too you.

**Comment by Biobox1** [comment]
This issue is due to one of the following:
1. Ensure there are no spaces in the file names(directories) where you are installing Anaconda
 Therefore reinstall anaconda in a different path(with no spaces) with admin privileges
2. Ensure you add C:\Users\YourNameWithNoSpaces\Anaconda2  and   
    C:\Users\YourNameWithNoSpaces\Anaconda2\Scripts  folders to System Variables path.
To do this in Windows;
-- Right click on computer
-- Click Advanced  System Settings
-- Click Environment Variables
-- Under System Variable scroll to 'path'
--Click on edit
--For windows 8 and below add a semicolon(;) before adding each of the above paths
--Ok all
--Restart command prompt

3. If you did not install on default path, make sure you run with admin privileges

**Comment by zhourongrong** [comment]
> I have a problem when trying to use atom-beautify. It is always showing message "Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version'".
> 
> ![Error Message](https://camo.githubusercontent.com/6025fbb84999e99c19e4d06b6a58eb041768ef25/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f32326a5372307043516a79614970756d5964436466672e706e67)
> 
> Here is the full message:
> `Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version' Hide Stack Trace Error: Unable to create process using 'C:\Anaconda3\python.exe C:\Anaconda3\Scripts\autopep8-script.py --version' at file:///C:/Users/Kadek/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:27 at tryCatcher (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23) at Promise._settlePromiseFromHandler (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31) at Promise._settlePromise (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18) at Promise._settlePromise0 (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10) at Promise._settlePromises (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:693:18) at Async._drainQueue (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16) at Async._drainQueues (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10) at Async.drainQueues (C:\Users\Kadek\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14) at process._tickCallback (internal/process/next_tick.js:103:7)`
> 
> I use Anaconda Python 3.6 on my Windows 10 laptop. Everything is okay when I use CMD, but it never runs on Atom.
> 
> ![CMD](https://camo.githubusercontent.com/d90a0c6f1a69174ffdacaae2123140871c6d194d/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f707a666675343633533675484832644f3951454635512e706e67)
> 
> How do I resolve this problem?

check  the exe，its name is python  not python3.6

**Comment by Joelexy** [comment]
I have literally tried every possible solutions given out here, but there aren't solving any issue for me.

**Comment by lokeshvarma4511** [comment]
> I have literally tried every possible solutions given out here, but there aren't solving any issue for me.

Hi,

Solved?

**Comment by thedatadecoder** [comment]
Check if some third-party application is blocking it. In my case, it was "ThreatLocker".

**Comment by lokeshvarma4511** [comment]
ok
Thank you

**Comment by SiyabongaN** [comment]
> This issue is due to one of the following:
> 
> 1. Ensure there are no spaces in the file names(directories) where you are installing Anaconda
>    Therefore reinstall anaconda in a different path(with no spaces) with admin privileges
> 2. Ensure you add C:\Users\YourNameWithNoSpaces\Anaconda2  and
>    C:\Users\YourNameWithNoSpaces\Anaconda2\Scripts  folders to System Variables path.
>    To do this in Windows;
>    -- Right click on computer
>    -- Click Advanced  System Settings
>    -- Click Environment Variables
>    -- Under System Variable scroll to 'path'
>    --Click on edit
>    --For windows 8 and below add a semicolon(;) before adding each of the above paths
>    --Ok all
>    --Restart command prompt
> 3. If you did not install on default path, make sure you run with admin privileges

Thank you, it worked for me. I had to create another folder with no spaces and installed Anaconda there.

**Comment by faqihuddien** [comment]
i get the same error. I just run as administrator and it works.

**Comment by SVMendoza** [comment]
update pip 

python -m pip install --upgrade pip
