### ISSUE TITLE
"Preserve Newlines" option does not convert consecutive empty lines to single empty line.

### ISSUE THREAD

**Issue by JohaWeber** [Glavin001/atom-beautify#1799]
# Description

The results of beautification are not what I expect.
Although I made sure to have JS Beautify set as Default Beautifier in the package settings and have the option "Preserve newlines" checked (which says it will convert consecutive empty lines to a single empty line) nothing happens.

# Input Before Beautification

This is what the code looked like before:

```
h1 {
	background: $dark;
}




h4 {
	background: white;
	span {
		background: red;
	}
}
```

# Expected Output

The beautified code should have looked like this:

```
h1 {
	background: $dark;
}

h4 {
	background: white;
	span {
		background: red;
	}
}
```

# Actual Output

The beautified code actually looked like this:

```
h1 {
	background: $dark;
}




h4 {
	background: white;
	span {
		background: red;
	}
}
```

# Steps to Reproduce

1. Add code to Atom editor in CSS file with syntax set to `css` and the file-extension set to `.css`.
2. Make sure `Beautify On Save` is checked for css-files in package-settings
3. Save file
3. This beautified code does not look right!

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by niels-numbers** [comment]
Having the same issue. Would be nice if this would be configurable
