### ISSUE TITLE
"Beautify on save" in javascript erases file then saves then crashes

### ISSUE THREAD

**Issue by peteyhayman** [Glavin001/atom-beautify#1805]
Apologies this seems to be a duplicate issue, although it looks as though it has been closed
https://github.com/Glavin001/atom-beautify/issues/924

**Comment by mateddy** [comment]
Also happen on json files.

**Comment by Glavin001** [comment]
This may be caused by https://github.com/Glavin001/atom-beautify/issues/1721 . I will close this as a duplicate of either #1721 or #924.

Workaround: disable "Beautify On Save" until fixed.

---

Fix published to v0.30.5
