### ISSUE TITLE
Makefile support

### ISSUE THREAD

**Issue by angrykoala** [Glavin001/atom-beautify#1807]
# Description
`makefiles` are not supported, when trying to beatifify a makefile, an alert appears:

```
Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Makefile" and extension "". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues
```

I have:
- [ ] ~~Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly~~
- [ ] ~~Reloaded (or restarted) Atom to ensure it is not a caching issue~~
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by angrykoala** [comment]
* Cmake isn't the same syntax as [makefiles](https://stackoverflow.com/questions/25789644/difference-between-using-makefile-and-cmake-to-compile-the-code)
* Astyle is for C/C++ code and I'm not aware it supports makefiles
* OpenCL is completely unrelated

**Comment by picorealm** [comment]
I second this.  Support for GNU make would be very helpful.
