### ISSUE TITLE
Extra line before closing CSS/SCSS  rule?

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#181]
This sort of code"
````
.ttl {
  margin-bottom: 10px;
}
````
beautifies to this:
````
.ttl {
  margin-bottom: 10px;

}
`````
There is an empty line before the closing bracket. I would rather that not be there or, if anything, add the empty line AFTER the last bracket.

Note this is the last bracket of each rule in SCSS, like so:
````
.ttl {
  margin-bottom: 10px !important;
  .foo {
      color: red;
     }

}
````
The bracket for the sub-rule is fine.  

Atom 168.0, Atom Beautify 0.21.2, OS 10.10.1

**Comment by quicoto** [comment]
+1 for this.

**Comment by smlombardi** [comment]
Is this acknowledged or being fixed?  It's a real obstacle. Thanks.

**Comment by Glavin001** [comment]
- SCSS is handled by [Prettydiff](https://github.com/austincheney/prettydiff). See https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L424-L426 and https://github.com/Glavin001/atom-beautify/blob/master/lib/langs/less-beautify.coffee 
- CSS is handled by [js-beautify](https://github.com/beautify-web/js-beautify). See https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L420-L423

Forward those issues to their respective maintainers and see if those are being worked on or fixed. If they are resolved let me know and I will update Atom Beautify to reflect their updates :+1:. Thanks.

**Comment by smlombardi** [comment]
They prettydiff maintainer cannot reproduce the bug.  In fact, if you go to http://prettydiff.com and try this block, you'll see it works fine.  Try it in Atom (.174) saved as SCSS or CSS and it happens.

````
.block-grid-6 > li {
  width: 16.66666%;
}

.small-block-grid-3 > li {
    width: 33.33333%;
    list-style: none;
}

.small-block-grid-3 > li:nth-of-type(1n) {
    clear: none;
}

.small-block-grid-3 > li:nth-of-type(3n+1) {
    clear: both;
}
````

**Comment by Glavin001** [comment]
I am away from my laptop right now however if you could submit a failing test as a pull request that would be very helpful. Look in the examples directory and follow that structure to add both test input and expected output files. 




Thanks and I'll try to take a closer look ASAP. 


—

**Comment by Glavin001** [comment]
I'm looking into this right now. Looks like a change between 1.6.3 to 1.8.8 of Prettydiff. I am able to get it to work properly, however my unit tests are failing, so this leads me to believe that there is a new Prettydiff option or a default has changed. I'll see if I can figure it out and let you all know.
