### ISSUE TITLE
JSX: Inline If with Logical && Operator does not format properly

### ISSUE THREAD

**Issue by ksb86** [Glavin001/atom-beautify#1814]
# Description

The result of the beautification is not correct.

# Input Before Beautification

This is what the code looked like before:

```
class Test extends React.Component {
render() {
return (
<div>
{this.props.user && <span>
{this.props.user.displayname}
</span>
}
</div>
)
}
}

```

# Expected Output

The beautified code should have looked like this:

```
class Test extends React.Component {
    render() {
        return (
            <div>
                {this.props.user &&
                    <span>
                        {this.props.user.displayname}
                    </span>
                }
            </div>
        )
    }
}
```

# Actual Output

The beautified code actually looked like this:

```
class Test extends React.Component {
    render() {
        return (
            <div>
                {this.props.user && <span>
                    {this.props.user.displayname}
                </span>
}
            </div>
        )
    }
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ksb86/b9f72702086ffea09e04043b2ba7bbed

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
This is definitely a beautifier defect.  I would open an issue with the respective issue.  You could just copy paste the issue text into a new issue at the other repository and link to this issue.

**Comment by ksb86** [comment]
Thanks! What do you mean by 'other repository'.  Is 'atom-beautify' not the beautifier? Sorry I'm a little confused.

**Comment by ksb86** [comment]
Thanks @prettydiff! https://github.com/prettydiff/prettydiff/issues/473

**Comment by prettydiff** [comment]
This appears to be resolved in the latest version of Pretty Diff which is now in Atom Beautify.
