### ISSUE TITLE
Installing “atom-beautify@0.30.5” failed.Hide output…

### ISSUE THREAD

**Issue by anand853** [Glavin001/atom-beautify#1818]
Installing “atom-beautify@0.30.5” failed.Hide output…
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/cigniti_apasunoori/.atom/packages/atom-beautify/node_modules/marko/scripts/build.js'
    at Error (native)
```

**Comment by Sphinxs** [comment]
/* Ward */
