### ISSUE TITLE
blinking when beautify scss file

### ISSUE THREAD

**Issue by WLyKan** [Glavin001/atom-beautify#1819]
# Description

blinking when beautify scss file
![untitled](https://user-images.githubusercontent.com/2155093/29450314-ccef89ee-8430-11e7-9b30-54da46357deb.gif)

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by WLyKan** [comment]
I fund the `scss` config conflicts with the `whitespace` and `editorconfig`.
```
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by szeck87** [comment]
Does it only happen when saving?  What version of atom-beautify are you running?

**Comment by WLyKan** [comment]
**Platform**: darwin

## Versions

**Atom Version**: 1.19.3

**Atom Beautify Version**: 0.30.4

**Comment by szeck87** [comment]
Upgrade to 0.30.5 and try
