### ISSUE TITLE
rbeautify issues

### ISSUE THREAD

**Issue by dabates** [Glavin001/atom-beautify#182]
According to your Readme, one should installed ruby beautifier, but when I do that.. it's still looking for rbeautify.  when I install rbeautify, however, it just returns a empty buffer after it runs. 

Has the new ruby beautifier not been implemented yet?

**Comment by Glavin001** [comment]
Have you set the `ruby_rbeautify_path` in the package settings?
See https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L294-L298

Atom Beautify attempts to automatically find your installation of `rbeautify` but this could have failed. You can force it by setting it up manually. Let me know if that helps.

**Comment by dabates** [comment]
Yup I didn't realize that was there.. sorry about that.. if it's in there it will run the new one..

**Comment by Glavin001** [comment]
Not a problem. If there's anything else you need a hand with let me know. I'm still improving documentation ( #58 ).

**Comment by dabates** [comment]
And if you ever need help, let me know I do javascript work daily (professionally) so wouldn't mind helping out if needed..

**Comment by Glavin001** [comment]
Thanks! I appreciate that. Contributors are always welcome :smiley:.
