### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed

### ISSUE THREAD

**Issue by codingkidprodigy** [Glavin001/atom-beautify#1821]
# Description

I installed atom-beautify and when I tried to beautify some PHP code the error message:
Could not find 'php-cs-fixer'. The program may not be installed.
See php-cs-fixer installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
Your program is properly installed if running 'where.exe php-cs-fixer' in your CMD prompt returns an absolute path to the executable.
popped up. I did all of this, I installed php-cs-fixer so, when I run the where.exe php-cs-fixer in the terminal this file path comes up:
C:\Users\myUserName\AppData\Roaming\Composer\vendor\bin\php-cs-fixer
C:\Users\myUserName\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat

I don't know what to do because I have been searching up online how to do this for many days now. I also don't know how to get the debug.md file. So please help me out. Thanks in advance. I am also using Windows 10 x64-bit. I also installed the bash terminal so I will be able to run sudo commands

**Comment by mikewconnolly** [comment]
Had the same problem.

After loads of trial error in W10 x64 bit; I found that I needed to set the PHP-CS-FIxer Path in 'atom-beautify' packages settings to the BAT file

I set the absolute path to be based on:
C:\Users\myUserName\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat

NOTE: I found two places to put the path in atom-beautify settings, one under a top-level category of PHP and the second under Executables / PHP-CS-Fixer.

I'm a novice, not sure if it was part of the solution; 
but I did put a copy of php-cs-fixer.phar in the C:\Users\myUserName\AppData\Roaming\Composer\vendor\bin directory too.

Hope that helps.  As I say I'm no expert, but after a trying for a few hours this appears to be working.

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by atefBB** [comment]
@mikewconnolly Thank you, it works for me!

**Comment by biniyam17** [comment]
I am getting the same error when trying to use Beautify on my html and php code in my .php file. Will try and troubleshoot using the above mentioned templates and update.
