### ISSUE TITLE
Semicolons in switch statements/javascript 

### ISSUE THREAD

**Issue by jesseroow** [Glavin001/atom-beautify#1824]
# Description

I updated to 0.30.5 and this version appears to not respect end of lines correctly in javascript switch statements if there is no semi colon. 

Ending statements with a semicolon fixes this issue and this issue has not existed for mein previous versions. 

I can generate debug for this if needed. 

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

switch (case) {
  case 1:
  console.log(1)
  console.log(2)
  break;
  default:
}

# Expected Output

The beautified code should have looked like this:

switch (case) {
  case 1:
      console.log(1)
      console.log(2)
    break;
  default:
}

# Actual Output

The beautified code actually looked like this:

switch (case) {
  case 1:
    console.log(1)console.log(2)break;
  default:
}

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Please prepare the debug.md file so that we can know where to begin debugging.  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md
