### ISSUE TITLE
Request: Use Atoms built in language settings rather then reparsing file extensions for beautification process

### ISSUE THREAD

**Issue by sPalmerTSY** [Glavin001/atom-beautify#1829]
# Description

There are several open tickets for file extension support most of which could be handeled with the systems already in place by rather then parsing the file extension directly you used Atoms built in language typing then ran the beautification off that. it would also allow you to have support for non-standard file types like those used in many frameworks/libraries. as well as other community modules like file-type

**Comment by Glavin001** [comment]
Atom-Beautify does use Atom's grammars (AKA "built in language"), however when it fails it falls back to file extensions. See for `JavaScript` example: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L5-L19

Maybe I misunderstood what you are suggestion. Please let me know!
