### ISSUE TITLE
Add meteor support

### ISSUE THREAD

**Issue by Francescu** [Glavin001/atom-beautify#183]
Hi, 

I installed the `meteor-api` package and it adds Javascript (Meteor) as a language. 

`atom-beautify` tells me `Unsupported language for grammar 'JavaScript (Meteor)'.`

**Comment by awatson1978** [comment]
Oh my gosh, if you could add the Meteor styleguide to atom-beautify, that would be *amazing*.  I've been working on the ``meteor-api`` package, and would be more than happy to help debug any Meteor support.

Meteor styleguide is below...
https://github.com/meteor/meteor/wiki/Meteor-Style-Guide

**Comment by Glavin001** [comment]
@Prettydiff is this a language that you'd consider supporting?

**Comment by prettydiff** [comment]
Yep, I will add Meteor style guide to the jspetty style guide options. Would you be able to assign or transfer this issue to me?

**Comment by Glavin001** [comment]
@prettydiff has added support so this is not high priority.

**Comment by Glavin001** [comment]
@Francescu / @awatson1978 , please provide a simple example file that is not beautified. I am adding tests and once I have that example file I will publish :+1:.

**Comment by Glavin001** [comment]
Meteor support should come when #282 is released.

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.

**Comment by Glavin001** [comment]
I may have to add the grammar `JavaScript (Meteor)` to a language. Is Meteor simply JavaScript? If you change the grammar for your file from `JavaScript (Meteor)` to `JavaScript` and then beautify, does that work?

**Comment by awatson1978** [comment]
Yeah, it's just JavaScript.  A specific api implemented in javascript, but same grammar and syntax.  I'm away from my computer this weekend, but have this on my todo list.  Will try getting to it early this week!

**Comment by Glavin001** [comment]
Excellent, thanks! Let me know wherever I can help.
