### ISSUE TITLE
PHP-CS-Fixer Path configuration option has been deprecated

### ISSUE THREAD

**Issue by tangzhibo317** [Glavin001/atom-beautify#1830]
I'm a PHP developer, One day, I used atom-beautify, There's a problem, The error of a yellow toolbox was reported.
_The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "PHP-CS-Fixer" labelled "Path" in Atom-Beautify package settings._
It's all available before.
So, I wonder what the reason is?How do I do that?
thinks

**Comment by MorrowindAJi** [comment]
ok,I meet the same problem too
But the problem does not seem to prevent atom-beautify formatting our php code，If that can solve the problem that is the best :D 
oh,my english is not very good ，so i can see you mean ,but i dont  know how to say, i have to need 
 google help me ,sry  my friend

**Comment by Axel186** [comment]
Have the same problem...

**Comment by szeck87** [comment]
It's in the Atom preferences -> Atom Beautify settings.  If you click on Executables it will list a bunch of languages and packages.  Click on PHP-CS-Fixer and it will have one text box for the path.

![screen shot 2017-09-05 at 2 59 37 pm](https://user-images.githubusercontent.com/8315038/30080920-fe7977c2-924a-11e7-85ff-4ff156e9a0aa.png)

**Comment by szeck87** [comment]
@tangzhibo317 @MorrowindAJi @Axel186 Did those directions fix the deprecation warning?

**Comment by Axel186** [comment]
Still getting this error - I think I have to reinstall my Atom. Maybe it's some OS issues (I am using Linux)...

But any way, you can see that PHP-CS-Fixer path is there, and the file is really exists and works.

![screenshot from 2017-09-12 19-15-25](https://user-images.githubusercontent.com/11068030/30336738-c2c73c88-97ee-11e7-9b3b-cd9643848b55.png)

Or maybe I missing something else?

**Comment by szeck87** [comment]
@Axel186  Try putting the path in the Executables setting PHP-CS-Fixer (like screenshot from my previous comment) and not under the PHP setting where you have it.

**Comment by Axel186** [comment]
@szeck87, You're right! That was confusing...

Issue is fixed for me, thank you!

**Comment by raaams** [comment]
I have the same issue in windows and i tried all the options above

**Comment by softmvlz** [comment]
it was to enter the path (C: / user / ....) in the executables option PHP-CS-FIXER and not in settings-PHP
