### ISSUE TITLE
Deprecation warning for os.tmpDir

### ISSUE THREAD

**Issue by VentyCZ** [Glavin001/atom-beautify#1833]
# Description

There's a DeprecationWarning for os.tmpDir()

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Look in the developer console

# References
[Nodejs pull request](https://github.com/nodejs/node/pull/6739)

![image](https://user-images.githubusercontent.com/3247664/29980096-7c5a488e-8f48-11e7-9595-633515280f5a.png)

**Comment by szeck87** [comment]
This is specific to those that are run through executables (such as php-cs-fixer in this screenshot).  Those preinstalled are not affected.

**Comment by Glavin001** [comment]
Published to v0.30.6
