### ISSUE TITLE
property deleted by atom-beautify

### ISSUE THREAD

**Issue by benpptung** [Glavin001/atom-beautify#1835]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:
```
var o = { uploading: e.loaded/e.total*100 }
 ```

# Expected Output

The beautified code should have looked like this:

```
var o = {
  uploading: e.loaded / e.total*100
}
```

# Actual Output

The beautified code actually looked like this:

```
var o = {
  uploading: e.loaded / e.*100
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Which language and beautifier are you using?  Can you generate a debug gist?

**Comment by benpptung** [comment]
Hi, szeck87 , thank you for reply.
I am using the default settings, so I assume the beautifier is `JS Beautify` and the language is `JavaScript`. My atom version is 1.20.1 x64. Hope it helps. :)

**Comment by szeck87** [comment]
I'm not able to recreate.  Can you debug and post a gist of the log to this?  Also, is this the only code in that file?  If not, please upload the file itself.  Both of these will help troubleshoot the issue.

**Comment by prettydiff** [comment]
I remember seeing something like this a while ago.  I bet this is an issue with old Pretty Diff.  It does not appear to be present in the current version of Pretty Diff.

If my guess is correct then this issue will be resolved by completing this pull request: https://github.com/Glavin001/atom-beautify/pull/1750.  The pull request is held by a conflict with a newer dependency.

**Comment by szeck87** [comment]
@prettydiff  Ah you're right.  I switched to prettydiff and it did just that.

@benpptung Try switching to js-beautify as the default javascript beautifier.

**Comment by prettydiff** [comment]
The latest version of Pretty Diff is published to Atom Beautify where this issue is resolved.
