### ISSUE TITLE
Short conditionals

### ISSUE THREAD

**Issue by RomanISWG** [Glavin001/atom-beautify#1836]
# Description

Can we have a setting to turn following behaviour off please?

# Input Before Beautification

This is what the code looked like before:

```
a == b ? c : d
```

# Expected Output

The beautified code should have looked like this:

```
a == b ? c : d
```

# Actual Output

The beautified code actually looked like this:

```
a == b
? c
: d
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
This looks like a Pretty Diff related defect that is resolved on the Pretty Diff side with the option `ternaryline=true`.  If this issue is closed prematurely please reopen it.
