### ISSUE TITLE
Does not work with clang-format-3.4 on ubuntu 14.04

### ISSUE THREAD

**Issue by bufanda** [Glavin001/atom-beautify#1837]
# Description

When I try to beautify c-source code with clang-format-3.4 on ubuntu 14.04 I always get the following message:

LLVM (http://llvm.org/): LLVM version 3.4

Optimized build. Built Mar 5 2014 (17:05:10). Default target: x86_64-pc-linux-gnu Host CPU: corei7-avx
LLVM (http://llvm.org/):
  LLVM version 3.4
  
  Optimized build.
  Built Mar  5 2014 (17:05:10).
  Default target: x86_64-pc-linux-gnu
  Host CPU: corei7-avx
Hide Stack Trace
Error: LLVM (http://llvm.org/):
  LLVM version 3.4
  
  Optimized build.
  Built Mar  5 2014 (17:05:10).
  Default target: x86_64-pc-linux-gnu
  Host CPU: corei7-avx
    at /home/liepertt/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:27
    at tryCatcher (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/liepertt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

# Steps to Reproduce

1. Add c-code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. The error message above gets reported!

# debug.md
https://gist.github.com/bufanda/4cd33c6592ecc463517e24d3dddcd0c6

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by mmikhasenko** [comment]
It seems that I have the same issue as described above
```
LLVM (http://llvm.org/): LLVM version 3.4.2 Optimized build. Built Dec 7 2015 (09:37:36). Default target: x86_64-redhat-linux-gnu Host CPU: core-avx2
LLVM (http://llvm.org/):
  LLVM version 3.4.2
  Optimized build.
  Built Dec  7 2015 (09:37:36).
  Default target: x86_64-redhat-linux-gnu
  Host CPU: core-avx2
Hide Stack Trace
Error: LLVM (http://llvm.org/):
  LLVM version 3.4.2
  Optimized build.
  Built Dec  7 2015 (09:37:36).
  Default target: x86_64-redhat-linux-gnu
  Host CPU: core-avx2
....
```
```
Centos7
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
Clang was instal from epel repository
```
=================================================================================
 Package                Arch                Version                    Repository                   Size
=================================================================================
Installing:
 clang                  x86_64              3.4.2-8.el7                EPEL7_2_x86_64               19 M
Installing for dependencies:
 llvm                   x86_64              3.4.2-8.el7                EPEL7_2_x86_64              1.3 M
 llvm-libs              x86_64              3.4.2-8.el7                EPEL7_2_x86_64              7.6 M

Transaction Summary
=================================================================================

```
