### ISSUE TITLE
Minified javascript makes Atom "hang" while they're being beautified/loaded

### ISSUE THREAD

**Issue by tlygnersjo** [Glavin001/atom-beautify#1841]
# Description

When the package "atom-beautify" is enabled, opening a minified javascript file takes extremely long time (at least a minute) processing and meanwhile Atom "hangs".

# Input Before Beautification

This is what the code looked like before:

```
Any minified JS file (e.g. https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js)
```

# Expected Output

I expected Atom to not hang for a couple of minutes when opening a minified javascript file

# Actual Output

Atom hangs for at least one minute before being able to edit the minified js file.

# Steps to Reproduce

1. Enable Atom Beautify package
2. Open any minified javascript file
3. You'll see that Atom "hangs" while processing the file for at least a minute

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
Disabled Atom Beautify and everything works as expected.

**Comment by szeck87** [comment]
Hmm, can you post your machine specs?  I tried it and it opened instantly.
