### ISSUE TITLE
Stylus Beautify Not Working

### ISSUE THREAD

**Issue by bariskrdrl** [Glavin001/atom-beautify#1847]
But it doesn't work I'm doing to beautify Stylus

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
