### ISSUE TITLE
How can I hide/remove 'Debug Atom Beautify' from context menus?

### ISSUE THREAD

**Issue by udayms** [Glavin001/atom-beautify#1848]
The context menu is already very cluttered. I'm trying to remove unnecessary items on that menu.

**Comment by Glavin001** [comment]
I am not sure how this could be supported through Atom-Beautify.

I recommend contacting Atom team over at https://github.com/atom/atom or asking the question at https://discuss.atom.io . Please post back here when you find an answer. Thanks!

**Comment by udayms** [comment]
@Glavin001 : when I have the atom-beautify package installed, I have two new items added to my context menu - 1) Beautify Editor Contents and 2) Debug Atom Beautify.

Are you sure that the 2nd item is not added by the Atom Beautify package? I don't see other packages adding such menu items to my context menu.

**Comment by szeck87** [comment]
@Glavin001 It's kept in https://github.com/Glavin001/atom-beautify/blob/master/menus/atom-beautify.cson for context menu. Don't know if there's a way to show it based on a preference though.

**Comment by udayms** [comment]
can i atleast edit this file and change this setting?

**Comment by Glavin001** [comment]
> > I am not sure how this could be supported through Atom-Beautify.

> Are you sure that the 2nd item is not added by the Atom Beautify package? I don't see other packages adding such menu items to my context menu.

The context menu item `Debug Atom Beautify` is from Atom-Beautify, however I am not sure how to show/hide menu items for your personal Atom installation. Providing this menu item is important for helping users debug their issues -- a requirement -- so I leave it to the Atom team to support a way to configure a personal Atom installation to show/hide these menu items.

**Comment by udayms** [comment]
I understand the need for this. But isn't it a requirement for only the developers of the package? Is it relevant for the users as well? Also can't we make it configurable through the settings?

**Comment by szeck87** [comment]
The `Debug Atom Beautify` command is a bit misleading as far as the text.  It basically generates a log of your atom settings and before/after information for beautifying a file.  It's something end users can easily do to help us troubleshoot any issues.

I'd have to research if it's possible to add a setting for it or not when the commands are stored in a cson file.  Would adding separators around those two options help?

**Comment by udayms** [comment]
Forgive me if I am out of line here. I come from a UX background and tend to get a bit nit-picky about things like this :) ... If that command generates a log for debugging. All the more reason not to have it in the UI. It should be hidden somewhere in the settings from where it can be triggered **when** the users stumble on a bug/problem. It should not be part of the UI that general users use. I for one have been using Atom Beautify probably for more than a year now. I have never needed to use that. It's been sitting there in my menu taking up space. I'm sure tons of users have used that menu item to get useful info to get support from here. But, that's not the typical use case. We are talking about exposing a live wire in the car dashboard - a wire that has to be hidden somewhere in the engine compartment. Just my 2 cents. I love the package and would love to see it get better :)

**Comment by szeck87** [comment]
@Glavin001 I don't have an objection to removing the Debug option from the context menu.  It would still be available from the Packages menu and Command Palette.  We should probably put separators in the context menu regardless.

**Comment by combs** [comment]
I'd love to see this menu item removed @Glavin001
