### ISSUE TITLE
Atom-beautify - can't install OSX

### ISSUE THREAD

**Issue by pomyslografia** [Glavin001/atom-beautify#1856]
Hi, I tried to install atom-beautify.

I've got output. 

Installing “atom-beautify@0.30.5” failed.Hide output…
/private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr
`-- (empty)

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr/package.json'
npm WARN apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr No description
npm WARN apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr No repository field.
npm WARN apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr No README data
npm WARN apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/akrawczyk/.atom/.apm/.apmrc" "--userconfig" "/Users/akrawczyk/.atom/.apmrc" "install" "/private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/d-117818-710-2ttgm2.eb87iudi/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr/node_modules/atom-beautify/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/zw/gtn7_0s15y33hp9j1x8qmfmjzjz_mx/T/apm-install-dir-117818-710-1r56cfb.zn6mv7k3xr/npm-debug.log
npm ERR! code 1

Please help.

**Comment by dsfernandobond** [comment]
Same problem here

**Comment by szeck87** [comment]
Please try installing now.

**Comment by dsfernandobond** [comment]
Hi, I've installed it again and instead of yesterdays errors I'm now getting this:
![captura de tela 2017-09-19 as 08 19 56](https://user-images.githubusercontent.com/12818565/30590050-69cca102-9d13-11e7-9c89-653cfd850b18.png)
](url)

**Comment by szeck87** [comment]
You need to install Ruby Beautify separately.  Follow the instructions here:  https://github.com/erniebrodeur/ruby-beautify#installation

**Comment by dsfernandobond** [comment]
Ah of course. Stupid of me. Thanks!!

**Comment by pomyslografia** [comment]
It works now, thanks

**Comment by Glavin001** [comment]
> It works now, thanks

Closing as resolved.

Thanks @szeck87 !

---

@dsfernandobond do you have any feedback for how the error message could be improved to make it more clear? I see the link to https://github.com/erniebrodeur/ruby-beautify was provided in the error message, however the instructions were not followed. Is the message not clear?

Thanks in advance for your feedback!
