### ISSUE TITLE
Appveyor and Travis badges are outdated

### ISSUE THREAD

**Issue by szeck87** [Glavin001/atom-beautify#1857]
# Description

The code showing the Appveyor and Travis statuses are outdated, using a shields.io URL and it always shows the build is failing.

Appveyor should look something like this (this is from my Appveyor atom-beautify repo, so obviously will have to get it for this repo from Appveyor):  `[![Build status](https://ci.appveyor.com/api/projects/status/b3j4htx6btcpdlnu/branch/master?svg=true)](https://ci.appveyor.com/project/szeck87/atom-beautify/branch/master)`

Travis CI should look something like this:  `[![Build Status](https://travis-ci.org/szeck87/atom-beautify.svg?branch=master)](https://travis-ci.org/szeck87/atom-beautify)`

**Comment by Glavin001** [comment]
Reopening for AppVeyor

**Comment by Glavin001** [comment]
AppVeyor markdown:

```markdown
[![Build status](https://ci.appveyor.com/api/projects/status/himnq7tjxl2fdc8u/branch/master?svg=true)](https://ci.appveyor.com/project/Glavin001/atom-beautify/branch/master)
```
