### ISSUE TITLE
Right-Click in File Tree to Beautify only on file names

### ISSUE THREAD

**Issue by jerone** [Glavin001/atom-beautify#186]
The cool feature to [beautify when right-click in the tree view](https://github.com/Glavin001/atom-beautify/issues/36) only works when you right-click on the file name, not on the whole file row.

![beautify](https://cloud.githubusercontent.com/assets/55841/5764798/12d8e2d2-9cf5-11e4-9ee8-2accdbdd3b87.jpg)

**Comment by Glavin001** [comment]
I originally had it working for the entire file row, however it felt rather hacky (checked if it was name, if not then find sub-element, etc). Then I saw that [Markdown-Preview only allows right-clicking on the names](https://github.com/atom/markdown-preview/blob/master/menus/markdown-preview.cson#L17-L30) I decided to follow suit. I like this idea and have also found it annoying that I must be precise and click directly on the name. I'll definitely look more into this and find a better solution when I can. Thanks for your feedback.

**Comment by toadhats** [comment]
This feature isn't working at all for me, but beautifying via that command palette, or via the 'packages' menu works fine. Is this something I should report as a bug?

**Comment by Glavin001** [comment]
@toadhats : Definitely. Thanks for creating https://github.com/Glavin001/atom-beautify/issues/489

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
