### ISSUE TITLE
InvalidArgumentException The "..." directory does not exist.

### ISSUE THREAD

**Issue by spencerandhill** [Glavin001/atom-beautify#1864]
Hi guys,
i'm trying to setup atom-beautify with php-cs-fixer on MacOS Sierra. I installed php-cs-fixer, configured the path to php-cs-fixer in the atom-package (under php-cs-fixer executable path) to "/usr/local/bin/php-cs-fixer". This was the output of which php-cs-fixer.

Problem: 
Whenever i'm running "beautify" on a file, it shows me the output "[InvalidArgumentException]
The "/Applications/MAMP/htdocs/shopware/shopware/tests" directory does not
exist.

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] []..."

Unfortunately this is correct, cause there's no directory "/Applications/MAMP/htdocs/shopware/shopware/tests". The file, which i was trying to beautify is not in this path. It looks, like atom is not passing the correct parameter to php-cs-fixer.

Is this a known issue? I did not configure anything in php-cs-fixer, could this also be a problem?

I have:
- Tried uninstalling and reinstalling Atom Beautify (including reinstallation of ATOM itself) to ensure it installed properly
- Reloaded (or restarted) Atom to ensure it is not a caching issue
- Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues

**Comment by szeck87** [comment]
Hi @spencerandhill.  Can you please clarify a few things?

>  I installed php-cs-fixer

Which [method](https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation) did you use to install it?

> configured the path to php-cs-fixer in the atom-package (under php-cs fixer executable path) to "/usr/local/bin/php-cs-fixer"

Did you put that path under the PHP section or under the Executables > PHP-CS-Fixer section?  If not the latter, can you put the path there?

Also, if you haven't already, put the path to PHP under Executables > PHP.

**Comment by spencerandhill** [comment]
Hi szeck87,
i installed it via "Globally (Composer)" with

$ composer global require friendsofphp/php-cs-fixer

I've put "/usr/local/bin/php-cs-fixer" under the php-cs-fixer settings in the field named "PHP-CS-fixer executable path"

Unfortunately i didn't put the php-path under executables. I thought, that it's accessible via php-alias as it is in the terminal. after putting in this, it's working. Thank you very much!!!!
