### ISSUE TITLE
path.dirname must be a string

### ISSUE THREAD

**Issue by szeck87** [Glavin001/atom-beautify#1866]
# Description

Similar to #1509 and #1423 

Argument to path.dirname must be a string

Object.dirname - /Applications/Atom Beta.app/Contents/Resources/app/src/electron-shims.js:9:10
<unknown> - /Users/[user]/Desktop/Development/atom-beautify/src/beautify.coffee:360:115
tryCatcher - /Users/[user]/Desktop/Development/atom-beautify/node_modules/bluebird/js/release/util.js:16:23
Promise._settlePromiseFromHandler - /Users/[user]/Desktop/Development/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31
Promise._settlePromise - /Users/[user]/Desktop/Development/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18
Promise._settlePromiseCtx - /Users/[user]/Desktop/Development/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10

# Steps to Reproduce

1. Add code to Atom editor, but do not save the file
2. Run command `Atom Beautify: Debug`
3. Deprecation warning

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Documentation - https://nodejs.org/dist/latest-v8.x/docs/api/path.html#path_path_dirname_path

* The error is probably on this line: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L415
* The argument *filePath* comes from https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L342
* The reference *editor* appears to come from this line https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L292

If my manual stack trace is correct, I'm not good with CoffeeScript, it looks like this might be an Electron error.

**Comment by szeck87** [comment]
Nah, it's an atom-beautify issue.  I need to update the description to say run debug for an unsaved file, that's when the path is `undefined` throwing this warning.
