### ISSUE TITLE
Add Settings shortcut to the Packages menu

### ISSUE THREAD

**Issue by rishacha** [Glavin001/atom-beautify#1869]
# Description
It would be really nice if you can add a shortcut to open the settings view as part of the package sub-menu.  
> This is my go-to tool before I submit any piece of code for review. Appreciate the work done :+1:

**Comment by szeck87** [comment]
This is a pretty simple update.  I have it completed, just waiting on Linuxbrew to fix one of their formulas so Travis passes.  https://github.com/szeck87/atom-beautify/tree/add-settings-menu

**Comment by Glavin001** [comment]
Published to v0.30.6
