### ISSUE TITLE
Beautify not working properly: no indent after if/for etc

### ISSUE THREAD

**Issue by nilsgoksor** [Glavin001/atom-beautify#1879]
# Description

The beautify command does nothing most of the time, and sometimes just part of the desired function. I've reinstalled atom and the package. I've mostly tried it in python. I've checked the settings: it's not disabled, beautify on save is on and it uses autopep8. Still, when I press ctrl + alt + b nothing happens even though I can see the program is executing.

Here's an example  

# Input Before Beautification

This is what the code looked like before:

```
<list = range(1, 11)
for i in list:
if i % 2 == 0: print 'even'
    else:
    print 'not even'>
```

# Expected Output

The beautified code should have looked like this:

```
<list = range(1, 11)
for i in list:
    if i % 2 == 0:
        print 'even'
    else:
        print 'not even'>
```

# Actual Output

The beautified code actually looked like this:

```
<list = range(1, 11)
for i in list:
if i % 2 == 0:
    print 'even'
    else:
    print 'not even'>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
If you run autopep8 from the command line, what options would you pass in to make it look the expected way?  I ran `autopep8 -i --aggressive test.py` (where test.py is the same as your original) and it beautified it the same way as running through Atom Beautify.
