### ISSUE TITLE
html comment new line after beautify

### ISSUE THREAD

**Issue by savgiannis** [Glavin001/atom-beautify#1885]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
  <div class="container">
        <div class="row">
          <div class="col-md-4">

          </div><!--/col-->
          <div class="col-md-8">

          </div><!--/col-->
        </div><!--row-->
    </div><!--container-->>
```

# Expected Output

The beautified code should have looked like this:

```
 <div class="container">
        <div class="row">
          <div class="col-md-4">

          </div><!--/col-->
          <div class="col-md-8">

          </div><!--/col-->
        </div><!--row-->
    </div><!--container-->
```

# Actual Output

The beautified code actually looked like this:

```
    <div class="container">
      <div class="row">
        <div class="col-md-4">

        </div>
        <!--/col-->
        <div class="col-md-8">

        </div>
        <!--/col-->
      </div>
      <!--row-->
    </div>
    <!--container-->
```

Hi,
As you can see after I beautify the code, the html comments next to the html tags go to a new line and that makes the code messy and also adds unnecessary lines and makes the code larger. Is there any way to change this property? 
Thanks

**Comment by prettydiff** [comment]
Which beautifier was used?  It was likely JS Beautify or Pretty Diff.  If you generate the debug.md file you can see which one is used.

**Comment by savgiannis** [comment]
With both JS Beautify and Pretty Diff happens the same

**Comment by prettydiff** [comment]
There was a really old issue I closed yesterday about this.  Normally the beautifiers are smart enough to know that a line comment following some code on the same line is related specifically to the code on that line.  The exception here (and thus challenge) is that the comment is following an end tag.  It is hard to know that the comment is directly related to that previous tag, since an end tag closes a structure, or if it is comment between this structure and the next and just happens to be written on this line out of convenience.

**Comment by savgiannis** [comment]
So, There isn't anything we can do at this moment?

**Comment by prettydiff** [comment]
If you can provide some design direction to us know when a comment should be paired with a preceding end tag versus when it shouldn't I can implement the solution.

**Comment by savgiannis** [comment]
Well, I think it should stay in the same line after all the ending tags, and if someone wants it in a new line that's what preserve new lines property is for.

**Comment by prettydiff** [comment]
Good point.  I will investigate this.

**Comment by savgiannis** [comment]
Thanks I'll be waiting for your response

**Comment by jfletcher-nuxeo** [comment]
In the latest release of atom-beautify, using PrettyDiff when I have something like this:

```html
<!--
`myelement-create-layout`
@group Nuxeo UI
@element myelement-create-layout
-->
```

It gets merged into a single line.  Do you think this is related?  Or should I open a new bug?  FWIW I have "preserve newlines" enabled.

**Comment by CodeSpartan** [comment]
Still an issue, at least for Vue.
