### ISSUE TITLE
Add *.html5 suffix

### ISSUE THREAD

**Issue by operatorone** [Glavin001/atom-beautify#1886]
Can I add another suffix to be formatted in HTML? 

I got files witch are named *.html5 and they are HTML, but they have to have this suffix for the CMS to be used as templates. Thanks for your effort. atom.beautify rules!

Cheers,
operatorone

**Comment by szeck87** [comment]
Hi @operatorone, it should beautify those files as long as you have HTML selected as the grammar/language for those files.

![screen shot 2017-10-11 at 12 00 37 pm](https://user-images.githubusercontent.com/8315038/31454694-db099e0a-ae7b-11e7-989e-104547e9bc77.png)
