### ISSUE TITLE
Option to keep LI tags on one line?

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#189]
Currently, the closing LI tag breaks to a new line. If I make LI unformatted, then all the LIs run together,

Is it possible to format LIs, but keep the contents together. As in:

````
<ul>
    <li>lorem iosum</li>
    <li>dolor sit amet</li>
</ul>
`````

**Comment by ryanwbauer** [comment]
Same issue here. My beautified code ends up like this:
```
<li><a href="index.html">Home</a>
</li>
```

**Comment by Glavin001** [comment]
This is handled by [js-beautify](https://github.com/beautify-web/js-beautify). I recommend creating an issue for them and they will have a better idea of what to do. If there's anything I can do with Atom Beautify, such as update js-beautify dependency and/or add more options, let me know.

**Comment by Glavin001** [comment]
Any progress from js-beautify on this? I do not see a referenced issue on js-beautify I can take a look at.

**Comment by Glavin001** [comment]
Either [js-beautify](https://github.com/beautify-web/js-beautify) or [prettydiff](https://github.com/prettydiff/prettydiff) can be selected as beautifier to handle HTML. Hopefully one of those works well for you. If there are bugs, forward them over to their respective repositories for their team to resolve.
You can select beautifiers with `Language Config - <language> - Default Beautifier`. See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---html---default-beautifier for more documentation. 

You can trick Atom into updating Atom Beautify's dependencies, such as Pretty Diff, by uninstalling Atom Beautify and reinstalling it. Atom will install the latest version of Atom Beautify's dependencies, and you will have the most up-to-date version of Pretty Diff and be able to test these changes @prettydiff is working on.
