### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by operatorone** [Glavin001/atom-beautify#1890]
Hi there,

when I try to beautify my PHP code I always get this message.

> Could not find 'php-cs-fixer'. The program may not be installed.
> See php-cs-fixer installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
> Your program is properly installed if running 'which php-cs-fixer' in your Terminal returns an absolute path to the executable.

I checked it PHP-CS-Fixer is installed. Reinstalled it. Reinstalled ATOM etc.
It just can't find it at the default path. But Where to look for? Any idea?

Cheers, operatorone

**Comment by szeck87** [comment]
Try putting the path to php-cs-fixer under `Executables -> PHP-CS-Fixer`.  I'm guessing right now you have the path under `PHP` and the`PHP-CS-Fixer Path` field.

**Comment by szeck87** [comment]
@operatorone Any updates on this?

**Comment by phamthanhnghia** [comment]
**I fixed this.** You need uninstall **atom-beautify**
