### ISSUE TITLE
Vue nested templates not formatted

### ISSUE THREAD

**Issue by chavyleung** [Glavin001/atom-beautify#1892]
# Description

Vue nested templates not formatted

```
<template>
<div>
  <template>
  <div>
            <div>
      hello world
    </div>
  </div>
  </template>
</div>
</template>
```

# Expected Output

```
<template>
<div>
  <template>
  <div>
    <div>
      hello world
    </div>
  </div>
  </template>
</div>
</template>
```

# Actual Output

do noting

```
<template>
<div>
  <template>
  <div>
            <div>
      hello world
    </div>
  </div>
  </template>
</div>
</template>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug
https://gist.github.com/chavyleung/4bf0210f7fb3e03e5f868d4fe4d2ef13

**Comment by zhoujieluning** [comment]
I have the same issue
