### ISSUE TITLE
Refactor beautify on save to take advantage of onWillSave allowing async

### ISSUE THREAD

**Issue by szeck87** [Glavin001/atom-beautify#1895]
# Description

Referencing @Glavin001 's question here:  https://discuss.atom.io/t/best-way-to-change-the-texteditor-textbuffer-on-save-when-my-function-is-asynchronous/43531.  The `onWillSave` callback function now looks for a returned promise, and will not save the buffer until the promise is resolved.  Atom Beautify's beautify on save feature should make use of this.

This will require significant code changes of core atom-beautify code, but will result in performance improvements as well as less code.  This will also require users to be on Atom 1.21 or higher, so have to make sure package.json atom engine version is also updated.

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Other references:

https://atom.io/docs/api/v1.21.0/TextBuffer#instance-onWillSave
https://github.com/atom/atom/pull/14435#issuecomment-330990750
https://github.com/atom/text-buffer/pull/254

**Comment by Glavin001** [comment]
This would be huge!! Pull Requests very welcome!

@szeck87 would you be up for taking this on? If so, I will assign to you.

**Comment by szeck87** [comment]
Yep, I will put effort into this.
