### ISSUE TITLE
Deprecated Selectors

### ISSUE THREAD

**Issue by stramel** [Glavin001/atom-beautify#190]
From Atom's Deprecation Cop:

* **File:** menus/atom-beautify.cson
  * Use the `atom-workspace` tag instead of the `workspace` class.
  * Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by ffsantos92** [comment]
@stramel here is a pull request to fix deprecated selectors: https://github.com/Glavin001/atom-beautify/pull/187

**Comment by stramel** [comment]
:+1: Forgot to check PRs... -.-

**Comment by framerate** [comment]
Will this be pushed out soon? Trying to clear all my deprecation errors for my OCD :)

**Comment by Glavin001** [comment]
I want to make sure this push doesn't break anything while removing the deprecation warnings, so I'm going to give it a little more time and review it this weekend. Thank you all for your patients and interest and I hope to resolve all of these issues very soon.

**Comment by Glavin001** [comment]
Published to v0.21.3
