### ISSUE TITLE
uhtmanifest is a json file

### ISSUE THREAD

**Issue by MJBrune** [Glavin001/atom-beautify#1900]
# Description

This is a file apart of the Unreal Engine 4 stack. Trying to debug it with atom and was trying to simply beautify it with this add on.

The results of beautification are not what I expect: Indeed did not beautify because it could not realize the entire file was just json.

# Input Before Beautification

This is what the code looked like before:
https://gist.github.com/MJBrune/d3fd57d0c998e3551ae1bcd83fc45713

# Expected Output

The beautified code should have looked like this:
json lint did this: 
https://gist.github.com/MJBrune/07735057c84e54a5f93a316628408b7a

# Actual Output

The beautified code actually looked like this:
Same this as the original output. Not trying to clog up the ticket.

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

^ perfect
# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
https://gist.github.com/MJBrune/c92c4fb798cc4f1a0b2015378cc1d866
# Checklist

I have:
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly

Thanks for your time.

**Comment by prettydiff** [comment]
It looks like the debug file failed to correctly generate.  Which beautifier were you using?  I tried this in Pretty Diff's web tool and it does generate an error if the option "vertical" is used but either way it appears to beautify the entire file.  I also ran this through JS Beautifier's web tool and saw no errors.

**Comment by szeck87** [comment]
@MJBrune I noticed that the files are `.txt` in your first two gists.  Did you change the grammar within Atom for those files to be JSON instead of Plan Text (or whatever grammar it is exactly)?

**Comment by MJBrune** [comment]
Nah the .txt is from just copy and paste. I ran this through atom-beautifier json. The expected stuff is jsonlint.com.

**Comment by szeck87** [comment]
Right, but when you have the file/editor open with the json contents, do you have JSON selected as the language/grammar within Atom?  In the lower right, it looks like this:

![screen shot 2017-10-25 at 6 02 29 pm](https://user-images.githubusercontent.com/8315038/32027467-caae3028-b9ae-11e7-80ce-f82a105ce8cf.png)

**Comment by MJBrune** [comment]
Oh, right the issue is with the auto-detection of the file's format. So it shows as plain text and thus doesn't parse. Which is the original issue that uhtmanifest files are json files.

**Comment by szeck87** [comment]
Correct.  The other option is to use the command palette to specifically tell it to beautify json (type in beautify json into the search and Atom Beautify: Beautify Language Json will show up).
