### ISSUE TITLE
String replace issue in vue beautifier when script tag contains "$'"

### ISSUE THREAD

**Issue by Tmjk** [Glavin001/atom-beautify#1901]
# Description
"$'" is replaced with "</script>"
Problem seems to be the replace function in vue-beautifier.coffee line 53:
```
result = if beautifiedText then match.replace(replaceText, "\n#{beautifiedText.trim()}\n") else match
```
It looks like the same problem in https://stackoverflow.com/questions/36441837/bug-in-javascript-string-replace-with-replace-string

# Input Before Beautification

This is what the code looked like before:

```
<template></template>
<script>
let a = '$'
</script>
<style></style>
```

# Expected Output

The beautified code should have looked like this:

```
<template></template>
<script>
let a = '$'
</script>
<style></style>
```

# Actual Output

The beautified code actually looked like this:

```
<template></template>
<script>
let a = '$</script>
</script>
<style></style>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/Tmjk/e9bc8a66c6e9a7f4a57b0f52a3cad831

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by sgehrman** [comment]
Same problem Oct 2018.  How can I get this working?

**Comment by Tmjk** [comment]
@sgehrman 
This issue has closed, I think you might need to make a new issue if you care.
