### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by Pankajthakur335583** [Glavin001/atom-beautify#1902]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.30.5

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=407

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (/packages/atom-beautify/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:290:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:394:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -2:46.6.0 core:move-left (input.hidden-input)
  5x -2:45.6.0 core:move-right (input.hidden-input)
     -2:44.2.0 core:move-left (input.hidden-input)
  6x -2:43.3.0 core:backspace (input.hidden-input)
  4x -2:29.8.0 core:save (input.hidden-input)
     -0:51.8.0 atom-beautify:beautify-editor (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-react-snippets 0.2.2 
language-babel 2.73.0 
modern-react-snippets 0.3.0 
```

**Comment by szeck87** [comment]
What are you trying to do exactly?

At first glance, it looks like a firewall/proxy issue.  Try this:  Locate the `~/.atom/.apmrc` file and open it with a text editor.  Add a new line with this text:  `strict-ssl = false`.  Restart Atom and see if that makes a difference.

**Comment by szeck87** [comment]
@Pankajthakur335583 Have you had a chance to review my comment?

**Comment by nickdavies791** [comment]
When I try installing packages or themes I get a 407 error. 

`C:\WINDOWS\system32>apm install --check
Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.15/iojs-v1.6.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: tunneling socket could not be established, statusCode=407
gyp ERR! stack     at ClientRequest.onConnect (C:\Users\nick.davies\AppData\Local\atom\app-1.24.0-beta2\resources\app\apm\node_modules\tunnel-agent\index.js:166:19)
gyp ERR! stack     at ClientRequest.g (events.js:291:16)
gyp ERR! stack     at emitThree (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:194:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:395:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:176:18)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:134:10)
gyp ERR! stack     at TCP.onread (net.js:548:20)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\nick.davies\\AppData\\Local\\atom\\app-1.24.0-beta2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\nick.davies\\AppData\\Local\\atom\\app-1.24.0-beta2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.6.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure" "--proxy=http://xx.xx.xx.xx:1234/"
gyp ERR! cwd C:\Users\nick.davies\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
`
