### ISSUE TITLE
Please make a Visual Studio Code version of Atom Beautify

### ISSUE THREAD

**Issue by bgarrant** [Glavin001/atom-beautify#1905]
Atom rocks but sometimes we use VS Code as well.  Please consider making a VS Code port of this plugin!

**Comment by prettydiff** [comment]
We are working on it.  Please help us get there by contributing code.  https://github.com/Unibeautify/

**Comment by Glavin001** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/1737
