### ISSUE TITLE
Disable End with Comma for single lines

### ISSUE THREAD

**Issue by jbcoder** [Glavin001/atom-beautify#1908]
# Description

When I end with a comma, I would expect that single line arrays/objects would not need an ending comma. However, commas are entered anyways.

# Input Before Beautification

This is what the code looked like before:

```
import { alertColor, alertness } from './helpers';
```

# Expected Output

The beautified code should have looked like this:

```
import { alertColor, alertness } from './helpers';
```

# Actual Output

The beautified code actually looked like this:

```
import { alertColor, alertness, } from './helpers';
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor` with End with Comma set to true
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.

**Comment by szeck87** [comment]
Can you update the issue with what language you have selected in Atom and which beautifier you are using?

**Comment by jbcoder** [comment]
It was happening for a couple days and then it stopped. It's not reproducible. Closing.
