### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by andyday** [Glavin001/atom-beautify#191]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Andy\AppData\Local\atom\app-0.175.0\resources\app\src\atom.js:55:11)
LoadingView.module.exports.LoadingView.show (c:\Users\Andy\.atom\packages\atom-beautify\lib\loading-view.coffee:38:11)
```

**Comment by Glavin001** [comment]
Published to v0.21.3
