### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by rakafaProg** [Glavin001/atom-beautify#1912]
# Description

when using install on atom to install the package it just get stuck there, 
and takes down the cpu..

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by szeck87** [comment]
Are you behind a firewall/proxy?  If so, that tends to slow down Atom package installations, particularly those with a lot of dependencies like Atom Beautify.  It's not really "stuck", it's just slow.

**Comment by rakafaProg** [comment]
Thanks
I kind of gave up on this..
will buetify my code myself ;)
