### ISSUE TITLE
PHP-cs-fixer not beautifying code

### ISSUE THREAD

**Issue by amperand** [Glavin001/atom-beautify#1922]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:
A section of the code only...
```
<footer id="news" class="jumbo reg-text" role="complementary" style="clear:both;">
	<section class="wrapper">
		<h1 class="align-center newsandeventsheader">
			<?php if (is_front_page()) {
    echo 'News &amp; Events';
} else {
    echo 'Upcoming Events';
} ?>
```
Spacing is still all over the place.

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/amperand/0e85e7843b25f16f76ca2b08c6dd70d9

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Can you update the settings to put the path to the php executable as well?  Settings > Executables > PHP

**Comment by brutalcrozt** [comment]
i also have same issue, but specifically i use Phpcbf `3.1.0` . Since use 2 space is not supported by php-cs-fixer, which is outrage me. I do specify the option via [cli](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#setting-configuration-options), verified by `phpcs --config-show` tab_width: 2.  Additional info is i use windows and composer for this case.
