### ISSUE TITLE
Installing “atom-beautify@0.30.6” failed.

### ISSUE THREAD

**Issue by TishGitHub** [Glavin001/atom-beautify#1925]
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.15/iojs-v1.6.15.tar.gz
gyp http 200 https://atom.io/download/electron/v1.6.15/iojs-v1.6.15.tar.gz
gyp http GET https://atom.io/download/electron/v1.6.15/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.6.15/win-x64/iojs.lib
gyp http GET https://atom.io/download/electron/v1.6.15/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.15/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.6.15/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.15/win-x64/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Tish\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Tish\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.6.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\Tish\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
What could cause this? I'm running latest Atom with Windows 10 Pro FCU.

**Comment by szeck87** [comment]
Can you try running `apm clean` from your terminal?

**Comment by TishGitHub** [comment]
thanks, it worked!

**Comment by codewithkaranjeswani** [comment]
Its not working for me! Tried apm clean, still getting same error message:

> ```
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.4.0
> gyp info using node@6.9.5 | win32 | x64
> gyp http GET https://atom.io/download/electron/v1.6.15/iojs-v1.6.15.tar.gz
> gyp http 200 https://atom.io/download/electron/v1.6.15/iojs-v1.6.15.tar.gz
> gyp http GET https://atom.io/download/electron/v1.6.15/SHASUMS256.txt
> gyp http GET https://atom.io/download/electron/v1.6.15/win-x64/iojs.lib
> gyp http GET https://atom.io/download/electron/v1.6.15/win-x86/iojs.lib
> gyp http 200 https://atom.io/download/electron/v1.6.15/SHASUMS256.txt
> gyp http 200 https://atom.io/download/electron/v1.6.15/win-x86/iojs.lib
> gyp http 200 https://atom.io/download/electron/v1.6.15/win-x64/iojs.lib
> gyp WARN install got an error, rolling back install
> gyp ERR! install error 
> gyp ERR! stack Error: read ECONNRESET
> gyp ERR! stack     at exports._errnoException (util.js:1022:11)
> gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Users\\Tish\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Tish\\AppData\\Local\\atom\\app-1.21.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.6.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
> gyp ERR! cwd C:\Users\Tish\.atom
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> ```
> What could cause this? I'm running latest Atom with Windows 10 Pro FCU.
