### ISSUE TITLE
Conditional operator: Space before : is being removed

### ISSUE THREAD

**Issue by derwaldgeist** [Glavin001/atom-beautify#1927]
This is probably an issue with the latest PrettyDiff update.

Before beautification:

```js
const obj = {
  prop: isTrue ? alternativeA : alternativeB
}
```

After:

```js
const obj = {
  prop: isTrue ? alternativeA: alternativeB
}
```

The space between `alternativeA` and the following colon is missing, which is marked as an error by `eslint`.

**Comment by derwaldgeist** [comment]
Update: This also happens if the condition is not part of an object, like here:

`const result = isTrue ? _.find(obj, conditionFn) : alternativeObj;`

**Comment by prettydiff** [comment]
Looks like a Pretty Diff defect as I can reproduce this behavior.

**Comment by derwaldgeist** [comment]
Thanks, that was quick. Will open this issue in the Pretty Diff repo then.
