### ISSUE TITLE
Phpcbf tries to write temporary file to tmp/ instead of /tmp ?

### ISSUE THREAD

**Issue by fletanoux** [Glavin001/atom-beautify#1932]
# Description

Complely unable to make atom-beautify works with phpcbf. I traced back the problem to phpcbf trying to write temporary files to `tmp/{nameOfTempFile}. php` and being unable to do so because the folder doesn't exist. The  involved function can be found at "quizlabs/php_codesniffer/src/Reports/Cbf.php" on line 82.

I've not checked who set up that folder path and where but since phpcbf is working in standalone mode, i guess the problem is in atom-beautify, and that's why i've created the issue here.

As a temporary fix i've simply added a `/` in the file_put_contents function so that it writes in the right folder, and it works like a charm. But it's not a sustainable solution in the long term.

# System info

* OS : Linux, Kubuntu
* Atom : 1.21
* Atom-beautify : 0.30.6 (but that's not a new problem for me)
* Phpcbf : 3.0 and 3.1
 
# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Link to debug gist

https://gist.github.com/fletanoux/251e1bf4a2193f0fc2e73bc9fefe959c#file-debug-md

# Checklist

I have:
- [*] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [*] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [*] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [*] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Hi @fletanoux, at first glance I can't determine what the problem might be.  I tried it from my Mac with the Docker image (which is on phpcbf 3.1.1) One thing I do notice, which may not be making any difference, is that your `ruleset.xml` is named `rules1et.xml`.  Is that file being used in standalone mode at all?

Can you post what you run in your terminal when running PHPCBF as a standalone?

**Comment by fletanoux** [comment]
Oh sorry i didn't posted the right debug. 

I messed a little bit with the settings to determine what may not be working and purposely added a typo in the filename for my ruleset, to see if the problem may come from here. You can also see some strange echo near the end (bibambom) as well that i used as debugging purpose..

But the problem was not coming from there, and i immediatly changed the setting back to what they were previously. Sadly i posted the wrong debug, but aside from the echo and that ruleset path nothing else changed.

When i'm using phpcbf as a standalone i use the command : `vendor/bin/phpcbf src/ features/  --standard=ruleset.xml`. Unlike atom-beautify which use the global composer package, here i'm using my project dependency, since i'm mainly using it ina  pre-commit script.

But obviously i also tried settings atom-beautiful to use my project's phpcbf, and using the global one as standalone.  Both package work as a standalone, none work with atom-beautify.

I'm pretty sure, the problem come from whom is setting the path to the temporary folder. But i didn't find anything, even if i need to admit i didn't search for long.

Thanks for your answer already, if you have some time to search further it would gladly be appreciated. But if i'm the only one with that problem, don't waste your time :).

**Comment by szeck87** [comment]
OK, just making sure that's not the problem.

It's actually atom-beautify that creates the temp file, PHPCBF just reads it.  It uses node's `[os.tmpdir()](https://nodejs.org/docs/latest-v8.x/api/os.html#os_os_tmpdir)` method to get the operating system's default directory for temporary files and places the file there (I forget why temp files are needed for executables, need to look into more).

It's very possible the temp file is the cause, but I'm curious what the second stack trace is about with the undefined variable.  I can't remember how PHP stack traces go exactly, but does the second stack trace cause the first in this case?

**Comment by fletanoux** [comment]
`os.tmpdir()` returns `/tmp` so what is expected.

Otherwise the stack trace about that undefined variable is probably caused by the first one yes but i'm not entirely sure since it's a pain in the ass to debug. 

The variable comes from another file which is included into the class method (I wanted to puke when i saw that), but even worse, the file to include is not a constant, it's a fucking variable (And that's when i puked).

I don't have time to debug that right now at work (and i've got an entirely different setup at home, so not sure i will even face the same problem). But next week i will have more time so see what's up with that spaghetti code, and will post here the result of what i found.

**Comment by szeck87** [comment]
What is line 679 in your install? Is it this by chance: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Runner.php#L679

**Comment by Glavin001** [comment]
Applicable code:
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/phpcbf.coffee#L59
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L106-L120

I wonder if any other users experiencing this issue or only @fletanoux ?
