### ISSUE TITLE
High CPU & RAM usage when beautifying Coffeescript with regex

### ISSUE THREAD

**Issue by DervishD** [Glavin001/atom-beautify#1933]
First of all, I'm sorry but I can't provide a debug.md of this issue because when generating the debug report with the Coffeescript file causing the problem Atom eats so much CPU and RAM that my system is unusable and I have to kill the editor.

This said, I can try to provide any information you need, @Glavin001, in order to debug this issue if you can't reproduce the problem. I've tried like ten times to generate debug.md, to no avail. Atom looks dead, eating resources, to the point to have to force a restart in my computer.

I'm running `atom-beautify 0.30.6` on `atom 1.21.2 x64` on Windows 10 x64.

The problem happens when trying to beautify a Coffeescript file containing ONLY the following:
```
/^/
```

Of course it also happens when such a regex or derivative appears in the text to beautify. I discovered it by using a longer source code, but the Coffeescript above is the bare minimum I need to reproduce the problem.

Thanks A LOT for you beautifier!

# Steps to Reproduce

1. Put that `/^/` regex in `whatever.coffee` and load it into Atom.
2. Run command `Atom Beautify: Beautify Editor`
3. Look how the CPU usage rises and RAM get's eaten.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Looks like an issue with [coffee-fmt](https://github.com/sterpe/coffee-fmt).

**Comment by DervishD** [comment]
You're right, @szeck87 thanks a lot for pointing to this :)
If you don't mind, I'll link the issue here for future reference, for people searching for this problem.
[https://github.com/sterpe/coffee-fmt/issues/16](url)
