### ISSUE TITLE
Comment slashes inside comments are removed

### ISSUE THREAD

**Issue by derwaldgeist** [Glavin001/atom-beautify#1936]
Maybe also a side-effect of the latest PrettyDiff:

Before:
```js
// imagePort: 80, // (default: 80, some images EXPOSE different ports)
```

After:
```js
// imagePort: 80,  (default: 80, some images EXPOSE different ports)
```

This makes it quite cumbersome to temporarily disable code lines and keep their comments.

This especially gets annoying when commenting out whole sections of your code, e.g. for temporary testing:

Before commenting out:

```js
// my comment
const foo = bar;
```

After commenting out this section (but before beautification):

```js
// // my comment
// const foo = bar;
```

After beautification:
```js
//   my comment
// const foo = bar;
```

If you then remove the comments again (e.g. by using Cmd-Shift-7 in Atom, you get invalid code:

```js
my comment
const foo = bar;
```

For me, this auto-deletion of additional slashes is not desirable.

BTW: Although the // are being removed, additional space around them are kept.

**Comment by Glavin001** [comment]
@prettydiff has created an issue over at https://github.com/prettydiff/prettydiff/issues/500 . Please subscribe there.
