### ISSUE TITLE
php-cs-fixer not working with windows

### ISSUE THREAD

**Issue by Med-Seif** [Glavin001/atom-beautify#1939]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Med-Seif** [comment]
Even after changing config to the new "Executables>PHP-CS-Fixer>Binary/Script Path", the fixer didn't work! ..Is thaer a problem with .phar files?
Thank you

**Comment by szeck87** [comment]
Can you please provide a debug gist?  Go to Packages > Atom Beautify > Debug.  It will open a new pane with output, please paste that output into a gist file and attach a link to it in this ticket.

**Comment by Med-Seif** [comment]
The problem is with some options that become deprecated in php-cs-fixer.phar v2, like 'allow-risky'
I work with an old version of PHP (5.3.x) and I shouldn't have updated atom-beautify.

Thank you
