### ISSUE TITLE
Where to config `Python autopep8 path`?

### ISSUE THREAD

**Issue by zachguo** [Glavin001/atom-beautify#194]
I cannot find it in package settings page (Atom v0.175). 
Should I put it in the `.jsbeautifyrc`? Could anyone give me an example? Thanks!

**Comment by Glavin001** [comment]
I would recommend setting the path from Atom Beautify Package settings.
See https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L273-L277 and https://github.com/Glavin001/atom-beautify/blob/master/lib/langs/python-beautify.coffee#L5
It will be called `python_autopep8_path`.

**Comment by zachguo** [comment]
Got it, I should put it in `config.cson`. Thanks!
It would be better if documentation include this.

**Comment by Glavin001** [comment]
There are many, many options to be documented (see https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L68-L384 ) so I opted to add documentation and more details in with each of the options. So at any time you can view your Atom Beautify Package settings and see those options. Improving documentation ( #58 ) is on my list of TODOs. Thanks for asking questions and helping me understand what is missing and needs improvement!

**Comment by zachguo** [comment]
Sounds great! Thank you for building and maintaining such an awesome package.

**Comment by fahd** [comment]
that atom-beautify config.cson file document you have linked is dead. any way to view it again? I have to manually add my path for autopep8 as well

**Comment by augaug** [comment]
I too apparently need to manually add this path to autopep8, I'm assuming to the config.cson, how do I do this?

**Comment by Glavin001** [comment]
It doesn't look like `autopep8` beautifier is configurable right now: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/autopep8.coffee#L18

This is something I'd like to address in a future release. However, if your `PATH` environment variable is configured properly it should automatically detect `autopep8` without changing Atom-Beautify's code itself.

**Comment by rjoomen** [comment]
Fedora installs `autopep8` for Python 3 as `python3-autopep8`. After fixing the hardcoded command in `autopep8.coffee` and rebuilding, the beautifying works.
Maybe this strengthens the case for a configurable autopep8 command?
