### ISSUE TITLE
atom-beautify + uncrustify crashes atom in windows 10

### ISSUE THREAD

**Issue by Piussa** [Glavin001/atom-beautify#1940]
Prerequisites

    [X ] Put an X between the brackets on this line if you have done all of the following:
        Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
        Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
        Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
        Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
        Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

Description

Trying to beautify causes atom to crash
Steps to Reproduce

    Open .c file in atom
    Select packages>atom beautify>beautify
    Crash

Expected behavior: Beautification of .c file

Actual behavior: Crash

Reproduces how often: Every single time
Versions

Atom : 1.22.0
Electron: 1.6.15
Chrome : 56.0.2924.87
Node : 7.4.0
Additional Information

Use of atom-beautify package + uncrustify

**Comment by Piussa** [comment]
reinstalled everything except windows, i.e. atom uncrustify and atom-beautify

**Comment by szeck87** [comment]
Can you describe what happens when it crashes?  Which version of Uncrustify are you using?

**Comment by Piussa** [comment]
So beautify starts running with the blue wheel saying beautifying and then pops up another window saying atom has crashed asking if I want to reload, close or something else! I'm on my phone so i can't check my uncrustify version but I used this link to download it https://sourceforge.net/projects/uncrustify/files/latest/download

**Comment by Piussa** [comment]
Nothing happens to my file or atom in general it just crashes

**Comment by Piussa** [comment]
so i solved my problem by uninstalling uncrustify and beautify and installing uncrustify through ubuntu's bash on windows

**Comment by Piussa** [comment]
started working now dont know what changed

**Comment by szeck87** [comment]
OK, good to hear.
