### ISSUE TITLE
atom-beautify not allowing to save file when there is a syntax error on new update

### ISSUE THREAD

**Issue by jithinlal** [Glavin001/atom-beautify#1948]
# Description

The atom-beautify package is not allowing my file to be saved, if there is any syntax error in my PHP file.

**Comment by bitgijs** [comment]
same!

**Comment by johanvanhelden** [comment]
Might be the same as: https://github.com/Glavin001/atom-beautify/issues/1949

With the difference being that mine does not save at all. Even if there are no errors.

**Comment by Jbz797** [comment]
Same here !

**Comment by jithinlal** [comment]
I mean is this an error in PHP, or any kind of language?

**Comment by eqfox** [comment]
use eslint-fixer same problem~

**Comment by Glavin001** [comment]
Closing as a duplicate of https://github.com/Glavin001/atom-beautify/issues/1949 , since it has more 👍 s.

**Comment by Glavin001** [comment]
Bug in https://github.com/Glavin001/atom-beautify/pull/1924

**Comment by Glavin001** [comment]
Published the fix recommended by @exoticorn : https://github.com/Glavin001/atom-beautify/issues/1949#issuecomment-346347191

Patch version 0.30.8

Please try and let me know!

**Comment by johanvanhelden** [comment]
Cheers @Glavin001 !

Just updated and everything works great again - it saves with and without beautifying.

**Comment by Glavin001** [comment]
**Update**: Please try v0.30.9

**Comment by jithinlal** [comment]
Its done now, working smoothly.
