### ISSUE TITLE
Use Allman style indentation for beautification of CSS, PHP and any

### ISSUE THREAD

**Issue by gusbemacbe** [Glavin001/atom-beautify#1952]
# Description

I do not like the traditional style of beautification. 

# Input Before and After Beautification

This is what the code looked like before:

```
while (x == y) {
    something();
    somethingelse();
}
```

I really hate the KNF style.

# Expected Output

The beautified code shall have looked like this in the Allman style:

```
while (x == y)
{
    something();
    somethingelse();
}
```

You shall add feature, allowing us to choose one of favourite six indentation styles — GNU, Hortsmann, KNF, K&R, Pear and Whitemsiths. 

# Sources
* [Indentation style](https://en.wikipedia.org/wiki/Indentation_style)
* [PHP Beautifier](http://phpbeautifier.com/)
* [PHP Formatter](http://beta.phpformatter.com/)

**Comment by gusbemacbe** [comment]
Nobody answered since November 2017...

**Comment by gusbemacbe** [comment]
It is shameful that @Glavin001 ignored it.

**Comment by szeck87** [comment]
Which language exactly are you looking to have it for? Look for an option named *Brace Style* and change it to expand.

**Comment by gusbemacbe** [comment]
I want to apply the Allman style to CSS, JavaScript and PHP, @szeck87.

**Comment by szeck87** [comment]
For JavaScript, set the Brace Style option to Expand and the beautifier to JS Beautify, like the below.  I'll have to look into CSS and PHP a bit more.

![screen shot 2018-02-28 at 12 57 14 pm](https://user-images.githubusercontent.com/8315038/36806905-24607a32-1c87-11e8-9926-90c648215d29.png)

**Comment by szeck87** [comment]
@gusbemacbe I'm still trying to figure out CSS and PHP.  I'm having difficulties trying PHP because I can't get PHP-CS-Fixer to read my config file.  They do look to have an option that you can use named "quotes", as seen here: https://github.com/FriendsOfPHP/PHP-CS-Fixer.

**Comment by Glavin001** [comment]
> It is shameful that @Glavin001 ignored it.

I apologize, I have been busy.

> I want to apply the Allman style to CSS, JavaScript and PHP,

The supported options are documented here: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md

If you look at the docs you will find Atom-Beautify does not explicitly support using Allman style indentation, or any other styles listed at https://en.wikipedia.org/wiki/Indentation_style#Brace_placement_in_compound_statements 

Atom-Beautify wraps beautifiers for each language. You asked for `CSS`, `JavaScript`, and `PHP`.

If you go to https://github.com/Glavin001/atom-beautify/#language-support you will see the list of supported languages and their respective supported beautifiers.

**CSS**: JS Beautify, CSScomb, Prettier, Pretty Diff, SassConvert
**JavaScript**: JS Beautify, ESLint Fixer, JSCS Fixer, Prettier, Pretty Diff
**PHP**: PHP-CS-Fixer, PHPCBF, hh_format

Each of these beautifiers are supported by different maintainers and support different configuration options.

For `JS Beautify`, the option `Brace style`, as @szeck87  suggests may be what you are looking for. I recommend you reach out to https://github.com/beautify-web/js-beautify to ask for `JavaScript` language support. Repeat for other beautifiers for other languages.

Once those beautifiers support a configuration option for `Allman style indentation`, please feel free to submit a Pull Request to Atom-Beautify adding this support. We can assist you if you have any questions.

At the current time, @szeck87 and I are working on https://github.com/Unibeautify/unibeautify which is a complete rewrite and the future of Atom-Beautify. Therefore, feature requests like these are unlikely to be implemented by us. Please submit a Pull Request adding these features and let us know if you need any assistance.

**Comment by gusbemacbe** [comment]
> **CSS:** JS Beautify, CSScomb, Prettier, Pretty Diff, SassConvert
> **JavaScript:** JS Beautify, ESLint Fixer, JSCS Fixer, Prettier, Pretty Diff
> **PHP:** PHP-CS-Fixer, PHPCBF, hh_format

None of them supported apply Allman style for CSS and PHP, except `CSSComb` (the original and not `atom-beautify`). Tested all in Atom, Brackets, Sublime Text and VSCode. Only `CSSComb` worked on Atom and VSCode. 

* I couldn't figure how to apply Allman style for `atom-beautify` to format PHP, using `PHP-CS-Fixer`. I do not remember a plugin which used to support applying Allman style for PHP.
* `CSSComb` (original) worked perfectly to apply Allman style for CSS, in spite of it not being able to format CSS inside HTML, JavaScript, PHP and Python files because this plugin applies only to CSS files.
* As `atom-beautify` comes with `CSSComb` installed **[unless the original `CSSComb` need[s] to be installed]**, didn't support applying Allman style to CSS file[s] if it has or they have `:root` which blocks your plugin from formatting. But strangely the original `CSSComb` was able of formatting the CSS file which contains `:root`. The `atom-beautify` with `CSSComb` would be able to format if `:root` is omitted or isn't present there.

**Comment by szeck87** [comment]
@gusbemacbe Unibeautify will start to address issues with different types of code in the same file, in your case which is very common, CSS inside of an HTML file.

One thing you can do right now to beautify CSS in non CSS files is this:

1. Highlight the text you want to beautify
2. Open the command palette (Cmd + Shift + P on Mac)
3. Search for `Atom Beautify: Beautify Language Css` and hit enter when you find it

That should only process what you highlight, so CSSComb only beautifies CSS and not the HTML.

**Comment by szeck87** [comment]
That's what I would do, format the whole file as HTML or PHP first, even though that will also format in-file CSS to a point.  Then highlight the CSS specifically and beautify that.  I know it's a two-step process, but it's the only way right now.
