### ISSUE TITLE
Beautifiying prevents tab switching when autosave is activated

### ISSUE THREAD

**Issue by ejpcmac** [Glavin001/atom-beautify#1955]
## Description

When I have the *Beautify on Save* option activated alongside *autosave* and click to another tab before saving, the beautification process prevents tab switching. I am not sure it this comes from `atom-beautify` or from Atom itself.

**Edit: I can’t reproduce this issue anymore. This is quite strange, as I did nothing.**
**Edit 2: I can reproduce it again and edit this message to precise the case (only from foo.h to foo.c).**

## Input Before Beautification

*Not applicable.*

## Actual Output

*Not applicable.*

## Steps to Reproduce

1. Activate the *Beautify on Save* option.
2. Activate the `autosave` package.
3. Open a `foo.c` and `foo.h` files in two tabs.
4. Edit the `foo.h` file.
5. Click on the other tab.

## Actual result

The beautification process works and the file is saved, but the tab is not switched. However, it works correctly if the `.h` and `.c` doesn’t start with the same name.

## Expected result

The clicked tab should be activated.

## Debug

*Nothing to see in the console.*

## Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Can you provide a link to the autosave package you're using?

**Comment by ejpcmac** [comment]
@szeck87 This is the core `atom/autosave` package: https://github.com/atom/autosave

**Comment by szeck87** [comment]
So it only happens when the files have the same name (ignoring extension)?

**Comment by ejpcmac** [comment]
Yes. And only when editing the `.h` and then clicking the `.c`.

**Comment by szeck87** [comment]
Ok, I'll look at this when I get back home in a couple days. Was this working up until Atom Beautify 0.30.9?

My guess as order of events:

1. User makes changes to file and clicks another file
2. Autosave kicks in and tells Atom to save it
3. Atom Beautify is told a save is being requested, and beautifies the file before it's saved
4. Atom Beautify returns a resolved promise and Atom saves

So there's a disconnect somewhere when files are the same name.

**Comment by ejpcmac** [comment]
> Was this working up until Atom Beautify 0.30.9?

I don’t know. I enabled *Beautify on Save* on Thursday evening, used it a bit but not a full day of work. Then, *Beautify on Save* was broken yesterday morning and working back in 0.30.9. I noticed the problem only since this morning. Sorry if I can’t help about that :(

**Comment by ejpcmac** [comment]
Even more strange: the problem does not occur on all files. On files named `led.c/h` and `blink.c/h` I have the problem. On another named `ihm.c/h`, no problem. The issue is reproducible after restarting Atom and closing / re-opening the files.

**Comment by szeck87** [comment]
Can you uninstall Atom Beautify and install 0.30.6?  `apm install atom-beautify@0.30.6` and try?

**Comment by ejpcmac** [comment]
Ok, so:

1. The bug is 100% reproductible on the specific files in the project where the problem occurs on version 0.30.6.
2. The bug does not occur on the very first tab switch after Atom startup.
3. If there was another tab switch before trying to reproduce the bug, it occurs.
4. The bug is not reproductible if I copy the project directory elsewhere and open it there.

It seems hard to debug, so :( But it remains 100% reproductible on the very files on that very project at its location, even when I close and re-open them.
