### ISSUE TITLE
beautify php not working

### ISSUE THREAD

**Issue by b3nhysteria** [Glavin001/atom-beautify#1958]
dear all,

i want to asking something about atom beautify,

currently using php for dev web. not show any error, i installed php cs fixer using brew,

even i press ctrl + alt/option + b, it still ugly.. some body can give me a hint why i cant beautify this script? thank you

here is my script in 
https://imgur.com/w8G2Ipb

and my setting 
https://imgur.com/biY7Srt

my script 
`<?php

/*
  |--------------------------------------------------------------------------
  | API Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register API routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | is assigned the "api" middleware group. Enjoy building your API!
  |
 */

Route::group([
    "prefix" => "v1.0",
    "namespace" => "V1_0",
    "middleware" => "version.api.v1_0"], function () {
        Route::group([
        "prefix" => "client/service",
        "namespace" => "Client\Service"], function () {
            Route::post("register", [
            "as" => "v1_0.client.service.register",
            "uses" => "AuthController@create"
        ]);
            Route::post("login", [
            "as" => "v1_0.client.service.login",
            "uses" => "AuthController@login"
        ]);
            Route::post("forgot", [
            "as" => "v1_0.client.service.forgot",
            "uses" => "AuthController@resetPassword"
        ]);
            Route::group(["middleware" => ["jwt.auth"]], function () {
                Route::post("logout", [
                "as" => "v1_0.client.service.logout",
                "uses" => "AuthController@logout"
            ]);
            });
            Route::group([
            "prefix" => "profile",
            "middleware" => ["jwt.auth"]], function () {
                Route::post("update", [
                "as" => "v1_0.client.service.profile.update",
                "uses" => "ProfileController@update"
            ]);
                Route::post("get", [
                "as" => "v1_0.client.service.profile.get",
                "uses" => "ProfileController@get"
            ]);
            });
            Route::group([
            "prefix" => "board",
            "middleware" => ["jwt.auth"]], function () {
                Route::post("create", [
                "as" => "v1_0.client.service.board.create",
                "uses" => "BoardController@create"
            ]);
                Route::post("update", [
                "as" => "v1_0.client.service.board.update",
                "uses" => "BoardController@update"
            ]);
                Route::post("list", [
                "as" => "v1_0.client.service.board.list",
                "uses" => "BoardController@get"
            ]);
                Route::post("detail", [
                "as" => "v1_0.client.service.board.detail",
                "uses" => "BoardController@getDetail"
            ]);
            });
            Route::group([
            "prefix" => "card",
            "middleware" => ["jwt.auth"]], function () {
                Route::post("create", [
                "as" => "v1_0.client.service.card.create",
                "uses" => "CardController@create"
            ]);
                Route::post("update", [
                "as" => "v1_0.client.service.card.update",
                "uses" => "CardController@update"
            ]);
                Route::post("delete", [
                "as" => "v1_0.client.service.card.delete",
                "uses" => "CardController@delete"
            ]);
                Route::post("comment", [
                "as" => "v1_0.client.service.card.comment",
                "uses" => "CardController@comment"
            ]);
                Route::post("listbyboard", [
                "as" => "v1_0.client.service.card.byboard",
                "uses" => "CardController@getByBoard"
            ]);
                Route::post("listall", [
                "as" => "v1_0.client.service.card.list",
                "uses" => "CardController@getAll"
            ]);
                Route::post("detail", [
                "as" => "v1_0.client.service.card.detail",
                "uses" => "CardController@getDetail"
                ]);
            });
            Route::group([
            "prefix" => "task",
            "middleware" => ["jwt.auth"]], function () {
                Route::post("create", [
                "as" => "v1_0.client.service.task.create",
                "uses" => "TaskController@create"
            ]);
                Route::post("update", [
                "as" => "v1_0.client.service.task.update",
                "uses" => "TaskController@update"
            ]);
                Route::post("delete", [
                "as" => "v1_0.client.service.task.delete",
                "uses" => "TaskController@delete"
            ]);
                Route::post("comment", [
                "as" => "v1_0.client.service.task.comment",
                "uses" => "TaskController@comment"
            ]);
                Route::post("list", [
                "as" => "v1_0.client.service.task.list",
                "uses" => "TaskController@get"
            ]);
                Route::post("listall", [
            "as" => "v1_0.client.service.task.listall",
            "uses" => "TaskController@getAll"
        ]);
                Route::post("detail", [
                "as" => "v1_0.client.service.task.detail",
                "uses" => "TaskController@getDetail"
            ]);
            });
            Route::group([
            "prefix" => "member",
            "middleware" => ["jwt.auth"]], function () {
                Route::post("create", [
                "as" => "v1_0.client.service.task.create",
                "uses" => "TaskController@create"
            ]);
            });
        });
    });
`

**Comment by catscarlet** [comment]
Did you set up PHP-CS-Fixer? I saw your PHP-CS-Fixer Path is empty.

And please use **markdown syntax**. Don't just paste your code directly.

**Comment by MitaiGit** [comment]
какая то не понятная хренатня этот пакет...
