### ISSUE TITLE
wrong empty objects in new line

### ISSUE THREAD

**Issue by matteszk** [Glavin001/atom-beautify#196]
Similar problem seen elsewhere, so I'll [link to that](https://github.com/beautify-web/js-beautify/issues/582).

But essentially, an item like 
```javascript
var o = someObj || {}; 
```
Gets formatted to a new line, instead of remaining on the same one:
```javascript
var o = someObj || 
{}; 
```

**Comment by Glavin001** [comment]
Atom Beautify uses js-beautify fo JavaScript beautification. Once that related issue that you linked has been resolved, let me know. Thanks.

**Comment by Glavin001** [comment]
Closing this as it [is an issue with js-beautify](https://github.com/beautify-web/js-beautify/issues/582).
