### ISSUE TITLE
Whitespace options should have named options

### ISSUE THREAD

**Issue by davidenglishmusic** [Glavin001/atom-beautify#1960]
More an improvement than a bug. It would be ideal if options for whitespace would use option names instead:

<img width="861" alt="screen shot 2017-11-26 at 11 23 26 am" src="https://user-images.githubusercontent.com/4421670/33241479-4e3b1d6a-d29c-11e7-95b6-3c5f213376b9.png">

ie. Spaces and Tabs instead of ___ and ___

**Comment by Glavin001** [comment]
Good point! 👍 

Pull Requests welcome!

**Comment by Glavin001** [comment]
This has been fixed in Unibeautify: https://unibeautify.com/docs/option-indent-style.html

@szeck87 is working on migrating Atom-Beautify to use Unibeautify.
