### ISSUE TITLE
ReactJS automatically assigns a value to empty prop with the name of the prop itself

### ISSUE THREAD

**Issue by tommycarpi** [Glavin001/atom-beautify#1963]
# Description

In ReactJS when you use a component that takes a prop without value, the beautifier automatically assigns to that props a string containing the name of the props itself.

# Input Before Beautification

This is what the code looked like before:

`<div propWithoutValue propWithValue="a value">test</div>`

# Expected Output

The beautified code should have looked like this:

`<div propWithoutValue propWithValue="a value">test</div>`

# Actual Output

The beautified code actually looked like this:

`<div propWithoutValue="propWithoutValue" propWithValue="a value">test</div>`

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by tommycarpi** [comment]
Yes, it is still an issue.

**Comment by szeck87** [comment]
@tommycarpi which beautifier are you using?

**Comment by tommycarpi** [comment]
<img width="740" alt="screen shot 2018-01-29 at 22 56 22" src="https://user-images.githubusercontent.com/10156527/35536607-ad8b55b8-0547-11e8-81c9-1ef5e3f066e2.png">

for JS

**Comment by szeck87** [comment]
Can you open the settings for atom-beautify and scroll down to JSX and expand that?  It should have a default beautifier selected.

**Comment by tommycarpi** [comment]
The default beautifier is **Pretty Diff**, should I switch to **JS Beautify**?

**Comment by szeck87** [comment]
You can give that a try yes.  @prettydiff any thoughts on this?

**Comment by megantaylor** [comment]
i'm also seeing this with Pretty Diff, which I otherwise prefer to JS Beautify.

**Comment by PrajwalK** [comment]
Any update on this issue guys?

**Comment by LucasLagrimante** [comment]
The problem remains. Could not have an option in the settings for this?

**Comment by prettydiff** [comment]
This is fixed in the latest version of Pretty Diff.  We just need to get the latest version of Pretty Diff into the application.
