### ISSUE TITLE
Install failed atom-beautify@0.30.9

### ISSUE THREAD

**Issue by MiniZagGi** [Glavin001/atom-beautify#1966]
# Description
When I try to install it. It fails and outputs this.
Installing “atom-beautify@0.30.9” failed.
```
> coffee-script@1.12.8 postinstall C:\Users\math438m\AppData\Local\Temp\apm-install-dir-1171030-5928-f4e4is.cvn0442t9\node_modules\atom-beautify\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

C:\Users\math438m\AppData\Local\Temp\apm-install-dir-1171030-5928-f4e4is.cvn0442t9
`-- (empty)


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[eval]:1
'if
^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\math438m\AppData\Local\Temp\apm-install-dir-1171030-5928-f4e4is.cvn0442t9\package.json'
npm WARN apm-install-dir-1171030-5928-f4e4is.cvn0442t9 No description
npm WARN apm-install-dir-1171030-5928-f4e4is.cvn0442t9 No repository field.
npm WARN apm-install-dir-1171030-5928-f4e4is.cvn0442t9 No README data
npm WARN apm-install-dir-1171030-5928-f4e4is.cvn0442t9 No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\math438m\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\math438m\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\math438m\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\math438m\\.atom\\.apmrc" "install" "C:\\Users\\math438m\\AppData\\Local\\Temp\\d-1171030-5928-o1ufzd.7opeva38fr\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coffee-script@1.12.8 postinstall script 'node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coffee-script package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coffee-script
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coffee-script
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\math438m\AppData\Local\Temp\apm-install-dir-1171030-5928-f4e4is.cvn0442t9\npm-debug.log
npm ERR! code 1
```
# Steps to Reproduce

When trying to install.

# Checklist

I have:
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Tried to run Atom as admin when installing
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.

**Comment by kevsler** [comment]
Same here :)

**Comment by NeoMili** [comment]
Same here ...

**Comment by theDyingMountain** [comment]
i also have the same problem

**Comment by VladiSylvan** [comment]
I also have the same problem, pls fix that. I'm re-install atom, delete all atoms dirs, and then try to install atom-beautify same problem(

**Comment by AndrewBarfield** [comment]
Yup. Same.

Installing “atom-beautify@0.30.9” failed.Hide output…

> coffee-script@1.12.8 postinstall C:\Users\ambar\AppData\Local\Temp\apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9\node_modules\atom-beautify\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

C:\Users\ambar\AppData\Local\Temp\apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9
`-- (empty)


npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[eval]:1
'if
^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ambar\AppData\Local\Temp\apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9\package.json'
npm WARN apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9 No description
npm WARN apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9 No repository field.
npm WARN apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9 No README data
npm WARN apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9 No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\ambar\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ambar\\AppData\\Local\\atom\\app-1.22.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\ambar\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\ambar\\.atom\\.apmrc" "install" "C:\\Users\\ambar\\AppData\\Local\\Temp\\d-1171030-7180-oqt2lp.qyitua0pb9\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coffee-script@1.12.8 postinstall script 'node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coffee-script package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coffee-script
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coffee-script
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ambar\AppData\Local\Temp\apm-install-dir-1171030-7180-1ofve4q.7fxy25ipb9\npm-debug.log
npm ERR! code 1

**Comment by szeck87** [comment]
Please run `apm clean` from your terminal and try again.

**Comment by szeck87** [comment]
@MiniZagGi were you able to install?

**Comment by abarfield-ideation** [comment]
Yes, I've installed. The issue can be closed for me. Thank you!

**Comment by MiniZagGi** [comment]
@szeck87 Yes. Sorry have not been able to get on the computer for awhile
