### ISSUE TITLE
Vue maxPreserveNewlines one less than setting for js/css

### ISSUE THREAD

**Issue by mokkabonna** [Glavin001/atom-beautify#1968]
# Description

I have set max_preserve_newlines: 2

Only the html template seems to get the correct amount of newlines.

# Input Before Beautification

This is what the code looked like before: (3 newlines for all)

```
<template>
<div>



  <div>
  </div>
</div>
</template>
<script>
import foo from 'foo'



export default {}
</script>
<style lang="scss" scoped>
.class1 {}



.class2 {}
</style>
```

# Expected Output

The beautified code should have looked like this: (2 newlines for all)

```
<template>
<div>


  <div>
  </div>
</div>
</template>
<script>
import foo from 'foo'


export default {}
</script>
<style lang="scss" scoped>
.class1 {}


.class2 {}
</style>

```

# Actual Output

The beautified code actually looked like this: (2 for html 1 for js/css)

```
<template>
<div>


  <div>
  </div>
</div>
</template>
<script>
import foo from 'foo'

export default {}
</script>
<style lang="scss" scoped>
.class1 {}

.class2 {}
</style>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/mokkabonna/f03f1684426ca7fc7140a90b47168552

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by mokkabonna** [comment]
This is still an issue.

**Comment by mokkabonna** [comment]
Still an issue

**Comment by szeck87** [comment]
@bitwiseman

**Comment by bitwiseman** [comment]
@szeck87 This issue does not repro on http://jsbeautifier.org/ .

**Comment by szeck87** [comment]
My bad, it goes through a few different pipelines.

**Comment by szeck87** [comment]
Yea, a lot issues with https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/vue-beautifier.coffee.  For one, we're not transforming the options that are passed into prettydiff.

**Comment by bitwiseman** [comment]
@szeck87 No problem.
