### ISSUE TITLE
XML treated as HTML for beautification

### ISSUE THREAD

**Issue by bitwiseman** [Glavin001/atom-beautify#197]
#3 turned on xml beautification by treating xml as html.  That solution is a hack and will be ineffective in a wide variety of cases.  #158 is one example of this. 

js-beautify does not support xml beautification at this time.  https://github.com/beautify-web/js-beautify/issues/648 is the feature request for beautifying xml.   That said we will attempt to fix xml related bugs as opportunity arises.

**Comment by prettydiff** [comment]
@Glavin001 you could use Pretty Diff for XML beautification. The markup parser in Pretty Diff was written to support XML first and then HTML support was added with an option on top of the XML parser. This is mostly seamless if using Pretty Diff's language auto-detection.

**Comment by Glavin001** [comment]
Definitely want to use PrettyDiff. Thanks for heads up!

**Comment by Glavin001** [comment]
@prettydiff will handle XML in the next release (see #282).

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.
