### ISSUE TITLE
Add support for Typescript (tsx)

### ISSUE THREAD

**Issue by DamickDoni** [Glavin001/atom-beautify#1977]
# Description

Add Support for TypescriptReact (.tsx)

Greetings :-)

**Comment by daggerjames** [comment]
duplicated, see #601

**Comment by Glavin001** [comment]
Merged https://github.com/Glavin001/atom-beautify/pull/2021
Coming in next release.

**Comment by Glavin001** [comment]
Published to v0.32.0
