### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by Kat35601** [Glavin001/atom-beautify#1982]
# Description
I get an error message when trying to run atom-beautify
"Could not find 'php-cs-fixer'. The program may not be installed."
php-cs-fixer is installed and I have uninstalled it and atom-beautifiy and then installed both again. I get the same error.

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/Kat35601/851dd2503678ecc58719b917d31b9605

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Please make sure you've updated Atom Beautify's settings under Executables -> PHP-CS-Fixer to put the path to the binary/script.

**Comment by JoeReadSEO** [comment]
szeck87 could you expand on what you mean by the binary/script?

I'm having the issue above and have installed php-cs-fixer.

I found the settings Executables -> PHP-CS-Fixer

But am not sure what path to enter here?

Thanks in advance

**Comment by szeck87** [comment]
@JoeReadSEO What operating system are you using?

**Comment by JoeReadSEO** [comment]
OS X El Capitan. Installed via the 'Install packages' setting in Atom

**Comment by szeck87** [comment]
@JoeReadSEO How did you install php-cs-fixer though?  Or did you install the Atom package for it (https://atom.io/packages/php-cs-fixer)?

**Comment by JoeReadSEO** [comment]
Hi szeck87, yes I installed the atom package for it via the 'Install packages' setting in Atom

**Comment by MitaiGit** [comment]
не могли бы вы описать как устанавливать и куда что прописывать, что бы он начал работать?
![2018-01-30 15-37-39](https://user-images.githubusercontent.com/32243762/35561898-91e26310-05d3-11e8-9f09-9fae45fa21a7.png)
![2018-01-30 15-39-05](https://user-images.githubusercontent.com/32243762/35561969-bb33b3a4-05d3-11e8-8dfe-9aff490a0641.png)
что где надо прописать что бы эта хренатень заработала?

**Comment by szeck87** [comment]
@JoeReadSEO that won't work, you need to install php-cs-fixer itself.  Since you're on a Mac, I would [install it via Homebrew](https://github.com/FriendsOfPHP/PHP-CS-Fixer#globally-homebrew) by running `brew install homebrew/php/php-cs-fixer`.

**Comment by MitaiGit** [comment]
значит что бы он начал работать просто установить пакет в атом не достаточно, его нужно так же устанавливать локально на ОС как отдельную программу, так себе пакет в таком случае...
