### ISSUE TITLE
Beautyfier makes nonsense on less file

### ISSUE THREAD

**Issue by kolbma** [Glavin001/atom-beautify#1983]
# Description

The results of beautification are not what I expect. It becomes totally invalid code.
There was also https://github.com/atom/language-less/issues/85 - but wrong repo.

# Input Before Beautification

This is what the code looked like before:

```
@stylenr: 6;
@sl-color-var: @sl-color6;
@sl-color-shadow-var: @sl-color6;

.n4v-apos-spotlight-widgets.wrapper.spotlight {
  &.style@{stylenr} {
    background-color: @sl-color-var;
  }

  &.style@{stylenr}:before,
  &.style@{stylenr}:after {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100' preserveAspectRatio='none'%3E%3Cpolygon points='0,100 100,0 100,100' style='fill:%232d3a69%3B;fill-opacity:0.5' /%3E%3C/svg%3E");
    box-shadow: inset 0 -1px 0 0 @sl-color-shadow-var, 0 1px 0 0 @sl-color-shadow-var;
  }
}
```

# Expected Output

Maybe same as input, but not the invalid code in actual output.

# Actual Output

The beautified code actually looked like this:

```
stylenr: 6;
@sl-color-var: @sl-color6;
@sl-color-shadow-var: @sl-color6;

.n4v-apos-spotlight-widgets.wrapper.spotlight {
  &.style@{stylenr} {
    background-color: @sl-color-var;
  }

  &.style@,
  &.style@{stylenr}:before {
    stylenr
  }

  :after {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100' preserveAspectRatio='none'%3E%3Cpolygon points='0,100 100,0 100,100' style='fill:%232d3a69%3B' /%3E%3C/svg%3E");
    box-shadow: inset 0 -1px 0 0 @sl-color-shadow-var, 0 1px 0 0 @sl-color-shadow-var;
  }
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code is invalid!

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
@prettydiff has created an issue over at https://github.com/prettydiff/prettydiff/issues/504 . Please subscribe there.
