### ISSUE TITLE
Support HUGO commands in html 

### ISSUE THREAD

**Issue by jandechent** [Glavin001/atom-beautify#1996]
# Description

Flattens all commands in the layout html files of the [hugo CMS](http://gohugo.io/) into one single line. But it should respect the programming structure and indent as in e.g. js - or at least leave the parts unchanged. 

# Input Before Beautification

```html
<div class="row">
	{{range (sort ( (where .Data.Pages "Section" "x" ) ) ".Params.weight" "desc" )}}`
		{{ if in .Params.tags "y" `}}
			{{ partial "person6u" .}}
		{{end}}
	{{end}}
</div>
```
# Expected Output

```html
<div class="row">
	{{range (sort ( (where .Data.Pages "Section" "x" ) ) ".Params.weight" "desc" )}}`
		{{ if in .Params.tags "y" `}}
			{{ partial "person6u" .}}
		{{end}}
	{{end}}
</div>
```

# Actual Output

```html
<div class="row">
	{{range (sort ( (where .Data.Pages "Section" "x" ) ) ".Params.weight" "desc" )}}`{{ if in .Params.tags "y" `}}{{ partial "person6u" .}}{{end}}{{end}}
</div>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@jandechent which beautifier are you using for these files?
