### ISSUE TITLE
Atom-Beautify doesn't format things the way the default Atom editor does

### ISSUE THREAD

**Issue by davelogear** [Glavin001/atom-beautify#2001]
# Description

If I open a new file and type `html` then hit Tab or Enter, Atom automatically generates some generic html code formatted all nice and properly. If then mis-indent something or do something hideously unbeautiful, then click Packages > Atom Beautify > Beautify, it changes far more than the unbeautiful thing I typed, including the auto-formatted Atom `html` code, which looked fine to begin with, into something less sensible.

Using Atom version 1.23.2 x64
Using Atom Beautify version 0.30.9

# Input Before Beautification

This is what the code looked like before:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>
```

# Expected Output

The beautified code should have looked like this:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>
```

# Actual Output

The beautified code actually looked like this:

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>

</body>

</html>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: If the code I pasted is not how Atom Beautify should be behaving, please let me know and I will generate a Gist. Right now I don't even know how to tell how Beautify should be formatting the HTML.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Edited the checklist so the checkboxes are filled out properly.  @davelogear can you tell us which beautifier you are using for HTML files?  You can generate the Debug output and submit a gist to link here, or you can find it under Settings > HTML in the Default Beautifier field.

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by dadave92** [comment]
Same Problem here
https://gist.github.com/dadave92/b6166b7c4c283e1559e5c0da1061f4c9
