### ISSUE TITLE
Could not find 'C:\Users\USERNAME.atom\packages\atom-beautify\node_modules.bin\cljfmt'. The program may not be installed.

### ISSUE THREAD

**Issue by HactarCE** [Glavin001/atom-beautify#2007]
(The title is directly copied and pasted from Atom's error window, including lack of backslashes preceding `.`s.)

# Description

`cljfmt` causes the following error when run:

```
Could not find 'C:\Users\USERNAME.atom\packages\atom-beautify\node_modules.bin\cljfmt'. The program may not be installed.

See C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\.bin\cljfmt installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/snoe/node-cljfmt
Your program is properly installed if running 'where.exe C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\.bin\cljfmt' in your CMD prompt returns an absolute path to the executable.

Stack Trace:
Error: Could not find 'C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\.bin\cljfmt'. The program may not be installed.
    at Function.Executable.commandNotFoundError (file:///C:/Users/USERNAME/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:10)
    at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/USERNAME/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
    at file:///C:/Users/USERNAME/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
    at tryCatcher (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\USERNAME\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

There are no instructions for installation of `cljfmt` at the supplied links. `where.exe` results in `ERROR: Invalid pattern is specified in "path:pattern".`, but the file does exist.

# debug.md

[debug.md](https://gist.github.com/HactarCE/166d62e990a9314a94f6f52f66ed3822#file-debug-md)

# Steps to Reproduce

1. Open a Clojure file
2. Run command `Atom Beautify: Beautify Editor`
3. Crash

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
cljfmt is included when you install Atom Beautify.  Can you navigate to `C:\Users\USERNAME.atom\packages\atom-beautify\node_modules\` and see if `node-cljfmt` is there?

**Comment by HactarCE** [comment]
Yep, and it looks healthy too. https://i.imgur.com/zYNokX3.png

**Comment by szeck87** [comment]
Whoops, sorry. Go into the `bin` folder there and then see if a folder named `node-cljfmt` is there.

**Comment by HactarCE** [comment]
Nope, there's just the single file `cljfmt`, which contains a whole bunch of obfuscated JS. https://i.imgur.com/EApTOfl.png

**Comment by szeck87** [comment]
I would uninstall Atom completely and reinstall, then try again.  The files in that directory from your screenshot don't look right.

**Comment by HactarCE** [comment]
A complete reinstall did not resolve the issue.

atom-beautify is working fine with Python.

**Comment by szeck87** [comment]
Try running `npm install` or `npm install node_cljfmt` from `C:\Users\USERNAME\.atom\packages\atom-beautify`

**Comment by HactarCE** [comment]
```
Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\USERNAME\.atom\packages\atom-beautify>npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> atom-beautify@0.30.9 prepublish C:\Users\USERNAME\.atom\packages\atom-beautify
> npm run docs


> atom-beautify@0.30.9 docs C:\Users\USERNAME\.atom\packages\atom-beautify
> npm run build-options && coffee docs/


> atom-beautify@0.30.9 build-options C:\Users\USERNAME\.atom\packages\atom-beautify
> node script/build-options.js

Building options for beautifiers
Done building options for beautifiers
Beautifier options successfully saved to C:\Users\USERNAME\.atom\packages\atom-beautify\src\options.json
Generating options...
Loading options template...
Building documentation from template and options...
Writing documentation to file...
Updating package.json
Done.
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 7.684s

C:\Users\USERNAME\.atom\packages\atom-beautify>npm install node_cljfmt
npm ERR! code E404
npm ERR! 404 Not Found: node_cljfmt@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2018-01-14T20_44_04_414Z-debug.log

C:\Users\USERNAME\.atom\packages\atom-beautify>
```

[Here's the log file.](https://gist.github.com/HactarCE/3f9c4106edce95daef50b41497a3751e)

**Comment by szeck87** [comment]
OK, I'll have to boot up my Windows machine and see where everything is located again.  There should be a folder (I thought it was directly in node_modules) where it has all of atom-beautify's dependencies.

**Comment by amatlock930** [comment]
If you look at the error message, there are some missing "\" in the path before each ".". Is the path just getting messed up?

**Comment by scarcher2** [comment]
I'm having the same issue. 

Could not find 'C:\Users\scarc.atom\packages\atom-beautify\node_modules.bin\cljfmt'. The program may not be installed.
See C:\Users\scarc\.atom\packages\atom-beautify\node_modules\.bin\cljfmt installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/snoe/node-cljfmt
Your program is properly installed if running 'where.exe C:\Users\scarc\.atom\packages\atom-beautify\node_modules\.bin\cljfmt' in your CMD prompt returns an absolute path to the executable.

My username is "scarch" it's missing a \ after that part of the path. so it's looking in "scarch.atom" instead of "scarch\.atom"

**Comment by scarcher2** [comment]
I think the backslash is just getting truncated when displayed (it's probably not escaped) the stacktrace has the proper location and the file is where it says it should be. 

`
C:\Users\scarc\.atom\packages\atom-beautify\node_modules\.bin>dir cljfmt*.*
 Volume in drive C has no label.
 Volume Serial Number is 2471-1ACA

 Directory of C:\Users\scarc\.atom\packages\atom-beautify\node_modules\.bin

05/24/2018  11:32 PM               315 cljfmt
05/24/2018  11:32 PM               192 cljfmt.cmd
               2 File(s)            507 bytes
               0 Dir(s)  64,733,278,208 bytes free

C:\Users\scarc\.atom\packages\atom-beautify\node_modules\.bin>`
