### ISSUE TITLE
Option to disable indentation in specific files

### ISSUE THREAD

**Issue by msharitasa** [Glavin001/atom-beautify#2013]
Is there any option to disable or ignore autosave indentation or indentation for a specific file excluding the rest?

**Comment by szeck87** [comment]
Nope sorry, there is not an option to do that.

**Comment by Glavin001** [comment]
Not yet. Currently you can disable a language, not a specific file(s). Pull Requests welcome!

**Comment by Glavin001** [comment]
@msharitasa : Unibeautify will be the successor of Atom-Beautify. I recommend you search and/or create an issue over at https://github.com/unibeautify/unibeautify/issues 😃 .
