### ISSUE TITLE
rbeautify keep crashing

### ISSUE THREAD

**Issue by melalj** [Glavin001/atom-beautify#202]
I have installed rube-beautify using `sudo gem install ruby-beautify`

Is ruby-beautify really buggy and unsupported project? 
https://github.com/Glavin001/atom-beautify/issues/25

Keep getting this error message:

Command failed: /bin/sh -c [ -f ~/.bash_profile ] && source ~/.bash_profile;[ -f ~/.bashrc ] && source ~/.bashrc;rbeautify "/var/folders/pl/1m6gyp_11hsc43hljhf0_hh00000gn/T/input11513-38729-xhr9t6" /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/lib/ruby-beautify.rb:152:in `indented_line': invalid byte sequence in US-ASCII (ArgumentError) from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/lib/ruby-beautify.rb:38:in `block in pretty_string' from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/lib/ruby-beautify.rb:27:in `each' from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/lib/ruby-beautify.rb:27:in `pretty_string' from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/bin/rbeautify:24:in `print_or_die' from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/bin/rbeautify:57:in `block in <top (required)>' from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/bin/rbeautify:36:in `each' from /Library/Ruby/Gems/2.0.0/gems/ruby-beautify-0.97.1/bin/rbeautify:36:in `<top (required)>' from /usr/bin/rbeautify:23:in `load' from /usr/bin/rbeautify:23:in `<main>'

**Comment by Glavin001** [comment]
Switching over to Rubocop is the next release (v0.25.0). That should fix this up for you. See #275
