### ISSUE TITLE
Atom-beautify turn Angular html tag attribute into lowercase

### ISSUE THREAD

**Issue by brexis** [Glavin001/atom-beautify#2025]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<input type="text" [(ngModel)]="username" />
```

# Expected Output

The beautified code should have looked like this:

```
<input type="text" [(ngModel)]="username" />
```

# Actual Output

The beautified code actually looked like this:

```
<input type="text" [(ngmodel)]="username" />
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by szeck87** [comment]
@prettydiff I can reproduce this using Pretty Diff as the formatter.

@brexis meanwhile you can change the formatter to JS Beautify.  If you are using the `HTML (Angular)` grammar in Atom, make the change under EJS in atom beautify's settings.  If you're using regular `HTML` grammar, make the change under HTML.  JS Beautify seems to ignore casing on Angular directives.

**Comment by speedfl** [comment]
Hello,

got the same issue

**Comment by tshowers** [comment]
I get the same

**Comment by markhowellsmead** [comment]
This is still an issue (in my case, for Twig files).
