### ISSUE TITLE
Could not find 'php'. The program may not be installed.

### ISSUE THREAD

**Issue by reflex073** [Glavin001/atom-beautify#2029]
Firstly I am very grateful for such a this package.
I am use Ampps localhost. Its mean installed php language. 

But path not a c:\

My php path
C:\Program Files (x86)\Ampps\php-7.1

If i change atom-beautify php way can work or not?
and how can i change atom php way. 

> (sorry my english.)

**Comment by szeck87** [comment]
If PHP is not in your environment path, go into Atom Beautify's settings and select Executables.  Insert the path to your local PHP there.

![screen shot 2018-01-28 at 11 56 51 am](https://user-images.githubusercontent.com/8315038/35485245-65a98218-0422-11e8-8a9f-dfd71205c401.png)

**Comment by reflex073** [comment]
Thank you.
