### ISSUE TITLE
wrong beautification on SCSS concatenation in background url property 

### ISSUE THREAD

**Issue by Bodhiz** [Glavin001/atom-beautify#203]
Hi,

I noticed an issue after beautifying my SCSS containing this kind of concatenation :
![image](https://cloud.githubusercontent.com/assets/2632229/6039966/ccbd2bfa-ac6c-11e4-93a3-e6c0da48b363.png)

it produces this (it adds a double quote before my var), which is not correct :
![image](https://cloud.githubusercontent.com/assets/2632229/6039980/f12bf41c-ac6c-11e4-86ca-caed94d92b54.png)

Maybe I did something wrong regarding my SCSS syntax, but at first sight it looks more an error from the beautifyer. 

Thank you.

**Comment by prettydiff** [comment]
https://github.com/prettydiff/prettydiff/issues/63

This is my bug. SCSS support is provided by Pretty Diff, so I need to fix this in my library.

**Comment by Bodhiz** [comment]
ok. thanks in advance :)

**Comment by prettydiff** [comment]
QA version up for your review:



Up for review:

prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by prettydiff** [comment]
Now fixed in v1.11.3

**Comment by Bodhiz** [comment]
@Glavin001 Is that fix has been embedded in the latest versions ?

**Comment by Glavin001** [comment]
Not yet. I am in the middle of exams, however once I can take a break from studying I'll make this fix and publish it. Thank you for your patients.
Also thanks to @prettydiff for being awesome and resolving these so quickly!

**Comment by Bodhiz** [comment]
I updated to the atom-beautify latest version and it seems to work fine. I can't reproduce the bug. Maybe you embedded prettydiff 1.11.3 in a previous release :)

Anyway, good luck for your exams ;)

**Comment by Glavin001** [comment]
Ooh that may be the case: see https://github.com/Glavin001/atom-beautify/blob/master/package.json#L65 
Thanks to semver, Atom likely updated the version of Prettydiff to latest automatically when you updated. Sweet! Thanks for letting me know.

> Anyway, good luck for your exams ;)

Thank you :smiley:
