### ISSUE TITLE
Question - should this plugin work on minified files?

### ISSUE THREAD

**Issue by myxal** [Glavin001/atom-beautify#2034]
# Description

I ran into lua source file where everything was in 1 line. It seems that lua-beautify doesn't do anything beyond auto-indentation, as running atom-beautify didn't make any changes to the minified code.

# Input Before Beautification

This is what the code looked like before:

```
TUNING.VIRTUALRED = color / 100 TUNING.VIRTUALGREEN = (color / 10)%10 TUNING.VIRTUALBLUE = color%10 STRINGS.NAMES.VIRTUALFIREPIT = STRINGS.NAMES.FIREPIT STRINGS.NAMES.VIRTUALCOLDFIREPIT = STRINGS.NAMES.COLDFIREPIT STRINGS.NAMES.VIRTUALMUSHROOM_LIGHT = STRINGS.NAMES.MUSHROOM_LIGHT
```

# Expected Output

The beautified code should have looked like this:

```
TUNING.VIRTUALRED = color / 100
TUNING.VIRTUALGREEN = (color / 10)%10
TUNING.VIRTUALBLUE = color%10
STRINGS.NAMES.VIRTUALFIREPIT = STRINGS.NAMES.FIREPIT
STRINGS.NAMES.VIRTUALCOLDFIREPIT = STRINGS.NAMES.COLDFIREPIT
STRINGS.NAMES.VIRTUALMUSHROOM_LIGHT = STRINGS.NAMES.MUSHROOM_LIGHT

```

# Actual Output

The beautified code actually looked like this:

```
TUNING.VIRTUALRED = color / 100 TUNING.VIRTUALGREEN = (color / 10)%10 TUNING.VIRTUALBLUE = color%10 STRINGS.NAMES.VIRTUALFIREPIT = STRINGS.NAMES.FIREPIT STRINGS.NAMES.VIRTUALCOLDFIREPIT = STRINGS.NAMES.COLDFIREPIT STRINGS.NAMES.VIRTUALMUSHROOM_LIGHT = STRINGS.NAMES.MUSHROOM_LIGHT
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/myxal/dbb80f3c18f8b6d06019210e1b22366d

# Checklist

I have:
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by myxal** [comment]
Added.

**Comment by myxal** [comment]
@Glavin001 - is anything else needed? I don't think I can modify the labels to remove "waiting for user info".

**Comment by myxal** [comment]
>  If this is still an issue

Yes it is.

**Comment by myxal** [comment]
Yes it's still an issue. (A question, in fact - don't the developers know if a feature is implemented or not? Why is an answer taking so long?!)
