### ISSUE TITLE
HTML/TWIG beautify breaks code by adding incorrect values in empty data attributes

### ISSUE THREAD

**Issue by kevinmu17** [Glavin001/atom-beautify#2039]
# Description
The results of beautification are not what I expect.

# Input Before Beautification
This is what the code looked like before:
```
<form method="post" action  novalidate data-plugin>
```

# Expected Output
The beautified code should have looked like this:
```
<form method="post" action  novalidate data-plugin>
```

# Actual Output
The beautified code actually looked like this:
```
<form method="post" action="action" novalidate="novalidate" data-plugin="data-plugin">
```

# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor` or ctrl+alt+b
3. This beautified code does not look right!

# Checklist
I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
A popular issue of the moment: https://github.com/prettydiff/prettydiff/issues/502

**Comment by xeon826** [comment]
This happens to me as well. I have the latest versions of Atom and atom-beautify. If I have a line for instance
&#x60;
&#x3C;option value=&#x27;&#x27; {% if customer.admin_status is null %} selected{% endif %} &#x22;&#x3E;Status&#x3C;/option&#x3E;
&#x60;
It becomes 
&#x60;          
&#x3C;option value=&#x27;&#x27; {% if customer.admin_status is null %} selected{% endif %}=&#x22;selected{% endif %}&#x22;&#x3E;Status&#x3C;/option&#x3E;
&#x60;
Also I&#x27;ve noticed 
&#x60;        &#x3C;input type=&#x22;name&#x22; name=&#x22;address&#x22; value=&#x27;{{ not customer.address ? &#x27; &#x22;N/A&#x22; &#x27; : customer.address }}&#x27; class=&#x22;form-control&#x22; id=&#x22;address&#x22; placeholder=&#x22;Address&#x22;&#x3E;&#x60;

becomes         

&#x60;&#x3C;input type=&#x22;name&#x22; name=&#x22;address&#x22; value=&#x27;{{ not customer.address ? &#x27; n/a=&#x22;N/A&#x22; &#x27; : customer.address }}&#x27; class=&#x22;form-control&#x22; id=&#x22;address&#x22; placeholder=&#x22;Address&#x22;&#x3E;
&#x60;

**Comment by prettydiff** [comment]
This was a major defect in the prior major version of Pretty Diff.  The latest version of Pretty Diff solves these problems.  I need to get it into Atom Beautify.
