### ISSUE TITLE
Atom 1.25 assigns JavaScript language to .jsx files

### ISSUE THREAD

**Issue by szeck87** [Glavin001/atom-beautify#2045]
# Description

Atom 1.25 looks to be defaulting the language of `.jsx` files to JavaScript if no other language package is installed that would otherwise overrule it.

This is causing prettydiff to recognize it as JavaScript, thus the beautification is different.  This is why the Travis build is failing (2/16/2018)

# Steps to Reproduce

1. Download Atom Beta 1.25
2. Uninstall any language packages not included with the core download
3. Open a file with a `.jsx` extension
4. Observe selected grammar/language

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Looking through packages that make sense to add for proper jsx support.  Might have to adjust prettydiff as well.

**Comment by Glavin001** [comment]
Published to v0.32.0
