### ISSUE TITLE
Unable to install atom beautify

### ISSUE THREAD

**Issue by AnastasiaEvgenia** [Glavin001/atom-beautify#2050]
Hi, I am trying to install this package through atom, and I get an error. Can you help me? This is the output I take. Thank you.

Installing “atom-beautify@0.30.9” failed.Hide output…

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\nen_a\\AppData\\Local\\atom\\app-1.24.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\nen_a\\AppData\\Local\\atom\\app-1.24.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\nen_a\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\nen_a\\.atom\\.apmrc" "install" "C:\\Users\\nen_a\\AppData\\Local\\Temp\\d-118121-480-1v0wib0.1uanb138fr\\package.tgz" "--runtime=electron" "--target=1.6.16" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.112.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nen_a\AppData\Local\Temp\apm-install-dir-118121-480-oiklm9.4if67s0pb9\npm-debug.log

**Comment by szeck87** [comment]
@AnastasiaEvgenia are you behind a firewall or proxy?  Can you try what's outlined here:  https://github.com/atom/apm#behind-a-firewall

**Comment by AnastasiaEvgenia** [comment]
Hi, thank you for your help.

**Comment by szeck87** [comment]
Did it work?

**Comment by AnastasiaEvgenia** [comment]
yes. thank you again!
