### ISSUE TITLE
Beautification deletes code when it meets several `if` statements in the same line

### ISSUE THREAD

**Issue by developerlover** [Glavin001/atom-beautify#2054]
# Description

Like title says, beautification deletes useful code in lines that contains several `if` statements. 

Seems like, from second `endif` tag beautification deletes everything after it, including the second `endif` tag.

# Input Before Beautification

This is what the code looked like before:

```
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
```

# Expected Output

The beautified code should have looked like this:

```
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow" {% endif %} {% if bar %} rel="nofollow" {% endif %}>foobar</a>
```

# Actual Output

The beautified code actually looked like this:

```
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow">foobar</a>
<a {% if foo %} target="_blank" {% endif %} {% if bar %} rel="nofollow">foobar</a>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/developerlover/37781b9bd5e8a39b38e4b06f510d31f3

**Comment by szeck87** [comment]
Please run the Debug command in Atom and paste the results into a gist here on GitHub, with a link to it in this issue.

**Comment by developerlover** [comment]
@szeck87 Hi, I updated my comment with the debug. Sorry for the inconvenience!

**Comment by szeck87** [comment]
Thans @developerlover.  @prettydiff I was able to reproduce at prettydiff.com.  Thoughts?

**Comment by developerlover** [comment]
@Glavin001 ok thanks! I will
