### ISSUE TITLE
Could not find 'php'. The program may not be installed.

### ISSUE THREAD

**Issue by TheHatMan98** [Glavin001/atom-beautify#2058]
"See php installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to http://php.net/manual/en/install.php
You can configure Atom Beautify with the absolute path to 'php' by setting 'Executable - PHP - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'where.exe php' in your CMD prompt returns an absolute path to the executable."

path to 'php'? i upload my script to a FTP server.

**Comment by szeck87** [comment]
You need to have PHP and whatever PHP beautifier you're using installed locally.
