### ISSUE TITLE
Do support for the Brightscript language(.brs)

### ISSUE THREAD

**Issue by CsHimanshu** [Glavin001/atom-beautify#2059]
Please do the support for the BrightScript language which is majorly used for Roku development. It's extension is brs.

When I am trying to do beautify .brs file. It is prompting me the following message : 
Atom Beautify could not determine a supported beautifier to handle this file with grammar "BrightScript" and extension "brs". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by mcsgdigital** [comment]
Yo guys,

Can we have an update on this please?

About same as javascript and XML so would be ok to have an option that says 'wanna beautify like [language] ?' and let the user decide what to do.


Thanks,
Mark
