### ISSUE TITLE
package.json repository.url format invalid

### ISSUE THREAD

**Issue by joaomlneto** [Glavin001/atom-beautify#2062]
TL;DR: package.json repository.url should be `github:Glavin001/atom-beautify`

Repository URL in `package.json` should be publicly available:
https://docs.npmjs.com/files/package.json#repository

When viewing the package from the Atom package browser, you can't click the URL (it shows up as http://git@github.com/Glavin001/atom-beautify)

I guess it should be something like `github:Glavin001/atom-beautify`

(It's so minor I feel ashamed to open the issue, but here you go 😛)

**Comment by Glavin001** [comment]
I did know know about the `github:` prefix support for Repository URL. Pull Request welcome!

**Comment by JamesCoyle** [comment]
You probably want either:
```
"repository": "https://github.com/Glavin001/atom-beautify",
```
or
```
"repository": {
    "type": "git",
    "url": "https://github.com/Glavin001/atom-beautify.git"
},
```
