### ISSUE TITLE
error on update to 0.32.0

### ISSUE THREAD

**Issue by anthony-ra** [Glavin001/atom-beautify#2072]
# Description

I can't update it with Atom 1.24.0 x64 (debian stretch)

# Input Before Beautification

This is what the code looked like before:

```
Updating to “atom-beautify@0.32.0” failed.Hide output…

npm ERR! cb() never called!

```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
https://gist.github.com/anthony-ra/89319b983a3fe30395d939a9dc3b10c8

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
This is an error when trying to update the package, not when beautifying python files, correct?  If so, please try running `apm clean` from the terminal and try updating again.

**Comment by anthony-ra** [comment]
Yes, this error is when trying to update.
I do apm clean as current user and start Atom to update package but same error
I do apm clean a root but same error when trying to update.

**Comment by szeck87** [comment]
@anthony-ra Can you upload a screenshot of the error?

**Comment by anthony-ra** [comment]
@szeck87 
http://tinypic.com/r/xvcbm/9

**Comment by szeck87** [comment]
Try running `npm cache verify`

**Comment by anthony-ra** [comment]
@szeck87 
/usr/share/atom/resources/app/apm/bin/npm cache verify
npm ERR! Usage: npm cache add <tarball file>
npm ERR! npm cache add <folder>
npm ERR! npm cache add <tarball url>
npm ERR! npm cache add <git url>
npm ERR! npm cache add <name>@<version>
npm ERR! npm cache ls [<path>]
npm ERR! npm cache clean [<pkg>[@<version>]]

**Comment by szeck87** [comment]
Looks like your npm contents are a bit corrupted (for Atom packages and elsewhere).  I'm not exactly sure how to fix that, you could try forcing it to clean `npm cache clean --force`, but I don't think that's recommended anymore.

**Comment by anthony-ra** [comment]
well, I ran this commands:
/usr/share/atom/resources/app/apm/bin/npm cache clean --force
/usr/share/atom/resources/app/apm/bin/npm cache verify
/usr/share/atom/resources/app/apm/bin/npm install -g n
/usr/share/atom/resources/app/apm/bin/npm install -g npm
after the last command, I can update atom-beautify :-)

without your help, I couldn't see the problem, thanks a lot.
