### ISSUE TITLE
Indent code inside of <template>, <script> and <style> tags

### ISSUE THREAD

**Issue by wederer** [Glavin001/atom-beautify#2073]
# Description

Is there a setting to indent all code inside of <script> and <style> tags like that?
I thought "indent_inner_html" was the correct option, but does not bring the desired behaviour.

Please let me know if issues are not used for questions and point me in the right direction where I can ask.

Thank you!

# Input Before Beautification

This is what the code looked like before:

```
<template>
<div class="container">
  <p>This is some content.</p>
</div>
</template>

<script>
export default {
  console.log("this is some logging");
}
</script>

<style>
div {
  color: black;
}
</style>

```

# Expected Output

The beautified code should have looked like this:

```
<template>
  <div class="container">
    <p>This is some content.</p>
  </div>
</template>

<script>
  export default {
    console.log("this is some logging");
  }
</script>

<style>
  div {
    color: black;
  }
</style>

```

# Actual Output

The beautified code actually looked like this:

```
<template>
<div class="container">
  <p>This is some content.</p>
</div>
</template>

<script>
export default {
  console.log("this is some logging");
}
</script>

<style>
div {
  color: black;
}
</style>

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by FINDarkside** [comment]
Anyone? It's really annoying to write Aurelia template files when you have to format them manually.
