### ISSUE TITLE
Beautify not working on PHP files

### ISSUE THREAD

**Issue by ajCastiglione** [Glavin001/atom-beautify#2079]
# Description

No beautification happened.

# Expected Output

The code should have been beautified.

# Debug

See php installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to http://php.net/manual/en/install.php
You can configure Atom Beautify with the absolute path to 'php' by setting 'Executable - PHP - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'where.exe php' in your CMD prompt returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'php'. The program may not be installed.
at Function.Executable.commandNotFoundError (file:///C:/Users/Owner/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:10)
at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/Owner/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
at file:///C:/Users/Owner/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
at tryCatcher (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
at Promise._settlePromises (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
at Async._drainQueue (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
at Async._drainQueues (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
at Async.drainQueues (C:\Users\Owner\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by szeck87** [comment]
Do you have PHP and a PHP beautifier (PHP-CS-Fixer or PHPCBF) installed?  If so, you also need to specify the absolute path to the binary script under atom-beautify settings Executables -> PHP and the beautifier.

![screen shot 2018-03-10 at 1 07 15 pm](https://user-images.githubusercontent.com/8315038/37245854-1b014e64-2464-11e8-8f78-c0228d36c724.png)

**Comment by ajCastiglione** [comment]
How would I go about finding the absolute path to the binary script?

**Comment by szeck87** [comment]
You'll need to download PHP first, believe you are on Windows so from here:  https://windows.php.net/download#php-7.2.  Unzip it and somewhere should be php.exe.  Copy the path where that file is into the PHP field from the screenshot above.  I _think_ that's all you need to do here.  I'm not on a Windows machine so I can't try it myself.  You'll need to do the same for whichever beautifier you choose as well.

Give that a try and post back if you run into issues along the way.

**Comment by ajCastiglione** [comment]
Oh wow that was a simple fix. Thanks so much for the help!

**Comment by meshuu** [comment]
Hi guys, I have the same problem but I work on mac. I'm a beginner so I find it difficult to find a guide telling me how to solve the problem step by step. 
What information should I tell you to let me help? 
This is what I have done so far:
1) I installed Atom-Beautify;
2) I installed PHP-CS-Fixer;
3) at the beginning he gave me this error message
![35561898-91e26310-05d3-11e8-9f09-9fae45fa21a7](https://user-images.githubusercontent.com/37701762/37834430-fbe4c9a8-2ead-11e8-897f-ae08bcd4932e.png)
now when I try to use Atom-Beautify nothing is happening;
4) I have not set absolute path for Atom-Beautify
![schermata 2018-03-23 alle 15 23 57](https://user-images.githubusercontent.com/37701762/37834539-3e0148ca-2eae-11e8-8935-ac78b70049f6.png)
e for PHP-CS-Fixer 
![schermata 2018-03-23 alle 15 26 50](https://user-images.githubusercontent.com/37701762/37834744-bb4a49bc-2eae-11e8-8e36-8d038d2ee2b6.png)
and I've never installed php on the mac.

Thanks in advance to those who want to help me.

**Comment by szeck87** [comment]
@meshuu How did you install PHP-CS-Fixer?  Since you are on a Mac I would highly recommend installing it via Homebrew:  `brew install homebrew/php/php-cs-fixer`.  If you don't have Homebrew installed you can find directions here:  https://brew.sh/.  It should work right out of the box.

PHP itself should already be installed on your mac.

**Comment by meshuu** [comment]
Thanks for the quick response, I hope you can help me because I'm really at the beginning. As I wrote in the list I installed PHP-CS-Fixer also via Homebrew:

![schermata 2018-03-23 alle 15 54 10](https://user-images.githubusercontent.com/37701762/37836437-b330a902-2eb2-11e8-8b7a-3eaeee78eae3.png)
So now what can I do? Do I have to uninstall the PHP-CS-Fixer package from Atom and set the absolute paths in the Atom-Beautify settings? If so how?

**Comment by szeck87** [comment]
Ah sorry I missed that in your original comment.  Since you installed it through Homebrew it _should_ be working.  Can you please run the debug command in Atom (Packages -> Atom Beautify -> Debug) and paste the contents of the new tab into a gist here on GitHub.  Then post the link to that gist here.

**Comment by meshuu** [comment]
Here is the link, I hope I have not made mistakes: https://gist.github.com/meshuu/0b628df21a324a57a7d7c1237190665b

**Comment by szeck87** [comment]
Relevant information:
```
2018-03-23T15:44:10.222Z - debug: [] spawn done 255  
Fatal error: Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/console/Application.php on line 83

2018-03-23T15:44:10.222Z - verbose: [] spawn result, returnCode 255
2018-03-23T15:44:10.222Z - verbose: [] spawn result, stdout 
Fatal error: Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/console/Application.php on line 83
```

**Comment by szeck87** [comment]
@meshuu please run `php --version` and `php-cs-fixer --version` and post back what they are here.

**Comment by meshuu** [comment]
Of course, thank you very much for your attention:

(php --version)
PHP 5.6.30 (cli) (built: Oct 29 2017 20:30:32) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

(php-cs-fixer --version)
Fatal error: Default value for parameters with a class type hint can only be NULL in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/console/Application.php on line 83

**Comment by szeck87** [comment]
OK, you need to be one php 7 or higher.  I'm not sure how Macs know which version to install.  @Glavin001 do you know?

Otherwise try running `brew install php71` to install php 7.1.  You may also have to switch from 5.6.30 to 7.1, so see https://github.com/Homebrew/homebrew-php#installing-multiple-versions, the third part which starts with "If you would like to swap the PHP you use on the command line"

**Comment by meshuu** [comment]
I think I went too fast to read your post and without thinking I installed php 7 via homebrew as you told me "brew install php71". 
![schermata 2018-03-23 alle 18 34 27](https://user-images.githubusercontent.com/37701762/37844678-d5d875f0-2ec8-11e8-91d7-83846d4b0daf.png)
Ecco la situazione ora:

(php --version)
PHP 7.1.14 (cli) (built: Feb  2 2018 08:41:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

(php-cs-fixer --version)
PHP CS Fixer 2.10.0 Bowling Bear by Fabien Potencier and Dariusz Ruminski

**Comment by szeck87** [comment]
OK that looks better.  Try running Atom Beautify against a PHP file now.

**Comment by meshuu** [comment]
Nothing happens, it does not "beautify".
I also restarted the mac and tried to uninstall the package, since it was installed via Homebrew, but even this attempt does not change things.

**Comment by szeck87** [comment]
It's probably the content of your file itself, mine doesn't beautify that either.  Try copy/paste the raw contents of this file into Atom and try.  See if it does anything.

https://github.com/Glavin001/atom-beautify/blob/master/examples/simple-jsbeautifyrc/php/original/_test.php

**Comment by meshuu** [comment]
You're right, thank you so much now it works.
Can I ask you one last thing? Is there a package that performs a beautify on mixed html and php, as WordPress file?

**Comment by Curtis-Lockley** [comment]
I also have an issue where Packages > Atom Beautify > Beautify
The loading screen below appears indicating that beautification is supposed to happen, but nothing changes and no error or warnings are provided
![Beautify](https://user-images.githubusercontent.com/26248049/67595449-96c52600-f75e-11e9-91ba-5c2d60c25aeb.png)

Here are my settings under Packages > Atom Beautify > Executables >PHP and Packages > Atom Beautify > Executables >PHP-CS-Fixer
![settings](https://user-images.githubusercontent.com/26248049/67595498-b8261200-f75e-11e9-8b54-7e486020ffe3.png)

**Comment by djmtype** [comment]
Upon trying to install `brew install homebrew/php/php-cs-fixer`, I get: `homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.`

**Comment by valenzine** [comment]
> 

Try `brew install php-cs-fixer` or check [the website](https://formulae.brew.sh/formula/php-cs-fixer) for updated instructions.
