### ISSUE TITLE
Support Atom IDE's built-in code formatting

### ISSUE THREAD

**Issue by wbinnssmith** [Glavin001/atom-beautify#2082]
Atom IDE supports code formatting and exposes a similar api via the atom services `code-format.file`, `code-format.onSave`, and others. Atom IDE users expect to use cmd-shift-c to format code of all types, not just those supported by atom-beautify. 

cc @hansonw

[Here's an example of Nuclide's JSON formatting using this service](https://github.com/facebook/nuclide/blob/99337a1a2c843ba7f75105c80306f3315aa6c501/pkg/nuclide-json/lib/main.js#L68-L76)

**Comment by Glavin001** [comment]
I think this is somewhat related to https://github.com/Unibeautify/unibeautify/issues/61

Great idea! Would be very interested in receiving a Pull Request!

**Comment by Glavin001** [comment]
More info can be found at https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/code-format.md

**Comment by szeck87** [comment]
Relevant documentation here:  https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/code-format.md#service-api

**Comment by Glavin001** [comment]
Awesome! Please let us know if you need any assistance, @wbinnssmith.

**Comment by wbinnssmith** [comment]
Thanks for plugging those docs and pages :)

**Comment by stevenzeck** [comment]
I'm incorporating this into [Unibeautify](https://github.com/stevenzeck/atom-beautify/blob/unibeautify/src/AtomBeautify.ts#L196-L210).  I want to make the methods in that file even more modular to: 1. Deduplicate code that is already there and 2. Implement this more easily.

**Comment by Glavin001** [comment]
@stevenzeck you'd like to related this to https://github.com/Glavin001/atom-beautify/issues/1174 and include in those changes? Sounds good to me 👍 .
