### ISSUE TITLE
Alters formatting against recommedations

### ISSUE THREAD

**Issue by Showcase-Joz** [Glavin001/atom-beautify#2083]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before beautification - having used Linter [steelbrain]:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
function signUp() {
  $('html, body').animate({
    scrollTop: $('#home').offset().top,
  }, 2000, function () {
    $('#mce-EMAIL').focus();
  });
}

```

# Actual Output

The beautified code actually looked like this:

```
function signUp() {
  $('html, body').animate({
    scrollTop: $('#home').offset().top,
  }, 2000, function() {
    $('#mce-EMAIL').focus();
  });
}
```

# Steps to Reproduce

1. Paste top code block into Atom
2. Ensure Beautifier and Linter [steelbrain] are installed
3. Beautify code and check linter issues

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

Please note, there are two errors in the code according to linter.

1. Space after the work function
2. New line after the last moustache

**Comment by szeck87** [comment]
For the second issue with newlines, check Atom Beautify's settings under JavaScript and make sure the option "End with newline" is unchecked.

Also check the "whitespace" package settings.  There is an option there "Ensure Single Trailing Newline" that might be causing that.

I'm looking into the first one with the space.

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
