### ISSUE TITLE
Install error: code ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by celson** [Glavin001/atom-beautify#2084]
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code **ERR_STREAM_WRITE_AFTER_END**
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.atom/.apm/_logs/2018-03-14T14_06_37_400Z-debug.log

Debug.log -> https://pastebin.com/y1S1JcaW

**Comment by szeck87** [comment]
I've never seen an error like that when installing Atom Beautify.  I guess I would first try closing Atom completely, running `apm clean` from the command line/terminal, open Atom back up and try again.

**Comment by celson** [comment]
I closed Atom, then uninstalled and removed the .atom directory.
I reinstalled Atom.
I ran `apm clean` and then`apm install atom-beautify` and gave the same error:

```
$ apm install atom-beautify
(node:13375) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing atom-beautify to /home/celson/.atom/packages ✗

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx/.atom/.apm/_logs/2018-03-16T19_41_20_830Z-debug.log
```
Are there any logs that I can get to help with the analysis?

**Comment by celson** [comment]
Today I updated my S.O. and rebooted, then I opened the Atom and tried to install atom-beautify and worked fine! Can close this issue please.

**Comment by L08-cshwong-5012345678** [comment]
I've got the same problem and cannot solve it.  My OS is updated and I reboot, start Atom (version 1.30.0x64) in administrator mode, but I still get the similar problem when I try to install atom-beautify.  I copy the output below.  Please help.
(p.s. The log told me to include a log file "C:\Users\helen\AppData\Local\Temp\apm-install-dir-118731-8936-osmwji.8gil4bo6r\npm-debug.log" but however there is no such a path in my computer)

Installing “atom-beautify@0.33.0” failed.Hide output…

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\helen\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\helen\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\helen\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\helen\\.atom\\.apmrc" "install" "C:\\Users\\helen\\AppData\\Local\\Temp\\d-118731-8936-1gvjnrt.72nunb3xr\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\helen\.atom\.apm\marko\4.13.3\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\helen\.atom\.apm\marko\4.13.3\package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\helen\AppData\Local\Temp\apm-install-dir-118731-8936-osmwji.8gil4bo6r\npm-debug.log_

**Comment by L08-cshwong-5012345678** [comment]
Sorry I don't know what is apm clean (grateful if you can tell me).
However, just now I install the beta Atom and then install atom-beautify (v0.33.0) and it works now!

**Comment by szeck87** [comment]
Open your terminal or command prompt and run the command `apm clean`.

**Comment by L08-cshwong-5012345678** [comment]
I see.  got it.  THanks.

**Comment by yswtrue** [comment]
I have the same problem too. And I had ran apm clean.

Installing “atom-beautify@0.33.0” failed.Hide output…

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Linux 4.18.5-arch1-1-ARCH
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ysw/.atom/.apm/.apmrc" "--userconfig" "/home/ysw/.atom/.apmrc" "install" "/tmp/d-11881-6150-6gqged.pijtvdvx6r/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/ysw/.atom/.apm/marko/4.13.3/package.tgz archive: ENOENT: no such file or directory, open '/home/ysw/.atom/.apm/marko/4.13.3/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11881-6150-loptfs.gqnpq1if6r/npm-debug.log

**Comment by tobml** [comment]
Same issue here

**Comment by josias-r** [comment]
Same issue here.

**Comment by szeck87** [comment]
Please watch https://github.com/Glavin001/atom-beautify/issues/2213.

**Comment by Paul020** [comment]
I went to this folder:
/Users/user/.atom/.apm/marko
Renamed the 4.14.4 folder I saw there to 4.14.3. and ran the install of Beautify again without errors.
