### ISSUE TITLE
filename not passed to clang-format

### ISSUE THREAD

**Issue by banjo74** [Glavin001/atom-beautify#2085]
# Description

If clang-format is configured to support header ordering, then it needs to know the name of the file so that it puts what it calls the main header file at the top.  When clang-format is invoked through beautifier it doesn't get the name of the file, it just gets the dumped file.

# Input Before Beautification

This is what the code looked like before:

B.cpp:
```
#include "B.hpp"
#include "A.hpp"
```

# Expected Output

The beautified code should have looked like this:

```
#include "B.hpp"
#include "A.hpp"
```

# Actual Output

The beautified code actually looked like this:

```
#include "A.hpp"
#include "B.hpp"
```

# Steps to Reproduce

1. Setup a directory with .clang-format and B.cpp from Gist linked at bottom.
2. Run command `Atom Beautify: Beautify Editor` on B.cpp
3. Compare this to code that results from running clang-format directly on B.cpp.

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

[https://gist.github.com/banjo74/dcfe5da4ed1a732f08a064450d6b0db1](https://gist.github.com/banjo74/dcfe5da4ed1a732f08a064450d6b0db1)

**Comment by szeck87** [comment]
I spent quite some time just trying to figure out this implementation.  I don't quite understand what is meant by this comment:  https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/clang-format.coffee#L55-L66, specifically "we HAVE TO generate the temp file in THE SAME directory as the editing file".  All I see it doing is making a duplicate in the same directory as the one you're editing.  And it doesn't even work when the file isn't saved.

I'll try to find some time to fix this, but we're in the middle of revamping Atom Beautify to use [Unibeautify](https://github.com/Unibeautify/unibeautify) at it's core.  That will hopefully fix a lot of issues, and make it easier to maintain in the long run.

**Comment by banjo74** [comment]
I added an updated version of clang-format.coffee to the gist above.  I don't have time to integrate it now.  This does the trick for me w/out dumping the file.  There don't appear to be any tests for clang-format so I don't know how to verify the fix.  I'm hoping that there is someone that is more comfortable contributing to this plugin that will pick it up from here.  Thanks.
