### ISSUE TITLE
CSSComb support

### ISSUE THREAD

**Issue by alem0lars** [Glavin001/atom-beautify#209]
The current CSS beautifier is not really flexible.

I think [CSScomb](http://csscomb.com) would be much better since it's a more [configurable](http://csscomb.com/config) and flexible beautifier.

We can take a look at our people implemented it in atom, here there are some examples:
- `atom-css-comb`
- `css-comb`

Thanks

**Comment by prettydiff** [comment]
@alem0lars the links provided for CSScomb resolve to 404 pages. Is there some other location for CSScomb?

**Comment by alem0lars** [comment]
Yes: [Github page](https://github.com/csscomb/csscomb.js)

**Comment by danielbayley** [comment]
+1

**Comment by Glavin001** [comment]
Links to existing Atom packages:
- [atom-css-comb](https://atom.io/packages/atom-css-comb)
- [css-comb](https://atom.io/packages/css-comb)
- [atom-csscomb](https://atom.io/packages/atom-csscomb)

**Comment by Glavin001** [comment]
CSScomb will be included in v0.26.0

To switch from `JS Beautify` (CSS)` or `Pretty Diff` (SCSS/Sass/LESS) to using `CSScomb`, you will go into Atom Beautify package settings and find the option for `Language Config - <Your Desired Language, CSS, etc> - Default Beautifier` and select `CSScomb`.

CSScomb looks for a `.csscomb.json` file in your Atom's first project directory. If it does not find one, or if importing it fails, it will fallback to `csscomb` predefined configuration.

**Comment by Glavin001** [comment]
Published to v0.26.0

**Comment by alem0lars** [comment]
Thanks very much :smile:

**Comment by DanielJoyce** [comment]
Buggy, doesn't seem to reload .csscomb.json sometimes.

**Comment by wyudong** [comment]
It must restart Atom to let custom `configPath` to take effect.

**Comment by Glavin001** [comment]
@DanielJoyce : The current implementation caches `.csscomb.json` and would require reloading Atom to clear cache: https://github.com/Glavin001/atom-beautify/pull/623/files#diff-da1ec4e677f98ecd91454c8d30ff68eaR33
Using `.csscomb.cson` does not appear to cache and should work without reloading: https://github.com/Glavin001/atom-beautify/pull/623/files#diff-da1ec4e677f98ecd91454c8d30ff68eaR31
Please submit a Pull Request implementing anything fixes you might have.

**Comment by robsonenke** [comment]
> CSScomb looks for a .csscomb.json file in your Atom's first project directory.

Just wondering, why doesn't it looks for the file in the project we're actually in?

**Comment by Glavin001** [comment]
@robsonenke it was not implemented like that in the Pull Request #623. Feel free to submit a Pull Request to fix it! Thanks in advance!
