### ISSUE TITLE
C++ - Uncrustify Throws Unknown Symbol Errors

### ISSUE THREAD

**Issue by MohanaManikandan** [Glavin001/atom-beautify#2090]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
#include <iostream>

int main()
{
std::cout << "Wellllll.....\n";
  return 0;
}
```

# Expected Output

The beautified code should have looked like this:

```
#include <iostream>

int main()
{
	std::cout << "Wellllll.....\n";
  	return 0;
}
```

# What I Get

/home/manikandan/.atom/packages/atom-beautify/src/beautifiers/uncrustify/default.cfg:103 
Unknown symbol 'indent_ctor_init_leading' 
...
...
...

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a [link](https://gist.github.com/MohanaManikandan/5a0c8b59ef64a085768964059e698117) to the `debug.md` Gist

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
I'll look at this when I get home. Can you confirm what version of Uncrustify you are using? It looks like 0.59.0 from the logs, can you try updating it?

**Comment by MohanaManikandan** [comment]
I guess I'm with the latest version of uncrustify. I tried a clean install of uncrustify and yet this issue pops up while beautifying C++ Code. 

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
uncrustify is already the newest version (0.59+dfsg1-1.1).
```

**Comment by szeck87** [comment]
@MohanaManikandan how are you installing Uncrustify?  Through a dependency manager or manually?

**Comment by MohanaManikandan** [comment]
I did it manually using apt

**Comment by szeck87** [comment]
I don't know why it's installing such an old version.  0.59 is 7 years old.  https://sourceforge.net/projects/uncrustify/files/uncrustify/.  I would try another way in updating it.  I'm not on Linux so I can't provide any pointers.

**Comment by MohanaManikandan** [comment]
@szeck87  I Just installed Uncrustify 0.65 using deb through this [link](https://www.ubuntuupdates.org/package/core/artful/universe/base/uncrustify). Beautify works flawlessly. Thanks for pointing out the issue :+1:

**Comment by szeck87** [comment]
@MohanaManikandan Good to hear!  I'll make a note to ensure Uncrustify is up to a 0.6x release before using.

**Comment by MohanaManikandan** [comment]
@szeck87 Yup. That would help a lot !
