### ISSUE TITLE
How to make curly braces show up on a different line ?

### ISSUE THREAD

**Issue by AhmedHelalAhmed** [Glavin001/atom-beautify#2093]
Basically what’s written in the topic; long story short is that I prefer writing the (opening) curly braces on separate lines from the block of code under which they belong.

i.e.

if (someBoolean)
{
//do things
}
NOT

if (someBoolean){
// do things
}

????

**Comment by szeck87** [comment]
What language?  If Javascript, set Brace Style to expand.

![screen shot 2018-03-27 at 9 31 56 am](https://user-images.githubusercontent.com/8315038/37974132-bc6f134a-31a1-11e8-9029-07641f1b7df7.png)

**Comment by AhmedHelalAhmed** [comment]
But this is for Javascript only ? how about php ?

**Comment by szeck87** [comment]
You'll need to create a configuration file for PHP CS Fixer with how you want `braces` configured.  See https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by sayand0122** [comment]
What about cpp?
How can i get the new line braces format in atom for cpp language?
