### ISSUE TITLE
Unable to install atom-beautify

### ISSUE THREAD

**Issue by gabumoh** [Glavin001/atom-beautify#2094]
```
Installing “atom-beautify@0.32.2” failed.Hide output…

npm ERR! tar.unpack error reading /tmp/d-118227-19898-1f254hm.itwy4lsor/package.tgz
npm ERR! addLocal Could not install /tmp/d-118227-19898-1f254hm.itwy4lsor/package.tgz
npm ERR! Linux 4.13.0-37-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/gabriel/.atom/.apm/.apmrc" "--userconfig" "/home/gabriel/.atom/.apmrc" "install" "/tmp/d-118227-19898-1f254hm.itwy4lsor/package.tgz" "--runtime=electron" "--target=1.6.16" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118227-19898-58l9i9.faorctbj4i/npm-debug.log
```

That's the error I've been having for the past day trying to install atom-beautify

**Comment by szeck87** [comment]
Close Atom completely and try running these commands from the terminal:

`apm clean`
`npm cache verify`

Then try again.

**Comment by gabumoh** [comment]
@szeck87 I'm still getting the same error

**Comment by gabumoh** [comment]
I've fixed the issue.
This was where I found my solution
https://github.com/atom/atom/issues/11798

**Comment by francosmp** [comment]
In windows i have

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\iFranco\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\iFranco\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\iFranco\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\iFranco\\.atom\\.apmrc" "install" "C:\\Users\\iFranco\\AppData\\Local\\Temp\\d-118731-7472-1rzyzv6.ry0uj714i\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\iFranco\.atom\.apm\marko\4.13.3\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\iFranco\.atom\.apm\marko\4.13.3\package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\iFranco\AppData\Local\Temp\apm-install-dir-118731-7472-1n6hv2y.ak2xz5b3xr\npm-debug.log




Issue: Atom cannot install atom-beautify 2018/08/31 #2213

**Comment by achmdnov** [comment]
I have tried to install atom-beautify, but it is failed and I got this message:

Installing “atom-beautify@0.33.4” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...s5R3faGZC94HXqk2w8how'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nova\.atom\.apm\_logs\2020-02-01T07_12_32_929Z-debug.log

how can i solve this?

**Comment by sintaawalisasng** [comment]
I'm almost frustrated
guys you only need to delete the .apm folder inside the .atom folder
Please try cz that's work for me:)))

**Comment by christinapap13** [comment]
I have tried to install atom-beautify and i got this message:

Installing “atom-beautify@0.33.4” failed.Hide output…
undefined

How can i solve this?
