### ISSUE TITLE
Add CMakeList.txt support

### ISSUE THREAD

**Issue by 01BTC10** [Glavin001/atom-beautify#2102]
> Atom Beautify could not determine a supported beautifier to handle this file with grammar "CMake Listfile" and extension "txt". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

Hi! There is a nice formater here: https://github.com/cheshirekow/cmake_format

Thanks!

**Comment by shearer12345** [comment]
cmake-format works pretty well for me (mostly).

#554 discusses this, so I'll link this issue in that issue.
