### ISSUE TITLE
Gherkin .feature file tables not aligned correctly

### ISSUE THREAD

**Issue by zmorris** [Glavin001/atom-beautify#2105]
# Description

The results of beautification are not what I expect.  Previously reported at https://github.com/Glavin001/atom-beautify/issues/665 and https://github.com/Glavin001/atom-beautify/issues/986 but not fixed.  Example taken from https://github.com/acuminous/yadda/blob/master/examples/mocha-sync/features/bottles.feature and pared down for clarity.

# Input Before Beautification

This is what the code looked like before:

```
Feature: Mocha Synchronous Example

    Scenario Outline: [N] bottles are standing on a wall
        Given [N] green bottles are standing on the wall
        When 1 green bottle accidentally falls
        Then there are [N-1] green bottles standing on the wall

        Examples:
            | N | N-1 |
            | 100 | 99 |
            | 99 | 98 |
            | 10 | 9 |
```

# Expected Output

The beautified code should have looked like this:

```
Feature: Mocha Synchronous Example

    Scenario Outline: [N] bottles are standing on a wall
        Given [N] green bottles are standing on the wall
        When 1 green bottle accidentally falls
        Then there are [N-1] green bottles standing on the wall

        Examples:
            | N   | N-1 |
            | 100 | 99  |
            | 99  | 98  |
            | 10  | 9   |
```

# Actual Output

The beautified code actually looked like this:

```
Feature: Mocha Synchronous Example

    Scenario Outline: [N] bottles are standing on a wall
        Given [N] green bottles are standing on the wall
        When 1 green bottle accidentally falls
        Then there are [N-1] green bottles standing on the wall

        Examples:
            | N | N-1 |
            | 100 | 99 |
            | 99 | 98 |
            | 10 | 9 |
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/zmorris/d822e86aee1cdc2624e526e1394072f6

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@Glavin001 Perhaps this would be a good alternative?  Not sure how to coffeescript it. 
 https://github.com/kozhevnikov/cucumber-pretty

**Comment by JthenG9** [comment]
This would be really nice to have, current formatting is not horrible when you have a small table, but once it grows it can be pretty hard to read.

**Comment by zmorris** [comment]
Also the reason I submitted this (as it doesn't seem like that serious of an issue at first glance) is that QA testers need to have some kind of autoformatter running so they don't have to waste time styling cucumber files by hand.  This unbeautified table formatting blocks them from autorunning atom-beautify on every save (making it generally useless for cucumber files currently).  So this is a much higher priority fix than it may seem.  Otherwise, keep up the good work!
