### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by musayazlik** [Glavin001/atom-beautify#2107]
https://resmim.net/f/uJs1cO.png

I have a problem with the above link in my Atom.io editor. How can I solve this problem?  I installed the plug-in, but the problem was not resolved.

**Comment by szeck87** [comment]
What OS are you on and how did you install PHP-CS-Fixer?  Do you also have PHP installed?

**Comment by musayazlik** [comment]
I am using windows 10. From the upload location in the program. xampp is installed.

**Comment by szeck87** [comment]
You'll need to specify the path to PHP and PHP-CS-Fixer binary/script.  Go to Packages -> Atom Beautify -> Settings and expand Executables.  Scroll down until you see PHP and right under that PHP-CS-Fixer.  Expand both of those and put the path to each there.

**Comment by musayazlik** [comment]
https://resmim.net/f/PUgiNb.png         Is that it?

**Comment by szeck87** [comment]
No you scrolled down a bit too far.

![screen shot 2018-04-04 at 10 35 08 am](https://user-images.githubusercontent.com/8315038/38318016-076bb0f8-37f4-11e8-9903-983ea16a72a1.png)
![screen shot 2018-04-04 at 10 35 26 am](https://user-images.githubusercontent.com/8315038/38318017-077e0a14-37f4-11e8-932f-cae5dc72d40e.png)

**Comment by musayazlik** [comment]
https://resmim.net/f/2WxAtW.png    Now I've found the right place. I filled it like this. The problem is solved, but automatic correction is not working. 

https://resmim.net/f/WdzH7u.png Like this one. What is keyboard shortcut?

**Comment by szeck87** [comment]
Run the debug command and copy/paste its contents to a GitHub gist and link it here to this issue.  

Packages -> Atom Beautify -> Debug -> Hit OK button a couple of times.  It will generate a new editor tab to copy/paste.

**Comment by musayazlik** [comment]
OK. The file was created. I have my own custom codes in the file. https://resmim.net/f/FOv7Zz.png

**Comment by szeck87** [comment]
@musayazlik I need the whole file.  Please copy and paste those contents into a GitHub gist (https://gist.github.com/) and link that gist to this issue.

**Comment by musayazlik** [comment]
@szeck87 OK I did it.

**Comment by Glavin001** [comment]
@musayazlik : In the future, please copy text as text into this GitHub issue or a [Gist](http://gist.github.com/). Also images can be uploaded to GitHub directly as well instead of using https://resmim.net/ : https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by musayazlik** [comment]
@Glavin001 I did not know how to upload pictures. I learned now. Thank you.

**Comment by musayazlik** [comment]
![screenshot_1](https://user-images.githubusercontent.com/33998073/38333964-bcda59bc-3862-11e8-88bc-9c263330b7ed.png)

You're talking about the location where the plugin is loaded.

**Comment by szeck87** [comment]
@musayazlik you need to install PHP-CS-Fixer itself, not the Atom extension.  https://github.com/FriendsOfPHP/PHP-CS-Fixer/#installation

**Comment by musayazlik** [comment]
What did you write in the php-cs-fixer section? Could you send a screenshot?

**Comment by andres-conforti** [comment]
> What did you write in the php-cs-fixer section? Could you send a screenshot? I am using windows. how to install.

Not sure if you still need help, but at least this might help someone else using windows with xampp.

Once you are here: https://resmim.net/f/2WxAtW.png
On php write this: [this is your install location]\xampp\php\php.exe
and for the PHP-CS-Fixer, first go here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/#installation
download php-cs-fixer.phar, place that file as it is in the same location that php.exe is (the location you just wrote above) and then you can complete the PHP-CS-Fixer tab with it.
For example: [this is your install location]\xampp\php\php-cs-fixer-v2.phar

This is how i have it: https://i.imgur.com/ftTAahZ.png

**Comment by Rovert88** [comment]
> > ¿Qué escribiste en la sección php-cs-fixer? ¿Podrías enviar una captura de pantalla? Estoy usando ventanas. cómo instalar.
> 
> No estoy seguro de si aún necesita ayuda, pero al menos esto podría ayudar a otra persona a usar Windows con xampp.
> 
> Una vez que esté aquí: https://resmim.net/f/2WxAtW.png
> En php escriba esto: [esta es su ubicación de instalación] \ xampp \ php \ php.exe 
> y para PHP-CS-Fixer, primero vaya aquí : https://github.com/FriendsOfPHP/PHP-CS-Fixer/#installation
> descarga php-cs-fixer.phar, coloque ese archivo como está en la misma ubicación que php.exe (la ubicación que acaba de escribir arriba) ) y luego puede completar la pestaña PHP-CS-Fixer con él. 
> Por ejemplo: [esta es su ubicación de instalación] \ xampp \ php \ php-cs-fixer-v2.phar
> 
> Así es como lo tengo: https://i.imgur.com/ftTAahZ.png

@andres-conforti I did what you mentioned, the problem that said php cs fixer was not installed was corrected, however the code was not indented.

This is the debug information of atom-beautify:

"executables": {
        "php": {
            "path": "C:\\xampp\\php\\php.exe"
        },
        "php-cs-fixer": {
            "path": "C:\\xampp\\php\\php-cs-fixer-v2.phar"
        },

Do you know another way to make atom-beautify work?
