### ISSUE TITLE
Add link to "who's using" edit page in README

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#2115]
See https://github.com/unibeautify/website/edit/master/website/data/users.yml and https://unibeautify.com/users.html

**Comment by Glavin001** [comment]
@szeck87 false positive from issue-complete bot 😉

**Comment by prettydiff** [comment]
I do have an unusual story about this.  About 2 months after I started working at the bank (early fall 2017), my current civilian employer, a coworker scolded me when they saw me using VS Code.  Everybody should be using Atom because Atom Beautify is the best thing since sliced bread.
