### ISSUE TITLE
Spaces are being added in HTML documents at the wrong place, causing errors

### ISSUE THREAD

**Issue by xoelop** [Glavin001/atom-beautify#2116]
I'm using atom-beautify to beautify a HTML document. But it adds a space right at the worst place and it messes up the behaviour of the Flask app, which reports an error. 

The space is added right before editMenuItem. It does the same in other similar lines. It took me hours to realize where the error was coming from. I love beautify and this is a super weird error, would love to fix it so that other people also don't have to waste time on this as I did. 

I'm using Pretty Diff, but this also happens with JS Beautify. How could I fix this?

Thanks!!

______________________________________________________________________________________________ 

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<a href='{{url_for('editMenuItem', restaurant_id = restaurant.id, menu_id = i.id) }}'>Edit</a>
```

# Expected Output

The beautified code should have looked like this:

```
<a href='{{url_for('editMenuItem', restaurant_id = restaurant.id, menu_id = i.id) }}'>Edit</a>
```

# Actual Output

The beautified code actually looked like this:

```
<a href='{{url_for(' editMenuItem', restaurant_id = restaurant.id, menu_id = i.id) }}'>Edit</a>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/xoelop/a22444a34339d150946a68f9e5d17c56

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Should you be using single quotes for both the href and editMenuItem?

**Comment by xoelop** [comment]
I don't know. The template works well with either double and single quotes. But beautify inserts the space also in all of the cases, when it shouldn't do it in any of them, I think. Any ideas on how to fix it?

**Comment by szeck87** [comment]
If I use the opposite quote type around the href compared to editMenuItem, it doesn't insert the space.  So either:

<a href="{{url_for('editMenuItem', restaurant_id = restaurant.id, menu_id = i.id) }}">Edit</a>
<a href='{{url_for("editMenuItem", restaurant_id = restaurant.id, menu_id = i.id) }}'>Edit</a>

But I don't know what editMenuItem is in the context you are working on.
