### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by lgarcin** [Glavin001/atom-beautify#212]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Laurent\AppData\Local\atom\app-0.179.0\resources\app\src\atom.js:54:11)
LoadingView.module.exports.LoadingView.show (C:\Users\Laurent\.atom\packages\atom-beautify\lib\loading-view.coffee:38:11)
```

**Comment by Glavin001** [comment]
This has already been fixed. Please update Atom Beautify. See #191.
