### ISSUE TITLE
PACKAGE IS NOT INSTALLING

### ISSUE THREAD

**Issue by BLACKpanther786007** [Glavin001/atom-beautify#2120]
# Description

The results of beautification are not what I expect.

# Input Before Beautification
Actually this package is not installing properly its shows error while installation time and it takes lots
of time i am struct of it....

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@BLACKpanther786007 we need more information here.  What is the error you are receiving?

**Comment by Glavin001** [comment]
Can reopen when information is provided.
