### ISSUE TITLE
File Input Error Indent/Outdent [ BUG ]

### ISSUE THREAD

**Issue by cybertunnel** [Glavin001/atom-beautify#2122]
# Description
Get an error within Atom when Beautify is ran on a Shell Script item.
The results of beautification are not what I expect.

# Input Before Beautification
`echo /path/to/file | awk -F "\"" '/SearchForText/ {print $1}'`
This is what the code looked like before:
```
if [[ $var -eq 1 ]]; then
echo /path/to/file | awk -F "\"" '/SearchForText/ {print $1}'`
fi
```

# Expected Output

The beautified code should have looked like this:

```
if [[ $var -eq 1 ]]; then
     echo /path/to/file | awk -F "\"" '/SearchForText/ {print $1}'`
fi
```

# Actual Output

The beautified code actually looked like this:

```
if [[ $var -eq 1 ]]; then
echo /path/to/file | awk -F "\"" '/SearchForText/ {print $1}'`
fi
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. You will get an error when running Beautify
4. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>
Error is on `"\""` section, once I remove it, it doesn't error out.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Is that valid shell script?  What are the `"\""` and a single backtick at the end of that line doing?
