### ISSUE TITLE
Beautification of .java and .tex files not working Win10x64

### ISSUE THREAD

**Issue by g-uru** [Glavin001/atom-beautify#2123]
# Description

Beautification is not working due to an error.  Docker-for-Windows is installed.

# Debug

Here is a link to the `debug.md` Gist for .java-files: 
https://gist.github.com/g-uru/eaf58af41e869ff00969710f8eab0dbc
Here is a link to the `debug.md` Gist for .tex-files: 
https://gist.github.com/g-uru/e3841548538e12f10ffecb489cb345cc

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

# errors I see when I try to beautify from within atom

**_Latex (*.tex-files):_** 
`
Can't locate LatexIndent/Document.pm in @INC (you may need to install the LatexIndent::Document module) (@INC contains: /c/Users/*/AppData/Local/Temp /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at C:\Users\*\AppData\Roaming\MiKTeX\2.9\scripts\latexindent\latexindent.pl line 27. BEGIN failed--compilation aborted at C:\Users\*\AppData\Roaming\MiKTeX\2.9\scripts\latexindent\latexindent.pl line 27.
`

`
Can't locate LatexIndent/Document.pm in @INC (you may need to install the LatexIndent::Document module) (@INC contains: /c/Users/*/AppData/Local/Temp /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at C:\Users\*\AppData\Roaming\MiKTeX\2.9\scripts\latexindent\latexindent.pl line 27.
BEGIN failed--compilation aborted at C:\Users\*\AppData\Roaming\MiKTeX\2.9\scripts\latexindent\latexindent.pl line 27.
`

**_Java (*.java-files):_**

`
load_option_file: fopen(C:\Users\*\AppData\Local\Temp\11841-20196-f7tdbp.nxtsk.cfg) failed: No such file or directory (2) Unable to load the config file Try running with -h for usage information
`

`
load_option_file: fopen(C:\Users\*\AppData\Local\Temp\11841-20196-f7tdbp.nxtsk.cfg) failed: No such file or directory (2)
Unable to load the config file
Try running with -h for usage information
Hide Stack Trace
Error: load_option_file: fopen(C:\Users\*\AppData\Local\Temp\11841-20196-f7tdbp.nxtsk.cfg) failed: No such file or directory (2)
Unable to load the config file
Try running with -h for usage information
    at file:///C:/Users/*/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:23
    at tryCatcher (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\*\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
`

**Comment by szeck87** [comment]
@Glavin001 any ideas on this one?

```
docker [ 'run',
  '--volume',
  'C:\\Users\\*\\AppData\\Local\\Temp:/workdir',
  '--volume',
  'C:\\:/mountedRoot',
  '--workdir',
  '/workdir',
  'unibeautify/uncrustify',
  [ '-c',
    'C:\\Users\\*\\AppData\\Local\\Temp\\11841-20196-1goy557.m3s2.cfg',
    '-f',
    'C:\\Users\\*\\AppData\\Local\\Temp\\input11841-20196-yshg9j.mk7p.java',
    '-o',
    'C:\\Users\\*\\AppData\\Local\\Temp\\output11841-20196-1ufma3o.n62g.java',
    '-l',
    'JAVA' ] ]
```

**Comment by g-uru** [comment]
To avoid any eventual confusion, please note that I changed the Username to * for privacy reasons..

**Comment by g-uru** [comment]
So 11 days have passed, any news regarding this problem?

**Comment by g-uru** [comment]
For Latex I was able to fix it by properly installing and configuring perl and then installing the missing modules. I fixed uncrustify too, by removing the docker images and  installing uncrustify manually.

**Comment by dumblole** [comment]
I have the same problem but with java

**Comment by dumblole** [comment]
Like the error I get is the exact same

**Comment by dumblole** [comment]
@g-uru I installed uncrustify manually but I get the same error, could you help me?

**Comment by g-uru** [comment]
Well its not really a fix rather a workaround, because I was trying to get it work with docker.. Anyway:

- Download Uncrustify from [here](https://sourceforge.net/projects/uncrustify/files/uncrustify/)
- Unpack into some location, e.g. C:\Uncrustify
- Add this location to your your PATH like [so](https://prnt.sc/k0ckpr)
- Go to atom-beautify settings -> Executables -> Uncrustify and specify the absolute path to your uncrustify.exe inside your uncrustify folder
- Still in atom-beautify settings -> Scroll down further to Java settings and specify the absolute path to one of the cfgs (e.g. sun.cfg) inside the cfg folder of the uncrustify directory
- eventually restart atom

If you really start developing you should start using a proper IDE for Java such as [eclipse](https://www.eclipse.org/) or [intellij](https://www.jetbrains.com/idea/)

**Comment by dumblole** [comment]
tysm @g-uru
