### ISSUE TITLE
Could not find 'sqlformat'. The program may not be installed.

### ISSUE THREAD

**Issue by databasekevin** [Glavin001/atom-beautify#2128]
# Description

sqlformat is installed and working on my computer. I cannot figure out how to get beautify to recognize it for some reason. Please help - installed both python/sqlformat and atom.beautify this morning and have been trying to figure this out all day.

> Error: Could not find 'sqlformat'. The program may not be installed.
>     at Function.Executable.commandNotFoundError (file:///C:/Users/kkimm/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:10)
>     at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/kkimm/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
>     at file:///C:/Users/kkimm/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
>     at tryCatcher (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
>     at Async._drainQueue (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
>     at Async._drainQueues (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
>     at Async.drainQueues (C:\Users\kkimm\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:109:7)
> 

**beautify location:**
C:\Users\kkimm\.atom\packages\atom-beautify\src\beautifiers

**sqlformat location:**
C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts

**Where.exe result**

> Microsoft Windows [Version 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
> 
> C:\Users\kkimm>where.exe sqlformat
> INFO: Could not find files for the given pattern(s).

**SQLPARSE installed and SQLFORMAT checked to work:**

> C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts>pip install --upgrade sqlparse
> Requirement already up-to-date: sqlparse in c:\users\kkimm\appdata\local\program
> s\python\python36-32\lib\site-packages (0.2.4)
> 
> C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts>sqlformat test.
> sql --reindent
> select *
> from tables
> where name = 'john';

**CMD PATH:**
C:\Users\kkimm>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;c:\oracle\product\11.2.0\dbhome_1\bin;c:\ora
cle\product\11.2.0\client_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Pro
gram Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32
\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sybase\
shared\PowerBuilder;C:\Program Files (x86)\Sybase\shared\PowerBuilder\x64;C:\Pro
gram Files (x86)\Sybase\PowerBuilder 12.6;C:\Windows\Microsoft.NET\Framework\v4.
0.30319;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
 (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\In
tel(R) Management Engine Components\IPT;C:\Program Files (x86)\Sybase\PowerBuild
er 12.0;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framewo
rk\v2.0.50727;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\F
ramework\v2.0.50727;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Fil
es\Intel\WirelessCommon\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Intel
\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\kkimm\Ap
pData\Local\Programs\Python\Python36-32;C:\Users\kkimm\AppData\Local\atom\bin

**Atom PATH:**
process.env.PATH
"C:\ProgramData\Oracle\Java\javapath;c:\oracle\product\11.2.0\dbhome_1\bin;c:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sybase\shared\PowerBuilder;C:\Program Files (x86)\Sybase\shared\PowerBuilder\x64;C:\Program Files (x86)\Sybase\PowerBuilder 12.6;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Sybase\PowerBuilder 12.0;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32;C:\Users\kkimm\AppData\Local\atom\bin"

# Input Before Beautification

This is what the code looked like before:

```
select * from tables where name = 'john';
```

# Expected Output

The beautified code should have looked like this:

```
select *
from tables
where name = 'john';
```

# Actual Output

The beautified code actually looked like this:

```
N/A
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/databasekevin/23d8fd6311a77d43f61b6863f96e6f9f

# Checklist

I have:
- [ X ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ X ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ X ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ X ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ X ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@databasekevin does the `sqlformat` command work anywhere other than `C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts>`?

**Comment by szeck87** [comment]
@databasekevin ok thanks.  Unfortunately sqlformat was never converted to the proper executable format for Atom Beautify.  Can you add `sqlformat` to your path like you did with Python and see if the command works anywhere else?  If it does, then try Atom Beautify again.

**Comment by databasekevin** [comment]
@szeck87 Do you mean add this as another system variable - C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts\sqlformat.exe

**Comment by szeck87** [comment]
@databasekevin correct.

**Comment by databasekevin** [comment]
@szeck87 No luck.
> C:\Users\kkimm>echo %PATH%
> C:\ProgramData\Oracle\Java\javapath;c:\oracle\product\11.2.0\dbhome_1\bin;c:\ora
> cle\product\11.2.0\client_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Pro
> gram Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32
> \Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sybase\
> shared\PowerBuilder;C:\Program Files (x86)\Sybase\shared\PowerBuilder\x64;C:\Pro
> gram Files (x86)\Sybase\PowerBuilder 12.6;C:\Windows\Microsoft.NET\Framework\v4.
> 0.30319;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
> :\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
>  (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\In
> tel(R) Management Engine Components\IPT;C:\Program Files (x86)\Sybase\PowerBuild
> er 12.0;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\Framewo
> rk\v2.0.50727;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Windows\Microsoft.NET\F
> ramework\v2.0.50727;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Fil
> es\Intel\WirelessCommon\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Intel
> \WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\kkimm\Ap
> pData\Local\Programs\Python\Python36-32;C:\Users\kkimm\AppData\Local\atom\bin;C:
> \Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts\sqlformat.exe
> 
> C:\Users\kkimm>where.exe sqlformat
> INFO: Could not find files for the given pattern(s).

**Comment by szeck87** [comment]
@databasekevin ok, you can delete that variable I suggested to add.  Did you modify `Path` variable to add `;%PYTHON_HOME%\;%PYTHON_HOME%\Scripts\` at the end of it by chance?  I'm reading through this: https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation

**Comment by databasekevin** [comment]
I had missed the %PYTHON_HOME%\Scripts\. Good catch!

![image](https://user-images.githubusercontent.com/38899976/39872280-7681b78c-5435-11e8-9274-762f2a7cb593.png)

**Comment by databasekevin** [comment]
@szeck87 atom.beautify is working now. Thank you so so much for all of your help.

**Comment by szeck87** [comment]
Great to hear!
