### ISSUE TITLE
Could not find 'gofmt'. The program may not be installed.

### ISSUE THREAD

**Issue by Ewocker** [Glavin001/atom-beautify#2130]
## Description
keep getting : 
Could not find 'gofmt'. The program may not be installed.

while:
```
$ which gofmt
/Users/ylin/.gvm/gos/go1.10.2/bin/gofmt
```

Using GVM2 for managing GO version, which should not affect anything on atom-beautify side as long as the absolute path is there.

**Comment by szeck87** [comment]
@Ewocker do `gofmt` commands work from directory?

**Comment by Ewocker** [comment]
Yep...
From terminal or the terminal plugin inside atom both works

**Comment by szeck87** [comment]
Sorry I mistyped, but `gofmt` does run from ANY directory on your machine?  Meaning its on your environment path?

**Comment by Ewocker** [comment]
Yes, I was able to lint (I mean format go here) any .go file from terminal.
I am not sure if it is related to using GVM2, but I suppose not because what atom-beautify essentially needs is to be able to run gofmt which in my case is there working on any terminal session but not atom-beautify.

**Comment by szeck87** [comment]
Can you run the Debug command for atom beautify and make a gist and link to this issue?

**Comment by Ewocker** [comment]
Sorry was not sure about the Debug command part of it, where can I find instructions on that?

**Comment by szeck87** [comment]
Open a go file and from the top menu in Atom:  Packages -> Atom Beautify -> Debug.  Click OK a couple of times and it will generate a markdown file in a new buffer.  Copy/paste the contents of that file into a gist here on GitHub and post a link to it.

**Comment by GetRektByMe** [comment]
Also having this issue, as the other person hasn't replied @szeck87 I've done what you've asked of them. The gist is [here](https://gist.github.com/GetRektByMe/bc538043e071d68585152b5031743ce6)!

Here's me running `which gofmt`
```
recchan@Recchans-PC:~/Dev/Go/src/github.com/getrektbyme/honzuki$ which gofmt
/home/recchan/.goenv/shims/gofmt
```

**Comment by szeck87** [comment]
@GetRektByMe and `gofmt` works from any directory in your terminal?
