### ISSUE TITLE
Empty class cause error

### ISSUE THREAD

**Issue by ballanz89** [Glavin001/atom-beautify#2131]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Title</title>
    </head>

    <body class=" ">
    <a id="start"></a>

    </body>
</html>

```

# Expected Output

The beautified code should have looked like this:

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Title</title>
    </head>
    <body class=" ">
        <a id="start"></a>
    </body>
</html>

```

# Actual Output

The beautified code actually looked like this:

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Title</title>
    </head>
    <body class=" ">
        <a id=" start"="start""></a>
</body>
</html>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ballanz89/5287f25c1f8fdc85ca9f4a3b4a425ab6

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@prettydiff I recreated this on prettydiff.com.  @ballanz89 you can change your default beautifier for HTML files to be JSBeautify instead.

**Comment by ballanz89** [comment]
It's still an issue.
