### ISSUE TITLE
Ruby code doesn't beautify after pressing Ctrl + Alt + B

### ISSUE THREAD

**Issue by aruprakshit** [Glavin001/atom-beautify#2138]
# Description
When I press Ctrl + Alt + B, I see a progress window, and then a warning:

The "Ruby - Rubocop Path (rubocop_path)" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "Rubocop" labelled "Path" in Atom-Beautify package settings.

<img width="1138" alt="screen shot 2018-05-21 at 5 17 42 pm" src="https://user-images.githubusercontent.com/3428463/40306165-3ee44c42-5d1b-11e8-8436-2559abb062b4.png">

After that my file content left as it was before. No beautification applied.

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
# frozen_string_literal: true

# This class is doing some heavy work
class HeavyWorker
  def work
    500.times { |i| i.times {} }
    more_work
  end

  def more_work
    500.times { |i| i.times {} }
end
end

```

# Expected Output

The beautified code should have looked like this:

```
# frozen_string_literal: true

# This class is doing some heavy work
class HeavyWorker
  def work
    500.times { |i| i.times {} }
    more_work
  end

  def more_work
    500.times { |i| i.times {} }
  end
end

```

# Actual Output

The beautified code actually looked like this:

```
# frozen_string_literal: true

# This class is doing some heavy work
class HeavyWorker
  def work
    500.times { |i| i.times {} }
    more_work
  end

  def more_work
    500.times { |i| i.times {} }
end
end
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/aruprakshit/7cfa781169850350ba1b29939cdc8d40

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by ggriffin** [comment]
@aruprakshit Did you follow the instructions and verify that the rubocop executable is set up properly on your system? e.g.:
`$ which rubocop`
`/Users/me/.rvm/gems/ruby-2.4.1@global/bin/rubocop`

**Comment by aruprakshit** [comment]
@ggriffin Yes I did. Does that mean every time, I switch to different Ruby version using Rvm, I need to go and change the settings manually in Atom? Ca't it detect from the current Ruby version selected by RVM?

**Comment by szeck87** [comment]
@aruprakshit Sorry I missed this issue somehow.  That message is saying that the place to specify the path to the executable has changed.  Assuming you have it under `Ruby -> Rubocop Path` right now, remove it from there and put it under `Executables -> Rubocop -> Binary/Script Path`.

**Comment by thyeun** [comment]
If anyone still having this issue, kindly see the below pic.

``` Setting -> Executables -> Rubocop -> the_path_rubocop```

![screenshot_2018-07-16_01-40-26](https://user-images.githubusercontent.com/1939446/42736431-75bf3962-8899-11e8-98f2-818e32f21515.png)
