### ISSUE TITLE
Not working with codebase on Samba network share

### ISSUE THREAD

**Issue by Toeplitz** [Glavin001/atom-beautify#2143]
# Description

When trying to run atom-beautify on a project that is mapped on a Samba network share, the beautify hangs with "Beautification in progress" forever.

**On the same setup everything works as expected if the project is stored on the local disk.**

I use autopep3 on python code on a windows machine.

The samba network share is mapped as this:

```
[share]
   path = /home/user/project
   available = yes
   valid users = user
   read only = no
   browseable = yes
   public = no
   writable = yes
   create mask = 0700
   directory mask = 0700
```

# Input Before Beautification

This is what the code looked like before:

```
        now = datetime.now()
        path = '/data'
        curpath = path + '/' + str(now.year) + '/' + str(now.month) + '/' + str(now.day)

```

# Expected Output

The beautified code should have looked like this:

```
        now = datetime.now()
        path = '/data'
        curpath = path + '/' + str(now.year) + '/' + \
            str(now.month) + '/' + str(now.day)
```

# Actual Output on project from Samba share

Same as input Before Beautification.

# Debug

When running the Beautify debug nothing happens and the beautify tool also hangs with "Beautification in progress".

**Comment by Toeplitz** [comment]
Following the instructions on https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md, there is nothing in the clipbord after running the debugging command (as I already stated).

**Comment by szeck87** [comment]
@Toeplitz can you open the developer tools and see if there is an error there?

**Comment by Toeplitz** [comment]
Yes, I found a difference and an error. See attached the two logs. One is when files are on the network drive and beautifier fails, the other is on the local disk when it works.

[log_local_disk.txt](https://github.com/Glavin001/atom-beautify/files/2040298/log_local_disk.txt)
[log_network_disk.txt](https://github.com/Glavin001/atom-beautify/files/2040299/log_network_disk.txt)

**Comment by szeck87** [comment]
Is that the only error?

**Comment by Toeplitz** [comment]
Yes, I'm showing the full log from the "console" in the dev window.
