### ISSUE TITLE
Could not find 'docker'. The program may not be installed error

### ISSUE THREAD

**Issue by Ptheguy** [Glavin001/atom-beautify#2145]
# Description

I have installed `atom-beautify` from the `Atom` packages tab like any other normal package. I have installed `uncrustify` on my machine too (win 10). I can confirm that it works because `where.exe uncrustify` returns the correct path to the executable. I have given `atom-beautify` the correct path to the configuration files for `uncrustify`. Nonetheless, when I try to save my `.cpp` files, I get the error "Could not find docker. The program may not be installed."

Indeed, the issue is obvious. I need to install `docker`. That's not what I'm asking here. I have been using `atom-beautify` for a while now and have gone through setting up twice. I have never had this issue with `docker`. It's the first time I'm hearing about it. 

Is this a bug? Or, is this a recent new implementation that now requires me to install some third-party app (so called `docker`) to get it working?

Just saying, before it used to be install `atom-beatify`, install `uncrustify`, give the correct configuration files' paths, and it's done. Now, there's `docker`! Note that [#1687](https://github.com/Glavin001/atom-beautify/issues/1687) and [#1441](https://github.com/Glavin001/atom-beautify/issues/1441) seem to be close relatives of my problem, but I wasn't able to seek what I was looking for there. My advanced apologies if somehow I'm posting a duplicate question.

# Debug

Here is a link to the [debug.md](https://gist.github.com/Ptheguy/8357e1e2289a87ed4df897be5b87e52d#file-debug-md)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by szeck87** [comment]
Ideally it shouldn't be displaying an error around Docker, that is likely caused by https://github.com/Glavin001/atom-beautify/pull/2129.  @Glavin001 we should fix that.

The relevant error from the log is:
```
2018-05-29T19:30:26.413Z - debug: [] error Error: spawn uncrustify ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
2018-05-29T19:30:26.413Z - debug: [] error Error: spawn uncrustify ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

@Ptheguy can you try putting the full path to the Uncrustify executable into `Settings -> Executables -> Uncrustify`?

**Comment by szeck87** [comment]
Yea I'll open a separate issue.  Thanks, glad to hear it's working.

**Comment by Glavin001** [comment]
Thank you for reporting this issue, @Ptheguy !

> Is this a bug? Or, is this a recent new implementation that now requires me to install some third-party app (so called docker) to get it working?

Docker support was added as part of #1707 and #1687. The idea is to improve the installation by leveraging's portable Docker features (i.e. works the same on Windows, Mac, Linux, etc).

However, Docker is definitely not required, it should be a last resort / fallback. I'll take a look at #2146 and see about fixing this for yourself and future users. Thanks to @szeck87 , it sounds like you're no longer blocked, @Ptheguy ? Please let us know if you have any more issues. Thanks again!

**Comment by mukeshbasira** [comment]
It is asking for docker on c++ And I don't know what it is. why is this necessary for this package?

**Comment by yoopersteeze** [comment]
Seeing this with beautify version 0.32.5. when trying to beautify a shell script running Atom v1.29.0 on macOS 10.13.4

What I've tried:
- [ ] Uninstalling and re-installing Atom Beautify. Uninstalled via settings in GUI and re-installed with the command: `apm install atom-beautify`
- [ ] Reloaded / restarted Atom and also applied the update that was available
- [ ] Ensure that "auto beautify shell files on save" is not enabled from the beautify package settings
- [ ] Ran `which docker` from Terminal, which returned nothing

Is anyone else seeing this issue with shell scripts? 
<img width="1436" alt="screenshot 2018-07-31 20 04 05" src="https://user-images.githubusercontent.com/31364490/43495307-f5b66f86-94fc-11e8-8699-20fe938720b4.png">

**Comment by simonmelouah** [comment]
Having this issue as well with Python3
