### ISSUE TITLE
Executable error should be from Executable not Docker installation check

### ISSUE THREAD

**Issue by szeck87** [Glavin001/atom-beautify#2146]
# Description

Executable errors are not being displayed in the UI.  Originated from https://github.com/Glavin001/atom-beautify/issues/2145.

# Input Before Beautification

This is what the code looked like before:

N/A

# Expected Output

The beautified code should have looked like this:

N/A

# Actual Output

The beautified code actually looked like this:

N/A

# Steps to Reproduce

1. Add code to Atom editor
2. Shut down Docker if you have it installed
3. Configure a beautifier/executable so it will error intentionally (like setting the wrong path)
4. Run command `Atom Beautify: Beautify Editor`

Result:  Shows an error "could not find Docker"
Expected:  Should show an error about the executable not being able to run instead or in addition to

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
The problem is definitely from 
https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/executable.coffee#L390-L412

@szeck87 I think this `error` in `Promise.reject(error)` is what we want: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/executable.coffee#L396

Would you be able to try out the following change:

```
  init: () ->
    super()
      .then(() =>
        return @
      )
      .catch((error) =>
        return Promise.reject(error) if not @docker?
        return Promise.resolve(error) # <--- CHANGE HERE
      )
      .then((errorOrThis) => # <----- CHANGE HERE
        shouldTryWithDocker = not @isInstalled and @docker?
        @verbose("Executable shouldTryWithDocker", shouldTryWithDocker, @isInstalled, @docker?)
        if shouldTryWithDocker
          return @initDocker().catch(() => Promise.reject(errorOrThis)) # <---- CHANGE HERE
        return @
      )
      .catch((error) =>
        if not @.required
          @verbose("Not required")
          @
        else
          Promise.reject(error)
      )
```

Please and thank you 😃 . I think this will fix it!
