### ISSUE TITLE
PHP-CS-Fixer doesn't work in Atom on Windows.

### ISSUE THREAD

**Issue by jack1142** [Glavin001/atom-beautify#2153]
# Description

I put correct php-cs-fixer absolute path in configuration, but I'm still getting error `Could not find 'C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer'. The program may not be installed.`
```
See C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
Your program is properly installed if running 'where.exe C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer' in your CMD prompt returns an absolute path to the executable.
```

I used command `where.exe C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer` and it gave this output `INFO: Could not find files for the given pattern(s).`, but path is correct because I can execute `C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer` and it will give me standard help.

I also tried to use `php-cs-fixer` as path, because then if I would use `where.exe php-cs-fixer`, I'm getting absolute path to executable as plugin wants me to, but it still gives me the same error.

# Steps to Reproduce

1. Install PHP-CS-Fixer through Composer
2. Add to "Atom Beautify: Executables: PHP-CS-Fixer: Path" setting path to php-cs-fixer executable
3. You're getting error mentioned above!

# Debug

Here is a link to the `debug.md`: https://gist.github.com/jack1142/ddf91d5fab1e61e6004efecab6cc6ec4

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by jack1142** [comment]
Bot, you idiot, it's right there! XD

**Comment by jack1142** [comment]
https://gist.github.com/jack1142/ddf91d5fab1e61e6004efecab6cc6ec4

**Comment by szeck87** [comment]
@jack1142 it looks for `gist.github.com` and at the checkboxes too.  I'll update the comment message to clarify that.

What kind of file is `php-cs-fixer` at `C:\\Users\\kubak\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer`?

**Comment by jack1142** [comment]
If you're asking about extension, then it just doesn't have any extension, looks like some sh script:
```
#!/usr/bin/env sh

dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../friendsofphp/php-cs-fixer" && pwd)

if [ -d /proc/cygdrive ] && [[ $(which php) == $(readlink -n /proc/cygdrive)/* ]]; then
   # We are in Cgywin using Windows php, so the path must be translated
   dir=$(cygpath -m "$dir");
fi

"${dir}/php-cs-fixer" "$@"
```
I checked `dir` variable (`C:\Users\kubak\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer`) and it is just entire repository from https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by szeck87** [comment]
Hmm, actually I don't think the error message in the UI is correct. It should be `where.exe php-cs-fixer` . Can you try running that?

After that, try putting `.bat` at the end of the path in Atom Beautify for php-cs-fixer.

**Comment by jack1142** [comment]
Yeah, I did that before, here's what `where.exe php-cs-fixer`:
```
C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer
C:\Users\kubak\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat
```
I also have already tried version with and without `.bat` both shows the same error.

**Comment by szeck87** [comment]
Can you run the debug command when you have the path that includes `.bat`?

**Comment by jack1142** [comment]
Okay, I have no idea how, but I was sure I checked `.bat` variant and it didn't work, but it apparently works 😮 
Thanks for help!

**Comment by szeck87** [comment]
No problem, glad to hear it's working.
