### ISSUE TITLE
please replace from first place in context menu

### ISSUE THREAD

**Issue by patriciussanctus** [Glavin001/atom-beautify#2163]
Hi! atom-beatify is great plugin, but it's no priority function and dangerously change and save code-files. Function can often be caused by accident.

<img width="212" alt="2018-06-13 11 40 00" src="https://user-images.githubusercontent.com/16253399/41339898-b79d5800-6efe-11e8-9d29-285c97556066.png">

<INSERT CODE HERE>
CODE NOT REQUIRED
</INSERT CODE HERE>

**Comment by patriciussanctus** [comment]
<INSERT CODE HERE>
CODE NOT REQUIRED
</INSERT CODE HERE>

**Comment by patriciussanctus** [comment]
what debug? haha

**Comment by szeck87** [comment]
Unfortunately https://github.com/atom/atom/pull/16661 isn't documented anywhere and I don't have time to play around with it.  Pull requests are welcome.
