### ISSUE TITLE
Linux ElementaryOS: Settings page select is not showing its options, inputs are not working.

### ISSUE THREAD

**Issue by pegasuspect** [Glavin001/atom-beautify#2166]
# Description

Settings does not work for selection or changing/setting values.

## Select on Settings page

<img src="https://i.imgur.com/zcGBpBu.png"/>

<img src="https://imgur.com/LTAR5AX.png"/>

Inputs doesn't work either. I set the value for indentation size to 4. It uses the default value 2 for it.

# Expected Output

I should be able to change and see options.

# Steps to Reproduce

1. Install elementaryOS, a linux distro from its website https://elementary.io/
2. Download Atom v1.27.2
3. From "Packages" tab in settings download atom-beautify v0.32.5
4. Click on Settings button on package to open atom-beautify settings.
5. Try to set and use beautifier for html.

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/pegasuspect/8defb82c882cb88a9b0216e88d65ec0b

# Versions

```
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@pegasuspect can you change settings anywhere else in Atom besides Atom Beautify?

**Comment by pegasuspect** [comment]
@szeck87 Yes I can. For instance: 
###### Settings Page | Core Settings
<img src="https://i.imgur.com/cu5NMaW.png"/>

**Comment by szeck87** [comment]
Hmm, that's weird.  We don't put any control into how to render the options on the screen, it's just a `json` file that Atom parses and uses to display everything.

Can you try opening your Atom's `config.cson` file and see if there is anything under `"*":` named `"atom-beautify"`?

**Comment by pegasuspect** [comment]
@szeck87 
Yes there was. I removed them and tried again still same results. 

Oh, btw I now tried another package settings, same error persists there also. The package is **language-javascript** which is a core package. I cannot choose Tab Type from auto to something else. I still get the same blank dropdown.

**Comment by pegasuspect** [comment]
@szeck87 
Now it started to happen everywhere... I don't even know what may cause this. I mean I cannot debug it because as soon as I click debugger it unfocuses out of select and that white bow is gone. Check it out: 
###### Packages Page | Language Javascript
<img src="https://i.imgur.com/g4MLMDo.png"> 

###### Settings Page | Core Settings
 <img src="https://i.imgur.com/ZiL5FMj.png">

**Comment by szeck87** [comment]
@pegasuspect How did you install Atom through ElementaryOS exactly?

**Comment by pegasuspect** [comment]
something like this.
```sh
curl -sL https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add - https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
sudo apt-get install atom
sudo apt-get install atom-beta
```

**Comment by szeck87** [comment]
I'm not sure then.  Since it's happening in other places other than Atom Beautify, I suspect it's either an installation issue or a compatibility issue with ElementaryOS.  I would open an issue in github.com/atom/settings-view/issues

**Comment by pegasuspect** [comment]
@szeck87 Thanks for your comments! 

Yes just like you thought. It was a problem about the distro's theming or an issue related to google chrome (chromium). I am assuming it is the 1st option, because I have had the same problem on google chrome while surfing the web on a website.

**Comment by pegasuspect** [comment]
@szeck87 I found the solution. But I cannot change chromium settings for atom... Do you have any idea how I can do this? https://askubuntu.com/a/688974/842912

**Comment by szeck87** [comment]
Try what's here:  https://discuss.atom.io/t/how-to-disable-hardware-acceleration-in-atom-version-1-0-0-in-linux/20996/8

**Comment by szeck87** [comment]
@pegasuspect let me know whether that works or not.

**Comment by pegasuspect** [comment]
@szeck87 no it didnt work,I tried with 
```
atom --disable-gpu
```
```
atom -disable-gpu
```
I also tried setting `/usr/share/applications/atom.desktop`. But that is just creating an alias anyway. So, sorry but it didn't work :|

**Comment by szeck87** [comment]
@pegasuspect from chatting with someone from Atom:

> Please update your Atom version to the (just released yesterday) v1.28.0, one of the improvements included in there is an upgrade to Electron 2.0.0, which means a much newer version of Chrome backing it.  For future reference, disabling the GPU is covered here: https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem

**Comment by pegasuspect** [comment]
It still is like that:
```
$ atom --disable-gpu .
```
<img src="https://imgur.com/1rINs48.png">

```sh
$ atom -v
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by szeck87** [comment]
I'm not sure then.  I would open an issue over in https://github.com/atom/settings-view/issues or https://github.com/atom/atom/issues
