### ISSUE TITLE
Can't seem to get tabs correct 

### ISSUE THREAD

**Issue by zeeev** [Glavin001/atom-beautify#2168]
# Description

Thank you for making this wonderful tool. I've been very pleased with it's functionalities. However, I'm struggling with getting the auto-tab complete to work right. When copy and pasting the before and after beautify I noticed the tabs pasted normal (i.e. the desired/correct spacing/tab). This might be a hint that it's just how it's being rendered. I've tried playing with the files in the "uncrustify" folder, the editor settings, and go through restarting/unistalling the package with no success. I've also attached a screen shot of my editor showing what appears to be double tabbing. I'm not great with Atom so I've likely missed a setting.

Thank you for any help,

Best,

Zev 

https://gist.github.com/zeeev/95a45bec2f723ad777298bbfb5ea78ff

<img width="594" alt="screen shot 2018-06-22 at 5 28 38 pm" src="https://user-images.githubusercontent.com/651553/41803853-593c66fc-7642-11e8-9363-0618a08c5851.png">

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by zeeev** [comment]
The link to the gist is in the debug.md was already in the issue. I'm not sure why the bot is not seeing it.

**Comment by szeck87** [comment]
It's the checkboxes in the issue template.  I'll fix the message to say that.

**Comment by zeeev** [comment]
@szeck87 Thanks. I've updated the checkboxes. I missed one.

**Comment by szeck87** [comment]
Yea it doesn't use the `default.cfg` unless you put it in the settings.  We only send `input_tab_size`, `output_tab_size`, and `indent_with_tabs`, none of those seem to do anything.  I'll need to do some playing around and fix what we send by default.

Meanwhile, can you try putting the path to the default.cfg file in Atom Beautify's settings under `C`?  Also comment out `align_number_left` in that same file.

**Comment by zeeev** [comment]
Thank you for the suggestion, @szeck87. By simply providing the path to the default config, and commenting out the align_number_left the issues was resolved. 

Thank you again for building and supporting high-quality open source software.

**Comment by szeck87** [comment]
No problem.  Let's leave this open as a defect with spacing using Uncrustify. I'll look into it more later this week.
