### ISSUE TITLE
php-cs-fixer no effect, no error

### ISSUE THREAD

**Issue by peterremote1980** [Glavin001/atom-beautify#2169]
Hi All. php-cs-fixer no effect, no error, just do nothing.

/Users/peter>php-cs-fixer --version
PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski (beef6cb)
/Users/peter>which php-cs-fixer
/usr/local/bin/php-cs-fixer

<img width="936" alt="screen shot 2018-06-23 at 12 22 04 pm" src="https://user-images.githubusercontent.com/36571333/41805598-0ef89acc-76e0-11e8-8a65-01495c0e41fa.png">

**Comment by francoism90** [comment]
This is whats happens:
```
"Cannot read config file ".php_cs.dist".
```

I'm willing to share more debug info, but this also collects personal issues, like API-keys.

**Comment by szeck87** [comment]
@francoism90 is that a message you are receiving somewhere?  Can you post a screenshot of that and the text you are trying to format?

**Comment by francoism90** [comment]
@szeck87 This is from debug (`Atom Beautify: Help Debug Editor`).

After renaming `.php_cs` to `.php_cs.dist` in the project root, the issue was gone. Maybe the new fixer only accepts the one with the `.dist` extension?

**Comment by ghost** [comment]
got this issue some time ago , 
just go to beautify setting,
 remove cs-fixer phar path from exutable, and put into php setting, 
at this point beautify will notice you that is deprecated,
 just go to to you user folder (i'm assuming you are uing win10) ".../.atom\packages\atom-beautify\src\beautifiers" and edit file "php-cs-fixer.coffee" at line 46 from "cs_fixer_path: true" to "cs_fixer_path: false"
and it should work again

**Comment by xairoo** [comment]
I stopped wasting more of my time, so I switched to https://atom.io/packages/php-cs-fixer for PHP. It just works.
