### ISSUE TITLE
Spacebars support (almost identical to handlebars)

### ISSUE THREAD

**Issue by serkandurusoy** [Glavin001/atom-beautify#217]
[Meteor](www.meteor.com)'s templating language is a derivative of handlebars and is called [spacebars](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md).

It would be great to see spacebars support, even if it is just a blanket copy of handlebars.

Thanks.

**Comment by Francescu** [comment]
:+1:

**Comment by Francescu** [comment]
+1

**Comment by prettydiff** [comment]
Since the syntax appears to be identical to Handlebars Pretty Diff already supports this. Looking at the documentation I did find a minor bug though.

https://github.com/prettydiff/prettydiff/issues/62

**Comment by serkandurusoy** [comment]
hm, yes, that seems to be a showstopper :(

**Comment by prettydiff** [comment]
I put a QA version up for review.  Please test this out and see if it is closer to happiness.

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

**Comment by prettydiff** [comment]
Support added in Pretty Diff v1.11.3.

**Comment by Glavin001** [comment]
Will be coming soon with #282, thanks to @prettydiff.

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.
