### ISSUE TITLE
Sas syntax not indenting correctly on save

### ISSUE THREAD

**Issue by mclusky** [Glavin001/atom-beautify#2170]
# Description

Despite all settings (editor and atom-beautify) set to indent 4, as soon as I save it's beautified and indented 2 spaces. this is a new issue, never had that problem in the past.

# Input Before Beautification

This is what the code looked like before:

```
.social-media-icons
    background: #38fa2b
    height: 50px

.search
    background: #22a18d
    height: 50px

.main-menu ul li
    display: inline
```

# Expected Output

The beautified code should have looked like this:

```
.social-media-icons
    background: #38fa2b
    height: 50px

.search
    background: #22a18d
    height: 50px

.main-menu ul li
    display: inline
```

# Actual Output

The beautified code actually looked like this:

```
.social-media-icons
  background: #38fa2b
  height: 50px

.search
  background: #22a18d
  height: 50px

.main-menu ul li
  display: inline

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/mclusky/d46dc81b9fb6ddfd76ab6a98b636c446

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by mclusky** [comment]
did all that.

**Comment by szeck87** [comment]
It looks like we don't pass any options other than the text when running sass-convert.  I'll take a look over their docs and see if specifying an indent size is available.

**Comment by mclusky** [comment]
cool, thanks a lot.
