### ISSUE TITLE
Docker error: invalid mode: /workdir

### ISSUE THREAD

**Issue by CambrianNode** [Glavin001/atom-beautify#2179]
# Description

The results of beautification are not what I expect, after installing docker toolbox onto my system, I followed the commands to add uncrustify and clang-format to atom. After installing them, atom-beautify would not work and would spit out an error.

# Input Before Beautification

This is what the code looked like before:

```
//test
#include <stdio.h> int main(void){printf("test\n")return 0;}

```

# Expected Output

The beautified code should have looked like this:

```
//test
#include <stdio.h> 
int main(void) {
    printf("test\n");
    return 0;
}
```

# Actual Output

The beautified code actually looked like this:

```
//test
#include <stdio.h> int main(void){printf("test\n")return 0;}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Atom Error
Atom returned this error:
`
C:\Program Files\Docker Toolbox\docker.EXE: Error response from daemon: invalid mode: /workdir. See 'C:\Program Files\Docker Toolbox\docker.EXE run --help'.
`
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/CambrianNode/5bbe5d1c6ab4a2a195eaaae2d0a010ec

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by RobertLucian** [comment]
I'm getting the same error.
