### ISSUE TITLE
Marko template support

### ISSUE THREAD

**Issue by Solido** [Glavin001/atom-beautify#218]
Marko template is the most powerful JS template I've used, it's basically HTML but each time I need to switch from Marko to HTML file type just to start the plugin. Can we have a config update for that little nice to have ? 

https://github.com/raptorjs/marko

**Comment by Glavin001** [comment]
Awesome idea! I'd accept Pull Requests for this addition.

**Comment by Solido** [comment]
I guess we just have to happend 'Marko' to this line of code 
 when "HTML (Liquid)", "HTML", "XML", "Marko" ?
Just need to understand how to setup atom plugins

**Comment by Glavin001** [comment]
Implemented with #219!

Will publish at a later time when I can and post version number here.

**Comment by Glavin001** [comment]
For future reference, I believe this was published to v0.21.4
