### ISSUE TITLE
Optional "opt-in" approach for enabling/disabling beautification languages

### ISSUE THREAD

**Issue by s2t2** [Glavin001/atom-beautify#2191]
# Description

From the Settings, I would like the ability to take an "opt-in" approach to enabling and disabling beautifying languages, instead of an "opt-out" approach. 

# Current Behavior

Enable all by default, then disable individual languages ("opt-out").

# Desired behavior

Disable all by default, then enable individual languages ("opt-in").

**Comment by Glavin001** [comment]
Opt-in per language is actually how [Unibeautify](http://unibeautify.com/) works: https://unibeautify.com/docs/config-file
I recommend you subscribe to #1174 .

This would be a major breaking change and not something we could support in Atom-Beautify before the Unibeautify release. I do expect many breaking changes in the Unibeautify release, so this kind of change would be more appropriate to build into Unibeautify. Fortunately, it already is 😄 .
