### ISSUE TITLE
I'm Japanese! Atom-beautify not woking!

### ISSUE THREAD

**Issue by YutaNakai** [Glavin001/atom-beautify#2193]
First of all, I'm Japanese and my English is not really good.

# Description

Atom beatify is working with no errors and
no results.

l installed "Atom beatify" and "php-cs-fixer" in Atom.

And I also instaled "php-cs-fixer" 
at 
https://github.com/FriendsOfPHP/PHP-CS-Fixer#installation 
which is in my pc.

The file name of it is "php-cs-fixer-v2.phar" which of course is  
in my pc(c:¥xampp¥php¥php-cs-fixer-v2.phar)

And in Atom

my path is "c:¥xampp¥php¥php-cs-fixer-v2.phar".(Excuatbles▶︎PHP-CS-Fixer)

the other path is "c:¥xampp¥php.exe".
(Excuatbles▶︎PHP)

l don't why it's not working.

l geuss setting is no problem becuse
"linter-php" is working.

--------------------------------------------------

This is my fist time doing this. This is all I can do now.
I aiso don't know how to post pictures and debug from Atom.
I've been so in trouble.  
Please help me!

**Comment by JFATech** [comment]
From the given paths I asume you are working on a windows pc.

Here are some things you can check:

- have you restartet Atom after the settings where made?
- What is the extension of the file you are trying to beautify? (should be .php)
- have you tried the developer tools? Are there any messages if you perform ctrl+alt+b in your file?

You should also give more detail on your setup and on the failing action you are trying to perform.

**Comment by szeck87** [comment]
@YutaNakai can you run the debug command?  There is likely an error somewhere, it's just not shown in the UI.  Open the file you are trying to format and go to `Packages -> Atom Beautify -> Debug`.  Follow the prompts and when it opens a tab with text, copy and paste that text into a GitHub gist and make a comment here with the link to the gist.

![screen shot 2018-08-02 at 9 31 37 am](https://user-images.githubusercontent.com/8315038/43590600-fb9a1ab6-9636-11e8-8996-d402f7b0871b.png)

**Comment by YutaNakai** [comment]
Thank you! I really appreciate responding.
Yes l did run debug.

But l don't know how to upload here.

@szeck87
How can l put pictures here?

@JAFteach
Yeas l restarted.
The file name is "bbs.php".
You mean run debug?

**Comment by szeck87** [comment]
@YutaNakai Don't take a picture of it, copy and paste the text and create a gist (https://gist.github.com/) and comment here with a link to the gist.

**Comment by YutaNakai** [comment]
Thank you! 
Please forgive me for not being used to this.

l've been the link before and pasted.

How about after that?

Add file button?

**Comment by szeck87** [comment]
No, Create public gist.

**Comment by YutaNakai** [comment]
l'm sorry l'm late.

I hope I did.

https://gist.github.com/YutaNakai/d17fa7e3d81b7eea52a0e36f4070f442#file-atom

**Comment by YutaNakai** [comment]
And I also know how I can upload pictures.

l think it's very helping

**Comment by szeck87** [comment]
It looks like it's running properly, but there isn't anything for it to change.  Try creating a `.php_cs.dist` in the same directory with contents something like:

```
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        'indentation_type' => true
    ])
    ->setIndent("\t")
    ->setFinder(
        PhpCsFixer\Finder::create()
        ->exclude('vendor')
        ->in(__DIR__)
    )
;
```

**Comment by YutaNakai** [comment]
Thank you. 

Do you mean l make file?

l'm sorry l'm not really good at PC.

**Comment by szeck87** [comment]
Yes, create/make a new file.

**Comment by YutaNakai** [comment]
Thank you.

But l really make sure l'm correct.

Can l ask you again how l put pictures here.

l'm so sorry. l really want you to help me out here.

**Comment by YutaNakai** [comment]
l'm sorry.
Could you please help me?

**Comment by JFATech** [comment]
@YutaNakai you can simply drag & drop pictures in the box you write your comments. You can also copy & paste them from your clipboard. 
How to attach files is also described under the dashed line in the commentbox.

**Comment by YutaNakai** [comment]
Okay. Thank you.

@szeck87 said this

It looks like it's running properly, but there isn't anything for it to change. Try creating a .php_cs.dist in the same directory with contents something like:

And it turns out I have to make a file.

l don't know what is the next.
