### ISSUE TITLE
R installation

### ISSUE THREAD

**Issue by pit00** [Glavin001/atom-beautify#2198]
# Description
I can't install Docker (Windows 10 Home Single Language), so I'm trying to set manually the installation path of Rscript (with formatR installed), but I only get the "Could not find 'docker'. The program may not be installed." error.
I think is not clear the relation/installation of Rscript/formatR

# Checklist
I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Setting manually "C:\Program Files\R\R-3.5.1\bin"
- [x] Setting manually "C:\Program Files\R\R-3.5.1\library\formatR\R"

**Comment by szeck87** [comment]
@pit00 please update to v0.33.0.  It won't fix your issue, but it will give you the proper error.  Update your issue with the new error

**Comment by pit00** [comment]
After update: "Could not find 'rscript'. The program may not be installed."
So I change the path to "..\R\R-3.5.1\bin\Rscript.exe".
Problem solved.

**Comment by szeck87** [comment]
Great, glad it's fixed.
