### ISSUE TITLE
atom-beautify update deletes custom uncrustify cfg files

### ISSUE THREAD

**Issue by julian-poidevin** [Glavin001/atom-beautify#2201]
# Description

N/A

# Input Before Beautification

N/A

# Expected Output

N/A

# Actual Output

N/A

# Steps to Reproduce

1. Have a custom uncrustify cfg file in `C:\Users\poidevinj\.atom\packages\atom-beautify\src\beautifiers\uncrustify`
2. Update to a new version of atom-beautify via atom update manager
3. Run command `Atom Beautify: Beautify Editor`
4. Encounter error : `Error `???: fopen(C:\Users\poidevinj.atom\packages\atom-beautify\src\beautifiers\uncrustify\clang.cfg) failed: No such file or directory (2) Unable to load the config file Try running with -h for usage information``
5. Go to `C:\Users\poidevinj\.atom\packages\atom-beautify\src\beautifiers\uncrustify` : the custom cfg file has been deleted.

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/julian-poidevin/80da4d9ae099a00ae3c9372c7459971f>

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
That directory is apart of the package.  When you update Atom Beautify yes it is going to overwrite everything in there.  Is there a reason why you can't put that config file in your project directory or somewhere outside of the package?

**Comment by julian-poidevin** [comment]
I guess I put it there because the `default.cfg` file was here and I presumed it was the place to save other configuration files.

**Comment by szeck87** [comment]
Yea that's just the default settings that are applied when no configuration file is specified.  It's apart of the package itself so it will be overwritten anytime during an upgrade.
