### ISSUE TITLE
HTML (Liquid) / Liquid Support

### ISSUE THREAD

**Issue by MattOsynlig** [Glavin001/atom-beautify#2202]
# HTML (Liquid) / Liquid Support

Hey team! I **LOVE** atom-beautify & have been using it since I made the switch to ATOM!
Been working on a shopify store for a while now & would love to be able to run this bad boy on my _.liquid_ files!

Not in any rush for this to be done! Just figured I'd throw it on the radar for ya!

Thanks for all your hard work, this plugin makes my life easier on a day to day!
Keep up the great work guys!!

**Comment by prettydiff** [comment]
This will be supported in Pretty Diff 3 once I publish to NPM in the next 2 weeks or so.  In the mean time test it out at https://prettydiff.com and if you find any defects please open an issue at https://github.com/prettydiff/prettydiff/issues
