### ISSUE TITLE
Tree view beautify throwing error "undefined"

### ISSUE THREAD

**Issue by unknowntrojan** [Glavin001/atom-beautify#2206]
# Description

When beautifying using the tree view, it says `C:\Users\Silas\AppData\Local\Temp\118721-5084-16m1dwp.x6i5.cfg:1 for the assignment: unknown option 'undefined':
C:\Users\Silas\AppData\Local\Temp\118721-5084-16m1dwp.x6i5.cfg:1
  for the assignment: unknown option 'undefined':
Hide Stack Trace
Error: C:\Users\Silas\AppData\Local\Temp\118721-5084-16m1dwp.x6i5.cfg:1
  for the assignment: unknown option 'undefined':
    at file:///C:/Users/Silas/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\Silas\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

# Input Before Beautification

This is what the code looked like before:

```
#include <iostream>

using namespace std;

int main(){

        cout << "Hello world.";
        return 0;

}

```

# Expected Output

The beautified code should have looked like this:

```
#include <iostream>

using namespace std;

int main(){

        cout << "Hello world.";
        return 0;

}

```

# Actual Output

The beautified code actually looked like this:

```
N/A
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command beautify from tree view
3. It throws this error

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/unknowntrojan/aab53aa9486aed4bb5a55353f1dccfb9

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
@unknowntrojan can you share what your `.cfg` file looks like?

**Comment by unknowntrojan** [comment]
I can, though i haven't changed anything. i just installed the package.

**Comment by unknowntrojan** [comment]
also here's my config: https://pastebin.com/BQUVtpVF

**Comment by szeck87** [comment]
OK, I unlinked from development and used the downloaded version and get the same error.  The configuration that is being passed is:

```
output_tab_size = undefined
input_tab_size = undefined
indent_with_tabs = 1
```

Looking into why it's doing that.

**Comment by szeck87** [comment]
OK, so for `beautifyFile`, which you are doing, no editor is passed into [`getOptionsForPath`](https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L218). None of the [`editorOptions`](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L560-L569) are set, which causes this issue downstream.

@unknowntrojan For now I would just create a `.cfg` file and copy/paste the full path to that file into Atom Beautify's settings (C++  ->  Config Path). You can find an example here:  https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/default.cfg
