### ISSUE TITLE
HTML Beautify is being Weird

### ISSUE THREAD

**Issue by ReamTeame** [Glavin001/atom-beautify#2216]
# Description

I have beautify on save enabled and whenever I'm saving using Pretty Diff for HTML some tags are being put in a separate line. When I would like them to be in the same line.

This is what the code looked like before:

<div class="navigation">
    <ul>
      <li><a href="#">HOME</a></li>
      <li><a href="#">ONLINE TUTORIALS</a></li>
      <li><a href="#">GET A PRIVATE TUTOR</a></li>
      <li><a href="#">SIGN UP</a></li>
      <li><a href="#">CONTACT US</a></li>
    </ul>
  </div>

# Expected Output

The beautified code should have looked like this:

<div class="navigation">
    <ul>
      <li><a href="#">HOME</a></li>
      <li><a href="#">ONLINE TUTORIALS</a></li>
      <li><a href="#">GET A PRIVATE TUTOR</a></li>
      <li><a href="#">SIGN UP</a></li>
      <li><a href="#">CONTACT US</a></li>
    </ul>
  </div>

# Actual Output

The beautified code actually looked like this:

<div class="navigation">
      <ul>
        <li>
          <a href="#">HOME</a>
        </li>
        <li>
          <a href="#">ONLINE TUTORIALS</a>
        </li>
        <li>
          <a href="#">GET A PRIVATE TUTOR</a>
        </li>
        <li>
          <a href="#">SIGN UP</a>
        </li>
        <li>
          <a href="#">CONTACT US</a>
        </li>
      </ul>
    </div>

**Comment by prettydiff** [comment]
I will add this to my backlog.

**Comment by prettydiff** [comment]
I just pushed a commit to fix this in Pretty Diff.  It will be available in the next 2 weeks or so when I launch the next major version of Pretty Diff.
