### ISSUE TITLE
XML with Cyrillic tags

### ISSUE THREAD

**Issue by Nexion** [Glavin001/atom-beautify#222]
Hi, I'm working with XML documents containing Cyrillic tags and arguments, besides their contents.
[Example code](https://gist.github.com/Nexion/a15043831e5f8eb81664#file-gistfile1-xml).

Unfortunately, atom-beautify can't recognize them:
```
Unsupported language for grammar 'Null Grammar'.
Cannot read property '0' of null
```
Could you fix this please?

**Comment by Glavin001** [comment]
@prettydiff do you plan on supporting this?

**Comment by prettydiff** [comment]
The provided code sample (from the gist) fails the Pretty Diff language auto-detection. I can fix auto-detection to recognize the language as XML provided that "<?xml" is at the beginning.

Aside from language detection this code is already fully supported by Pretty Diff. Just go to http://prettydiff.com/ and change the language selection from "auto" to "xml" to verify.

I will release the auto-detection update very soon (fixed on my local) when I push out support for mustache/handlebars/erb and other support.

**Comment by Glavin001** [comment]
Since @prettydiff supports this, that means with the next release (v0.25.0) which uses Prettydiff for XML beautification will support this. /cc #197

**Comment by Nexion** [comment]
Thanks, works like a charm :+1:
