### ISSUE TITLE
SASS beautify with comma at end of inline comment causes lines to be rearranged

### ISSUE THREAD

**Issue by doggan** [Glavin001/atom-beautify#223]
Save the following as `foo.scss`:
```sass
// test 1,
// test 2
.project-info {
    border-style: solid;
}
```

Run Beautify once and you will get:
```sass
// test 2
// test 1,
.project-info {
    border-style: solid;
}
```

Run Beautify again and you will get:
```sass
// test 2
// test 1,.project-info
{
    border-style: solid;
}
```

:dizzy_face:

I'm using: OSX 10.10.2, Atom 0.184.0, atom-beautify 0.21.3.

Thanks.

**Comment by Glavin001** [comment]
SASS is handled by [`prettydiff`](https://github.com/prettydiff/prettydiff) ( see https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L434 ).

@Prettydiff, any ideas on this would be happening?

**Comment by Glavin001** [comment]
@prettydiff has added fixed this, so this is now high priority.

**Comment by Glavin001** [comment]
Looks like @prettydiff has resolved this.

You can trick Atom into updating Atom Beautify's dependencies, such as Pretty Diff, by uninstalling Atom Beautify and reinstalling it. Atom will install the latest version of Atom Beautify's dependencies, and you will have the most up-to-date version of Pretty Diff and be able to test these changes @prettydiff is working on.
