### ISSUE TITLE
Unable to install/update to atom-beautify 0.33.4

### ISSUE THREAD

**Issue by bjmiller** [Glavin001/atom-beautify#2240]
# Description
When attempting to update to atom-beautify 0.33.4, this happens:
```
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bjmil\.atom\.apm\_logs\2018-10-03T04_30_41_017Z-debug.log
```

Platform: Windows 10
apm version: 2.1.1

# Steps to Reproduce

1. `apm update atom-beautify`

# Debug
From apm debug:
```
151 verbose stack ZlibError: zlib: unexpected end of file
151 verbose stack     at Zlib.(anonymous function).onerror (C:\Users\bjmil\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:131:21)
151 verbose stack     at Unzip.write (C:\Users\bjmil\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:255:31)
151 verbose stack     at Unzip.flush (C:\Users\bjmil\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:222:10)
151 verbose stack     at Unzip.end (C:\Users\bjmil\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:229:10)
151 verbose stack     at Object.end (C:\Users\bjmil\AppData\Local\atom\app-1.31.1\resources\app\apm\node_modules\npm\node_modules\tar\lib\parse.js:415:21)
151 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
151 verbose stack     at Object.onceWrapper (events.js:313:30)
151 verbose stack     at emitNone (events.js:111:20)
151 verbose stack     at PassThrough.emit (events.js:208:7)
151 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
151 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
151 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
152 verbose cwd C:\Users\bjmil\AppData\Local\Temp\apm-install-dir-11893-23680-qz2eim.y5uii
153 verbose Windows_NT 10.0.17134
154 verbose argv "C:\\Users\\bjmil\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bjmil\\AppData\\Local\\atom\\app-1.31.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\bjmil\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\bjmil\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball" "--runtime=electron" "--target=2.0.7" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
155 verbose node v8.9.3
156 verbose npm  v6.2.0
157 error code Z_BUF_ERROR
158 error errno -5
159 error zlib: unexpected end of file
160 verbose exit [ -5, true ]
```

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] (n/a) Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] n/a) Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by DidierPais** [comment]
Same here

**Comment by bjmiller** [comment]
Yes, this still remains an issue.  Multiple people have reported not being able to update to 0.33.4 .

**Comment by bjmiller** [comment]
I managed to solve the problem locally by removing the .apm directory, and installing fresh.  I feel like it's appropriate to close this now.

**Comment by daryelj** [comment]
I'm running into the same issue listed here, but with Manjaro (Arch Linux) with trying to install.  I have tried both through Atom and apm command line with same error each time.  I have conducted apm clean and nap cache reset also after these failures. 

 This is encountered after the silly savetree ends:
151 silly saveTree   └── yaml-front-matter@3.4.1

Error message from log:
152 verbose stack ZlibError: zlib: unexpected end of file
152 verbose stack     at Zlib.(anonymous function).onerror (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
152 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
152 verbose stack     at Unzip.flush (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
152 verbose stack     at Unzip.end (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
152 verbose stack     at Object.end (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:416:21)
152 verbose stack     at PassThrough.onend (_stream_readable.js:655:10)
152 verbose stack     at Object.onceWrapper (events.js:276:13)
152 verbose stack     at PassThrough.emit (events.js:193:15)
152 verbose stack     at endReadableNT (_stream_readable.js:1129:12)
152 verbose stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
153 verbose cwd /tmp/apm-install-dir-119018-18048-1ozge59.evw1
154 verbose Linux 4.19.14-1-MANJARO
155 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/daryelj/.atom/.apm/.apmrc" "--userconfig" "/home/daryelj/.atom/.apm$
156 verbose node v11.6.0
157 verbose npm  v6.5.0
158 error code Z_BUF_ERROR
159 error errno -5
160 error zlib: unexpected end of file
161 verbose exit [ -5, true ]

**Comment by bjmiller** [comment]
@daryelj: apm clean didn't do the right thing here for some reason.  I deleted the whole .apm directory through the OS, and that's what finally made this work.

**Comment by JoyKarmoker** [comment]
I had the same problem in my windows 10 64-bit. I tried many things. But at last i deleted the .apm file and then successfully installed atom-beautify

**Comment by sintaawalisasng** [comment]
I'm almost frustrated
guys you only need to delete the .apm folder inside the .atom folder
Please try cz that's work for me:)))

**Comment by DevanshShukla1** [comment]
where to locate .apm folder?

**Comment by DevanshShukla1** [comment]
> I'm almost frustrated guys you only need to delete the .apm folder inside the .atom folder Please try cz that's work for me:)))

I am not able to find it please help me

**Comment by Edetraymond** [comment]
> 

For Windows 10, 
C:\Users\*your username*\.atom

you'll see the .apm folder, delete it, uninstall atom and reinstall. Then try installing atom-beautify after installation of atom. It worked for me. Hope it works for you.

**Comment by Edetraymond** [comment]
For Windows 10,
C:\Users\*your username*\.atom

you'll see the .apm folder, delete it, uninstall atom and reinstall. Then try installing atom-beautify after installation of atom. It worked for me. Hope it works for you.

**Comment by Edetraymond** [comment]
For Windows 10,
C:\Users\ *your username* \.atom

you'll see the .apm folder, delete it, uninstall atom and reinstall. Then try installing atom-beautify after installation of atom. It worked for me. Hope it works for you.

**Comment by Edetraymond** [comment]
For Windows 10,
C:\Users\your username*\.atom

you'll see the .apm folder, delete it, uninstall atom and reinstall. Then try installing atom-beautify after installation of atom. It worked for me. Hope it works for you.

**Comment by Edetraymond** [comment]
For Windows 10,
C:\Users\your username\.atom

you'll see the .apm folder, delete it, uninstall atom and reinstall. Then try installing atom-beautify after installation of atom. It worked for me. Hope it works for you.

**Comment by Edetraymond** [comment]
For Windows 10,
C:\Users\your username\ .atom

you'll see the .apm folder, delete it, uninstall atom and reinstall. Then try installing atom-beautify after installation of atom. It worked for me. Hope it works for you.
