### ISSUE TITLE
Support for Rmarkdown

### ISSUE THREAD

**Issue by JulienGAMartin** [Glavin001/atom-beautify#2246]
# Description

I obtain an error message if I use the beautify function on a Rmarkdown file (*Rmd, markdown with R chunks embedded) telling me that the format is not supported and to create an issue to request support.

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
When you say R chunks embedded is it using a convention like this:

   \```r
   my code here
   \```

**Comment by jenshda** [comment]
+1 on RMarkown files not working. Changing the name to .md means you can beautify but not when the file ends in .rmd
