### ISSUE TITLE
Request SilverStripe template file .ss (html)

### ISSUE THREAD

**Issue by intwebg** [Glavin001/atom-beautify#2248]
That will be very usefull thanks!

**Comment by prettydiff** [comment]
Could you please link to the formal spec for SliverStripe?  We need to see its syntax in order to verify compatibility.

**Comment by intwebg** [comment]
Syntax are pretty simple. It's just like .HTML file and .ASP like tag

<% with Element %>
<% end_with %>
<% control Element %>
<% end_control %>
<% loop Elements %>
<% end_loop %>
<% if Condition %>
<% end_if %>

Variables, always begin by '$'
$Variable
$Variable.custom
and
{$Variable}
{$Variable.custom}

**Comment by prettydiff** [comment]
@intwebg Please review https://github.com/prettydiff/prettydiff/issues/531 and let me know if I am missing anything, as this will impact indentation.

Most of the template languages like this are handled by Pretty Diff for Atom Beautify.  I will launching the next major version in about 2 weeks or so.  Once published I will work to modify the configs at the Unibeautify project to ensure it supports the latest version of Pretty Diff.  The Unibeautify is the next version of Atom Beautify.
