### ISSUE TITLE
Error in install 

### ISSUE THREAD

**Issue by MohMehrnia** [Glavin001/atom-beautify#2250]
When i install show me below error message:

pm ERR! Unexpected end of JSON input while parsing near '...tegrity":"sha512-zQIM'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mohammad/.atom/.apm/_logs/2018-10-28T06_02_21_773Z-debug.log

Command for install
apm install atom-beautify

**Comment by lyfeyaj** [comment]
+1

**Comment by lyfeyaj** [comment]
Finally solved this problem by running `rm -rf ~/.atom/.apm/*` 😂
