### ISSUE TITLE
Forces too long lines

### ISSUE THREAD

**Issue by eadadi** [Glavin001/atom-beautify#2255]
# Description
It forces too long lines (over the default in the Atom app)
The results of beautification are not what I expect.

# Input Before Beautification

this.members.slice(this.members.indexOf(object) - 1).
      join(this.members.slice(this.members.indexOf(object) + 1, this.members.length - 1));
This is what the code looked like before:

# Expected Output

The beautified code should have looked like the same as above;

# Actual Output
this.members.slice(this.members.indexOf(object) - 1).join(this.members.slice(this.members.indexOf(object) + 1, this.members.length - 1));

(no newline...)

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by prettydiff** [comment]
Using options *wrap:50* and *method_chain:3* Pretty Diff will output this code:

```javascript
this
    .members
    .slice(this.members.indexOf(object) - 1)
    .join(this.members.slice(
        this.members.indexOf(object) + 1,
        this.members.length - 1
    ));
```

Please help Unibeautify update to the latest major version of Pretty Diff to get this capability (and a huge host of bug fixes) in your editor.  https://github.com/Unibeautify/beautifier-prettydiff/issues/114
