### ISSUE TITLE
Ruby: use rubocop --auto-correct

### ISSUE THREAD

**Issue by lloeki** [Glavin001/atom-beautify#226]
Since rubocop has `--auto-correct`, this covers probably everything `ruby-beautify` covers, and more, including project specific settings via `.rubocop.yml`.

**Comment by jney** [comment]
#275

**Comment by Glavin001** [comment]
#275 has been merged. Will be available when I release v0.25.0

**Comment by huanzhang** [comment]
awesome!!!
