### ISSUE TITLE
Latest version doesn't work now

### ISSUE THREAD

**Issue by baybird** [Glavin001/atom-beautify#2262]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

After updated to latest version, it can't correctly format HTML code in *.js file. The previous version was worked properly.

```
<table class="table table-sm">
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>@mdo</td>
    </tr>
  </tbody>
</table>
```

# Expected Output

The beautified code should have looked like this:

```
<table class="table table-sm">
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>@mdo</td>
        </tr>
    </tbody>
</table>
```

# Actual Output

The beautified code actually looked like this:

```
< table class = "table table-sm" >
    <
    tbody >
    <
    tr >
    <
    th scope = "row" > 1 < /th> <
    td > @mdo < /td> <
    /tr> <
    /tbody> <
    /table>
```

# Steps to Reproduce

1. Add code to "filename.js" file.
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by pedroserra** [comment]
Got the same issue but doesn't seem related to this plugin. 
Apparently the file is wrongly being detected as "Javascript" instead of "Javascript with JSX". If I switch it manually it works perfectly.

**Comment by baybird** [comment]
I tried to beautify it with switch it to "Javascript with JSX", got following result. 

```
<table class = "table table-sm" > <tbody>
    <tr>
        <th scope="row">1</th>
        <td>@mdo</td>
    </tr>
</tbody>
</table>
```

**Comment by pm0u** [comment]
I am having the same issue.. switching the language to 'Javascript with JSX' via grammar selector does not fix the problem for me

**Comment by pm0u** [comment]
that is short syntax for a React.Fragment

Info here 
https://reactjs.org/docs/fragments.html#short-syntax
