### ISSUE TITLE
Win7 64bit: Beautify .html does not seem to work with JS Beautify

### ISSUE THREAD

**Issue by ambad4u** [Glavin001/atom-beautify#2267]
# Description

Beautification seems not working with .html files with JS Beautify as default Beautifier.
This is on Windows 7 Ultimate 64bit machine.
PS: 1st time submitting an issue ever, hope it is valid.

# Input Before Beautification

This is what the code looked like before:

```
<!DOCTYPE html>
<html lang="en"     >
    <head>
        <meta                 charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
                <title>Document</title>

        
    </head>
    <body></body>
</html>
```

# Expected Output

The beautified code should have looked like this:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body></body>
</html>
```

# Actual Output

The beautified code actually looked like this:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body></body>

</html>
```

# Steps to Reproduce

1. Add/Load any valid *.html code to Atom editor
2. Make sure that 'Default Beautifier' is set to: `JSBeautify` in settings
3. Run command `Atom Beautify: Beautify Editor` or "`CTRL` + `S`" if have "Beautify On Save" ticked.
4. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ambad4u/e5ad0a6eb7c3ad857322aea0446edc3d

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I beautified your code sample against JS Beautify's web tool and it appears to provide similar output.

https://beautifier.io/

**Comment by BevansDesign** [comment]
I'm pretty sure you can get rid of the extra line breaks in the settings, but that's the expected default behavior. Look for "Extra Liners".

It also doesn't indent second-level tags (<head> and <body>) because that cuts down on unnecessary indentation a bit. I think you can turn that on with "Indent Inner HTML
