### ISSUE TITLE
JSX starting & ending tag have different indentations!

### ISSUE THREAD

**Issue by Quichei** [Glavin001/atom-beautify#2268]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before ( I kinda need that new line after `return` to make it readable) :

```
return (
       <View>
            <Text>
            </Text>       
        </View>
);
```

# Expected Output

The beautified code should have looked like this( same as above):

```
return (
       <View>
            <Text>
            </Text>       
        </View>
);
```

# Actual Output

The beautified code actually looked like this (indendation is WRONG, making the code confusing and hard to find the start/end tag):

```
return (<View> //starting tag indendation
            <Text>
            </Text>       
</View> //ending tag indendation
);
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Which beautifier are you using?

**Comment by Quichei** [comment]
@prettydiff Pretty Diff

**Comment by prettydiff** [comment]
I will be updating a solution for this as part of an issue I am working right now: https://github.com/prettydiff/prettydiff/issues/473

This will be the last one or two outside issues I work before going live with the next major release of Pretty Diff.

**Comment by prettydiff** [comment]
This is fixed in the latest major version of Pretty Diff, but we could use some help integrating into Unibeautify (Atom Beautify's successor):  https://github.com/Unibeautify/beautifier-prettydiff/issues/114
