### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by filipesilva** [Glavin001/atom-beautify#227]
Hey, is it just me or have pretty much all settings disappeared? I remember there being loads of settings in the GUI but now I can only find two. (windows 8.1, atom 0.186.0)

![image](https://cloud.githubusercontent.com/assets/4172079/6541376/65587dba-c4c3-11e4-981d-7ebeb885bce3.png)

**Comment by Glavin001** [comment]
Sounds like the Atom API has changed and broke this package, once again. Thank you for letting me know.

**Comment by filipesilva** [comment]
Anything I can do to help?
I was looking at how to do a PR to allow for a new option in jsbeautify (attribute wrapping for html) when I noticed this.

**Comment by Glavin001** [comment]
Pull requests are very welcome! Thanks!



—

**Comment by filipesilva** [comment]
I've verified the new options work out of the box on a .jsbeautifyrc file, and after the problem with Atom's API is sorted I'll add the new options to the settings by following the example of other options.

I don't think I can help much with this specific bug though, I'm not really familiar with the Atom API. If you think it's something easy and can point me in the right direction, I'm happy to have a stab at it.

**Comment by Glavin001** [comment]
I'm not quite sure what could have changed however here are the appropriate docs: https://atom.io/docs/api/v0.186.0/Config#defining-settings-for-your-package 
and here are the two places with configs: https://github.com/Glavin001/atom-beautify/blob/master/lib/beautify.coffee#L225-L256 and https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L68-L384
I may be able to help out tomorrow. However it'd be awesome if you've solved it by then. Good luck and thanks for contributing! :smiley:

**Comment by filipesilva** [comment]
Haven't managed to fix it, but here's what I have so far:
-added my fork as dev package, loaded atom in dev mode
-changed the config object, no change in the settings window
-checked the console, config object show that the options are there

![image](https://cloud.githubusercontent.com/assets/4172079/6542975/a026a578-c501-11e4-89d6-e621b2b72db0.png)

**Comment by filipesilva** [comment]
It seems like the a different config is being loaded, because there are configuration options (js break chained and js wrap line length). I can't find those options anywhere though, which is weird.

**Comment by filipesilva** [comment]
Calling `atom.config.get('atom-beautify')` shows the settings in the first screenshot, plus the rest of them.

![image](https://cloud.githubusercontent.com/assets/4172079/6543037/82677952-c503-11e4-87e9-4d3166bc6698.png)

**Comment by filipesilva** [comment]
An odd behaviour that I noticed: when atom starts, the plugin configuration is not all there. After the plugin is activated, the rest appears.

![image](https://cloud.githubusercontent.com/assets/4172079/6543116/fab905da-c506-11e4-84ee-ea19ce315a54.png)


By the way, I'm sorry If I'm being spammy. I don't really know much about atom package development and just want to put here all the details.

**Comment by Glavin001** [comment]
I don't mind this spamminess, at all. This is great. Keep it coming. If anyone does not want to receive these messages they can simply unsubscribe to this thread. Thanks for the research!




That's interesting that it does not fully populate when atom loads. Maybe it's because atom beautify uses two separate config files? strange. 



—

**Comment by filipesilva** [comment]
Apparently, if I remove the `activationCommands` from `package.json` the configuration loads correctly. 

One of the changes in [0.184.0](https://github.com/atom/atom/releases/tag/v0.184.0) had to do with `activation` function export being optional. Maybe it's related?

**Comment by Glavin001** [comment]
Sounds like you're on the right track. Potentially *none* of the options are being loaded and those that you do see you had manually set and so Atom knows of it from your person settings but not from the package itself. 



—

**Comment by filipesilva** [comment]
Ah and here it is. That's the problem alright!
https://github.com/atom/settings-view/issues/356

**Comment by filipesilva** [comment]
So if I do something that activates the package, I can see the settings. I'll leave this as is for now and try to add in the new options for jsbeautify.

**Comment by Glavin001** [comment]
Yup looks like an Atom issue. Good work diagnosing. Move onto new options support. Thanks!



—

**Comment by filipesilva** [comment]
And done. https://github.com/Glavin001/atom-beautify/pull/228

**Comment by Glavin001** [comment]
Closing this as it is an issue with Atom's Settings View and not Atom Beautify package.
