### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:36805

### ISSUE THREAD

**Issue by tilek** [Glavin001/atom-beautify#2272]
# Description

I get an error after clicking Beautify if I switch default beautifier from autopep8 to pybeautifier.
When I choose autopep8 it works fine.

It doesn't matter what input code you have.

# Steps to Reproduce

1. Add code to Atom editor
2. Set default beautifier to pybeautifier
2. Run command `Atom Beautify: Beautify Editor`

# Debug

Here is a link to the `debug.md` Gist: 
https://gist.github.com/tilek/f0a37e3d949b109ebc3377e7ac091142

# Checklist

I have:
- [ x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ x ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by tilek** [comment]
I am guessing the issue is that I don't have pybeautifier installed, but when I try to use yapf beautifier, I get a proper error message:

"""
Could not find 'yapf'. The program may not be installed.

See yapf installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/google/yapf
Your program is properly installed if running 'which yapf' in your Terminal returns an absolute path to the executable.
"""

I think it would be great to have a better error message.

**Comment by guyskk** [comment]
@tilek You are right.
