### ISSUE TITLE
js-beautif: no newline before object declaration brace 

### ISSUE THREAD

**Issue by rzjnzk** [Glavin001/atom-beautify#2275]
![2018-11-30 14_47_36-window](https://user-images.githubusercontent.com/29923471/49268391-27dc4000-f4af-11e8-8b8f-5380efd780da.png)

As can be seen in the above image, atom-beautify will not place a newline before the opening brace of queryStringObject, however, does so correctly elsewhere. I have tried this across various files, and it seems as though this is the case specifically with object declarations.

Edit: This is also the case with multi-line array declarations. If I manually place a newline in said position, it is removed by atom-beautify.

**Comment by prettydiff** [comment]
Are you intending output like this:

```javascript
var queryStringObject =
{
    'id': currentToken.id
};
```
