### ISSUE TITLE
I cannot install.

### ISSUE THREAD

**Issue by Lavenderloved** [Glavin001/atom-beautify#2280]
I can not install the plugin. 

-------------------------------------------------

npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Unexpected end of JSON input while parsing near '..."~0.1.5"},"bin":{"aco'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lavender“\.atom\.apm\_logs\2018-12-14T11_46_13_320Z-debug.log

**Comment by stevenzeck** [comment]
What version of Atom are you on?  What OS and version of it are you using?
