### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by alieamami** [Glavin001/atom-beautify#2285]
Could not find 'php-cs-fixer'. The program may not be installed.
See php-cs-fixer installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
Your program is properly installed if running 'where.exe php-cs-fixer' in your CMD prompt returns an absolute path to the executable.

**Comment by lcy101u** [comment]
same problem here ~

**Comment by Taimoor-AbdULLAH** [comment]
same issue here

**Comment by scpketer** [comment]
Worst implementation of beautifying code - why not making packages just like `linter-<lang>`.
Didn't make it work for any language - from C/C++ to PHP.
Just keeps saying 'program may not be installed' - though it's on $PATH, and totally functional

**Comment by stevenzeck** [comment]
@scpketer we looked into doing that in the new Unibeautify implementation, but we are scope naming our packages and Atom doesn't recognize them in that way.

For your error, I think you still need to have the absolute path to the exe in Atom Beautify settings. Please try that. @Glavin001 do you know if it is supposed to work without the path in settings, but in the environment variable?

**Comment by scpketer** [comment]
@stevenzeck I don't have 'exe', I'm on Unix :)
Besides, absolute path to the lang fixer is 'deprecated' and gives me a warning.

**Comment by ghost** [comment]
got this issue some time ago , 
just go to beautify setting,
 remove cs-fixer phar path from exutable, and put into php setting, 
at this point beautify will notice you that is deprecated,
 just go to to you user folder (i'm assuming you are uing win10) ".../.atom\packages\atom-beautify\src\beautifiers" and edit file "php-cs-fixer.coffee" at line 46 from "cs_fixer_path: true" to "cs_fixer_path: false"
and it should work again
