### ISSUE TITLE
Clang Format error linux

### ISSUE THREAD

**Issue by honigbeutler123** [Glavin001/atom-beautify#2290]
# Description
Hi, i recently got an error while using the clang-format feature for cpp. The error was 'callback must be a function' and no formatting did work at all. I have to say that i am using an archlinux system (so maybe this is only an issue with a new node version or smt). 

#Solution
I was able to fix the issue by going into the clang-format.coffee and insert an empty function into line 84. 

from:
`return @exe("clang-format").run([
        @dumpToFile(dumpFile, text)
        ["--style=file"]
        ]).finally( ->
          fs.unlink(dumpFile)
        )
`
to: 
`return @exe("clang-format").run([
        @dumpToFile(dumpFile, text)
        ["--style=file"]
        ]).finally( ->
          fs.unlink(dumpFile, ->)
        )
`

this fixed the issue for me. You might want to consider adding this to your code, because i do not thing it will be a breaking change to other systems :).

**Comment by honigbeutler123** [comment]
I still think this should be added since the error still exists

**Comment by Netzia** [comment]
I have this same error, also on Arch Linux (5.1.15-arch1-1-ARCH, x86_64). Will try the fix mentioned above.

**Comment by bin-haw** [comment]
WOW,the method works for me too.I'm also on Arch Linux(5.1.16-arch1-1-ARCH)

**Comment by iamyoukou** [comment]
Works for me. I'm on `macOS High Sierra 10.13.6`.

**Comment by kneupane1** [comment]
Thanks @honigbeutler123 , it works for me too.

**Comment by MoienBowen** [comment]
I now have a issue on macOS Catalina Public Beta.
Your solution is almost prefect, just one more bracket ')' at the end.
Well, it is my case. :)

Thanks a lot for your solution, I only found this one.

**Comment by omichel** [comment]
Same problem here, the patched worked for me as well. Thanks!

**Comment by hirnc** [comment]
I had the same problem on Windows 10 (Atom 1.41.0 x64). The patch worked well in my environment as well.

**Comment by julibeg** [comment]
same story on ubuntu 16.04, atom v1.40

**Comment by TheDarkTron** [comment]
Fixed it for me too, thanks!
I am on macOS 10.14.6
Atom 1.41.0 x64

**Comment by lzy-106** [comment]
Issue persists in latest package

**Comment by yirami** [comment]
Fixed it for me too, thanks!
I am on windows 10 18363.1016
Atom 1.50.0 x64

**Comment by saisesai** [comment]
It works for me, thanks!

**Comment by serk12** [comment]
the fix from the title works for me, it should be merged, the issue it's not done yet. Thanks!

**Comment by vinimlo** [comment]
The fix from the title works for me! It should be merged

**Comment by Ma11ock** [comment]
Same issue on Arch Linux and Manjaro Linux, fix worked for me as well

**Comment by na-trium-144** [comment]
I had the same issue on Linux Mint 20.3 and the fix worked for me too.
