### ISSUE TITLE
css "space_around_selector_separator" nor "space_around_combinator" not working

### ISSUE THREAD

**Issue by subfighter3** [Glavin001/atom-beautify#2291]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
.container>a {
  position: relative;
}
```

# Expected Output

The beautified code should have looked like this:

```
.container > a {
  position: relative;
}
```

# Actual Output

The beautified code actually looked like this:

```
.container>a {
  position: relative;
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [ * ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ * ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ * ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
- [ * ] Tried to add the following line to my global .jsbeautifyrc file
```
  "space_around_combinator": true,
  "space_around_selector_separator": true
```

after a lot of searching, i'm actually lost and I cannot understand how to set this parameter to my atom-beautify.

**Comment by subfighter3** [comment]
no one can help me on this?

**Comment by prettydiff** [comment]
I am able to reproduce this at https://beautifier.io/

**Comment by subfighter3** [comment]
Thanks!
and now what happens?

**Comment by prettydiff** [comment]
And now we wait for triage and then resolution.

**Comment by subfighter3** [comment]
Thanks for reply!

crossed fingers!

**Comment by subfighter3** [comment]
but not working in Atom plugin

**Comment by bitwiseman** [comment]
@subfighter3 
Perhaps, but if it works on https://beautifier.io/  the problem is in the plugin.  If it doesn't work on https://beautifier.io/  then the problem is in https://github.com/beautify-web/js-beautify/ .

**Comment by subfighter3** [comment]
yes exactly I found the bug just in the atom plugin, so I posted the issue in the wrong place, sorry!

**Comment by bitwiseman** [comment]
@subfighter3 
No problem.  
What this means is that the plugin will need updating.  I'm not sure where that change needs to happen though.  Probably https://github.com/Glavin001/atom-beautify/blob/master/src/languages/css.coffee .

**Comment by subfighter3** [comment]
Thanks @bitwiseman 

Unfortunately i thought posting this request was the way to ask the owner to fix this bug, which I think should be enabled by default, since the plugin is a code "Beutifier"

**Comment by bitwiseman** [comment]
@subfighter3 
Well, it lets the owner know there's a bug. The owner of the plugin may not have time. If you want it fixed, you will probably need to submit a PR.

**Comment by subfighter3** [comment]
ok, thanks for the suggestion
