### ISSUE TITLE
Eslint fixer indentation not correct

### ISSUE THREAD

**Issue by mrleblanc101** [Glavin001/atom-beautify#2294]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
            <li>
                <a href="http://vuex.vuejs.org/" target="_blank">vuex</a>
            </li>
```

# Expected Output

The beautified code should have looked like this:

```
            <li>
                <a
                    href="http://vue-loader.vuejs.org/"
                    target="_blank"
                >
                    vue-loader
                </a>
            </li>
```

# Actual Output

The beautified code actually looked like this:

```
            <li>
                <a
href="http://vuex.vuejs.org/"
target="_blank"
>
vuex
</a>
            </li>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/mrleblanc101/8d765f0a206910e96f29a2a6453f73ee

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by mrleblanc101** [comment]
Manually running eslint output the correct code. Only using atom beautify Eslint Fixer does this output.

**Comment by prettydiff** [comment]
Really, the anticipated answer is not really correct either.  You are buffering the text with white space that did not exist in the original input.

Ideal output would be:

```html
<li>
    <a href="http://vuex.vuejs.org/" target="_blank">vuex</a>
</li>
```

forcing attributes to be indented
```html
<li>
    <a
        href="http://vuex.vuejs.org/"
        target="_blank"
    >vuex</a>
</li>
```

with word wrap at 30 characters:
```html
<li>
    <a
        href="http://vuex.vuejs.org/"
        target="_blank">vuex</a>
</li>
```

**Comment by mrleblanc101** [comment]
The expected output in my initial post is correct, it's the result from my local eslint --fix.
This follow vue:recommended standard.
Eslint and atom beautify should have the same result.
