### ISSUE TITLE
Suggestion: add option to use single-line format for CSS styles with only one property

### ISSUE THREAD

**Issue by BevansDesign** [Glavin001/atom-beautify#2301]
# Description

It'd be great if there was an option to keep single-property CSS styles on a single line, to reduce line breaks that aren't really necessary for the readability of the code. In fact, this probably makes the code _more_ readable.

It would probably be useful for other languages too.

# Input From Beautification

This is what the code looks like when Beautified:

```
#promoslides ul {
  width: 960px;
  margin: 0 auto;
  padding: 0;
  display: flex;
}

#promoslides .r2c {
  animation-name: r2c;
}
@keyframes r2c {
  0% {
    transform: translateX(100%)
  }

  100% {
    transform: translateX(0%)
  }
}
```

# Desired Output

The beautified code could look something like this:

```
#promoslides ul {
  width: 960px;
  margin: 0 auto;
  padding: 0;
  display: flex;
}

#promoslides ul {animation-name: moveme;}

@keyframes moveme {
  0% {transform: translateX(100%)}
  100% {transform: translateX(0%)}
}
```

# Debug

Not a bug.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by donsony** [comment]
I've been looking for this specific option, have no clue how to activate it. Basically I would like to format the beautifier to support single line css

**Comment by jtcarrasco** [comment]
would love this option

**Comment by joezappie** [comment]
I to would like this option
