### ISSUE TITLE
Could not find 'rubocop'. The program may not be installed

### ISSUE THREAD

**Issue by misterernest** [Glavin001/atom-beautify#2303]
# Description

The results of beautification are not what I expect.

I'm work with rbenv and I did `gem install robucop` and it did not work.

[GIST](https://gist.github.com/misterernest/aa843b0388a323cd7004a6e070b85658)

# Input Before Beautification

This is what the code looked like before:

```
class BookInStock
def initialize(isbn, price)
@isbn = isbn
@price = Float(price)
end
def to_s
"ISBN: #{@isbn}, price: #{@price}"
end
end
```

# Expected Output

The beautified code should have looked like this:

```
class BookInStock
  def initialize(isbn, price)
    @isbn = isbn
    @price = Float(price)
  end

  def to_s
    "ISBN: #{@isbn}, price: #{@price}"
  end
end
```

# Actual Output

The beautified code actually looked like this:
![screenshot from 2019-01-28 12-38-13](https://user-images.githubusercontent.com/8209943/51854783-998f0980-22f9-11e9-9ded-659952a6e74e.png)
Could not find 'rubocop'. The program may not be installed.
# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: 
[GIST](https://gist.github.com/misterernest/aa843b0388a323cd7004a6e070b85658)

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by rogercodes1** [comment]
having the same issue. When I try and run 
`gem install rubocop`

I get the following: 
`// ♥ gem install rubocop
Building native extensions. This could take a while...
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    current directory: /Users/rogerperez/.rvm/gems/ruby-2.5.3/gems/jaro_winkler-1.5.2/ext/jaro_winkler
/Users/rogerperez/.rvm/rubies/ruby-2.5.3/bin/ruby -r ./siteconf20190201-95719-di5gax.rb extconf.rb
creating Makefile

current directory: /Users/rogerperez/.rvm/gems/ruby-2.5.3/gems/jaro_winkler-1.5.2/ext/jaro_winkler
make "DESTDIR=" clean
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

current directory: /Users/rogerperez/.rvm/gems/ruby-2.5.3/gems/jaro_winkler-1.5.2/ext/jaro_winkler
make "DESTDIR="
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

make failed, exit code 1

Gem files will remain installed in /Users/rogerperez/.rvm/gems/ruby-2.5.3/gems/jaro_winkler-1.5.2 for inspection.
Results logged to /Users/rogerperez/.rvm/gems/ruby-2.5.3/extensions/x86_64-darwin-17/2.5.0/jaro_winkler-1.5.2/gem_make.out`

**Comment by rogercodes1** [comment]
### A SOLUTION: 
`xcode-select --install`
Then try running 
`gem install rubocop`
