### ISSUE TITLE
JSON Beautifier not supporting Line Breaks

### ISSUE THREAD

**Issue by ngurney** [Glavin001/atom-beautify#2306]
# Description

When attempting to beatify long JSON files it does not adjust line breaks, even with the setting disabled. I am copying information from Slack and it is sometimes split between multiple messages. This is where the error is occurring as far as I can tell. 

# Input Before Beautification

This is what the code looked like before:

```
{"vendorItemId":"AMD-17830-148","upc":"784626944169","manufacturerItemId":"C5350015","purchaseOrderlineNumber":14,"itemTitle":"PUMPKIN","packageCount":1,"packageLabel":"Bolt","itemsPerPackage":"1","

itemLabel":"yard","cost":87}
```

# Expected Output

The beautified code should have looked like this:

```
{
            "vendorItemId": "AMD-17830-124",
            "upc": "784626944152",
            "manufacturerItemId": "C5350014",
            "purchaseOrderlineNumber": 13,
            "itemTitle": "MAIZE",
            "packageCount": 1,
            "packageLabel": "Bolt",
            "itemsPerPackage": "1",
            "itemLabel": "yard",
            "cost": 87
        }
```

# Actual Output

The beautified code actually looked like this:

```
{
            "
            vendorItemId ": "
            AMD - 17831 - 43 ",
            "
            upc ": "
            784626944176 ",
            "
            manufacturerItemId ": "
            C5350016 ",
            "
            purchaseOrderlineNumber ": 15,
            "
            itemTitle ": "
            LEAF ",
            "
            packageCount ": 1,
            "
            packageLabel ": "
            Bolt ",
            "
            itemsPerPackage ": "
            1 ",
            "
            itemLabel ": "
            yard ",
            "
         
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by ngurney** [comment]
Where can I enable sorting? I can't find the option is the beatify settings. Right now I am getting the following output from Pretty Diff:
```{
            "
                    vendorItemId ": "
                    E014 - 308 ",
            "
                    upc ": "
                    784626535077 ",
            "
                    manufacturerItemId ": "
                    E014 - 308 ",
            "
                    purchaseOrderlineNumber ": 33,
            "
                    itemTitle ": "
                    LINEN ",
            "
                    packageCount ": 1,
            "
                    packageLabel ": "
                    Bolt ",
            "
                    itemsPerPackage ": "
                    1 ",
            "
                    itemLabel ": "
                    yard ",
            "
                    cost ": 57.75
        }```

I have used different JSON data for each example. If you'd like I can correct my comments to use consistent data if that helps.

**Comment by prettydiff** [comment]
Atom Beautify is using an older version of Pretty Diff.  I released a new major version about a month ago and have not update Atom Beautify to support the newer version.  Is the output example in my previous comment what you are hoping for?

**Comment by prettydiff** [comment]
Ignore the sorting.  I just had some settings set incorrectly in my tool when I generated the output sample and didn't realize it until I already pasted it in here.

**Comment by ngurney** [comment]
So I am realizing this isn't a great use case for the Beautifier and have found a way to more easily manually adjust the code. I'll be closing this as I no longer need the request. Feel free to reopen if you'd like to see this functionality.
