### ISSUE TITLE
Installing “atom-beautify@0.33.4” failed.

### ISSUE THREAD

**Issue by zaoqi-unsafe** [Glavin001/atom-beautify#2314]
# Description
```
Installing “atom-beautify@0.33.4” failed.Hide output…
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/1828_sandbox/.atom/packages/atom-beautify/node_modules/JSV/CHANGELOG.md'
Community Packages1/1
```
# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by nitishkyadav** [comment]
Facing same issue

**Comment by sintaawalisasng** [comment]
I'm almost frustrated
guys you only need to delete the .apm folder inside the .atom folder
Please try cz that's work for me:)))
