### ISSUE TITLE
Cannot find php-cs-fixer, even though correct executable path is provided

### ISSUE THREAD

**Issue by tunapiq** [Glavin001/atom-beautify#2318]
# Description

atom-beautify stops working after update. 

```
Could not find 'C:\Users\name\AppData\Roaming\Composer\vendor\bin'. The program may not be installed.
See C:\Users\name\AppData\Roaming\Composer\vendor\bin installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
Your program is properly installed if running 'where.exe C:\Users\abere\AppData\Roaming\Composer\vendor\bin' in your CMD prompt returns an absolute path to the executable.
```

**Comment by ghost** [comment]
got this issue some time ago , 
just go to beautify setting,
 remove cs-fixer phar path from exutable, and put into php setting, 
at this point beautify will notice you that is deprecated,
 just go to to you user folder (i'm assuming you are uing win10) ".../.atom\packages\atom-beautify\src\beautifiers" and edit file "php-cs-fixer.coffee" at line 46 from "cs_fixer_path: true" to "cs_fixer_path: false"
and it should work again
