### ISSUE TITLE
beautify django inside html <span ...> tag

### ISSUE THREAD

**Issue by Chistabo** [Glavin001/atom-beautify#2325]
olo!

- using 'beautify on save'
- the django/python code inside a html tag (<span> in this case) is sliced and each slice put into new line.
- in atom settings/packages/atom-beautify/[language] HTML, i use 'brace style' : 'expand', i believe this is why code inside html tag is sliced; and have also added 'content unformated' : 'pre, textarea, {%, %}'; but have not achieved desired result.

The results of beautification are not what I expect.
I would expect to be on 1 line, like:
`{% if message.tags %}
...
{% endif %}`

# Input Before Beautification

This is what the code looked like before:

```
      {% for message in messages %}
      <span {% if message.tags %}
            class="{{ message.tags }}"
            {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}important: {% endif %}
        {{ message }} <br>
      </span>
      {% endfor %}
```

# Expected Output

The beautified code should have looked like this:

```
      <span {% if message.tags %}
            class="{{ message.tags }}"
            {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}important: {% endif %}
        {{ message }} <br>
      </span>
```

# Actual Output

The beautified code actually looked like this:

```
      {% for message in messages %}
      <span {%
            if
            message.tags
            %}
            class="{{ message.tags }}"
            {%
            endif
            %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}important: {% endif %}
        {{ message }} <br>
      </span>
      {% endfor %}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/Chistabo/70b8efea531621ffef4faba181a04a43>
or this (same file):
<script src="https://gist.github.com/Chistabo/70b8efea531621ffef4faba181a04a43.js"></script>

# Checklist

I have:
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

have fun,

simon
s love nia

**Comment by prettydiff** [comment]
I need to get the latest version of Pretty Diff into Atom Beautify.

When the language is explicit set to HTML you get
```twig
{% for message in messages %}
    <span {% if message.tags %} class="{{ message.tags }}" {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}important:
        {% endif %}
        {{ message }} <br>
    </span>
{% endfor %}
```

Otherwise if the language is not set to `html` you would need to change `<br>` to <br/>`.

If there is any white space between the second if and the important text you would get:

```twig
{% for message in messages %}
    <span {% if message.tags %} class="{{ message.tags }}" {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            important:
        {% endif %}
        {{ message }} <br>
    </span>
{% endfor %}
```

**Comment by Chistabo** [comment]
yes, but i use JS Beautify, since this one nicely puts attributes (class, name, content...) into new line, and this is exactly the issue here, with my code:
'{%' and 'if' and 'message.tags' and  '%}' is recognized (JS Beautify) as attribute, and put into new line.
pretty diff puts it all in one line. long line.

simon
s love nia
