### ISSUE TITLE
Make sourcing `.bash_profile` and `.bashrc` optional/disableable

### ISSUE THREAD

**Issue by demosdemon** [Glavin001/atom-beautify#233]
While researching the cause of #215, I see that both `.bash_profile` and `.bashrc` are loaded. [cli-beautify.coffee:43](https://github.com/Glavin001/atom-beautify/blob/77ec0b2e6fd33dd79474897147c8b42f605bda02/lib/langs/cli-beautify.coffee#L43)

It's not necessary in my issue with autopep8 since I already provide the path for autopep8. 

Another issue from sourcing those two files, I have my `.bash_profile` set up to do as it pleases and `.bashrc` set up to source `.bash_profile`. So, in this case, `.bash_profile` is being sourced twice unnecessarily causing some significant delay (I put too much in mine).

I would like it if this were at least disableable from the configuration if not fully customizable.

**Comment by Glavin001** [comment]
Absolutely agree. This will be implicitly resolved with #164 , however that may very well be a while off. At least this is a temporary fix.

I am accepting pull requests for this issue.

**Comment by Glavin001** [comment]
A quick fix that would be even better would be having users set their `$PATH` for Atom Beautify. That was the whole point of that code you referenced.

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.
