### ISSUE TITLE
A debug or error log, Not exactly sure what to do.

### ISSUE THREAD

**Issue by JaydenAndrews** [Glavin001/atom-beautify#2331]
I feel really stupid because I don;t have a full idea of what this is but I run a Fedora 29 machine, the latest with all the updates up to this point and i was wondering what this error log was about, sorry I'm still a student.
[2019-03-21T21_22_41_893Z-debug.log](https://github.com/Glavin001/atom-beautify/files/2994058/2019-03-21T21_22_41_893Z-debug.log)

**Comment by prettydiff** [comment]
Create a github gist and paste the contents of that file into the gist.  Then paste the web address of that gist into a new comment of this issue and I will review it.

https://gist.github.com/
