### ISSUE TITLE
Use tilda (~) in configPaths

### ISSUE THREAD

**Issue by pathawks** [Glavin001/atom-beautify#235]
I would like to specify my `configPath`s relative to my home directory, but it seems to choke when I use "`~/Dropbox/Tools/c-uncrustify.cfg`"  I instead need to use the full path.

This makes life difficult as my config file is synced between different machines, even though my home directory is different.

**Comment by Glavin001** [comment]
For *machine specific* configurations, like this, I configure in the Atom Beautify *Package settings*.

**Comment by Glavin001** [comment]
Looks like this is what I need: http://stackoverflow.com/a/24840351/2578205

**Comment by Glavin001** [comment]
Published to v0.22.1

Let me know how it works for you.

**Comment by pathawks** [comment]
:+1: Awesome. Thank you.
