### ISSUE TITLE
Support beautifying files with unknown grammars

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#238]
Blocker for #122 

- [ ] Extension to Grammar mapping
  - [ ] Atom Beautify package setting for a JSON structure representing extension mapping to Grammar

```json
{
   "tss": "Titanium Style Sheet"
}
```
  - [ ] Alternative grammar mappings (above) are forced priority on top of Atom's

**Comment by Glavin001** [comment]
- See Config docs: https://atom.io/docs/api/v0.187.0/Config

Instead of using JSON, how about using `array` type and make the sub items of type `string` and the string must be in the form `#{extension}:#{grammar}`. For example: `tss:Titanium Style Sheet`

**Comment by m1ga** [comment]
any news here?

**Comment by Glavin001** [comment]
I am working on exams until April 17th. So that will be the earliest time I will have to develop on this and any other features.

If your package https://github.com/m1ga/language-tss  works then that should allow a much quicker fix. All we need is for Atom to recognize that grammar, even if that language support does not do much else.

**Comment by m1ga** [comment]
no problem! Good luck for your exams!

its at least showing TSS in the bottom so it's finding tss files I guess:
![img](https://cloud.githubusercontent.com/assets/4334997/7106298/f9006fc0-e13b-11e4-95d2-ad6aca0d0561.png)

**Comment by Glavin001** [comment]
> its at least showing TSS in the bottom so it's finding tss files I guess:

Excellent! In that case!...

**Comment by Glavin001** [comment]
Published TSS support to v0.24.0

Be sure to install https://github.com/m1ga/language-tss to allow Atom to detect TSS.

:smiley: 

Now I'm off to studying. Thanks!

**Comment by Glavin001** [comment]
This was effectively implemented with #282.
