### ISSUE TITLE
Windows: source file name(s) are larger than is supported by the file system

### ISSUE THREAD

**Issue by digihash** [Glavin001/atom-beautify#239]
Dear

The problem is that if I copy the folder from my Mac OS X system to the packages folder on a Windows 7 system without internet, I get the error that the Source Path is Too Long. I checked which folder is causing this and it starts at atom-beautify/node-modules. I started going in there and every time I go a folder deeper and try to copy the node-modules folder, I get the same error.

This is because this folder structure keeps going deeper and deeper.

Is it possible to make this structure smaller, so you don't have this problem on a Windows 7 machine or is this because it was installed on my Mac OS X (Unix) system and then copied to the windows machine. Should I maybe try to compile it on the windows machine?

Best Regards

**Comment by Glavin001** [comment]
Why are you copying the Atom Beautify package folder? This should not be done.

>  folder is causing this and it starts at atom-beautify/node-modules

This is handled by `npm`, Node'js package manager. It is the folder for *other dependency packages*, so not Atom Beautify source code.

Please install properly with Atom's package manager.

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.
