### ISSUE TITLE
php_beautifier error (or bad installation?)

### ISSUE THREAD

**Issue by bronze** [Glavin001/atom-beautify#241]
hi there

when trying to beautify php i get

    Command failed: /bin/sh -c [ -f ~/.bash_profile ] && source ~/.bash_profile > /dev/null 2>&1;[ -f ~/.bashrc ] && source ~/.bashrc > /dev/null 2>&1;php "/users/bronze/pear/bin/php_beautifier" --input "/var/folders/y7/2xqg1601455cq89gjdy7t5qh0000gn/T/input115217-312-339wa0" --output "/var/folders/y7/2xqg1601455cq89gjdy7t5qh0000gn/T/115217-312-zovrpv"

checked and saw it was really similar to issue #148 (which is closed).
dont know if this is a new one in the wild or i just went full retard on installing beautifier.

**Comment by Glavin001** [comment]
Try `php "/users/bronze/pear/bin/php_beautifier" --help` in your Terminal and see if `php_beautifier` is installed and working.

**Comment by bronze** [comment]
right on point. it returned an error:

    Warning: require_once(PEAR.php): failed to open stream: No such file or directory in /users/bronze/pear/bin/php_beautifier on line 37

so i went google-fu'ing and found the best way was to enable my php.ini (copy /private/etc/php.ini.dafault into /private/etc/php.in) and adding a line with PEAR's path to it.
Right at the bottom of the new php.ini i added ``include_path=".://Users/bronze/pear/share/pear/"``
lo and behold, no more errors.

thanks for the help Glavin! cheers!

**Comment by Glavin001** [comment]
Glad to hear it worked out!
