### ISSUE TITLE
Remove or move "Beautify Directory" option in hover menu

### ISSUE THREAD

**Issue by nielskrijger** [Glavin001/atom-beautify#244]
By default the first option in the right-click menu when hovering over a directory is "Search Directory"; an option I use a lot.

With Atom-beautify installed this changes to "Beautify Directory"; I've already accidentally clicked it several times and decided to deinstall atom-beautify as a result after failing to disable this feature. Clicking it by accident is likely to mess up quite a lot and combined with unstaged changes can be a very costly mistake (believe me).

**Comment by Glavin001** [comment]
This has already been done. Please update Atom Beautify  See #213 And update to above v0.21.5
