### ISSUE TITLE
Installing “atom-beautify@0.33.4” failed.

### ISSUE THREAD

**Issue by naveenbettiah** [Glavin001/atom-beautify#2444]
Installing “atom-beautify@0.33.4” failed.

npm ERR! Unexpected end of JSON input while parsing near '...1utieKjMndBAklg4VqSIe'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XYZ\.atom\.apm\_logs\2020-02-10T06_32_12_278Z-debug.log

I have installed several other packages to my Atom but only this particular package is throwing error every time I'm trying to install it. Please help. What wrong am I doing?

**Comment by nic4bags** [comment]
I am having similar issue

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AGAPE_FORCE-NAT\.atom\.apm\_logs\2020-02-13T05_38_53_825Z-debug.log

**Comment by naveenbettiah** [comment]
I just lost the hope that I'll be able to install this package as there is no quick responses from the developing team. But after two days when I tried again, unexpectedly it installed successfully on my Atom. Can't figured out what was the issue earlier. Closing this issue as it has solved for me. You are advised to open a new thread with your error. Best of Luck.

**Comment by jkisika** [comment]
Am having the same issues on installing atom-runner package, Am new to programming and I wanted to have my first start with Ruby also receiving the same error

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file
I emailed the team hopefully it will be resolved soon
