### ISSUE TITLE
Not passing 'preserve_newlines' args through to Prettydiff for LESS/SCSS formatting

### ISSUE THREAD

**Issue by sebastiankade** [Glavin001/atom-beautify#245]
When specifying the preserve_newlines in .jsbeautifyrc they do not get passed through to prettydiff, see:
https://github.com/Glavin001/atom-beautify/blob/master/lib/langs/css-prettydiff-beautify.coffee#L4-L10

Originally raised here:
https://github.com/Glavin001/atom-beautify/issues/211#issue

**Comment by Glavin001** [comment]
Looks like `preserve_newlines` is not even supported on CSS (yet): https://github.com/beautify-web/js-beautify/issues/537

I'm working on Prettydiff support now.

**Comment by Glavin001** [comment]
The only property I see is `preserve` ( see 31 in http://prettydiff.com/documentation.php#function_properties ). Is that the `preserve_newlines` you are looking for?

> Retain empty lines in either JavaScript or CSS like languages. Consecutive empty lines will be converted to a single empty line.

**Comment by Glavin001** [comment]
Published to v0.22.5

Atom Beautify uses a boolean (true or false) value for `preserve_newlines` option and will translate to `all` in Prettydiff. Support is only for LESS/SCSS/SASS (Prettydiff supported languages).

Thank you for your patients.

**Comment by sebastiankade** [comment]
Thanks so much!
