### ISSUE TITLE
Ruby beautification support

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#25]
See https://github.com/CraigWilliams/BeautifyRuby

**Comment by huanzhang** [comment]
@Glavin001 Could you tell me how to set spaces as the default indent character for ruby-beautify?

**Comment by mh61503891** [comment]
@huanzhang This is just a makeshift way, but I have created the following ruby script named `/path/to/my_rbeautify` and set "Ruby rbeautify path" of the atom-beautify's Settings to the path of this script.

```ruby
ARGV = %w(--spaces --indent_count 2) + ARGV
load '/Users/masayuki/.gem/ruby/2.2.0/bin/rbeautify'
```

The real path of the rbeautify can be detected by '$ type -a rbeautify'

**Comment by huanzhang** [comment]
@mh61503891 Seems your solution is more convenient for configuration, but I have just solved this by rebuild ruby-beautify(https://github.com/huanzhang/ruby-beautify/commit/4152fe6bbb37e11386b60daf52318004fa84eb6f).

To have spaces as default indention for ruby, I have submit a pull request to ruby-beautify(https://github.com/erniebrodeur/ruby-beautify/pull/15)

**Comment by ahmetabdi** [comment]
rbeautify is completely messed up, if you try beautify a ruby file with it everything just gets removed inside the file! :-1:

**Comment by ahmetabdi** [comment]
Could update to using rubocop with the `-a/--auto-correct` flag? at least it's something
