### ISSUE TITLE
Would be great to support Erlang language.

### ISSUE THREAD

**Issue by minimedj** [Glavin001/atom-beautify#253]

**Comment by Glavin001** [comment]
Have you tried `erl_tidy`? If that works for you, let me know, and I could look into adding Atom Beautify support for it.

**Comment by Glavin001** [comment]
If Erlang developers could test out `erl_tidy` and let me know if it works, this beautifier could be added.

**Comment by Glavin001** [comment]
Completed in https://github.com/Glavin001/atom-beautify/pull/683
