### ISSUE TITLE
Groovy, Jenkinsfile

### ISSUE THREAD

**Issue by metaIhead** [Glavin001/atom-beautify#2531]
What about  Beautify for groovy and Jenkinsfile ? :)

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
