### ISSUE TITLE
Broke single word into two

### ISSUE THREAD

**Issue by LeeroyJenks** [Glavin001/atom-beautify#254]
For some reason, in a wordpress header (php with html code) it broke an "array" into "a rray", which then broke the code. Not sure what this issue may actually be, but thought it should be noted.

**Comment by prettydiff** [comment]
Would you be able to provide a small code sample that the bug can be reproduced?

**Comment by Glavin001** [comment]
If this issue is still occurring, let us know with some reproducible steps and we can look into it. Thank you.
