### ISSUE TITLE
Atom Beautify SCSS disable unitless zero

### ISSUE THREAD

**Issue by joel-st** [Glavin001/atom-beautify#2543]
# Description

Since IE11 (and other browsers too) needs Zero with Units, I try to setup Atom Beautify to beautify my SCSS without removing Units from zero values.

I am not able to disable this beautification. So we start using this ugly workaround:

```
.element {
  flex: 1 1 0.00000001px;
}
```

# Input Before Beautification

This is what the code looked like before:

```
.element {
  flex: 1 1 0px;
}
```
# Expected Output

The beautified code should have looked like this:

```
.element {
  flex: 1 1 0px;
}
```

# Actual Output

The beautified code actually looked like this:

```
.element {
  flex: 1 1 0;
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/joel-st/3b906b3bf4568d365a42b3a5bbc2fe2a

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
- [x] Asked this question on Stackoverflow: https://stackoverflow.com/questions/58799597/atom-beautify-scss-disable-unitless-zero

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
