### ISSUE TITLE
Adding spaces before/after <> when using ReactJS syntax

### ISSUE THREAD

**Issue by awamser** [Glavin001/atom-beautify#255]
A space is being added inside the React.render() behind the < and before the > after running beautify.

***Original:***

```javascript
React.render( <App /> ,
    document.getElementById('main'));
```

***After beautify:***

```javascript
React.render( < App / > ,
    document.getElementById('main'));
```

**Comment by Glavin001** [comment]
ReactJS JSX is not *yet* supported, however it will be soon! See #144
