### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by sepenadiaz** [Glavin001/atom-beautify#2554]
I am getting this error when installing via settings and console:

Installing “atom-beautify@0.33.4” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...e":"latest","@types/q'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Desktop\.atom\.apm\_logs\2021-02-20T21_07_44_858Z-debug.log

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
