### ISSUE TITLE
php_beautifier and php-cs-fixer (probable) conflict

### ISSUE THREAD

**Issue by bronze** [Glavin001/atom-beautify#260]
Hi there
Sorry for  coming in here bearing an issue again.

After updating atom-beautify i saw the move to another package and went about installing php-cs-fixer.
went with homebrew for the apparent ease of install and updates/maintenance.
during installation it warned about not having php installed already.
figured it may want its own homebrew-n version so i installed php through homebrew.

now, though, beautify doesnt work with php anymore.
checked ``php "/users/bronze/pear/bin/php_beautifier" --help`` as per Glavin's last help on https://github.com/Glavin001/atom-beautify/issues/241 and this is what returns:
```
PHP Warning:  require_once(PHP/Beautifier.php): failed to open stream: No such file or directory in /users/bronze/pear/bin/php_beautifier on line 49

Warning: require_once(PHP/Beautifier.php): failed to open stream: No such file or directory in /users/bronze/pear/bin/php_beautifier on line 49
PHP Fatal error:  require_once(): Failed opening required 'PHP/Beautifier.php' (include_path='.:/usr/local/Cellar/php56/5.6.7/lib/php') in /users/bronze/pear/bin/php_beautifier on line 49

Fatal error: require_once(): Failed opening required 'PHP/Beautifier.php' (include_path='.:/usr/local/Cellar/php56/5.6.7/lib/php') in /users/bronze/pear/bin/php_beautifier on line 49
```
i figure it might be a conflict with the homebrewn php i installed due to the path. (the cellar also has the pandoc dependency installed, also not working with md)
however, after disabling php beautifier on atom it still didnt do anything on my files. tried firing up php-cs-fixer through the command line and it worked, just not from within atom.

im a bit of at a loss right now on how to proceed.
should i just delete and forget php_beautifier?
any tips on how to troubleshoot php-cs-fixer? (google fu didnt work for me this time)

thank you for your attention

**Comment by Glavin001** [comment]
I'm not a PHP developer, so this is all new for me. I've had a lot of troubles with installing php_beautifier and using it afterwards.

I am using Homebrew as well to install php-cs-fixer. Atom Beautify is no longer using Php_beautifier so you can just forget it. 

Take a look at the [.travis.yml file](https://github.com/Glavin001/atom-beautify/blob/master/.travis.yml) and see how Travis CI (Mac server) is also installing everything.

>  # Update Homebrew
  - brew update
  - brew tap homebrew/dupes
  - brew tap homebrew/versions

>  \# PHP
  - brew tap homebrew/homebrew-php
  - brew install php56
  - brew install php-cs-fixer

If you have php-cs-fixer working then change the `php_cs_fixer_path` (see https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L282-L285 ) to your installation path of php-cs-fixer.
For instance mine is `/usr/local/bin/php-cs-fixer` by `which php-cs-fixer`.

Hope that helps!

**Comment by bronze** [comment]
redid my steps, i actually came pretty close to that walkthrough (yay!)
uninstalled pear and double checked the install, brew doctor returns ok

yea no idea what may be happening, lets see if someone else runs into this

thanks for the help!

**Comment by Glavin001** [comment]
So all working for you? Beautification of PHP files uses php-cs-fixer and looks beeaaaauutiful? :smile:

**Comment by bronze** [comment]
oh sorry, no, still not working
i just wanted to mention i had retraced my steps double checking with yours and i got no clue why it didnt work yet... maybe my computer just had a lazy sunday? gonna come back to it later...

**Comment by Glavin001** [comment]
Are there any errors? And running php-cs-fixer from Terminal works, and you have manually set the `php_cs_fixer_path`? Weird..

**Comment by bronze** [comment]
no errors from atom (like those red windows on the upper-right) or from atom-beautify (a text box below)
config.cson as follows
```
"atom-beautify":
    _analyticsUserId: *maybe this shouldnt be here*
    css_selector_separator_newline: true
    html_brace_style: "end-expand"
    html_preserve_newlines: false
    html_max_preserve_newlines: 1
    php_cs_fixer_path: "/usr/local/bin/php-cs-fixer"
    markdown_yaml_front_matter: false
    html_end_with_newline: true
    beautifyOnSave: true
```
the path is as per ``which php-cs-fixer``, not just copying you :wink: 
php-cs-fixer --version ``PHP CS Fixer version 1.6 by Fabien Potencier (81a46f8)``

**Comment by bronze** [comment]
working... maybe something on the previous updates?
no idea why but wont complain about it, life is good :)
