### ISSUE TITLE
.jsbeautifyrc not working on Windows

### ISSUE THREAD

**Issue by CarterSnich** [Glavin001/atom-beautify#2612]
# Description

Config file not getting loaded on Windows, or maybe I just missed something or done something that overrides my config.

# Steps to Reproduce

1. Created `.jsbeautify` inside `%USERPROFILE`.
2. Inserted the following config:
     ```
      {
	      "indent_size": 4,
	      "indent_char": " ",
	      "other": " ",
	      "indent_level": 0,
	      "indent_with_tabs": false,
	      "preserve_newlines": true,
	      "max_preserve_newlines": 2,
	      "jslint_happy": true,
	      "indent_handlebars": true
      }
     ```
4. Run command `Atom Beautify: Beautify Editor` on a Arduino sketch.
5. The indents are still 8 spaces.

# Debug

Here is a link to [`debug.md`](https://gist.github.com/CarterSnich/4db67526e7632a1352daba662bbc14bb).

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
