### ISSUE TITLE
Some calls are deprecated since Atom 0.189.0

### ISSUE THREAD

**Issue by d4k0** [Glavin001/atom-beautify#267]
Since the update to Atom 0.189.0, these messages appear:

![Deprecated calls](https://i.imgur.com/TMsona6.png)

It would be nice if this could be fixed.

**Comment by Glavin001** [comment]
Please update Atom Beautify before creating new issues.

I believe these have been fixed for a while , #193 , #172 , #195 , etc. 
Also see https://github.com/Glavin001/atom-beautify/blob/master/package.json#L72-L85 which *does* use `activationCommands` instead of `activationEvents`.

Thanks!

**Comment by d4k0** [comment]
Of course I updated to the latest version (0.23.2) of Atom Beautify before creating this issue, but these deprecated messages are still there. 

BTW: Atom Beautify is not the only package that shows these messages since the update to Atom 0.189.0. I have 4 other packages that also use some deprecated calls.

**Comment by Glavin001** [comment]
This is strange. I will have to look into this closer after my midterms. Thanks for confirming.

**Comment by d4k0** [comment]
No problem. You don't need to hurry as Atom Beautify still seems to work without a problem.

Atom 0.189.0 seems to have changed quite a few things regarding deprecated calls (you can see this when you look at the commits to the Atom repository, but it's not mentioned in the changelog) as the other packages all mention different calls (or directory names for themes) that shouldn't be used anymore.

**Comment by Glavin001** [comment]
I am unable to reproduce your results above in the Deprecation Cop. Could you provide some information on how you were able to achieve those deprecation warnings? I am currently opening Atom and beautifying files which should trigger those warnings.

Also if you could run `Beautify : Help Debug Editor` and paste contents here, that may be helpful. 
Thanks!

**Comment by d4k0** [comment]
I just tried it with a new profile with only Atom Beautify installed and this is how it looks:

![New profile with Atom Beautify](https://i.imgur.com/jsFSGbw.png)

As you can see Atom now somehow only shows one of the deprecation warnings here. It seems that maybe some of my other packages affect Atom Beautify (I already could observe this with other packages that complain about the stylesheet folder of another package), but so far I haven't had any luck to find out which one of the packages is the culprit (I will do some more tests).

Regarding the deprecation warnings: I get them when I start Atom (no file has to be loaded):

![Deprecation warnings](https://i.imgur.com/5dJGH5Z.png)

Here is the requested Beatifiy debugging information (the only strange thing that I noticed here is the path at ```Home Options``` as it doesn't exist; my user folder is on ```C:```):

# Atom Beautify - Debugging information

The following debugging information was generated by `Atom Beautify` on `Mon Apr 06 2015 20:40:02 GMT+0200 (Mitteleuropäische Sommerzeit)`.

---

**Platform**: win32

## Versions

**Atom Version**: 0.189.0

**Atom Beautify Version**: 0.23.2

## Original file to be beautified

**Original File Path**: `C:\Users\d4k0\.atom\packages\seti-syntax\sample-files\Html.html`

**Original File Grammar**: HTML

**Original File Contents**: 
```HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Jade</title>
    <script type="text/javascript">
      var foo = false;
      if (foo) {
        var bar = 6;
        return bar;
      }
    </script>
  </head>
  <body>
    <h1>Jade - node template engine</h1>
    <div id="container" class="col">
      <p>You are amazing</p>
      <p>
        Jade is a terse and simple
        templating language with a
        strong focus on performance
        and powerful features.
      </p>
    </div>
  </body>
</html>

```

## Beautification options

**Editor Options**: 
Options from Atom Editor settings
```json
{
    "indent_size": 2,
    "indent_char": " ",
    "indent_with_tabs": false
}
```

**Config Options**: 
Options from Atom Beautify package settings
```json
{
    "js": {
        "indent_size": 2,
        "indent_char": " ",
        "indent_level": 0,
        "indent_with_tabs": false,
        "preserve_newlines": true,
        "max_preserve_newlines": 10,
        "space_in_paren": false,
        "jslint_happy": false,
        "space_after_anon_function": false,
        "brace_style": "collapse",
        "break_chained_methods": false,
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "space_before_conditional": true,
        "eval_code": false,
        "unescape_strings": false,
        "wrap_line_length": 0,
        "end_with_newline": false
    },
    "css": {
        "indent_size": 2,
        "indent_char": " ",
        "selector_separator_newline": false,
        "newline_between_rules": false,
        "preserve_newlines": false
    },
    "html": {
        "htmlbeautifier_path": "",
        "indent_inner_html": false,
        "indent_size": 2,
        "indent_char": " ",
        "brace_style": "collapse",
        "indent_scripts": "normal",
        "wrap_line_length": 250,
        "wrap_attributes": "auto",
        "wrap_attributes_indent_size": 2,
        "preserve_newlines": true,
        "max_preserve_newlines": 10,
        "unformatted": [
            "a",
            "sub",
            "sup",
            "b",
            "i",
            "u"
        ],
        "end_with_newline": false
    },
    "sql": {
        "indent_size": 2,
        "keywords": "upper",
        "identifiers": "lower",
        "sqlformat_path": ""
    },
    "markdown": {
        "pandoc_path": "",
        "yaml_front_matter": true
    },
    "perl": {
        "perltidy_path": "perltidy",
        "perltidy_profile": ""
    },
    "php": {
        "cs_fixer_path": "",
        "fixers": "",
        "level": ""
    },
    "python": {
        "autopep8_path": "",
        "max_line_length": 79,
        "indent_size": 2,
        "ignore": [
            "E24"
        ]
    },
    "ruby": {
        "rbeautify_path": ""
    },
    "c": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "cpp": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "objectivec": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "cs": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "d": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "java": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "pawn": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "vala": {
        "uncrustifyPath": "",
        "configPath": ""
    }
}
```

**Home Options**: 
Options from `D:\Users\d4k0\.jsbeautifyrc`
```json
{}
```

**EditorConfig Options**: 
Options from [EditorConfig](http://editorconfig.org/) file
```json
{}
```

**Project Options**: 
Options from `.jsbeautifyrc` files starting from directory `C:\Users\d4k0\.atom\packages\seti-syntax\sample-files` and going up to root
```json
[
    {},
    {},
    {},
    {},
    {},
    {}
]
```

## Logs

**Error logs**: *Not yet supported*

**Comment by Glavin001** [comment]
Hi @d4k0 , could you confirm that these deprecation warnings still appear for you? I am going through and cleaning up, given Atom's API will remove those deprecation warnings and start breaking in a month or so. Thanks.

**Comment by d4k0** [comment]
Hi,
The ContextMenuManager message was fixed with https://github.com/Glavin001/atom-beautify/pull/279. A week ago I made some tests regarding the other messages and it turned out that Atom somehow "propagated" these message from other packages (mostly linters). I had to deactivate package after package to find this out (Atom then always showed another package as the culprit until I found the right ones). So there doesn't seem to be a problem with atom-beautify anymore. Thanks for the fix!

One interesting note: I updated to Atom 0.196.0 today (from 0.194.0) and the packages which are still using deprecated calls are now listed correctly (instead of listing one "innocent" package as the source), so they seem to have fixed this "bug".

**Comment by Glavin001** [comment]
> So there doesn't seem to be a problem with atom-beautify anymore. 

Great to hear. Thanks for looking deeper into this!

> One interesting note: I updated to Atom 0.196.0 today (from 0.194.0) and the packages which are still using deprecated calls are now listed correctly (instead of listing one "innocent" package as the source), so they seem to have fixed this "bug".

Really glad they have fixed that.
