### ISSUE TITLE
Atom commands for specific language

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#27]
See https://github.com/taronfoxworth/atom-beautifier/blob/master/lib/beautifier.coffee#L99-L102 

``` coffee
  atom.workspaceView.command "beautifier", -> convert()
  atom.workspaceView.command "beautifier:js", -> convertJs()
  atom.workspaceView.command "beautifier:html", -> convertHTML()
  atom.workspaceView.command "beautifier:css", -> convertCSS()
```

**Use case:** highlight a specific area of code that is a different language than the overall file's grammar type. Now apply the desired, correct, beautification.

**Comment by ilanbiala** [comment]
@Glavin001 can this be closed?

**Comment by Glavin001** [comment]
Nope, not yet implemented.

**Comment by Glavin001** [comment]
- [ ] Create list of all the supported Grammars from https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L396
- [ ] Iterate over supported Grammars and create Command
  - [ ] Call `beautify` and force the `grammar` parameter to be the selected grammar
     - See https://github.com/Glavin001/atom-beautify/blob/master/lib/beautify.coffee#L176

**Comment by l3ender** [comment]
This would be fantastic 👍

**Comment by Glavin001** [comment]
It's working!

## Example beautifying JavaScript within HTML

Step 1) Select the appropriate code.

![image](https://cloud.githubusercontent.com/assets/1885333/25775305/cd6d3e0c-3278-11e7-9bdd-3a3558569861.png)

Step 2) Open command palette and search for `Atom Beautify: Beautify Language Javascript`.

![image](https://cloud.githubusercontent.com/assets/1885333/25775318/104762fc-3279-11e7-8f8c-aa66b722569a.png)

Step 3) Run command and see selected code has been beautified with the specific beautifier for `JavaScript`.

![image](https://cloud.githubusercontent.com/assets/1885333/25775332/220fcdda-3279-11e7-8fd7-2c7b78a57010.png)

**Comment by Glavin001** [comment]
Published to v0.29.24

**Comment by Glavin001** [comment]
![atom-beautify-language-commands-2](https://cloud.githubusercontent.com/assets/1885333/25775586/f3fc7ec4-327e-11e7-8576-45e735e80032.gif)

**Comment by Glavin001** [comment]
Added a new section to README: https://github.com/Glavin001/atom-beautify#beautify-a-specific-language
