### ISSUE TITLE
Characters written in top of python files 

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [Glavin001/atom-beautify#270]
Every time I run `beautify:beautify-editor` in a python file, the following gets written at the very beginning of the file : `[0m[0m[0m`, with character `0x001b` in front of each `[`. It stacks if ran multiple times.

I can't reproduce this behaviour using `autopep8` from command line, nor using another beautifier (such as HTML and CSS ones).

Configuration:

* Linux 3.16.7.8-1-MANJARO x86_64
* Atom 0.189.0 [(source)](https://aur.archlinux.org/packages/atom-editor-bin/)
* autom-beautify 0.23.4
* autopep8 1.1

[Debug log](http://pastebin.com/raw.php?i=78snq8Nu)

**Comment by Glavin001** [comment]
What version of Atom Beautifier?

**Comment by GeoffreyFrogeye** [comment]
Latest, just upgraded.

**Comment by Glavin001** [comment]
This sounds exactly like #215. Very strange that updating to latest Atom Beautify did not help. Have you reloaded Atom? Menu -> View -> Reload

**Comment by GeoffreyFrogeye** [comment]
Yes, still the same issue.
It's been around since I started used it, probably since 0.20 or so.

**Comment by Glavin001** [comment]
Weird.

Could you run the command `Beautify : Help Debug Editor` and send me contents. Thanks!

In a separate comment, to keep this organized/clean: also could you give #215 a quick read? That is pretty much what I assume to be the problem, just the current patch is not working for you. Specifically after this part: https://github.com/Glavin001/atom-beautify/issues/215#issuecomment-78538798
Let me know what happens. Thanks!

**Comment by GeoffreyFrogeye** [comment]
Here you go: <http://pastebin.com/raw.php?i=78snq8Nu>
I already started reading #215, I'll try stuff and come back.

**Comment by GeoffreyFrogeye** [comment]
Ok, update time. #215 made me try unloading my `~/.bashrc` file, which has custom prompt in it, reloaded atom from a clean terminal, and was **unable** to reproduce the issue.

Looks like `autopep8` call is interfering with custom prompt.

Currently trying to figure out which part of the prompt is incriminated.

**Comment by GeoffreyFrogeye** [comment]
Ok, it's not exactly the custom prompt that is messing up, but an extra feature, that makes my prompt and the comand I type bold while the output isn't, i.e. that line:
```bash
trap 'echo -ne "\e[0m"' DEBUG
```
We find the pattern that we previously saw, and if I use the following:
```bash
trap 'echo -ne "A"' DEBUG
```
I get `AAA` in front of my files.

You can remove the `high-priority` label I guess :smile:.

Now the question is: how to properly call `autopep8` without having `trap` interfering ?
Also, for curiosity: why the `trap` pattern **three times** ?

**Comment by Glavin001** [comment]
This should be resolved with the new changes in #282 and #164. Currently (your release), Atom Beautify will actually run your `~/.bashrc`, which can have these weird characters, as we have discovered.
The new release should not do this (will require some testing).

> Also, python beautifier relies on cli-beautify as probably other linters do, why can't I get the same bug with other linters? (again, only tried with HTML and CSS).

Only beautifiers that use cli-beauty base class will have this problem and use a shell to execute. HTML and CSS are handled in Node.js by packages such as [js-beautify](http://jsbeautifier.org/).

I'll post here once #282 is released and we can see if this issue still persists.

**Comment by Glavin001** [comment]
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.
