### ISSUE TITLE
PHP Being removed when running beautify

### ISSUE THREAD

**Issue by drawcard** [Glavin001/atom-beautify#277]
Hi,

The following lines are being removed from my PHP file when running the beautifier:

```
use Roots\Sage\Config;
use Roots\Sage\Wrapper;
```

For example, this occurs:

**Before**
```
<?php

namespace Roots\Sage;

use Roots\Sage\Config;
use Roots\Sage\Wrapper;

?>
```

**After**
```
<?php

namespace Roots\Sage;

?>
```

Using Atom 1.9.0

**Comment by Glavin001** [comment]
Hi. If this is still occuring please: update Atom Beautify and run `Help Debug Editor`. 
However, Atom Beautify uses PHP-CS-Fixer for PHP beautification so it may be an issue with PHP-CS-Fixer and nothing that Atom Beautify can do.

**Comment by Glavin001** [comment]
With some more information this can be investigated. For now, I'm going to close this issue, as with the new releases all of the PHP tests are passing.

**Comment by drawcard** [comment]
Sorry, things have been flat out for me so I haven't had time to test. I'll check it out in a day or so now after following your directions.

**Comment by drawcard** [comment]
I should add the file in question where this is occuring is this one: https://github.com/roots/sage/blob/master/base.php

If you wanted to grab a copy and try it yourself feel free :smiley:
