### ISSUE TITLE
Disable Beautify on Save on per-language basis not working.

### ISSUE THREAD

**Issue by garrows** [Glavin001/atom-beautify#284]
In the `Disabled Languages` section I have put:
```
.json, json,json,.json, .ejs, ejs,ejs,.ejs
```
but it still formats json and ejs. 

This was apparently done in https://github.com/Glavin001/atom-beautify/issues/118 but isnt working for me.

Thanks in advance.

**Comment by ac360** [comment]
Same issue here.  Format on save breaks my ejs templates

**Comment by Glavin001** [comment]
I will be deprecating the current array of strings form of `Disabled Languages` for a much more user-friendly and less error-prone view of the options. Coming soon with release of #282.

**Comment by Glavin001** [comment]
This is now implemented for #282 and will be released soon (this week). You will no longer use `Disabled Languages` and instead will disable each language for their individual language configuration. For instance, this is what it looks like to disable languages `JSON` and `EJS`:
![image](https://cloud.githubusercontent.com/assets/1885333/7441962/2f344550-f0d5-11e4-9b84-757519c9dab5.png)

It will be much less error-prone and no longer relies on grammars or extensions.

**Comment by garrows** [comment]
Awesome. Thanks.
