### ISSUE TITLE
Beautify adds extra space in HTML properties 

### ISSUE THREAD

**Issue by netmou** [Glavin001/atom-beautify#287]
duplicate #231 issue
beautify adds extra space into phpcode like below  when a html file width embed phpcode and edited in html snippet-mode

...
 <?php $ Info=m ysql_fetch_assoc ( $mysql->execute ( "select * from bumen_info where CODE=" . $ info ['badw'] ) ); ?>
...

**Comment by Glavin001** [comment]
PHP is handled by [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). I'd recommend forwarding these related issues over to their maintainers at https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues
