### ISSUE TITLE
TextBuffer.on is deprecated.

### ISSUE THREAD

**Issue by nileshmali** [Glavin001/atom-beautify#289]
Use TextBuffer::onWillSave instead. A TextBuffer instance is no longer provided as a callback argument.
```
TextBuffer.on (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1179:16)
Object.subscribeWith (/opt/atom/resources/app.asar/node_modules/emissary/lib/subscriber.js:28:32)
Object.subscribe (/opt/atom/resources/app.asar/node_modules/emissary/lib/subscriber.js:63:21)
<unknown> (/home/nilesh/.atom/packages/atom-beautify/lib/beautify.coffee:319:13)
```

**Comment by Glavin001** [comment]
And migrate to [Event-kit](https://github.com/atom/event-kit) from [emissionary](https://github.com/atom/emissary). 

See https://atom.io/docs/api/v0.196.0/TextBuffer#instance-onWillSave and https://github.com/Glavin001/atom-beautify/blob/4915c38b2a31d3a3b7053f8dab254a0f94d0bb20/lib/beautify.coffee#L316-L319
