### ISSUE TITLE
Add missing Pretty Diff options

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#297]
- [x]  comm           - if comments should receive indentation
- [x]  cssinsertlines - if lines should be forcefully inserted between CSS blocks (see #265 )
- [x] force          - if indentation should be forcefully applied to markup even if it disruptively adds unintended whitespace to the documents rendered output
- [x] langdefault    - if `lang = "auto"` cannot determine an actual language a value can be specified as the default
- [x] quoteConvert   - if single quotes should be converted to double quotes or the opposite
- [x] vertical       = if JavaScript assignment lists and object properties and CSS property assignments should be vertically aligned for easy reading
- [x] wrap           - if code should wrap after a given number of columns. This option is applied only gracefully and does not compete with indentation

/cc @prettydiff

**Comment by Glavin001** [comment]
@prettydiff, here is the `Pretty Diff` beautifier code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L11-L18
Any other important options that I am missing?

**Comment by prettydiff** [comment]
I will review this later today.

**Comment by prettydiff** [comment]
I have deprecated the option `alphasort`. Please use `objsort` instead.

Multilanguage Missing options
---

* comm           - if comments should receive indentation
* cssinsertlines - if lines should be forcefully inserted between CSS blocks 
* force          - if indentation should be forcefully applied to markup even if it disruptively adds unintended whitespace to the documents rendered output
* langdefault    - if `lang = "auto"` cannot determine an actual language a value can be specified as the default
* quoteConvert   - if single quotes should be converted to double quotes or the opposite
* vertical       = if JavaScript assignment lists and object properties and CSS property assignments should be vertically aligned for easy reading
* wrap           - if code should wrap after a given number of columns. This option is applied only gracefully and does not compete with indentation


I know you are not using Pretty Diff for JavaScript, but here is a summary of missing options for my own documentation in case Pretty Diff is added for JavaScript support later.

JavaScript only options
---

* braceline    - should a newline pad blocks in javascript
* bracepadding - should a space pad conditions in javascript
* braces       - should curly braces in javascript be "allman" style or "knr" style 
* correct      - should some autocorrection occur on JavaScript code:
   - insert missing semicolons
   - insert missing curly braces
   - convert some instances of `++` and `--` to `+=` and `-=` respectively
   - convert `new Array()` and `new Object()` to `[]` and `{}` respectively
* elseline     - if the `else` keyword should be given its own line
* space        - if a space should be inserted between `function` keyword and the first `(` if there is no function name
* styleguide   - if beautification options should conform to a given popular style guide
* varword      - if list of variables should be consolidated into a comma separated list or forcefully broken apart so each is given a `var` keyword

vertical example

    p {
        color         : red;
        background    : blue;
        font-size     : 1.2em;
        vertical-align: middle;
    }

wrap example with a value of 20

    <p>A big long

        sentence that wraps

        onto multiple

        lines</p>

braceline example

    if (a === b) {
    
        return;
        
    }

bracepadding example

    if ( a === b ) {
        return;
    }

**Comment by Glavin001** [comment]
Awesome, thanks @prettydiff !

**Comment by Glavin001** [comment]
See available options for `Pretty Diff` beautifier: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff

**Comment by Glavin001** [comment]
Published to v0.28.0
