### ISSUE TITLE
Add config Importer API

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#299]
Import configurations from external sources:
- [ ] [EditorConfig](http://editorconfig.org/)
- [ ] Atom Linters, see #286
- [ ] [CSScomb's `.csscomb.json` file](http://csscomb.com/)
- [ ] [JS Beautifier](http://jsbeautifier.org/)'s `.jsbeautifyrc` file

Some of these are already implemented internally. These should be moved out into reusable components using an API of some form, similar to how Beautifiers now work after #282.

**Comment by danielbayley** [comment]
Would be handy if we could specify a path to a custom `csscomb.json` in the settings.

**Comment by solarsailer** [comment]
I agree. I'd prefer to store the `.csscomb.json` file into my $HOME folder (like other dotfiles) than in each project. :)

I think that this use case might be applicable to other beautifiers as well.

**Comment by Glavin001** [comment]
Should add more to this list.

**Comment by Glavin001** [comment]
This will be implemented in Unibeautify: https://github.com/Unibeautify/unibeautify-options-importer
