### ISSUE TITLE
Python beautifier erase the whole document

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [Glavin001/atom-beautify#301]
Since 0.26 (or 0.25, I haven't tried with this one), when you run the beautifier on a Python document, it become empty.

Here's [a log](https://gist.github.com/GeoffreyFrogeye/bc22b8bff9d944a1a513) that will hopefully provide everything you need.
`autopep8` (which is located in `/usr/bin`) works as intended, removing `~\.bashrc` doesn't change a thing.

**Comment by Glavin001** [comment]
I am able to reproduce this issue. I apologize for the inconvenience. This likely broke with v0.25.0. I am working on it now and adding Python tests so that this will not happen again in the future.

**Comment by Glavin001** [comment]
Originally working Python beautifier: https://github.com/Glavin001/atom-beautify/blob/v0.24.1/lib/langs/python-beautify.coffee

**Comment by Glavin001** [comment]
Published fix to v0.26.1

**Comment by GeoffreyFrogeye** [comment]
It now works correctly, thanks !

**Comment by Glavin001** [comment]
Awesome, thanks for letting me know :smiley:.
