### ISSUE TITLE
autopep8 is not very friendly with debian 8

### ISSUE THREAD

**Issue by yvan-sraka** [Glavin001/atom-beautify#307]
Hello,

This morning, I decided to install `autopep8` on my new `debian 8` machine:

	$ sudo apt-get install python-autopep8
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	The following extra packages will be installed:
	  pep8 python-setuptools
	The following NEW packages will be installed:
	  pep8 python-autopep8 python-setuptools
	0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
	Need to get 309 kB of archives.
	After this operation, 1,098 kB of additional disk space will be used.
	Do you want to continue? [Y/n] Y
	Get:1 http://ftp.fr.debian.org/debian/ testing/main python-setuptools all 5.5.1-1 [242 kB]
	Get:2 http://ftp.fr.debian.org/debian/ testing/main pep8 all 1.5.7-2 [36.2 kB]
	Get:3 http://ftp.fr.debian.org/debian/ testing/main python-autopep8 all 0.9.1-2 [30.6 kB]
	Fetched 309 kB in 1s (168 kB/s)           
	Selecting previously unselected package python-setuptools.
	(Reading database ... 229779 files and directories currently installed.)
	Preparing to unpack .../python-setuptools_5.5.1-1_all.deb ...
	Unpacking python-setuptools (5.5.1-1) ...
	Selecting previously unselected package pep8.
	Preparing to unpack .../archives/pep8_1.5.7-2_all.deb ...
	Unpacking pep8 (1.5.7-2) ...
	Selecting previously unselected package python-autopep8.
	Preparing to unpack .../python-autopep8_0.9.1-2_all.deb ...
	Unpacking python-autopep8 (0.9.1-2) ...
	Processing triggers for man-db (2.7.0.2-5) ...
	Setting up python-setuptools (5.5.1-1) ...
	Setting up pep8 (1.5.7-2) ...
	Setting up python-autopep8 (0.9.1-2) ...

And now when I try to clean my code, atom replaces it by this error message:

	Usage: autopep8 [options] [filename [filename ...]]
	Use filename '-'  for stdin.

	autopep8: error: no such option: --indent-size

**Comment by Glavin001** [comment]
Strange. Could you run `autopep8 --help` so I could see what options are supported, if not `indent-size`. Let's add Debian 8 support to Atom Beautify.

**Comment by yvan-sraka** [comment]
$ autopep8 --help
	Usage: autopep8 [options] [filename [filename ...]]
	Use filename '-'  for stdin.

	Automatically formats Python code to conform to the PEP 8 style guide.

	Options:
	  --version             show program's version number and exit
	  -h, --help            show this help message and exit
	  -v, --verbose         print verbose messages; multiple -v result in more
		                verbose messages
	  -d, --diff            print the diff for the fixed source
	  -i, --in-place        make changes to files in place
	  -r, --recursive       run recursively; must be used with --in-place or
		                --diff
	  -j n, --jobs=n        number of parallel jobs; match CPU count if value is
		                less than 1
	  -p n, --pep8-passes=n
		                maximum number of additional pep8 passes (default:
		                infinite)
	  -a, --aggressive      enable non-whitespace changes; multiple -a result in
		                more aggressive changes
	  --exclude=globs       exclude files/directories that match these comma-
		                separated globs
	  --list-fixes          list codes for fixes; used by --ignore and --select
	  --ignore=errors       do not fix these errors/warnings (default: E24,W6)
	  --select=errors       fix only these errors/warnings (e.g. E4,W)
	  --max-line-length=n   set maximum allowed line length (default: 79)

**Comment by yvan-sraka** [comment]
$ autopep8 --version
    autopep8 0.9.1

It does not seems very recent ...
For example, here the result when I install in my `virtualenv` `autopep8` with `pip`:

    $ autopep8 --version
    autopep8 1.1.1

**Comment by Glavin001** [comment]
Sounds like you should use pip for installing autopep8. 

I'm going to close this as the problem was an outdated autopep8 installation.
