### ISSUE TITLE
Unsupported language for grammar 'HTML (Twig)' with extension '.twig'.

### ISSUE THREAD

**Issue by Zmaon** [Glavin001/atom-beautify#309]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.26.4

### Stack Trace

Unsupported language for grammar 'HTML (Twig)' with extension '.twig'.

```
At Unsupported language for grammar 'HTML (Twig)' with extension '.twig'.

Error: Unsupported language for grammar 'HTML (Twig)' with extension '.twig'.
  at /Users/simon/.atom/packages/atom-beautify/src/beautifiers/index.coffee:351:28
  at tryCatcher (/Users/simon/.atom/packages/atom-beautify/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._resolveFromResolver (/Users/simon/.atom/packages/atom-beautify/node_modules/bluebird/js/main/promise.js:427:31)
  at new Promise (/Users/simon/.atom/packages/atom-beautify/node_modules/bluebird/js/main/promise.js:53:37)
  at Beautifiers.module.exports.Beautifiers.beautify (/Users/simon/.atom/packages/atom-beautify/src/beautifiers/index.coffee:230:20)
  at atom-workspace.beautify (/Users/simon/.atom/packages/atom-beautify/src/beautify.coffee:133:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:17 core:copy (atom-text-editor.editor.is-focused)
  2x -0:16.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:15.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:15 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:14.4.0 bracket-matcher:close-tag (atom-text-editor.editor.is-focused)
     -0:10.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:delete (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.2.0 beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "linter-coffeelint"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "66fa6d09-0ca0-4bea-acf2-31fc546e7503",
    "css_newline_between_rules": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.26.4
autocomplete-css, v0.6.0
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
color-picker, v1.7.0
css-snippets, v0.8.0
file-icons, v1.5.5
go-plus, v3.3.9
highlight-selected, v0.9.2
javascript-snippets, v1.0.0
language-apache, v1.3.0
language-htaccess, v0.1.1
linter, v0.12.1
linter-js-yaml, v1.0.0
linter-jshint, v0.1.2
linter-php, v0.0.12
mate-subword-navigation, v3.0.1
php-getters-setters, v0.3.0
php-twig, v3.0.0
quickdoc, v0.0.1
symbols-tree-view, v0.9.2
trailing-spaces, v0.2.5

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
See http://twig.sensiolabs.org/doc/templates.html

This looks kind of like ERB. @prettydiff is something like the following already supported:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>My Webpage</title>
    </head>
    <body>
        <ul id="navigation">
        {% for item in navigation %}
            <li><a href="{{ item.href }}">{{ item.caption }}</a></li>
        {% endfor %}
        </ul>

        <h1>My Webpage</h1>
        {{ a_variable }}
    </body>
</html>
```

**Comment by prettydiff** [comment]
The syntax is close enough to other supported languages that Pretty Diff cannot tell it apart. As a result it is already supported.  The above code sample demonstrates an unrelated bug:

https://github.com/prettydiff/prettydiff/issues/85

**Comment by Glavin001** [comment]
@Zmaon , I can create a new supported Language for the grammar `HTML (Twig)` and have Pretty Diff support it. Example file: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/erb.coffee 
Please confirm for me that Pretty Diff works as expected for you, by changing your file's grammar temporarily to something like `HTML (Rails)` or `HTML (Ruby - ERB)` which is recognized as `ERB` in Atom Beautify and is supported by Pretty Diff.
To change a file's currently detected grammar in Atom: Menu --> `Edit` --> `Select Grammar` --> select your new grammar.

@prettydiff I prefer to select the language explicitly instead of using `auto`. Should I just consider this as `markup`? See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L42-L61 for details.

**Comment by Zmaon** [comment]
@Glavin001 I have the following error if I try to switch the grammar to `HTML (Rails)` or `HTML(Ruby - ERB)` and to beautify. Maybe am I missing something?:

    Error: spawn htmlbeautifier ENOENT
      at exports._errnoException (util.js:734:11)
      at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
      at child_process.js:1127:20
      at process._tickCallback (node.js:357:13)

**Comment by Glavin001** [comment]
Oh, my apologies. Could you try `JavaScript Template` instead. I forgot that ERB defaults to using `htmlbeautifier`.

**Comment by Zmaon** [comment]
Ok I installed htmlbeautifier and tester with grammer ´HTML (Rails)´. The only issue I see is that newlines are added at each beautify after "%}". Not sure if this could be fixed in the settings.

**Comment by Glavin001** [comment]
Use `JavaScript Template`, I want to see how Pretty diff handles this, as I will likely be using Pretty diff for this language's beautification support. Also @prettydiff has been great for support, so if there are any bugs we can look into tackling those next.

**Comment by Zmaon** [comment]
I don't see `Javascript Template` in my list of grammars. Is this available in a package?

**Comment by Glavin001** [comment]
Oh looks like that isn't installed in Atom by default. Here's the package: https://atom.io/packages/language-ejs

You can likely delete this after we test this.

Also what package are you using to detect `HTML (Twig)`? I will need to install that so I can do my own tests.

**Comment by Zmaon** [comment]
The package I use for Twig is https://atom.io/packages/php-twig

I just ran a quick test with `Javascript Template`, it looks like it could be ok with some tweaking. I'll run more tests when I have some time.

**Comment by Glavin001** [comment]
Excellent! Then this should go very smoothly and be fairly easy to add support for thanks to @prettydiff.

**Comment by Glavin001** [comment]
Published to v0.27.12

**Comment by keithmancuso** [comment]
can there be an option to indent the twig code as well so for example you have

```
<ul id="navigation">
   {% for item in navigation %}
   <li><a href="{{ item.href }}">{{ item.caption }}</a></li>
   {% endfor %}
</ul>
```

but i would like is 

```
<ul id="navigation">
   {% for item in navigation %}
     <li><a href="{{ item.href }}">{{ item.caption }}</a></li>
   {% endfor %}
</ul>
```
So basically means things like if blocks and for statements are nested

also worth noting that if you have a block of just twig in the file right now like this

{% if entry.description %}
	{% set description = entry.description %}
{% else %}
	{% set description = entry.body %}
{% endif %}

It just puts it all in one line. 

If theres anything i can do to help, I'm happy to do it

**Comment by Glavin001** [comment]
@keithmancuso : I would recommend playing around with http://prettydiff.com/ and if you find that there are bugs or you have feature requests then please forward them over to @prettydiff at https://github.com/prettydiff/prettydiff/issues
We can help there better over there. Twig support and features are handled by the Pretty Diff beautifier.

**Comment by narration-sd** [comment]
Yes, looks like the same problems on prettydiff, and there's a request button right there.

**Comment by prettydiff** [comment]
@narration-sd @keithmancuso  The reason why TWIG is not further indented apart from the HTML is that Pretty Diff responds to syntax only.  TWIG tags are not differentiated by syntax, but by grammar (tag name).

**Comment by narration-sd** [comment]
Trying to understand what you may mean here. 

By 'syntax' you mean that it's just that a new tag has begun without a close tag first that makes HTML tags indent, as an example?

And in Javascript, that it's just the block indicator ({}) which governs?

It would seem that allowing multi-character block indicators would allow Twig to be parsed in the  same fashion, no? What do you think about that?

**Comment by prettydiff** [comment]
How do I know which Twig tags gain or lose indentation?  I have to be able to differentiate the tags, which is done by looking at the tag names, for instance: *if*, *for*, *else*, *endif*, *endfor*.  Currently, the markup parser is not set up to parse based upon any kind of naming.  It parses based only upon syntax.  The only one exception is that the parser understands certain HTML tags are really self-closing tags even if the proper syntax isn't provided, for instance: `<br>` is understood to really be `<br/>`.

The term `syntax` refers to any collection of symbols, which may include words, that convey a rule or operation directly and are directly parse-able as atomic units.  So in the context of Twig specifically something like `{% endfor %}` probably is syntax.  Looking at markup more generally syntax is frequently described as delimiters and the symbols that define internal components within delimiters.  Keeping the basic identification of syntax extremely broad is what allows XML to be very extensible and how HTML can contain separately parse-able languages like template tags and JavaScript.

The parser could be extended to provide more advanced support by supporting Twig tag names, but this would be a lot of extra code for an additional 15-20 tag names.

**Comment by narration-sd** [comment]
Thanks for giving  your notes here - appreciated.

What you said was my point, really, about the intents of the word 'syntax' in prettydiff context, and that Twig ought to fit.

I had a look, and decided I didn't have time to learn coffeescript to go after this. I don't want to imply that you should either, if there are a lot of persons who use Twig out there these days, as with CraftCMS for example.

Thanks...and what you have done is quite useful, also appreciated.

**Comment by prettydiff** [comment]
Thanks, if you can gather some amount of community support for this addition then I am sure the effort and increase of code will be justified. At that time just open an issue at https://github.com/prettydiff/prettydiff/issues

**Comment by johanneslamers** [comment]
I've put on a feature request to add twig language to prettydiff. 

https://github.com/prettydiff/prettydiff/issues/218

Please add your comments to speed up the process
