### ISSUE TITLE
Coffeescript support

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#31]
See https://github.com/derekchiang/Coffee-Formatter

**Comment by v3ss0n** [comment]
it uses default indentation for editor instead of default identation for coffeescript package?

Right now beautify makes 4 spaces indent , making linters unhappy.

**Comment by Glavin001** [comment]
> it uses default indentation for editor instead of default identation for coffeescript package?

I'm not quite sure what you mean by `default indentation for coffeescript package`. I am not sure if [CoffeeScript](http://coffeescript.org/) itself has a recommended default indentation size, however for Atom Beautify all settings are extracted from user configuration and can easily be changed to be what you want, such as the `default indentation for coffeescript package` as you described.

You can see the order of prioritized configurations at https://github.com/Glavin001/atom-beautify#configuration
In addition to `.jsbeautifyrc` you are able to use `.editorconfig` and Atom package settings for Atom Beautify, which provides the easiest view and descriptions for each option.

> Right now beautify makes 4 spaces indent , making linters unhappy.

Then you can simply change it: see https://github.com/Glavin001/atom-beautify#configuration

**Comment by ironyinabox** [comment]
![screen shot 2016-06-06 at 2 31 25 pm](https://cloud.githubusercontent.com/assets/12389386/15833153/6fa7fd8e-2bf3-11e6-9e66-f146fe44d36e.png)
and yet, it's still beautifying with 2 spaces of indent. What gives?

**Comment by Glavin001** [comment]
@ironyinabox please create a new issue and follow the Issue template structure.

More specifically, be sure to add a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by ironyinabox** [comment]
Thanks anyway.
