### ISSUE TITLE
Gracefully handle errors when beautifier binary is not installed

### ISSUE THREAD

**Issue by benogle** [Glavin001/atom-beautify#311]
There should be a [user notification](https://atom.io/docs/api/v0.196.0/NotificationManager#instance-addError) when the binary cannot be found. Without this handler, user's see scary error messages that are attributed to core, and not easy to figure out how to fix. e.g. https://github.com/atom/atom/issues/6636

**Comment by Glavin001** [comment]
+1 I definitely want to improve this experience for users. Thanks for creating this issue.

**Comment by Glavin001** [comment]
I've switched off of `addFatalError` and over to `addError` to make it less *scary*. See #317.

Now to add support to detect installation of the CLI beautifier binaries.

**Comment by Glavin001** [comment]
May be able to find the path of executable if they are installed: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/dba0c5185f7568ac7856e0555749e516cc119780/lib/utils.js#L192-L219

**Comment by Glavin001** [comment]
Will detect if error is ENOENT and replace user's notification message with something more helpful thank Node.js' default.

Note that en ENOENT error has `code` equal to `ENOENT`: https://github.com/nodejs/io.js/blob/e61ee49c7a2f577eb1338ee35f8768d79010ebc9/deps/npm/lib/utils/spawn.js#L18

**Comment by Glavin001** [comment]
Published to v0.27.11
