### ISSUE TITLE
Language Request: grammar "HTML (Swig)" with extension ".html"

### ISSUE THREAD

**Issue by mmarol** [Glavin001/atom-beautify#323]
Will there be support for the HTML Swig syntax anytime soon?

I would like to help, but I don't have sufficient knowledge of what that would require.

>Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "HTML (Swig)" and extension ".html". If you would like to request support for this file and it's language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by Glavin001** [comment]
We may be able to support it already :smile:, with Pretty Diff.

1) Could you provide me with a sample input file so I can add `HTML (Swig)` to my tests

2) You can temporarily try to use Pretty Diff by switching the file's grammar in Atom to one that Pretty Diff handles. Menu --> Edit --> Select Grammar -> Select `HTML (Ruby - ERB)` for example. Then try to beautify. Let me know if this works for you, and if so, then we can definitely support `HTML (Swig)` very soon.

**Comment by mmarol** [comment]
Here are what I think you're asking for with the input files
https://github.com/mmarol/atom-beautifier_HTML-Swig_tests/tree/master

I tried using other HTML grammars, but they would simply remove the returns between the Swig tags, placing them all on the same line.

The Swig tags in the files are the ones that came as snippets with the language-html-swig package (https://github.com/screeny05/language-html-swig).

Thanks for the prompt response!

**Comment by Glavin001** [comment]
@prettydiff is this grammar something that you could support?

@mmarol I am adding Swig language and it uses the Pretty Diff beautifier, however it does not beautify correct. Hopefully this can be resolved by @prettydiff

**Comment by prettydiff** [comment]
Yeah, I am already supporting `{% %}` delimiters. @mmarol could you head over to http://prettydiff.com/?m=beautify and run some tests. If anything breaks just open an issue either here or in my own github repo and I will hop on it.

**Comment by mmarol** [comment]
@Glavin001 thanks for the help. I will run tests and create an issue if needed on @prettydiff's repo.

**Comment by Glavin001** [comment]
Published to v0.27.2
