### ISSUE TITLE
EPERM issue updating

### ISSUE THREAD

**Issue by jerone** [Glavin001/atom-beautify#324]
Almost every other version from atom-beautify gives me issues while trying to update. I can't seem to find a clear reason or clear steps to reproduce, but you might have more inside then me.

The following error is shown when pressing the update button when a new version of atom-beautify is released:

> Updating to “atom-beautify@0.27.0” failed.Hide output…
> EPERM, unlink 'C:\Users\jerone\.atom\packages\atom-beautify\styles'

Navigating to that folder gives me access denied in Windows. When I close Atom, I have access to that folder again.

I don't have any tabs open or any other processes running.

Atom 0.196.0
Windows 7 64-bits

Feel free to close this issue as it's probably not related to atom-beautify, it's just that it only happens to your package. Great package btw!

**Comment by Glavin001** [comment]
I have no idea why this would be occurring. You're right, it is likely not an Atom Beautify issue. Did you find a way to resolve this?

**Comment by jerone** [comment]
> Did you find a way to resolve this?

Sadly no. Maybe it's fixed in Atom. I'll close this issue until I or someone else has more info.
