### ISSUE TITLE
Refuses to save.

### ISSUE THREAD

**Issue by MichaelMcGlothlin** [Glavin001/atom-beautify#326]
Upgraded to 0.27.0. Saw the warning that the auto was depreciated and switched it off and turned on support for each language. Tried to save again and din't get the warning but files aren't saving. Tried JS and HTML/Handlebar and both had the same problem. Had to disable and restart Atom to restore the ability to save.

**Comment by Onigirium** [comment]
I have the same issue.

**Comment by Glavin001** [comment]
I'm going to migrate this over to the first related issue, #314. Please continue discussion there. I want this issue resolved ASAP.
