### ISSUE TITLE
loading dialog pops on save, even when not beautifying

### ISSUE THREAD

**Issue by wyand** [Glavin001/atom-beautify#327]
Even with beautify on save disabled, the loading dialog flickers on all saves. It looks like it is set to show [here](https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L65), before the process has even decided if it will beautify.

Not exactly a show stopper -- but it would be nice to only see a progress dialog pop up when there is something to make progress on.

**Comment by Glavin001** [comment]
I'm pretty sure I know what's going on and what change makes this happen. I'll look into it. Thank you for making me aware of this issue.

**Comment by Glavin001** [comment]
I think the patch in v0.27.1 (see #314 ) should also resolve this. Update and let me know.

**Comment by Glavin001** [comment]
I think the solution should be something like:
- [ ] add event emitter to [Beautifiers](https://github.com/Glavin001/atom-beautify/blob/1335313dc672f7b5624ccc537d042fd37a0b9d67/src/beautifiers/index.coffee)
- [ ] add event handler for toggling the `beautify progress` view
  - [ ] add event handler and toggles the progress view, in https://github.com/Glavin001/atom-beautify/blob/1335313dc672f7b5624ccc537d042fd37a0b9d67/src/beautify.coffee 
  - [ ] [Beautifiers](https://github.com/Glavin001/atom-beautify/blob/1335313dc672f7b5624ccc537d042fd37a0b9d67/src/beautifiers/index.coffee) emits event to trigger progress view event handlers

**Comment by Glavin001** [comment]
Published to v0.28.1
