### ISSUE TITLE
Remove deprecated "Beautify: Beautify Editor" command

### ISSUE THREAD

**Issue by BlaM** [Glavin001/atom-beautify#332]
"Beautify: Beautify Editor" still shows on the command palette, but when selected displays a message:

    The command "beautify:beautify-editor" has been 
    removed and changed to "atom-beautify:beautify-editor".

I kind of see the reason for the message to be there, but that also means that if I enter the command palette, type "beau" and press enter I get the message and not a beautified source code. So then I have to press ESC, enter the command palette again and type "beau", press cursor down and ENTER.

Can't we get rid of the command palette menu entry if it is invalid now? Or at least signal Atom to somehow prioritize the valid command higher than the old (expired) one? Maybe rename the menu entry to "[REMOVED] Beautify: Beautify Editor" or something similar?

**Comment by Glavin001** [comment]
> Or at least signal Atom to somehow prioritize the valid command higher than the old (expired) one?

Atom uses https://github.com/atom/fuzzaldrin for ordering. Last time I had a command that I wanted the order to be different (later), I had to make it longer... See #240

> Maybe rename the menu entry to "[REMOVED] Beautify: Beautify Editor" or something similar?

I'm not sure how Atom allows for renaming commands. All I have is `beautify:beautify-editor` and it generates `Beautify: Beautify Editor` from that. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L390-L392

> Can't we get rid of the command palette menu entry if it is invalid now?

I really want to. I just do not know what is the best way to notify users that the command has been deprecated without them thinking Atom Beautify is broken.
I support the only users this will concern are those who has setup custom shortcuts for Atom beautify: they would no longer work. However, for those using the existing shortcut or using the command palette, would simply type `beau`.. and have the new `Atom Beautify: Beautify Editor`.

---

Let's remove it :+1:.

**Comment by Glavin001** [comment]
Published to v0.27.2
