### ISSUE TITLE
Collapses Shortcut?

### ISSUE THREAD

**Issue by rudarobson** [Glavin001/atom-beautify#334]
Does collapse have a shortcut? 
for collapsing javascript object's property,
1) collapse All on the file
2) collapse everything inside the current cursor's level (everything inside the cursor's parent block context, like in visual studio)

**Comment by Glavin001** [comment]
I don't think this is for Atom Beautify? Would this be better suited for Atom's issue tracker for a question? https://github.com/atom/atom/issues

**Comment by Glavin001** [comment]
Please create this issue on Atom repo. Thanks.
