### ISSUE TITLE
Active Editor not found.

### ISSUE THREAD

**Issue by Cipa** [Glavin001/atom-beautify#336]
Hi,

I recently tried to use atom with phonegap so I built a Hello word(phonegap create my-app) project and I got this

![screen shot 2015-05-07 at 9 12 24 pm](https://cloud.githubusercontent.com/assets/293377/7528909/1aa3ee10-f4fe-11e4-8144-130084f13204.png)

**Comment by Glavin001** [comment]
Could it be because you tried running `beautify` on that Phonegap Preview window?

**Comment by Cipa** [comment]
Don't think so, the error appeared on opening.

**Comment by Cipa** [comment]
Well, it stopped doing it. Running beautify doesn't trigger the error.
I'll reopen if it starts again

**Comment by Glavin001** [comment]
Thanks. Definitely let me know if it happens with these later releases.

**Comment by kwokster10** [comment]
Hi, I'm also getting this error. I restarted Atom and it's still occurring. Was there a fix for this?
<img width="926" alt="screen shot 2016-08-12 at 2 21 41 pm" src="https://cloud.githubusercontent.com/assets/11097983/17633223/3acb2146-609a-11e6-8137-ab3d6c05e288.png">

**Comment by prettydiff** [comment]
@kwokster10 Would you be able to provide any data or instructions that might help us to reproduce this issue?  It sounds like it might be a defect with Atom itself, but we don't have enough information to rule Atom Beautify out yet.

**Comment by kwokster10** [comment]
@prettydiff This was happening when I tried to fire up the Beautify Editor from the Command Palette. This is a fresh install of Atom and the package. It's working now though. Thanks for the response!

**Comment by Vasile-Marian-Danci** [comment]
Hi, when I run Beautify I get the same error.
