### ISSUE TITLE
when beautifying file scrolls to top

### ISSUE THREAD

**Issue by Icehunter** [Glavin001/atom-beautify#338]
I never saw this before (I have latest version) but now when beautifying it will cause the document to scroll to the top rather than being in-place and remembering the scroll position.

Did this always happen like that? Working on large files now is extremely time consuming to scroll back down.

**Comment by Glavin001** [comment]
This is a bug caused by my patch of #314. Thanks for letting me know.

**Comment by Glavin001** [comment]
I should confirm, is this for beautify on save?

**Comment by Glavin001** [comment]
Bump, @Icehunter can you confirm this is for `beautify on save`? It is handled very differently than manually triggered beautification.

**Comment by Iodine-** [comment]
I have the exact same issue with beautify on save.  this behavior is not seen in the regular 'packages -> atom beautify -> beautify' function.  it is VERY tedious every time i save my file to scroll back down 3000+ lines.

**Comment by Glavin001** [comment]
> For additional information: 
1000 line js file = expected behavior (cursor stays in current position)
3000 line js file = unexpected (cursor goes to the top of the page or very near the top)

It changes based on different files? I thought it changes based on using `beautify on save`:

> I have the exact same issue with beautify on save. this behavior is not seen in the regular 'packages -> atom beautify -> beautify' function. it

Can you confirm / explain please.

**Comment by Iodine-** [comment]
Sorry to be unclear.  I meant when the 'beautify on save' is enabled and saving a file with 1000 lines it works fine and as expected.  saving a file with 3000+ lines causes it to scroll to the top of the file. 

Does that help?

**Comment by Glavin001** [comment]
Published to v0.27.8

**Comment by nikmartin** [comment]
This is still happening for me, and I'm on Atom 1.02-9432598 and atom-beautify 0.28.8. I verified it is the beautify package by enabling and disabling the package, reloading the view,  then saving. It also happens whether beautify on save is checked or not, which is weird. If I disable beautify on save and use CTRL+S, the file scrolls to the top.

I can do a screen share to debug.

**Comment by Glavin001** [comment]
> It also happens whether beautify on save is checked or not, which is weird.

@nikmartin: This is strange...

Let's try to figure this out:
- create a new issue
- run Atom command `Atom Beautify - Help Debug Editor` so I can see your current settings and try to understand where it could be going wrong

**Comment by nikmartin** [comment]
OK, will do.
