### ISSUE TITLE
No Rubocop beautification on save

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#340]
I am writing Ruby in a .rb file and on save no beautification happens. Rightclick beautification however works just fine.

Steps taken:
1. Installed `gem install rubocop`
2. Checked the "Language Config - Ruby - Beautify On Save" checkbox in atom-beautify preferences
3. Changed and saved a .rb file
4. No beautification
5. Right click code "Beautify editor content"
6. Works

Atom v0.198.0
Atom-beautify v0.27.1

**Comment by Glavin001** [comment]
So beautification works however the on save is not working for Ruby. Strange it's only with Ruby: the Language Config options are generated automatically, so if Ruby does not work then all of the other languages should have the same problems and it's a problem with the core and not with Ruby specifically.

I'll look into when I have a chance.

For debugging purposes, could you run `Atom Beautify - Help Debug Editor`. Thanks.

**Comment by janwerkhoven** [comment]
It's indeed peculiar. The "on save" works fine for SCSS files, not for my Ruby files. I'll try the debugger and get back to you.

**Comment by Glavin001** [comment]
Any luck, @janwerkhoven ?

**Comment by janwerkhoven** [comment]
Mate, apologies for the delay. I have tried today again with .HBS files (Handlebars) and .RB files (Ruby). Both beautify nicely when pressing CTRL+ALT+B, but nothing on save. In the preferences the "Beautify on save" checkboxes for both languages are checked and the "Disable" checkboxes are unchecked.

How do I enable the debugger?

In preferences I set the Logger Level to "debug". Now what?

I'll try respond a bit quicker now :)

**Comment by Glavin001** [comment]
> Mate, apologies for the delay.

Not a problem. I know all too well how other responsibilities can take you away and cause delays.

> How do I enable the debugger?

You actually have it correct:

> In preferences I set the Logger Level to "debug". Now what?

And set to `verbose` actually.

Now you can view by opening the Developer Tools. Menu -> View -> Developer -> Toggle Developer Tools and then watch for logs. It should *at least* log a message when you save for `save editor positions`. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L408 
The second value in that message is a boolean, `beautifyOnSave`, which indicates if beautification should happen for this Language.

I did just publish an update, v0.27.8, which resolves as many deprecation warnings as I could find. Hopefully it works now for you. Let me know how it goes and what you notice in the logs. Thanks.

**Comment by janwerkhoven** [comment]
All right, I have no idea what changed the last few updates or what I did wrong, but it all works now!

.HBS (Mustache) beautifies on save (I thought this was Handlebars!)
.ERB beautifies on save
.RB beautifies on save
.SASS beautifies on save

This standardises how our team formats code in a one package solution (unlike Sublime).

It also speeds up work!

You're a legend!

**Comment by Glavin001** [comment]
Excellent! Glad to hear it's all working for you and the rest of your team :smiley:!
