### ISSUE TITLE
Add PHP Code Sniffer beautifier for PHP language

### ISSUE THREAD

**Issue by rahul286** [Glavin001/atom-beautify#343]
https://pear.php.net/package/PHP_Beautifier/ is outdated since long.

PHP Code Sniffer has `phpcbf` command which automatically fixes issue. 

Atom plugin - https://atom.io/packages/linter-phpcs

It will be helpful if `phpcbf` is used to fix PHP coding standard issue.

PHP Code Sniffer support many different PHP Coding Standard already.

**Comment by Glavin001** [comment]
PHP-CS-Fixer is the other PHP Beautifier that you can choose. Go to Atom Package Settings for Atom Beautify -> Find `Language Config - PHP - Default Beautify` -> select `PHP-CS-Fixer`.
See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee for beautifier source code.

Feel free to submit pull request for `PHP Code Sniffer`. Thank you.

**Comment by rahul286** [comment]
@Glavin001 thanks for your reply. :-)

I already saw https://github.com/FriendsOfPHP/PHP-CS-Fixer . I think it's different than `phpcbf`command code-sniffer comes with. 

I will try to integrate it with your code. If my attempt works, will send a pull request.

**Comment by Glavin001** [comment]
See https://github.com/Glavin001/atom-beautify/issues/300#issuecomment-107590998 for how to add a new language and/or beautifier.

**Comment by rugk** [comment]
What's different of `phpcbf` compared to php-cs-fixer?

**Comment by rahul286** [comment]
`phpcbf` fixes some issues e.g. spacing, linebreaks automatically

**Comment by Glavin001** [comment]
Supporting multiple beautifiers for the same language is common and expected in Atom Beautify. The more options for the user to choose from the better! I am happy to review a pull request adding this beautifier. Thanks!

**Comment by rugk** [comment]
> `phpcbf` fixes some issues e.g. spacing, linebreaks automatically

Okay, and from what I read it's better to say "`phpcbf` **only** fixes some issues e.g. spacing, linebreaks automatically" because `php-cs-fixer` does this and much more too.

**Comment by jcartledge** [comment]
@rugk `phpcbf` is part of https://github.com/squizlabs/PHP_CodeSniffer, so if you use `phpcs` to check compliance with a particular coding standard you'd naturally want to use `phpcbf` to automatically fix issues based on the same standard.  

@rahul286 are you still planning to look at integrating this? I'm keen to have a go but don't want to double up.

**Comment by Glavin001** [comment]
#744 has been merged and will be in next release.

**Comment by Glavin001** [comment]
Published to v0.28.23
