### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by alicoding** [Glavin001/atom-beautify#344]
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

**Comment by Glavin001** [comment]
I am unable to reproduce this deprecation warning. Could you confirm what Atom version and Atom Beautify version you have?

Here is the current context menu file: https://github.com/Glavin001/atom-beautify/blob/573a949b6f09a629d1ca42db4bcee0965be76c9b/menus/atom-beautify.cson
I believe it is formatted correct, under the key `context-menu` and using `label` and `command` sub-keys.

**Comment by alicoding** [comment]
I can't seem to reproduce this anymore but I was on latest or maybe Atom didn't update the package at the time I'm not so sure. Closing this ticket now :+1:
