### ISSUE TITLE
 PHP beautification not working in Windows (related to #288) 

### ISSUE THREAD

**Issue by guillempascual** [Glavin001/atom-beautify#345]
Hi,
Please take a look at my comments in #288, where you can find the debug info.
Still not working in Windows. It'll show a red error panel.
I made some comments 11 days ago but I guess being a closed issue no on pays attention. 

Thanks.

**Comment by Glavin001** [comment]
#288 could have been reopened. I have now reopened #288.

I have been personally busy with work and family. Being the sole maintainer of this project it is difficult to keep up with these many issues, as I am sure you can understand. I am always accepting Pull Requests and contributions from the community.

Let's continue our discussion over at #288.

**Comment by guillempascual** [comment]
Sure, I understand absolutely, first things first!
 I am willing to cooperate in the way you prefer. I have no experience with nodejs or coffescript though.
Thank you.
