### ISSUE TITLE
Error formatting sql - spawn sqlformat ENOENT

### ISSUE THREAD

**Issue by acarl** [Glavin001/atom-beautify#347]
When trying to format a sql file I get the following error and stack trace.
atom version: 0.199.0
beautify version: 0.27.1

Error: spawn sqlformat ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

**Comment by Glavin001** [comment]
1. Have you installed `sqlparse` which has `sqlformat`? See https://github.com/andialbrecht/sqlparse
2. Could you run `Atom Beautify - Help Debug Editor`

**Comment by acarl** [comment]
Thanks for the quick response. The following command installed this for me on Ubuntu.

`sudo apt-get install python-sqlparse`

**Comment by alexkilla** [comment]
in OS X, just run pip install sqlparse.
