### ISSUE TITLE
Add support for Visualforce

### ISSUE THREAD

**Issue by NemSavic** [Glavin001/atom-beautify#349]
Would be nice to have support for Visualforce grammar and ".page" extension for Salesforce developers.

**Comment by Glavin001** [comment]
This? https://developer.salesforce.com/page/Visualforce_Webinar_Getting_Started

Could you try beautifying a sample at http://prettydiff.com/ and let me know how that goes.

**Comment by prettydiff** [comment]
Yeah, this looks like standard XML syntax. Based upon the three examples in the link above this language is already supported as XML.  @NemSavic try entering crazy edge case samples and really trying to produce errors at http://prettydiff.com/ and let me know what the code samples look like.

**Comment by NemSavic** [comment]
Yup, standard XML syntax. I couldn't come up with anything that might break in prettydiff.

Was hoping we could have native support for Visualforce. I've been changing my file grammar to HTML/XML to format my markup, but I also rely on some autocompletes from the Visualforce grammar. I find myself swapping grammars somewhat frequently which is what I'm trying to get away from.

`Atom Beautify could not determine a supported beautifier to handle this file with grammar "Visualforce" and extension "page"`

**Comment by Glavin001** [comment]
Great! I will add a new language for VisualForce grammar, page extension, and uses Pretty Diff's XML beautifier. Thanks for the feedback everyone!



—

**Comment by NemSavic** [comment]
@Glavin001 thank you!

**Comment by Glavin001** [comment]
Published to v0.27.5
