### ISSUE TITLE
Fix typescript support

### ISSUE THREAD

**Issue by ewgenius** [Glavin001/atom-beautify#351]
Because of some changes in [typescript-formatter](https://github.com/vvakame/typescript-formatter) there is issue
"Cannot find module 'typescript-formatter/typescript-toolbox/lib/formatter'"

**Comment by ewgenius** [comment]
fixed [#352](https://github.com/Glavin001/atom-beautify/pull/352)

**Comment by Glavin001** [comment]
Published to v0.27.3
