### ISSUE TITLE
Right-Click in File Tree to Beautify other files

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#36]
- [x] Right-click single file
- [x] Right-click directory

**Comment by Glavin001** [comment]
So single-file right-click in Atom's tree to beautify is working, and I am using it often actually! (not yet released, coming soon) Now I thinking about the directory beautification support.

I am thinking of using https://www.npmjs.com/package/node-dir and recursively processing the files in sub-directories, and if they are a supported Grammar then beautify them, and if not, ignore the file. Thoughts? How else could this be done, from a users perspective. Possibly list all of the files in the directory and sub-directories and allow the user to select/check files using multi-select-box.

**Comment by Glavin001** [comment]
Single-File support has been published to v0.18.0. Happy New Year! :smiley:

**Comment by budhajeewa** [comment]
Wow great @Glavin001 ! I am eagerly waiting for the directory support. It should be recursive. :)

**Comment by Glavin001** [comment]
Published to v0.19.0! Enjoy :)

**Comment by budhajeewa** [comment]
@Glavin001 You are awesome! :+1:

**Comment by budhajeewa** [comment]
Hi @Glavin001 , I checked this, but I encounter an error when trying to get it to work. Please see #170.

**Comment by luisrudge** [comment]
This is not showing as option anymore :(

**Comment by Glavin001** [comment]
I have temporarily removed this option. See https://github.com/Glavin001/atom-beautify/issues/213

**Comment by IanShoe** [comment]
Just curious if any progress has been made since the concerns from #213?

**Comment by Glavin001** [comment]
@IanShoe : Not yet completed. Would definitely review a Pull Request implementing the feature list here: https://github.com/Glavin001/atom-beautify/issues/213#issuecomment-74425531

**Comment by brunolemos** [comment]
@Glavin001 please add an option to easily do that. You could make an alert with the dangerous risk or open all files without saving it so the user can check it.

**Comment by bs-thomas** [comment]
@Glavin001 Sorry not trying to rush you.  I was really looking forward to this feature actually.  May I ask if there are any updates on this?  Thank you very much for your time and kind attention!

**Comment by Glavin001** [comment]
Hi everyone! Sorry, I haven't had time to implement this. The option could be easily added back ( see https://github.com/Glavin001/atom-beautify/commit/f4b29167f1fc37e4c4f838a1ef75bc9eae2c6e6d ), however I would want there to be safety measures to ensure users do not lose their code, in the case that Atom and/or Atom-Beautify locks up and starts deleting data.
I would be happy to review a Pull Request and have further discussions about this feature. Thanks!

**Comment by julmot** [comment]
What is the preferred workaround in the meantime (for years)? Manually beautifying isn't really an option with many files.

**Comment by Glavin001** [comment]
@julmot : you could edit the `menus/atom-beautify.cson` file and uncomment the `Beautify Directory` command: https://github.com/Glavin001/atom-beautify/commit/f4b29167f1fc37e4c4f838a1ef75bc9eae2c6e6d
I believe Atom packages are installed in `~/.atom/packages` directory. So look for for a file with a possible path of `~/.atom/packages/atom-beautify/menus/atom-beautify.cson` and after you edit the file reload Atom.

**Comment by Glavin001** [comment]
Actually the preferred workaround is not a workaround and instead that someone submits a Pull Request to Atom-Beautify resolving the problems outlined in #213 😄 . I need someone who wants this feature to exist and is willing to contribute to ensure it is developed and supported. I need your help and contribution.

I am currently focusing my after-work-and-after-school hours on #1174 which will provide a lot of value to both users and maintainers. Beautifying a directory of files is on the todo list to be completed after #1174 has been completed. However, no ETA on this feature. The best way to get this feature implemented is to contribute! Thanks in advance!
