### ISSUE TITLE
wrong formatting .jsx

### ISSUE THREAD

**Issue by luisrudge** [Glavin001/atom-beautify#360]
![image](https://cloud.githubusercontent.com/assets/941075/7780979/aacd0c1e-00bc-11e5-8053-2391e7f5e316.png)

**Comment by luisrudge** [comment]
Also, is that a way to setup how things should be formatted?

Current formatting:
```javascript
import {
  Blade,
  BladeContainer
}
from '../Components/Blade/';
```

What I'd expect:
```javascript
import { Blade, BladeContainer } from '../Components/Blade/';
```

**Comment by Glavin001** [comment]
JSX formatting is handled by Pretty Diff. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee
I'd recommend forwarding this issue over to @prettydiff at https://github.com/prettydiff/prettydiff

**Comment by prettydiff** [comment]
JSX is essentially XML embedded in JavaScript. The current beautifier is smart enough to parse JSX where the XML may contain JavaScript and/or where XML/HTML may contain JSX. As such the JavaScript portions will be beautified as JavaScript and the XML portions will be beautified as XML. The only thing specially here is knowing when one parser should hand off to another.

I have looked at the code samples provided here and do not see any errors in Pretty Diff at this time.  I have used the samples in https://github.com/prettydiff/prettydiff/blob/master/unit_tests/beautification_javascript_jsx.txt to validate my conformance to JSX.

**Comment by luisrudge** [comment]
So, I found an interesting bug.

Look at this gif @prettydiff  and @Glavin001. Not sure where the bu lies, though.
![prettydif](https://cloud.githubusercontent.com/assets/941075/7786458/774327fc-01a7-11e5-9609-81e9706d5f47.gif)

The code:

```javascript
import React from 'react';

class MyComponent extends React.Component {
  render() {
    var a = 1;
    return (
      <h1 style={{margin: 0}}>
        Test
      </h1>
    );
  }
}
```

**Comment by prettydiff** [comment]
its a prettydiff bug.

**Comment by luisrudge** [comment]
@Glavin001 can you update this to latest prettydiff please? This bug was fixed here: https://github.com/prettydiff/prettydiff/issues/99

Thanks!

**Comment by Glavin001** [comment]
You could likely trigger the update by uninstalling and installing Atom Beautify. The dependcy is not strict for Pretty Diff so Atom will run npm install and get the most recent version.  



—

**Comment by luisrudge** [comment]
@Glavin001 Yes! It worked. Thanks @Glavin001 and @prettydiff!
