### ISSUE TITLE
Scss beautifying does not work with Prettydiff for some files

### ISSUE THREAD

**Issue by THPubs** [Glavin001/atom-beautify#363]
Earlier this worked. But I re-formatted my system and re-installed atom. Now sass beautifying does not work. No change at all. When I use CssComb it adds extra blank new lines to the file messing it up. Prettydiff simply won't work. No error, no output. Please help.

**Update :** I just noticed that it does not work only for some files. Some scss files work. Before formatting I was working with one project and after that I started a different project. The new project's scss file won't get beautified.

**Comment by Glavin001** [comment]
Please run command `Atom Beautify - Help Debug Editor`.

**Comment by THPubs** [comment]
@Glavin001 Yes I did it, it copied the output to the clipboard with some details. It also have the same output. How can I find the error? I think there are some lines which prevent the beautifying. The file is a bit large so hard to find the exact place but if I keep only few lines it works.

**Comment by Glavin001** [comment]
Please post it as a Gist so I can see it, too. I am hoping to find something useful in the logs.

**Comment by THPubs** [comment]
I finally located the problematic line... In the css file I have a comment like this :

    //=================================
    //=        Sass Variables
    //=================================

When it's removed the beautifying works. I ran the debug on this piece of code :

    //=================================
    //=        Sass Variables
    //=================================
    body{
    background: #FFFFFF;
    }

and here's the gist : https://gist.github.com/THPubs/652314b617d7d2c5fec2

**Comment by THPubs** [comment]
That comment seems to be valid (Im not sure) because Rails didn't threw an error. Normally it gives an error if the scss have any problems.

**Comment by prettydiff** [comment]
Looking into it.

**Comment by prettydiff** [comment]
Language identification confusion on `//==`.

I have fixed this on my local and will publish an update later today once I can also close other a couple of other pending issues.

**Comment by Glavin001** [comment]
This has been fixed in Pretty Diff.

You can force Atom into updating Atom Beautify's dependency packages by uninstalling and reinstalling Atom Beautify, and it will install a fresh copy of the latest Pretty Diff package.
