### ISSUE TITLE
Beautifying html replaces > with ]

### ISSUE THREAD

**Issue by filipesilva** [Glavin001/atom-beautify#365]
This is a weird one. Running the beautify command on

    <input value="1" checked="number > -1"/>

gives out

    <input checked="number ] -1" value="1"/>

But if I do it on the jsbeautify website this does not happen. Anyone know what's up with this? It looks like it's related with the changing the position of the 'value' property.

**Comment by Glavin001** [comment]
Try on http://prettydiff.com/ and see if that is what is breaking

**Comment by filipesilva** [comment]
Yeap, pretty diff is what's breaking it. Should I open an issue there then?

**Comment by Glavin001** [comment]
Yup. Thanks. Let me know once that is resolved and I can update Atom Beautify's Pretty Diff dependency.

**Comment by prettydiff** [comment]
While technically, yes, this is a bug in that Pretty Diff should not be converting `>` to `]` the Pretty Diff bug is not the major issue here. The markup sample above is invalid XML/HTML with unknown consequences at the parser level that will likely fail in different ways in various different parsers.

I expect this defect will be unintentionally resolved when I rewrite my markup parser. Until that time it will remain unresolved.

**Comment by filipesilva** [comment]
Hey, thanks for looking at this! In my case, the real like example was part of an angular [ngCheck](https://docs.angularjs.org/api/ng/directive/ngChecked):

    <input  id="{{group.id}}" type="checkbox" value="{{group.id}}" ng-checked="campaign.groupRecipients.indexOf(group.id) > -1" ng-click="toggleSelection(group.id)" />

Some time after I ran the beautify command, I noticed I was getting loads of errors on my page because the angular parser failed on those lines. 

I cannot speak for handlebars specifically, but in angular it is fairly common to do some basic comparisons for core parts of it.

**Comment by prettydiff** [comment]
I will look into this and see if I can resolve!

**Comment by filipesilva** [comment]
Thank you :D

**Comment by Glavin001** [comment]
@prettydiff and @filipesilva, let me know when this is resolved and if there's any options for Atom Beautify to add.

For the future: You can trick Atom into updating Atom Beautify's dependencies, such as Pretty Diff, by uninstalling Atom Beautify and reinstalling it. Atom will install the latest version of Atom Beautify's dependencies, and you will have the most up-to-date version of Pretty Diff and be able to test these changes @prettydiff is working on.

**Comment by filipesilva** [comment]
Roger!
