### ISSUE TITLE
Beautify files of type HTML(Angular) doesn't work as expected for HTML files

### ISSUE THREAD

**Issue by guymguym** [Glavin001/atom-beautify#367]
Hi
Suddenly after recent update to atom 0.200 or 0.201 beautifying HTMLs suddenly became different.
most notably it doesn't respect the HTML config for preserve_newlines, and breaking lines.

I found that now my html files were auto detected as HTML (Angular) type, and that once I manually chose HTML beautifying went back to normal.

Any idea why HTML (Angular) is behaving badly compared to HTML?

Thanks!

**Comment by Glavin001** [comment]
Atom Beautify treats `HTML (Angular)` internally as `Embedded JavaScript (EJS)`. See https://github.com/Glavin001/atom-beautify/blob/3913267804995c33d595df9d8ba54b21837f443d/src/languages/ejs.coffee#L13 

EJS is handled by the Pretty Diff beautifier: https://github.com/Glavin001/atom-beautify/blob/3913267804995c33d595df9d8ba54b21837f443d/src/beautifiers/prettydiff.coffee#L20

The basic HTML grammar is treated as a separate language, simply `HTML`: https://github.com/Glavin001/atom-beautify/blob/3913267804995c33d595df9d8ba54b21837f443d/src/languages/html.coffee#L17

The HTML language is handled by both:
- Pretty Diff: https://github.com/Glavin001/atom-beautify/blob/3913267804995c33d595df9d8ba54b21837f443d/src/beautifiers/prettydiff.coffee#L21
- JS Beautify: https://github.com/Glavin001/atom-beautify/blob/3913267804995c33d595df9d8ba54b21837f443d/src/beautifiers/js-beautify.coffee#L8
with `JS Beautify` being the default.

Thus switching from `HTML` to `HTML (Angular)` grammar actually changes beautifiers from JS Beautify to Pretty Diff. /cc @prettydiff

If it is behaving badly, please provide examples such that @prettydiff can help. You can create issues for Pretty Diff over at https://github.com/prettydiff/prettydiff

**Comment by guymguym** [comment]
Thanks!
Then maybe the reason I see such a big difference in their output is that my project uses a `.jsbeautifyrc` config file but doesn't have a similar config file for prettydiff? I couldn't see a description for such a file for prettydiff. Do you know of such a way to set a project config file?

**Comment by Glavin001** [comment]
The settings for `EJS` should fallback on `js` and `html`, such that your `html` config in your `.jsbeautifyrc` file should apply: https://github.com/Glavin001/atom-beautify/blob/3913267804995c33d595df9d8ba54b21837f443d/src/languages/ejs.coffee#L6

Currently the `.jsbeautifyrc` file works for retrieving the options, regardless of beautifier. It was originally for js-beautify, however now at Atom Beautify supports many more, it still works. This may be renamed in the future.

If you could provide some concrete examples of the differences and what exactly is wrong with Pretty Diff's beautification, then we could look into it. If the file is pure HTML, then I recommend using `HTML` as the grammar and having Atom Beautify use the HTML Beautify in JS Beautify.

**Comment by guymguym** [comment]
the most notable difference is preserve empty lines that seems like prettydiff ignores completely

try this with prettydiff.com with `EJS` type:

```
<div>
    <p>
        lalala
    </p>
    
    
    
    
    
    <p>
        lululu
    </p>
</div>
```

**Comment by guymguym** [comment]
another issue is that it messes with line breaks.

first case - removes line break in empty tag:
```
<div bla="hhhh">
</div>
```

second case - add line break in long attribute list - seems like it has a default wrap marker at 80 chars:
```
<div key1="value" key2="value" key3="value" key4="value" key5="value" key6="value" key7="value" key8="value" key9="value" key10="value" key11="value" key12="value" key13="value">
</div>
```

**Comment by Glavin001** [comment]
Definitely forward these issues over to @prettydiff at https://github.com/prettydiff/prettydiff

**Comment by elebetsamer** [comment]
Is there any way to get beautify to not classify HTML (Angular) as EJS? I'm having a formatting problem too with HTML (Angular) files. I'd rather the files just be treated as HTML files, without having to manually set each file as HTML. Is this possible in any way?

**Comment by prettydiff** [comment]
The two issues:

1.  Empty lines
    * I am rewriting my markup parser. The new parser will preserve most empty lines.
    * I do not plan to preserve empty lines in some cases where it isn't helpful. The example above is one of those cases. Code is much easier to read and understand when a closing tag immediately follows its opening tag if there are not child nodes.
2. You can fix the wrapping right now. Pretty Diff has a [wrap property](http://prettydiff.com/documentation.xhtml#wrap) that when set to 0 removes wrapping as you desire. This option was added due to multiple requests. Read the atom-beautify documentation to see how the wrap property is implemented.

**Comment by elebetsamer** [comment]
@prettydiff @Glavin001 I'm already using "wrap_line_length": 0 in my config. Is the key name different for prettydiff?

**Comment by Glavin001** [comment]
Does not look like the wrap property is supported, yet, in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L9-L16

Documentation for all of the supported options can be found here: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md

There are a number of Pretty Diff options that are not yet supported in Atom Beautify: https://github.com/Glavin001/atom-beautify/issues/297

I'll hopefully get some time to complete that soon.

**Comment by Glavin001** [comment]
I have added support for `wrap_line_length` to `Pretty Diff` beautifier. See all available options for Pretty Diff in docs: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff

**Comment by elebetsamer** [comment]
Awesome. Thanks for adding support for wrap_line_length with Pretty Diff @Glavin001

**Comment by Glavin001** [comment]
You're very welcome.

Can this issue be closed, too? What else is left todo?

**Comment by Glavin001** [comment]
Let me know there is any options for Atom Beautify to add to support this.

For the future: You can trick Atom into updating Atom Beautify's dependencies, such as Pretty Diff, by uninstalling Atom Beautify and reinstalling it. Atom will install the latest version of Atom Beautify's dependencies, and you will have the most up-to-date version of Pretty Diff and be able to test these changes @prettydiff is working on.
