### ISSUE TITLE
Support for grammar "Gherkin" and extension "feature"

### ISSUE THREAD

**Issue by betogomez** [Glavin001/atom-beautify#377]

**Comment by Glavin001** [comment]
This language? https://github.com/cucumber/cucumber/wiki/Gherkin
Could you provide a sample input and output?

**Comment by betogomez** [comment]
Yes it is :)
 https://github.com/cucumber/cucumber/wiki/Gherkin

**Comment by Spy-Seth** [comment]
What do you mean by "a sample input and output"? An example of un-formatted file and his fixed version?

**Comment by Glavin001** [comment]
Yep. 




If the sample is similar to existing languages then we could support it easier. If it's different then we have an example to compare to our existing examples. 



—

**Comment by Spy-Seth** [comment]
Here it is: https://gist.github.com/Spy-Seth/3206c3015db5eb22fd54

**Comment by betogomez** [comment]
Great! looks good!

**Comment by Glavin001** [comment]
Published to v0.28.9

**Comment by Spy-Seth** [comment]
Excellent news! :dancers:
