### ISSUE TITLE
Beautifier for HTML vs HTML (Angular)

### ISSUE THREAD

**Issue by filipesilva** [Glavin001/atom-beautify#379]
Hi,

I've noted that on files whose syntax is listed as HTML the beautifier used is jsbeautify, but on files with the HTML (Angular) syntax Pretty Diff is used. 

I couldn't find a place to configure this in the settings screen of atom-beautify I did not find a configuration to choose which beautifier to use. Is there somewhere where I can do this?

**Comment by Glavin001** [comment]
> I've noted that on files whose syntax is listed as HTML the beautifier used is jsbeautify, but on files with the HTML (Angular) syntax Pretty Diff is used.

If you are writing pure `HTML` and not `HTML (Angular)` then that is fine, however if you are writing `HTML (Angular)` then I recommend changing your grammar to reflect that. I did notice a change recently for language packages detecting the grammars properly. If it detects your `HTML (Angular)` code as `HTML` then you should report it to their package as a bug.

> I couldn't find a place to configure this in the settings screen of atom-beautify I did not find a configuration to choose which beautifier to use. Is there somewhere where I can do this?

You can configure which beautifier is used for each language in the Atom Beautify package settings. Look for `Language Config - <your language, such as HTML> - Default Beautifier` and all possible beautifiers are listed.

**Comment by filipesilva** [comment]
It is detecting `HTML (Angular)` correctly, but even though `Language Config - HTML - Default Beautifier` is set to `JS Beautifier`, it seems like my files with `HTML (Angular)` are being ran through `Pretty Diff`.

Let me try to get an example up.

**Comment by filipesilva** [comment]
Concrete example of `HTML` and `HTML (Angular)` beautification yielding different results:

- in atom-beautifier settings, set `HTML - Wrap Attributes` to `force`
- open a new file
- paste the following code
```
<span ng-show="variable" ng-disabled="something">
  {{binding}}
</span>
```
- save as html, check that the syntax is `HTML (Angular)`
- beautify, result is the following
```
<span ng-disabled="something" ng-show="variable">
  {{binding}}
</span>
```
- undo beautify
- change syntax to `HTML`
- beautify, result is the following
```
<span ng-show="variable"
    ng-disabled="something">
  {{binding}}
</span>
```

I say it's being ran through Pretty Diff simply because that's the other option for HTML, but I suppose it might be using some other beautifier.

**Comment by Glavin001** [comment]
> It is detecting HTML (Angular) correctly, but even though Language Config - HTML - Default Beautifier is set to JS Beautifier, it seems like my files with HTML (Angular) are being ran through Pretty Diff.

*I should have mentioned.* Actually the language for `HTML (Angular)` internally in Atom Beautify is `EJS` (Embedded JavaScript). See https://github.com/Glavin001/atom-beautify/blob/master/src/languages/ejs.coffee#L13

EJS is handled by Pretty Diff because js-beautify does not handle those other extended languages on top of HTML. Pretty Diff has much wider support, and both are actively developed. /cc @prettydiff

> Concrete example of HTML and HTML (Angular) beautification yielding different results:

They likely will. Two different beautifiers that have different support. js-beautify I do not believe supports this syntax, while Pretty Diff does.

I'd recommend sticking with `HTML (Angular)` which is `EJS` language in Atom Beautify and uses Pretty Diff by default. Any problems you have please forward them to @prettydiff at https://github.com/prettydiff/prettydiff

**Comment by filipesilva** [comment]
Ah, I did not know that `EJS` bit! Now it makes much more sense. Cheers!

**Comment by Glavin001** [comment]
I hope to heavily document this soon. Still working on it. 

As a tip, you can use GitHub's search for your grammars, such as `HTML (Angular)`, and it should show you which language file handles it. For instance: https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=html+%28angular%29

I will be developing a way to generate a lot of documentation from the internal code and it should provide a clear guideline for all of the possible options, which languages support them, and which beautifiers support which languages.

Let me know if you need anything else.

**Comment by filipesilva** [comment]
Nice tip! That was the bit of info that I was missing really. Thanks for the swift reply, you're always very helpful :D
