### ISSUE TITLE
Avoid beautification of {{ "something" }}

### ISSUE THREAD

**Issue by RickCogley** [Glavin001/atom-beautify#380]
hello - thank you for atom-beautify. I am using the static site generator Hugo, which uses template code like: 

~~~
{{ "<!-- ENTERING layouts/_default/single.html -->" | safeHTML }} {{ partial "header.html" . }}
~~~

When I beautify my single.html file, this happens: 

~~~
{{ "
<!-- ENTERING layouts/_default/single.html -->" | safeHTML }} {{ partial "header.html" . }}
~~~

Atom-beautify inserts a newline after the first ".

Is there a way to tell it not to do this? I am not sure what language it thinks those {{ }} sections are.

Thank you in advance for your advise. 

Sincerely,
Rick

**Comment by Glavin001** [comment]
This looks like Handlebars, which is supported, not HTML. I'd recommend changing your Atom Text Editor's grammar to Handlebars. You may need to install https://atom.io/packages/atom-handlebars first.

**Comment by RickCogley** [comment]
@Glavin001 thanks very much. I'll try that!
