### ISSUE TITLE
support tex file

### ISSUE THREAD

**Issue by X-G** [Glavin001/atom-beautify#384]
Is there a plan to support tex file?

**Comment by Glavin001** [comment]
No plans, yet.

If you know of any third-party beautifiers that support tex / LaTeX, please let me know.

I've found a discussion ( http://tex.stackexchange.com/questions/26102/latex-code-sniffer-and-or-beautifier ) recommending:
- https://github.com/cmhughes/latexindent.pl
- http://bfc.sfsu.edu/cgi-bin/hsu.pl?LaTeX_Tidy

**Comment by X-G** [comment]
Yes, I also found that discussion.
I'm trying to use latexindent.pl, but not work it out yet.
I don't know much about coding, I will let you know if I have more information regarding this.
Thanks for you work on the package!

**Comment by X-G** [comment]
It seems that `latexindent.pl` has already built in `texlive`.
see this: [documentation](http://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/support/latexindent/documentation/manual.pdf) 
I'm using texlive, so I just run `latexindent -w test.tex`. It works.

**Comment by Glavin001** [comment]
See https://github.com/Glavin001/atom-beautify/issues/300#issuecomment-107590998 for how to add a new language and/or beautifier.

**Comment by Glavin001** [comment]
Published to v0.28.28
