### ISSUE TITLE
Not working with Java

### ISSUE THREAD

**Issue by Stevo5o** [Glavin001/atom-beautify#385]
atom-beautify will not beautify my Java file (below) in atom.
I get this error in atom.
spawn uncrustify ENOENT
Hide Stack Trace
Error: spawn uncrustify ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

Java file
public class ConditionalStatements {

  public static void main(String[] args) {

    String olive = "Kalamata";

    switch (olive.toLowerCase()) {
      case "kalamata":
        System.out.println("It's Greek");
        break;
      case "picholine":
        System.out.println("It's French");
        break;
      case "ligurio":
        System.out.println("It's Italian");
        break;

    default:
        System.out.println("I do not know, location");
        break;
    }
  }
}

atom running on 64 bit Microsoft Windows 8.1 Pro 
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
pip 7.0.3 from C:\tools\python2\lib\site-packages (python 2.7)

**Comment by Glavin001** [comment]
The language support is shown in the README: https://github.com/Glavin001/atom-beautify#language-support
For Java:
>  - Java
>    - Requires Uncrustify

Please confirm you have [Uncrustify](http://sourceforge.net/projects/uncrustify/) installed correctly first.

Then if you are still having problems please let me know and run Atom's command `Atom Beautify - Help Debug Editor`.

**Comment by Glavin001** [comment]
Let me know and this issue can be reopened if you are still having problems.
