### ISSUE TITLE
Bookmarks occasionally lost after beautification. Any way to persist?

### ISSUE THREAD

**Issue by pixelchutes** [Glavin001/atom-beautify#387]
This may be a long shot *(and probably an edge case)*, but is there a way to preserve bookmarks after running `atom-beautify:beautify-editor`? Under certain scenarios, active bookmarks can be lost after beautification.

For example, if you've bookmarked the beginning of a method definition in PHP with the opening brace on the same line, upon beautification and underlying PSR-2 fixers being applied, the brace is correctly relocated to a new line beneath the method name, but the previous bookmark on the signature itself is no longer present.

### BEFORE
![bookmark_line_5](https://cloud.githubusercontent.com/assets/352182/7991675/36f00350-0ab7-11e5-9c13-9cff0e3337a8.png)

### AFTER
![bookmark_lost_line5](https://cloud.githubusercontent.com/assets/352182/7991733/a265f022-0ab7-11e5-9f42-21982ecf8d12.png)

I realize this is a tough problem to solve reliably *(not to mention across the board)*, but am wondering if  perhaps class / method definition bookmarks could somehow be tracked / preserved?

**Comment by Glavin001** [comment]
Unfortunately, it's unlikely I will be able to solve this. Once Atom Beautify has processed the beautification it simply replaces the entire TextEditor. Ideally, if Atom's core would somehow diff the old and new text and know how to place the bookmarks in their new positions. I'd recommend maybe forwarding this issue / feature request over to [Atom's repository](https://github.com/atom/atom) and seeing if they have any ideas. It would be great if Atom supported handling these bookmarks even after changes made to text by packages.
