### ISSUE TITLE
auto-update always appears to hang

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#391]
I was just prompted to update several packages, including beautify 0.2.8

After all the others finished (after only about 10 seconds) the indeterminate progress bar for beautify kept going.  Eventually, I quit Atom and on relaunch I see that 0.2.8 has indeed installed.

This has happened for the past few AB updates. No other packages do this.  Atom .207

**Comment by Glavin001** [comment]
> beautify 0.2.8

Just to confirm, you mean v0.28.0?

> After all the others finished (after only about 10 seconds) the indeterminate progress bar for beautify kept going. Eventually, I quit Atom and on relaunch I see that 0.2.8 has indeed installed.

Atom Beautify has quite a lot of dependencies, so it may have needed the extra time to install. How long did you let it run? Was it truly hanging or simply taking it's required time to download all of it's dependencies?

> This has happened for the past few AB updates. No other packages do this. Atom .207

More than likely just more beautifiers and more dependencies required in Atom Beautify.

If it *does not* install, then this is an issue. However, this sounds just like it needs more time. If it does hang, then this is an `apm` issue: https://github.com/atom/apm/issues

**Comment by smlombardi** [comment]
OK, today I just let it go for 5 minutes until it finished, and I got this error
````

npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/ariya/esprima.git) xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone https://github.com/ariya/esprima.git xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/stevel/.atom/.apm/.apmrc" "--userconfig" "/Users/stevel/.atom/.apmrc" "install" "/private/var/folders/10/wbtwnvx88xlfj_006s6f3kq80000gn/T/d-115510-1379-16j1xhn/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 1

npm ERR! Command failed: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/10/wbtwnvx88xlfj_006s6f3kq80000gn/T/apm-install-dir-115510-1379-1vzqae4/npm-debug.log
````
And it failed to update.

**Comment by Glavin001** [comment]
> invalid active developer path 

Looks like your computer is not setup yet / properly for `apm` to do whatever it needs to do.
I'd recommend forwarding this over to https://github.com/atom/apm/issues or https://discuss.atom.io/ for some help with that.

---

From an Atom Beautify perspective: I think https://github.com/Glavin001/atom-beautify/issues/320 will resolve this issue above (taking too long to install), as it will make all of the beautifier dependencies loaded upon usage. This means that it will install quickly and then when you first use it, then it will download and install third-party packages that are required.

**Comment by smlombardi** [comment]
Yes, I recently updated this one to 10.11b1.  I had to install the latest command line tools.

But now I see

![screen shot 2015-06-10 at 7 09 19 pm](https://cloud.githubusercontent.com/assets/835148/8096346/38a523aa-0fa4-11e5-9f95-e3643593ddc0.png)

I'll try it on my other 10.10.4 mac.

**Comment by smlombardi** [comment]
Note that other pckages updated fine

**Comment by Glavin001** [comment]
I have no clue where to start with the error `undefined`. I'd recommend talking with the Atom/apm team at https://github.com/atom/apm/issues and if there is more information to provide maybe I can help then.

**Comment by smlombardi** [comment]
On my 10.10.4 rMBP, "updating" is still going after 1/2 hour.  Like in original bug, I am able to quickly update all other packages and Atom.  I'll check with them.

**Comment by Glavin001** [comment]
> On my 10.10.4 rMBP, "updating" is still going after 1/2 hour. 

A half hour is quite some time. Something is definitely wrong with your setup or Internet connection. Takes a matter of seconds over my wifi to download both production and development dependencies for this package.

Furthermore, I have both Travis CI (Mac) and AppVeyor (Windows) setup and running well and confirming my assumption that everything is downloading and installing properly:
- https://travis-ci.org/Glavin001/atom-beautify
- https://ci.appveyor.com/project/Glavin001/atom-beautify

It takes about 6 minutes to download and install Atom, multiple languages and many third-party beautifiers (see https://github.com/Glavin001/atom-beautify#language-support and note that most beautifiers are written in other languages and not Node.js), Atom Beautify and it's package dependencies, and then completely run all of the tests. See https://github.com/Glavin001/atom-beautify/blob/master/.travis.yml#L31-L54 for Travis CI and what it installs along with the Atom Beautify package itself. All freshly completed in 6 minutes.

> Like in original bug, I am able to quickly update all other packages and Atom.

Yup. I definitely want to speed things up (See https://github.com/Glavin001/atom-beautify/issues/391#issuecomment-110933831 ) however it should not (does not, see Travis CI and AppVeyor) take that long to install. 

I hope the Atom team can help you with this!

**Comment by smlombardi** [comment]
ok.   i have, for now, deleted the package and re-installed via APM which has worked.  Let's see how the next update goes.  Thanks.
