### ISSUE TITLE
problem with https on Windows 8.1

### ISSUE THREAD

**Issue by silverspectro** [Glavin001/atom-beautify#395]
npm ERR! git fetch -a origin (https://github.com/ariya/esprima.git) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\Ciro\\AppData\\Local\\atom\\app-0.208.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\Ciro\\AppData\\Local\\atom\\app-0.208.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Ciro\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Ciro\\.atom\\.apmrc" "install" "C:\\Users\\Ciro\\AppData\\Local\\Temp\\d-115511-956-osveze\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by Glavin001** [comment]
I'd recommend looking at these other issues: https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=https+git+fetch&type=Issues

Here is a fix that was found: http://stackoverflow.com/a/28296265/2578205

**Comment by silverspectro** [comment]
works like a charme !
thanks


2015-06-11 17:57 GMT+02:00 Glavin Wiechert <notifications@github.com>:

> I'd recommend looking at these other issues:
> https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=https+git+fetch&type=Issues
>
> Here is a fix that was found: http://stackoverflow.com/a/28296265/2578205
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Glavin001/atom-beautify/issues/395#issuecomment-111183106>
> .
>



-- 
[image: www.cirodecaro.net] <http://www.cirodecaro.net>
