### ISSUE TITLE
html in a php file indentation question

### ISSUE THREAD

**Issue by bronze** [Glavin001/atom-beautify#402]
Hi there Glavin.
I have some .php files that are not strictly speaking in php. something a bit like this:

    <section class="aboutus" id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="heading">
                        <h2><?php echo html($data->title()) ?></h2>
                        <h3><?php echo html($data->subtitle()) ?></h3>
                    </div>
                </div>
            </div>
        </div>
    </section>

however, it doesnt like to beautify as php, so i go to html to beautify it.
am i missing some preference/configuration that would work on these html/php hybrid files?

again, thanks for your time!

**Comment by Glavin001** [comment]
There's not much I can help with the information provided, that is doesn't like to beautify as PHP, however what I can tell him this is that it's likely an issue with PHP-CS-Fixer. PHP-CS-Fixer is the default beautifier for PHP. I would recommend forwarding this issue over to them at https://github.com/FriendsOfPHP/PHP-CS-Fixer

If there are additional options that need to be added to Atom Beautify for PHP-CS-Fixer then let me know.
