### ISSUE TITLE
Auto formatting on save does not work

### ISSUE THREAD

**Issue by WebFreak001** [Glavin001/atom-beautify#406]
I added a .jsbeautifyrc file to the root of my project and tried
```
{
  "language_d_beautify_on_save": true
}
```
like [options.md](https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---d---beautify-on-save) told me and also
```
{
  "d":
  {
    "beautify_on_save": true
  }
}
```
but none of these worked. I also tried it with css and it didn't work either. Formatting manually with ctrl+alt+b works although.

I also tried adding a .jsbeautifyrc to the ~/.atom/ folder and editing the ~/.atom/packages/atom-beautify/src/.jsbeautifyrc file but these didn't work either. (Im using Windows if that matters)

**Comment by Glavin001** [comment]
Have you tried configuring it in the Atom Beautify package settings panel, instead of in the `.jsbeautifyrc`?

**Comment by WebFreak001** [comment]
Um I cant find any settings there except these:

![](http://i.webfreak.org/5D57CF)

And checking Beautify On Save does nothing on save and only give me the error that it is deprecated when manually formatting

**Comment by Glavin001** [comment]
That's not right. What version of Atom are you? Could you run command `Atom Beautify - Help Debug Editor`?

**Comment by WebFreak001** [comment]
Oh wait reinstalling it helped. But I had that issue multiple times, that it does not show me all options

**Comment by WebFreak001** [comment]
Yeah got it to bug again. Its by disabling the package, then hitting the enable button 2 times because it does not do anything. Then reloading the window, then hitting the enable button 1 time and then reloading again. Then it somehow shows invalid config

**Comment by Glavin001** [comment]
Make sure Atom and Atom Beautify are both up-to-date. These issues should like problems with Atom and [Atom Settings View](https://github.com/atom/settings-view), let them know if you have any problems.

**Comment by WebFreak001** [comment]
Oh yeah it was probably because I still had v0.189.0. Seems like they removed auto update check for atom itself

**Comment by Glavin001** [comment]
Let me know if there's anything else.

**Comment by WebFreak001** [comment]
Yeah seems like config does not bug out anymore, thanks
