### ISSUE TITLE
Markdown: line removed between preceeding text and list

### ISSUE THREAD

**Issue by cconover** [Glavin001/atom-beautify#408]
When creating a list in a markdown file, the beautifier removes the blank line between the end of the preceeding text and the beginning of the list. So what starts out like this:

``` markdown
Here is some sample text.

- List item
- List item

Here is some more text.
```

Ends up like this:

``` markdown
Here is some sample text.
- List item
- List item

Here is some more text.
```

While GitHub's markdown parser seems to be able to handle this, many others cannot and so lists end up being broken.

**Comment by Glavin001** [comment]
Markdown is handled by https://github.com/slang800/tidy-markdown I would recommend that you forward this issue over to there and they'd be able to explain more.

**Comment by cconover** [comment]
I tried adding the two spaces, but the other parsers I tried still rejected that. 

I'll open this issue with Tidy Markdown, thanks!
