### ISSUE TITLE
<body> tag transforms into <body/>

### ISSUE THREAD

**Issue by fullhdpixel** [Glavin001/atom-beautify#420]
The following markup

```html
<body> </body>
```

gets changed to 
```html
<body/>
```

I think this should be changed, because right now the only solution is to do this:
```html
<body>
<!-- -->
</body>
```

**Comment by Glavin001** [comment]
This could either be `JS Beautify` or `Pretty Diff` beautifier.

From the information you have provided, I have no idea if this is plain HTML -- which is handled by JS Beautify by default -- or something more -- like EJS, ERB, etc -- which is likely handled by Pretty Diff.

Regardless, this is a third-party bug. I would recommend that you figure out which beautifier is causing this problem, by running `Atom Beautify - Help Debug Editor` and looking in the results for `Original File Language` and then check for `Language Config - <language> - Default Beautifier`, such as https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---html---default-beautifier

Once you know which beautifier is causing it then let their developer team know:

- JS Beautify - http://jsbeautifier.org/ - https://github.com/beautify-web/js-beautify
- Pretty Diff - http://prettydiff.com/ - https://github.com/prettydiff/prettydiff
