### ISSUE TITLE
JavaScript: preserve objects

### ISSUE THREAD

**Issue by ttsirkia** [Glavin001/atom-beautify#422]
It would be a very handful option to preserve the original formatting of objects.

Examples:
```javascript
var a = {a: 2, b: 3};

view.on('post', {action: 'removeTask'}, function(next) {

```

These would not be splitted to multiple lines. There are many cases where I'd like to prefer this kind of formatting, especially when passing tiny objects as function parameters etc.

**Comment by Glavin001** [comment]
The default beautifier for `JavaScript` is `JS Beautify`. See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---javascript---default-beautifier

So I would recommend that you forward this question over to the team at https://github.com/beautify-web/js-beautify 

Please include a link reference back to this issue such that other users who may have the same question can follow the reference to your new issue over at js-beautify. Thanks!

**Comment by ttsirkia** [comment]
Ah, OK. I didn't realize that this is just a wrapper for separate modules. I'll put this issue to that repository, thanks for the tip!

**Comment by ttsirkia** [comment]
It seems that this kind of feature has already been requested a long time ago: https://github.com/beautify-web/js-beautify/issues/315

**Comment by nmccready** [comment]
Does this option still exist? https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---javascript---default-beautifier I do not see where I can change the beautifier type.

![screen shot 2016-01-27 at 12 42 57 pm](https://cloud.githubusercontent.com/assets/583593/12622517/c3dd14b4-c4f3-11e5-9b50-3d4f1522d306.png)

![screen shot 2016-01-27 at 12 43 11 pm](https://cloud.githubusercontent.com/assets/583593/12622523/c6ffa328-c4f3-11e5-8cae-b5595a4cee30.png)

**Comment by ttsirkia** [comment]
This option is now appearing to js-beautify: https://github.com/beautify-web/js-beautify/commit/55f111eecd03f41316c5092c55b4043137d2e6e2
