### ISSUE TITLE
A problem with the spawn-sync package

### ISSUE THREAD

**Issue by 12789** [Glavin001/atom-beautify#423]
I installed  the Atom1.0.
When I install the package I got these log.

> spawn-sync@1.0.11 postinstall /private/var/folders/g7/ftzxkbjj5cddy62dvb_6gsbr0000gn/T/apm-install-dir-115526-69847-12g92bv/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm ERR! Darwin 14.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Zhang/.atom/.apm/.apmrc" "--userconfig" "/Users/Zhang/.atom/.apmrc" "install" "/private/var/folders/g7/ftzxkbjj5cddy62dvb_6gsbr0000gn/T/d-115526-69847-eymswa/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.11 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.11 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/g7/ftzxkbjj5cddy62dvb_6gsbr0000gn/T/apm-install-dir-115526-69847-12g92bv/npm-debug.log

**Comment by Glavin001** [comment]
I am not sure what is going on. I recommend that you forward this over to https://github.com/ForbesLindesay/spawn-sync and hopefully someone can help there.

**Comment by Glavin001** [comment]
See https://github.com/ForbesLindesay/spawn-sync/issues/11

**Comment by ForbesLindesay** [comment]
The latest version of spawn-sync should be much more resilient (even on older versions of node.js).  If anyone was struggling with this issue I'd encourage them to have another go.
