### ISSUE TITLE
weird <script> action on saving

### ISSUE THREAD

**Issue by bronze** [Glavin001/atom-beautify#425]
Hi there
I've stumbled upon a really weird error. When i put `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>` upon saving-and-beautifying it transforms to `<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"/>` and the next save clears everything below that line...

Trying to find a rhyme or reason to it, made a few tests.
If the `<script></script>` are on different lines, it returns:
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
Error: no source code supplied to jspretty!
</script>
```

I've disabled all packages and the error stopped. Enabled only atom-beautify and it came back.
Tried with a .php and .html (maybe another extension would throw something else at me) but no luck.
Unclicked everything under the javascript part on atom-beautify preferences, also no deal.
Got no Snippets or Init Scripts.

If anyone wants to test, heres the original code (the `</head>` and everything under is deleted after second save):
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta content="width=device-width,initial-scale=1.0" name="viewport">
        <title><?php echo $site->title()->html() ?>
            |
            <?php echo $page->title()->html() ?></title>
        <meta content="<?php echo $site->description()->html() ?>" name="description">
        <meta content="<?php echo $site->keywords()->html() ?>" name="keywords">
        <?php echo css('assets/css/main.css') ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
    <header class="header cf" role="banner">
        <a class="logo" href="<?php echo url() ?>">
            <img alt="<?php echo $site->title()->html() ?>" src="<?php echo url('assets/images/logo.svg') ?>"/>
        </a>
        <?php snippet('menu') ?>
    </header>
```

Video of the weird on-save http://cl.ly/bneX

cheers!

**Comment by jmenges** [comment]
I was able to reproduce your problem when using pretty-diff as the html beautifier. Switching to js-beautify works for now. Strangely if i execute prettydiff directly with the parameters supplied by the debug output the file gets beautified correctly, which points to some internal problem.

**Comment by bronze** [comment]
nice catch, switched away from Pretty Diff and it really stopped thx!

**Comment by prettydiff** [comment]
I fixed it this morning.  Please try again with v1.12.9.

**Comment by prettydiff** [comment]
More clarity on this issue.  I was recently asked to put forward an enhancement that transforms a start tag followed by an end tag of the same name into a single self-closing tag.  Before I was making an exception for `span` and `div` tag names and now I am making an exception for `span`, `div`, and `script` tag names. These exceptions are only necessary for compatibility with older versions of IE and HTML. This enhancement is always preferred for any sort of XML.

**Comment by Glavin001** [comment]
> I fixed it this morning. Please try again with v1.12.9 v.12.10. I am publishing a new update with a better solution.

**Important:** You can force / trick Atom Beautify to updating its dependencies by uninstalling and reinstalling Atom Beautify package. This will cause `apm`, Atom's package manager tool, to install the dependencies, including Pretty Diff, again in a fresh installation. The version of the dependencies for Atom Beautify are weak and allow for v1.12.10 to be installed instead of the older version.

Since this problem is resolved. I am going to close this issue. Thanks!
