### ISSUE TITLE
Self-closing tags doesn't play well with AngularJS directives

### ISSUE THREAD

**Issue by lifeofbrian** [Glavin001/atom-beautify#434]
I'm noticing that atom-beautify does not play well with self-closing directives. 

Is there a configuration I need to set to disable beautification of open and closed tags without child elements into self-closing tags? Thanks!

**Comment by Glavin001** [comment]
AngularJS language is handled by Pretty Diff (see #179).

Could you provide examples that we could debug? Preferably just run Atom command `Atom Beautify - Help Debug Editor`. 

/cc @prettydiff

**Comment by prettydiff** [comment]
I just shoveled this functionality under an option that is false by default in updated v1.12.11.  The new option is tagmerge - http://prettydiff.com/documentation.xhtml#tagmerge

If you notice any further problems please let me know.

**Comment by Glavin001** [comment]
Great, thanks @prettydiff ! Now it's my turn:
- [ ] add `tagmerge` option for Pretty Diff beautifier

**Comment by lifeofbrian** [comment]
Awesome -- thank you both for your efforts here!

**Comment by Glavin001** [comment]
I'll try to add this and publish today.
