### ISSUE TITLE
Beautify'ing XML files will change order of elements

### ISSUE THREAD

**Issue by octaviovelasco** [Glavin001/atom-beautify#438]
While trying to beautify a XML file, I noticed that sequence of elements inside a tag was altered. This shouldn't happen

**Comment by prettydiff** [comment]
@octaviovelasco Could you provide a code sample that indicates the problem? Once I can reproduce the problem I can offer a resolution.

**Comment by prettydiff** [comment]
Please reopen this issue with a code sample so that we can investigate this problem.
