### ISSUE TITLE
JS Beautify does not handle `space_before_conditional` for Javascript

### ISSUE THREAD

**Issue by KINFOO** [Glavin001/atom-beautify#439]
Hi,

I am using atom __v0.210__ with atom-beautify __v0.28.7__.

Given this file:

```js
$ cat /tmp/functionSample.js
var functionSample=function(){
return;
};
```

With this configuration:

```json
$ cat ~/.jsbeautifyrc 
{
  "end_with_newline": true,
  "indent_size": 4,
  "indent_char": " ",
  "indent_level": 0,
  "space_after_anon_function": false
}
```

Formatting with `js-beautify`, I get:

```js
$ js-beautify /tmp/functionSample.js 
var functionSample = function() {
    return;
};
```

Formatting in atom, I get:

```js
var functionSample = function () {
    return;
};
```

__Problem__: There is an extra space after `function`.

```diff
1c1
< var functionSample = function () {
---
> var functionSample = function() {
```

I think this extra space is a bug, because `space_before_conditional` option does not impact formating.
Am I right?

Thanks for the good work.
Kevin

**Comment by Glavin001** [comment]
The options for `JavaScript` are all passed through for `JS Beautify`. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/js-beautify.coffee#L13 
Therefore, `JS Beautify` should receive exactly your options you set:

```json
{
  "end_with_newline": true,
  "indent_size": 4,
  "indent_char": " ",
  "indent_level": 0,
  "space_after_anon_function": false
}
```

You should confirm this by running Atom command `Atom Beautify - Help Debug Editor` and looking under [`Final Options`](https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L368-L369).

I recommend that you forward this issue over to the `JS Beautify` team at https://github.com/beautify-web/js-beautify

If they release an update, you can trigger Atom to update Atom Beautify's dependencies, such as JS Beautify, by uninstalling and reinstalling Atom Beautify. This will reinstall a fresh and latest copy of dependencies.

**Comment by Glavin001** [comment]
@KINFOO I re-read your issue. I think the next step is definitely to run `Atom Beautify - Help Debug Editor` and let me know the results. I will specifically be looking for the `Final Options`, however please paste in the rest as well.

--

**Update**:

I see that for JavaScript the `space_before_conditional` is `true` by default. This is definitely what is causing your issue. See https://github.com/Glavin001/atom-beautify/blob/f1a6892ac8e0b0dddbb3c97b28a16d771fe882e9/src/languages/javascript.coffee#L90

Please forcefully set `space_before_conditional` to `false` and this should resolve your issue! Let me know.

**Comment by KINFOO** [comment]
@Glavin001 **Final Options**: 
Final combined options that are used
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false,
    "jslint_happy": true,
    "end_with_newline": true,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "space_in_paren": false,
    "space_after_anon_function": false,
    "brace_style": "collapse",
    "break_chained_methods": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

**Comment by Glavin001** [comment]
>     "space_before_conditional": true,

Yup, so you can see `space_before_conditional` is `true`. As [mentioned in my comment above](https://github.com/Glavin001/atom-beautify/issues/439#issuecomment-117806425), this is because the default value of `space_before_conditional` is `true`. 

Solution is to add `space_before_conditional:false` to your `.jsbeautifyrc` file.

**Comment by KINFOO** [comment]
@Glavin001 I went in _package preferences_, current configurations is:
**Final Options**: 
Final combined options that are used
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false,
    "jslint_happy": true,
    "end_with_newline": true,
    "space_before_conditional": false,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "space_in_paren": false,
    "space_after_anon_function": false,
    "brace_style": "collapse",
    "break_chained_methods": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```
When I save the following with atom
```js
var functionSample=function(){
return;
};
```
I still get the _extra space_:
```js
var functionSample = function () {
    return;
};
```
Running `js-beautify`, I still get:
```js
$ js-beautify /tmp/functionSample.js 
var functionSample = function() {
    return;
};
```
Both `js-beautify` and `atom-beautify` are using `~/.jsbeautifyrc`:
```js
$ cat .jsbeautifyrc 
{
  "end_with_newline": true,
  "indent_size": 4,
  "indent_char": " ",
  "indent_level": 0,
  "space_after_anon_function": false,
  "space_before_conditional": false
}

```
It definitely looks like a bug…

**Comment by Glavin001** [comment]
Could you try with the `.jsbeautifyrc` being:

```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false,
    "jslint_happy": true,
    "end_with_newline": true,
    "space_before_conditional": false,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "space_in_paren": false,
    "space_after_anon_function": false,
    "brace_style": "collapse",
    "break_chained_methods": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

**Comment by Glavin001** [comment]
Also, trigger Atom Beautify to update its dependencies, such as `jsbeautify`, by uninstalling Atom Beautify and reinstalling it in Atom. This will install a fresh and latest copy of jsbeautify. Do that first, to make sure that your version your are running from command line is up-to-date and also Atom Beautify's version is up-to-date.

**Comment by KINFOO** [comment]
@Glavin001 If I get it right, this procedure aims to have them using same default.

If it is a default configuration problem, I do not want to align them this way. I want to have a configuration file that _rules them all_.

Here it is:

```js
{
  "end_with_newline": true,
  "indent_char": " ",
  "indent_size": 4,
  "jslint_happy": false
  "space_after_anon_function": false,
  "space_before_conditional": true,
}
```

Thanks again for your help.

Kevin

**Comment by Glavin001** [comment]
Was making `jslint_happy: false` the key to making it work correctly?

The js-beautify [`defaults.json`](https://github.com/beautify-web/js-beautify/blob/master/js/config/defaults.json) shows that [`jslint_happy` is default to `false`](https://github.com/beautify-web/js-beautify/blob/master/js/config/defaults.json#L8) and [`space_after_anon_function` defaults to `false`](https://github.com/beautify-web/js-beautify/blob/master/js/config/defaults.json#L9) and [`space_before_conditional` defaults to `true`](https://github.com/beautify-web/js-beautify/blob/master/js/config/defaults.json#L13). These are the same in Atom Beautify's defaults for [`jslint_happy`](https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L63-L65), [`space_after_anon_function`](https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L67-L69), and [`space_before_conditional`](https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L88-L90).

Thus there must be another file or option set for `jslint_happy` somewhere that [forced it to be `true` in your `Final Options`](https://github.com/Glavin001/atom-beautify/issues/439#issuecomment-117988384).

Glad you have figured it out and created a file that works for you.

**Comment by Glavin001** [comment]
I was also just experiencing this problem. I can confirm the solution.

My original `.jsbeautifyrc` file:

```json
{
  "js": {
    "indent_size": 2,
    "indent_char": "",
    "jslint_happy": true,
    "space_after_anon_function": false
  }
}
```

And then I fixed it by setting `jslint_happy` to `false` which seemed to allow `space_after_anon_function` to apply properly:

```json
{
  "js": {
    "indent_size": 2,
    "indent_char": "",
    "jslint_happy": false,
    "space_after_anon_function": false
  }
}
```
