### ISSUE TITLE
How do I make javascript use less space

### ISSUE THREAD

**Issue by zwarag** [Glavin001/atom-beautify#443]
For example, there are lots of lines like this

<pre>
        res.json({
          message: 'Dislike updated!'
        });
</pre>

I would like them to just take one line of space and look like this:

<pre>
        res.json({ message: 'Dislike updated!' });
</pre>

how can I achieve this?

**Comment by Glavin001** [comment]
Looks like a duplicate of #422. I'd recommend reading the comments over there.
