### ISSUE TITLE
Problem with <p> tag 

### ISSUE THREAD

**Issue by iashanmugavel** [Glavin001/atom-beautify#445]
if ``<p>`` has an `id` and `class` then the `class` value is misplaced after the beautification 

For example:

before:
```html
<p id="notice" class ="success">
```
after: 
```html
<p ="success" class id="notice">
```

**Comment by Glavin001** [comment]
If this is pure HTML, please forward this issue over to JS Beautify: https://github.com/beautify-web/js-beautify
If this is something else, such as EJS, ERB, etc, please forward this issue over to Pretty Diff: https://github.com/prettydiff/prettydiff/

**Comment by iashanmugavel** [comment]
Thanks. This is in ERB templated. so I have logged an issue under prettydiff.

https://github.com/prettydiff/prettydiff/issues/122

**Comment by Glavin001** [comment]
Great, thank you. @prettydiff is awesome. I'm sure this will be taken care of promptly.
Once this has been published to npm for Pretty Diff, you can uninstall and reinstall Atom Beautify to force an install of the latest Pretty Diff dependency.
