### ISSUE TITLE
Add grammar "HTML (Handlebars)" and extension "handlebars" for language "Handlebars"

### ISSUE THREAD

**Issue by mikegleasonjr** [Glavin001/atom-beautify#447]
Using Atom 1.0, atom-beautify 0.28.7
Language is set to `HTML (Handlebars)` for the file:

![screen shot 2015-07-06 at 11 47 13 am](https://cloud.githubusercontent.com/assets/1644534/8515421/defa2068-23d4-11e5-8379-ce5acc627a1c.png)

**Comment by Glavin001** [comment]
You may need to make a Pull Request adding `HTML (Handlebars)` grammar to the Atom Beautify language specifications: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/handlebars.coffee#L11

Currently it only detects with the `Handlebars` grammar.

**Comment by mikegleasonjr** [comment]
Thanks will do it later today :)

**Comment by Glavin001** [comment]
Published to v0.28.8
