### ISSUE TITLE
unable to install 0.28.7 with atom 1.0.0

### ISSUE THREAD

**Issue by jhau** [Glavin001/atom-beautify#452]
Installing “atom-beautify@0.28.7” failed.Hide output…

npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jhau/.atom/.apm/.apmrc" "--userconfig" "/Users/jhau/.atom/.apmrc" "install" "/private/var/folders/ck/bspn7s855sg34j4vxftny4j00000gn/T/d-11567-4889-jky1ed/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /var/folders/ck/bspn7s855sg34j4vxftny4j00000gn/T/npm-4893-ba475332/registry.npmjs.org/prettydiff/-/prettydiff-1.12.11.tgz
npm ERR! Expected: f4782cd5461fa1f8ecb0a2c3d5bf489b5a18c3d5
npm ERR! Actual:   69abcc62c21f62b0b22be461d49c4fd42360aa68
npm ERR! From:     https://registry.npmjs.org/prettydiff/-/prettydiff-1.12.11.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/ck/bspn7s855sg34j4vxftny4j00000gn/T/apm-install-dir-11567-4889-hzccnl/npm-debug.log

**Comment by Glavin001** [comment]
> npm ERR! shasum check failed for /var/folders/ck/bspn7s855sg34j4vxftny4j00000gn/T/npm-4893-ba475332/registry.npmjs.org/prettydiff/-/prettydiff-1.12.11.tgz
npm ERR! Expected: f4782cd5461fa1f8ecb0a2c3d5bf489b5a18c3d5
npm ERR! Actual: 69abcc62c21f62b0b22be461d49c4fd42360aa68
npm ERR! From: https://registry.npmjs.org/prettydiff/-/prettydiff-1.12.11.tgz

It looks like a Pretty Diff issue. /cc @prettydiff

> npm ERR! If you need help, you may report this error at:
npm ERR! http://github.com/npm/npm/issues

Or an `npm` issue.

Please forward this issue over to https://github.com/prettydiff/prettydiff/ or https://github.com/npm/npm

**Comment by prettydiff** [comment]
I have an update coming very soon. Hopefully republishing will fix this issue.

**Comment by prettydiff** [comment]
v1.12.12 just published.  Please verify if problem is resolved.

**Comment by jhau** [comment]
when will 0.29 be released?

**Comment by Glavin001** [comment]
@jhau : You do not need to wait for Atom Beautify v0.29 to get the latest Pretty Diff. Uninstall and reinstall Atom Beautify to trick Atom into loading the latest dependencies, such as the latest Pretty Diff.
