### ISSUE TITLE
Multiple active beautifiers per language

### ISSUE THREAD

**Issue by Cortys** [Glavin001/atom-beautify#457]
It would be pretty awesome if the plugin could handle multiple active beautifiers per language so that you can set up something like a queue of beautifiers.

I for example use JSCS and JSBeautify at the same time, since the JSCS fixer is quite rudimentary atm and JSBeautify cannot be configured to be fully compliant with my JSCS config.

This problem could be solved if it was possible to setup a queue, that runs a file through JSBeautify first and then through JSCS.

Another use case for this would be if you use different beautifiers on different projects. Instead of switching the beautifier in the settings, it would be possible to simply connect all beautifiers in series and tell them to only run if a config file is present.

This of course requires quite a lot of work but I think it's worth discussing.

**Comment by Glavin001** [comment]
Very interesting idea. So taking advantage of the additional features between various beautifiers to achieve your desired formatting? Right now there is only a single `defaultBeautifier` however I could see a `beautifierPipeline` or something similar where multiple beautifiers are enabled, each utilizing different beautification features that the other(s) may not.

If there is interest from other users as well then I think this is worth researching and developing in a future version.

**Comment by Cortys** [comment]
Sounds great. Thanks!

**Comment by pavankris** [comment]
Yes this would be really useful, as we could use default and then override some from user ..

**Comment by danseethaler** [comment]
I'd love to see this concept come to life. I've got the same issue as outlined in #484 and would love to see an HTML beautify followed by PHP. Any idea of when this might get looked at?

**Comment by Glavin001** [comment]
For those interested in developing a Pull Request.

- [ ] Add language specific options for Cascading Beautifiers
  - See `Generate Language configurations` code in `buildOptionsForBeautifiers` function at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L251-L280
- [ ] Add support for the Cascading Beautifiers in the `beautifiers.beautify` method
   - See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L322
   - [ ] Extract Cascading Beautifier language option at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L366-L369
   - [ ] Process text with each language in sequence
      - [ ] Get options for current language: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L378-L379
      - [ ] Get beautifier for current language: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L381-L399
      - [ ] Transform options for each beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L400-L451
      - [ ] Beautify current text state with current beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L455
     
The above is rough. Looking forward to seeing what others come up with as well.

**Comment by danseethaler** [comment]
Fantastic outline @Glavin001 I'd love to take a look at it although I'll have to brush up my coffeescript skills.

**Comment by Glavin001** [comment]
@danseethaler maybe http://js2.coffee/ could help you with the CoffeeScript part :wink:. Best of luck!

**Comment by Glavin001** [comment]
In addition to chaining / piping beautifier output to another, such beautifying JavaScript with JSCS and then JS-Beautify or Pretty Diff, after looking into #722 it appears that being able to beautify a language with multiple types of sub-languages (think PHP file with both PHP code and HTML code and maybe even JavaScript and CSS code within) would be valuable.

Vue is a great example ( #722 ) and an implementation found at https://github.com/LeslieYQ/vue-format/blob/master/lib/vue-format.coffee#L27-L50 used Regular Expressions to split the code into each of the sub-languages and allow their respective beautifiers to be applied individually.

I'll keep thinking about this feature. Hopefully we can have this support in upcoming months and for release v1.

**Comment by mjanser** [comment]
Is there any progress on this?

I'd be really interested in the part of using different beautifiers on different projects. Some projects I work on are using PHP_CodeSniffer, other use PHP-CS-Fixer. It would be great if the plugin could check if a config file is present and then only run the appropriate beautifier.

**Comment by Glavin001** [comment]
> Is there any progress on this?

No progress yet.

> I'd be really interested in the part of using different beautifiers on different projects. Some projects I work on are using PHP_CodeSniffer, other use PHP-CS-Fixer. It would be great if the plugin could check if a config file is present and then only run the appropriate beautifier.

This sounds like a different issue / feature, which I think would also be great to have. 
This Issue is about having multiple beautifiers for handling beautification of a complex file.
What you want would be a way for the default beautifier to be chosen dynamically given the current project. This would be simpler to accomplish. I'll have to think a little more about how I'd want to implement this. Feel free to create a separate issue for this feature request detailing your use case. Thanks!

**Comment by mjanser** [comment]
Thank you for the information. I created a separate issue #1041 as suggested.

**Comment by Glavin001** [comment]
I'm working on this feature for Unibeautify: https://github.com/Unibeautify/unibeautify/issues/4

Atom-Beautify will eventually be migrated over to Unibeautify, and therefore support this feature. See #1174.

**Comment by MattRiddell** [comment]
Hi, any progress on this?

**Comment by eivindml** [comment]
Any news?

**Comment by Glavin001** [comment]
No updates lately. I just finished my final exams yesterday, so now I will have time to revisit my work on Unibeautify. Thank you for your patience!

**Comment by MattRiddell** [comment]
Donations accepted?

**Comment by Glavin001** [comment]
Donations are very much appreciated, @MattRiddell . Thank you! 😃 

P.S. Paypal Donation button is at the top of the README. I'm not overly familiar with donations, so feel free to recommend other donation platforms I should add. Thanks again!

**Comment by MattRiddell** [comment]
Ok cool no probs 😊

**Comment by SimonFricker** [comment]
Any updates?

**Comment by Glavin001** [comment]
No update, yet. Just released #1687 and testing it now. I think this may be the next feature.

In fact, I am going to reopen this and implement in Atom-Beautify first. I will port over to Unibeautify once we are all happy with its implementation.

**Comment by MattRiddell** [comment]
Awesome!

**Comment by StefKors** [comment]
Any updates?

**Comment by Glavin001** [comment]
Multiple beautifiers per language has been implemented in Unibeautify: https://github.com/Unibeautify/unibeautify/issues/4

Atom-Beautify is being rewritten to be powered by Unibeautify. (cc @szeck87 )

Please keep the feature ideas and support coming! I appreciate your patience. I hope to develop Unibeautify to meet all of your needs.
