### ISSUE TITLE
Incorrect JavaScript formatting

### ISSUE THREAD

**Issue by richtr** [Glavin001/atom-beautify#459]
Atom Beautify is turning:

``` javascript
var someData = [
  10,
  20,
  30,
  (40),
  50
].join(',');
```

In to:

``` javascript
var someData = [
  10,
  20,
  30, (40),
  50
].join(',');
```

Any idea why `(40)` is added to the previous line and can this be fixed to maintain the original output?

**Comment by Glavin001** [comment]
Please run Atom command, `Atom Beautify - Help Debug Editor` to provide me with useful debugging information.

**Comment by prettydiff** [comment]
This issue appears to be fixed.  If I am closing this issue incorrectly please reopen it and provide details that we can investigate.
