### ISSUE TITLE
Duplicating content beautifying highlighted text

### ISSUE THREAD

**Issue by halvves** [Glavin001/atom-beautify#471]
Atom: 1.0.2
Beautify: 0.28.8
OS: Windows 7 64-bit

After the recent update, whenever I try to run beautify on highlighted content, it creates a duplicate. It seems as though its being performed as a second step from the initial "beautify", because when I "undo", the duplicate is removed, but the beautify edit remains.

**Before Beautify**
![beautifybug01](https://cloud.githubusercontent.com/assets/9411730/8778565/451cd30a-2ec4-11e5-8034-06ac64f9c44e.png)

**After Beautify**
![beautifybug02](https://cloud.githubusercontent.com/assets/9411730/8778564/44fd0ce6-2ec4-11e5-9bad-f766df4d2d91.png)

**After Undo**
![beautifybug03](https://cloud.githubusercontent.com/assets/9411730/8778637/a34e62cc-2ec4-11e5-9141-5dd2b0ee2920.png)

**Comment by Glavin001** [comment]
Does this still happen when you do not select a part of your text editor? Or only when you have selected code?

**Comment by halvves** [comment]
Strangely enough, I cannot get the bug to replicate today. Perhaps it was a problem in updating, and a system restart solved it (of course). My apologies. I will let you know if the bug ever presents itself again.

**Comment by Glavin001** [comment]
No problem. I find Atom / apm does not update packages properly, almost ever, especially for Atom beautify. I *always* recommend Restarting Atom after updating, as it is the only way to ensure it has worked and the package has been reloaded.

Let me know if it happens again. I am going to close this for now. Please let me know to reopen this issue if necessary.
