### ISSUE TITLE
Java beautify not working

### ISSUE THREAD

**Issue by ghost** [Glavin001/atom-beautify#485]
Getting the uncrustify not installed properly error. Have tried moving the uncrustify folder everywhere and anywhere. However the only way I've gotten 'where.exe uncrustify' to give me an absolute path is to make an environment variable called 'uncrustify' containing the abs path of uncrustify's containing folder. 

I can use uncrustify in terminal although i admittedly have no idea what im doing i just want the atom package to work.

currently have the uncrustify path in two environment variables, the second being the PATH variable as directed by the error. still no cigar

**Comment by kelvix** [comment]
Atom does not appear to handle changes in your environment variables between changes. So if you did not restart Atom between your changes that could be your culprit. If you did restart Atom between changes the following approach got me to my setup. Setting a user variable like so

    variable name: uncrustify
    variable value: C:\Users\JG030743\Apps\uncrustify-0.61.3

Note that I did not specify the executable only the directory where it is located and then adding that variable to my path.

    variable name: PATH
    variable value: %ORACLE_HOME%;C:\Users\JG030743\AppData\Roaming\npm;C:\Users\JG030743\AppData\Local\atom\bin:C:\Python34\Scripts;C:\Users\JG030743\AppData\Local\atom\bin;C:\Users\JG030743\.gradle\gradle-2.5\bin;%uncrustify%

If after the previous you are still not running properly could you try running `Atom Beautify: Help Debug Editor` after which you could create a gist named *.md like [this one](https://gist.github.com/kelvix/7d4daff2d1ae950de789) and link it over here for someone to look into.
