### ISSUE TITLE
Feature "Right-Click in File Tree to Beautify other files" not working

### ISSUE THREAD

**Issue by toadhats** [Glavin001/atom-beautify#489]
While the plugin works fine when invoked via the command palette or plugins menu, right clicking in the file tree generates the following error (w/ stack trace provided). Apologies if I'm reporting this wrong, long time lurker first time participator.

```
/var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/115630-39496-1uce8b3.cfg:1 Expected a number for output_tab_size, got undefined /var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/115630-39496-1uce8b3.cfg:2 Expected a number for input_tab_size, got undefined Parsing: /var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/input115630-39496-a0yrfr as language C
/var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/115630-39496-1uce8b3.cfg:1 Expected a number for output_tab_size, got undefined
/var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/115630-39496-1uce8b3.cfg:2 Expected a number for input_tab_size, got undefined
Parsing: /var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/input115630-39496-a0yrfr as language C
Hide Stack Trace
Error: /var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/115630-39496-1uce8b3.cfg:1 Expected a number for output_tab_size, got undefined
/var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/115630-39496-1uce8b3.cfg:2 Expected a number for input_tab_size, got undefined
Parsing: /var/folders/jb/jnrxxr6n5w9fssk3jr_2qpjc0000gn/T/input115630-39496-a0yrfr as language C
    at /Users/jonathan/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:289:25
    at tryCatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
    at MutationObserver.Async.drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:367:9)
```

**Comment by Glavin001** [comment]
Could you run the Atom command from the Command Palette: `Atom Beautify: Help Debug Editor`. Paste the contents of that into a Gist with the file extension `.md` (it is a markdown file), then paste the link to it here for me to see.

So the right click beautify in the file tree does call different code than would the command palette beautify however they should be similar for the most part (beautification).

If you would be interested in doing some debugging yourself, that would be very helpful.

The menu item `Beautify File` calls the command `atom-beautify:beautify-file`. See https://github.com/Glavin001/atom-beautify/blob/master/menus/atom-beautify.cson#L8
The command `atom-beautify:beautify-file` is added here: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L446
`beautifyFile` function is implemented here: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L233-L240
`beautifyFile` calls `beautifyFilePath` which is implemented here: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L187-L231

You are able to change the debugging levels by going into Atom Beautify's package settings, and changing the value of `Logger Level` option to something like `verbose` (declared at https://github.com/Glavin001/atom-beautify/blob/master/src/config.coffee#L14-L18 ). This will now show logs with level `verbose` and up, which is basically everything, in your Atom JavaScript Developer Console. So you can add debugging statements using the `logger`, such as `logger.verbose('well, this happened')`.

Hope that helps. Thanks!

**Comment by toadhats** [comment]
Here's the debug output: https://gist.github.com/toadhats/1d0b04e003bc9a3ad6f7

**Comment by toadhats** [comment]
also I'm pretty clueless so forgive me if this is really dumb, but aren't all the functions you just mentioned called when beautify is used via palette/menu as well? Since those both work, I was going to look in the code that added the right-clicking-in-tree-view functionality – but I'm like an idiot baby at JS and friends so this is definitely not my turf, I might just stare at it for a bit and see if I get a eureka

**Comment by Glavin001** [comment]
Your debug output looks successful: https://gist.github.com/toadhats/1d0b04e003bc9a3ad6f7#results 

Are you still experiencing this?
