### ISSUE TITLE
beautify HTML does not align comments

### ISSUE THREAD

**Issue by GradyD** [Glavin001/atom-beautify#490]
When on an HTML file it does beautify comments. It appears it tries to but when the comment spans multiple lines it does not end up properly indented.

**Comment by prettydiff** [comment]
Most beautifiers will not attempt to beautify the internals of comment, because a comment can contain anything.  Attempting to parse the internals of the comment can produce parse errors unnecessarily.  Accounting for these potential parser errors is a lot of work that produces extremely limited benefits.

**Comment by prettydiff** [comment]
What if a comment were lightly minified so that it is pushed onto a single line of code? This way it will no longer be a challenge to read the code, but there is the risk that you have permanently lost extraneous white space that you might need in some rare edge cases.

**Comment by GradyD** [comment]
I'm not so much asking for the comment to be minified. I would rather see the comment block be roughly the same indent as the code around it. Or if it's possible leave the comment block at the current spacing instead of moving it?

**Comment by prettydiff** [comment]
Would you mind creating a gist with an example?  Perhaps a before and after?  I believe I understand what you mean exactly, but I want to be sure we are speaking to the same things.

**Comment by GradyD** [comment]
For some reason I am not able to duplicate it anymore. Maybe it was just a blip in one of the releases.
