### ISSUE TITLE
Incorrect indentation when a comment line is placed right after a line without semicolon (JS Beautify)

### ISSUE THREAD

**Issue by seoker** [Glavin001/atom-beautify#494]
If I have a line marked as comment under a normal statement without semicolon, like this
![image](https://cloud.githubusercontent.com/assets/7975797/9057778/f01d4f4e-3ace-11e5-93df-a14a965788f5.png)
atom-beautify turns them to be
![image](https://cloud.githubusercontent.com/assets/7975797/9057812/319b3166-3acf-11e5-8d13-dc9a3176b6b9.png)

I'm wondering if this is a limitation or bug?

PS. For my team's coding convention, we don't use semicolon at the end of statements.

**Comment by Glavin001** [comment]
Could you run Atom command in command palette: `Atom Beautify: Help Debug Editor`, the put the contents into a Gist with a markdown file (extension `.md`) and paste the link here. Thanks,

**Comment by seoker** [comment]
Hi, I create a sample that shows this problem, not my original file.
Here is the link: https://gist.github.com/seoker/7e023d42715417c4811c

**Comment by prettydiff** [comment]
This looks like a Pretty Diff bug.

**Comment by seoker** [comment]
I'm using __JS Beautify__ as default JS beautifier, not prettydiff, and the result is different from pretty diff.
![image](https://cloud.githubusercontent.com/assets/7975797/9437288/0bd90b2e-4a88-11e5-89c8-5a791e57ee9f.png)

original code:
![image](https://cloud.githubusercontent.com/assets/7975797/9437343/5949afe4-4a88-11e5-8620-6ee7bf0eefe6.png)

JS beautify:
![image](https://cloud.githubusercontent.com/assets/7975797/9437349/6e4a3eae-4a88-11e5-9d36-d660ffb3309b.png)

prettydiff:
![image](https://cloud.githubusercontent.com/assets/7975797/9437400/b19a4c1c-4a88-11e5-983e-a788810dd32b.png)

**Comment by Glavin001** [comment]
If the beautifier is set to `JS Beautify` I recommend forwarding this issue over to them at https://github.com/beautify-web/js-beautify 
When you create the issue there please link back to this issue so we can see if it is closed.

Also it looks like @prettydiff implemented the fix in `Pretty Diff` beautifier: https://github.com/prettydiff/prettydiff/issues/138
So you could switch from `JS Beautify` to `Pretty Diff` for your Default Beautifier.

**Comment by prettydiff** [comment]
This issue is 2 years old.  I am closing this issue as it is likely resolved.  If the defect remains present please reopen this issue.
