### ISSUE TITLE
JS: Keeping object literals on same line?

### ISSUE THREAD

**Issue by iksose** [Glavin001/atom-beautify#495]
Especially in functions

```javascript
Array.from({length: 5}, (v, k) => k);
```

gets formatted to
```javascript
Array.from({
      length: 5
    }, (v, k) => k);
```

Also destructuring objects in function parameter definitions hit this too, but that's probably a completely different formatter.

**Comment by prettydiff** [comment]
This would be a feature request.  The default JavaScript beautifier used by atom-beautify is js-beautify but atom-beautify also uses Pretty Diff and Pretty Diff can be optionally chosen to beautify JavaScript.  My recommendation is to open a bug on each of those projects to request this:

* https://github.com/beautify-web/js-beautify
* https://github.com/prettydiff/prettydiff

To be precise when the intended option is available and set to true any list (not just objects) should be flattened if supplied as a method argument or immediately following a word type (destructuring).

**Comment by luisrudge** [comment]
:+1:  I like that idea!

**Comment by iksose** [comment]
Opened an issue on js-beautify exactly a year ago

https://github.com/beautify-web/js-beautify/issues/511

**Comment by prettydiff** [comment]
https://github.com/prettydiff/prettydiff/issues/140

**Comment by danbim** [comment]
This bug is a real show-stopper :(

**Comment by prettydiff** [comment]
I am including this change directly opposed to hiding it behind some option. Please test this out in the following beta location and let me know if you find any code examples that fail to perform as desired.

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

I used this code to develop against:

    var a = 1;
    foo({a:"a", b:"b", c:"c"});
    foo(t,["a", "b", "c"]);
    import ("a", "b", "c") from "wherever";
    import ({a:"a", b:"b", c:"c"}) from "wherever";
    import (["a", "b", "c"]) from "wherever";

Please leave any comments my repo's bug, so that I can be notified directly: https://github.com/prettydiff/prettydiff/issues/140

**Comment by bitwiseman** [comment]
@Glavin001 - js-beautify 1.6.0 supports this.

**Comment by prettydiff** [comment]
Awesome!!  For everybody waiting on this you can wait for the next Atom Beautify version or you can uninstall Atom Beautify and reinstall it to get the update immediately.
