### ISSUE TITLE
Pretty Diff (JSX, etc) creating two spaces between tag name and first attribute

### ISSUE THREAD

**Issue by luisrudge** [Glavin001/atom-beautify#496]
![jsx](https://cloud.githubusercontent.com/assets/941075/9100126/7523e214-3bad-11e5-9299-cc316e7148e9.gif)

**Comment by Glavin001** [comment]
I noticed this, too. Could you please forward this over to https://github.com/prettydiff/prettydiff and link back to here. I'll try to take a look at the Pretty Diff code and figure out what's going wrong.

**Comment by luisrudge** [comment]
Done!

**Comment by Glavin001** [comment]
Awesome, thanks! I believe @prettydiff is still away, so I will try my best to read through the Pretty Diff code and figure this one out. @luisrudge if you find anything in the Pretty Diff source that looks interesting, let me know. Thanks!

**Comment by Glavin001** [comment]
@prettydiff has already fixed this! If you uninstall and reinstall Atom Beautify it will cause the dependencies, such as Pretty Diff, to reinstall with the latest code, which has the bug fixes.

**Comment by luisrudge** [comment]
I just removed and installed atom-beautify, but it's loading the old prettydiff still

**Comment by prettydiff** [comment]
The updated version is 1.12.18.

**Comment by Glavin001** [comment]
@luisrudge that's weird. Have you restarted Atom?

**Comment by luisrudge** [comment]
@Glavin001 yeah :( I went to .atom/packages/atom-beautify/node_modules/ and pretty diff was using 1.12.17

**Comment by Glavin001** [comment]
@prettydiff please publish 1.12.18 to npm. It says only 1.12.17 is published right now: https://www.npmjs.com/package/prettydiff

**Comment by prettydiff** [comment]
Sorry about that.  It is published.

**Comment by Glavin001** [comment]
Published to v0.28.11
