### ISSUE TITLE
Editor hangs when select beautify for some time

### ISSUE THREAD

**Issue by shanalikhan1** [Glavin001/atom-beautify#498]
Hi , 
I am using latest version of your package and atom.
When i apply beautify to my page. Editor hangs for like 2-4 seconds and when i type during that ,  the edit stop responding and shows dialog to close and wait more. 
Suggestion  : There should be a status bar when applying the beautify in order to show the status ( i didnt notice any yet , if there is ) and it should allow to type when the beautify is clicked and when its in process.

**Comment by Glavin001** [comment]
It should show a popup window saying "Beautification in progress.".

Could you provide some more details please? Running Atom command from the command palette: `Atom Beautify: Help Debug Editor` will help. Please paste the contents of that into a Gist and provide the link to that Gist here so I can review. Thanks.
