### ISSUE TITLE
Non ending update indicator

### ISSUE THREAD

**Issue by zachguo** [Glavin001/atom-beautify#499]
<img width="658" alt="screen shot 2015-08-06 at 10 17 47 am" src="https://cloud.githubusercontent.com/assets/3478203/9118348/9aa0e5b0-3c24-11e5-9a99-cc7aecf30f17.png">

However the package is indeed updated after restarting Atom.

**Comment by Glavin001** [comment]
This would be an Atom or more likely `apm` bug. Please forward this issue over to https://github.com/atom/apm

That being said, I know Atom Beautify does have more dependencies than most Atom packages, and this is why some users do experience what you described in this issue. This is more obvious on slower Internet connections. 
The issue https://github.com/Glavin001/atom-beautify/issues/320 is related to this and will resolve this issue: limiting the dependencies installed by `apm` to a minimum and installing required dependencies for language-specific beautification on-demand.
