### ISSUE TITLE
Feature request: nginx.conf

### ISSUE THREAD

**Issue by alanclarke** [Glavin001/atom-beautify#505]
I :heart: this package, and would :heart: to be able to beautify nginx.conf files with it

**Comment by esetnik** [comment]
+1

**Comment by gnoymmij** [comment]
+1

**Comment by waleedsamy** [comment]
+1

**Comment by alanclarke** [comment]
Atom's auto indent feature works pretty well for nginx.conf actually, still would be nice to be able to use the same shortcut

**Comment by wonderbeyond** [comment]
+1

**Comment by ezalejski** [comment]
+1

**Comment by Glavin001** [comment]
This may work: http://stackoverflow.com/a/34958345/2578205
I recommend the Python code.

I would accept a Pull Request adding a `Nginx` language and beautifier: https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md
Example language: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/python.coffee
Example beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/autopep8.coffee

Let me know if you have any questions!

**Comment by denysvitali** [comment]
I'm working on it right now, expect a PR in a few minutes

**Comment by Glavin001** [comment]
PR Merged: https://github.com/Glavin001/atom-beautify/pull/1494

**Comment by Glavin001** [comment]
Published to v0.29.19
