### ISSUE TITLE
Beautify not yet saved files

### ISSUE THREAD

**Issue by philiplb** [Glavin001/atom-beautify#506]
Hi,

sometimes, I just want to beautify some code in my clipboard. For this, I'd like to throw it in an unsaved, new file in Atom and just hit "Beautify". But currently, I get this message: "Atom Beautify could not find a supported beautifier for this file".
Of course, the plugin doesn't have a clue what to do with this text.
It would be very neat, if Beautify could ask what beautifier to use in this case. The user could select then from a list.

**Comment by mkieblesz** [comment]
I think we might have problem with recognizing file type here, but I have the same need.

+1

**Comment by Glavin001** [comment]
This is a two part issue: 
- Atom should be attempting to recognize the grammar from the file without using its extension
- Atom Beautify should popup asking the user which beautifier they want to use, if Atom has been unable to detect the grammar

>  For this, I'd like to throw it in an unsaved, new file in Atom and just hit "Beautify". 

When I do this, I simply change the Atom text editor's grammar to my desired grammar. Go to Atom menu -> Edit -> Select grammar. You can treat that file as an already built-in way to do what you want:
> It would be very neat, if Beautify could ask what beautifier to use in this case. The user could select then from a list.

Hope that helps, it works quickly and easily for me when I do exactly what you are doing.

**Comment by mkieblesz** [comment]
wow that was easy. Thanks @Glavin001

**Comment by Glavin001** [comment]
You're welcome :smile:.

**Comment by philiplb** [comment]
Nice, good hint. :)
