### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by Erossek** [Glavin001/atom-beautify#508]
I got an error telling me to specify path to PHP CS Fixer:
"You can configure Atom Beautify with the absolute path to 'php-cs-fixer.phar' by setting 'PHP - CS Fixer Path' in the Atom Beautify package settings."
But I cannot find it in settings. The only settings I got are:
![capture](https://cloud.githubusercontent.com/assets/13380190/9220260/75db75a8-40e1-11e5-8e3d-0cb57c3bba56.PNG)
How can I do this?

**Comment by Glavin001** [comment]
Not `Language Config - PHP - CS Fixer Path`. Just `PHP - CS Fixer Path`. See docs: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php---php-cs-fixer-path

**Comment by Erossek** [comment]
I have no idea where are these options :s 
Can someone point me to exact location?

**Comment by Glavin001** [comment]
> The only settings I got are:

Is that screenshot actually the *only* settings you see? You should see many, many options shown there, including the `PHP - CS Fixer Path` option.

Please make sure Atom is updated and update Atom Beautify, if applicable.

**Comment by Erossek** [comment]
I meant settings connected to PHP, but anyway I was wrong. I just couldnt find these settings. I have found them now and everything works perfectly.

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
