### ISSUE TITLE
Feature request: Beautify for .gsp files

### ISSUE THREAD

**Issue by dudesl** [Glavin001/atom-beautify#509]
GroovyServerPage are the standar template for Java Grails Framework.

How marvelous be able to prettify the .gsp files whit atom-beautify.

**Comment by prettydiff** [comment]
Would you mind showing us where we can see a sample of GSP code?  If the code is similar enough to some other existing language it might already be supported.

**Comment by pixelbacon** [comment]
This is a very brief code snipper. but basically, it's HTML with the addition to `g` tag and the function to run via `g:___` such as `<g:each></g:each>`.
```
<ul class="myClass" id="myId"
   <g:each var="vendor" in="${allVendors}">
      <li>${vendor.name}</li>
   </g:each>
</ul>
```

**Comment by prettydiff** [comment]
Sweet.  That looks like modified XML syntax.  Could you trying running some of your largest, most complex, and seriously aggressive code samples through http://prettydiff.com/?m=beautify

If that works for you then this will be a simple enhancement.

**Comment by pixelbacon** [comment]
Yep, it worked on a pretty complex 125 line gsp that uses multiple `g` tags such as `g:each`, `g:render`, `g:if`, etc.

So pretty straight forward I think!

**Comment by prettydiff** [comment]
In that case Pretty Diff is the default beautifier for XML in Atom Beautify.  Just submit a pull request with the necessary modifications to this file: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/xml.coffee

**Comment by prettydiff** [comment]
Closing this issue as the corresponding pull request merged last year.
