### ISSUE TITLE
Add CSS Leading Zero config

### ISSUE THREAD

**Issue by ArekSredzki** [Glavin001/atom-beautify#511]
Please add support to configure whether the css beautifiers should remove/keep leading zeros.
Thanks!

**Comment by Glavin001** [comment]
I'd recommended forwarding this to:
- JS Beautify: https://github.com/beautify-web/js-beautify/issues
- Pretty Diff: https://github.com/prettydiff/prettydiff/issues 

@prettydiff

**Comment by ArekSredzki** [comment]
I know that csscomb supports it, perhaps those don't.
I'll let them know.

**Comment by Glavin001** [comment]
you can switch your default beautifier to CSScomb then.

**Comment by ArekSredzki** [comment]
Correct. I meant that it would be a nice parameter to have available from the atom-beautify settings pane. However, thinking about it now, it's probably too specific, and better left to project beautifier settings.

**Comment by prettydiff** [comment]
By leading 0 do you mean everywhere or just before a decimal:

    width: 0.5em;

Pretty Diff will retain/add a leading 0 for CSS beautification and does not provide an option otherwise.

**Comment by ArekSredzki** [comment]
@prettydiff Only just before a decimal.
Perhaps this would be a good feature to add?
Certain style guides use this, for example the default for scss-lint

**Comment by prettydiff** [comment]
https://github.com/prettydiff/prettydiff/issues/146
