### ISSUE TITLE
Keep Python template tags from formatting

### ISSUE THREAD

**Issue by studiorooster** [Glavin001/atom-beautify#514]
Is there a way to customize atom-beautify to keep Python template tags from formatting?  Python template tags are wrapped in `{% inset tag here %}` below is a code sample to give an idea of what it would look like; currently when I run atom-beautify, it formats all the tags as one line, but I would like them to stay how they are currently.  Thank you.

Sample Code

```
<ul class="menu">
     <li><a href="{% url 'home' %}">Home</a></li>
     <li><a href="{% url 'post_list' %}">Blog</a></li> 
     {% if request.user.is_authenticated %}
     <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
     <li><a href="{% url "post_new" %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> New Post</a></li> 
     {% else %}
     <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
     <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li> 
     {% endif %}
</ul>
```

**Comment by Glavin001** [comment]
Please help me, help you by providing some additional information. Follow the steps for creating a new issue at https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc , specifically the part about `Atom Beautify: Help Debug Editor`. Let me know if you have any questions. Thanks.

Also I recommend testing the beautification mode over at http://prettydiff.com/ and seeing if that does or does not work for you. Let me know.

**Comment by seangates** [comment]
👍  The tags should be left with whitespace around them (new lines especially) in tact.

Thanks for a great plugin, btw!

**Comment by prettydiff** [comment]
To what Glavin said simply beautify this as HTML with prettydiff as your HTML beautifier in the Atom Beautify settings.  This code is completely supported already.

I did see a defect in the code sample through.  `<a href="{% url "post_new" %}" class="top-menu">` should probably be `<a href="{% url 'post_new' %}" class="top-menu">`.
