### ISSUE TITLE
php-cs-fixer didn't fix the formatting and spacing.

### ISSUE THREAD

**Issue by qiansen1386** [Glavin001/atom-beautify#515]
Somehow, I found it doesn't work.

No alignment being fixed, no extra spaces being removed, there is just nothing happened. 
Can anyone please help me verify the issue? 
I am not 100% sure that it only happens on me or what.....

**Comment by tinchoz49** [comment]
same problem here :+1:

**Comment by Glavin001** [comment]
Please follow the steps outlined in https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc , specifically regarding using the command `Atom Beautify: Help Debug Editor`.

**Comment by tinchoz49** [comment]
hi @Glavin001 i made some tests and i found that my problem was to have an outdated version of php-cs-fixer. sorry

**Comment by Glavin001** [comment]
Not a problem. Future users can now see this Issue and know that they should update php-cs-fixer.
