### ISSUE TITLE
Sass does not beautify 

### ISSUE THREAD

**Issue by optikalefx** [Glavin001/atom-beautify#519]
This sass http://cl.ly/image/453l1h2q0E0W
beautifies to 
http://cl.ly/image/3Y0X2c442U2X

```
.account-form
    background: #fff
    border-bottom: 1px solid $article-preview-border
    border-left: 1px solid $article-preview-border
    border-right: 1px solid $article-preview-border
    border-top: 5px solid $header
    margin-top: +rem(200)
    +outer-container(800px)
    padding-top: +rem(30)
```

to 

```
.account-form background:#fff border-bottom:1px solid $article-preview-border border-left:1px solid $article-preview-border border-right:1px solid $article-preview-border border-top:5px solid $header margin-top:+rem(200) +outer-container(800px) padding-top:+rem(30)
```

**Comment by prettydiff** [comment]
Sass would be hard to beautify because white space is syntax.  Since white space is syntax there is an expectation that this code would be largely beautiful already.  This tool does support the SCSS variant of Sass.

**Comment by optikalefx** [comment]
If all it did was sure up new lines between styles, that would be enough. You're right that tabbing should be taken care of already, but a bunch of weird newlines could be cleaned.

**Comment by tonytonyjan** [comment]
I encountered the same problem, but I've tried many SASS format files but in vain. I just wonder that if this is not a feature of atom-beautify, why it claims it works in README: 

> CSS, including
> - Sass
> - Less

**Comment by prettydiff** [comment]
@tonytonyjan the readme says that because the package supports the SCSS form of Sass, which seems to a more common form of Sass grammar using the same pre-compiler.

**Comment by prettydiff** [comment]
It seems this question is answered.
