### ISSUE TITLE
Option to run before saving

### ISSUE THREAD

**Issue by nohe427** [Glavin001/atom-beautify#520]
Can we incorporate an option to run this before saving the file?  Alternatively, is there a way to modify the init.coffee to run the beautify before saving?

Thanks!

**Comment by rondonjon** [comment]
I'm interested in the same but when files are opened.

Our repository takes care of converting everything to company style on commit. I would like to have my own styles applied when I open a file FROM the company repository.

**Comment by Glavin001** [comment]
I am not sure I understand *why* you would want to do this, @nohe427. I suppose you could write your own script that called Atom Beautify whenever you like.

Here are the available commands: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L454-L457

```coffee
  @subscriptions.add atom.commands.add "atom-workspace", "atom-beautify:beautify-editor", beautify
  @subscriptions.add atom.commands.add "atom-workspace", "atom-beautify:help-debug-editor", debug
  @subscriptions.add atom.commands.add ".tree-view .file .name", "atom-beautify:beautify-file", beautifyFile
  @subscriptions.add atom.commands.add ".tree-view .directory .name", "atom-beautify:beautify-directory", beautifyDirectory
```

You can read and use Atom's API to call these commands: https://atom.io/docs/api/v1.0.11/CommandRegistry#instance-dispatch
I believe `dispatch` would be what you want.

So for example, this might work to trigger beautification on the current Atom text editor:

```coffee
target = "atom-workspace"
commandName = "atom-beautify:beautify-editor"
atom.commands.dispatch(target, commandName)
```

@rondonjon you may take a look at Atom's API for workspaces and text editors.
For instance, to subscribe to events for each text editor in a workspace you could use https://atom.io/docs/api/v1.0.11/Workspace#instance-observeTextEditors 

Hope that helps.
