### ISSUE TITLE
Alignment with Atom-Alignment

### ISSUE THREAD

**Issue by jeromevvb** [Glavin001/atom-beautify#521]
I use atom-alignment to align my code. 
But I use atom-beautify with the Beautify On Save function (JS Beautify). Atom-beautify alignment "break". Solution?
Thanks

**Comment by Glavin001** [comment]
Please provide additional debugging information by following the steps here: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc

**Comment by prettydiff** [comment]
@jeromevvb JS Beautify is the default beautifier for JavaScript in the atom-beautify package, but the package also includes Pretty Diff which has its own JavaScript beautifier.  Check and see if this vertical alignment is kind of what you are looking for:

* Go to http://prettydiff.com/?m=beautify
* Scroll down or search the page for option `(vertical)`
* Ensure the radio button for `Vertically align CSS/JS` is checked.
* Test out your code at the top of the page.

The vertical alignment supports:
* A list of assignments
* Object properties
* Is multidimensional

What it does not support is:
* comma separated expressions

**Comment by jeromevvb** [comment]
@prettydiff  Where can I configure this option in the settings ? Thanks!

**Comment by Glavin001** [comment]
Here are all of the documented options: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md
I recommend using the Atom Beautify package settings and finding the options you want. There are a lot.

To switch from `JS Beautify` to `Pretty Diff` use `Language Config - JavaScript - Default Beautifier`: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---javascript---default-beautifier

The `vertical` option for Pretty Diff is called `align_assignments` in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L24 
You can set it in your `.jsbeautifyrc` file with something like:

```json
{
"js": {
"align_assignments": true
}
}
```

**Comment by kfird214** [comment]
where is the .jsbeautifyrc?

**Comment by prettydiff** [comment]
Closing as this issue is likely resolved.

@kfird214 https://github.com/Glavin001/atom-beautify/blob/master/src/.jsbeautifyrc
