### ISSUE TITLE
astyle support

### ISSUE THREAD

**Issue by ScriptorNY** [Glavin001/atom-beautify#527]
Hello,

according to issue #259 there is a support for astyle (if I understood well). So, in other words, it would be able to support astyle, but as long as somebody added the beautifier ?
So if I wanted to use astyle instead of uncrustify I would have to follow [this](https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md).

Thank you very much for any response :)

**Comment by Glavin001** [comment]
You are correct, you can follow [the instructions in the documentation provided](https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language) and add an Astyle beautifier to Atom Beautify.

Feel free to submit an early Pull Request with your progress and any questions you have, and we can discuss it together. Thanks!

**Comment by Glavin001** [comment]
I recommend taking a good look at the existing beautifiers before you start: https://github.com/Glavin001/atom-beautify/tree/master/src/beautifiers
Let me know if you have any questions about these.

**Comment by ScriptorNY** [comment]
Thank you very much :)
