### ISSUE TITLE
How to indent with 2 spaces HTML code ?

### ISSUE THREAD

**Issue by solisoft** [Glavin001/atom-beautify#532]
I tried to use beautify for HTML code but always use 4 spaces for indenting code ... I checked settings (all by default) and it looks ok.

How can I fix it?

**Comment by Glavin001** [comment]
Please follow the Contribution guidelines I wrote: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Specifically the points about creating a Gist with a `debug.md` file that has the contents of `Atom Beautify: Help Debug Editor`. This will help me help you resolve this problem.

**Comment by Alex0007** [comment]
I getting reverse error. In my settings there is 4 tab size, but after beautifying i got 2 tab size

In debug indent size setting overrides in .editorconfig file, but i haven't that file. After creating .editorconfig with normal indent_size value everything is going normal
https://gist.github.com/Alex0007/6314100a7140cfcb7954
