### ISSUE TITLE
Any priority of the settings? .editorconfig vs .jsbeautifyrc vs atom preference

### ISSUE THREAD

**Issue by gddabe** [Glavin001/atom-beautify#533]
I found at least 3 places for setting up atom-beautify.
1) Atom -> Preference -> Installed Package -> atom-beautify
2) .editorconfig in the project root folder / home directory
3) .jsbeautifyrc in the project root folder / home directory

I have a .jsbeautifyrc in home directory with html indent_size = 4, while I have a .editorconfig in a project root folder with html indent_size = 2, it seems to me that jsbeautifyrc is overriding the editorconfig. I am quite confused here. What is the best practice on using all these files? Is there any dependencies / priority of them?

**Comment by Glavin001** [comment]
Here is the applicable section of code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L737-L755

```coffee
# Combine all options together
    allOptions = [
      {
        _default:
          editorOptions
      },
      configOptions,
      {
        _default:
          homeOptions
      },
      editorConfigOptions
    ]
    # Reverse and add projectOptions to all options
    projectOptions.reverse()
    allOptions = allOptions.concat(projectOptions)

    # logger.verbose(allOptions)
    return allOptions
```

Options in order from lowest to highest priority:
- `editorOptions` is from your Atom's TextEditor editor options: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L655-L666
- `configOptions` is from Package Settings: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L668-L669
- `homeOptions` is from your home directory, using `.jsbeautifyrc`: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L679
- `editorConfigOptions` is from your `.editorconfig` file: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L685
- `projectOptions` are all of the options (`.jsbeautifyrc`) from the path of your current file up to the root directory: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L709-L732

I hope this helps! Please let me know if you have any more questions.

**Comment by TheCopartnery** [comment]
Nice answer. Imo would be good to see this included the docs / README

**Comment by Glavin001** [comment]
> Imo would be good to see this included in the docs / README

I absolutely agree. IMO as well. I am still working on improving the documentation as I find time.
