### ISSUE TITLE
Beautification History (AKA "undo the beautification I just did after I already closed that tab")

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#536]
Some users are experiencing problems when they beautify and then close the tab, only to realize later that the beautification was incorrect and they now must manually fix their code.

Solution:
- [ ] History limit - how many items to remember in history (this can be small, like 3)
- [ ] Automatically push the original text into the history
- [ ] Add command to open History, which is create tabs for those 3 or so items remembered in history

**Comment by phumberdroz** [comment]
I want to approach this one... 

Do you already have an idea how to store them ?

**Comment by Glavin001** [comment]
> Do you already have an idea how to store them ?

Since the history should be small (maybe 1-3 entries?), I was thinking store the History simply in memory (JS variable).

Take the file path as a key and map that to an array of 3 strings for history. Push next history item on save and keep the array short (3 entries max?).

```javascript
{
  "FILE_PATH_1": [ "change3_last", "change2_old", "change1_oldest" ],
  ...
}
```

With respect to Atom-Beautify and Unibeautify, I think for now this can be implemented within Atom-Beautify (so users can get this feature ASAP) and later, once I have finished with Unibeautify migration, we can see about moving it to either Unibeautify or keeping within Atom-Beautify.

---

**Update**: The more I think about the problem:
> Some users are experiencing problems when they beautify and then close the tab, only to realize later that the beautification was incorrect and they now must manually fix their code.

And really it comes down to: Users makes change, saves file, closes tab, loses Atom editor history for file because previous tab was closed.
With that in mind, I think this should be a separate Atom package entirely. One for persisting Undo History across sessions. I think this feature should be separate from Atom-Beautify and will be valuable even in other contexts.

**Comment by Glavin001** [comment]
I'm going to close this as `wontfix` with the expectation that *someone* may develop another package for Atom which fixes this UX issue 😄 . When (if) someone does develop such a package, please provide a link to it here with a comment and I can add it to the README to recommend users to take a look.

**Comment by phumberdroz** [comment]
I have to disagree since if I do beatification on a file path (e.g. Right click the file/path and beautify) it would not have an Undo to Beginn with.. I might be able to hack into the save function and copy the old file before. (Have to do some research on that).

At least that is why I need this feature asap.

**Comment by Glavin001** [comment]
>  it would not have an Undo to Beginn with

Shoot! You are correct. Thank you for reminding me. Here is the applicable code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L227

So I do still think a package for Atom could (and should) exist to solve the problem of Atom's Undo History being lost, however that is not (yet) this issue here.

I haven't thought too much about this feature. What are your ideas on how you are thinking of implementing it?

**Comment by phumberdroz** [comment]
I would like to replicate the file structure on beautification with file system if project root exists I would but it in a folder .atom-beautify/path/to/file.date otherwise I would store it in the plugin Folder under history something then save it somehow in the settings to get all the old files .. not so sure yet. 

I still have to do some research.

**Comment by Glavin001** [comment]
I think creating a backup copy within the date is a good idea. I recommend something like https://www.npmjs.com/package/tmp or https://github.com/bruce/node-temp for creating the directory though, so it eventually gets cleaned up.
