### ISSUE TITLE
CoffeeScript does not beautify... :/

### ISSUE THREAD

**Issue by aayushkapoor206** [Glavin001/atom-beautify#537]
CoffeeScript never beautifies in Atom

**Comment by Glavin001** [comment]
Please following the guidelines for creating issues: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Specifically running the command `Atom Beautify: Help Debug Editor` and putting the debugging results into the Gist.

**Comment by prettydiff** [comment]
White space is syntax in CoffeeScript, so it can be presumed that CoffeeScript should already be beautified.

**Comment by Glavin001** [comment]
There are some things that are beautified for CoffeeScript using https://github.com/sterpe/coffee-fmt
