### ISSUE TITLE
Please add an easy to find note about your use of Google Analytics

### ISSUE THREAD

**Issue by rugk** [Glavin001/atom-beautify#538]
Please add an easy to find note about your use of Google Analytics to the Readme (or another prominent place). Similar to https://github.com/Hackafe/atom-sync-settings#privacy

Additionally - if you not already have - please also add an option to disable tracking.

**Comment by Glavin001** [comment]
There is an option available for disabling analytics: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#anonymous-analytics

**Comment by rugk** [comment]
Okay, so that's there. What about a note in the Readme?

**Comment by Glavin001** [comment]
The README links to the documentation: https://github.com/Glavin001/atom-beautify#configuration

**Comment by Glavin001** [comment]
I would be open to reviewing and merging a Pull Request on any changes you would recommend.

**Comment by rugk** [comment]
Well... okay. It's a bit hidden, but as almost all users of this package should have visited [the options page](https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#anonymous-analytics) so I think that's okay.
