### ISSUE TITLE
Support for TSX (use JSX)

### ISSUE THREAD

**Issue by tomitrescak** [Glavin001/atom-beautify#542]
What a superb plugin! I have tested that JSX formatter works quite wel in TSX files, is there any wau that I can say that also TSX files should be formatted by JSX? Thanks!

**Comment by Glavin001** [comment]
Take a look at this document that @prettydiff helped put together: https://github.com/Glavin001/atom-beautify/wiki/Add-an-unsupported-language-using-an-existing-beautifier
I always love to review Pull Requests and get them merged for everyone else to use.
Let us know if you have any questions. Thanks!

**Comment by Glavin001** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/601
