### ISSUE TITLE
How to turn off leading zero on decimals?

### ISSUE THREAD

**Issue by abea** [Glavin001/atom-beautify#543]
I searched the [options md file](https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md), but couldn't find this option. Is there a way to turn off the addition of a leading zero to decimal values in Sass (or altogether?). It conflicts with Sass linting.

E.g., leave `margin: .5rem` as-is instead of changing to `margin: 0.5rem`.

**Comment by Glavin001** [comment]
Please follow the contribution instructions at https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc for creating a new issue. Specifically the parts about creating Gist with the results of command `Atom Beautify: Help Debug Editor`. This will provide us with additional information about your current setup, which beautifier is being used, an example file we can use for testing this feature later, and more. Thanks.

**Comment by abea** [comment]
Thanks, Glavin. [Here's my debug gist](https://gist.github.com/abea/632626ddbda0111c5aca#file-debug-md).

**Comment by Glavin001** [comment]
> 2015-09-10T17:36:03.050Z - verbose: [/Users/alex/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee] prettydiff inchar= , insize=2, objsort=false, preserve=none, cssinsertlines=false, comments=indent, force=false, quoteConvert=double, vertical=none, wrap=0, space=undefined, source=


Looks like [Pretty Diff](prettydiff.com) is being used. @prettydiff has created issue #524 to note which Pretty Diff options are still not supported by Atom Beautify. I see an option `noleadzero`: http://prettydiff.com/documentation.xhtml#noleadzero

> If in CSS values leading 0s immediately preceeding a decimal should be removed or prevented.

This `noleadzero` sounds like the option you want.

This is good! It is pretty easy to add options to Atom Beautify languages and beautifiers. See https://github.com/Glavin001/atom-beautify/issues/524#issuecomment-133938850 for some notes and links to applicable files, if you are interested in making a Pull Request.

Here's a TODO list that can guide you to create this Pull Request:
- [ ] Add the option to the `css` language
  - See https://github.com/Glavin001/atom-beautify/blob/master/src/languages/css.coffee#L30
  - Note that the `sass` language will fallback and apply options set to `css` namespace: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/sass.coffee#L5 
   - This means that putting the option on the `css` language will mean both `css`, `sass`, and others that fallback to `css` will be able to use it too!
- [ ] Allow the option to be used by the Pretty Diff beautifier within Atom Beautify
  - See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L8
  - [ ] Add the key for the option and it will now be available internally to the beautifier when `beautify` is called at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L51
- [ ] Update the documentation
  - run `coffee docs/` and commit these documentation changes, too

That's it! Let me know if you have any questions.

**Comment by Glavin001** [comment]
I am going to mark this as a duplicate and migrate my comment over to #524.

**Comment by Glavin001** [comment]
Published to v0.28.12 as CSS option `no_lead_zero`

**Comment by abea** [comment]
Excellent! Thank you, Glavin.
