### ISSUE TITLE
Beautify Fortan 77

### ISSUE THREAD

**Issue by jpsferreira** [Glavin001/atom-beautify#544]
I can't beautify my files in fortran 77 format. Only .f90 and .f95 works. Is there any possibility to extend for .f, .for , .f77 formats?

**Comment by prettydiff** [comment]
If you were to beautify Fortran 77 code as though it were a Fortran 90 code sample does it break?  I am not familiar enough with Fortran to be aware of differences in syntax requirements.

**Comment by jpsferreira** [comment]
F77 is a sub-set of F90. Regarding the syntax, F77 is a fixed format source code while F90 allows free format. Grossly, F77 does not allow variables with more than 6 characters and the first 7 columns of each code line have special features. For example, if the 1st column have a character the respective line is a comment, is the 6th column have a number means that the code line is to continue the previous one (usually used for long equations).

**Comment by Foadsf** [comment]
I receive this message when trying to beatify my f95 code:

Atom Beautify could not determine a supported beautifier to handle this file with grammar "Fortran - Free Form" and extension "f95". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by prettydiff** [comment]
@Foadsf Could you submit a pull request with the solution.  Justify modify this document: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/fortran.coffee

**Comment by Foadsf** [comment]
you may consider I a very new user of git and github :)
I added the f95 file extension and sent a pull request. hopefully it helps.

**Comment by Glavin001** [comment]
Closed by https://github.com/Glavin001/atom-beautify/pull/1380

**Comment by Glavin001** [comment]
Published to v0.29.15
