### ISSUE TITLE
Add support for Elixir

### ISSUE THREAD

**Issue by kyledecot** [Glavin001/atom-beautify#545]

**Comment by prettydiff** [comment]
Any additional information you could provide would be helpful.  I have no idea what Elixir is.

https://github.com/Glavin001/atom-beautify/wiki/Add-an-unsupported-language-using-an-existing-beautifier

**Comment by jvanek** [comment]
+1

**Comment by Tonkonozhenko** [comment]
+1

**Comment by prettydiff** [comment]
I am guessing Elixir is this: http://elixir-lang.org/

**Comment by Tonkonozhenko** [comment]
@prettydiff, exactly

**Comment by nateless** [comment]
+1

**Comment by efries** [comment]
+1

**Comment by davidmoshal** [comment]
+1

**Comment by jeromedoyle** [comment]
+ 1

**Comment by agelin** [comment]
+1

**Comment by thewolf** [comment]
+1

**Comment by thewolf** [comment]
http://elixir-lang.org/

**Comment by greentornado** [comment]
+ 1

**Comment by rakirox** [comment]
+1

**Comment by mintuhouse** [comment]
+1

**Comment by JohnBat26** [comment]
+1

**Comment by gohackfelipe** [comment]
+ 1

**Comment by sergiorivas** [comment]
+1

**Comment by Dephora** [comment]
+1

**Comment by chrisjowen** [comment]
+1

**Comment by prettydiff** [comment]
Is anybody able to recommend a Elixir beautifier?

**Comment by ssijak** [comment]
+10

**Comment by prettydiff** [comment]
Somebody on Hacker News suggested https://github.com/rrrene/credo/

Does anybody have experience with that tool and does it make for a good beautifier?

**Comment by Glavin001** [comment]
@prettydiff: credo looks like it only works for linting. Do you see in their documentation how to force editing the file?

**Comment by prettydiff** [comment]
No, I honestly did not look closely at it.  There are many people observing this issue who are familiar with Elixir applications, so I wondering if anybody else had better information.

**Comment by Glavin001** [comment]
I see 20 participants for this Issue.
Everyone who is interested in this feature being supported, no more +1s are necessary. Adding support is definitely something we want to do. What you can do to help, and what is required to make this happen, is find a third-party beautifier to integrate Atom-Beautify with.

**Comment by greentornado** [comment]
Can this help ? It is intellj elixir plugin 
https://github.com/KronicDeth/intellij-elixir

**Comment by ykinuse** [comment]
+1

**Comment by agustif** [comment]
There is no linter in elixir for a reason,the core team thinks there should be no enforcement or a code formatting tool for elixir.

You can check out this thread on Google Groups: https://groups.google.com/forum/#!msg/elixir-lang-talk/CfYVmQpKPIw/A5anDI4gBgAJ

+1 On an issue on a project about linting is not gonna work, I think.

**Comment by rubencaro** [comment]
+1

**Comment by RomarioLopezC** [comment]
+1

**Comment by OvermindDL1** [comment]
Also looking for elixir support.  For note the vim plugin `vim-elixir` has support for reformatting elixir source, it can be used as an example implementation.

**Comment by JohnBat26** [comment]
+1

**Comment by nietaki** [comment]
+1

**Comment by benjamingb** [comment]
+1

**Comment by alexfilatov** [comment]
+1

**Comment by DioDread** [comment]
+1

**Comment by piotrv** [comment]
+1

**Comment by taorg** [comment]
+1

**Comment by Eiji7** [comment]
@prettydiff: I'm not professional or core developer in Elixir, but I know it and I can try to help you.
As you should know Elixir is functional language.
It also has syntax inspired by Ruby and runs on the Erlang virtual machine (BEAM).
> I am guessing Elixir is this: http://elixir-lang.org/

Exactly

> Somebody on Hacker News suggested https://github.com/rrrene/credo/
>
> Does anybody have experience with that tool and does it make for a good beautifier?

Yes, it's really good tool. I use it and recommend.
The project **README.md** file have link to: [Credo's Elixir Style Guide](https://github.com/rrrene/elixir-style-guide). You can find all really useful rules and it would be awesome if you implement **Credo** messages resolving.

>There is no linter in elixir for a reason,part of the core team (or at least, member of elixir-lang-talk) thinks there should be no enforcement or a code formatting tool for elixir.
> 
> You can check out this thread on Google Groups: https://groups.google.com/forum/#!msg/elixir-lang-talk/CfYVmQpKPIw/A5anDI4gBgAJ

Maybe it's because Elixir is designed to be beautiful? 😃
But not all Elixir developers can accept him opinion. For example it's really good feature for beginners that don't know language so good, but they are happy on any tips.
From same topic:
> So what are you guys waiting for?  Jose has always been very open to accepting community contributions!  Get on that so we have an official formatting tool!  You're the "they" in this case (as in "they should build an official formatting tool").

I think describe it: "Official formatting tool in José Valim way" is not a best choose. Look at [Contributors list](https://github.com/rrrene/credo/graphs/contributors) - there are no info about "Elixir master" support. Of course I don't check all messages, issues etc., but we can describe it like: "Elixir formatting tool insipred by Credo".  Of course it's not so important. 😄

I recommend also José [Valim answer](https://elixirforum.com/t/elixir-features-inspired-or-modelled-after-other-languages/1842/5?u=eiji) in **Elixir features inspired or modelled after other languages** thread on official Elixir forum, [whole forum](https://elixirforum.com/), [official website](http://elixir-lang.org/) and [docs page](http://elixir-lang.org/docs.html) on it. You are welcome to add any newbie question in Elixir forum. We will try help you as good as we can. 😄

Any more questions?

**Comment by prettydiff** [comment]
Thanks @Eiji7 that is very helpful.  I just need to find a dedicated Elixir user who is willing to do the work to get an appropriate beautifier integrated.  There is clearly enough demand that I am sure we could find a bunch of people willing to test it and lend assistance.

**Comment by Eiji7** [comment]
@prettydiff: We have [new topic](https://elixirforum.com/t/the-elixir-style-guide-is-open-for-you/2534) on our forum for Elixir style guide. I asked for merge this with previous Credo style guide that I linked. After this I will create a git repo with sample code to test on it + code as expected results. We have lots of rules, so it needs more work than on for example JavaScript beautifier implementation.

**Comment by Eiji7** [comment]
@prettydiff: Hey, I added first [examples](https://github.com/Eiji7/atom-beautify/tree/master/examples/elixir-examples) in my fork. Can you wrote what do you think about it before I create rest examples?

**Comment by prettydiff** [comment]
@Glavin001 Would you mind reviewing and providing guidance upon these examples: https://github.com/Eiji7/atom-beautify/tree/master/examples/elixir-examples

**Comment by nardopessoa** [comment]
+1

**Comment by Eiji7** [comment]
@prettydiff: I check it every day ... when should I expect response?

**Comment by Glavin001** [comment]
> Would you mind reviewing and providing guidance upon these examples 

The directory structure for examples to be used in tests is incorrect.

For example,
- Currently is: `examples/elixir-examples/lexmag_elixir-style-guide/1_source_code_layout/01_spaces-indentation/expected.ex`
- Should be: `examples/nested-jsbeautifyrc/elixir/expected/01_space-indentation.ex`

> when should I expect response?

I'm currently finishing off two big projects for work and also starting my final exams. I should be more responsive after December 15th. Thank you for your patience. I intend on doing a major push on Atom-Beautify over the holidays.

**Comment by Eiji7** [comment]
@Glavin001: Yes, I know lots of developers are busy, so I ask (not require reviewing now) when I should expect your response. I started other projects too. You selected time after 15tth December, so I will continue writing and fixing examples near this date and at now I will focus on one of my projects that I should also finish to mid of December. Thanks for your time.
btw. I wish you good luck on your exams. 😄

**Comment by Eiji7** [comment]
@Glavin001: I have created (locally) a skeleton of all examples (I defined modules with docs and blank methods + README.md + simple script to check if we can compile these files - groups, rules, description, source, license with all needed links) with file structure that you provided. Now I need only to fill body of methods for 86 files (2 x 43 - original + expected), so I will commit my changes in next days (maybe tomorrow). Will you have a time to verify them before Christmas?

**Comment by awwong1** [comment]
+1

**Comment by xbinxu** [comment]
+1

**Comment by Glavin001** [comment]
**PLEASE DO NOT POST A +1 COMMENT**

Please 👍 on the main Issue above (see screenshot if you are confused). Only post constructive comments. Thanks.

![image](https://cloud.githubusercontent.com/assets/1885333/25067672/302c4b72-2221-11e7-87b1-604c4d2f6bde.png)

---

With regards to finding a formatter to use, it looks like there are not many options available right now:
 - https://groups.google.com/forum/#!topic/elixir-lang-talk/CfYVmQpKPIw
- https://github.com/fr1zle/vscode-elixir/issues/51#issuecomment-286431458

Elixir users who want this should go to https://groups.google.com/forum/#!topic/elixir-lang-talk/CfYVmQpKPIw and other forums to encourage the Elixir community to develop such a tool. Once the tool exists, post a link back here and we can get it integrated into Atom-Beautify.

**Comment by pinya** [comment]
There is a pretty new project: https://github.com/lpil/exfmt
While it may be a really good candidate, it's still in alpha stage and doesn't work correctly in some cases

**Comment by Glavin001** [comment]
Awesome, @pinya!

As always, Pull Requests welcome! Please let me know if you have any questions. See https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md for current instructions.

**Comment by mattdanna** [comment]
@pinya Just curious, will this support Elixir embedded in another file (i.e., `.html.eex`)?

re: https://github.com/Glavin001/atom-beautify/issues/1215

**Comment by OvermindDL1** [comment]
To elaborate on @mattdanna Elixir's template format (files ending in `.eex`) have an extension before them (in @mattdanna's example of `.html`) to make the full format of `.<templatefiletype>.eex`, so like `.html.eex`.  The file is normal content of whatever the filetype is (like html, json, xml, text, whatever) and the elixir code in it is delinated by `<%` and `%>` blocks, so something like `<% a = 42 %>` sets the binding `a` to 42, and `<%# this is a comment %>` is a comment and `<%= "blah" %>` returns the result of the expression converted to text if not already and puts it in the template (safely and escaped depending on the filetype).  But inside the `<%` and `%>` delinaters you can have any and all elixir code, and it can span multiple ones as well, like:
```html
<body>
  <%= for item <- @items do %>
    <%= if item.active do %>
      Item is active:  <%= item.name %>
    <%= else %>
      Item is not active:  <%= "#{item.name}:  #{item.inactiveReason} %>
    <% end %>
  <% end %>
</body>
```
And so forth.

**Comment by lpil** [comment]
Hi all! I'm working on an Elixir formatter [over here](https://github.com/lpil/exfmt). It's still in alpha stage but if you're interested please do check it out and open an issue for any feedback you might have. There's atom integration through another plugin, hopefully we'll also have support for this one soon. :)

**Comment by Eiji7** [comment]
@lpil: How your version will work? Did you looked at my test examples that should pass? If so then please ping me if you need to update them, because I saw that in linked style guide were merged lots of PRs, so my examples needs update. Fell free if you have any questions for each rule.

**Comment by lpil** [comment]
The formatter largely aims to implement lexmag's style guide, though this is a work in progress that will not be complete any time soon.

I think it would be counter-productive to attempt to replicate exfmt's test suite in this project as the output style is not the responsibility of this project, and work would need to go into maintaining it as exfmt's output style develops over time.

**Comment by rgreenjr** [comment]
I recently released an Elixir source code formatter for Atom. It automatically formats Elixir code using the new formatter coming in Elixir 1.6.

https://atom.io/packages/atom-elixir-formatter

**Comment by kumekay** [comment]
@rgreenjr Ron, did you figure out how to build elixir 1.6 from master on travis?

**Comment by lpil** [comment]
If you use the asdf version manager it has a command for installing the master branch. That was the easiest way that I tried. :)

**Comment by rgreenjr** [comment]
Hi @kumekay – You have a couple of options. You can download and compile the master branch of Elixir directly:

```sh
git clone https://github.com/elixir-lang/elixir.git
cd elixir
make clean test
```

Or use the `asdf` version manager, like @lpil mentioned:

```sh
asdf install elixir master-otp-20
```

Either way, make sure to go to the `atom-elixir-formatter` settings in Atom and set **Elixir Executable** and **Mix Executable** to the absolute paths of the `elixir` and `mix` executables.

<img width="748" alt="settings" src="https://user-images.githubusercontent.com/37242/31721853-1a64296c-b3e0-11e7-9b37-5d025c3a3cd3.png">

**Comment by Glavin001** [comment]
For those interesting in adding Elixir support to Atom-Beautify, please see https://github.com/Glavin001/atom-beautify/pull/1738 and help by submitting a Pull Request with changes and/or testing the existing Pull Request. With your help, hopefully, this will be coming soon!

**Comment by peterromfeldhk** [comment]
my current workaround in `~/.atom/init.coffee` (i have `atom-elixir` installed for goto def)
```
# Formats/Indents files on save.
atom.workspace.observeTextEditors (editor) ->
  editor.buffer.onWillSave ->
    sourceGrammars = ['text.html.elixir']
    currentGrammar = editor.getGrammar()?.scopeName
    return unless currentGrammar in sourceGrammars
    editor.autoIndentBufferRows 0, editor.getBuffer().getLineCount() - 1

  editor.buffer.onDidSave ->
    sourceGrammars = ['source.elixir']
    currentGrammar = editor.getGrammar()?.scopeName
    return unless currentGrammar in sourceGrammars
    ChildProcess = require('child_process')
    if currentGrammar == 'source.elixir'
      ChildProcess.spawnSync('mix', ['format', editor.buffer.file.path])
```

**Comment by jwarlander** [comment]
@peterromfeldhk, your workaround is appreciated :) I used `atom-elixir-formatter` before, but it doesn't respect `.formatter.exs` settings due to the way it's implemented.

Had to make the following change though, for the `mix format` command to run in the correct context:
```diff
@@ -57,10 +57,7 @@ atom.workspace.observeTextEditors (editor) ->
     return unless currentGrammar in sourceGrammars
     ChildProcess = require('child_process')
     if currentGrammar == 'source.elixir'
+      ChildProcess.spawnSync('mix', ['format', editor.buffer.file.path])
-      # Set CWD to the project root so 'mix format' picks up .formatter.exs settings
-      options = { cwd: atom.project.relativizePath(editor.getPath()).shift() }
-      ChildProcess.spawnSync('mix', ['format', editor.buffer.file.path], options)
```

**Comment by peterromfeldhk** [comment]
i did had some issues with undo after that format, please let me know if
you figure out something. Im currently not working with elixir sadly :( but
its one of my favourite langs!
