### ISSUE TITLE
Could not find 'rubocop'. The program may not be installed.

### ISSUE THREAD

**Issue by reidcooper** [Glavin001/atom-beautify#548]
I have install rubocop as for my linter and auto-beautify via atom-beautify in settings. However, when I run the command, "ctrl-alt-b", it returns the error that it cannot find 'rubocop'.

But linter-rubocop can find rubocop fine and work properly. I have it under rbenv.

Link:
https://gist.github.com/reidcooper/1cc6d16bf06cc8686d0c

**Comment by Glavin001** [comment]
Please follow contribution guides at https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md
Specifically the Gist named `debug.md` with the results of the `Atom Beautify: Help Debug Editor`.

**Comment by reidcooper** [comment]
I updated my original post.

**Comment by Glavin001** [comment]
For reference, here is the applicable code in linter-rubocop: https://github.com/AtomLinter/linter-rubocop/blob/master/index.coffee

**Comment by Glavin001** [comment]
@reidcooper Atom Beatify uses your PATH environment variable to detect the location of executables.

This is what Atom Beautify detects your PATH environment variable to be:

> PATH=/Users/reidcooper/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin

Could you confirm this by going into your Terminal and running `echo $PATH`?

Also what is the path to your `rubocop` executable? Running `which rubocop` will return this in your Terminal.

**Comment by reidcooper** [comment]
echo $PATH

    /Users/reidcooper/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin

which rubocop

    rubocop not found

If I type:

    rbenv which rubocop

then I get:
    
    /Users/reidcooper/.rbenv/versions/2.2.2/bin/rubocop

**Comment by reidcooper** [comment]
I am using linter-rubocop and according to their documentation, it said, if you are using rbenv to type in:

    rbenv which rubocop

Link:
https://atom.io/packages/linter-rubocop

**Comment by Glavin001** [comment]
So you have manually set the `executablePath` for linter-rubocop then? If yes, then this indicates that your statement:
> But linter-rubocop can find rubocop fine and work properly.
was incorrect. linter-rubocop was not able to find rubocop and instead you manually set it.

You can get Atom Beautify to work by adding `/Users/reidcooper/.rbenv/versions/2.2.2/bin/` to your `PATH` environment variable.

**Comment by reidcooper** [comment]
I executed

    export PATH=$PATH:/Users/reidcooper/.rbenv/versions/2.2.2/bin

to add to my path, and I restarted Atom. However, I still received the same error. Am I forgetting something? Also, I am using z-shell if that matters.

**Comment by Glavin001** [comment]
> Edit: I think I got it to work. I had to add to my zshell profile instead of the bash profile.

Right on. Glad to here it is working now.

I hope to make this process easier in the future.

**Comment by geoffreysteven** [comment]
I have been working on this problem. Just fixed it - the gem is missing:

gem install rubocop 

Solved it by looking at linter-rubocop

**Comment by emanuelet** [comment]
I'm still experiencing this issue even after having tried the solutions listed above. Would it be possible to add an option at the end  to specify the path of Rubocop?

**Comment by Glavin001** [comment]
@emanuelet : I would accept a Pull Request. Applicable code can be found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/rubocop.coffee

**Comment by emanuelet** [comment]
opened PR #676

**Comment by aashish** [comment]
update settings as in following: 

[settings]( https://i.imgsafe.org/e01de3f221.png)

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by goxr3plus** [comment]
@aashish  Image is missing ...

**Comment by aashish** [comment]
@goxr3plus Sorry for that. Please follow the instructions 
```
$ which rubocop
/home/xxxxxx/.rvm/gems/ruby-2.3.1@xxxxxxxx/bin/rubocop

```
Update Rubocop Path as
/home/xxxxxx/.rvm/gems/ruby-2.3.1@xxxxxxxx/bin/rubocop

**Comment by goxr3plus** [comment]
I did ''' gem install robucop ''' and problem was solved :)

Στις 25 Δεκ 2017 16:57, ο χρήστης "Aashish Kiran" <notifications@github.com>
έγραψε:

**Comment by aashish** [comment]
@goxr3plus great!! robocop is being detected.

**Comment by stramec** [comment]
For anyone that the above doesn't work for. If you have installed the gem and still getting errors, try using the RVM wrappers, solved it for me.

/Users/xxxxx/.rvm/gems/ruby-2.3.7@xxxxx/wrappers/rubocop
