### ISSUE TITLE
Update Install Fail

### ISSUE THREAD

**Issue by krishnat2** [Glavin001/atom-beautify#549]
I get an error while installing the new update:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'C:\Users\krishnat.atom\packages\atom-beautify\examples\simple-jsbeautifyrc\markdown\expected\yaml-front-matter-2.md'

**Comment by Glavin001** [comment]
Could you try installing again? This sounds like apm failed to download all of the files correctly.

**Comment by johnsonz** [comment]
It works well when I re-install it.
#803
