### ISSUE TITLE
Cannot set html indent to tabs from within atom

### ISSUE THREAD

**Issue by RangerMauve** [Glavin001/atom-beautify#55]
Trying to set the `Html indent char` field to `\t` makes it insert the characters `\` and `t`. It's also impossible to paste a tab character into the text input.

**Comment by julmot** [comment]
@Glavin001 Can you please elaborate why using `"indent_with_tabs": true` does not work?

**Comment by Glavin001** [comment]
> Can you please elaborate why using `"indent_with_tabs": true` does not work?

@julmot : `indent_with_tabs` *should* work, and it overrides `indentation size` and `indentation character` when used with JS-Beautify. 
If you are having issues, please create a new Issue following the template found at https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md and be sure to include the debugging information in a Gist.

**Comment by regedit15** [comment]
I had the same problem, i solved it by deleting the file ".editorconfig" of the project folder where I was working
