### ISSUE TITLE
SourcePawn

### ISSUE THREAD

**Issue by TryHardDood** [Glavin001/atom-beautify#555]
It's almost a same as C#.
Preview: http://hlmod.hu/viewsp.php?f=15940-csgo_gore.sp

**Comment by prettydiff** [comment]
I am sorry I missed this issue.  If you are willing to work with me I will add support for SourcePawn to Pretty Diff and that support will become available to this project.  I opened a new issue at https://github.com/prettydiff/prettydiff/issues/595

Please try to submit test samples to https://prettydiff.com/?mode=beautify

I suspect Pretty Diff is already providing some minimal level of support for languages that look like Java and C# but I do not program in those languages.  I need help to confirm support and identify defects.
