### ISSUE TITLE
Beautifying SCSS removes newline in nested selectors

### ISSUE THREAD

**Issue by filipesilva** [Glavin001/atom-beautify#558]
I tried running this example in prettydiff (which is the default for SCSS) but I could not get it to reproduce. It happens in atom though.

Input:
```
.comments {
  .card-block {
    background-color: #f5f5f5;
  }
}
```

Expected:
```
.comments {
  .card-block {
    background-color: #f5f5f5;
  }
}
```

Actual:
```
.comments {.card-block {
    background-color: #f5f5f5;
  }
}
```

**Comment by Glavin001** [comment]
> I tried running this example in prettydiff (which is the default for SCSS) but I could not get it to reproduce. It happens in atom though.

Sounds like maybe the Pretty Diff dependency installed within Atom Beautify may not be updated and Pretty Diff has a bug fix that you do not have.

Try uninstalling and reinstalling Atom Beautify, this will trigger a fresh install of the latest Pretty Diff and hopefully resolve your issue.

If this does not work, then please follow the steps outlined for creating new Issues: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc

**Comment by filipesilva** [comment]
Reinstalling did the trick. Should have tried that first!

**Comment by Glavin001** [comment]
No problem! Glad it worked :smiley:.
