### ISSUE TITLE
Beautify XSL

### ISSUE THREAD

**Issue by Dagur** [Glavin001/atom-beautify#559]
I was surprised to find that xsl files are not supported since xml and html are included. Would it be much trouble to add support for it?

**Comment by Glavin001** [comment]
[Pretty Diff](http://prettydiff.com/) (/cc @prettydiff) currently handles XML (see https://github.com/Glavin001/atom-beautify/blob/master/src/languages/xml.coffee#L22 ).

@Dagur please provide an example XSL file or simply try your XSL in Atom Beautify as XML, by changing your file's grammar to XML and running beautify. If it all works, we can very quickly add support for it using the current XML beautifier. Thanks.

**Comment by Dagur** [comment]
Renaming the file as .xml works very well (as far as I can see). I tried this on one (fairly large) xsl file and this example: http://producthelp.sdl.com/SDL%20Trados%20Studio/client_en/File_Types/Transformation_file_for_Sample_XML_File.htm

**Comment by prettydiff** [comment]
Yeah, XSL and XSD are just XML grammars.  They should beautify exactly with the same settings as XML.  This just needs for `.xsd` and `.xsl` file extensions to be treated the same as `.xml`.

**Comment by Glavin001** [comment]
Great! Now someone could easy make a Pull Request to:
- [ ] add the grammars and file extensions to https://github.com/Glavin001/atom-beautify/blob/master/src/languages/xml.coffee#L11-L20
- [ ] add test files in the `examples` directory. See step 4 in "How to add a Beautifier for a Language" of https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language for details.

**Comment by prettydiff** [comment]
Pull request generated: https://github.com/Glavin001/atom-beautify/pull/560

**Comment by Glavin001** [comment]
Great! Could you or @Dagur add some tests files, too. Once the tests pass it is merge ready. Thanks!

**Comment by prettydiff** [comment]
Pull request updated per your comment and includes test criteria

**Comment by Glavin001** [comment]
Published to v0.28.13

**Comment by Dagur** [comment]
Great work. Thanks everyone!
