### ISSUE TITLE
Changelog version mismatch

### ISSUE THREAD

**Issue by bartocc** [Glavin001/atom-beautify#563]
Last changelog entry is v0.29.0 while last version is 0.28.14

**Comment by jpluimers** [comment]
https://github.com/Glavin001/atom-beautify/blob/master/CHANGELOG.md badly needs updating. It mentions v0.29.0 and we're at least at v0.29.13 by now according to https://github.com/Glavin001/atom-beautify/releases without a simple way of finding out what has changed in between.

**Comment by jpluimers** [comment]
It looks like that as of https://github.com/Glavin001/atom-beautify/commit/06dcea04e9bcb6b1e2a1bd443f7dcf4a77b15933 @Glavin001 has started to regularly maintain the changelog again: 

- [History for `atom-beautify/CHANGELOG.md`](https://github.com/Glavin001/atom-beautify/commits/master?after=3dd3a2b9e9f8b2f588c28e66e100171c94da3364+34&path%5B%5D=CHANGELOG.md)
- [Blame of `atom-beautify/CHANGELOG.md`](https://github.com/Glavin001/atom-beautify/blame/master/CHANGELOG.md)

In the mean time, contributions of many others have been incorporated as well: @Focus, @mikegleasonjr, @qwemaze, @emileber, @yesenarman, @kdheepak, @sbine, @taylon, @ProgramFan, @splodingsocks, @fdelbos, @JoostvDoorn, @vmuriart, @re6exp, @papatience, @jeffs, @thejamespower, @hyst329, @tanyadegurechaff, @derBroBro.

This deserve a big thank you, as maintaining docs is hard. Keep up the good work.

**Comment by jpluimers** [comment]
@Glavin001 this issue can be closed.
