### ISSUE TITLE
PHP-(cs-fixer): Add .php_cs search and passing as --config-file

### ISSUE THREAD

**Issue by rugk** [Glavin001/atom-beautify#564]
Similar to https://github.com/pfefferle/atom-php-cs-fixer/issues/11 you could also add the `--config-file` parameter.

**Comment by rugk** [comment]
Closed as https://github.com/Glavin001/atom-beautify/pull/1010 has been merged.

**Comment by Glavin001** [comment]
Published #1010 to v0.29.8
