### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by FranBar** [Glavin001/atom-beautify#565]
I found the unpleasant surprise that this option is enabled by default.

Please completely remove this feature or at least do that is disabled by default.

Surely these data are very importants for you, but is my data, my privacy, and it is more important for my.

Thank you.

**Comment by Glavin001** [comment]
There is an option to disable analytics: https://github.com/Glavin001/atom-beautify/issues/535#issuecomment-138088039

**Comment by Glavin001** [comment]
In case you are interested, here is a reference to the code that does the analytics tracking: https://github.com/Glavin001/atom-beautify/blob/4e528809f04d88cb21e46e6dc923ef5cd17cc2a2/src/beautifiers/index.coffee#L468-L482

```coffee
# Setup Analytics User Id
          userId = atom.config.get("atom-beautify._analyticsUserId")
          analytics.identify userId : userId
          version = pkg.version
          analytics.track
            userId : atom.config.get("atom-beautify._analyticsUserId")
            event : "Beautify"
            properties :
              language : language?.name
              grammar : grammar
              extension : fileExtension
              version : version
              options : allOptions
              label : language?.name
              category : version
```

Note that the `userId` is a [randomly generated UUID (`uuid.v4()`)](https://github.com/Glavin001/atom-beautify/blob/4e528809f04d88cb21e46e6dc923ef5cd17cc2a2/src/beautifiers/index.coffee#L465-L466).
Atom Beautify tracks only information about the language name, grammar, version, and options.

This analytical data allows me to track user adopter (when Users update, and how many users are running on an older version with lots of bugs) and which languages are most used and therefore need the most support.

Top Atom Beautify Versions:
![image](https://cloud.githubusercontent.com/assets/1885333/10080558/ad7f61f2-62c6-11e5-9680-572a939ea193.png)

Top Languages:
![image](https://cloud.githubusercontent.com/assets/1885333/10080572/b8cf0e54-62c6-11e5-8cb0-9922b567feba.png)

**Comment by FranBar** [comment]
Thanks for responding, but I've seen the  Atom core ago also collects information, then instead of arguing with everyone about the importance of privacy, I decided to stop using Atom definitely.

But I appreciate your response.

**Comment by steve-ross** [comment]
Atom > Settings > Metrics (disable)

**Comment by beautispy** [comment]
Please disable by default.  This is not okay.

**Comment by prettydiff** [comment]
@beautispy Please see the comment above: https://github.com/Glavin001/atom-beautify/issues/565#issuecomment-142995190

The collected data helps prioritize efforts to improve the application.  This is free software written and maintained by volunteers on their own time outside of their real jobs.  Time is a limited resource.  If this is distressing it might be better to use an editor with a conservative constricted license that you pay for with money.

**Comment by Glavin001** [comment]
For those interested in disabling analytics, feel free to do so quickly and easily by changing the `Anonymous Analytics` setting in Atom-Beautify package settings:
![image](https://cloud.githubusercontent.com/assets/1885333/14547124/06b3f468-0281-11e6-812b-fa76bd204282.png)

In addition, I support @prettydiff 's [comment above](https://github.com/Glavin001/atom-beautify/issues/565#issuecomment-210078645).

**Comment by Glavin001** [comment]
For those interested in this issue, I recommend you read https://github.com/Glavin001/atom-beautify/issues/919#issuecomment-210216512
Thank you.
