### ISSUE TITLE
React JSX attribute order beautification

### ISSUE THREAD

**Issue by sizeon** [Glavin001/atom-beautify#566]
Atom-beautify automatically reorders attributes in a React JSX DOM tag; however, the order of attributes in a React JSX DOM tag is important, i.e. overriding.

Is it possible to add this as an option so that the beautifier does not reorder the attributes?

**Comment by Glavin001** [comment]
@prettydiff is there an option for that?

Here are the list of options for Pretty Diff in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff

**Comment by prettydiff** [comment]
No, I don't have an option for that.  I will have to create it.

**Comment by prettydiff** [comment]
Actually, before I write the option for this @sizeon can you provide an example where attribute order causes problems?  I want to have a specific understanding of the problem in case I can solve this problem directly for JSX support.

**Comment by sizeon** [comment]
React Example:
https://facebook.github.io/react/docs/jsx-spread.html
"You can use this multiple times or combine it with other attributes. The specification order is important. Later attributes override previous ones." -- Quote from the page


My Example:
<input attribute="overridden attribute" {...this.props} {...custom_props_overriding_this_props} attribute="overriding attribute">

**Comment by prettydiff** [comment]
In that case what makes the most sense is to ensure the embedded JavaScript logic on the tag, as determined by the curly braces, always comes before named attributes. The named attributes are more specific and so should overwrite similarly named references declared in the curly braces.  Would that work for you?

**Comment by sizeon** [comment]
'''<input attribute="overridden attribute" {...this.props} {...custom_attributes_overriding_this_props} attribute="overriding attribute">

**Comment by sizeon** [comment]
The following would happen if I use the beautify.

Original Code
```
<input {...this.props} {...custom_attributes_overriding_this_props} style={custom_style}>
```
Currently Beautified
```
<input  style={custom_style} {...custom_attributes_overriding_this_props} {...this.props}  >
```

**Comment by prettydiff** [comment]
Sorry, I should have been more specific.  What if the code becomes this:

    <input {...custom_attributes_overriding_this_props} {...this.props} style={custom_style}>

The attributes are still alphabetized, but named attributes come after the unnamed attributes thereby allowing anything provided from spread operators to be more specifically overwritten.

**Comment by sizeon** [comment]
@prettydiff 

I believe the named attributes, if put before curly braces, will be overridden by the similarly named references declared in the curly braces.  It seems that only order matters.  (I just checked in react 0.13.3)

**Comment by prettydiff** [comment]
Great, then I can fix this without the creation of a new option.

**Comment by sizeon** [comment]
The correct one would be (do not reorder):
```
<input {...this.props}  {...custom_attributes_overriding_this_props} style={custom_style}>
```

**Comment by prettydiff** [comment]
Then I will ensure there is this order of precedence: 

* Unnamed attributes come first
* Unnamed attributes beginning with spread operator and `this` come before other unnamed attributes.
* Named attributes come last
* Alphabetize all attributes while adhering to the prior specified rules.

**Comment by sizeon** [comment]
The order of precedence above certainly (w/o alphabetizing unamed attributes beginning with spread operators) works for me in most cases; however, I think the easiest and the more versatile option would be leave it to the user.  That is named attributes could come before or after unnamed attributes beginning with spread operator.  

For example, in my code, I would like to have my own named attribute overriding spread operator.  In this way, I can take over the style and still make customization available.  This could be done by writing a style mixin that merges the input prop style and my own style, and then apply it to the component.

My Code Example: style can enhance and override prop style but i need to merge using mixin.
```
<a {...this.props} style={style}>
```

But, other people may want to have the spread operator overriding their named attribute.  In this way, they can take over the style but they have to provide the entire style outside the component.

Potential Other Code Example: prop style will override style if prop style exists
```
<a style={style} {...this.props}>
```

**Comment by prettydiff** [comment]
Bah, I am going to make this really simple and just eliminate attribute sorting entirely for JSX only.

**Comment by sizeon** [comment]
Thanks for the good work!

**Comment by sizeon** [comment]
@Glavin001 
prettydiff already solved this bug, can you integrate it into beautify?  Thanks!

**Comment by prettydiff** [comment]
I haven't published the solution just yet.

**Comment by Glavin001** [comment]
@sizeon : Once Pretty Diff has been published, you can uninstall and reinstall Atom Beautify to trigger a fresh install of the latest Pretty Diff.

**Comment by prettydiff** [comment]
@sizeon I have launched this change to Pretty Diff.

**Comment by sizeon** [comment]
Great! it works.
