### ISSUE TITLE
If .csscomb.json is edited, changes do not apply til atom is reloaded

### ISSUE THREAD

**Issue by DanielJoyce** [Glavin001/atom-beautify#567]
1) Edit .csscomb.json in project root
2) load Atom
3) Try and format a scss file, it works.
4) edit .csscomb.json while atom is open.
5) Try and reformat, new format rules are not applied
6) Quit and restart atom, try reformatting same scss file, new format now is applied.

**Comment by DanielJoyce** [comment]
On mac, a custom .csscomb.json in project root doesn't seem to work at all.

**Comment by Glavin001** [comment]
Here is the applicable code: https://github.com/Glavin001/atom-beautify/blob/f1a6892ac8e0b0dddbb3c97b28a16d771fe882e9/src/beautifiers/csscomb.coffee#L26

```coffee
 # Load from Project's .csscomb.json
        projectConfigPath = atom.project.getDirectories()?[0]?.resolve('.csscomb.json')
        config = require(projectConfigPath) # Will throw error if does not exist
```

Looking at the code, this makes sense, because using `require` is cached.

I would be open to reviewing a Pull Request that fixes this issue.

**Comment by DanielJoyce** [comment]
Well I can't do it. I just use atom, and I am unfamiliar with Electron.

**Comment by DanielJoyce** [comment]
#568

**Comment by manavm1990** [comment]
Yes, it seems that one must, in fact, close out the project prior to closing and then reopening Atom. I consider this a minor issue though, as once everything 'is set,' granted, it may require some closing/reopening, it doesn't usually need to be touched, and one move along with the project after this point.
