### ISSUE TITLE
Uncrustify for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA language support

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#57]
Closes existing issue #45 (Java).

**Comment by pavankris** [comment]
sublime uses astyle, and i think astyle also accepts multiple cfg

**Comment by melkir** [comment]
Can I use Astyle instead of Unscriustify actually ?
I'm trying to edit the default.cfg to indent to 4 instead of 8 but it doesn't work.
Plus it's use tab and I prefer space and it's don't indent java inner class...
Pretty boring to configure such things manually :(
