### ISSUE TITLE
Dont break Line if object has only one attribute (JavaScript)

### ISSUE THREAD

**Issue by ericrange** [Glavin001/atom-beautify#571]
Hey is it possible somehow to prevent atom-beautify from breaking the line if a javascript object has only one attribute + value?

i think its much more beautiful then the other way round. e.g.

```
/* The way it should be */
obj.push({ id: 1 });
```

```
/* The way it is */
obj.push({ 
  id: 1
});
```

**Comment by prettydiff** [comment]
I would suggest opening an issue with web-beautify/js-beautify and I will evaluate adding this to Pretty Diff.
