### ISSUE TITLE
Allowing custom command-line options for autopep8

### ISSUE THREAD

**Issue by bziemons** [Glavin001/atom-beautify#581]
First off: Great atom package. It's been helping me a lot.

I am using atom-beautify for my python code at work and I know autopep8 has some additional options listed on https://pypi.python.org/pypi/autopep8/, which can make my life even easier. The most important examples are the --aggressive and the --experimental command-line options.

To my regard: I would like to have a setting to enable these in some way.

Right now I have modified atom-beautify myself to enable me to enter additional command-line options myself in the package settings. The few lines I added look like these:

``` Diff
diff --git a/src/beautifiers/autopep8.coffee b/src/beautifiers/autopep8.coffee
index e924755..5a01825 100644
--- a/src/beautifiers/autopep8.coffee
+++ b/src/beautifiers/autopep8.coffee
@@ -20,6 +20,7 @@ module.exports = class Autopep8 extends Beautifier
       ["--max-line-length", "#{options.max_line_length}"] if options.max_line_length?
       ["--indent-size","#{options.indent_size}"] if options.indent_size?
       ["--ignore","#{options.ignore.join(',')}"] if options.ignore?
+      [options.additionals] if options.additionals?
       ], help: {
         link: "https://github.com/hhatto/autopep8"
       })
```

``` Diff
diff --git a/src/languages/python.coffee b/src/languages/python.coffee
index d1cc1da..a05fe1d 100644
--- a/src/languages/python.coffee
+++ b/src/languages/python.coffee
@@ -41,5 +41,11 @@ module.exports = {
       items:
         type: 'string'
       description: "do not fix these errors/warnings"
+    additionals:
+      type: 'array'
+      default: []
+      items:
+        type: 'string'
+      description: "additional autopep8 command-line options"

 }
```

I am not directly making a pull-request, because I have no idea about coffee nor your codebase. But you are welcome to commit, modify, etc. the "code" above as your own, it's public domain.

Thanks for making this project.

**Comment by Glavin001** [comment]
I would definitely review and merge a Pull Request for adding the `aggressive` and `experimental` options for `autopep8`. You are on the right track with the above changes. I prefer to have the specific options available (`aggressive` and `experimental`), instead of providing a catch all such as `additionals`. Great to see you have them working locally for you! This may be something that I can add later in a few weeks when I have some time to go through Atom Beautify and clean up some Issues. Thanks!

**Comment by bziemons** [comment]
Sure. That's why I didn't pull request.
Do not forget that you can add up two aggressive options (or use -aa) though to have the aggressive level 2 option.

**Comment by Glavin001** [comment]
> Do not forget that you can add up two aggressive options (or use -aa) though to have the aggressive level 2 option.

Wow, I did not know that. Okay so how about instead of making the option a `boolean` (true or false) we make it an `integer` and let that be the number of times we repeated add the `--aggressive` option to the command? The `experimental` option could be a `boolean` though.

**Comment by bziemons** [comment]
That sounds good

**Comment by MattiooFR** [comment]
How do you set atom-beautify to use autopep8 in aggressive mode ? I can't find after hours of research...
