### ISSUE TITLE
Allow ES6 single line import Statements

### ISSUE THREAD

**Issue by KeKs0r** [Glavin001/atom-beautify#582]
I wanted to ask if there is an option to keep single line imports for ES6:

```javascript
import { Router, Route } from 'react-router';
```
is always being reformatted to:
```javascript
import {
  Router, Route
}
from 'react-router';
```

This behaviour would also be valid for normal object assignments e.g.
```javascript 
const { increment, incrementIfOdd, incrementAsync, decrement, counter } = this.props;
```

I do agree that line splits for objects is the prettier way, but for these kind of assignments, I think an option would be good to keep them in a single line

**Comment by prettydiff** [comment]
I recommend opening an issue with https://github.com/beautify-web/js-beautify/

I am already supporting this in Pretty Diff, which you can demo at: http://prettydiff.com/?m=beautify Just bear in mind that these code samples are not enough for the tool to automatically detect the language so just add `var a = 0;` before or after.

**Comment by KeKs0r** [comment]
How can I select using this setting in atom-beautify as for now? I don't find a setting for it in the settings pane.

**Comment by Glavin001** [comment]
All currently supported Pretty Diff options: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff

Issue about pending Pretty Diff options: https://github.com/Glavin001/atom-beautify/issues/524
I am accepting Pull Requests.

**Comment by prettydiff** [comment]
This convention is now supported by both Pretty Diff and JS Beautify.  The JS Beautify update is very fresh so you can wait for the next Atom Beautify version or uninstall/reinstall Atom Beautify to get the latest JS Beautify support.

**Comment by willin** [comment]
@KeKs0r @prettydiff @Glavin001 
How to config??

**Comment by prettydiff** [comment]
@willin It should just work automatically without any configuration.  Are you experiencing problems?

**Comment by KeKs0r** [comment]
@willin Make sure you are using prettydiff as default beautifier, its not working with JS Beautify.

**Comment by jgog** [comment]
@Glavin001 @prettydiff can we have a toggleable setting for single/multiline imports?

**Comment by prettydiff** [comment]
@jgog I opened an issue to examine this further.  I am away at a military school right now, but I will resume work on enhancements once I return home this weekend.

**Comment by jgog** [comment]
@prettydiff alright no issues!

**Comment by prettydiff** [comment]
@jgog I just reviewed the application and this feature is already in Pretty Diff.  You are looking for Pretty Diff's `neverflatten` option.  http://prettydiff.com/documentation.xhtml#neverflatten

I just tested this option against your code sample and it appears to do what you need.  http://prettydiff.com/?m=beautify

The limitation to using this option is that it applies to all blocks.

**Comment by Glavin001** [comment]
I do not think the `neverflatten` option is supported in Atom-Beautify yet. I would review and merge a Pull Request implementing it. Thanks.
