### ISSUE TITLE
Add option to disable the loading notification

### ISSUE THREAD

**Issue by tlaverdure** [Glavin001/atom-beautify#585]
Could there be an option in the settings disable to notification that says "Beautification in Progress"? Don't see the need to show this each time if using Beautify on save.

**Comment by floomy** [comment]
Much needed - this could be an optional setting.

**Comment by Glavin001** [comment]
I'm surprised this does not already exist.

Easy to add feature. Good idea.

Applicable sections of code are: 
- add an option: https://github.com/Glavin001/atom-beautify/blob/master/src/config.coffee
- read the option and do or do not show the loading view: https://github.com/Glavin001/atom-beautify/blob/288b3813bc2bb4f3f7426ae4daa5593b54e52261/src/beautify.coffee#L50-L58

I look forward to reviewing a Pull Request. Thanks!

**Comment by sharifzadesina** [comment]
Any fix for this?

**Comment by Glavin001** [comment]
@sharifzadesina : I don't believe anyone has submitted a Pull Request for this feature yet. It would be fairly straightforward to add. See https://github.com/Glavin001/atom-beautify/issues/585#issuecomment-146688740 above. If someone who wants this feature would submit a Pull request I would be happy to review and merge. Thanks!

**Comment by Glavin001** [comment]
https://github.com/Glavin001/atom-beautify/pull/1330/ has been merged.

**Comment by Glavin001** [comment]
Published to v0.29.19
