### ISSUE TITLE
Not doing anything - PHP

### ISSUE THREAD

**Issue by diego-vieira** [Glavin001/atom-beautify#595]
I just installed and it's not beautifying the code.

If you look at

``` php
$payment_type_id = $_GET['payment_type_id'];
```

you'll see that it's not indenting correctly. Not sure why. php-cs-fixer is installed globally.

https://gist.github.com/diego-vieira/d47138dd16d28478307b

**Comment by Glavin001** [comment]
Looking at your debug logs:
> 2015-10-08T13:05:59.993Z - debug: [/Users/diego/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee] spawn done 0  Fixed all files in 0.053 seconds, 6.000 MB memory used

PHP-CS-Fixer says that it *did* fix all files.

Atom Beautify correctly found the `php-cs-fixer` executable path and ran it:

> spawn /Users/diego/.composer/vendor/bin/php-cs-fixer 0=fix, 1=/var/folders/np/snghrw8n5q94z4rrvd0r_5ch0000gn/T/temp11598-45374-5kxynm

This is strange. Could you try running `php-cs-fixer` on your own and seeing if the result works? It sounds like the `php-cs-fixer` is not beautifying your code as you expect, so I recommend that you create an Issue over at https://github.com/FriendsOfPHP/PHP-CS-Fixer and see what they say.

**Comment by rbaprado** [comment]
+1

**Comment by Nightbr** [comment]
@Glavin001 hey, I see a lots of issues with php-cs-fixer and I don't know exactly why there is a bug but I find out a workaround.

In fact, if you install https://github.com/FriendsOfPHP/PHP-CS-Fixer with Globally (Composer) it is not working (don't know why, no error message...). But If you install it manually (with .phar) https://github.com/FriendsOfPHP/PHP-CS-Fixer#globally-manual, and you specified the php-cs-fixer path, it works!

Here we are, I think there are several solutions for this problem:

1. download and install the php-cs-fixer.phar and install it with the plugin
2. try to find out why it's not working with the composer install (problem executing .bat/executable file)

Let me know if I can help!

Thanks for all your work!
