### ISSUE TITLE
Bug: jsx indentation with 'switch' statements

### ISSUE THREAD

**Issue by cgong-strade** [Glavin001/atom-beautify#597]
@prettydiff ,
The indentations starting from line 3 are not quite right, please look into this.

before:

```
function getDisplay(value) {
  switch (value) {
    case 12 :
      return 'Within 1 year';
    case 24 :
      return 'Within 2 years';
    case 999 :
      return 'Any';
  }
}
```

after:

```
function getDisplay(value) {
  switch (value) {
  case 12 :
    return 'Within 1 year';
  case 24 :
    return 'Within 2 years';
  case 999 :
    return 'Any';
  }
}
```

**Comment by prettydiff** [comment]
No, this is intentional.  Originally when I started building JavaScript beautifiers they were primarily tooled towards the JSLint style guide, because at the time it was the complete and easily testable style guide around for JavaScript.  This is what JSLint recommends.

I could put an option to indent the `case` sections as nested blocks, but most of the style guides are moving towards guidance of strong opposition to switch/case.

**Comment by cgong-strade** [comment]
Thanks for the reply. I have noticed that in js files atom-beautify would actually indent the case by two space from switch. We are currently using jsx and js files together and experiencing eslint conflicts between the two. Can you reconcile them or advice. Thanks

**Comment by prettydiff** [comment]
I can hide the default behavior behind an option.

**Comment by cgong-strade** [comment]
yeah, it would be great if you have provide the option.

**Comment by axelson** [comment]
+1 for the ability to configure the switch/case indentation behavior in Javascript.

**Comment by calidion** [comment]
it is problem solved? i run into this problem too.

**Comment by prettydiff** [comment]
@calidion Could you create a debug.md file using Atom Beautify and paste that into a gist?  It will provide me all the details I need to reproduce the problem.

**Comment by Kitanotori** [comment]
Still no possibility to set switch/case indentation in JavaScript (or even better, autoload the SwitchCase setting from .eslintrc) ?

**Comment by Glavin001** [comment]
Does the `Js Beautify` also have this issue? If so, please create an issue over at https://github.com/beautify-web/js-beautify and reference back to this Issue. Thanks.

**Comment by Kitanotori** [comment]
Just realized that the "jslint-happy" setting was the culprit. Turned it off and the indentation got fixed.

https://github.com/beautify-web/js-beautify/issues/15
