### ISSUE TITLE
Question about php-cs-fixer.phar

### ISSUE THREAD

**Issue by Ray0305** [Glavin001/atom-beautify#602]
![1](https://cloud.githubusercontent.com/assets/14798066/10420690/f5c73dfa-70cb-11e5-8526-291459547cf7.png)
![5](https://cloud.githubusercontent.com/assets/14798066/10420692/f5d03112-70cb-11e5-8021-4f0fab2d58b2.png)
![3](https://cloud.githubusercontent.com/assets/14798066/10420694/f5d0baa6-70cb-11e5-8ace-2dcfaa37f192.png)
![4](https://cloud.githubusercontent.com/assets/14798066/10420693/f5d09436-70cb-11e5-9fe8-0097ddcfa9f4.png)
![2](https://cloud.githubusercontent.com/assets/14798066/10420691/f5cb46de-70cb-11e5-879c-cfd906b7aa5b.png)
![6](https://cloud.githubusercontent.com/assets/14798066/10420695/f5d81fc6-70cb-11e5-9e5c-9a7cf9e51c87.png)

I put the "php-cs-fixer.phar" into php file and user file , but it still telling me "not installed". I can load it in cmd but can't use it in atom.

**Comment by Glavin001** [comment]
Could you reload Atom and try again?
And then follow the instructions found here: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Specifically the instructions regarding running command `Atom Beautify: Help Debug Editor` and putting that into a Gist and providing a link here.
With that we will be able to see what Atom Beautify is detecting and other information that is logged.
