### ISSUE TITLE
New line after comments in CSS files

### ISSUE THREAD

**Issue by Mihayl** [Glavin001/atom-beautify#603]
Whenever I use atom-beautify on CSS files, all `/* */` line or block comments get an empty line after them.
![empty-line-after-comments](https://cloud.githubusercontent.com/assets/1562939/10450983/7953bf62-7195-11e5-9e16-560f1be3e8f4.png)

I do not have this issue with HTML or JS comments.

**Comment by Glavin001** [comment]
Please follow the instructions found here: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Specifically regarding the command `Atom Beautify: Help Debug Editor` and putting that into a Gist and linking back here. This will help us debug your issue.

**Comment by Mihayl** [comment]
Thanks for the reply Gavin. Here is the gist with the debug information: https://gist.github.com/Mihayl/684c9d858199d54f4cb9
