### ISSUE TITLE
Feature request: Add shell/bash beautifier.

### ISSUE THREAD

**Issue by jbkr** [Glavin001/atom-beautify#604]
There appears to be no beautify support for bash on the OSX version (and possibly other versions). Are there any plans to introduce this feature? Perhaps there is a bug and there is already support.

[Debugging information.](https://gist.github.com/jbkr/34f4251d28c791a228a4)

**Comment by jwigley** [comment]
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/451.
