### ISSUE TITLE
HTML beautify breaks angular expression

### ISSUE THREAD

**Issue by ghost** [Glavin001/atom-beautify#609]
beautify breaks angular expression in HTML

![before](https://cloud.githubusercontent.com/assets/2653417/10551586/cc415904-741b-11e5-925c-99dbfd2b26b9.png)

![after](https://cloud.githubusercontent.com/assets/2653417/10551588/d019944c-741b-11e5-9393-010cd299a0c0.png)

**Comment by Glavin001** [comment]
Please follow instructions found here: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
- Run command `Atom Beautify: Help Debug Editor`
- Make a Gist and post it here
Thanks.

**Comment by prettydiff** [comment]
This issue is resolved in the latest release of Pretty Diff.

**Comment by prettydiff** [comment]
I suspect this issue is long since resolved.  If the issue is closed prematurely please reopen it.
