### ISSUE TITLE
ES6 method properties are improperly indented

### ISSUE THREAD

**Issue by jordanbtucker** [Glavin001/atom-beautify#611]
``` js
obj = {
  foo(a, b) {
      return a + b
    },
    bar(x, y) {
      return x * y
    }, * quux(x, y) {
      yield x
      yield y
    }
}
```

when it should be

``` js
obj = {
  foo(a, b) {
    return a + b
  },
  bar(x, y) {
    return x * y
  },
  *quux(x, y) {
    yield x
    yield y
  }
}
```

See:
- http://es6-features.org/#MethodProperties
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

**Comment by prettydiff** [comment]
The primary beautifier for JavaScript in atom-beautify is the js-beautify project.  I recommend opening an issue with them: https://github.com/beautify-web/js-beautify/issues.  This appears to be 95% correct in Pretty Diff.

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/issues/704
It may not be pretty but it is also not a syntax error.

**Comment by prettydiff** [comment]
Closing as this issue appears to be resolved.
