### ISSUE TITLE
Pretty Diff jsx wrap line length

### ISSUE THREAD

**Issue by jmlv** [Glavin001/atom-beautify#613]
![2015-10-19 10-44-06 settings - c users evg code rekko - atom](https://cloud.githubusercontent.com/assets/7571432/10572171/873deb80-764e-11e5-8d58-78d50c279721.png)

Not working wrap line length or preserve new line

```
var New = React.createClass({
  render() {
    return (
      <InputText
        valid={validate}
        value={this.state}
        onChange={this.handleSalaryChange}
        label='test'
        onValidationError='test2'
        placeholder='test3'
        ref='test4'/>
    );
  }
});
```

After ctrl+alt+b i get

```
var New = React.createClass({
  render() {
    return (
      <InputText valid={validate} value={this.state} onChange={this.handleSalaryChange} label='test' onValidationError='test2' placeholder='test3' ref='test4'/>
    );
  }
});

```

**Comment by prettydiff** [comment]
Pretty Diff defect.

**Comment by prettydiff** [comment]
@jmlv If in the latest version of Pretty Diff you are no longer experiencing this problem would you mind recommending this issue be closed?

**Comment by jmlv** [comment]
yes

**Comment by AamuLumi** [comment]
Hi ! I'm on the last version of _atom-beautify_ (0.29.7), and I get the same bug.
I setup **JSX Wrap line length** to 80, but it doesn't do anything (some lines in my code have a length of 100~110). 

Is there any idea ?

**Comment by prettydiff** [comment]
I will investigate this weekend.

**Comment by prettydiff** [comment]
@AamuLumi I looked just now and could not reproduce the problem.  When I beautified the long defect sample in the first comment I get:

    var New = React.createClass({
        render() {
            return (<InputText
                valid={validate}
                value={this.state}
                onchange={this.handlesalarychange}
                label='test'
                onValidationError='test2'
                placeholder='test3'
                ref='test4' />);
        }
    });

Could you provide a code sample demonstrating this problem?
