### ISSUE TITLE
ES7 Class Decorators

### ISSUE THREAD

**Issue by schalke046** [Glavin001/atom-beautify#614]
@
Component({
  selector: 'my-app'
})@ View({
  template: `<div><h1>
    Welcome {{name}}
    </h1></div>`
})
class a{}

**should be like**

@Component({
  selector: 'my-app'
})
@View({
  template: `<div><h1>
    Welcome {{name}}
    </h1></div>`
})
class a{}

**Comment by prettydiff** [comment]
I recommend opening an issue with https://github.com/beautify-web/js-beautify/issues.  The beautification appears to be correct with Pretty Diff, except that Pretty Diff is not properly inserting semicolons into the sample code.
