### ISSUE TITLE
Installation on Windows without Node.js

### ISSUE THREAD

**Issue by akashpb** [Glavin001/atom-beautify#616]
I'm unable to install the package.
This message is being displayed:

Installing “atom-beautify@0.28.14” failed.Hide output…

> spawn-sync@1.0.13 postinstall C:\Users\AKASH_~1\AppData\Local\Temp\apm-install-dir-115922-2412-1wx0rj0\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\akash_000\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\akash_000\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\akash_000\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\akash_000\\.atom\\.apmrc" "install" "C:\\Users\\AKASH_~1\\AppData\\Local\\Temp\\d-115922-2412-1uns2x5\\package.tgz" "--target=0.30.7" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

**Comment by prettydiff** [comment]
Do you know if node is installed on your computer?

**Comment by akashpb** [comment]
I'm not sure. How can I install it? 

Sent from my OnePlus One.

On Oct 22, 2015 8:08 PM, Austin Cheney <notifications@github.com> wrote:

Do you know if node is installed on your computer?

**Comment by prettydiff** [comment]
I had node installed before I installed Atom in all my environments so I cannot say if its included or a prerequisite.  @Glavin001 would be better able to answer that.

Try to install Node and let me know if you are still having problems: https://nodejs.org/en/

**Comment by Glavin001** [comment]
Looks like Node.js is not installed.

spawn-sync will be using your global node.js installation instead of Atom's. That may be room for improvement actually...

**Comment by akashpb** [comment]
How do I install it? 

Sent from my OnePlus One.

On Oct 24, 2015 3:13 AM, Glavin Wiechert <notifications@github.com> wrote:

Looks like Node.js is not installed.

spawn-sync will be using your global node.js installation instead of Atom's. That may be room for improvement actually...

**Comment by Glavin001** [comment]
As @prettydiff indicated:

> Try to install Node and let me know if you are still having problems: https://nodejs.org/en/

Specifically, you can go to https://nodejs.org/en/download/ and get the appropriate Windows installer, download, run it, profit.

**Comment by Glavin001** [comment]
I am going to close this issue. @akashpb let us know if that does not work out for you.

**Comment by Glavin001** [comment]
`cross-spawn` has since been removed so this will no longer happen See https://github.com/Glavin001/atom-beautify/pull/955
