### ISSUE TITLE
html - [auto] wrap attributes indent size

### ISSUE THREAD

**Issue by robrez** [Glavin001/atom-beautify#617]
_Windows 7, atom 1.0.19, atom-beautify 0.28.14_

Thanks in advance!

I do not get the expected behavior given the following HTML settings:
- `Wrap attributes to new lines:  auto`
- `Wrap attributes indent size: 4`
- `Wrap line length: 80`

_Un-beautified_
```
<section>
  <div>
    <div data-thing="yes" data-another-thing="false" data-blah="hello" class="one two three four" data-blahblah="blah" id="mydiv">
    </div>
  </div>
</section>
```

_Beautified w/ wrap attributes:  `auto`_
```
<section>
  <div>
    <div data-thing="yes" data-another-thing="false" data-blah="hello" class="one two three four"
    data-blahblah="blah" id="mydiv">
    </div>
  </div>
</section>
```

_Beautified w/ wrap attributes:  `force` -- works as I'd expect_
```
<section>
  <div>
    <div data-thing="yes"
        data-another-thing="false"
        data-blah="hello"
        class="one two three four"
        data-blahblah="blah"
        id="mydiv">
    </div>
  </div>
</section>
```

_Desired output_
```
<section>
  <div>
    <div data-thing="yes" data-another-thing="false" data-blah="hello" class="one two three four"
        data-blahblah="blah" id="mydiv">
    </div>
  </div>
</section>
```
_Note: would be super-awesome if wrap could occur prior to the class attribute since it's the one that makes line-length > 80. I'm not sure if this is possible_

**Comment by prettydiff** [comment]
The default beautifier for HTML is js-beautify.  I recommend [opening an issue](https://github.com/beautify-web/js-beautify/issues) with.  In the mean time you can switch your desired beautifier for HTML to Pretty Diff.  Before making changes to the configuration of atom-beautify ensure that Pretty Diff does what you expect by playing around with its web tool at http://prettydiff.com/

There is a [guide](https://github.com/Glavin001/atom-beautify/wiki/Change-the-default-beautifier-for-a-given-language) that they help you change the beautifier for a given language.

**Comment by robrez** [comment]
@prettydiff Thanks for the help! I'll go check out the issue list over there.

That prettydiff demo looks very promising.
I'm going to try and track down the setting for one small tweak to its output..
```
<section>
  <div>
    <div class="one two three four" data-another-thing="false" data-blah="hello"
      data-blahblah="blah" data-thing="yes" id="mydiv"></div>
  </div>
</section>
```
I like the indentation to be '2' except in the case of wrapped attributes (i'd like '4' demo did '2')

**Comment by robrez** [comment]
Found this issue:
https://github.com/beautify-web/js-beautify/issues/640
