### ISSUE TITLE
JS/TS async/await support

### ISSUE THREAD

**Issue by patroza** [Glavin001/atom-beautify#621]
Whenever the async or await keyword is found, the beautification of the lines below will be indented wrong.

e.g:

```
    public a(options): Promise<IQueryResult<IA>> {
      x.....
    }

    public async b(gameId, options): Promise<IB[]> {
    x....
  }
```

**Comment by Glavin001** [comment]
Please follow contributing guidelines: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Specifically, run the `Atom Beautify: Help Debug Editor` command and put that into a Gist and comment link here.

**Comment by prettydiff** [comment]
I would also recommend opening a bug with https://github.com/beautify-web/js-beautify/issues

I cannot reproduce this issue with Pretty Diff.
