### ISSUE TITLE
CSS - Convert quotes always uses double quotes

### ISSUE THREAD

**Issue by lenovouser** [Glavin001/atom-beautify#622]
I've tried all options, including "double quotes", "single quotes" and "none". In any case it always converts them to double quotes. I am trying to beautify in a SCSS file. The option seems to be for CSS, but there is no equivalent option for SCSS in atom-beautify, you can just switch between JSbeautify / PrettyDiff etc. It also converts `'` to `"` in my SCSS file, which means some code is converting it in SCSS files too :smile:

**Comment by prettydiff** [comment]
Pretty Diff is not the default beautifier for CSS, but it is for SCSS and LESS so I am not sure if this is my bug.  Just in case though, I have opened this issue: https://github.com/prettydiff/prettydiff/issues/197

**Comment by ApfelUser** [comment]
@prettydiff I am actually in a SCSS file, sorry for not declaring that correctly. I thought there is no real difference, and the option in beautifier's atom package is also called "**CSS** - Convert quotes", not "**SCSS** - Convert quotes" or "**LESS** - Convert quotes". Updated my comment.

**Comment by prettydiff** [comment]
In that it is entirely my bug and I have added it to the next release: https://github.com/prettydiff/prettydiff/issues/190

**Comment by prettydiff** [comment]
This is resolved in the latest release of Pretty Diff.

**Comment by lenovouser** [comment]
Yes, this seems to work now.
