### ISSUE TITLE
Any plan to remove external dependencies 

### ISSUE THREAD

**Issue by GradyD** [Glavin001/atom-beautify#624]
Hey,

In an enterprise setting it is hard to get the external resources approved by infosec and is more software to have installed when a new employee starts. 

Is there any plan to remove the dependencies or package them into the actual package?

**Comment by prettydiff** [comment]
Having managed information security auditing for the US Army in Afghanistan I can completely sympathize with your pains.  The challenge though is that most of the dependencies are independently managed and updated.  When management of these packages is internalized they fall out of sequence with the latest updates and patches.

The big challenge here is the size of the project and the number of dependencies.  If the dependencies were all tiny or if there were only a few of them I am sure the project could work something out with internalizing things and manually updating them as needed.

I am not imagining any resolution right now, and so suggested solutions would be very helpful.
