### ISSUE TITLE
Support for ASP.NET Razor / .cshtml

### ISSUE THREAD

**Issue by edwardm** [Glavin001/atom-beautify#627]
I would LOVE to beautify my .cshtml :)

**Comment by prettydiff** [comment]
I am looking at http://weblogs.asp.net/scottgu/introducing-razor

Could you please test a whole bunch of your code samples at http://prettydiff.com/ ? I am thinking this code could just be beautified as HTML, and if so, then we only have to add support for a new file extension.

**Comment by carpogoryanin** [comment]
@prettydiff 
>> I am thinking this code could just be beautified as HTML

There are some special syntax with @, for instance:
```@Html.Partial("some_file")```
http://www.w3schools.com/aspnet/razor_syntax.asp

Pretydiff.com broke this cshtml.
.cshtml language package exist https://github.com/demyte/language-cshtml package, may be it can help for beatify supporting?

**Comment by prettydiff** [comment]
I could extend the HTML parser in Pretty Diff so that `@{` is treated as an open script tag and `}` is treated as the closing script tag.  We can also investigate adding the language-cshtml package.

**Comment by carpogoryanin** [comment]
It would be great!
But `@{` and `}` enough, see example:
![screenshot_082216_034445_pm](https://cloud.githubusercontent.com/assets/2052214/17855090/5ae85c9a-687f-11e6-9dd2-a24b796dab3f.jpg)

**Comment by prettydiff** [comment]
Conslidating to https://github.com/Glavin001/atom-beautify/issues/612
