### ISSUE TITLE
Add documentation indicating YAPF support for Python

### ISSUE THREAD

**Issue by nikolay** [Glavin001/atom-beautify#630]
It would be nice to support something other (better?) than just `autopep8` and such vital alternative is Google's [YAPF](https://github.com/google/yapf).

**Comment by nikolay** [comment]
Oops! Maybe you should just update the documentation that it's already supported.

**Comment by Glavin001** [comment]
Oh that support was added here: https://github.com/Glavin001/atom-beautify/pull/546 

I would love to receive a Pull Request for updating the documentation :smile:. Thanks in advance!

**Comment by nikolay** [comment]
@Glavin001 Will do. There's some cleanup that that PR needs anyway. Thanks!

**Comment by nikolay** [comment]
@Glavin001 Actually, YAPF does not work at all. It's disabled by default.

**Comment by Glavin001** [comment]
You can change the default beautifier: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---python---default-beautifier
Default is `autopep8` which has been supported for a while. And now `yapf` is also supported and can be easily switched to.

**Comment by nikolay** [comment]
@Glavin001 Okay, thanks! It would be nice to be able to specify the default beautifier in `.jsbeautifyrc` as well (i.e. per project).

**Comment by Glavin001** [comment]
> It would be nice to be able to specify the default beautifier in .jsbeautifyrc as well (i.e. per project).

Not the first time I have heard this; I would also like to support this, as well.

The applicable code can be found at https://github.com/Glavin001/atom-beautify/blob/1e2041e5fb560996e4b33517c0f75d21561fcde6/src/beautifiers/index.coffee#L367 for those interested in submitting a Pull Request :wink:.

**Comment by nikolay** [comment]
@Glavin001 Thanks! I will give it a try... I mean, a PR. :smile:
