### ISSUE TITLE
Space after method name depending on wether it's declared or called

### ISSUE THREAD

**Issue by sommerper** [Glavin001/atom-beautify#632]
Is there a way to achieve the following?

```
export default class SomeClass {
  constructor () {
    // no space before parentheses 
    this.doStuff();
  }

  // with space before parentheses 
  doStuff () {
  }
}
```

As far as I can see it's either on or off for all.

**Comment by prettydiff** [comment]
I recommend opening a bug with https://github.com/beautify-web/js-beautify/issues

I have just updated Pretty Diff so that this is the native behavior.
