### ISSUE TITLE
Saving SCSS multiplies leading quote of url('''''''''''''../img/icon.png')

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#635]
Hi @Glavin001 ,

As always, love your work. Found bug.

Beautifying SCSS files multiplies the leading single/double quote of `url(../img/icon.png)`.

Expected behaviour:
```SCSS
// before beautification
background-image: url(../img/icon.png);
background-image: url('../img/icon.png');
background-image: url("../img/icon.png");

// after beautification
background-image: url("../img/icon.png');
background-image: url("../img/icon.png");
background-image: url("../img/icon.png");
```

Current behaviour
```SCSS
// after 1 beautification
background-image: url('../img/icon.png');
background-image: url(''../img/icon.png');
background-image: url("../img/icon.png');

// after 2 beautifications
background-image: url(''../img/icon.png');
background-image: url('''../img/icon.png');
background-image: url("../img/icon.png');

// after 10 beautifications
background-image: url('''''''''''../img/icon.png');
background-image: url(''''''''''''../img/icon.png');
background-image: url("../img/icon.png');
```
Basically on every save my work escalates worse and worse and worse.

**The workaround** : I went to atom-beautify preferences and set `CSS - Convert quotes` to `double` or `none`. Everything stuffs up when set to `single`.

Gist debug log: https://gist.github.com/janwerkhoven/1f16ea38bc3cccf83a5e

**Comment by Glavin001** [comment]
Thanks for posting great examples and your debug log. Could you change your file extension in the Gist to `.md` (Markdown), which will make it more readable. Thanks.

@prettydiff looks like an issue with Pretty Diff beautifier.

**Comment by prettydiff** [comment]
Yep, I will issue a resolution this evening.

**Comment by prettydiff** [comment]
I put up a fix at http://prettydiff.com/  If everything appears solid I will publish this to NPM.

**Comment by prettydiff** [comment]
I just went ahead and published this resolution as v1.15.6 because I have to fly this evening and I don't know when I will be back online.

**Comment by Glavin001** [comment]
Uninstalling and reinstalling Atom Beautify -- and reload or restart Atom -- will trigger an update of Pretty Diff dependency.

**Comment by janwerkhoven** [comment]
@Glavin001 I like how you keep asking me to uninstall / install atom-beautify JUST to bump up the download counter ;)

**Comment by janwerkhoven** [comment]
It worked! :)

**Comment by Glavin001** [comment]
> I like how you keep asking me to uninstall / install atom-beautify JUST to bump up the download counter ;)

![plan](http://cdn.meme.am/instances/63917472.jpg)

In all seriousness, maybe I should talk to the Atom team about allowing dependency updates for packages -- update just the dependencies of Atom Beautify but not Atom Beautify itself. It would make this process quicker, with less Internet usage for downloading installations. I think there is a possible Pull Request in there. Lots to do over the upcoming winter holidays in a couple months.

> It worked! :)

Excellent! Enjoy.

Awesome work, as always, @prettydiff !
