### ISSUE TITLE
cannot install because of spawn sync

### ISSUE THREAD

**Issue by pungggi** [Glavin001/atom-beautify#637]
cannot install. > spawn-sync@1.0.14 postinstall C:\Users\Ale\AppData\Local\Temp\apm-install-dir-115103-7368-1yapu71\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

Der Befehl "node" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Ale\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Ale\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Ale\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Ale\\.atom\\.apmrc" "install" "C:\\Users\\Ale\\AppData\\Local\\Temp\\d-115103-7368-zok1ku\\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.14 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.14 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

**Comment by Glavin001** [comment]
I'd recommend taking a look at the other related issues: https://github.com/Glavin001/atom-beautify/search?q=spawn+sync+postinstall&type=Issues&utf8=%E2%9C%93

Here is a comment that could be a potential solution for you: https://github.com/Glavin001/atom-beautify/issues/573#issuecomment-143354959
