### ISSUE TITLE
HTML/Polymer file script gets stripped out

### ISSUE THREAD

**Issue by adefran83** [Glavin001/atom-beautify#647]
Here is my gist with the debug.md: https://gist.github.com/adefran83/35d95b8ab9a82fdcbe80

When attempting to beautify the html in the attached gist it removes everything below the <script> tag.

**Comment by prettydiff** [comment]
PrettyDiff defect.  I will have this patched in just a few.

**Comment by prettydiff** [comment]
Thank you so much for reporting this.  It's now fixed in v1.15.15.
