### ISSUE TITLE
Violations is not defined

### ISSUE THREAD

**Issue by arhodes18** [Glavin001/atom-beautify#652]
I am getting an error that says violations is not defined. I am working on .jsp files with javascript mixed in.

**Comment by Glavin001** [comment]
Please follow https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc , specifically the steps about running command `Atom Beautify: Help Debug Editor`. This information will be useful for debugging,

**Comment by arhodes18** [comment]
debug.md:
https://gist.github.com/758a14c017a5a119086f

Because the source file is close to 1000 lines, i removed all but the opening and closing html tags and the jstl at the beginning. I am not sure if I'm reading the output correctly, but it seems that the source file is being interpreted as xml.

**Comment by Glavin001** [comment]
@prettydiff any ideas?

**Comment by prettydiff** [comment]
Fixed in v1.15.16
