### ISSUE TITLE
Would like a setting to enable attribute wrap & indent for html

### ISSUE THREAD

**Issue by end-user** [Glavin001/atom-beautify#653]
I'd like the ability to set a max line length that would cause an html tag to wrap and indent it's attributes.  This would help with adding things like Angular markup.

```
<a href="/#/products/" ng-class="{'active':showProducts===nav.choice}" ng-click="fireEvent(refreshCart)">list products</a>
```

could become

```
<a href="/#/products/"
    ng-class="{'active':showProducts===nav.choice}"
    ng-click="fireEvent(refreshCart)">
         list products
</a>
```

**Comment by prettydiff** [comment]
The default beautifier for HTML is https://github.com/beautify-web/js-beautify/ and I thought they already provided this feature.  I recommend opening an issue with them or changing your beautifier to use Pretty Diff.

**Comment by laicosly** [comment]
I'm also looking to for wrap all html element attributes, "wrap_attributes": "force" sounds like the option, but isn't working like @end-user's code-example.

**Comment by prettydiff** [comment]
This issue is stale and looks fixed in Pretty Diff.  I am not sure of the status in JS Beautifier.  If this issue is closed prematurely please reopen it.
