### ISSUE TITLE
Question: is there a setting to show import in one line?

### ISSUE THREAD

**Issue by snowcxt** [Glavin001/atom-beautify#655]
For example:
I expect this code (es6/7) can be formatted in one line
```javascript
import React, {Component, PropTypes} from 'react';
```
instead of
```javascript
import React, {
  Component,
  PropTypes
} from 'react';
```

Is there any config/setting that can change this formatting behavior?

**Comment by Glavin001** [comment]
I would recommend taking a look at...

Atom Beautify documentation: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md
Pretty Diff documentation: http://prettydiff.com/documentation.xhtml#options_definitions

/cc @prettydiff

**Comment by arturparkhisenko** [comment]
@prettydiff @Glavin001 its looks fine in online version
Also its relatedTo/duplicateOf https://github.com/Glavin001/atom-beautify/issues/582

**Comment by prettydiff** [comment]
This convention is now supported by both Pretty Diff and JS Beautify.  The JS Beautify update is very fresh so you can wait for the next Atom Beautify version or uninstall/reinstall Atom Beautify to get the latest JS Beautify support.

**Comment by willin** [comment]
sorry but hard to understand
