### ISSUE TITLE
Windows - Atom - php-cs-fixer

### ISSUE THREAD

**Issue by MrDeek** [Glavin001/atom-beautify#657]
Hello,

I'm trying to install 'php-cs-fixer' what steps are needed exactly for windows10x64 ( after all the reading i can't find a good windows example step by step ).
1. Download - Atom, PHP, php-cs-fixer.phar
2. Install - Atom, PHPx64
   Path-Atom-Conf = C:\Users\Mr.Deek.atom
   Path-Atom = C:\Users\Mr.Deek\AppData\Local\atom\bin
   Path-Fixer = C:\Users\Mr.Deek.atom\packages\php-cs-fixer
   path-php=C:\Program Files\PHP\5.6.15
3. Open Atom - Install  package : atom-beautify, php-cs-fixer
4. Copy php-cs-fixer.phar to %Path-Fixer% path.
5. Restart Atom. 

My issue from here:
- I see php-cs-fixer in the menu packages menu, but it does not format the code?
- I run Atom-Beautify and it sais it can not find php-cs-fixer ???

SystemPath

```
C:\Program Files\Python\Python27;C:\Users\Mr.Deek\AppData\Local\atom\bin;C:\Program Files\PHP\5.6.15;C:\Users\Mr.Deek\.atom\packages\php-cs-fixer;C:\Users\Mr.Deek\.atom\packages\
```

C:\Users\Mr.Deek.atom\config.cson

```
"*":
  "exception-reporting":
    userId: ""
  welcome:
    showOnStartup: false
  "atom-beautify":
    _analyticsUserId: ""
    core: {}
  "php-cs-fixer":
    executablePath: "C:/Users/Mr.Deek/.atom/packages/php-cs-fixer/php-cs-fixer.phar"
    executeOnSave: false
    showInfoNotifications: true
    phpExecutablePath: "C:/Program Files/PHP/5.6.15/php.exe"
  editor:
    fontSize: 19

```

C:\Users\Mr.Deek\.jsbeautifyrc

```
{
  "html": {
    "brace_style": "collapse",
    "indent_char": " ",
    "indent_scripts": "normal",
    "indent_size": 6,
    "max_preserve_newlines": 1,
    "preserve_newlines": true,
    "unformatted": ["a", "sub", "sup", "b", "i", "u"],
    "wrap_line_length": 0
  },
  "css": {
    "indent_char": " ",
    "indent_size": 4
  },
  "js": {
    "indent_size": 2,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 2,
    "jslint_happy": true
  },
  "sql": {
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false
  }
 "php": {
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false
  }
}
```

Thank you for any suggestions?
Mr.Deek

**Comment by MrDeek** [comment]
Solution placeholder....

**Comment by Glavin001** [comment]
Here is how I was able to install php-cs-fixer on Windows for AppVeyor: https://github.com/Glavin001/atom-beautify/blob/master/appveyor.yml#L96-L105

> Path-Fixer = C:\Users\Mr.Deek.atom\packages\php-cs-fixer

I am not really why php-cs-fixer is installed here. PHP-CS-Fixer should not be in the Atom Packages directory. However, if that is where you want to put it, sure, does not really matter.

> I see php-cs-fixer in the menu packages menu, but it does not format the code?

Not really sure what this is. Atom Beautify does not put `php-cs-fixer` in the packages menu, last I checked.

Any chance you mistakenly installed https://atom.io/packages/php-cs-fixer and are confused which is php-cs-fixer for Atom and Atom Beautify?

Both php-cs-fixer for Atom and Atom Beautify require using the php-cs-fixer executable: https://github.com/FriendsOfPHP/PHP-CS-Fixer

---

I would recommend seeing https://github.com/FriendsOfPHP/PHP-CS-Fixer and talking with them for how to install PHP-CS-Fixer properly.

> C:/Users/Mr.Deek/.atom/packages/php-cs-fixer/php-cs-fixer.phar

So it looks like you do have `php-cs-fixer.phar` in a rather strange location -- under .atom/packages -- however this is OK.

And looking at your System Path (or Path Environment Variable in non-Windows systems) is valid and includes: 

> C:\Users\Mr.Deek\.atom\packages\php-cs-fixer

I think you should test to make sure this is working properly from your Shell.

I do this on the AppVeyor Windows CI: https://github.com/Glavin001/atom-beautify/blob/master/appveyor.yml#L105

Run the following: `where php-cs-fixer`

I would also recommend first reading https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
and following the instructions provided. Specifically the steps regarding `Atom Beautify: Help Debug Editor` and creating a Gist. It will help with proper debugging.

**Comment by AntiTriki** [comment]
I see php cs fixer only works on Linux and not for Windows... Nothing of these works!!!
