### ISSUE TITLE
CSS support shadowdom selectors?

### ISSUE THREAD

**Issue by arturparkhisenko** [Glavin001/atom-beautify#658]
I have only 1 problem, but maybe we have another problems with shadowdom selectors.
Before beautify: `:host ::content` after beautify: `:host::content`. Maybe i can config that?

**Comment by prettydiff** [comment]
Is this a problem standard CSS or in something like LESS/SCSS?  I ask because the default beautifier used for CSS is different than for the other languages and I cannot reproduce the problem in those other languages.

**Comment by ikeagold** [comment]
@prettydiff ok thanks, i'll test it soon and answer here with tests results

**Comment by ikeagold** [comment]
@prettydiff its standard CSS.

**Comment by prettydiff** [comment]
It appears csscomb is the default beautifier if I am reading https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee correctly.  You may wish to open a bug with that project: https://github.com/csscomb/CSScomb

@Glavin001 is this correct?

**Comment by Glavin001** [comment]
The default beautifier for CSS is `JS Beautify`: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/css.coffee#L28

Also see https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---css---default-beautifier
