### ISSUE TITLE
Field labels not appearing on Atom config

### ISSUE THREAD

**Issue by popcornpool** [Glavin001/atom-beautify#661]
The last batch of config fields are not showing labels; they were appearing before, of course, but no longer. The fields still write to the Atom config file, but it's just hard to know what each field does without labels.

I've tried reinstalling atom-beautify with no success to get them back. I've also tried changing themes to see if there was any effect from the theme itself, but no luck. I do not get any error alert from Atom. Below is a screen shot of what it looks like.

<img width="770" alt="screenshot 2015-11-15 00 34 51" src="https://cloud.githubusercontent.com/assets/9163179/11168009/67d120c6-8b31-11e5-83c1-416bf9dd12eb.png">

**Comment by Glavin001** [comment]
I am unable to reproduce this on my end. 

![image](https://cloud.githubusercontent.com/assets/1885333/11170025/8ad52c26-8b9e-11e5-9925-669bfda3bfdd.png)

This is an extremely weird issue. Thank you for including a screenshot.

> they were appearing before, of course, but no longer. 

Do you happen to recall the version number from before and what version you are now, so I can try to see what has changed between the two versions.

**Comment by popcornpool** [comment]
I usually try to keep my packages up to date, but I don't tend to review the settings on every update, so I can't tell for sure from what version this began happening. However, after removing Atom altogether an installing atom-beautify clean, I was able to get the labels back. Trial and error leads me to believe that my theme (https://atom.io/themes/monokai) is what is causing this problem. Reverting to the default One Dark resolves the issue.

**Comment by Glavin001** [comment]
Glad it worked out. Thanks for sharing your findings.
