### ISSUE TITLE
Settings page bug

### ISSUE THREAD

**Issue by hedii** [Glavin001/atom-beautify#667]
I don't know if it is an atom bug but the settings page for atom-beautify package is bugged.
There is a (very) long list of settings, and everything after the checkboxes list is not displayed correctly.
OSX 10.11.1, atom 1.2.1, few packages installed (all core packages, atom-autocomplete-php, php-twig, atom-beautify).

see these pictures:

![capture d ecran 2015-11-18 a 17 18 01](https://cloud.githubusercontent.com/assets/5358048/11246657/d715c54c-8e18-11e5-829c-c562c7c8eb20.png)
![capture d ecran 2015-11-18 a 17 18 05](https://cloud.githubusercontent.com/assets/5358048/11246656/d714469a-8e18-11e5-87fa-7b7bfd8e1e88.png)
![capture d ecran 2015-11-18 a 17 18 09](https://cloud.githubusercontent.com/assets/5358048/11246655/d71441d6-8e18-11e5-8648-d3b52e6b5c68.png)

**Comment by Glavin001** [comment]
I'd recommend trying a different Atom theme and seeing if that helps. 
Possibly related to issue #661.

**Comment by hedii** [comment]
changing theme to Atom black fix the issue.
strange, because #661 changed to One dark to fix the issue, but One dark is the theme you can see in my pictures where there is the issue. There must be a real problem: before opening the issue, the package setting page was messed up randomly (4/5 times).

**Comment by Glavin001** [comment]
I'd recommend making an issue over at https://github.com/atom/settings-view
Thanks.
