### ISSUE TITLE
PHP Error: Beautify in progress for a split second, and then nothing (php-cs-fixer properly installed and accessible in path)

### ISSUE THREAD

**Issue by dsifford** [Glavin001/atom-beautify#670]
Hi there,

So whenever I go to beautify a file with PHP, it acts like it's going to do something for a split second and then nothing happens. 

Let me know if you're able to find something in the logs below. Happy to answer any questions.

> Edit: removed huge debug log as requested

**Comment by dsifford** [comment]
Here's a screen recording demonstrating what's happening:

http://screencast.com/t/JtiWhp8MGe

**Comment by Glavin001** [comment]
@dsifford could you move your debugging information into a Gist, please. See https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc for details.

**Comment by dsifford** [comment]
My apologies @Glavin001 -- the debug popup didn't mention that step.

Here you go: https://gist.github.com/6c2722cdd3e12292f521

**Comment by Glavin001** [comment]
No problem. ~~You can also remove the original debug logs from your initial issue contents above, to clean up the discussion.~~

> the debug popup didn't mention that step.

Good point. Thank you for mentioning that. The contributing guidelines are newer than the debugging feature. I should change the message there to be more helpful.
Applicable code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L394-L399

**Comment by Glavin001** [comment]
So there has been another reported issue with PHP-CS-Fixer that may be related: https://github.com/Glavin001/atom-beautify/issues/453

Looking at your debugging logs that you provided, it looks like Atom Beautify is working as expected.

Could you try to beautify your PHP file manually with PHP-CS-Fixer and see if the resulting beautified file contents is different? See usage instructions at https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage

**Comment by dsifford** [comment]
Yep, I did that step before posting the issue to double check that I'm not a beautifully-gifted PHP code writer (spoiler: I'm not!).. 

I can run it again and post the differences if you'd like.

**Comment by Glavin001** [comment]
> I can run it again and post the differences if you'd like.

I would appreciate that data, too. Thanks.

Also, I noticed you are beautifying a selected part of your code. Why not beautify the entire file, without pre-selecting it? Maybe this is a selection problem, which is why I want to eliminate that concern.

**Comment by dsifford** [comment]
### Before CLI php-cs-fixer

```php
<?php
/**
 * @package ALiEMU Course Grid
 * @version 1.0 0
 */
/*
 * Plugin Name: ALiEMU Course Grid
 * Plugin URI: http://www.learndash.com
 * Description: ALiEMU LearnDash Course Grid Add-on
 * Version: 1.0
 * Author: Chris Gaafary
 * Author URI: http://www.aliemu.com
 */

add_action("plugins_loaded", "learndash_course_grid_localize");
function learndash_course_grid_localize() {
	load_plugin_textdomain( 'learndash_course_grid', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
}


add_filter("the_content", "learndash_course_grid_css");
function learndash_course_grid_css($content) {
	if(strpos($content, "[ld_course_list") === false) {
		return $content;
	}

	wp_enqueue_style( 'learndash_course_grid_css', plugins_url( 'style.css', __FILE__ ) );
	return str_replace("[ld_course_list", "<div id='ld_course_list'>[ld_course_list", $content);
}


add_filter( 'learndash_template', 'learndash_course_grid_course_list', 99, 5);
function learndash_course_grid_course_list($filepath, $name, $args, $echo, $return_file_path) {
	if($name == "course_list_template") {
		return dirname(__FILE__)."/course_list_template.php";
	}
	return $filepath;
}


function learndash_course_grid_course_list_ending($output) {
	return $output."</div><br style='clear:both'>";
}
add_filter("ld_course_list", "learndash_course_grid_course_list_ending",1, 1);


add_filter("learndash_post_args", "learndash_course_grid_post_args", 10, 1);

function learndash_course_grid_post_args($post_args) {
	foreach($post_args as $key => $post_arg) {
		if($post_arg["post_type"] == "sfwd-courses") {
			$course_short_description = array(
                                              'name' => __('Course Short Description', 'learndash_course_grid'),
                                              'type' => 'textarea',
                                              'help_text' => __('A short description of the course to show on course list generated by course list shortcode.', 'learndash_course_grid'),
                                            );
			$post_args[$key]["fields"] = array("course_short_description" => $course_short_description) + $post_args[$key]["fields"];
		}
	}
	return $post_args;
}
```

### After

```php
<?php
/**
 * @version 1.0 0
 */
/*
 * Plugin Name: ALiEMU Course Grid
 * Plugin URI: http://www.learndash.com
 * Description: ALiEMU LearnDash Course Grid Add-on
 * Version: 1.0
 * Author: Chris Gaafary
 * Author URI: http://www.aliemu.com
 */

add_action('plugins_loaded', 'learndash_course_grid_localize');
function learndash_course_grid_localize()
{
    load_plugin_textdomain('learndash_course_grid', false, dirname(plugin_basename(__FILE__)).'/languages/');
}

add_filter('the_content', 'learndash_course_grid_css');
function learndash_course_grid_css($content)
{
    if (strpos($content, '[ld_course_list') === false) {
        return $content;
    }

    wp_enqueue_style('learndash_course_grid_css', plugins_url('style.css', __FILE__));

    return str_replace('[ld_course_list', "<div id='ld_course_list'>[ld_course_list", $content);
}

add_filter('learndash_template', 'learndash_course_grid_course_list', 99, 5);
function learndash_course_grid_course_list($filepath, $name, $args, $echo, $return_file_path)
{
    if ($name == 'course_list_template') {
        return dirname(__FILE__).'/course_list_template.php';
    }

    return $filepath;
}

function learndash_course_grid_course_list_ending($output)
{
    return $output."</div><br style='clear:both'>";
}
add_filter('ld_course_list', 'learndash_course_grid_course_list_ending', 1, 1);

add_filter('learndash_post_args', 'learndash_course_grid_post_args', 10, 1);

function learndash_course_grid_post_args($post_args)
{
    foreach ($post_args as $key => $post_arg) {
        if ($post_arg['post_type'] == 'sfwd-courses') {
            $course_short_description = array(
                                              'name' => __('Course Short Description', 'learndash_course_grid'),
                                              'type' => 'textarea',
                                              'help_text' => __('A short description of the course to show on course list generated by course list shortcode.', 'learndash_course_grid'),
                                            );
            $post_args[$key]['fields'] = array('course_short_description' => $course_short_description) + $post_args[$key]['fields'];
        }
    }

    return $post_args;
}
```
---------

I attempted to run `beautify editor contents` without selecting anything to beautify the entire file and the same issue occurred (menu flashed for a split second and nothing happened).

Let me know if there's anything else I can provide.

**Comment by Glavin001** [comment]
What command did you run to obtain those results? Maybe the command generated by Atom Beautify is incorrect.

From your debugging logs, Atom Beautify ran:

> spawn D:\Shell\php\php.EXE 0=C:\Users\dsifford\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT, 1=fix, 2=C:\Users\dsifford\AppData\Local\Temp\temp1151018-12140-1fwjbxn

So could you try something like:

`D:\Shell\php\php.EXE C:\Users\dsifford\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.BAT fix YOURFILEPATH`

**Comment by dsifford** [comment]
Looking at the command generated by Atom Beautify I can see that it's incorrect. There should not be a call to `php.exe` before `php-cs-fixer.bat` -- Doing so results in an error.

Good catch!

**Comment by Glavin001** [comment]
Could you set the `PHP-CS-Fixer Path` option to the absolute path to your PHP-CS-Fixer's PHP script. See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php---php-cs-fixer-path for details.

Applicable Atom Beautify code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L20-L36

**Comment by dsifford** [comment]
Found the issue... There is more than one location (on windows systems) where files named `php-cs-fixer` live. I tried the other file location (below) and it looks like it was the winner...

Correct path:
`C:\Users\<USERNAME>\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer\php-cs-fixer`


Incorrect path:
`C:\Users\<USERNAME>\AppData\Roaming\Composer\vendor\bin\php-cs-fixer`

**Comment by Glavin001** [comment]
You're welcome. Glad to see it is working for you now.

**Comment by thatdoorsajar** [comment]
This should be in the documentation maybe!? It took me an hour to debug this. Works perfectly after though. Great atom package.
