### ISSUE TITLE
Uncaught TypeError: document.querySelector(...).appendLeft is not a function

### ISSUE THREAD

**Issue by abbas133** [Glavin001/atom-beautify#672]
Steps to reproduce :

1. Open Atom.exe and wait for all loading to be done.

**Atom Version**: 1.2.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.19

### Stack Trace

Uncaught TypeError: document.querySelector(...).appendLeft is not a function

```
At /C:/Users/Fazle%20Abbas/.atom/packages/mavensmate-atom/lib/status-bar-view.coffee:60

TypeError: document.querySelector(...).appendLeft is not a function
    at StatusBarView.module.exports.StatusBarView.attach (C:\Users\Fazle Abbas\.atom\packages\mavensmate-atom\lib\status-bar-view.coffee:57:46)
    at StatusBarView.module.exports.StatusBarView.initialize (C:\Users\Fazle Abbas\.atom\packages\mavensmate-atom\lib\status-bar-view.coffee:28:8)
    at StatusBarView.View [as constructor] (C:\Users\Fazle Abbas\AppData\Local\atom\app-1.2.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new StatusBarView (C:\Users\Fazle Abbas\.atom\packages\mavensmate-atom\lib\status-bar-view.coffee:14:7)
    at C:\Users\Fazle Abbas\.atom\packages\mavensmate-atom\lib\mavensmate.coffee:78:36
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "atom-beautify": {
    "_analyticsUserId": "ed89105b-4168-4a9a-b7a0-59059efb9fcc",
    "css_align_assignments": true,
    "css_force_indentation": true
  }
}
```

### Installed Packages

```coffee
# User
highlight-line, v0.11.0
highlight-selected, v0.11.1
jshint, v1.8.3
MavensMate-Atom, v1.0.6
minimap, v4.16.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
pretty-json, v0.4.1
save-session, vundefined
tabs-to-spaces, v1.0.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
As the error indicates:

> At /C:/Users/Fazle%20Abbas/.atom/packages/mavensmate-atom/lib/status-bar-view.coffee:60

The error is with some other package called `mavensmate-atom`, not with Atom Beautify.

**Comment by abbas133** [comment]
@Glavin001 Sorry, did not read stack trace before logging this issue. Thanks for your time.

**Comment by Glavin001** [comment]
No worries. This is not the first time. @abbas133 if you could report to https://github.com/atom/atom that the error reports from Atom are being incorrectly detected at Atom Beautify instead of the correct packages. Thanks.
