### ISSUE TITLE
Ruby Beautify not working

### ISSUE THREAD

**Issue by glendonyeo** [Glavin001/atom-beautify#673]
I have installed ruby-beautify and rubocop at my computer. The beautification in process message shown but no changes on my code.

Below is the debug.Md for your reference.

https://gist.github.com/glendonyeo/827458294d72b26a4634

Notes : 
1. I have tried to run at command prompt using "ruby-beautify --overwrite 888.rb".
2. I am using windows 10 not sure whether it will cause this.

Thanks.

**Comment by Glavin001** [comment]
> 1. I have tried to run at command prompt using "ruby-beautify --overwrite 888.rb".

Does running `ruby-beautify` manually from command prompt work?

**Comment by glendonyeo** [comment]
Hi, 


Thanks for reply. 

Yes, it manage to update with --overwrite





—

**Comment by Glavin001** [comment]
Your debugging information says you are using rubocop:

```
spawn C:\Ruby22-x64\bin\rubocop.BAT 0=--auto-correct, 1=--config, 2=D:\glendon.yeo\AppData\Local\Temp\rubocop-config1151019-10052-1chjw1m, 3=D:\glendon.yeo\AppData\Local\Temp\temp1151019-10052-1f4firj
```

Could you manually test that `rubocop` works from command prompt?
See https://github.com/bbatsov/rubocop#basic-usage for details.

This is the `rubocop` beautifier in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/rubocop.coffee

This is the `ruby-beautify` beautifier in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/ruby-beautify.coffee

You can change your Ruby default beautifier with this option: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---ruby---default-beautifier

**Comment by glendonyeo** [comment]
My apologize on it.

After changed the default setting now it works.
Sorry as i cannot locate the ruby default previously.

Thanks for your help.

**Comment by Glavin001** [comment]
Not a problem. Glad to hear it is working for you now! Let me know if you have any more questions.
