### ISSUE TITLE
Ruby version/gemset support

### ISSUE THREAD

**Issue by kWhittington** [Glavin001/atom-beautify#677]
Hi,

Great tool, I've been using it for months. One of the recent updates now prevents atom-beautify from detecting my RVM environment on Beautify. My linter (linter-rubocop) is still successfully calling the correct rubocop version but atom-beautify's debug log reports it looking in my system default ruby + gemset.

Is there a way to specify the path to rubocop for atom-beautify or a method to make it .ruby-version and .ruby-gemset aware?

Thank you!

**Comment by Glavin001** [comment]
> Is there a way to specify the path to rubocop for atom-beautify or a method to make it .ruby-version and .ruby-gemset aware?

Interesting idea. I would be interested in reviewing a Pull Request with this functionality.
Here is the applicable code for the rubocop beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/rubocop.coffee

Please follow the contribution guidelines found at https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc specifically the part about running the Atom command `Atom Beautify: Help Debug Editor` and making the Gist. That information should help me help you debug this problem. Thanks.
