### ISSUE TITLE
Request: Leave JS Variable Whitespace

### ISSUE THREAD

**Issue by SKGrimes** [Glavin001/atom-beautify#680]
Hey Mate,

This package has been pretty helpful and I find it quite a bit better than what I was using before. That said, I write a lot of code in NodeJS. Maybe this is just a vanity request, but I often like to add custom styling for my variables. This does also seem to be fairly conventional across the community.

**Example**

This is how I lay out my variables. I have intentionally, done it sloppy for reference purposes.

```
var express =                                              require('express');
var path =                                                    require('path');
var logger =                                                require('morgan');
var cookieParser                =                    require('cookie-parser');
```

The above will be formatted into:

```
var express = require('express');
var path = require('path');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
```

If there was the ability to leave all whitespace between the declaration, and the closing `;`, it would be awesome.

**i.e**

Javascript - Leave Variable Declaration Whitespace

_All whitespace is left between declarations Const, Let, Var and their closing semi-colon_

```
const pi                     = 3.14;
let k  = 0;
var  cookieParser                                                           = require('cookie-parser');
```

All of the above would render exactly as typed, keeping whitespace between the declaration `let`, `const`, `var`, and their closing `;`, semi-colon.

Cheers.

edit: or if there were an ignore line similar to a markdown `pre` tag that would work the same way.

```
//::= ===================================================================
var express =                                              require('express');
var path =                                                    require('path');
var logger =                                                require('morgan');
var cookieParser                =                    require('cookie-parser');
// ==================================================================== =::
```

in the above example i was using the `=::` as close and `::=` as open, but a pre-tag type ignore case would do the job superbly as well.

Thanks.

**Comment by prettydiff** [comment]
Not quite the same thing, but what if there were an option to vertically align things, such as:

    var a = {
            cat                         : "meow",
            door                        : "brown",
            antidisestablishmentarianism: "long word"
        },
        cat                          = "meow",
        door                         = "brown",
        antidisestablishmentarianism = "long word"

And what if this option were applied to all of the following:

* consecutive assignments
* object literal properties
* comma separated variable lists

Would this be close enough to what you want?

**Comment by prettydiff** [comment]
Closing as this issue is stale and fixed on the Pretty Diff side.  If there is additional work to be done please reopen the issue.
