### ISSUE TITLE
Installing “atom-beautify@0.28.19” failed

### ISSUE THREAD

**Issue by dessant** [Glavin001/atom-beautify#681]
```
Installing “atom-beautify@0.28.19” failed.

> spawn-sync@1.0.14 postinstall C:\Users\prc\AppData\Local\Temp\apm-install-dir-1151022-4152-1m7bxqg\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall


'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\prc\\AppData\\Local\\atom\\app-1.2.3\\resources\\app\\apm\\bin\\node.exe" "c:\\Users\\prc\\AppData\\Local\\atom\\app-1.2.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\prc\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\prc\\.atom\\.apmrc" "install" "C:\\Users\\prc\\AppData\\Local\\Temp\\d-1151022-4152-1oo8plx\\package.tgz" "--target=0.34.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.14 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.14 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
```

**Comment by andrewjanke** [comment]
Same here except I get:

Installing “atom-beautify@0.28.19” failed.Hide output…


events.js:72
        throw er; // Unhandled 'error' event
              ^

Error: ENOENT, open '/home/rotor/.atom/packages/atom-beautify/spec/atom-beautify-spec.coffee'

Ubuntu 15.10, atom 1.2.4

**Comment by vkbansal** [comment]
I too am having problem with install.

Windows 10, atom 1.2.4

```
> apm install atom-beautify
Installing atom-beautify to C:\Users\VivekKumar\.atom\packages failed

> spawn-sync@1.0.13 postinstall C:\Users\VIVEKK~1\AppData\Local\Temp\apm-install-dir-115116-4684-su28sn\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
'C:\Users\VivekKumar\.atom\.node-gyp\cmd-alias.bat' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\VivekKumar\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\VivekKumar\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\VivekKumar\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\VivekKumar\\.atom\\.apmrc" "install" "C:\\Users\\VIVEKK~1\\AppData\\Local\\Temp\\d-115116-4684-x8z5gg\\package.tgz" "--target=0.34.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
```

**Comment by Glavin001** [comment]
I'd recommend looking at the other duplicate issues: https://github.com/Glavin001/atom-beautify/search?q=node+postinstall&type=Issues&utf8=%E2%9C%93

This issue is with the `spawn-sync` package. Looks like this has been discussed here: https://github.com/ForbesLindesay/spawn-sync/issues/28

**Comment by dessant** [comment]
@Glavin001, running atom as administrator on windows 10 while installing atom-beautify fixed the issue, you could add this to the readme.

**Comment by Glavin001** [comment]
Glad to hear it is working! I would be open to reviewing a Pull Request adding to the README the steps that worked for you. Thanks!

**Comment by swatisabharwal** [comment]
Is there any other way through which I can format the code automatically in Atom?

**Comment by kofimokome** [comment]
Please how can I fix the problem on ubuntu?

**Comment by TilakMaddy** [comment]
I'm getting the same error on Windows too 

`Installing atom-beautify@0.29.13 to C:\Users\Chintu\.atom\packages failed

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN engine remark@6.2.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.
13.3"})
npm WARN engine typescript-formatter@2.3.0: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10
.40","npm":"2.13.3"})
npm WARN engine remark-parse@2.3.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","np
m":"2.13.3"})
npm WARN engine unified@5.1.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2
.13.3"})
npm WARN engine remark-stringify@2.4.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40"
,"npm":"2.13.3"})
npm WARN engine pad@1.1.0: wanted: {"node":">= 4.0.0"} (current: {"node":"0.10.40","npm":"2.13.
3"})
npm WARN engine trough@1.0.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.
13.3"})
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"2.13
.3"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"nod
e":"0.10.40","npm":"2.13.3"})
npm WARN engine markdown-table@1.1.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","
npm":"2.13.3"})
npm WARN engine glob-expand@0.2.1: wanted: {"node":">0.10"} (current: {"node":"0.10.40","npm":"
2.13.3"})
npm WARN engine array-iterate@1.1.0: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","n
pm":"2.13.3"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a Reg
Exp DoS issue
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"
2.13.3"})
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"
2.13.3"})
npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3
"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.1
3.3"})
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a Reg
Exp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3
"})
npm WARN engine resolve-from@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2
.13.3"})
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\htmlparser2\3.8.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\minimatch\3.0.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\chalk\1.1.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cli-table\0.3.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\strip-json-comments\1.0.4\package.tg
z
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\typescript\1.8.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\minimatch\3.0.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\jsonlint\1.6.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\typescript\1.8.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\pathval\0.1.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\3.10.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\reserved-words\0.1.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ini\1.3.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\js-yaml\3.4.6\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\handlebars\4.0.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\vow-fs\0.3.6\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\xmlbuilder\3.1.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\vow\0.4.16\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\estraverse\4.2.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prompt\0.2.14\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\minimist\0.0.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\strip-json-comments\1.0.4\package.tg
z
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\typescript\1.8.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\estraverse\4.2.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\jscs-preset-wikimedia\1.0.0\package.
tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\gherkin\2.12.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\typescript\1.8.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cli-table\0.3.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\vow\0.4.16\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\handlebars\4.0.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\jscs-jsdoc\2.0.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\natural-compare\1.2.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\commander\2.9.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\glob\5.0.15\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\commander\2.9.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\typescript\1.8.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\gherkin\2.12.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prompt\0.2.14\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\xmlbuilder\3.1.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\estraverse\4.2.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\3.10.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\minimist\0.0.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\js-yaml\3.4.6\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\jscs-jsdoc\2.0.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\commander\2.9.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\estraverse\4.2.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\glob\5.0.15\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\3.10.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\handlebars\4.0.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\xmlbuilder\3.1.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\es5-ext\0.10.21\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\minimist\0.0.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\commander\2.9.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\jscs-preset-wikimedia\1.0.0\package.
tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\xmlbuilder\3.1.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\handlebars\4.0.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\glob\5.0.15\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\glob\5.0.15\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\glob\5.0.15\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\handlebars\4.0.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\handlebars\4.0.10\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\jscs-preset-wikimedia\1.0.0\package.
tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\minimist\0.0.8\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Chintu\\AppData\\Local\\atom\\app-1.7.4\\resources\\app\\apm\\bin\\no
de.exe" "C:\\Users\\Chintu\\AppData\\Local\\atom\\app-1.7.4\\resources\\app\\apm\\node_modules\
\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Chintu\\.atom\\.apm\\.apmrc" "--userconfig"
 "C:\\Users\\Chintu\\.atom\\.apmrc" "install" "C:\\Users\\Chintu\\AppData\\Local\\Temp\\d-11742
9-5736-9upiuz\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ENOSPC
npm ERR! errno 54

npm ERR! nospc ENOSPC, write
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\prettydiff\1.16.37\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\cst\0.4.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.13.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\exit\0.1.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\ajv\4.11.8\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\marko\4.4.5\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\resolve\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Chintu\.atom\.apm\lodash\4.17.4\package.tgz
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\Chintu\AppData\Local\Temp\apm-instal
l-dir-117429-5736-ih4erw\node_modules\atom-beautify\node_modules\js-beautify\node_modules\mkdir
p\node_modules\minimist\test\default_bool.js'
npm ERR! error rolling back  { [Error: EPERM, unlink 'C:\Users\Chintu\AppData\Local\Temp\apm-in
stall-dir-117429-5736-ih4erw\node_modules\atom-beautify\node_modules\js-beautify\node_modules\m
kdirp\node_modules\minimist\test\default_bool.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\Chintu\\AppData\\Local\\Temp\\apm-install-dir-1
17429-5736-ih4erw\\node_modules\\atom-beautify\\node_modules\\js-beautify\\node_modules\\mkdirp
\\node_modules\\minimist\\test\\default_bool.js' }
`
