### ISSUE TITLE
Ruby Beautify Empty whole file

### ISSUE THREAD

**Issue by jinwen95** [Glavin001/atom-beautify#684]
HI,

I have issues with beautifying ruby file using ruby-beautify. I able to beautify the file through terminal, but when i try to beautify by using atom-beautify, the content of my ruby file become empty. Currently only found out the issues with ruby.

Environment ： Ubuntu 11.04 TLS

Link below is the debug log for your reference.
https://gist.github.com/jinwen95/698a5d707f5c76126b1a

Thanks.

**Comment by Glavin001** [comment]
> I able to beautify the file through terminal

Could you compare the command that you used manually in your Terminal to the command generated by Atom Beautify as shown from your debugging logs:

>  2015-11-26T02:52:20.707Z - debug: [beautifiers/beautifier.coffee] spawn /home/jinwen/.rbenv/shims/rbeautify 0=--spaces, 1=--indent_count, 2=2, 3=/tmp/input1151026-2386-1j8lquz

Atom Beautify ruby-beautify command:

```
/home/jinwen/.rbenv/shims/rbeautify --spaces --indent_count 2 <FILEPATH>
```

**Comment by jinwen95** [comment]
Hi,

It work perfectly.

ruby --overwrite --spaces --indent_count 2 test.rb

Thanks.

**Comment by Glavin001** [comment]
There could be a problem with the command at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/ruby-beautify.coffee#L18-L21

What does using the following give you in the Terminal:

```
rbeautify --spaces --indent_count 2 test.rb
```

It should output your beautified code to stdout.
If not, I recommend opening an issue at https://github.com/erniebrodeur/ruby-beautify to figure out why it does not output to stdout as expected, which would cause this problem (empty beautified result).

I recommend switching to Rubocop (which should be default). See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---ruby---default-beautifier for details on how to change your default Ruby beautifier.
See https://github.com/bbatsov/rubocop for Rubocop details.
