### ISSUE TITLE
In Windows node js dependency is a undeleteable

### ISSUE THREAD

**Issue by abhiesa-tolexo** [Glavin001/atom-beautify#685]
NodeJS dependency nightmare: example library path from my machine:   `is_buffer is required by kind-of, kind-of required by align-text, center-align and right-align requires align-text,  center-align and right-align require by cliui, cliui required by yargs, yargs requred by defs, defs required by regenerator, regenartor required by pac-resolver, pac-resolver required by pac-proxy-agent, pac-proxy-agent required by pac-agent, pac-agent required by superagent-proxy, superagent-proxy required by analyitics-node, and so on...` and for every dependency, browser tree has 2 directory, actual library and node_modeules. Now, curious situation arises, when i want to to delete the directory and os is not letting me, as path is too long for it to actually understand.

**Comment by prettydiff** [comment]
The `node_modules` directory comes from NPM, and as of v3 NPM performs dependency normalization and flattening.  In this case you get a big fat directory with a whole huge ton of dependencies, which is still better than having all those dependencies in various locations often repeated as dependencies of dependencies.

**Comment by vmuriart** [comment]
Had the same issue, and i think it was also breaking my atom updater. 
[this](http://stackoverflow.com/a/3887659/5208670) solution worked for me to delete the folders.

**Comment by prettydiff** [comment]
I believe this problem is no longer relevant.  If I am closing this issue prematurely please reopen it.
