### ISSUE TITLE
Could not find 'rubocop'. The program may not be installed

### ISSUE THREAD

**Issue by martin-jamszolik** [Glavin001/atom-beautify#689]
Hi 
Just tried the atom-beautify plugin and found myself stuck while trying to format ruby file.
It is not obvious to me how to install this rubocop dependency as part of the plugin. Frankly I just don't think a user should be settled with this burden.  

In the settings it shows Ruby as selected with a bullet point saying Requires Ruby Beautify, which seems to be an actual ruby gem.  Really?  That's not gonna work for a non hard core or casual user!

**Comment by aried3r** [comment]
Please see https://github.com/Glavin001/atom-beautify/pull/676

**Comment by Glavin001** [comment]
> Frankly I just don't think a user should be settled with this burden [of installing rubocop dependency].
> In the settings it shows Ruby as selected with a bullet point saying Requires Ruby Beautify, which seems to be an actual ruby gem. Really? That's not gonna work for a non hard core or casual user!

I recommend that you read https://github.com/Glavin001/atom-beautify/issues/396#issuecomment-111545914 which was a discussion on a similar statement.

After you have installed the required third-party Ruby beautifier, either [Rubocop](https://github.com/bbatsov/rubocop) or [Ruby-Beautify](https://github.com/erniebrodeur/ruby-beautify), if you are still having troubles, please feel free to create an issue following the contribution guidelines found at https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc so someone can help you get everything setup.

Many of the languages that Atom Beautify support use beautifiers written in JavaScript/Node.js and therefore require no additional installation and configuration on your part. Some of the supported beautifiers that exist for certain languages are not in JavaScript/Node.js and instead often written in the same language -- Ruby beautifier Rubocop is written in Ruby. It is then expected that a Ruby developer writing Ruby code should be able to install a Ruby beautifier, such as Rubocop or Ruby Beautify, which is also written in Ruby. It would then be up to the beautifier's project maintainer to ensure the installation process is straightforward, such as installing with Ruby gem. I am not a Ruby developer, so I cannot comment on the ease-of-use of Ruby gem for installing dependencies. There are tests passing for Ruby beautification using Rubocop and you can see how Travis CI installs rubocop here: https://github.com/Glavin001/atom-beautify/blob/master/.travis.yml#L36-L38

If someone would like to re-implement and maintain a beautifier, such as Rubocop, in JavaScript/Node.js and publish to [npm](https://www.npmjs.com/) then I would be more than happy to add support for it in Atom Beautify, and then deprecate the third-party dependencies that are not written in JavaScript/Node.js such as Rubocop. Thanks!

**Comment by martin-jamszolik** [comment]
Thank you for clarification.  Indeed it's admirable that you are trying to support these options despite the 3rd party dependencies.  I understand, I would suggest as far as to removing these options if its not native JavaScript/node.js. 

Also food for thought I was seeking this plugin only for a general ability to format indentation on all the code blocks.  I was expecting to find this capability quite common. So some level of formatting should not be hindered by deep integration with the language syntax.  What do you think?

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by jaychu28** [comment]
gem install rubocop
