### ISSUE TITLE
How to turn off space between function and opening bracket?

### ISSUE THREAD

**Issue by vorou** [Glavin001/atom-beautify#69]
Thanks for the great package!

In this code I don't want beautify to put a whitespace between `function` and `(`:

```
$(function () {
        var el = $('.l-mainMenu');
        if (el.length) {
            new NavigationView({
                el: el
            });
        }
    });
```

Didn't find the option, is it possible?

**Comment by craigotis** [comment]
Thanks for having this issue documented, just ran into the same problem.
