### ISSUE TITLE
How can I change indent_size for C++ from 8 to 4? 

### ISSUE THREAD

**Issue by morning-color** [Glavin001/atom-beautify#690]
When I attemped to beautify my c++ code, the default indent_size is 8, i want to change it to 4, how can I do it? My OS is Linux.

**Comment by Glavin001** [comment]
You could use [`Uncrustify`](http://uncrustify.sourceforge.net/). See documentation:
- https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---c---default-beautifier
- https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#c---config-path

**Comment by Glavin001** [comment]
Atom Beautify should also be able to generate an Uncrustify config file with https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/cfg.coffee
However there are currently no tests and I have not used it personally for a while, so not sure of its condition.

**Comment by morning-color** [comment]
OK, thank you.But it is a bit difficult for me, cause I am a beginner:joy:, but thanks a lot!

**Comment by Glavin001** [comment]
C++ support is something I definitely want to improve, including easier usage, improved documentation, and more supported options for configuration.
