### ISSUE TITLE
beautify py file why empty

### ISSUE THREAD

**Issue by Javacym** [Glavin001/atom-beautify#691]
I have already install pep8 and autopep8 ,and my atom-beautify version is 0.28.19.
when i beautify a py file,then i clean all,leaves a empty file,why?

**Comment by Glavin001** [comment]
Please follow https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc , specially providing a Gist with the results from running command `Atom Beautify: Help Debug Editor`.
