### ISSUE TITLE
Unable to install package on Linux

### ISSUE THREAD

**Issue by Kayoti** [Glavin001/atom-beautify#692]
I am unable to install the package using (apm install atom-beautify) the console freezes and I am also unable to install using atom gui.

**Comment by Glavin001** [comment]
Travis CI is passing and is Ubuntu (Linux): https://travis-ci.org/Glavin001/atom-beautify

Any errors for you?

**Comment by Kayoti** [comment]
No errors, I have bad internet and I am behind a company firewall that could explain why
