### ISSUE TITLE
Rails and PrettyDiff having a few oops.

### ISSUE THREAD

**Issue by kelvix** [Glavin001/atom-beautify#693]
[Debug Information](https://gist.github.com/kelvix/f179fa724cc71b6565a9)

    <div class="container">
      <% flash.each do | key, value | %>
        <div class="alert alert-"<%= key %>>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>

Seems like this is getting turned into

    <div % <% class="container" do flash.each key, value | |>
      <div % <%= class="alert alert-" key>>
        <%= value %>
      </div>
      <% end %>
      <%= yield %>
    </div>

Not exactly sure how pretty diff and atom-beautify coordinate their issues. I can go make an issue at pretty-diff if needed.

**Comment by Glavin001** [comment]
Yeah best to make an issue with those respective projects. Thanks.

**Comment by kelvix** [comment]
It's been a while... this is resolved in the latest version installed on my device.
