### ISSUE TITLE
newline_between_rules doesn't work on TSS

### ISSUE THREAD

**Issue by yomybaby** [Glavin001/atom-beautify#694]
Beautify is one of my favorite package. Thanks!

I had one problem using Beautify package.

After create `.jsbeautifyrc` in my home folder with below code,
- on css, new line remain after beautify (This is what I won't :smile:  )
- But on tss, new line be removed after beautify (Oh no~ :disappointed:  )

```
{
    "tss": {
        "newline_between_rules": true
    },
    "css": {
        "newline_between_rules": true
    }
}
```

How can I fix it?

**Comment by prettydiff** [comment]
Unless you have changed beautifiers in the settings Pretty Diff is the default beautifier for TSS.  I have attempted to reproduce this defect, but Pretty Diff appears to be working correctly.  I tested this at http://prettydiff.com/?m=beautify&l=tss

**Comment by yomybaby** [comment]
On prettydiff.com, new line between is remained. but on atom, it disappear.

I can reproduce by following below steps.

1. delete `atom-beautify` and reinstall `atom-beautify`
1. create .jsbeautifyrc on my home path : `~/.jsbeautifyrc ` and past below code
    ```
{
    "tss": {
        "newline_between_rules": true
    },
    "css": {
        "newline_between_rules": false
    }
}
    ```
1. relaunch atom
1. create any tss file : `app.tss`
1. open that file. and past below code to that file
    ```
 ".container": {
  backgroundColor: "white",
  
}



"Label": {
  width: Ti.UI.SIZE,
  height: Ti.UI.SIZE,
  color: "#000"
}

    ```
1. DO beautify (ctrl + alt + b)
1. **you can see the disappearing new line between rules**
1. If similar thing on css, new line is remained.

**Comment by prettydiff** [comment]
Closing this issue as it is stale and likely resolved.  If I am closing this issue prematurely please reopen it.
