### ISSUE TITLE
Add support for Clojure language

### ISSUE THREAD

**Issue by ghost** [Glavin001/atom-beautify#696]
This is https://github.com/bbatsov/clojure-style-guide#source-code-layout--organization
may help

**Comment by phreed** [comment]
This should also include beautification for https://github.com/edn-format/edn

**Comment by yochannah** [comment]
I would find this useful too. At the moment the main options for code clojure formatting are either parinfer or lisp-paredit, neither of which suits my purposes.

**Comment by pcwerk** [comment]
:+1: clojure support would be very nice.

**Comment by stil4m** [comment]
+1

**Comment by middlesphere** [comment]
waiting for clojure support

**Comment by MarcManhart** [comment]
+1
really need clojure support!

**Comment by shyblower** [comment]
+1

**Comment by kwladyka** [comment]
+1
It is last thing (i hope) what i need to use atom :)

**Comment by jonathan-chen-tda** [comment]
I'm still getting Could not find 'C:\Users\USER01.atom\packages\atom-beautify\node_modules.bin\cljfmt'. The program may not be installed.

Am I missing something or is this still a work in progress?

**Comment by Glavin001** [comment]
Closed by #1173.
Published to Published to v0.29.12

**Comment by Glavin001** [comment]
@jonathan-chen-tda I recommend creating a new Issue if you are still experiencing problems.
