### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by bobsilon** [Glavin001/atom-beautify#699]
**Update**
Sorry Duplicate For https://github.com/Glavin001/atom-beautify/issues/394 and https://github.com/Glavin001/atom-beautify/issues/508

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
