### ISSUE TITLE
Add braces option for Pretty Diff beautifier

### ISSUE THREAD

**Issue by lukassero** [Glavin001/atom-beautify#702]
it would be great if there was an option to put an opening curly bracket in a new line in .scss/.less/.css files, like so

```
.class
{
  ...

  .nested-class
  {
    ....

    &:after
    {
      ...
    }
  }
}
```

**Comment by jackywongcw** [comment]
Hi, @lukassero 

Have you found the solution for this? I've been searching and trying different ways, still unable to find the option. Have you found it? Can you kindly point me to the right direction?

**Comment by prettydiff** [comment]
The appropriate option is has been in Pretty Diff for quite a while now.  If this Pretty Diff option is not available in Atom Beautify then add it and submit a pull request.

**Comment by Glavin001** [comment]
I don't see the `braces` option for Pretty Diff beautifier in Atom-Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L10-L44

**Comment by Glavin001** [comment]
@lukassero and @jackywongcw please add a link to a Gist with your debugging information so we can help without guessing your configuration. Thanks!

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by szeck87** [comment]
For reference:  http://prettydiff.com/documentation.xhtml#braces
