### ISSUE TITLE
Beautifying not working 

### ISSUE THREAD

**Issue by Alex0007** [Glavin001/atom-beautify#703]
atom-beautify is installed http://i.imgur.com/QXkjk5e.png
but beautifing isn't working on any language
and there is no `Atom Beautify: Help Debug Editor` command available http://i.imgur.com/JfKEbaq.png

How can i fix this? Atom version is 1.4.0-beta0

**Comment by Glavin001** [comment]
This is weird. Maybe Atom 1.4.0-beta0 has a new CommandRegistry API? I only see 1.3.1 on list which shows the API Atom Beautify should be using currently: 
- https://atom.io/docs/api/v1.3.1/CommandRegistry
- https://atom.io/docs/api/v1.3.1/CommandRegistry

**Comment by Alex0007** [comment]
Rollback to stable worked

**Comment by prettydiff** [comment]
Closing as this issue is old.  If the problem is still present please reopen this issue.
