### ISSUE TITLE
Handlebars in <head> become inline

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#704]
When beautifying `.html` and `.hbs` (Mustache, Handlebars):

Expected behaviour:

``` html
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Brenndel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/brenndel.css">

    {{content-for 'head-footer'}}

  </head>
```

What happens instead:

``` html
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Brenndel</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">{{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/brenndel.css">{{content-for 'head-footer'}}

  </head>
```

Handlebars in `<head>` are common in Ember projects. In the `<body>` such Handlebars are formatted correctly. Please ask Mustache to update their beautifiers accordingly.

Gist: https://gist.github.com/janwerkhoven/776f9ba4be40663ede83

**Comment by prettydiff** [comment]
I suspected Pretty Diff would be the default beautifier for Handlebars, but I cannot reproduce this problem with Pretty Diff.

Current: http://prettydiff.com/?m=beautifyl=html
Beta: http://prettydiff.com/ignore/testlocation/index.xhtml?m=beautify&l=html

**Comment by janwerkhoven** [comment]
Good point, my setting for HTML was set to `JS Beautify`. I switched to `Pretty Diff` and it formats the HTML correctly :)

**Comment by prettydiff** [comment]
I am thinking this issue is resolved, but I am wrong please reopen this issue.
