### ISSUE TITLE
JSON tab length

### ISSUE THREAD

**Issue by Alex0007** [Glavin001/atom-beautify#705]
I set different tab length in JSON language package, but JS's tab length applied in beautifier. How can i set JSON tab length in GUI?

Debug info: http://pastebin.com/YMbANxdw

**Comment by NerdPad** [comment]
+1

**Comment by prettydiff** [comment]
Settings -> Packages -> Atom-Beautify

I don't see a setting for setting indentation size/type for JSON.  Try making the desired changes for JavaScript language and see if these apply for your JSON file.

**Comment by Alex0007** [comment]
It's applied, but i need different indents for them
