### ISSUE TITLE
Can't deal with XHTML5

### ISSUE THREAD

**Issue by garretwilson** [Glavin001/atom-beautify#706]
I'm using XHTML5, which for most practical purposes means HTML5 using the XML syntax---which again is pretty much HTML5 syntax except that it's stricter.

http://www.w3.org/TR/html5/introduction.html#html-vs-xhtml

I have a nice little XHTML5 document, starting with this:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
```

Unfortunately atom-beautify thinks that the XML declaration is a tag or something, and indents the entire document except for the first line!

```
<?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE html>
    <html lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
    ....
```

Please recognize the XML declaration in XHTML documents, and don't cause the entire documented because of this. Thanks.

**Comment by prettydiff** [comment]
JS Beautify is the default beautifier for HTML in Atom Beautify, which leaves you with two courses of action:

* Open an issue at https://github.com/beautify-web/js-beautify/issues
* In the Atom Beautify settings change your beautifier for HTML to use Pretty Diff.

**Comment by garretwilson** [comment]
> Open an issue at https://github.com/beautify-web/js-beautify/issues

[Done](https://github.com/beautify-web/js-beautify/issues/828).

**Comment by Glavin001** [comment]
> In the Atom Beautify settings change your beautifier for HTML to use Pretty Diff.

If your code beautifies properly over at http://prettydiff.com/ then I would say switiching to using Pretty Diff beautifier would be the best of the two choices :smile:. Give that a shot. Hope it works out.

**Comment by garretwilson** [comment]
@Glavin001 , Pretty Diff was Pretty Crappy. See #735.

So I'm stuck. Why can't we just fix JS Beautify to recognize XML declarations?

Saying that this is a third-party bug is taking the easy way out rather than trying to fix your tool. You could add some workaround code to detect the XML declaration, and after JS Beautify is ran simply go through each line in the buffer and remove the first tab.

**Comment by garretwilson** [comment]
I wanted to circle back and note that js-beautify finally fixed this issue in https://github.com/beautify-web/js-beautify/issues/828 . As that fix has since been integrated into atom-beautify, the issue has been resolved. I'll go head and close this one out.
