### ISSUE TITLE
Breaks content by wrapping in <pre> block

### ISSUE THREAD

**Issue by garretwilson** [Glavin001/atom-beautify#708]
js-beautify wraps lines inside a `<pre>` block. This 100% absolutely breaks my content and is a show-stopper. You cannot wrap lines inside a `<pre>` block, as this is **pre**formatted code.

I have [filed a bug](https://github.com/beautify-web/js-beautify/issues/830) with js-beautify, and I am making a note here so you can update to their latest version whenever they fix this show-stopper bug.

**Comment by Glavin001** [comment]
When js-beautify published their release you can uninstall and reinstall Atom Beautify to install a fresh and up-to-date copy of the dependencies, such as js-beautify. Hope they can help you out with your issue.

**Comment by romanseidl** [comment]
I wouldn't be too optimistic. They seem to not even see it as a bug. crazy.

**Comment by bitwiseman** [comment]
@romanseidl, I've updated the label be more descriptive.  I'm not getting a repro of this issue as you described it.  Perhaps @garretwilson could comment further? 

@Glavin001 - the code for preserving formatting in `<pre>` blocks hasn't changed in a while.  I'm not sure this is a js-beautify issue.

**Comment by romanseidl** [comment]
Seems that it is not?

**Comment by bitwiseman** [comment]
I cannot reproduce it on http://jsbeautifier.org/.  The website is not completely synchronized with the current release, but it doesn't look like the changes are ones that would have effected this.

**Comment by garretwilson** [comment]
I've been swamped with stuff, and now trying to address some more fundamental js-beautify problems, so I'm not even sure I could reproduce this offhand anyway. But I'll be on the lookout for this while I try to get back on top of things.

**Comment by prettydiff** [comment]
According to https://github.com/beautify-web/js-beautify/issues/830 this issue is complete.  That issue is remaining open until this one is closed, which means it is only awaiting publication of the next Atom Beautify version at which time both can close.

**Comment by Glavin001** [comment]
Uninstalling and reinstalling Atom Beautify will install the latest version of JS-Beautify (because of https://github.com/Glavin001/atom-beautify/blob/master/package.json#L87 ) and therefore should resolve this already fixed JS-Beautify isssue. Let me know if that does not work for anyone. Thank you.
