### ISSUE TITLE
Disable newline after comments?

### ISSUE THREAD

**Issue by crdil** [Glavin001/atom-beautify#709]
Just as the title says. How can I disable that newlines are added after comments when beautifying?
Thanks

**Comment by prettydiff** [comment]
What language?

**Comment by crdil** [comment]
CSS

**Comment by prettydiff** [comment]
In the atom-beautify settings there is an option labeled `CSS - Newline between rules`.  Try using that.

**Comment by Glavin001** [comment]
See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#css---newline-between-rules for more information.

**Comment by crdil** [comment]
I have that one disabled, but still newlines gets added after comments

**Comment by Glavin001** [comment]
Please follow guidelines for creating Issues: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Thanks.

**Comment by yhhwpp** [comment]
I've met the question as you too. set `Newline between rules` false not work

**Comment by prettydiff** [comment]
@yhhwpp Could you produce a debug.md file?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

This issue can be reopened once we have the appropriate information to help you.
