### ISSUE TITLE
Beautify settings UX

### ISSUE THREAD

**Issue by chschtsch** [Glavin001/atom-beautify#713]
Hello,

I like this plugin and find it really useful!

But as for me, the current state of settings is really messy. First, at the top you have a list of settings for every language. Not really categorized, "Language-Name - " prefixes are used instead of nice, clean sections:

![screen shot 2015-12-16 at 4 21 53 pm](https://cloud.githubusercontent.com/assets/6196182/11841907/4abebdb0-a411-11e5-9268-61cdcc48d919.png)

But then goes the worst part of UX: when you scroll down, you find another list of settings for every language again:

![screen shot 2015-12-16 at 4 22 11 pm](https://cloud.githubusercontent.com/assets/6196182/11841910/4c4b92f2-a411-11e5-8974-8b73227d3cf2.png)

Again, prefixes are used instead of sectioning.

Here are some ideas how to improve UX:
* make clean sections for every language, divided by headers with its name
* do either of:
  * merge all settings concerning one language into one section
  * make two main sections from what we have now

Please, tell me what you think about it. I really think that this nice plugin deserves a nicer look of settings.

I'm new to Atom plugins development, but I think I could create a pull request some time if nobody else would do that.

**Comment by prettydiff** [comment]
Would you be able to work up a quick visual comp?

**Comment by Glavin001** [comment]
@chschtsch does Atom's [settings view](https://github.com/atom/settings-view) API support sections?

If so, please submit a pull request. The applicable code can be found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L98 in the function `buildOptionsForBeautifiers`. Thanks.

**Comment by chschtsch** [comment]
@prettydiff, here you go:
![screen shot 2015-12-17 at 1 23 01 pm](https://cloud.githubusercontent.com/assets/6196182/11867431/04db1f4e-a4c2-11e5-8ffb-5ffc022e2f76.png)

@Glavin001, I understand your point, and it really sucks that there's not a plenty of possibilities in Atom (maybe it would be good to open an issue for that), but what do you think about what I did on the screenshot, using separate settings for every language? Is this posible/easy to implement? Check out preinstalled Atom packages `language-sass` or `language-c`, for example. They did the same thing (actually I took their html to compose my preview screenshot).

**Comment by Glavin001** [comment]
I really like the idea of organizing these settings better and your screenshot looks good. Unfortunately, I am doing my final exams and have big deadlines at work so it is unlikely I will have time to develop this improvement out for the next little while. I would appreciate a pull request. Let me know if you need any help. Thanks!

**Comment by SeriouslyAwesome** [comment]
Also, if possible, it would be great if the settings for languages that have been disabled were hidden or at least moved to a separate, collapsed section below the settings for languages that *are* enabled. I'm new to Atom, so I'm not sure if that's even possible, but it seems like it would also help simplify the UX here.

**Comment by danielbayley** [comment]
+1.

**Comment by Glavin001** [comment]
Everyone please subscribe to https://github.com/atom/settings-view/pull/736 and let them know that it is important to improve Settings View such that packages like Atom Beautify can organize the options to make it easier for users.

**Comment by Glavin001** [comment]
https://github.com/atom/settings-view/pull/736 has been merged! Once they publish the update this week then I will update Atom Beautify to utilize this feature. Unfortunately, it will be a breaking change to the package settings.
