### ISSUE TITLE
Spawning the process - Having error after uninstalling fish shell

### ISSUE THREAD

**Issue by mahdavipanah** [Glavin001/atom-beautify#714]
I installed atom-beautify and uncrustify when I was using [fish shell](http://fishshell.com/).
I have uninstalled fish shell and now I am using bash (/bin/bash). After uninstalling fish shell when I try to beautify C codes, I get below error messages.
And even when I try to run the command `Atom Beautify: Help Debug Editor`, same thing happens.

![atom-beautify](https://cloud.githubusercontent.com/assets/1397846/11849386/d4d95dcc-a43c-11e5-8eb5-b93f6a9ab374.png)

![atom-beautify](https://cloud.githubusercontent.com/assets/1397846/11849377/c850784c-a43c-11e5-8ec7-9a1b28670cd4.png)

**Comment by enuzzo** [comment]
Same problem here, with php files.
I also uninstalled fish. Using bash as default now. Nothing changes.
![screen shot 2017-02-10 at 14 07 52](https://cloud.githubusercontent.com/assets/3628008/22827885/6da08a9a-ef9a-11e6-90d8-535bd32546a7.jpg)
