### ISSUE TITLE
Switch to JavaScript (ES6) from CoffeeScript

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#716]

**Comment by bziemons** [comment]
Just out of curiosity: why would you like to move away from CoffeeScript?

**Comment by Glavin001** [comment]
I'm doing this now before we write more CoffeeScript and accrue more technical debt.

**Comment by Glavin001** [comment]
Upgrade the Beautifiers to use static member properties: https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Cstage-1&code=class%20MyClass%20%7B%0A%20%20myProp%20%3D%2042%3B%0A%20%20static%20myStaticProp%20%3D%2021%3B%0A%0A%20%20constructor()%20%7B%0A%20%20%20%20console.log(this.myProp)%3B%20%2F%2F%20Prints%20'42'%0A%20%20%20%20console.log(this.constructor.myStaticProp)%3B%0A%20%20%20%20console.log(MyClass.myStaticProp)%3B%20%2F%2F%20Prints%20'21'%0A%20%20%7D%0A%7D%0A%0Alet%20c1%20%3D%20new%20MyClass()%3B%0A%2F%2Fc1.initialize()%3B%0A%0Aclass%20MyClass2%20extends%20MyClass%20%7B%0A%20%20myProp%20%3D%2024%3B%0A%20%20static%20myStaticProp%20%3D%20%7B222%3A23%7D%3B%0A%0A%7D%0A%0Alet%20c2%20%3D%20new%20MyClass2()%3B%0A%2F%2Fc2.initialize()%3B%0A

```javascript
class MyClass {
  myProp = 42;
  static myStaticProp = 21;

  constructor() {
    console.log(this.myProp); // Prints '42'
    console.log(this.constructor.myStaticProp);
    console.log(MyClass.myStaticProp); // Prints '21'
  }
}

let c1 = new MyClass();
//c1.initialize();

class MyClass2 extends MyClass {
  myProp = 24;
  static myStaticProp = {222:23};

}

let c2 = new MyClass2();
//c2.initialize();
```

**Comment by Glavin001** [comment]
I started converting the existing code base from CoffeeScript into ES6, however given the features I want to support for Atom-Beautify v1, it may end up simply being a complete rewrite.

**Comment by Glavin001** [comment]
Atom-Beautify will be completely rewritten in TypeScript. Work has started: https://github.com/Unibeautify/unibeautify
