### ISSUE TITLE
JS arrays of objects doesn't fold properly after beautification

### ISSUE THREAD

**Issue by aspin** [Glavin001/atom-beautify#719]
e.g. beautification creates this:

``` js
var array = [{
    property: 'blah',
}, {
    property: 'blah2',
}];
```

which folds to

``` js
var array = [{ ...
    property: 'blah2'
}];
```

I don't really have a great suggestion for a fix or anything, but I think this behavior is undesirable?

**Comment by prettydiff** [comment]
The fold feature is not associated with atom-beautify.  It is kind of frustrating but you would have fold first from the second object (that starts on the third line) then when you fold from the first line the entire thing is folded.

**Comment by Glavin001** [comment]
Please follow https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc when reporting Issues. Thanks.
