### ISSUE TITLE
Fails on SCSS file

### ISSUE THREAD

**Issue by lombardi-gux** [Glavin001/atom-beautify#72]
Tried to run "beautify" on a fairly simple SCSS file: http://cl.ly/code/4201472J3l2F/kendoui.scss

![screen shot 2014-09-02 at 1 33 25 pm](https://cloud.githubusercontent.com/assets/7459986/4122699/3d70a7ca-32c7-11e4-909b-e472fd0283ae.png)

**Comment by Glavin001** [comment]
Check if this works now and add it as a SCSS test.

**Comment by Glavin001** [comment]
I was unable to reproduce. It's likely been fixed a while ago then in some third-party dependency.
