### ISSUE TITLE
Not working for python (autopep8 error)

### ISSUE THREAD

**Issue by revernus** [Glavin001/atom-beautify#728]
Whenever I try to use beautify, it raises an error related to autopep8 usage:

Usage: autopep8 [options] [filename [filename ...]] Use filename '-' for stdin.
autopep8: error: no such option: --indent-size

Here is a printscreen: http://i.imgur.com/o8uGNNC.png

**Comment by Glavin001** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/419

Updating `autopep8` should resolve this issue.

**Comment by revernus** [comment]
It should be updated to which version? I have version 0.9.1 installed.

**Comment by Glavin001** [comment]
> It should be updated to which version? I have version 0.9.1 installed.

Version 1.5.7

See https://github.com/Glavin001/atom-beautify/issues/419#issuecomment-115438486
