### ISSUE TITLE
Sass not compiling correctly due to delay of beautify with Codekit/Prepros

### ISSUE THREAD

**Issue by paperrobots** [Glavin001/atom-beautify#729]
Curious if anyone else has experienced this. When compiling SASS with Codekit or Prepros sometimes my CSS files are incomplete or blank. So when the page auto refreshes all my styles are gone. Sometimes I have to re-save the SASS file upwards of 10 times before it recompiles correctly. I'm not getting any errors from Codekit. It just seems like it's picking up on a file change before atom beautify has finished doing it's thing. I haven't tried it with compiling via the command line yet, I will do some testing on that later today. Any ideas what might be going on? I love this friggin plugin and want to get it to work for me!

**Comment by prettydiff** [comment]
I thinking this is probably a Codekit defect.  This is an Atom Beautify defect only if Codekit produces a result that is not being applied by Atom Beautify.  If you open a defect with Codekit please link to that issue in a comment here so that we can track it and evaluate the progress towards resolution.

**Comment by paperrobots** [comment]
Well it happens with not just Codekit though. Happens with Prepros and when I'm using Gulp.

**Comment by prettydiff** [comment]
I would like to rule out Atom Beautify as a defect cause.  Could you please list some steps so that we can reproduce?  I would like to know how results from Codekit and Prepros are being fed into Atom.  We should also not rule out this being an Atom.io defect.

**Comment by paperrobots** [comment]
Well to me it seems like there's a delay for Atom Beautify to do it's thing. Sometimes taking it up to 5-10 seconds where Atom is frozen while that is happening. 

If it delays too long that's when it seems like my Sass compilers are detecting a file change before the file is completely done changing. Then I end up with a blank stylesheet.

**Comment by prettydiff** [comment]
In that case would be able to list steps so that we can reproduce?

**Comment by paperrobots** [comment]
I'm just editing my SCSS file as normal and hitting save. That's about it. Atom Beautify starts working. Sass compiler (Codekit/Prepros) detects a change and tries to compile. Successfully compiled message pops up. Refresh the browser and the styles are gone. So I just hit save a few more times in Atom until the styles finally compile correctly. Usually 3-4 times on average sometimes more. 

If there's a config file or something I could provide that might help just let me know.

**Comment by prettydiff** [comment]
This issue is old and is likely reflective a specific build cycle containing tools and steps outside of Atom Beautify.  Closing for now, but please feel free to reopen this issue if there is additional investigation we can assist with.
