### ISSUE TITLE
JS: ignore comments?

### ISSUE THREAD

**Issue by Christilut** [Glavin001/atom-beautify#730]
Hi,

I've got code like this:
```js
    /**
     * @class MyClass
     */
    can.Control.extend('MyClass',
        /** @Static */
        {
            defaults : {
                template: "/path/to/template",
                message: "test"
            }
        },
        /** @Prototype */
        {
            init : function () {   }
        });
```
but it gets formatted to this:
```js
        /**
         * @class MyClass
         */
          
        can.Control.extend('MyClass',    /** @Static */      {      
            defaults: {
                template: "/path/to/template",
                message: "test"
            }    
        },      /** @Prototype */      {      
            init: function() {   }    
        });
```

How do I manage to get the comments to stay on their own line? They should act as a separator between code.
Or is there another way to write comments here so this doesn't happen?

**Comment by prettydiff** [comment]
In version 28.19 I show a limited version of this defect when beautifying with Pretty Diff and no defect at all when beautifying with JS Beautify.  There is no defect at all in the latest versions of Pretty Diff and JS Beautify, using each beautifier's latest web tool.  I know I fixed this in Pretty Diff two updates ago.

I am updating to version 28.21 to see if the fix from Pretty Diff is in there.  If now then it will be in the very next release, or you can uninstall and reinstall Atom Beautify to get the latest versions of all dependencies and fix the problem immediately.

**Comment by rickysullivan** [comment]
Fixed for me.
