### ISSUE TITLE
Suggest configuration of options given expected beautifier output

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#737]
### Goal

Given an ugly / un-beautifier input and an expected beautified output, find the configuration for the options that achieves the closest expected result.
#### Ugly Input

``` javascript
function test() {
  console.log('hello world');
}
```
#### Expected Beautified Output

``` javascript
function test() {
    console.log('hello world');
}
```
#### Recommended Configuration

`indent_size: 4`

**Comment by yaykyle** [comment]
I like this idea!

**Comment by prettydiff** [comment]
Is this something like support for a collection of option configurations like a styleguide preference?

**Comment by Glavin001** [comment]
@prettydiff My goal here was to find the optimal configuration which achieves the closest beautified output text. Kind of like beautifier parameter optimization. I have yet to work on this. It will be a priority after Unibeautify.
