### ISSUE TITLE
Feature request: Groovy support

### ISSUE THREAD

**Issue by rbatllet** [Glavin001/atom-beautify#739]
Could you add support in the near future to the groovy language as well?

http://www.groovy-lang.org/documentation.html#languagespecification

Thank you!

**Comment by tobilarscheid** [comment]
Seems like a duplicate of https://github.com/Glavin001/atom-beautify/issues/371

**Comment by prettydiff** [comment]
Thanks @tobilarscheid 

Closing as this is a duplicate.
