### ISSUE TITLE
atom-beautify fails to install

### ISSUE THREAD

**Issue by citrusui** [Glavin001/atom-beautify#740]
Not only does it take *forever* to install, it sometimes just fails altogether. From the screenshot below, it looks like `node` is called (which isn't installed).

![beautify-fail](https://cloud.githubusercontent.com/assets/9056756/12265830/70fbfb1c-b90d-11e5-8033-5646067f32aa.png)

The output above also suggests spawn-sync@1.0.15 is to blame, but I'm not sure if that is the case.

Tested on Atom 1.3.3 and 1.4.0-beta3.

**Comment by matthewrose** [comment]
Also hanging/failing when installing from within the settings of the application.

**Comment by ryanwischkaemper** [comment]
I'm getting this same error on atom 1.5.4

**Comment by prettydiff** [comment]
Those are NPM errors, which indicates both Node and NPM are actually installed.  The error message indicates a failure at an NPM script for the install phase of package `spawn-sync` which is a dependency of `cross-spawn` which is a direct atom-beautify dependency.

@Glavin001 could we look up updating Node and NPM to the latest versions.  I think that would fix a lot of these stability issues, particularly on Windows.  This `spawn-sync` appears to have different behavior for this version of node according to its readme: https://www.npmjs.com/package/spawn-sync

**Comment by Glavin001** [comment]
I just published a patch in release v0.29.4 that makes `cross-spawn` dependency optional. 
The [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) package depends on [`spawn-sync`](https://github.com/ForbesLindesay/spawn-sync) and has been causing problems when installing Atom-Beautify for many users. By making this dependency optional, users will be able to easily install Atom-Beautify and, in the case that [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) fails to install, will fallback to the builtin [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) method.
