### ISSUE TITLE
Array reformat

### ISSUE THREAD

**Issue by dbroadhurst** [Glavin001/atom-beautify#741]
I'm trying to stop my array from being reformatted from

```
      var grid = [
        [],
        [{w: 1,h: 1}],
        [{w: 2,h: 1}, {w: 2,h: 1}],
]
```

to

```
      var grid = [
        [],
        [{
            w: 1,
            h: 1
          }],
        [{
            w: 2,
            h: 1
          }, {
            w: 2,
            h: 1
          }],
```

Any ideas? I've tried "keep_array_indentation": true but no luck

**Comment by prettydiff** [comment]
This requested behavior is not present in either Pretty Diff or JS-Beautify.  This feature would have to be enabled through an option, which would be the only way to avoid massive regression.  It is more challenging than it appears due to various degrees of structure depth with potential for all kinds of strange side effects.

**Comment by dbroadhurst** [comment]
Thanks, is there anyway to mark the part of the source to not be reformatted?

**Comment by prettydiff** [comment]
Not that I am aware of because deep data structures like that can occur in a variety of locations.

**Comment by prettydiff** [comment]
Pretty Diff can achieve this with the options `formatArray: "inline", formatObject: "inline"`.  These options might need to be added to Atom Beautify though.

**Comment by marcelbraun1985** [comment]
hi,

i tried alot but nothing works!

This ...
`{%  if key not in ['id', 'slug', 'datecreated', 'datechanged', 'datepublish', 'username', 'status', 'title', 'subtitle'] %}`

will be reformated to:
```
{% if key not in[
            'id',
            'slug',
            'datecreated',
            'datechanged',
            'datepublish',
            'username',
            'status',
            'title',
            'subtitle'
] %}
```

Then i get a syntax error. I tried to configure the behavior with .jsbeautifyrc but `formatArray: "inline", formatObject: "inline"` doesn't work and the official doku have not these option.

Any idea?


Thanks
