### ISSUE TITLE
react-native files jsx code ~ bad format

### ISSUE THREAD

**Issue by TOP-Chao** [Glavin001/atom-beautify#742]
```javascript
class weeweefree extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}
```
beautify to

```javascript
class weeweefree extends Component {
    render() {
        return ( < View style = {
                styles.container
            } >
            < Text style = {
                styles.welcome
            } >
            Welcome to React Native!
            < /Text> < Text style = {
                styles.instructions
            } >
            To get started, edit index.ios.js < /Text> < Text style = {
                styles.instructions
            } >
            Press Cmd + R to reload, {
                '\n'
            }
            Cmd + D or shake
            for dev menu < /Text> < /View>
        );
    }
}
```
indent size = 4 
so bad. How do I need to setting?

**Comment by prettydiff** [comment]
The code is beautified as JavaScript and not JSX.  Are you using `.js` for your file extension instead of `.jsx`?  Pretty Diff is the default beautifier for JSX in Atom Beautify and it appears to be working when I process the sample code at http://prettydiff.com/?m=beautify&l=jsx

**Comment by TOP-Chao** [comment]
That's right. The file suffix is `.js`. But I would like to know the.Js file also supports JSX beautifier how to set up

**Comment by prettydiff** [comment]
I am not sure how to make the code beautify as JSX with a `.js` file extension.  Maybe @Glavin001 would have some additional information.  Saving the file as `.jsx` would solve this problem though.

**Comment by Glavin001** [comment]
The Atom file grammar takes precedence over file extension. If you want to use extension `.js` and be recognized as `JSX` then you should change your file's grammar within Atom. 
See https://github.com/atom/grammar-selector for details.

**Comment by prettydiff** [comment]
@Glavin001 I looked, but did not see an Atom grammar for JSX format.

**Comment by Glavin001** [comment]
It wouldn't be built-in to Atom, you will likely have to install a package. This one adds `JSX` grammar: https://github.com/Icehunter/language-jsx/blob/master/grammars/jsx.cson#L7

This one won't work because the grammar name is different: https://github.com/subtleGradient/language-javascript-jsx/blob/master/grammars/JavaScript%20with%20JSX.cson#L7
So that could be added support for with a pull request changing  https://github.com/Glavin001/atom-beautify/blob/master/src/languages/jsx.coffee#L10-L13

**Comment by TOP-Chao** [comment]
@Glavin001  @prettydiff  Thank you. The problem is solved.

**Comment by Glavin001** [comment]
Excellent to hear! You're very welcome. Enjoy!

**Comment by ewgenius** [comment]
@Glavin001 i have the same issue with `*.jsx` files. I've tryed [atom-react](https://github.com/orktes/atom-react) and [language-jsx](https://github.com/Icehunter/language-jsx) for grammars, but always same result, as in first message here:

```javascript
class Test extends React.Component {
				render() {
								return <div>
												test
								</div>
				}
}
```

Also, when i set file extension to `.js` and grammar to JavaScript, beautifier creates different result:

```javascript
class Chat extends React.Component {
	render() {
		return <div >
			chat < /div>
	}
}
```

**Comment by prettydiff** [comment]
@ewgenius The first result is demonstrating correct beautification and the second one is broken.  The only problem with the first code sample is the indentation is really big (16 spaces).  Have you changed any settings regarding beautification size or use of soft-tabs or anything like that?

**Comment by ewgenius** [comment]
@prettydiff oh, there was an `.editorconfig` file in my project with 'tab' seetting for identation, what i have not noticed, so there is no problem now. Thank you for your answer!

**Comment by niranjan-b-prajapati** [comment]
@TOP-Chao  can you please explain how did you solved your problem.

**Comment by anhldbk** [comment]
@niranjan-b-prajapati : Package `language-babel` does NOT compatible with my current version of Atom (1.12.2). I removed it and used package `react` instead. It works! Hope this will help you out.

**Comment by indivisable** [comment]
@anhldbk @TOP-Chao

Can anyone give full answer to this? Trying to use with react-native / react and not much luck.

So far I tried:

installed atom-beautify
installed language-jsx
installed file-types and configured as instructed above

*.js files are still being detected as JS and not JSX when I run beautify

**Comment by njwangchuan** [comment]
Thanks to @Glavin001 ! Just add these package to atom:

https://atom.io/packages/language-javascript-jsx

**Comment by mpathy** [comment]
@tayfunyasar then read the comments about the solution. it has some reason it is closed.

**Comment by tibistibi** [comment]
i had the same but could do two things: 
one is per file change what kind of file it  is (in the right bottom of the screen click file type and change it:
![image](https://user-images.githubusercontent.com/1875634/33223450-d43e8e62-d15f-11e7-943f-3e292aa1a584.png)

or change the format type of js files in the settings:
![image](https://user-images.githubusercontent.com/1875634/33223472-0d8b5e84-d160-11e7-9b78-913a26684dbc.png)
