### ISSUE TITLE
Could I set a supported beautifier to the file with customed file extension

### ISSUE THREAD

**Issue by Colin6618** [Glavin001/atom-beautify#746]
The case: there is an template engine named [xtemplate](https://github.com/xtemplate/xtemplate), the file extensioin is xtpl, (e.g. itemlist.xtpl ).
The atom could not determine a beautifier when i use beautifier.

i need the file been beautified by Html grammar basiclly.

 Could i add an rule in the beautify setting, e.g. xtpl => html. 

![image](https://cloud.githubusercontent.com/assets/3047309/12318136/f1c7e3fc-bad2-11e5-956e-a63ac581006c.png)

**Comment by prettydiff** [comment]
I opened a pull request to provide official support for this language.

**Comment by Glavin001** [comment]
Pull request has been merged and published.
