### ISSUE TITLE
Cannot use "~" in uncrustify config file-path

### ISSUE THREAD

**Issue by TheSlowGrowth** [Glavin001/atom-beautify#747]
I just installed atom-beautify and tried to use a custom uncrustify config located in my home directory. Typing "~/uncrustify.cfg" into "Settings panel" -> "C-Config Path" results in an error message that
_projectDirectory_/~/uncrustify.cfg" is not found.

Platform: OSX 10.11

**Comment by prettydiff** [comment]
@JohannesNeumann This sounds like a path resolution error from the `uncrustify` package.  Have you tried using an absolute path instead?  I would also recommend opening an issue with https://github.com/bengardner/uncrustify/issues

**Comment by JohannesNeumann** [comment]
Yes, absolute paths are fine. I'll open a ticket at uncrustify as well.

**Comment by chdsbd** [comment]
As mentioned, there is an issue with path resolution. But the issue lies with atom-beautify resolving the path correctly, not uncrustify, which just receives that mangled path.

FYI: The other issue posted on uncrustify was closed saying this was a problem on atom-beautify's end.
https://github.com/uncrustify/uncrustify/issues/426

**Comment by Glavin001** [comment]
I would agree that this could be an Atom-Beautify bug.

For those who are experiencing this issue please submit a pull request if you are able to resolve the issue.
I recommend looking at the applicable code found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L36-L41 and https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L48-L49

The original issue for this is https://github.com/Glavin001/atom-beautify/issues/235 and was implemented and closed with https://github.com/Glavin001/atom-beautify/commit/bc14c04f84d9af452d43c44de1573481c5cc4792

**Comment by gerritzen** [comment]
I have the same issue on openSUSE 42.1.
