### ISSUE TITLE
on use adds indent on every line in .css files

### ISSUE THREAD

**Issue by tstelzer** [Glavin001/atom-beautify#749]
So far happens only in css. Html seems to work for me, havent tried anything else.
The Code still gets beautified though, but it repeatedly adds indent, on every use.
See image for reference:
![broken](https://cloud.githubusercontent.com/assets/15860486/12342797/5e710e6a-bb2e-11e5-8638-db81e2c0c546.jpg)

Already tried:
disableing every other community package i am using
disableing / re-enableing 
un-install / install
manually deleting the package just in case

/edit
After manually removing the indents the behaviour has not reappeared. Can't seem to reproduce it again.

/edit2: a word

**Comment by prettydiff** [comment]
Is this problem happening in actual CSS language or something like LESS or SCSS?  Would you mind posting the code that caused the problem so that I can reproduce the issue.

**Comment by Zeit-Werk** [comment]
Pure CSS. I will check if I have a version of the bugged code in my repo.

**Comment by prettydiff** [comment]
There has been no movement on this issue in almost 2 years.  Please reopen this issue if you are able to reproduce the defect again.
