### ISSUE TITLE
Feature: Add support for Riot.js tag

### ISSUE THREAD

**Issue by rodrigorodriguez** [Glavin001/atom-beautify#750]
Add support for Riot.js tag files: .tag, grammar HTML (Riot Tag).

**Comment by prettydiff** [comment]
Duplicate https://github.com/Glavin001/atom-beautify/issues/731

This grammar appears to be supported by an included beautifier, so it just needs a pull request to associate `.tag` files with Pretty Diff beautifier.

**Comment by prettydiff** [comment]
This is just pending the next release.

**Comment by phillip-haydon** [comment]
Splooge! Hope new release is soooonnnnnn :D

**Comment by rodrigorodriguez** [comment]
@prettydiff  That's what I meant as I wrote 'HTML (Riot Tag)', that's the name of the grammar.

**Comment by Glavin001** [comment]
#766 has been merged.

**Comment by Glavin001** [comment]
Published to v0.28.28
