### ISSUE TITLE
comma before key: value pair in js

### ISSUE THREAD

**Issue by codelight89** [Glavin001/atom-beautify#751]
For example copy-pasted autogenerated options for spinner.js (http://fgnass.github.io/spin.js) :

```
var opts = {
    lines: 7 // The number of lines to draw
  , length: 20 // The length of each line
  , width: 19 // The line thickness
 }
```

beautify produces:

```
var opts = {
    lines: 7 // The number of lines to draw
        ,
    length: 20 // The length of each line
        ,
    width: 19 // The line thickness
}
```

Is it right way ...?

**Comment by prettydiff** [comment]
This is a defect in both JS Beautify and Pretty Diff.  I am working to resolve this on the Pretty Diff side right now.  I recommend opening an issue with: https://github.com/beautify-web/js-beautify/issues

**Comment by prettydiff** [comment]
This is resolved and published in Pretty Diff.  I am not sure yet the status on the JS Beautify side.  Were you able to open a bug with JS Beautify?

**Comment by prettydiff** [comment]
I just noticed this code sample breaks in the latest version of Pretty Diff due to the closing curly brace being sucked into the final comment.  I already have an issue open this: https://github.com/prettydiff/prettydiff/issues/496
