### ISSUE TITLE
PHP beautify: PHP-CS-Fixer not working

### ISSUE THREAD

**Issue by ihabovich** [Glavin001/atom-beautify#753]
I cannot use for PHP files since I always get the error message:
**Could not find 'php-cs-fixer'. The program may not be installed.**

Then I added PHP-CS-Fixer path where [php-cs-fixer.phar](https://github.com/FriendsOfPHP/PHP-CS-Fixer) file is being located and then gave a test to get alternative error message:
**Could not find 'php'. The program may not be installed.**

That all happens on Windows 10 OS while I was on Ubuntu I managed to install PHP-CS-Fixer successfully and everything was just fine.

I hope anyone could offer fix for this issue soon.

**Comment by superDuperCyberTechno** [comment]
Sounds like you need to install PHP: https://www.youtube.com/watch?v=6Y6lOHov3Bk

**Comment by ihabovich** [comment]
What that mean?, I use Wamp Server.

**Comment by superDuperCyberTechno** [comment]
If I'm right, you need to install PHP which makes Windows able to execute PHP programs. Using WAMP doesn't install PHP on Windows as you might think (as far as I know). The video should be pretty self-explanatory.

**Comment by ihabovich** [comment]
@superDuperCyberTechno I followed this [tutorial on Installing PHP on Windows](http://www.sitepoint.com/how-to-install-php-on-windows/). It is all about to ensure Windows can find PHP, I had to change the path environment variable to my PHP directory.

Thanks for sharing the idea. No atom beautify can do PHP files :+1:

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by Xin-Y** [comment]
when I run the code of Python with beautify  ,the system shows 'connet ECONNREFUSED 127.0.0.1:36805. I can't fix it .  May I ask for help ?
