### ISSUE TITLE
Settings button to disappear？

### ISSUE THREAD

**Issue by phpluo** [Glavin001/atom-beautify#754]
![118105806](https://cloud.githubusercontent.com/assets/15026737/12382476/2693533c-bdd5-11e5-8ed6-573b1e63f623.png)
My computer is win10 64 bit

**Comment by nunovieira** [comment]
Same happened to me on OS X.
I've added a .jsbeautifyrc file on a project... don't know if it's related.

**Comment by rdcvnh** [comment]
Same here on Windows 10.
@nunovieira no, it is not related to .jsbeautifyrc

**Comment by Glavin001** [comment]
I'd recommend also contacting https://github.com/atom/settings-view because this appears to be happening on another package above , `auto-indent`, too.

**Comment by kk8412** [comment]
@Glavin001 I've already had uninstall `auto-indent`, but it's still the same.
I don't know which installation package is in conflict.
Here's all of my package
![102649](https://cloud.githubusercontent.com/assets/15026737/12500979/24c64a66-c0f3-11e5-81cb-a8d3025220ed.png)

**Comment by jerone** [comment]
Seems related to https://github.com/atom/atom/issues/10426

**Comment by kk8412** [comment]
I follow the link[atom/atom#10426](https://github.com/atom/atom/issues/10426)
The same operation to removed `activationCommands` from `package.json(atom-beautify)`, setting page become accessible.
I don't know if there's a problem, but it's normal at the moment. And programmers shouldn't spend too much time on the editor.
Finally thank you
