### ISSUE TITLE
Failing to beautify C#

### ISSUE THREAD

**Issue by philhudson91** [Glavin001/atom-beautify#759]
Failing to beautify C# - stacktrace:

Parsing: /var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3 as language CS
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:19 Garbage in col 12: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 38: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 40: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 46: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 65: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 18: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 38: 2013
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 53: 201d
Hide Stack Trace
Error: Parsing: /var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3 as language CS
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:19 Garbage in col 12: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 38: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:31 Garbage in col 40: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:32 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 46: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:33 Garbage in col 65: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 27: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:35 Garbage in col 33: 201d
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 18: 201c
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 38: 2013
/var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3:37 Garbage in col 53: 201d
    at /Users/philhudson/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:258:27
    at tryCatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
    at MutationObserver.Async.drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:368:9)

**Comment by prettydiff** [comment]
This might be a defect with Uncrustify.  I recommend opening an issue with that project: https://github.com/bengardner/uncrustify/issues

I am not trying to pass the buck, but this is the line that struck me:

    Error: Parsing: /var/folders/3p/31fp7bl56pd_1y_y4xbf2ltr0000gn/T/input116019-1982-ddozy3 as language CS

**Comment by philhudson91** [comment]
Ah okay thanks - are you guys planning on ditching uncrustify anytime soon?

**Comment by prettydiff** [comment]
We cannot ditch uncrustify without an alternative for beautifying C like languages.  If you are able to recommend a different beautifier we will evaluate adding it.

**Comment by derwaldgeist** [comment]
I came here because I was looking for a C# beautifier that supports MacOS (for Unity development). Uncrustify is available for Win and Solaris only. Is there any alternative available for Macs?
