### ISSUE TITLE
php-cs-fixer fails to "de-indent"

### ISSUE THREAD

**Issue by superDuperCyberTechno** [Glavin001/atom-beautify#760]
So I have installed atom-beautify along with php-cs-fixer.phar which I have correctly referenced in the settings. CTRL-ALT-B starts the beautification and it does its thing...

One thing I cannot get it to do though, is to "de-indent" lines that are indented too much. Say I declare a variable (in an empty file, "<?php" and all that jazz) and gives it an indentation. Beautifying the file now does not scootch the file back to zero indentation, but leaves it alone...

**Comment by prettydiff** [comment]
@superDuperCyberTechno would you mind providing a gist of a code sample and steps to reproduce?

**Comment by Glavin001** [comment]
Please follow contribution guidelines for creating Issues: https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc
Thank you.
