### ISSUE TITLE
Use scope instead of grammar name

### ISSUE THREAD

**Issue by timkelty** [Glavin001/atom-beautify#764]
Using `editor.getGrammar().name` requires there to be a specific beautifier for the current grammar. This is unfortunate because of how scope extension and nesting works.

Consider a templating language, e.g. "Smarty". Ideally I should be able to beautify as HTML in this grammar, as the `scopeName` is `text.html.smarty`. However, since you're _only_ using the grammar name, I have to switch grammars to be able to beautify.

Related/Similar issue: https://github.com/emmetio/emmet-atom/issues/376

**Comment by timkelty** [comment]
More reference: https://discuss.atom.io/t/why-do-so-many-packages-ignore-scope-and-only-use-grammar-name/24724

**Comment by Glavin001** [comment]
This is a very interesting idea.

Applicable code sections for someone who may want to try implementing this:
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L390-L395
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L314-L326
- https://github.com/Glavin001/atom-beautify/blob/master/src/languages/index.coffee#L84-L91

**Comment by timkelty** [comment]
Thanks!

**Comment by timkelty** [comment]
It seems that perhaps `editor.scopeDescriptorForBufferPosition().getScopesArray()` is the right method here to use, actually: https://github.com/emmetio/emmet-atom/issues/376#issuecomment-173536921

**Comment by Glavin001** [comment]
I'd love to see a Pull Request implementing something in this direction! Major changes are happening for #1174 and if this is the right direction then I would want this improvement to be in the next major release! Thanks in advance.
