### ISSUE TITLE
Angular 2 Formatting?

### ISSUE THREAD

**Issue by jgodi** [Glavin001/atom-beautify#770]
I am writing some Angular 2 code, which uses ES6 with some annotations and imports. I am writing in ES6 rather then Typescript and it is formatting the following a bit odd. Any suggestions to get this to work properly?

File to Beautify

```
import {Component} from 'angular2/core';
import {Todo} from './todo';
import {TodoList} from './todo_list';
import       {TodoForm} from './todo_form';

@Component({
  selector: 'todo-app',
  template: `
    <h2>Todo</h2>
    <span>{{remaining}} of {{todos.length}} remaining</span>
    [ <a (click)="archive()">archive</a> ]
    <todo-list [todos]="todos"></todo-list>
    <todo-form (newTask)="addTask($event)"></todo-form>`,
  styles:['a { cursor: pointer; cursor: hand; }'],
  directives: [TodoList, TodoForm]
})
class TodoApp {             }
```

Output

```
import {
    Component
}
from 'angular2/core';
import {
    Todo
}
from './todo';
import {
    TodoList
}
from './todo_list';
import {
    TodoForm
}
from './todo_form';

@
Component({
    selector: 'todo-app',
    template: `
    <h2>Todo</h2>
    <span>{{remaining}} of {{todos.length}} remaining</span>
    [ <a (click)="archive()">archive</a> ]
    <todo-list [todos]="todos"></todo-list>
    <todo-form (newTask)="addTask($event)"></todo-form>`,
    styles: ['a { cursor: pointer; cursor: hand; }'],
    directives: [TodoList, TodoForm]
})
class TodoApp {}
```

**Comment by prettydiff** [comment]
Beautification appears to be correct except for the new line prior to the `from` keyword and the destructuring in the blocks following `import`.  I recommend opening a bug with the JS Beautify project so that they can get this corrected.  https://github.com/beautify-web/js-beautify/issues

In the mean time you can change your beautifier in the Atom Beautify settings for language JavaScript to Pretty Diff and see if that works.

**Comment by jgodi** [comment]
The annotation should look like 

```@Component({
    selector: 'todo-app',
    template: `
    <h2>Todo</h2>
    <span>{{remaining}} of {{todos.length}} remaining</span>
    [ <a (click)="archive()">archive</a> ]
    <todo-list [todos]="todos"></todo-list>
    <todo-form (newTask)="addTask($event)"></todo-form>`,
    styles: ['a { cursor: pointer; cursor: hand; }'],
    directives: [TodoList, TodoForm]
})```

over this?

```@
Component({
    selector: 'todo-app',
    template: `
    <h2>Todo</h2>
    <span>{{remaining}} of {{todos.length}} remaining</span>
    [ <a (click)="archive()">archive</a> ]
    <todo-list [todos]="todos"></todo-list>
    <todo-form (newTask)="addTask($event)"></todo-form>`,
    styles: ['a { cursor: pointer; cursor: hand; }'],
    directives: [TodoList, TodoForm]
})```

**Comment by prettydiff** [comment]
Thanks for pointing that out.  It is likely a defect in both Pretty Diff and JS Beautify.  I will add @bitwiseman so that he can see these things called specifically.

**Comment by jgodi** [comment]
Also, is there any setting to make the imports format as so?

```
import {Component} from 'angular2/core';
import {Todo} from './todo';
import {TodoList} from './todo_list';
import {TodoForm} from './todo_form';
```

Thanks for your help!

**Comment by prettydiff** [comment]
I am not sure if there is a JS Beautify option to flatten objects/blocks.  That is kind of a tricky quality because you don't want all blocks to be flattened, particularly multidimensional blocks or blocks containing functions and so forth.

**Comment by bitwiseman** [comment]
The next update to js-beautify will include support for destructured objects, and fixes the `from` formatting.

Annotations/Decorators will also be in the upcoming release: https://github.com/beautify-web/js-beautify/pull/765

**Comment by jgodi** [comment]
Awesome, is there a way to have Atom Beautify use the fork of js-beautify to get that functionality now?

**Comment by prettydiff** [comment]
@jgodi Just wait until updates to JS Beautify are published and the reinstall Atom Beautify.

**Comment by prettydiff** [comment]
If this problem is still relevant please reopen this issue.
