### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open .jsbeautifyrc

### ISSUE THREAD

**Issue by diegodorado** [Glavin001/atom-beautify#771]
steps:
1. created an .jsbeautifyrc
2. used it without problems
3. realized that I'll just keep the default, so deleted it

**Atom Version**: 1.4.1
**System**: Mac OS X 10.8.5
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.21

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/path/to/.jsbeautifyrc'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/diegodorado/proyectos/ciberseguridad-theme/.jsbeautifyrc'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Beautifiers.module.exports.Beautifiers.getConfig (/Users/diegodorado/.atom/packages/atom-beautify/src/beautifiers/index.coffee:636:21)
    at Beautifiers.module.exports.Beautifiers.getOptionsForPath (/Users/diegodorado/.atom/packages/atom-beautify/src/beautifiers/index.coffee:726:15)
    at atom-workspace.beautify (/Users/diegodorado/.atom/packages/atom-beautify/src/beautify.coffee:163:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:19 core:undo (atom-text-editor.editor.is-focused)
     -4:10.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:09.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:09.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -4:08.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:01.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:57.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -3:49.7.0 core:undo (atom-text-editor.editor.is-focused)
     -1:17.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:13.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -1:06.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:58.8.0 tabs:close-tab (div.title)
     -0:52.2.0 tree-view:remove (span.name.icon.icon-file-text)
  2x -0:38.2.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:07.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "2ecc23a5-e44d-4160-a398-d76339342095",
    "html_extra_liners": [
      "head",
      "body",
      "/html",
      "img"
    ],
    "html_preserve_newlines": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
autoclose-html, v0.18.0
autocomplete-glsl, v0.2.3
build, v0.53.0
build-make, v0.7.0
glsl-preview, v0.8.0
html2haml, v0.10.0
language-glsl, v2.0.1
language-haml, v0.21.0
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-glsl, v1.0.6
linter-jscs, v1.12.0
linter-jshint, v1.0.5

# Dev
No dev packages
```

**Comment by prettydiff** [comment]
Yeah, the package uses a .jsbeautifyrc file to store configuration details.  When you created your custom file you likely just overwrote the default file, and then when you deleted the file the package breaks.  To resolve this issue just grab the file from github and put it back into the default location.

https://raw.githubusercontent.com/Glavin001/atom-beautify/master/src/.jsbeautifyrc

**Comment by diegodorado** [comment]
I understand, but I think that a file exist check should be done first.
If I restart atom the problem is solved

2016-01-27 10:48 GMT-03:00 Austin Cheney <notifications@github.com>:

> Closed #771 <https://github.com/Glavin001/atom-beautify/issues/771>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Glavin001/atom-beautify/issues/771#event-528118620>.
>



-- 
--
Diego Dorado
11 3758 3589

**Comment by Glavin001** [comment]
The code at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L636-L638 should be wrapped in a try/catch since it is using the `sync` method. I would accept a Pull Request fixing this. Thanks!

**Comment by diegodorado** [comment]
never done a pull request, but i'm willing to learn about it. i will do it
late at night.
thanks

2016-01-27 11:41 GMT-03:00 Glavin Wiechert <notifications@github.com>:

> The code at
> https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee#L636-L638
> should be wrapped in a try/catch since it is using the sync method. I
> would accept a Pull Request fixing this. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Glavin001/atom-beautify/issues/771#issuecomment-175661255>
> .
>



-- 
--
Diego Dorado
11 3758 3589

**Comment by prettydiff** [comment]
Some quick steps:

1. Fork this github project so that you have a clone of this project associated with your account
2. Clone your fork to your local `git fork clone-address-provided-by-github`.  This will create a new directory containing the project code.  `cd` into this new directory.
3. Create a new branch `git checkout -b my-branch-name`
4. Make code changes
5. Commit the changes and push them back to a new branch on your fork: `git commit -m "a commit message" and then "git push origin my-branch-name".  You can see what has changed with `git status`.
6. Come back to github and open a pull request to Galvin001/atom-beautify branch master
