### ISSUE TITLE
Pretty Diff options for JSX

### ISSUE THREAD

**Issue by relifeted** [Glavin001/atom-beautify#774]
seems not all Pretty Diff options were supported , and .prettydiffrc file was ignored, and some options of Pretty Diff not found in [document](https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#pretty-diff).

so how could i enable below option in Pretty Diff with Atom Beautify?

http://prettydiff.com/documentation.xhtml#neverflatten

this option work in Pretty Diff like below:

``` javascript
    const {
         foo,
         bar,
    } = this.props;
```

when true:

``` javascript
    const {
         foo,
         bar,
    } = this.props;
```

when false:

``` javascript
    const {foo, bar,} = this.props;
```

Or can i switch JSX beautifier to js-beautify?

because js-beautify works fine on JSX file now.

**Comment by prettydiff** [comment]
There are some options still demanding support from Atom Beautify: https://github.com/Glavin001/atom-beautify/issues/524

I recently became a project collaborator and promised I would start generating pull requests to add support for these options, but I have just not gotten to it yet.  This might go faster if anybody were to generate some of the pull requests.
