### ISSUE TITLE
Support for Yesod Shakespeare in atom-beautify

### ISSUE THREAD

**Issue by AlienIndustries** [Glavin001/atom-beautify#775]
Just a request to include the Yesod Web .cassius, .hamlet, .julius, and .lucius extensions to the beautify realm. You can find a language-shakespeare package in atom now and the language package is located here https://github.com/hudon/language-shakespeare if that helps. Thank you for your work on atom-beautify. Edit--forgot to include Enhancement, feature request

**Comment by prettydiff** [comment]
It appears that the link you provided is just a syntax highlighter (code coloring).

The projects to be at:

* http://www.yesodweb.com/book/shakespearean-templates
* https://github.com/yesodweb/shakespeare

So this is a Haskell language based templating project supporting various syntaxes.  The various different supported formats would likely require a unique beautifier.

**Comment by AlienIndustries** [comment]
Thank you for looking into this. I just put the only real link I could find that was atom specific to shakespeare but I follow your point. Consider this closed and will hope to get time to develop a beautifier specific to shakespeare. Keep up the great work on beautify!
