### ISSUE TITLE
Handlebars {{else if}} and {{each}}{{else}} not formatting

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#781]
Hi,

There are couple of Handlebar blocks which do not indent as expected. Using JS Beautify (only option).

In Ember the `{{else if}}` block:

``` Handlebars
// Expected

{{#if isValid1}}
  <p>Is valid 1</p>
{{else if isValid2}}
  <p>Is valid 2</p>
{{else}}
  <p>Is neither</p>
{{/if}}

// What happens instead

{{#if isTrue1}}
  <p>Is valid 1</p> {{else if isTrue2}}
  <p>Is valid 2</p>
{{else}}
  <p>Is neither</p>
{{/if}}
```

Also in Ember the `{{else}}` blocks within  `{{each}}` blocks:

``` Handlebars
// Expected

{{#each clinics as |clinic|}}
  <p>{{clinic.name}}</p>
{{else}}
  <p>Unfortunately no clinics found.</p>
{{/each}}

// What happens instead

{{#each clinics as |clinic|}}
  <p>{{clinic.name}}</p>
  {{else}}
    <p>Unfortunately no clinics found.</p>
{{/each}}
```

Atom debug log: https://gist.github.com/janwerkhoven/9a20c4b21b2ee3ce0555

Love your package :+1:

**Comment by prettydiff** [comment]
I think Pretty Diff is the default beautifier for Handlebars templates.  When I supply the code samples to http://prettydiff.com the result looks correct.  I will continue to look at this.

**Comment by janwerkhoven** [comment]
There is only 1 option ...

![screen shot 2016-02-04 at 2 03 03 pm](https://cloud.githubusercontent.com/assets/4415419/12804514/0ebbbc38-cb48-11e5-804e-99bbe054361f.png)

**Comment by prettydiff** [comment]
I am alerting @bitwiseman that there may be an issue with JS Beautify.  I will also work on adding Pretty Diff as a secondary beautifier for Handlebars.

**Comment by prettydiff** [comment]
@Glavin001 Why is Handlebars not listing Pretty Diff as a beautifier?  It appears to be properly indicated in the code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L72

**Comment by bitwiseman** [comment]
@prettydiff, @janwerkhoven - handlebars support is very spotty in beautifier.  
https://github.com/beautify-web/js-beautify/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+handlebars

Please file this as an issue of there.  Thanks!

**Comment by prettydiff** [comment]
Done: https://github.com/beautify-web/js-beautify/issues/870
