### ISSUE TITLE
Beautify on Save not working for JavaScript

### ISSUE THREAD

**Issue by NerdPad** [Glavin001/atom-beautify#782]
I am using version 0.28.21, and beautify on Save doesn't work. The "Beautify Entire File On Save" is ON.

Example I add about 20 blank lines in a .js file, and save. The blank lines are supposed to be removed.

If I execute Atom Beautify from the command pallet, it works as expected.

**Comment by Glavin001** [comment]
`Beautify Entire File On Save` actually is not "Beautify On Save". It means that **if** you are beautifying on save, it will beautify the entire file, versus only the selected text.

Actually enabling beautify on save is language specific.

For JavaScript, see https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---javascript---beautify-on-save for beautify on save option.
