### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by BrianSidebotham** [Glavin001/atom-beautify#795]
I've tried with various Atom installs. I appreciate there are other reports like this, but none with the error I see:

This report is from Atom 1.6.0-beta, but it's the same for 1.4.3 and 1.5:

> spawn-sync@1.0.15 postinstall C:\Users\BRIAN~1.SID\AppData\Local\Temp\apm-install-dir-116110-10152-14ksgr4\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

>Installing native dependencies (this may take up to a minute)

>npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\atom\\resources\\app\\apm\\bin\\node.exe" "C:\\atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Brian.sidebotham\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Brian.sidebotham\\.atom\\.apmrc" "install" "C:\\Users\\BRIAN~1.SID\\AppData\\Local\\Temp\\d-116110-10152-10jkc6p\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\BRIAN~1.SID\AppData\Local\Temp\apm-install-dir-116110-10152-14ksgr4\node_modules\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\package.json.a87fee8600bf0bf59bbfe97f58857ce8
npm ERR! code ENOENT
npm ERR! errno 34

>npm ERR! enoent ENOENT, rename 'C:\Users\BRIAN~1.SID\AppData\Local\Temp\apm-install-dir-116110-10152-14ksgr4\node_modules\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\package.json.a87fee8600bf0bf59bbfe97f58857ce8'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by prettydiff** [comment]
> npm ERR! node v0.10.40
npm ERR! npm v2.13.3

Would you mind upgrading your Node to later version and see if that helps?

https://nodejs.org/en/

**Comment by BrianSidebotham** [comment]
I don't mind, but that is node under the ${ATOM_INSTALL}/resources/app/apm/bin/ folder - i.e. the version that atom includes in it's installer.

Updating node to 4.2.6 results in another failure from apm: 

> C:\atom\resources\app\apm\bin\\node.exe: bad option: --harmony_collections

**Comment by jbw56** [comment]
This package creates extremely huge directory tree with such long paths that Windows cannot handle.

**Comment by okoetter** [comment]
what does work is cloning this repo to atom packages' folder and then run `apm install`:

> cd c:\users\username\.atom\packages
> git clone https://github.com/Glavin001/atom-beautify.git
> cd atom-beautify
> apm install

restart atom after that.

As this manual method works, the automatic way also should work, right?

**Comment by ttsirkia** [comment]
I have also noticed that it takes sometimes over 15 minutes to install or update atom-beautify in Windows.

About the long path names, this is probably the longest:
`.atom\packages\atom-beautify\node_modules\handlebars\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\center-align\node_modules\align-text\node_modules\kind-of\node_modules\is-buffer\test`

**Comment by ttsirkia** [comment]
Actually, this is even longer:
`.atom\packages\atom-beautify\node_modules\jscs\node_modules\babel-jscs\node_modules\babel-core\node_modules\regenerator\node_modules\defs\node_modules\yargs\node_modules\cliui\node_modules\center-align\node_modules\align-text\node_modules\kind-of\node_modules\is-buffer\test`

**Comment by prettydiff** [comment]
Yeah, NPM v3 features dependency consolidation.  This means a flat dependency list and fewer redundant packages.  The big paths you are seeing are due to dependency trees.

**Comment by parhs** [comment]
Any workaround? I had to reinstall atom since it caused freezing. I need special software to delete these long paths!

**Comment by ttsirkia** [comment]
In the long paths, you can, for example, change all the folder names to `a`. Then you can remove the whole atom-beautify package if needed.

**Comment by jbw56** [comment]
I have deleted these *beautiful* paths nicely with cygwin - must-have tools from Linux world.

**Comment by Glavin001** [comment]
I just published a patch in release v0.29.4 that makes `cross-spawn` dependency optional. 
The [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) package depends on [`spawn-sync`](https://github.com/ForbesLindesay/spawn-sync) and has been causing problems when installing Atom-Beautify for many users. By making this dependency optional, users will be able to easily install Atom-Beautify and, in the case that [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) fails to install, will fallback to the builtin [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) method.

**Comment by jjsainzc** [comment]
i try to install using all recommendation, not working in any way
