### ISSUE TITLE
Brace_Style collapse-preserve-inline

### ISSUE THREAD

**Issue by NerdPad** [Glavin001/atom-beautify#796]
A new option was added in JSBeautifier to keep short objects inline. 

[https://github.com/beautify-web/js-beautify/commit/55f111eecd03f41316c5092c55b4043137d2e6e2](commit)
[https://github.com/beautify-web/js-beautify/pull/853](discussion) [https://github.com/beautify-web/js-beautify/issues/315](issue)

Can we please add support for this?

**Comment by ttsirkia** [comment]
Updgrading to newer version would be highly appriciated and it would fix #422.

**Comment by ttsirkia** [comment]
Actually, there seems to be #779 for this already.

**Comment by Glavin001** [comment]
#779 has been merged. Waiting for publishing.

**Comment by NerdPad** [comment]
@Glavin001 Thank you.

**Comment by Glavin001** [comment]
Published to v0.28.28
