### ISSUE TITLE
beautifyOnSave dont work in Windows 10 Atom Install

### ISSUE THREAD

**Issue by DabsDesign** [Glavin001/atom-beautify#798]
I changed the file with the required settings, but when I save a file .scss it does not stylize. Does not work. I'm changing the correct file?

![beautify-on-save](https://cloud.githubusercontent.com/assets/13589214/12959366/3b791ff2-d01d-11e5-9402-98bc3756c683.jpg)

**Comment by jarnix** [comment]
me too on any file (js, html...)
