### ISSUE TITLE
Handlebars adds breaking spaces after HTML attribute keys?

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#800]
Another Handlebars bug that forces me to turn of "beautify on save" for .HBS files...

```
// Expected
<form onsubmit={{action 'submit'}}>
  {{hd-email-input}}
</form>

// What JS Beautify does...
<form onsubmit= {{action 'submit'}}>
  {{hd-email-input}}
</form>
```

It added a space after `onsubmit`, which literally breaks the code, not just the formatting.

[Debug log Gist](https://gist.github.com/janwerkhoven/bc550b68f3103efd3c03)

**Comment by Glavin001** [comment]
The beautifier handling `Handlebars` is `JS Beautify`. I'd recommended discussing this issue over at https://github.com/beautify-web/js-beautify
When the js-beautify team published an update, you can uninstall and reinstall Atom Beautify to install the latest copy of js-beautify, which will have the fix.
