### ISSUE TITLE
Atom Beautify comment issue - html

### ISSUE THREAD

**Issue by SamuelColacchia** [Glavin001/atom-beautify#801]
Html beautify comment issue, below should demonstrate the issue

_**Before Issue**_

```
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js"></script>
    <!-- ### hi ### -->
  </head>
  <body>
    <main>
      <h1>hi</h1>
    </main>
  </body>
</html>
```

_**After Issue**_

```
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js"></script>
    <!--### hi ###--> </head> <body> <main> <h1>hi</h1> </main> </body> </html> 
```

Based on what i can tell when Beautify see `<!--### some text ###-->`  with no space between --### it does the above

**Comment by prettydiff** [comment]
I am having trouble reproducing on either http://prettydiff.com/ or http://jsbeautifier.org/

Which beautifier are you using for HTML. JS Beautifier is the default.

**Comment by Smhuel** [comment]
I just tried it there and it does not cause a problem but when i go back to atom and try it out i get the issue i highlighted.

Here is some more info:
Using atom-beautify v 0.28.22
config.cson 
```
  "atom-beautify":
    _analyticsUserId: hidden
    cpp_configPath: "\\dev\\uncrustify\\cfg\\ben.cfg"
    html_end_with_newline: true
    html_wrap_attributes: "force"
    html_wrap_line_length: 0
```

Language Config - HTML - Default Beautifier 
"JS Beautify"

Anything else that i should provide that would be useful?

**Comment by Smhuel** [comment]
Atom fully updated all other packages disabled. (Beyond the default atom packages)

**Comment by prettydiff** [comment]
Adding @bitwiseman so that JS Beautify can gain some visibility on this issue.

**Comment by SamuelColacchia** [comment]
Success!

I found the source of the issue.

**Source:** 

When Beautify see a html file marked as html (angular) and <!--# it does the above issue.

In atom for a file to be marked as html (angular) the package angularjs by angular-ui (author) must be downloaded.

**Solution:**

Change language type from html (angular) -> html

**Comment by prettydiff** [comment]
Awesome!
