### ISSUE TITLE
Unhandled issue when installing package

### ISSUE THREAD

**Issue by lkdsub0** [Glavin001/atom-beautify#803]
This problem (see below) occurs on two separate machines.
Desktop i5 Win7 x64
Laptop i7 Win10 x64

Whenever installing the package from within atom, I got the error below.
Uninstalling the package, restarting atom then retry did not solve the problem.
However after 5 unsuccessful attempts the install succeeded on the laptop, but never on the desktop.

```
Installing “atom-beautify@0.28.22” failed.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, open 'C:\Users\UserName\AppData\Local\Temp\apm-install-dir-116113-15448-x244dc\node_modules\atom-beautify\node_modules\jscs\node_modules\babel-jscs\node_modules\babel-core\node_modules\core-js\modules\core.log.js'
```

**Comment by johnsonz** [comment]
I meet this problem too when I install it.

```
Installing “atom-beautify@0.28.22” failed.Hide output…

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'C:\Users\username\.atom\packages\atom-beautify\node_modules\handlebars\dist\amd\handlebars\decorators\inline.js'
```
```
Installing “atom-beautify@0.28.22” failed.Hide output…
EPERM, unlink 'C:\Users\username\.atom\packages\atom-beautify\node_modules\typescript-formatter\node_modules\commandpost\node_modules\es6-promise\lib\es6-promise\asap.js'
```

**Comment by prettydiff** [comment]
All these errors look like dependency related failures.  I have been seeing this a lot lately and I am not sure why dependencies are failing to come in.

Try this from the Windows command line: `apm install atom-beautify`

**Comment by prettydiff** [comment]
Did reinstalling the package solve the problem for you guys?

**Comment by lkdsub0** [comment]
Eventually after several attempts it works at some point (same package), but I have no clue what causes the install to work at some point...

**Comment by Glavin001** [comment]
Did you restart / reload Atom at any point? I find issues like this is almost, if not, always a Node.js dependency caching issue and Atom does not clear the package's cache properly. So I make a habit of quickly reloading Atom after updating.

**Comment by lkdsub0** [comment]
It is quite likely that I tried to solve the problem by restarting Atom,
but I don't remember if the install succeeded right after that.

2016-03-10 7:37 GMT+01:00 Glavin Wiechert <notifications@github.com>:
