### ISSUE TITLE
Dojo unsupported script types.

### ISSUE THREAD

**Issue by lethevimlet** [Glavin001/atom-beautify#805]
Dojo Toolkit uses script type=”dojo/method” and script type=”dojo/aspect” since this is not a default this will cause formatting issues.

dojo/method and dojo/aspect is highly used when working with Dojo Toolkit, as described in

https://dojotoolkit.org/reference-guide/1.10/dijit/Declaration.html

It can be easily fixed like so (line 504 of beautify-html.js)
`
tag_complete.search(/\b(text|application|dojo)\/(x-)?(javascript|ecmascript|jscript|livescript|(ld\+)?json|method|aspect)/) > -1))) {`

Ideally atom-beautify shouldn't attempt to format unknown types since in worst case scenario the formatting would be omitted while if wrong formatting is applied to an unknown type code will get messed up affecting its functionality.

**Comment by prettydiff** [comment]
Notifying @bitwiseman

**Comment by joselightware** [comment]
I opened an issue on js-beautify github since atom-beautify depends on it.
[https://github.com/beautify-web/js-beautify/issues/874](https://github.com/beautify-web/js-beautify/issues/874)
