### ISSUE TITLE
How to disable quotation marks changing after beautify?

### ISSUE THREAD

**Issue by wyudong** [Glavin001/atom-beautify#807]
I have installed `php-cs-fixer` and want to format my PHP code. But how do I disable double quotation changing to single quotation?

Code before 

```
<?php
$db=mysql_connect("127.0.0.1", "root", "password");
```

But now, it becomes

```
<?php
$db = mysql_connect('127.0.0.1', 'root', 'password');
```

**Comment by prettydiff** [comment]
@wyudong Could you create a Gist for the debug.md document that Atom Beautify creates?  That will help us track this down.

**Comment by wyudong** [comment]
@prettydiff Thanks for you response! Created a gist here: https://gist.github.com/wyudong/41c8ad93d43eda2a3eb4

**Comment by prettydiff** [comment]
It seems you are using PHP-CS-Fixer as your beautifier and it does have an option called `single_quote` per https://github.com/FriendsOfPhp/PHP-CS-Fixer.  I don't see an equivalent option on the Atom Beautify side.  This is most likely the problem.

**Comment by Glavin001** [comment]
@prettydiff please use `add-beautifier-option` label where applicable. Thanks!
