### ISSUE TITLE
beautify never really start

### ISSUE THREAD

**Issue by rdelassus** [Glavin001/atom-beautify#809]
I have no gist to provide since it won't produce it.
I tried this on ubuntu 14.04 and ubuntu 15.10
I have the latest version of atom and the latest version of pep8 and autopep8.

here is a code sample : 

```
""" this is a sample file """

def(  pep8error,anotherone):
    return;
```

here is the result when applying autopep8 :

```
""" this is a sample file """

def(pep8error, anotherone):
    return
```

Now when I'm in atom and start to beautify the file, either with ctrl+alt+b, or trying to produce a debug gist with the `Atom Beautify: Help Debug Editor` command, a pop up appears,  "beautification in progress", it's loading and nothing more is happening.

**Comment by auximage** [comment]
I have a similar issue in so much that when I activate Beautify, the pop-up window comes up, and just spins telling me that "Beautification in progress", but nothing happens.  The window will remain open, and no beautification ever takes place.   I have to hide the window, and I never get any results.  Have tried w/ debugging and same happens, but w/ no debugging information.
