### ISSUE TITLE
Beautifier makes JavaScript syntax invalid

### ISSUE THREAD

**Issue by supaiku0** [Glavin001/atom-beautify#810]
I write a lot of QML/JavaScript code and they use a **non-standard** syntax to include other files.

For example the statement at the top of a file:
`.import "MyScript.js as MyScript`

is "beautified" to:

```
.import "MyScript.js
as MyScript
```

Which is invalid syntax.

How to work around the issue? The optimal solution would be to ignore those statements starting with ".import".

**Comment by prettydiff** [comment]
I am looking at QML here:

* https://en.wikipedia.org/wiki/QML
* http://doc.qt.io/qt-4.8/qmlreusablecomponents.html

I do see `import` statements in the examples but not `.import`.  What is messing up the beautifiers though is probably the quote.  All standard web languages expect an opening quote to be paired to a closing quote and there is no difference or precedence between single quotes and closing quotes so long as they appear in identical pairs.  JavaScript (and I believe CSS) have a limitation, though, that the quote pair must be complete before a line termination occurs, so else you get a parse error regarding an unterminated string.  That limitation is not present in HTML or XML.

I cannot reproduce the defect with JS Beautifier outside of Atom, but I can reproduce it with Pretty Diff (though the defect is different).  

Would you be able to provide a larger code example as a gist that I can play around with?

**Comment by supaiku-o** [comment]
Thanks for the fast reply.
I'm not talking about QML files, but JavaScript source files.
This is what I'm talking about:
http://doc.qt.io/qt-5/qtqml-javascript-imports.html#importing-a-javascript-resource-from-another-javascript-resource

**Comment by prettydiff** [comment]
I can reproduce the defect at http://jsbeautifier.org/

In the mean time you can change your beautifier for JavaScript to Pretty Diff, which did not seem to have this defect.  I also strongly encourage you to open an issue at https://github.com/beautify-web/js-beautify/ so that they can be tracking this issue and seek a resolution.

I am including @bitwiseman for his visibility.

**Comment by prettydiff** [comment]
This issue is still open at the third party.
