### ISSUE TITLE
Select Language When Not Found

### ISSUE THREAD

**Issue by dpitskobooster** [Glavin001/atom-beautify#814]
New files that are not saved do not have a file type and crash.  It would be nice that if you can't detect the file type to pop up a prompt for the user to select one.

A user would use this feature when they paste minified code into a temp document and just want to look at it.  This is a use case where a user never wanted to save the file.

**Comment by prettydiff** [comment]
Atom Beautify determines a given language first by examining the selected grammar and then by examining the file extension.  If a new file that hasn't yet been saved has a selected grammar there shouldn't be a problem.

When working with the new code was there a grammar (language) set for the given code?  You can set this manually by going to Edit -> Select Grammar from the main menu.

**Comment by dpitskobooster** [comment]
That solved this issue.
Thanks or informing me of  Edit -> Select Grammar.  I am new to atom.
