### ISSUE TITLE
Uncaught Error: Cannot find module 'lru-cache'

### ISSUE THREAD

**Issue by Jojokats** [Glavin001/atom-beautify#815]
Hi,
When entering ctr-option-b I got the following message:
Uncaught Error: Cannot find module 'lru-cache'
and that's after I updated the package.

**Comment by prettydiff** [comment]
During the update process a dependency must not have installed correctly.  From the command line try `apm install atom-beautify`.  If this still doesn't solve the problem then I will look at other options.

**Comment by Glavin001** [comment]
This usually indicates that Atom / apm failed to install everything properly. If reinstalling does not resolve the problem let us know and we can revisit this.
