### ISSUE TITLE
Add support for Atom config relative pathing for language configuration files.

### ISSUE THREAD

**Issue by grey07** [Glavin001/atom-beautify#818]
### Description

Its difficult to keep beautify in sync with other installations of atom on other machines as its configuration file paths are absolute.
### Expected Results

It would be nice if through a special keyword we can reference the default atom config directory "~/.atom". If you're a user of sync-settings you can have it backup your configs, but its unable to reference them in a common way across multiple operating systems.

**Comment by Glavin001** [comment]
I definitely want to work on this.
Which beautifier are you using with a config path option? A while back ( #235 ) I added `~` support to Uncrustify. Would that be sufficient if Atom Beautify were to make it available to all other beautifiers?

**Comment by grey07** [comment]
I'm using uncrustify as well, when I configure the c, and c++ paths to my config file, I get the following error when attempting to us the ~. (On Mac OSX El Cap)

load_option_file: fopen(/Users/<my_account>/Documents/<some_directory>/code.c/~/.atom/uncrustify.cfg)

I have sync-settings set up to sync my uncrustify config to my atom config directory. Ideally I would like my c and c++ config paths to look like this "~/.atom/uncrustify.cfg" but currently I have to change them each time and every time sync-settings re-synchs I have to fix it on each distro I'm working on. I've currently switched to putting in a common path off of my root directory, but I thought it would be cool if you could add that feature.

**Comment by grey07** [comment]
BTW I really like this plugin.

**Comment by Glavin001** [comment]
Could you add your `debug.md`. Follow https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist

**Comment by Glavin001** [comment]
Applicable code that should do this already: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L47-L48

**Comment by grey07** [comment]
I can't add my debug.md I see your code thats adding it for some reason on OSX its just not expanding correctly.

**Comment by Glavin001** [comment]
You are unable to run command  `Atom Beautify: Help Debug Editor`? Are there any error messages?
