### ISSUE TITLE
PHP with Xampp PHP

### ISSUE THREAD

**Issue by hung11** [Glavin001/atom-beautify#819]
Hi, Im using windows 10 pro x64 and Xampp newest version with PHP 7.0.2 .
The php folder is in C:\xampp\php but i dont see PHP Path in Atom Beautify settings, only settings for php-cs-fixer.phar
When i use beautify, it showed the error
`Could not find 'php'. The program may not be installed.
See http://php.net/manual/en/install.php for program installation instructions.
Your program is properly installed if running 'where.exe php' in your CMD prompt returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.`

**Comment by prettydiff** [comment]
The problem appears to be that either PHP is not locally installed on your machine or it is installed, but there is not a global path in your shell.  PHP-CS-Fixer is written in PHP, so it requires PHP to run.

http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx

**Comment by hung11** [comment]
Ok, i added the path for php folder.
But i did not see any changes when using beautify .

**Comment by prettydiff** [comment]
Are you able to open up a command prompt and execute `php` from any directory?

**Comment by mehdibo** [comment]
i have the same problem, i did as @prettydiff said
http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx
at **Step 4** i added C:\xampp\php but i still have the same problem, did i did it in the correct way ?

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
