### ISSUE TITLE
Bug with simple Ruby method

### ISSUE THREAD

**Issue by Riveascore** [Glavin001/atom-beautify#820]
### Description

The results of beautification are not what I expect.
### Expected Results

The beautified code should have looked like:

```
def age_method
  year = age.to_i
   month = ((age.to_f - year.to_i) * 12).round(3)
   if round_months.to_bool
     month = month.floor
   else
     month = month.round(2)
     #round it cause 0.0 looks weird
     month = 0 if month == 0.0      
   end
end
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/Riveascore/3df525d787bf322fc820
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
These error messages are almost always a user installation issue than a Atom Beautify *bug*.

Please follow the complete instructions found at https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist for creating the `debug.md` Gist. You are missing all of the important information that I need to help you debug this issue.
