### ISSUE TITLE
Problem with "{{> callTemplate}}"!

### ISSUE THREAD

**Issue by thearabbit** [Glavin001/atom-beautify#822]
I use  `Blaze of Meteor JS`.
I have problem with `{{> callTemplate}}` format.
Please help me.

**Comment by prettydiff** [comment]
From the main menu could you do:

Packages -> Atom Beautify -> Debug

And then paste the results in a gist.  We require more details to move forward.

**Comment by Glavin001** [comment]
Please follow the issue template that automatically appeared when you created this issue.
For your convenience, here is the template: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md

**Comment by Alfiepoleon** [comment]
I also have an issue with Blaze autoformat,
`<head>
    <title>resolutions</title>
</head>

<body>
    <ul>
        {{> resolutions}}
    </ul>
</body>

<template name="resolutions">
    <li>Title</li>
</template>`

The template tag is autoformatted to:
`<template name="resolutions">
<li>Title</li>
</template>`

**Comment by prettydiff** [comment]
We don't have enough details to investigate this old option.  Please reopen this issue with more information.
