### ISSUE TITLE
CSS breaks when: nesting and :matches() or :not() for first line

### ISSUE THREAD

**Issue by arturparkhisenko** [Glavin001/atom-beautify#827]
### Description

The results of beautification are not what I expect.

```
.btn {
  &:not(: first-child):not(: last-child) {
    // --^------------------^--
    //breaks only first line (full line), on the next time all will be fine
    border-radius: 0;
  }
}
```
### Expected Results

The beautified code should have looked like:

```
.btn {
  &:not(:first-child):not(:last-child) {
    border-radius: 0;
  }
}
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/arturparkhisenko/8a9c5ec5cf6877832a9e
#### How to create `debug.md` Gist

Note that this will include a copy of your code.
If your code is private, please create a different sample of code that reproduces the problem.
1. In the Atom [command-palette](https://atom.io/packages/command-palette), 
   search for and run the command `Atom Beautify: Help Debug Editor`. 
   The debugging results will be copied to your clipboard.  
2. Create a new Gist at https://gist.github.com/  
3. Create a file in your new Gist called `debug.md`.  
4. Paste your debugging results from Atom beautify into `debug.md` file in your Gist.  
5. Add a link to your Gist in your new Issue.
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I can verify the defect on Pretty Diff.  I am examining now.

**Comment by arturparkhisenko** [comment]
Tested current versions Pretty Diff and JS beautify - works without breaking css. Closing.
