### ISSUE TITLE
Updating to 0.28.23 gets all indentation wrong (CSS and JS)

### ISSUE THREAD

**Issue by jackocnr** [Glavin001/atom-beautify#830]
### Description
Indentation should be 2 spaces, but since the update is now 4 spaces. Tho weirdly the debug output says there's 2, but trust me there's 4 in the editor. One thing I noticed is that in the **Config Options** in the debug output, everything is nested twice, which looks weird and I think is new.
```js
if (true) {
    var a = true;
}
```

### Expected Results
2 spaces, as per the settings. This is how it worked with atom-beautify v0.28.22.
```js
if (true) {
  var a = true;
}
```

### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

### Debug
https://gist.github.com/jackocnr/97feddd5af71f68fc3fe

# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
I apologize for this! Thank you for making an Issue. The issue I believe is unrelated, I mistakenly pushed a commit that should have been in a work-in-progress branch.

Please install v0.28.24 and this should be resolved. Let me know if otherwise. Thank you!

**Comment by BigAB** [comment]
Thanks for updating this so quickly, it resolved my probems, though I did not post this issue.

**Comment by jackocnr** [comment]
Confirmed fixed. Thanks!
