### ISSUE TITLE
Does not support .slimbars

### ISSUE THREAD

**Issue by richardhenke** [Glavin001/atom-beautify#833]
### Description

The .slimbars, .hbs, and .handlebars extensions are not supported :(
![screen shot 2016-02-26 at 10 42 21 am](https://cloud.githubusercontent.com/assets/9287136/13360491/c90a245a-dc76-11e5-9cbb-9afe375977fe.png)
### Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/...
#### How to create `debug.md` Gist

Note that this will include a copy of your code.
If your code is private, please create a different sample of code that reproduces the problem.
1. In the Atom [command-palette](https://atom.io/packages/command-palette), 
   search for and run the command `Atom Beautify: Help Debug Editor`. 
   The debugging results will be copied to your clipboard.  
2. Create a new Gist at https://gist.github.com/  
3. Create a file in your new Gist called `debug.md`.  
4. Paste your debugging results from Atom beautify into `debug.md` file in your Gist.  
5. Add a link to your Gist in your new Issue.
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I am not sure about slimbars, but I know handlebars is supported.  I am going to label this as a defect for the moment because I cant look into it further right now.

**Comment by richardhenke** [comment]
Awesome, thank you.

**Comment by Glavin001** [comment]
In case @prettydiff or I need more debugging information, I recommend that you add your debugging information, `debug.md`, now as instructed above. This will help things move a lot quicker. Thanks.
