### ISSUE TITLE
beautifying js arrays - don't want one per line

### ISSUE THREAD

**Issue by mainpart** [Glavin001/atom-beautify#837]
![image](https://cloud.githubusercontent.com/assets/2713266/13380585/b93e28fc-de4f-11e5-8191-23ec172e115d.png)

Any chance to change the behavior of array beautification? I don't want to make them that tall 
I want to let them stay in one line or preserve their own existing line formatting

![image](https://cloud.githubusercontent.com/assets/2713266/13380635/69f69706-de50-11e5-80fe-e9c92b415111.png)
This option does not helped

**Comment by Glavin001** [comment]
Please follow the Issue template provided, it is a requirement not a recommendation. For your convience, here it is again: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md 
The most important part being the Gist containing your debugging information. That information would help @prettydiff or myself resolve many questions I will be asking without a tedious back and forth.

I await your debugging information. Thank you.

**Comment by prettydiff** [comment]
I will be working this through https://github.com/prettydiff/prettydiff/issues/276

I will have a different similar option for objects.  The goal will be to allow default behavior, always flattened arrays, or never flattened arrays.

**Comment by prettydiff** [comment]
This is fixed on the Pretty Diff side.  A new option exists named `formatArray`.  Please submit a pull request exposing this option to Atom Beautify.

http://prettydiff.com/documentation.xhtml#formatArray

**Comment by chrisdel101** [comment]
How do I use this in Atom?

**Comment by prettydiff** [comment]
@chrisdel101 It should be in the beautifier options for language JavaScript if Pretty Diff is your JavaScript beautifier.

**Comment by chrisdel101** [comment]
I can't find it. I'm in the Javascript  & JSX settings. This is occuring in JSX at the moment. I couldn't find the `format_array` or `formatarray`. U give me a hint? Sorry if I am just not seeing it.

**Comment by prettydiff** [comment]
It may not have been added.  The option was one of the last things I added before I halted work on version 2.  @Glavin001 do you remember if this option was added to the config?
