### ISSUE TITLE
Atom-Beautify updates appear to never finish installing in Atom

### ISSUE THREAD

**Issue by frankhale** [Glavin001/atom-beautify#841]
### Description

Atom version 1.5.3 on Windows 10

Previous issue: https://github.com/Glavin001/atom-beautify/issues/401

When installing atom-beautify updates from within Atom the updates appear to never finish even though they do. This happens on multiple machines for me.

Here is a screenshot that shows the updating spinner. When updating atom-beautify this never goes away until I click "check for updates" again after I can be reasonably sure that atom-beautify has indeed finished updating.

![atom-beautify-updating](https://cloud.githubusercontent.com/assets/190154/13464518/9253654c-e05f-11e5-8305-f410823b6090.PNG)

### Expected Results

The package should update and updating spinner should stop.

**Comment by fourmind** [comment]
I can confirm the same results with version 1.5.3 & 1.5.4 on Windows 7.

**Comment by Glavin001** [comment]
Please create an Issue in Settings-View project: https://github.com/atom/settings-view
The applicable code could be: https://github.com/atom/settings-view/blob/master/lib/package-manager.coffee#L249-L287

If they have recommendations for any changes to Atom Beautify to resolve this issue, please let me know. At this point, Atom Beautify should properly update and it may simply take a long time to install all of the dependencies. However if you are saying that it has already has successfully completed installing and yet Settings View is not showing this, then it sounds like a potential bug on their end.

That being said, there may be an event handler missing in Atom Beautify that I could add that would fix this issue. Feel free to CC me on the Settings-View issue you create. I suggest that you create it as you can reproduce the problem. Thanks.

**Comment by frankhale** [comment]
Issue has been filed on the Settings-View repo. Thanks!

**Comment by Glavin001** [comment]
Thanks! I hope we can resolve this issue for you and other users.

**Comment by frankhale** [comment]
Looks like the issue already existed on the Settings-View side: https://github.com/atom/settings-view/issues/532

**Comment by Glavin001** [comment]
This should already be resolved with https://github.com/Glavin001/atom-beautify/pull/501
Could you confirm that this is still a problem with Atom Beautify in the latest release (or anything after  v0.28.11 ). Thanks.

**Comment by frankhale** [comment]
Updating now, I will let you know.

**Comment by frankhale** [comment]
I'm pretty sure that I can't actually verify this until the next update after this one since it contains the patch #501 which my current version does not.

**Comment by frankhale** [comment]
Just updated on one of my PCs and everything went smoothly. Atom-Beautify installed and when the install was done the Atom UI updated accordingly. Thanks!

**Comment by Glavin001** [comment]
Awesome to hear! Thank you for verifying.

**Comment by frankhale** [comment]
Unfortunately the problem is still happening for me even with the latest versions of Atom-Beautify (0.29.1) and Atom 1.6.2. I've tested on two Windows 10 machines and Atom isn't correctly being notified that the Atom-Beautify install is complete so the UI just spins in the installing state forever (until you click the "Check for Updates" button).

NOTE: It actually did work once last week which is why I close the issue.

**Comment by Glavin001** [comment]
If you install Atom Beautify from command line (`apm install atom-beautify`) is there any errors? It may be an installation bug causing the update to fail entirely.

**Comment by frankhale** [comment]
I don't think there are any installation errors as 0.29.1 is installed and working.

**Comment by frankhale** [comment]
But to give it a shot I'll uninstall it and reinstall it and see what happens.

**Comment by frankhale** [comment]
Installing from scratch worked fine (eg. install finished and Atom's install UI displayed the correct state).  This isn't a good test though in my opinion because I've not encountered any issues installing Atom-Beautify from scratch.

**Comment by Glavin001** [comment]
> This isn't a good test though in my opinion because I've not encountered any issues installing Atom-Beautify from scratch.

Other Windows users have experienced problems installing Atom-Beautify. I am glad to see that v0.29.1 is installing fine for you.

> until you click the "Check for Updates" button

I wonder if this is a bug with how https://github.com/atom/settings-view updates the UI. If you could create an issue with them they may have some ideas for how to fix this. There may be a deprecated API that Atom-Beautify is using, the `deactivate` function is still available in Atom-Beautify which fixed it last time: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L568-L569

**Comment by frankhale** [comment]
I already created an issue with settings-view and it was immediately closed. However, to save everyone the headache I'm going to close this one again and just wait for the respective settings-view issue to be closed. Until then I'll just install updates, make sure to wait long enough and then just click "check for updates" to make Atom update the UI properly when installing Atom-Beautify updates.

Requisite issue on settings-view:

https://github.com/atom/settings-view/issues/532

**Comment by Glavin001** [comment]
Thanks. Let me know if there is something more that the `deactivate` method that Atom-Beautify can add to resolve this issue.

**Comment by geoffatcircle** [comment]
Tried installing on a Mac with Atom 1.10.2 and atom-beautify 0.29.12 will not ever finish installing.

**Comment by crankbird** [comment]
I had a similar problem on OSX 10.13.1 with Atom 1.22.1 x64 and atom-beautify 0.30.9 .. I left the install going for about 30 minutes with no apparent activity from either atom or atom-helper after the first minute or two. I exited atom and did the install of atom-beautify again which finished within a couple of minutes.  The only thing I can think of which was non-standard about my install is that I'd already installed a beautifier for elm first.
