### ISSUE TITLE
isort does not respect line length setting

### ISSUE THREAD

**Issue by cody-c-lewis** [Glavin001/atom-beautify#842]
### Description

isort does not respect the line length setting that autopep8 uses.
### Expected Results

Here's some sample code:

``` python
import os
from Tkinter import DISABLED, END, LEFT, NORMAL, RIDGE, Button, Canvas, Entry, Frame, Text, Tk
import subprocess
```

If I run the following:

``` sh
isort --line-width 119 -y example.py && autopep8 --recursive --in-place --max-line-length 119 example.py
```

I get this:

``` python
import os
import subprocess
from Tkinter import DISABLED, END, LEFT, NORMAL, RIDGE, Button, Canvas, Entry, Frame, Text, Tk
```

However, when I run atom-beautify I get this:

``` python
import os
import subprocess
from Tkinter import (DISABLED, END, LEFT, NORMAL, RIDGE, Button, Canvas, Entry,
                     Frame, Text, Tk)
```

My settings are:

```
"atom-beautify": {
        "python_max_line_length": 119,
        "python_sort_imports": true
    }
```

**Comment by Glavin001** [comment]
It looks like this is currently not implemented.
Applicable code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/autopep8.coffee#L28

I will review and accept a pull request implementing this feature. Thank you.

**Comment by cody-c-lewis** [comment]
Sorry, I accidentally submitted before finishing my post.

**Comment by maxim-lian** [comment]
I think `isort` also doesn't respect `Multi line output` setting - is that the same issue as this?

**Comment by guillochon** [comment]
I see the same thing @max-sixty, the multi line output setting is completely ignored.
