### ISSUE TITLE
Unnecessary chain method indentation

### ISSUE THREAD

**Issue by qwemaze** [Glavin001/atom-beautify#847]
### Description

The results of beautification are not what I expect.
### Expected Results

expected:
![OUTPUT](http://i.imgur.com/ksSxZrm.png)
### Steps to Reproduce

input:

``` javascript
new sql.Request().query(query.query).then((docs) => {
    res.json({
                result: true
        });
}).catch((e) => {
    e.status = e.status || 500;
    Log(e.stack || e);
    res.status(e.status).end();
});
```

Beautify

output:
![OUTPUT](http://i.imgur.com/wxLnKk6.png)
### Debug

[debug.md](https://gist.github.com/qwemaze/c87f10389d24ee7deae9)

**Comment by prettydiff** [comment]
It appears the output and expected output are identical aside from the extra indentation.  This would require a new option from both Pretty Diff and JS Beautify to customize this behavior differently from the default.

**Comment by Glavin001** [comment]
Closing this as third-party issue of Pretty Diff and/or JS-Beautify. Please let me know if a new option is needed in Atom-Beautify to support this.

**Comment by pietrovismara** [comment]
@Glavin001 After a long time, the enhancement has been implemented and merged by js-beautify (https://github.com/beautify-web/js-beautify/pull/1240). Any step that should be taken in order to have the latest js-beautify version in atom-beautify?

**Comment by bitwiseman** [comment]
@pietrovismara - The change is not released yet. It will be in 1.7.0.

**Comment by pietrovismara** [comment]
@bitwiseman I gave a look at [1.7.0 milestone](https://github.com/beautify-web/js-beautify/milestone/23).

Does this mean that it will take several months at least before having it released??

**Comment by bitwiseman** [comment]
@pietrovismara  Coming this weekend.

**Comment by bitwiseman** [comment]
@pietrovismara - Done.

**Comment by pietrovismara** [comment]
@bitwiseman. Thank you so much. Guess it's only a matter of time til i get the update in Atom.
