### ISSUE TITLE
Tab indentation

### ISSUE THREAD

**Issue by coltpini** [Glavin001/atom-beautify#851]
### Description

The results of beautification are not what I expect. It inserted 4 tabs on beautification of css.
### Expected Results

It should have inserted 1 tab.
### Steps to Reproduce

The default setting for indentation size on css is 4, but the default Char is "default:'. So it is giving me 4 tabs, not four spaces. Seems that the setting should be smart enough to know that if my spacing is a tab default size should be 1, and if a space default should be 4.
# Checklist
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue

**Comment by Glavin001** [comment]
Please add your debugging information as instructed at https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#debug
