### ISSUE TITLE
PostCSS Language support (.pcss)

### ISSUE THREAD

**Issue by megalofauna** [Glavin001/atom-beautify#855]
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue

Any plans to add [PostCSS](https://atom.io/packages/language-postcss) language support (*.pcss)?

**Comment by prettydiff** [comment]
I provide the default LESS and SCSS support for Atom Beautify.  Would you mind running code samples through http://prettydiff.com/?m=beautify and let me know of all problems you encounter.  I would love to provide support for PCSS as well.

**Comment by megalofauna** [comment]
@prettydiff Absolutely! I'll let you know what I find.

**Comment by prettydiff** [comment]
I am also looking at this in https://github.com/postcss/postcss/issues/770

The pointed me to some unit tests at https://github.com/postcss/postcss-parser-tests/tree/master/cases

Some defects I have observed:

    //Pretty Diff does not correct for the space between property name and colon
    @page :left {
        background: black
    }
    
    //Parsed as a variable property instead of a variable property and a value separated by a space
    @charset "UTF-8";
    
    //Parsed as a single token instead of a variable property and a value
    @import"test.css"
    
    //Parsed as a single selector.  Should be three comments and a selector
    @-moz-document/* near */ /* filter */ url("example.com/{") /* a */ {}
    
    //comment "end" gets dropped
    /* a { color: black } */
    /**/
    /* */
    div {
        /* inside */
        color: black;
        /* between */
        border-radius: 3px / 7px
        /* end */
    }
    /* b */

    a {
        color: black;
        /* c */
    }


I will look at more later.  I got down as far as this file: https://github.com/postcss/postcss-parser-tests/blob/master/cases/escape.css

Pretty Diff has some serious trouble with escaped syntax.... though that example could also use some refinement as well.

**Comment by prettydiff** [comment]
All of these issues are resolved on my local.  I have deliberately chosen to not fix `!` and `important` separated by a comment.  That is absolutely broken and should fail.  The changes have produced some regressions in my unit tests I still have to resolve and should launch soon.

**Comment by megalofauna** [comment]
@prettydiff I've run [prettydiff](http://prettydiff.com/?m=beautify) through its paces with my own code samples using your SCSS (SASS) and CSS language settings. I get errors and warnings with lang set to CSS (obviously).

But for my use cases, the SCSS (SASS) lang setting works pretty much like a charm! 

One thing I did notice, however, was that when nesting styles, prettydiff inconsistently retains new line characters (with cssinsertlines set to _false_).

### (1) Will retain first new line character, but not second:

`.selector {

  img {
    property: value;
  }

}`

### (2) Will _not _ retain either new line character:

`.selector {

  &::after {
    property: value;
  }

}`

The difference here is the pseudo element (`::after`). My personal preference would be for prettydiff to collapse all such newline characters whenever cssinsertlines is set to false. But I consider this a very minor issue. 

Otherwise, it's working great for me. You've made an awesome beautifier, Austin. Thank you.

**Comment by prettydiff** [comment]
I finally cleared this update through my unit tests.  You can play around with the update at prettydiff.com/ignore/testlocation/index.xhtml?m=beautify

I looked at your samples and I am having trouble reproducing the issues with the empty lines.  I will keep looking at this though.

**Comment by megalofauna** [comment]
Well, I'm having trouble reproducing it now, too. Maybe I imagined it! At any rate, it's a small win. Thanks for all your hard (and quick) work! Can't wait to have this in Atom.

**Comment by prettydiff** [comment]
It could be that this effort removed the defect.  I made many minor changes to the parser that impacts the beautifier later in the logic.

**Comment by prettydiff** [comment]
I have published the updated CSS support to v1.16.37.  From talking with the PCSS guys there is nothing else to do.  PCSS isn't a language, but rather a more robust parser for edge cases, so this enhancement brings my parser closer to their level of support.

**Comment by megalofauna** [comment]
@prettydiff 
Nice work! 

My initial issue was that Atom Beautify doesn't recognize files with the grammar 'PostCSS' with the extension '.pcss' (via Azat S's [package](https://atom.io/packages/language-postcss), so it won't process them with Pretty Diff.

That's still the case, though I've modified my local version to do so.

**Comment by elgandoz** [comment]
@prettydiff 
This still occurs. Although we could just rename the `.pcss` files to `.css`, it would be better to support the extension, simply telling Atom Beautify to treat them as css.
Meanwhile, is there any workaround to do so?

**Comment by szeck87** [comment]
@elgandoz you can do one of two things:

1. Change the grammar in Atom to be SCSS or Sass.
2. Use the command pallette and find `Atom Beautify Beautify Language Scss`
