### ISSUE TITLE
Not able to install behind proxy

### ISSUE THREAD

**Issue by mmrath** [Glavin001/atom-beautify#859]
I am behind a corporate proxy. I installed Atom and configured the proxy details. I am able to install packages such as linter, linter-tslint etc. But I am not able to install atom-beautify. It does not install form command line as well. Could someone please let me know how can I find what is causing this?

**Comment by Glavin001** [comment]
Is there a particular error that you are seeing? I recommend that you also talk to Atom's apm team as well, as they will likely have good ideas to solve this issue for you. https://github.com/atom/apm
