### ISSUE TITLE
ERB Support?

### ISSUE THREAD

**Issue by lallmon** [Glavin001/atom-beautify#86]
Erb is pretty much HTML, however it seems as though atom-beautify doesn't do anything. You can quickly rename the file, but that gets tedious.

Any way to enable it or what would it take to get support?

**Comment by williamtrennem** [comment]
@Glavin001 It would be great to have the ability to change the path directly in Atom Beautify settings.

**Comment by Glavin001** [comment]
@williamtrennem I'll add that to #164

**Comment by Willibaur** [comment]
@Glavin001 Have you added that ability to include path directly on Atom Beautify?
