### ISSUE TITLE
analytics-node dependency contains paths that are too long

### ISSUE THREAD

**Issue by dessant** [Glavin001/atom-beautify#860]
Windows throws errors while trying to move or delete the .atom folder, unsure if it's an upstream bug.

```
C:\Users\prc\.atom\packages\ATOM-B~1\NODE_M~1\ANALYT~1\NODE_M~1\SUPERA~2\NODE_M~1\PROXY-~1\NODE_M~1\PAC-PR~1\NODE_M~1\PAC-RE~1\NODE_M~1\REGENE~1\NODE_M~1\defs\NODE_M~1\yargs\NODE_M~1\cliui\NODE_M~1\CENTER~1\NODE_M~1\ALIGN-~1\NODE_M~1\kind-of\NODE_M~1\is-buffer
```

**Comment by dessant** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/795.

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.
