### ISSUE TITLE
Add YAML Front Matter in CSS/SCSS support (Jekyll)

### ISSUE THREAD

**Issue by clawfire** [Glavin001/atom-beautify#861]
### Description

When a frontmatter encounter, just don't try to oneline it.
### Expected Results

The beautified code should have looked like:

```

---
# Only the main Sass file needs front matter (the dashes are enough)

---
```
### Steps to Reproduce
1. Start a new jekyll project
2. Run command `Atom Beautify: Beautify Editor` in the `main.scss` in the `css` folder
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/clawfire/ee7099183ef315b93c96
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
I looked at the source indicated by the debug.md file.  It appears to beautify correctly except for the YAML part at the top:

    ---
    # Only the main Sass file needs front matter (the dashes are enough)
    ---

Currently the beautifier, prettydiff/lib/csspretty.js, attempts to parse the entirety of the document as CSS with some minor syntax exceptions for other template languages.  I would need to research Front Matter syntax more before I could do anything.

**Comment by clawfire** [comment]
Yep, you're right, the point is to be able to prevent rewriting of Front Matter in any type of file. Not just CSS/SCSS I think.

**Comment by benlachman** [comment]
Looks like this was fixed in prettydiff 2.0.5 last year (now version 2.2.x). But I'm still seeing the old behavior in 0.30.4 so I'm assuming atom-beautifier includes an older version of prettydiff. What needs to be done to pull a more recent release of prettydiff in?

**Comment by prettydiff** [comment]
@benlachman Yeah, I have had trouble getting Pretty Diff 2 into Atom Beautify.  There is a pull request for this if somebody could help figure out why the unit tests are broken.

https://github.com/Glavin001/atom-beautify/pull/1750

**Comment by davidlj95** [comment]
Still an issue

**Comment by oddlots** [comment]
Still an issue
