### ISSUE TITLE
HTML beautify on save doesn't work

### ISSUE THREAD

**Issue by Squidy06** [Glavin001/atom-beautify#862]
I don't know why, but HTML is the only language that I can't Beautify On Save (It works well manually).

Gist:
https://gist.github.com/Squidy06/1d8724ec759e05bf331d

PS. IDK why this is set:
Supported Beautifiers: Pretty Diff
Selected Beautifier: Pretty Diff

when this is also set:
"language_html_default_beautifier": "JS Beautify",

**Comment by Glavin001** [comment]
It is because the language is `EJS` not `HTML`. 

Pretty Diff supports EJS while JS Beautify does not. 
See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#language-config---ejs---default-beautifier for more information.
