### ISSUE TITLE
Nunjucks setting variable 

### ISSUE THREAD

**Issue by rickysullivan** [Glavin001/atom-beautify#867]
Working with Nunjucks here. I know this is supported officially. But so far the formatting has been working well.
Setting an array variable in Nunjucks with a length longer that 5 formats the array over multiple lines. 

```
{% set header1 = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6"
] %}
{% set header2 = ["1", "2", "3", "4", "5"] %}
{% set header3 = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6"
] %}
```
### Expected Results

The beautified code should have looked like:

```
{% set header1 = ["1", "2", "3", "4", "5", "6"] %}
{% set header2 = ["1", "2", "3", "4", "5"] %}
{% set header3 = ["1", "2", "3", "4", "5", "6"] %}
```

**Comment by prettydiff** [comment]
Yeah, that is a default Pretty Diff presentation for arrays.  There is an issue open to always flatten arrays, never flatten arrays, or keep the default.

https://github.com/prettydiff/prettydiff/issues/276

**Comment by jostrander** [comment]
It looks like this was fixed in the third party library, any chance we can get support for it in atom-beautify now?

**Comment by prettydiff** [comment]
As an update this issue was solved and published to Pretty Diff on 23 April.  I will doing work on a self-hosted module system this weekend, so that I can get automated fresh versions of Pretty Diff out to Atom Beautify.
