### ISSUE TITLE
Not able to install atom-beautify

### ISSUE THREAD

**Issue by callmeyesh** [Glavin001/atom-beautify#868]
I am new to atom. I ran `apm install atom-beautify` and I get the following error.
`
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/yvenkatesh/.atom/.apm/.apmrc" "--userconfig" "/Users/yvenkatesh/.atom/.apmrc" "install" "/private/var/folders/pt/b7011fvd6cscm53qg5165hjhv9cw04/T/d-116222-12138-5dl3as/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! version not found: expand-home-dir@0.0.2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/pt/b7011fvd6cscm53qg5165hjhv9cw04/T/apm-install-dir-116222-12138-15g1nw6/npm-debug.log
`

**Comment by crapthings** [comment]
+1 same here

**Comment by iRoachie** [comment]
+1

**Comment by Glavin001** [comment]
Published fix to v0.28.27

Thank you everyone for letting me know of this issue. It appears that the owner of expand-home-dir must have unpublished the old version and republished to v0.0.3. Not sure why they would want to break other dependencies like that though...
