### ISSUE TITLE
Destructing formatting

### ISSUE THREAD

**Issue by julmot** [Glavin001/atom-beautify#873]
### Description

The following code will not be formatted:

``` javascript
let [$stack, open] = getElements(), checkEnd = () => {
    // something
};
```
### Expected Results

``` javascript
let [$stack, open] = getElements(),
    checkEnd = () => {
        // something
    };
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by Glavin001** [comment]
@julmot: Please provide the `Debug` information as indicated in the Issue Template file: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md
Thank you.

---

@prettydiff any thoughts on this?

**Comment by prettydiff** [comment]
This appears to be resolved in the latest version of Pretty Diff.  Closing issue.
