### ISSUE TITLE
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Velocity (HTML)" and extension "vm". 

### ISSUE THREAD

**Issue by zetay** [Glavin001/atom-beautify#874]
### Description

Atom Beautify could not determine a supported beautifier to handle this file with grammar "Velocity (HTML)" and extension "vm".

**Comment by prettydiff** [comment]
I have an issue open to work on this https://github.com/prettydiff/prettydiff/issues/280

I have not gotten to it yet.

**Comment by Glavin001** [comment]
Duplicate of #522.
