### ISSUE TITLE
First save takes a long time

### ISSUE THREAD

**Issue by philippelesaux** [Glavin001/atom-beautify#876]
### Description

When saving a file for the first time after opening Atom, the process takes much longer than normal. The issue goes away when opening Atom in safe mode or disabling the beautify package. After the first save, everything works as normal.
### Steps to Reproduce
1. Open Atom
2. Modify a file and save it
3. Atom locks up for close to a minute
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/philippelesaux/34138a193b5762f47d170fc2c87d080f

Here is a screenshot of my profile as the issue happens:
![screen shot 2016-03-28 at 6 44 46 pm](https://cloud.githubusercontent.com/assets/13442851/14117173/6bce8570-f5b1-11e5-997c-66cff7eac4ca.png)

And here is my saved cpu profile from the screenshot:
https://dl.dropboxusercontent.com/u/13874732/CPU-20160328T184112.cpuprofile
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
I have experienced this, too, however I was not sure if it was Atom Beautify. Now that multiple users (including myself) have confirmed it, I deem this issue top priority.

I'm working on it now. Thank you for your patience!

**Comment by Glavin001** [comment]
Published to v0.29.0

Let me know if it is still slow! This should be a fairly dramatic performance improvement when the package activates. Still more improvements to go!

**Comment by Glavin001** [comment]
I'm not sure why I reopened this. Regardless, I will be looking to make performance improvements in future releases 😃 .

**Comment by VladimirDev93** [comment]
I also remember that your package took a lot of time to install on 5200 RPM HDD, maybe like ~15 minutes. I was surprised today that it took only a couple of seconds to install your package. Job well done! 😃
