### ISSUE TITLE
.csscomb.json is only loaded from first project when using multiple projects

### ISSUE THREAD

**Issue by hsimpson** [Glavin001/atom-beautify#877]
### Description

When using multiple project folders in Atom, then only a local .csscomb.json file from the first project folder is loaded and used.
Used version of atom-beautify: v0.28.27
### Expected Results

Use a per project .csscomb.json config
### Steps to Reproduce
1. Add 2 or more projects in atom
2. Add a .csscomb.json which is not the same as the one from this package (https://github.com/Glavin001/atom-beautify/blob/v0.28.27/.csscomb.json)
3. Configure Beautify on save for CSS
4. Only the CSS files of the first projects are correctly beautified.

I think the problematic code is here:
https://github.com/Glavin001/atom-beautify/blob/v0.28.27/src/beautifiers/csscomb.coffee#L29
`
project = atom.project.getDirectories()?[0]
`
Only the first directory is used, not the current.

**Comment by Glavin001** [comment]
I would be happy to review and merge a Pull Request fixing this bug. Thank you.
