### ISSUE TITLE
Incorrect change for Aurelia Import statement

### ISSUE THREAD

**Issue by JoshuaGarrison27** [Glavin001/atom-beautify#883]
### Description

The results of beautification are not what I expect. I am writing for Javascript and in the Aurelia framework.

### Expected Results

The beautified code should have looked like, all on one line:

```
import {inject} from 'aurelia-framework';
```

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/...

https://gist.github.com/JoshuaGarrison27/cbeb34720c6565a7b30b4bcdad237f7a

**Comment by prettydiff** [comment]
@JoshuaGarrison27 Would you mind resaving your debug gist from a `.txt` to a `.md` file.  It would really improve readability.

**Comment by JoshuaGarrison27** [comment]
Sorry about that. Fixed the file extension.

**Comment by prettydiff** [comment]
I see the original and the resultant code sample in the debug.md file.  Would you mind also providing the desired result so that I can tell the maintainers of JS Beautify what to look for?

**Comment by JoshuaGarrison27** [comment]
I did in the original issue post. Where else should I have put it?

**Comment by prettydiff** [comment]
You can put the desired code output directly into this thread.

**Comment by Glavin001** [comment]
@prettydiff : I believe it would be found at https://github.com/Glavin001/atom-beautify/issues/883#issue-144966851

> The beautified code should have looked like, all on one line:
  ```
import {inject} from 'aurelia-framework';
```

**Comment by JoshuaGarrison27** [comment]
@Glavin001 That is correct. I didn't add the entire code because that would cause additional confusion, IMO.

**Comment by prettydiff** [comment]
Adding @bitwiseman

**Comment by bitwiseman** [comment]
I'm not sure I understand: 
The input code was 
```js
import {
  inject
} from 'aurelia-framework';
```
That's valid.  There is nothing in the beautifier that will collapse that to one line at this time.

**Comment by prettydiff** [comment]
Thanks @bitwiseman 

@JoshuaGarrison27 You can either open an issue at https://github.com/beautify-web/js-beautify/issues or change your beautifier to Pretty Diff in the Atom Beautify settings.
