### ISSUE TITLE
`space-after-keywords` in es6 lint

### ISSUE THREAD

**Issue by muei** [Glavin001/atom-beautify#887]
Use `ESLint` by `always` model.
So the following patterns are considered problems:

``` js
var foo = {
    bar() {
        // ...
    }
};
```

This will tell `error  space-before-function-paren  Missing space before function parentheses`, this will not considered: 

``` js
 var foo = {
    bar () {
        // ...
    }
};
```

So please help me how to use to format like this.Thinks!

**Comment by prettydiff** [comment]
Please create the debug.md file and paste that into a gist.  This will help us identify which beautifier and settings you have set so that we can reproduce and investigate the issue.

**Comment by goelia** [comment]
Same with https://github.com/Glavin001/atom-beautify/issues/897
