### ISSUE TITLE
Support for PowerShell

### ISSUE THREAD

**Issue by brandonusher** [Glavin001/atom-beautify#901]
### Description

I'd very much like to have support for PowerShell in atom-beautify. I think it used to, but seems to not work anymore.
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue

**Comment by mbukosky** [comment]
+1

**Comment by winperec** [comment]
+1

**Comment by prettydiff** [comment]
A beautifier is needed for this request to be fulfilled.

**Comment by nemchik** [comment]
Just posted a possibility in https://github.com/Glavin001/atom-beautify/issues/333
