### ISSUE TITLE
Handlebars Pretty diff support

### ISSUE THREAD

**Issue by jaybeemind** [Glavin001/atom-beautify#905]
### Description

Please see sample codes below.
Try it on http://prettydiff.com/ and beautify

### Expected Results

```
<div class="container">
    {{partial 'header'}}
    {{outlet}}
</div>
```

# What actually happens
```
<div class="container">
    {{partial 'header'}} {{outlet}}
</div>
```

# Checklist

- Tried manually editing config default beautifier to change "JS Beautify" with "Pretty diff" but nothing has changed.

Thanks!

**Comment by prettydiff** [comment]
I can change that.

**Comment by prettydiff** [comment]
I am looking into this right now, but having trouble reproducing.  If there is any white space between the two template tags Pretty Diff is putting them each on their own line.  It is only if the two tags are immediately adjacent that they remain on the same line.  Could the problem be due to a combination of options setting that I am not setting correctly?

**Comment by jaybeemind** [comment]
hello sir have you tried it here http://prettydiff.com/  and beautify->execute?

using 
`<div class="container">
    {{partial 'header'}} {{outlet}}
</div>
`

I'm using Ember Js, and it seems to only happen on {{partial}} {{outlet}} {{yield}} helpers.
The new lines before or after are not preserved.
Tried it using Pretty diff (the link) and it beautified just fine.


Thanks!

**Comment by prettydiff** [comment]
I just wanted to update you that I can reproduce this in Atom Beautify and I am actively examining this issue now.

**Comment by prettydiff** [comment]
It seems, at least for me, that Pretty Diff is not an available beautifier for Handlebars templates.  When I attempt to beautify the code using JS Beautify or an HTML variant that forces JS Beautify over Pretty Diff then I get the defective output described above.  When I get the grammar to regular `HTML` and set Pretty Diff as the beautifier I get the desired output exactly like on the web tool.

I recommend submitting a pull request adding Pretty Diff as a secondary beautifier for Handlebars.

**Comment by Glavin001** [comment]
I do not see a link to a Gist with the debugging information in this discussion. @jaybeemind please provide your `debug.md` Gist as described https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist to help us diagnose this issue and answer questions that would be asked. Thank you.

@prettydiff I recommend not continuing work on this until we confirm exactly what is going on. The `debug.md` will answer our questions.

**Comment by jaybeemind** [comment]
Here is the gist link for `debug.md`:
https://gist.github.com/jaybeemind/ec823414e76206194ee897c4b14f0e05

Thank you kind sirs @Glavin001 @prettydiff

**Comment by Glavin001** [comment]
So Atom-Beautify needs to at least add Pretty Diff for Handlebars support: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L37-L58

Then resolve any Pretty Diff related issues for Handlebars.

> When I attempt to beautify the code using JS Beautify or an HTML variant that forces JS Beautify over Pretty Diff then I get the defective output described above. When I get the grammar to regular HTML and set Pretty Diff as the beautifier I get the desired output exactly like on the web tool.

So it sounds like JS-Beautify currently has Handlebars bugs. Pretty Diff will not be called by Atom-Beautify unless you change the grammar to something like `HTML` that is supported by Pretty Diff in Atom-Beautify.

@jaybeemind : I recommend that you contact JS-Beautify at https://github.com/beautify-web/js-beautify for notifying them of any Handlebars bugs you find.

@prettydiff : If you like to add Handlebars support to Atom-Beautify using the Pretty Diff beautifier, you know the drill :smiley:.

**Comment by jaybeemind** [comment]
Yes @Glavin001 I tried using HTML as the default grammar, then used Pretty Diff as the default beautifier, and it worked just fine. The thing is, someone like me needs syntax highlighting XD

**Comment by Glavin001** [comment]
I'm actually not sure why `Handlebars` is not already in the list of supported languages: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L37-L58

I'll make the change now, and the next release will have it.
