### ISSUE TITLE
Uncrustify command not found

### ISSUE THREAD

**Issue by thedadams** [Glavin001/atom-beautify#91]
Hello,

Beautify for Atom seems to be looking for uncrustify in the wrong place (at least for me).  I installed uncrustify with HomeBrew, and it installed it in `/usr/local/bin/`.  However, Beautify is looking in `/bin/sh`.  Is it possible to add an uncrustify path option?

Thanks.

**Comment by RocketSumit** [comment]
I just installed uncrustify using home-brew in`/usr/local/Cellar/uncrustify/0.63:` and it worked for me in mac. Use `brew install Uncrustify`.
