### ISSUE TITLE
Beautify on save and .jsbeautifyrc

### ISSUE THREAD

**Issue by serl** [Glavin001/atom-beautify#912]
Hello,
I guess I'm not the only one that:
- needs beautification, but not always
- forgets to run it manually.

So I wrote this into `.jsbeautifyrc` in my project root:

```
{
    "python": {
        "beautify_on_save": true
    }
}
```

But it does not work.

**Comment by Glavin001** [comment]
I haven't tested yet if `beautify_on_save` works within the `.jsbeautifyrc` yet. I think the currently supported way is to change it in the Package settings for Atom-Beautify. I will be adding support for this later, however. But for now, use the Atom-Beautify package settings.

**Comment by serl** [comment]
Perfect, thanks! :)
