### ISSUE TITLE
Configuration options for PHP

### ISSUE THREAD

**Issue by BramVanroy** [Glavin001/atom-beautify#915]
### Description

The results of beautification are not what I expect. I correctly installed the PHP-CS-FIXERs file, and PHP code _is_ beautified. But the problem is that I cannot find any configuration file for beautifying. As an example, I want functions to have braces on the same line as the declaration, but instead they are on a new line. Obviously this only an example. I wonder where the configuration file for PHP is.

I am not entirely sure _if_ there ought to be a config file. I know that some coding standards are followed such as leaving out the last `?>` in a block and so on. But does that mean that all of this is handled by the php-cs-fixer file and cannot be made configurable by atom beautify? Is it, thus, impossible to change such small behaviour and only possible by writing one's own standard?
### Results

```
  function setProgressClasses($index)
  {
      global $step;
      if ($step == $index) {
          echo 'class="active"';
      } elseif ($step > $index) {
          echo 'class="done"';
      }
  }
```
### Expected Results

The beautified code should have looked like:

```
  function setProgressClasses($index) {
      global $step;
      if ($step == $index) {
          echo 'class="active"';
      } elseif ($step > $index) {
          echo 'class="done"';
      }
  }
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by Glavin001** [comment]
The documentation of supported options for PHP-CS-Fixer beautifier can be found at https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php-cs-fixer

**Comment by meeprakash25** [comment]
i have the same issue
