### ISSUE TITLE
PHP Doc tags are removed from comments

### ISSUE THREAD

**Issue by jonppenny** [Glavin001/atom-beautify#917]
When I run Atom Beautify, phpdoc tags (@return, @var etc.) are being removed from comments. I am running version 0.29.2 of Atom Beautify with Atom 1.6.2 on Windows 10. No error is produced.

**Comment by Glavin001** [comment]
Please follow the issue template provided. For your convenience, here it is again: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md
Thanks.
