### ISSUE TITLE
Tab indentation is incorrect after beautification on Windows machine (correct on Arch)

### ISSUE THREAD

**Issue by Nikki1993** [Glavin001/atom-beautify#921]
### Description

The results of beautification are not what I expect on Windows. On my Arch installation my .html files are being correctly beautified with tab size set to 2. However, with exactly same settings (atom and beautify) tab indentation upon beautification is 4 not 2. 
### Expected Results

Tab indentation should remain 2 as per user settings. 
### Steps to Reproduce
1. Fill up index.html (in my case I use it in combination with AngularJS)
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right on Windows, however beautifies correctly on Arch machine. 
### Debug

Here is a link to the `debug.md` https://gist.github.com/Nikki1993/cd3b7caff6a8aa5b66a8fb0edea336ec
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
On an irrelevant aside I noticed the sample code is missing a `</div>` tag.

It appears the indentation size is manually changed by the user in the Atom Beautify settings, but this change is not being reflected into the language settings, which continue to operate with the default values.

**Comment by Nikki1993** [comment]
@prettydiff where is it missing </div>? o_O it's a just a sample code from my very very very early commit, the only thing it's missing is <span> closing tag but I can assure you even with proper HTML beautify doesn't take user settings in consideration.

**Comment by prettydiff** [comment]
Yeah, your bug is completely valid.  I was just completely nitpicking when I was talking about the sample code.  Missing tags would have nothing to do with this defect.

**Comment by Glavin001** [comment]
So the language being detected is `EJS` and while the settings for `HTML - Indent Size` are set to `2` the setting for `EJS - Indent Size` is `4`:

See under `Package Settings`:

```javascript
"ejs": {
        "indent_size": 4,
}
//...

 "html": {
        "indent_size": 2,
}
```

So it is worked as expected. I recommend you configure your `EJS` settings.

**Comment by prettydiff** [comment]
Closing as this appeared to be a configuration issue more than a bug and I believe all questions were answered.
