### ISSUE TITLE
Installation of atom-beautify fails with Atom 1.7.1 

### ISSUE THREAD

**Issue by krzychb** [Glavin001/atom-beautify#925]
### Description

Installation of  ``` atom-beautify ``` with Atom 1.7.1 on a PC with Windows 7 x64 fails with error below:

```
Installing “atom-beautify@0.29.2” failed.Hide output…

> spawn-sync@1.0.15 postinstall C:\Users\KRZYSZ~1\AppData\Local\Temp\apm-install-dir-116316-2924-1rw2l58\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall


npm WARN optional dep failed, continuing fsevents@1.0.11
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Krzysztof\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Krzysztof\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Krzysztof\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Krzysztof\\.atom\\.apmrc" "install" "C:\\Users\\KRZYSZ~1\\AppData\\Local\\Temp\\d-116316-2924-s9v6vf\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
```
### Expected Results

Installation should not fail :smile:

### Steps to Reproduce

1. Download and install Atom editor with PlatformIO package from http://platformio.org/platformio-ide
2. Open Atom and go to Settings > Install
3. Find ``` atom-beautify ``` package and press Install button
4. Information ``` Installing “atom-beautify@0.29.2” failed.Hide output… ``` will show after about two minutes or so.

### Debug

N/A

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly - **N/A**
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue - this issue looks similar to  #902 except:
-  ``` npm WARN optional dep failed, continuing fsevents@1.0.11 ```
- ``` Windows_NT 6.1.7601 ```

If this should be redirected to some else from the Atom team then please point me to respective repository.

- [ ] Generated debugging information and added link for `debug.md` Gist to this issue - **N/A**

**Comment by prettydiff** [comment]
Looks like a missing dependency.  Would you mind trying `apm install atom-beautify` from the command line and letting me know if that resolves the problem?

**Comment by Glavin001** [comment]
I just published a patch in release v0.29.4 that makes `cross-spawn` dependency optional. 
The [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) package depends on [`spawn-sync`](https://github.com/ForbesLindesay/spawn-sync) and has been causing problems when installing Atom-Beautify for many users. By making this dependency optional, users will be able to easily install Atom-Beautify and, in the case that [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) fails to install, will fallback to the builtin [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) method.

**Comment by krzychb** [comment]
Hi @prettydiff and @Glavin001,

Thank you for looking into this issue. 
I have bad and good news. I will start with bad news first :smile: 

First I tried to install ```atom-beautify``` from Settings > Install as I noticed that release v0.29.4 is available. Unfortunately it failed as follows:
```
Installing “atom-beautify@0.29.4” failed.Hide output…

> spawn-sync@1.0.15 postinstall C:\Users\KRZYSZ~1\AppData\Local\Temp\apm-install-dir-116317-4556-k8li8n\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall


> atom-beautify@0.29.4 postinstall C:\Users\KRZYSZ~1\AppData\Local\Temp\apm-install-dir-116317-4556-k8li8n\node_modules\atom-beautify
> node script/build-options.js


'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional dep failed, continuing cross-spawn@2.2.3
npm WARN optional dep failed, continuing fsevents@1.0.11
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Krzysztof\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Krzysztof\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Krzysztof\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Krzysztof\\.atom\\.apmrc" "install" "C:\\Users\\KRZYSZ~1\\AppData\\Local\\Temp\\d-116317-4556-vs88h0\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.4 postinstall: `node script/build-options.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.4 postinstall script 'node script/build-options.js'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/build-options.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.
```

Then, as suggested by @prettydiff, I tried ```apm install atom-beautify``` from the command line with the following result:
![beautify](https://cloud.githubusercontent.com/assets/12953787/14586288/e3ccdf36-0493-11e6-98f9-2d915c4a587b.PNG)

The net result is that ``` atom-beautify ``` is installed and working for me :+1: 

![installed](https://cloud.githubusercontent.com/assets/12953787/14586312/91d11aca-0494-11e6-85aa-ab94f2727924.PNG)

I like the message that you show when [uncrustify](http://uncrustify.sourceforge.net/) is missing and in particular information about adding it to PATH :ok_hand: 

Thank you for support and congratulations on awesome download count!

Krzysztof

**Comment by StanYan** [comment]
Hi all,
I have Atom v.1.12.9 and I can't install `atom-beautify` v.0.29.16.
`npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Stan Yan\\AppData\\Local\\atom\\app-1.12.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Stan Yan\\AppData\\Local\\atom\\app-1.12.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Stan Yan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Stan Yan\\.atom\\.apmrc" "install" "C:\\Users\\STANYA~1\\AppData\\Local\\Temp\\d-11708-1076-17xrq3o\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\STANYA~1\AppData\Local\Temp\apm-install-dir-11708-1076-1yeogap\npm-debug.log
npm ERR! code 1`

**Comment by dhananjayaS** [comment]
Installing “atom-beautify@0.30.9” failed.Hide output…

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/dhananjaya/.atom/.apm/.apmrc" "--userconfig" "/home/dhananjaya/.atom/.apmrc" "install" "/tmp/d-1171030-12236-1ubutxx.nvpe97ldi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EIO
npm ERR! errno -5
npm ERR! syscall read

npm ERR! EIO: i/o error, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1171030-12236-1559unc.2lrd1v2t9/npm-debug.log
