### ISSUE TITLE
Installation/Upgrade Error for Latest Version. `Version Error: EACCES, permission denied`

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [Glavin001/atom-beautify#927]
### Description

I am unable to install or update atom-beautify. I have removed  `.atom/`, cleaned `/private/tmp/npm*` and `/private/tmp/Atom*`, and then I did a fresh Atom install. The error I am getting is `Error: EACCES, permission denied`. I have attempted to install via CLI and in the Atom app, both fail.

I tried install old versions (`v0.28.x`) of atom-beautify and the same issue is happening.

OS X: `10.10.2 Yosemite`
### Logs  

	➜  ~ sudo apm install atom-beautify
	Installing atom-beautify to /Users/JohnDoe/.atom/packages ✗

	> spawn-sync@1.0.15 postinstall /private/tmp/apm-install-dir-116317-26539-1njcd6q/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
	> node postinstall

	> fsevents@1.0.11 install /private/tmp/apm-install-dir-116317-26539-1njcd6q/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents
	> node-pre-gyp install --fallback-to-build

	shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

	node.js:844
	    var cwd = process.cwd();
	                      ^
	Error: EACCES, permission denied
	    at Function.startup.resolveArgv0 (node.js:844:23)
	    at startup (node.js:58:13)
	    at node.js:935:3
	npm WARN optional dep failed, continuing cross-spawn@2.2.3
	npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
	sh: node-pre-gyp: command not found
	npm WARN optional dep failed, continuing fsevents@1.0.11
	npm ERR! tar.unpack error reading /Users/JohnDoe/.atom/.apm/longest/1.0.1/package.tgz
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm ERR! Darwin 14.1.0
	npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/JohnDoe/.atom/.apm/.apmrc" "--userconfig" "/Users/JohnDoe/.atom/.apmrc" "install" "/private/tmp/d-116317-26539-9wzuvi/package.tgz" "--target=0.36.8" "--arch=x64"
	npm ERR! node v0.10.40
	npm ERR! npm  v2.13.3
	npm ERR! code EBADF
	npm ERR! errno 9

	npm ERR! EBADF, fstat
	npm ERR! 
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     /private/tmp/apm-install-dir-116317-26539-1njcd6q/npm-debug.log

**Comment by Glavin001** [comment]
You should not need to use `sudo`. 
`apm install atom-beautify` should do.
Also, this error is coming from the installation of the package [`remark`](https://github.com/wooorm/remark), in case you want to investigate further with the maintainer(s) of that package.

**Comment by RanadeepPolavarapu** [comment]
I tested on version `0.28.22` and the `remark` error is displayed in log. Do you believe that the error in the older versions of atom-beautify is coming from a third-party package as well?

### Log  

	➜  ~ sudo apm install atom-beautify@0.28.22
	Installing atom-beautify@0.28.22 to /Users/JohnDoe/.atom/packages ✗

	> spawn-sync@1.0.15 postinstall /private/tmp/apm-install-dir-116318-27006-103s8oa/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
	> node postinstall


	shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

	node.js:844
	    var cwd = process.cwd();
	                      ^
	Error: EACCES, permission denied
	    at Function.startup.resolveArgv0 (node.js:844:23)
	    at startup (node.js:58:13)
	    at node.js:935:3
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
	npm ERR! Darwin 14.1.0
	npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/JohnDoe/.atom/.apm/.apmrc" "--userconfig" "/Users/JohnDoe/.atom/.apmrc" "install" "/private/tmp/d-116318-27006-8etv41/package.tgz" "--target=0.36.8" "--arch=x64"
	npm ERR! node v0.10.40
	npm ERR! npm  v2.13.3
	npm ERR! code ELIFECYCLE

	npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
	npm ERR! Exit status 8
	npm ERR! 
	npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
	npm ERR! This is most likely a problem with the spawn-sync package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node postinstall
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls spawn-sync
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /private/tmp/apm-install-dir-116318-27006-103s8oa/npm-debug.log
