### ISSUE TITLE
Windows. Forwardslash and backslash in path settings

### ISSUE THREAD

**Issue by avknor** [Glavin001/atom-beautify#928]
### Description

In settings when I copypast path from windows folder to plugin it pasts with backslashes. But in that case plugin does not work and no err mesages. Simple does not work. Because it wants forwardslashes in path. I think this is a BUG.

Simpliest solution is add label for all path variables. Something like "Use '/' instead '\' ".
But best solution is to make plugin understand both slash symbols.

In debug (PHP section) you can see that plugin replace all '\' symbols to '\\\\'.

### Expected Results

Working paths. No matter which slash you use.

### Steps to Reproduce

For example in PHP settings. 

1. Add path to "PHP-CS-Fixer Path" parameter
2. Use backslash instead forwardslash.

### Debug

Here is a link to the `debug.md` https://gist.github.com/avknor/71f17588d5f9b5d0567cb0f8b88262ba

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by avknor** [comment]
@Glavin001 done

**Comment by Glavin001** [comment]
Atom-Beautify uses the paths directly as given, and in the case of Windows the this usage would be correct. This should work fine.
Here is the applicable code for PHP-CS-Fixer that runs the command: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L35-L40

From the end of your logs:

>  2016-04-18T05:02:58.984Z - debug: [beautifiers\beautifier.coffee] spawn C:\OpenServer\modules\php\PHP-5.5\php.EXE 0=C:\Users\KryukovAV.NPR\AppData\Roaming\Composer\vendor\fabpot\php-cs-fixer\php-cs-fixer, 1=fix, 2=C:\Users\KRYUKO~1.NPR\AppData\Local\Temp\temp116318-1136-dsja5u
2016-04-18T05:03:00.306Z - debug: [beautifiers\beautifier.coffee] spawn done 0  Fixed all files in 0.397 seconds, 4.500 MB memory used

It appears that PHP-CS-Fixer is working and ran as expected. 

Could you explain more about what is not working?

**Comment by avknor** [comment]
Looks like this is local problem of a specific computer. On other windows pc problem is not repeated.
