### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by Bengt** [Glavin001/atom-beautify#93]
Currently Atom Beautify displays an error, when opening a markdown file:

> Unsupported language for grammar 'GitHub Markdown'.

It would be nice to have Atom Beautify normalize Markdown. That could be done using pandoc as [suggested in another repo](https://github.com/bundestag/gesetze-tools/issues/3):

``` bash
$ pandoc -f markdown -t markdown index.md
```

**Comment by slang800** [comment]
If you want to get rid of the pandoc dep, I wrote a markdown beautifier in pure JS: https://github.com/slang800/tidy-markdown (so it can be required via npm)

**Comment by Glavin001** [comment]
Awesome! Could you open an issue for this? I'd like to add support for tidy-markdown for Atom Beautify v1.0 :smiley:

**Comment by slang800** [comment]
gladly! ref: #292
