### ISSUE TITLE
Atom CRASHES on beautify + DELETES content

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#931]
### Description
Each time I beautify my HBS or SCSS files, Atom CRASHES. Once Atom reboots, my content is GONE. I had to restore my content with Git checkouts and was forced to uninstall the package. The next days, no crashes occurred. From the second I reinstall, crashes again and again. Help please!

### Expected Results
Beautify on save WITHOUT crashing Atom please.

### Steps to Reproduce
1. Enable "Beatify HBS on save"
2. Save HBS file
3. Freezes Atom, crashes, deleted content when I releod Atom

### Debug
My debug file: https://gist.github.com/janwerkhoven/c2de41dd37765821ee77bac591ef75ba

# Checklist
- [x] Tried uninstalling Atom Beautify, no crashes for couple of days
- [x] Reinstall package, crashes re-occur
- [x] Did migration

**Comment by epelc** [comment]
Duplicate #924
