### ISSUE TITLE
Installed Uncrustify last night and it was working now it says Uncrustify is not installed although it appears when running 'where.exe uncrustify'

### ISSUE THREAD

**Issue by Bertieio** [Glavin001/atom-beautify#932]
### Description

"Could not find 'uncrustify'. The program may not be installed." Error message when running beautify on c# code. 'where.exe uncrustify' shows C:\Program Files (x86)\uncrustify-0.62.0-g5987f22-win32\uncrustify.exe

It was working last night and I havent rebooted my pc.
I am Running Windows 10, Atom 1.7.2 Beautify 0.29.4
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. "Could not find 'uncrustify'. The program may not be installed." Error message
### Debug

I tried running Atom Beautify: Help Debug Editor but my clipboard didnt 
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
I am unable to help debug this issue without the debugging information obtained from `Help Debug Editor`. Please try to generate it again or explain what is wrong with `Help Debug Editor`. Thanks.

**Comment by Bertieio** [comment]
When I run Help Debug Editor it doesnt update my clipboard

**Comment by Glavin001** [comment]
And there are no helpful errors shown?
Atom-Beautify uses Atom's built-in clipboard API: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L463
```coffeescript
      atom.clipboard.write(debugInfo)
```
See https://atom.io/docs/api/v1.7.2/Clipboard#instance-write

So if the clipboard API is not working for you then I suggest you let the Atom team know at https://github.com/atom/atom/issues 


> C:\Program Files (x86)\uncrustify-0.62.0-g5987f22-win32\uncrustify.exe

Applicable code for Uncrustify beautifier: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L75
Atom-Beautify expects your PATH environment variable to be setup properly, such that `C:\Program Files (x86)\uncrustify-0.62.0-g5987f22-win32\` is present.
Without the debugging information I cannot help you diagnose what Atom and Atom-Beautify see as your PATH variable and if it is correct.

Another idea is that `cross-spawn` failed to be installed.
`cross-spawn` is required for `pathExt` option to work: https://github.com/IndigoUnited/node-cross-spawn#why
And pathExt is used for Windows support at https://github.com/Glavin001/atom-beautify/blob/c950557438e57dfa368c8d75d015605697f661b3/src/beautifiers/beautifier.coffee#L163
Uninstall Atom-Beautify and using your shell run `apm install atom-beautify` and look for any errors regarding the installation of packages `cross-spawn` or `spawn-sync`. If `cross-spawn` fails to install, then `pathExt` option will not be supported and cause other related Windows-only issues.

Without the debugging information, there is not much I can do until I know more about your installation and what Atom and Atom-Beautify are seeing in your setup.

**Comment by lhecker** [comment]
@Glavin001 I had the same problem for quite some time with Rust for atom-beautify. Today I debugged the application and found a solution:
If I disable `cross-spawn` [here](https://github.com/Glavin001/atom-beautify/blob/c950557438e57dfa368c8d75d015605697f661b3/src/beautifiers/beautifier.coffee#L10) everything works as expected! Reason being that `cross-spawn` always fails with `spawn cmd.exe ENOENT` while the "native" spawn works as expected.
Anything I could help with to fix this properly and permanently for atom-beautify?

**Comment by Glavin001** [comment]
@lhecker are you using Windows?

I think the long term solution is to remove `cross-spawn` entirely, which is only added to Atom-Beautify to improve Windows support.

**Comment by lhecker** [comment]
Yeah @Glavin001. I think this problem only exists on Windows and is caused by that dependency.

**Comment by Glavin001** [comment]
Seems that `cross-spawn` is causing more problems than it solves.

If you like, feel free to submit a Pull Request fixing any issues you have. I will merge it so long as AppVeyor (Windows CI) passes. Thanks!

**Comment by lhecker** [comment]
@Glavin001 I'll submit a PR for this issue soon. The Rust support is also a bit "annoying" right now because storing the editor contents in a temporary file to beautify them messes with the module lookup (because modules mentioned in a Rust file are of course not present in the temp. folder). I've never written CoffeScript before nor do I know the project well, so... Well we'll se. :sweat_smile:

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
