### ISSUE TITLE
Closing file causes atom-beautify to crash

### ISSUE THREAD

**Issue by epelc** [Glavin001/atom-beautify#935]
### Description

Hold ctrl-s for a few seconds then wait a few seconds then close the file and you get a stack trace. Notice after you hold ctrl-s for a few seconds clicking around in the file and editing it becomes very slow.

The 1.7.x saving update may be related. See #924 

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.6
### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At C:\Users\Ed\AppData\Local\atom\app-1.7.2\resources\app.asar\src\text-editor-element.js:372

TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (C:\Users\Ed\AppData\Local\atom\app-1.7.2\resources\app.asar\src\text-editor-element.js:372:28)
    at setScrollTop (file:///C:/Users/Ed/.atom/packages/atom-beautify/src/beautify.coffee:35:8)
    at file:///C:/Users/Ed/.atom/packages/atom-beautify/src/beautify.coffee:131:13
```
### Commands

```
     -2:25.1.0 core:close (atom-text-editor.editor.is-focused)
     -2:24.7.0 settings-view:open (div.pane-item.native-key-bindings.about)
     -0:44.9.0 golang:updatelinters (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:25 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:14.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:14.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:14.6.0 editor:indent (atom-text-editor.editor.is-focused)
 10x -0:13.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autoclose-html"
    ]
  },
  "atom-beautify": {
    "apex": {},
    "arduino": {},
    "c": {},
    "cfml": {},
    "coffeescript": {},
    "cpp": {
      "beautify_on_save": true
    },
    "cs": {},
    "css": {
      "beautify_on_save": true,
      "preserve_newlines": true
    },
    "d": {},
    "ejs": {},
    "erb": {},
    "fortran": {},
    "general": {
      "analytics": false
    },
    "gherkin": {},
    "go": {},
    "handlebars": {},
    "html": {
      "beautify_on_save": true
    },
    "jade": {},
    "java": {},
    "js": {
      "beautify_on_save": true,
      "end_with_comma": true
    },
    "json": {
      "beautify_on_save": true
    },
    "jsx": {},
    "latex": {},
    "less": {},
    "marko": {},
    "mustache": {},
    "objectivec": {},
    "pawn": {},
    "perl": {},
    "php": {},
    "python": {},
    "riot": {},
    "ruby": {},
    "rust": {
      "beautify_on_save": true
    },
    "sass": {
      "beautify_on_save": true
    },
    "scss": {
      "beautify_on_save": true
    },
    "spacebars": {},
    "sql": {},
    "svg": {},
    "swig": {},
    "tss": {},
    "twig": {},
    "typescript": {},
    "vala": {},
    "visualforce": {},
    "xml": {},
    "xtemplate": {}
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.6
autocomplete-go, v1.0.6
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.4
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
This is a disadvantage of the new Beautify On Save implementation that was required to fix #924. Basically, the TextEditor instance must still be alive throughout the beautification process, such that the text/code can be retrieved, beautified, and then finally saved.

So my official recommendation is to simply wait for beautification to complete, if you want to use Atom >= 1.7.x and Atom-Beautify's beautify on save functionality.


If anyone would like to take a shot at improving the beautify on save, take a look at the applicable code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L485-L534

**Comment by Glavin001** [comment]
> Notice after you hold ctrl-s for a few seconds clicking around in the file and editing it becomes very slow.

Wait a minute. Why are you **holding** `ctrl-s` and not just pressing it once? Doesn't that *repeatedly* save?
The current implementation will beautify on every save, so it makes sense the editor becomes slow if you are saving it repeatedly and unnecessarily.

**Comment by epelc** [comment]
If you accidentally hold it too long it makes the editor super slow for a long time. You end up having to have to close the file.
