### ISSUE TITLE
Warning after update: "Atom-Beautify: Migrate Settings"

### ISSUE THREAD

**Issue by MsEmma** [Glavin001/atom-beautify#936]
I am getting the below error whenever I run atom beautify

Please run Atom command 'Atom-Beautify: Migrate Settings'.
You have unsupported options: _analyticsUserId

**Comment by Glavin001** [comment]
Have you ran `Atom-Beautify: Migrate Settings` as instructed?
The command will convert your existing settings to the new format, as implemented in https://github.com/Glavin001/atom-beautify/pull/864

**Comment by MsEmma** [comment]
Where do I run the command? Atom Beautify: Migrate Settings?

**Comment by Glavin001** [comment]
> Where do I run the command?

In the traditional way, with the Atom command pallete where all commands are: https://github.com/atom/command-palette

You can open it with `cmd-shift-p` (OSX) or `ctrl-shift-p` (Linux/Windows) in Atom.

**Comment by konstantinmagg** [comment]
Had the same problem. Your solution, @Glavin001, fixed it right away.

**Comment by jadchaar** [comment]
Thanks a ton @Glavin001! This issue has been driving me nuts haha!

**Comment by Glavin001** [comment]
Sorry about that, guys. I thought more people knew about the Atom command palette. I've improved the error message, so a future release will be easier to understand. Thanks for your feedback!

**Comment by MsEmma** [comment]
Thanks a lot @Glavin001. Issue resolved

**Comment by reza-ryte-club** [comment]
Thanks @Glavin001, it worked.
