### ISSUE TITLE
Support options for clang-format

### ISSUE THREAD

**Issue by hz** [Glavin001/atom-beautify#944]
I modified clang-format.coffee in atom-beautify package as,

```javascript
    .then((dumpFile) =>
      # console.log("clang-format", dumpFile)
      return @run("clang-format", [
        @dumpToFile(dumpFile, text)
        ["--style='{BasedOnStyle: google, TabWidth: 2, SortIncludes: false}'"]
        ], help: {
          link: "https://clang.llvm.org/docs/ClangFormat.html"
        }).finally( ->
          fs.unlink(dumpFile)
        )
```
clang-format style is

>       ["--style='{BasedOnStyle: google, TabWidth: 2, SortIncludes: false}'"]

Could atom-beautify package support option input as one parameter for clang-format?

Thanks a lot.

**Comment by Glavin001** [comment]
Please feel free to submit a Pull Request improving clang-format support.
I recommend taking a look at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee for inspiration, as it has the most complex handling of options supported.

**Comment by hz** [comment]
I understood the tricks that clang-format in atom-beautify takes. It works well after I dumped my config to my workspace path /studio/.clang-format.  So I closed this issue.Thanks.

**Comment by sfc9982** [comment]
Just summraize, put a `.clang-format` in your Workspace, `clang-format` automaticlly use it.
