### ISSUE TITLE
Typescript formatter extremaly outdated (atom-beautify: 0.3.2, while its 2.1.0 already), formatting issues

### ISSUE THREAD

**Issue by radarsu** [Glavin001/atom-beautify#945]
Typescript formatter is version 2.1.0 already, while atom-beautify uses 0.3.2. It's horribly outdated and causes many formatting issues (espcially with readonly attributes).

Please update typescript formatter used in atom-beautifier ASAP!
https://github.com/vvakame/typescript-formatter/

**Comment by Glavin001** [comment]
Published to v0.29.7
