### ISSUE TITLE
Invalid typescript formatting when attribute is readonly dictionary with get property

### ISSUE THREAD

**Issue by radarsu** [Glavin001/atom-beautify#946]
When im using ctrl+alt+b on this:

```
class Race {

    private readonly $Stats: { [statName: string]: Stat; };
    get Stats(): { [statName: string]: Stat; } {
        return this.$Stats;
    }

}
```

it becomes:

```
class Race {

    private readonly $Stats: { [statName: string]: Stat; };
get Stats(): { [statName: string]: Stat; } {
    return this.$Stats;
}

}
```

The reason seems to be readonly combined with dictionary type variable.

ctrl+a & ctrl+alt+l (formatting by typescript formatter) works well though.

**Comment by prettydiff** [comment]
Please generate the debug.md file and paste that into a gist for us.

**Comment by radarsu** [comment]
https://gist.github.com/radarsu/53535a8397ebd1e9a3385f6ce91a1c56

**Comment by DanielJoyce** [comment]
Similar problem with square brackets inside generic types

It causes formatting of all subsequent lines to be off.
