### ISSUE TITLE
Unexpected number for output_tap_size error

### ISSUE THREAD

**Issue by FireAntJoe** [Glavin001/atom-beautify#948]
### Description

When I ran a C file through Beautify I got this weird error.

### Error
```
/tmp/116324-61374-ww7ib9.cfg:1 Expected a number for output_tab_size, got undefined /tmp/116324-61374-ww7ib9.cfg:2 Expected a number for input_tab_size, got undefined Parsing: /tmp/input116324-61374-17qhrfm as language C
/tmp/116324-61374-ww7ib9.cfg:1 Expected a number for output_tab_size, got undefined
/tmp/116324-61374-ww7ib9.cfg:2 Expected a number for input_tab_size, got undefined
Parsing: /tmp/input116324-61374-17qhrfm as language C
```

### Debug 

https://gist.github.com/FireAntJoe/6e30bec02de8b0532c1502168823747b

Ironically the same thing happened with a java file. If it matters I am using Ubuntu 14.04 64bit in a virtual box. It will do the beautify icon and such but jut gives that error when complete, so I am not even sure if it worked.

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by FireAntJoe** [comment]
Added it to the initial question.

**Comment by Glavin001** [comment]
I do not see `input_tab_size` mentioned in the debugging information at all. 
Everything in the debugging logs looks to be working as expected.

**Comment by FireAntJoe** [comment]
I indent one time, does that matter? So why does this occur when I beautify C code? Can you fully explain the error to me.

**Comment by Glavin001** [comment]
The error is being throw by Uncrustify, not Atom-Beautify.
You can create an Issue over at https://github.com/uncrustify/uncrustify if you need more explanation.

Here is my explanation of these error messages.

```
Expected a number for output_tab_size, got undefined
Expected a number for input_tab_size, got undefined
```

Atom-Beautify creates a configuration file for Uncrustify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/cfg.coffee#L12-L13

```coffeescript
  # Apply indent_size to output_tab_size
  options.output_tab_size = options.output_tab_size or options.indent_size # jshint ignore: line
  options.input_tab_size = options.input_tab_size or options.indent_size # jshint ignore: line
```

If `output_tab_size` and `input_tab_size` are `undefined` then that means `options.indent_size` must have been undefined.

Your [debugging information](https://gist.github.com/FireAntJoe/6e30bec02de8b0532c1502168823747b#final-options) shows the following options:

```json
{
    "indent_size": 2,
    "indent_char": " ",
    "indent_with_tabs": false,
    "configPath": "",
    "disabled": false,
    "default_beautifier": "Uncrustify",
    "beautify_on_save": false
}
```

Where `indent_size` is `2` and there is no error in the logs: https://gist.github.com/FireAntJoe/6e30bec02de8b0532c1502168823747b#logs
