### ISSUE TITLE
Installation Error( Windows 7  X64)

### ISSUE THREAD

**Issue by elicoyqf** [Glavin001/atom-beautify#950]
### Description

Installing atom-beautify fails, both through atom and in the command line. Error is the same both ways.
### Expected Results

Installing modules failed
npm WARN package.json Dependency 'handlebars' exists in both dependencies and de
vDependencies, using 'handlebars@^4.0.2' from dependencies
npm WARN engine analytics-node@2.1.0: wanted: {"node":">= 0.12.x"} (current: {"n
ode":"0.10.40","npm":"2.13.3"})
npm WARN engine typescript-formatter@2.1.0: wanted: {"node":">= 4.2.0"} (current
: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN optional dep failed, continuing cross-spawn@2.2.3
npm WARN optional dep failed, continuing fsevents@1.0.11
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"}
(current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN optional dep failed, continuing source-map@0.1.43
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Administrator\AppData\Local\atom\app-1.8.0-beta2\
resources\app\apm\bin\node.exe" "C:\Users\Administrator\AppData\Local\a
tom\app-1.8.0-beta2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "
--globalconfig" "C:\Users\Administrator\.atom\.apm\.apmrc" "--userconfig" "
C:\Users\Administrator\.atom\.apmrc" "install" "--target=0.36.8" "--arch=ia3
2"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\Administrator.atom.apm\lodash\3.10.1\package\package.js
on
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
# 

npm ERR! ^
npm ERR! File: C:\Users\Administrator.atom.apm\lodash\3.10.1\package\package.j
son
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

```
<INSERT CODE HERE>
```

C:\Users\Administrator.atom\packages>git clone https://github.com/Glavin001
m-beautify.git
Cloning into 'atom-beautify'...
remote: Counting objects: 5674, done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 5674 (delta 66), reused 0 (delta 0), pack-reused 5541
Receiving objects: 100% (5674/5674), 1.26 MiB | 666.00 KiB/s, done.
Resolving deltas: 100% (3523/3523), done.
Checking connectivity... done.

C:\Users\Administrator.atom\packages>cd atom-beautify

C:\Users\Administrator.atom\packages\atom-beautify>dir
 驱动器 C 中的卷没有标签。
 卷的序列号是 0EEA-3764

 C:\Users\Administrator.atom\packages\atom-beautify 的目录

2016/04/25  21:10    <DIR>          .
2016/04/25  21:10    <DIR>          ..
2016/04/25  21:10               212 .codoopts
2016/04/25  21:10            10,732 .csscomb.json
2016/04/25  21:10                56 .gitignore
2016/04/25  21:10               374 .jshintrc
2016/04/25  21:10               104 .mention-bot
2016/04/25  21:10                96 .npmignore
2016/04/25  21:10             2,213 .travis.yml
2016/04/25  21:10    <DIR>          appveyor
2016/04/25  21:10             4,085 appveyor.yml
2016/04/25  21:10             2,763 build-package.sh
2016/04/25  21:10            28,262 CHANGELOG.md
2016/04/25  21:10               189 coffeelint.json
2016/04/25  21:10             1,328 CONTRIBUTING.md
2016/04/25  21:10    <DIR>          docs
2016/04/25  21:10    <DIR>          examples
2016/04/25  21:10             1,395 ISSUE_TEMPLATE.md
2016/04/25  21:10    <DIR>          keymaps
2016/04/25  21:10             1,104 LICENSE.md
2016/04/25  21:10    <DIR>          menus
2016/04/25  21:10             4,760 package.json
2016/04/25  21:10               418 PULL_REQUEST_TEMPLATE.md
2016/04/25  21:10             8,077 README.md
2016/04/25  21:10    <DIR>          script
2016/04/25  21:10    <DIR>          spec
2016/04/25  21:10    <DIR>          src
2016/04/25  21:10    <DIR>          styles
              17 个文件         66,168 字节
              11 个目录 56,390,176,768 可用字节

C:\Users\Administrator.atom\packages\atom-beautify>apm install
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/...
#### How to create `debug.md` Gist

Note that this will include a copy of your code.
If your code is private, please create a different sample of code that reproduces the problem.
1. In the Atom [command-palette](https://atom.io/packages/command-palette), 
   search for and run the command `Atom Beautify: Help Debug Editor`. 
   The debugging results will be copied to your clipboard.  
2. Create a new Gist at https://gist.github.com/  
3. Create a file in your new Gist called `debug.md`.  
4. Paste your debugging results from Atom beautify into `debug.md` file in your Gist.  
5. Add a link to your Gist in your new Issue.
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
You need to `link` the cloned directory of Atom-Beautify.
See https://discuss.atom.io/t/manually-install-package/9251/21?u=glavin001 for details.

1. git clone and change into the directory
2. apm install
3. **apm link**

**Comment by elicoyqf** [comment]
the same installation, the previous version can be installed normally, the latest version can not be installed.

**Comment by Glavin001** [comment]
I recommend creating an issue over at https://github.com/atom/apm as it looks like there is a problem with installation of dependencies by `apm install`. Currently both Travis CI (Mac) and AppVeyor (Windows) are installing properly:
> apm install
Installing modules done

So I think there may be an issue with your `apm`. Hopefully the `apm` can help you with those issues. Please provide a link to this issue in your new issue over in the `apm` project, so other users who may experience this issue know where to go next and learn more. Thanks.

**Comment by mcarpenterjr** [comment]
@elicoyqf I'm running into a similar error, what's the specs on the windows machine you are using? I am starting to suspect it may have something to do with the cpu.
