### ISSUE TITLE
Please add support for .sh files (bash, sh, zsh, *sh, etc.)

### ISSUE THREAD

**Issue by TheSqrtMinus1** [Glavin001/atom-beautify#951]
That is all.

**Comment by fspafford** [comment]
I would also like to have support for bash files.

**Comment by ivanhuay** [comment]
+1

**Comment by lukeallister** [comment]
This would be great.

**Comment by Glavin001** [comment]
Bash is now supported: #451.

**Comment by fspafford** [comment]
Thank you!

**Comment by Glavin001** [comment]
Duplicate of https://github.com/Glavin001/atom-beautify/issues/451

Published to v0.29.15
