### ISSUE TITLE
format is not a function error

### ISSUE THREAD

**Issue by unclejustin** [Glavin001/atom-beautify#952]
### Description

Running beautify on typescript files throws error: format is not a function

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. throws error

### Debug

https://gist.github.com/unclejustin/43b2f5da21f9d42ecd9bd941e62230c6.

**Comment by Glavin001** [comment]
The Typescript formatter dependency has been updated. I recommend that you uninstall Atom-Beautify and do a clean install of Atom-Beautify and try again. Let me know if this does or does not resolve your issue. Thanks!

**Comment by unclejustin** [comment]
Reinstall did not solve my issue but quitting and restarting Atom did.

Note: This is for Atom 1.7.2 on OSX 10.11.4

Thanks @Glavin001 !

**Comment by Glavin001** [comment]
I recommend **always** reloading (or restarting) Atom after updating a package, as I find the dependencies are cached and cause problems more often than not.

Glad to hear it is working now for you!
