### ISSUE TITLE
Nested filename too long on Windows

### ISSUE THREAD

**Issue by steronydh** [Glavin001/atom-beautify#954]
I've found that the temporary folders created during install create filenames too long to put in the Recycle Bin and too long to shift-delete. I had to move some of the nested folders up a couple of levels to shorten their path length before I was able to delete them.

A very odd side effect: before I deleted the files manually, I ran Disk Cleanup and it reported over 1TB of data to delete from the temporary folder. After deleting the nested-too-deep folder, Disk Cleanup reported the correct size.

If this is a side effect of the nested-too-deep folders then it's a dangerous one!

**Comment by Glavin001** [comment]
Installation is handled by `apm`. I recommend you tell the Atom team over at https://github.com/atom/apm

**Comment by luisa123456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.
