### ISSUE TITLE
Using JS beautifier with .scpt file extension (supported by language-javascript-jxa)

### ISSUE THREAD

**Issue by RobTrew** [Glavin001/atom-beautify#957]
Is there a user setting that I can do this with ?

**Comment by prettydiff** [comment]
Just submit a pull request modifying the file: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee

Add the grammar name to the grammar array and the file extension to the extension array.

**Comment by RobTrew** [comment]
Thanks ! 
I've done that now.

**Comment by prettydiff** [comment]
https://github.com/Glavin001/atom-beautify/pull/960
