### ISSUE TITLE
ASCX beautify as HTML

### ISSUE THREAD

**Issue by jgarite** [Glavin001/atom-beautify#961]
### Description

There is no beautification available for ASCX files. 
### Expected Results

ASCX files are primarily HTML, so I would have expected the code to be beautified based on HTML syntax.
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Atom Beautify could not find a supported beautifier for this file

**Comment by aifrim** [comment]
I'd love one too. I have just started coding ascx files from a frontenders standpoint and from what I have tested by changing the language of the `.ascx` file:
- C# fails
- HTML fails
- ASP fails
- ASP HTML or HTML (ASP) fails

Autodetect has it at `Web Form/Control (C#)`.

**Comment by jgarite** [comment]
What I found works, for now, is changing the language to HTML. CTRL+SHIFT+L than select HTML. It works, but it’s not perfect because it breaks up the comments.

**Comment by aifrim** [comment]
@jgarite I have some <% %> tags at the beginning that define some information and after that HTML. When I beautify I end up having

    <% Long information line %>
        <% Long information line %>
            <% Long information line %>
                <% Long information line %>
                    <% Long information line %>
                        <div>
                             <div>
                                </div>
                                    </div>

You get my point.

**Comment by jgarite** [comment]
Yeah, that’s the one caveat with using that method. But until ASCX is put into beautification, that’s the best we can work with as far as I know. If you know or find otherwise, please let me know.

**Comment by aifrim** [comment]
I made my own workaround :)

- myfile.html
- myfile.ascx (contains only those definitions)

And I use gulp to `concat` them and create the myfile.ascx in the destination folder

**Comment by prettydiff** [comment]
Try changing the beautify to Pretty Diff in the HTML language settings in the Atom Beautify settings.  This seems to work correctly in Pretty Diff.

**Comment by jgarite** [comment]
Thanks. This does work better.
