### ISSUE TITLE
Colon and Equals aligment

### ISSUE THREAD

**Issue by steebchen** [Glavin001/atom-beautify#962]
Could a feature like [this](https://atom.io/packages/atom-alignment) be added to the Javascript beautifier? It really looks awesome and it would be helpful to have this in one single plugin.
So this:
```
var a = b;
var ab = c;
var abcd = d;
var ddddd =d;
```
becomes this:
```
var a     = b;
var ab    = c;
var abcd  = d;
var ddddd = d;
```
And the same for colons in JSON objects.

**Comment by prettydiff** [comment]
I am not sure if JS Beautify has this, but Pretty Diff does.  So just change your JavaScript beautifier in the Atom Beautify settings.  The Pretty Diff option that regulates this behavior is `vertical`.
