### ISSUE TITLE
can't update from Atom or APM

### ISSUE THREAD

**Issue by CanKer** [Glavin001/atom-beautify#966]
### Description
Hello, Atom is telling me the there is a new update 0.29.7, I have 0.29.1 and when I try to update from Atom or from APM (```sudo apm update atom-beutify```) I'm getting the next error
```
> spawn-sync@1.0.15 postinstall /private/tmp/apm-install-dir-11646-65147-2cvxdh/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


> fsevents@1.0.12 install /private/tmp/apm-install-dir-11646-65147-2cvxdh/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build


> atom-beautify@0.29.7 postinstall /private/tmp/apm-install-dir-11646-65147-2cvxdh/node_modules/atom-beautify
> node script/build-options.js


npm WARN engine typescript-formatter@2.1.0: wanted: {"node":">= 4.2.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine analytics-node@2.1.0: wanted: {"node":">= 0.12.x"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:844
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:844:23)
    at startup (node.js:58:13)
    at node.js:935:3
npm WARN optional dep failed, continuing cross-spawn@2.2.3
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-pre-gyp: command not found
npm WARN optional dep failed, continuing fsevents@1.0.12
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:844
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:844:23)
    at startup (node.js:58:13)
    at node.js:935:3
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/CanKer/.atom/.apm/.apmrc" "--userconfig" "/Users/CanKer/.atom/.apmrc" "install" "/private/tmp/d-11646-65147-ai69lc/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.7 postinstall: `node script/build-options.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.7 postinstall script 'node script/build-options.js'.
npm ERR! This is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/build-options.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/apm-install-dir-11646-65147-2cvxdh/npm-debug.log
```

Checklist 
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
> `sudo apm update atom-beautify`

Why are you using `sudo`? I never have to use `sudo` for `apm install` or `apm update`.

**Comment by CanKer** [comment]
maybe because I can't ``àpm install``` or ```apm update``` without ```sudo```, maybe some folder permissions...   does it that matters or have something to do with my problem?

**Comment by Glavin001** [comment]
Well the error is `Error: EACCES, permission denied` and I thought that `apm` installs within the user's personal directories so `sudo` should not be required, and if it is, then maybe indicates some problems / incorrectly setup file/folder permissions, that are now causing the `Error: EACCES, permission denied` error. Whenever I had to use `sudo` with `npm install` it *always* indicated an incorrect installation of node.js and npm and that permissions needed to be fixed.

I recommend you first speak with the `apm` team to confirm: https://github.com/atom/apm/issues
Currently installation is confirmed to work on both Mac (with Travis CI) and Windows (with AppVeyor) with a fresh and correctly setup installation, following the guidelines for Atom packages set by the Atom team: https://github.com/atom/ci
I encourage you to speak with the Atom team directly regarding `apm` and ensure you are properly set up.

**Comment by Glavin001** [comment]
I also see another error:
```
sh: node-pre-gyp: command not found
```

and in the logs:
> fsevents@1.0.12 install /private/tmp/apm-install-dir-11646-65147-2cvxdh/node_modules/atom-beautify/node_modules/remark/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

So `fsevents` package ( https://github.com/strongloop/fsevents ) may also be related because it uses `node-pre-gyp`. 

A quick search found https://github.com/mapbox/node-sqlite3/issues/474#issuecomment-120057820
Which reports:
> This will happen if you run as root.
