### ISSUE TITLE
How to configure atom-beautify package to format with babel/jsx javascript files?

### ISSUE THREAD

**Issue by damienleroux** [Glavin001/atom-beautify#974]
I'm new to Atom. And I need help on configuration. I post on [stackoverflow](https://stackoverflow.com/questions/37232310/how-to-configure-atom-beautify-package-to-format-with-babel-jsx-javascript-files) but without relevant answer, I seek for help here.

Thank you

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by damienleroux** [comment]
### Description

atom-beautify doesn't indent jsx code in javascirpt file

### Expected Results

atom-beautify should indent jsx as expected when indenting html code. see [language-babel](https://atom.io/packages/language-babel) that indent only jsx code ( not the jaascript around)

### Steps to Reproduce

1. Copy code from [this javascript file](https://github.com/damienleroux/react-grid-layout-builder/blob/master/src/bootstrapEditor.js): it's common javascript + jsx code
2. Format the file:all html tag (that is jsx code) doesn't indent as expected

Thank you for any advices :)

**Comment by Glavin001** [comment]
Hey @damienleroux. Thanks for elaborating 😃 .
I still need the `debug.md` Gist:
> More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thanks!

**Comment by rr20eid10** [comment]
In Atom, I tried to install and use this plugin, but after installation, I got an underscore.js module error.  I clicked the button to create an issue, but nothing happened, so I couldn't create an issue that way.  I'm doing a tutorial online and this plugin was recommended, but when looking at description, it doesn't list JSX files specifically.  Will JSX support be added to this plugin?

**Comment by Glavin001** [comment]
@rr20eid10 JSX should be supported now by JS-Beautify and Pretty Diff beautifiers.
