### ISSUE TITLE
Beautification not working on SASS after fresh install

### ISSUE THREAD

**Issue by Jimut** [Glavin001/atom-beautify#981]
### Description

I installed the plugin and applied it on some SASS code with all the default configs, it is just making all code end up in one line. 

But it was working fine with css files.
### Original Content

```
.container
    width:20px
    border:2px solid white
    z-index:100
```
### Expected Results

The beautified code should have looked like:

```
.container
    z-index: 100
    width: 20px
    border: 2px solid white
```
### Actual Result

```
.container width:20px border:2px solid white z-index:100
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/Jimut/c31deba490f7827782e44859a58c3a2c

I know that the debug information is saying that the original content was same, but I don't know why. I created a new sass file, wrote some code, saved it, run the beautify command and then clicked Debug Atom Beautify.

**Comment by wdetac** [comment]
I have the same problem too! After clean install Atom and Atom-Beautify, no matter how I change the settings, the code end up in one line.

**Comment by tearingItUp786** [comment]
I have also experienced the same issue. scss files beautify correctly but sass files all end up one line when I execute the beautify command

**Comment by Glavin001** [comment]
I see in the `debug.md` Gist at https://gist.github.com/Jimut/c31deba490f7827782e44859a58c3a2c#original-file-to-be-beautified that you are using Pretty Diff beautifier. You could try switching to another beautifier, such as `CSScomb` which supports SASS.

**Comment by Jimut** [comment]
I tried that it gives an error and the debug atom beautify option is not copying anything to the clipboard after that. So I copied the error.

Here is the gist
[https://gist.github.com/Jimut/4f5abc03e6978832bdda3d7efd6e7744](https://gist.github.com/Jimut/4f5abc03e6978832bdda3d7efd6e7744)

I tried it with many different sass code, it always gives error on the 3rd line, and when I wrote less than 3 lines, it was still showing error on the 3rd line, even when the 3rd line didn't exist.

**Comment by prettydiff** [comment]
Pretty Diff will not support this.  The original file does not contain curly braces to separate the selector from its properties and there are no semicolons to separate the properties from each other.

**Comment by Jimut** [comment]
So you are saying Pretty Diff will not support languages without semicolons and curly braces like SASS, JADE, Python etc?

**Comment by prettydiff** [comment]
@Jimut Yes, I am saying exactly that.  Pretty Diff will support the SCSS form of Sass though.
