### ISSUE TITLE
Setting dosen't work

### ISSUE THREAD

**Issue by skatpgusskat** [Glavin001/atom-beautify#982]
Even I changed the setting of atom-beautify, but it still dosen't change anything.
I changed indent from 4 to 2, and from 2 to 1, but nothing dosen't changed. it still just 4 indent.

**Comment by skatpgusskat** [comment]
wait. I just pressed post issue. still edit contents right now.

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.
