### ISSUE TITLE
!important will be removed

### ISSUE THREAD

**Issue by julmot** [Glavin001/atom-beautify#983]
### Description

When having the following code:

``` css
padding: 0 0 0 #{$numberWidth + ($navbarItemSpacing * 2)} !important;
```

the `!important` will be removed.
### Expected Results

The beautified code should have looked like:

```
padding: 0 0 0 #{$numberWidth + ($navbarItemSpacing * 2)} !important;
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

btw: Sorry, but I'm not going to create a gist for issues... If you need more information I'm willing to provide them in this issue.

**Comment by prettydiff** [comment]
Which beautify is being used?  I ran this code sample through Pretty Diff and it appeared to work fine:

    a{padding: 0 0 0 #{$numberWidth + ($navbarItemSpacing * 2)} !important;}

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.
