### ISSUE TITLE
php-cs-fixer found. but nothing happens; no code rewriting.

### ISSUE THREAD

**Issue by iz5clj** [Glavin001/atom-beautify#991]
### php-cs-fixer not working in windows.

The results of beautification are not what I expect. No results at all.
Nothing happens.
php-cs-fixer is found by atom beautify but the code remains as is.
If I run php-cs-fixer from the command line, everything works.
### Debug

Here is a link to the `debug.md` 
https://gist.github.com/iz5clj/2d2789ecd1eb73009b71181959f20314

**Comment by iz5clj** [comment]
Some good news:
php-cs-fixer is working: the file is being modified but not reloaded in atom!!
what am I missing?

thanks.

**Comment by romanstingler** [comment]
same here

**Comment by Glavin001** [comment]
I've been experiencing some weird file syncing issues with Atom lately, such as creating or renaming files and they do not appear in the Atom file tree. I wonder if a recently update of Atom has a bug in its file watcher that is causing it not to detect updates.

@iz5clj and @romanstingler I recommend you post up-to-date `debug.md` links that can help with debugging.

**Comment by dreamfalcon** [comment]
Same problem here.
But the file is not modified.

Just downloaded php-cs-fixer.phar to a folder and added the path in the atom-beautify PHP settings.
Click in in beautify, a loading image appears briefly but nothing happens..

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by dreamfalcon** [comment]
Found the problem looking ate the debug.
I was not including "php-cs-fixer.phar" in the path.
Its working a little slow but the file is modified and reloaded.
Thanks

**Comment by iz5clj** [comment]
Everything is working ok now.

- Downloaded the pfp-cs-fixer.phar file in a directory. (Ex: c:\mydir)

**Comment by sgehrman** [comment]
not working for me.  any one have more info to fix php in Atom?

**Comment by rohitkrishna094** [comment]
I tried including it in the path, also tried putting the absolute path to php-cs-fixer-v2.phar it in atom-beautify, but it just doesn't work. It also gives a warning saying that "The "PHP - PHP-CS-Fixer Path (cs_fixer_path)" configuration option has been deprecated. Please switch to using the option in section "Executables" (near the top) in subsection "PHP-CS-Fixer" labelled "Path" in Atom-Beautify package settings."

**Comment by rohitkrishna094** [comment]
Even after adding it to the executables' php-cs-fixer path, it's still not working.

**Comment by amperand** [comment]
Any updates here? I'm on ios and I have the executables php-cs-fixer path set

**Comment by gilad905** [comment]
This happened to me because of a different reason - `php-cs-fixer` failed fixing the file because `php -l` failed parsing the file.
This results in incorrect / no beautifying, but no error is shown in atom.
I found that out by typing `php-cs-fixer fix <filename>` from the command line.
