### ISSUE TITLE
support extension/grammer alias

### ISSUE THREAD

**Issue by creeperyang** [Glavin001/atom-beautify#992]
Hi, does `beautify` support extension alias?

I means something like below:

``` js
// maybe inside config file
{
  '.eslintrc': 'grammer-js' // means I want use js format to beautify file with extension '.eslintrc'
}
```

With this capability, many config files (json like) can be formatted easily.

Currently I can do this with setting file syntax. However it's nice to support extension alias.

**Comment by ccqgithub** [comment]
👍

**Comment by amitmarty** [comment]
👍

**Comment by Glavin001** [comment]
:+1: I think this would be a great idea for Atom's grammar selector! I think the language packages just need to be improved.
For example, see in https://github.com/atom/atom/blob/ff83e597530a41946fcae65e877924fc5b957191/spec/grammars-spec.coffee#L60 and https://github.com/atom/language-git/blob/643f81fe5f124cc1dc325b79899e8bd0f5cecb65/grammars/git%20config.cson#L4 the `.git/config` file is recognized as `Git Config`.

You could try changing https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L2
