### ISSUE TITLE
Space before opening brace on all functions JS

### ISSUE THREAD

**Issue by AugustinGrigorov** [Glavin001/atom-beautify#993]
Would it be possible to add an option for adding space before all functions not just anonymous ones for JavaScript as it's part of Standard JS?

**Comment by prettydiff** [comment]
Could you please include a minor code sample demonstrating exactly what you want?  This will ensure that I am focused on exactly what you need.

**Comment by drazisil** [comment]
```
function initServer () {

}
```

REF: https://github.com/feross/standard/blob/master/RULES.md
(Add a space before a function declaration's parentheses.)

**Comment by prettydiff** [comment]
I will probably make a new option for this.  Ideally the behavior would simply be folded into the existing `space` option, but this would break rules in a lot of various style guides.
