### ISSUE TITLE
Polymer 1.0 support

### ISSUE THREAD

**Issue by Renascienza** [Glavin001/atom-beautify#995]
### Description

On a Polymer 1.0 file (html + embeded JS), the beautifier is adding a space character on Strings, before the enclose quote. 
### Expected Results

Corect behavior: the beautifier can't never mess with strings content:

```
var myString = "Hello world";
//becomes
var myString="Hello world ";
//after beautifier run
```
### Steps to Reproduce
1. Add a polymer file to Atom editor, put a string literal on any function
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/...
#### How to create `debug.md` Gist

Note that this will include a copy of your code.
If your code is private, please create a different sample of code that reproduces the problem.
1. In the Atom [command-palette](https://atom.io/packages/command-palette), 
   search for and run the command `Atom Beautify: Help Debug Editor`. 
   The debugging results will be copied to your clipboard.  
2. Create a new Gist at https://gist.github.com/  
3. Create a file in your new Gist called `debug.md`.  
4. Paste your debugging results from Atom beautify into `debug.md` file in your Gist.  
5. Add a link to your Gist in your new Issue.
# Checklist
- [x ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
Please supply the required debug.md file as a Gist.  In order to troubleshoot the issue I need to know which beautifier you are using and which language grammar setting.
