### ISSUE TITLE
String Concatenation operator do not have a before and after spaces.

### ISSUE THREAD

**Issue by rainercedric23** [Glavin001/atom-beautify#996]
### Description

The concatenator operator "." do not have before and after spaces compare other operators like "+" and "-".
### Expected Results

The beautified code should have looked like:

```
// Expected result
$str = 'foo' . 'bar';

// Current Behavior
$str = 'foo'.'bar';
```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Checklist
- [/] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [/] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [/] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue

**Comment by prettydiff** [comment]
What language is this?

**Comment by Glavin001** [comment]
PHP I believe. 
http://php.net/manual/en/language.operators.string.php

**Comment by rainercedric23** [comment]
@prettydiff sorry, I didn't specify the language. Yes it's PHP.
