### ISSUE TITLE
Use native loading bar

### ISSUE THREAD

**Issue by sharifzadesina** [Glavin001/atom-beautify#999]
What about using atom native loading bar rather than loading popup?
![2016-06-01_16-28-06](https://cloud.githubusercontent.com/assets/15300551/15708803/19256748-2816-11e6-8362-849ecc08f4b1.png)

**Comment by Glavin001** [comment]
Is this built-in to Atom? This is great! I'd be happy to review and merge a Pull Request implementing this functionality. Thanks!
